import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: '6vui3xxze9',
  kicker: 'The Leadership',
  headline: `379 Labour MPs Back Burnham. Members Are Now Unlikely to Get a Vote`,
  standfirst: `Andy Burnham has finished the parliamentary stage of Labour's leadership election with 379 MP nominations out of a possible 403. His only nominal rival received one. Unless he fails the affiliate stage, Labour members will not get a leadership ballot — he will instead be formally declared leader at a special conference on Friday.`,
  publishedAt: '2026-07-15',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `Andy Burnham has finished the parliamentary stage of Labour's leadership election with 379 MP nominations out of a possible 403.` },
    { type: 'paragraph', text: `His only nominal rival, Catherine West, received one.` },
    { type: 'paragraph', text: `Unless Burnham now fails the party's affiliate stage, Labour members will not get a leadership ballot. He will instead be formally declared leader at a special conference on Friday.` },
    { type: 'paragraph', text: `The outcome had looked inevitable before nominations even opened.` },
    { type: 'paragraph', text: `Al Carns, the former Armed Forces Minister and the last potential challenger being seriously discussed at Westminster, ruled himself out on 8 July.` },
    { type: 'paragraph', text: `"I'd hoped a leadership contest would give us the opportunity for a proper debate."` },
    { type: 'paragraph', text: `Carns said months of internal Labour politics were not what the country needed and added: "Andy Burnham's earned this and he's got my full backing."` },
    { type: 'paragraph', text: `Labour's parliamentary nominations opened the following morning.` },
    { type: 'paragraph', text: `Candidates needed nominations from 20 per cent of the Parliamentary Labour Party. With 403 Labour MPs, that meant 81 nominations, not 80.` },
    { type: 'paragraph', text: `Burnham cleared the threshold immediately.` },
    { type: 'paragraph', text: `By the end of the first day, 322 Labour MPs had nominated him. That left exactly 81 MPs who had not, meaning another candidate was still mathematically capable of qualifying if every one of them united behind the same person.` },
    { type: 'paragraph', text: `One more Burnham nomination would end even that possibility.` },
    { type: 'paragraph', text: `It came.` },
    { type: 'paragraph', text: `By 13 July Burnham had 349 supporters. When nominations closed at 6pm today, his total stood at 379.` },
    { type: 'paragraph', text: `The remaining formal step is support from Labour-affiliated organisations.` },
    { type: 'paragraph', text: `Affiliate nominations opened at 6pm today and close at 6pm on Thursday. A candidate who has passed the parliamentary threshold needs nominations from at least three affiliates, including at least two trade unions.` },
    { type: 'paragraph', text: `If only one candidate is validly nominated, Labour's published timetable provides for a special conference on 17 July rather than a ballot of members and affiliated supporters. A contested ballot would not otherwise open until 6 August.` },
    { type: 'paragraph', text: `Burnham is therefore not yet Prime Minister.` },
    { type: 'paragraph', text: `Keir Starmer announced on 22 June that he would stand down as Labour leader and Prime Minister after mounting pressure within his party. He remains in office while Labour chooses his successor.` },
    { type: 'paragraph', text: `Once Labour has a new leader, Starmer can tender his resignation to the King. The monarch would then invite the person able to command the confidence of the Commons to form a government.` },
    { type: 'paragraph', text: `With Labour still holding a large parliamentary majority, that person would be Burnham.` },
    { type: 'paragraph', text: `No general election is constitutionally required.` },
    { type: 'paragraph', text: `There is precedent inside Labour too.` },
    { type: 'paragraph', text: `Gordon Brown became Labour leader unopposed in 2007 after receiving 313 MP nominations, leaving John McDonnell unable to reach the threshold required to stand. Brown was confirmed as leader at a special conference on 24 June and became Prime Minister on 27 June, three days later.` },
    { type: 'paragraph', text: `What is unusual about Burnham's succession is not that Britain can change prime minister without a general election.` },
    { type: 'paragraph', text: `It is how little of Labour's own leadership machinery has been needed to decide the result.` },
    { type: 'paragraph', text: `Burnham only returned to the Commons four weeks ago.` },
    { type: 'paragraph', text: `On 18 June he won the Makerfield by-election with 24,927 votes, 54.8 per cent of the total and a majority of 9,231 over Reform UK. It was his first return to the House of Commons since leaving Parliament in 2017 to become Mayor of Greater Manchester.` },
    { type: 'paragraph', text: `He had spent the intervening years building a political base outside Westminster.` },
    { type: 'paragraph', text: `Burnham won the Greater Manchester mayoralty in 2017 and was re-elected in 2021 and 2024. His return to Parliament immediately altered the balance inside Labour.` },
    { type: 'paragraph', text: `Four days after the Makerfield result, Starmer announced his resignation.` },
    { type: 'paragraph', text: `By the time formal leadership nominations opened on 9 July, most of the people who might have challenged Burnham had already decided not to.` },
    { type: 'paragraph', text: `Carns was the last significant holdout.` },
    { type: 'paragraph', text: `That has denied Labour the sort of leadership election in which competing candidates would have been forced to defend different plans for government before party members.` },
    { type: 'paragraph', text: `Burnham has set out a political direction.` },
    { type: 'paragraph', text: `He has proposed shifting more decision-making away from Westminster, expanding council and social housing, developing a new industrial strategy and creating a northern arm of Downing Street in Manchester.` },
    { type: 'paragraph', text: `He has said those plans would operate within Rachel Reeves's fiscal rules.` },
    { type: 'paragraph', text: `What he has not yet produced is a fully costed programme showing how much those ambitions would require or what would be cut, taxed or borrowed to pay for them.` },
    { type: 'paragraph', text: `In a contested leadership election, another candidate could have forced answers to those questions.` },
    { type: 'paragraph', text: `Labour members could then have chosen between them.` },
    { type: 'paragraph', text: `Instead, 379 MPs have made the decisive choice before the membership stage begins.` },
    { type: 'paragraph', text: `That is entirely within Labour's rules.` },
    { type: 'paragraph', text: `It is also why describing what is happening as a coronation is more than Westminster theatre.` },
    { type: 'paragraph', text: `Labour's members have a vote if there is a contest.` },
    { type: 'paragraph', text: `There is almost certainly not going to be one.` },
  ],
  evidence: {
    recordsReviewed: [
      `Labour Party, Leadership Election 2026 timetable and rules: establishes the 20 per cent PLP threshold, 9 to 15 July parliamentary nomination period, affiliate requirements and provision for a 17 July special conference where only one candidate is validly nominated`,
      `Labour Party, final leadership announcement: confirms Burnham ultimately received 379 Labour MP nominations`,
      `ITV News, 9 July 2026: records Al Carns withdrawing from consideration and endorsing Burnham, including his statement that he had hoped a leadership contest would allow a proper debate`,
      `Reuters, 22 June 2026: records Starmer's resignation announcement and the expected transition to a new Labour leader`,
      `UK Parliament, Makerfield by-election result, 18 June 2026: records Burnham's 24,927 votes, 54.8 per cent vote share and 9,231 majority`,
      `UK Parliament, Andy Burnham and Makerfield briefing: confirms Burnham's return to the Commons and the legal consequences for his Greater Manchester mayoralty`,
      `House of Commons Library, Labour leadership elections: records Gordon Brown's uncontested 2007 succession, his 313 MP nominations and the failure of John McDonnell to reach the required threshold`,
    ],
    lastChecked: '5 October 2026',
  },
};

export default piece;
