import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'ag7k4mxq9w',
  kicker: 'Accountability',
  headline: `Six Threat Cases Against Parliamentarians Should Have Brought Election Bans. None Did`,
  standfirst: `Six people prosecuted over threats against parliamentarians should have received five-year bans from standing for elected office, according to the Speaker's Conference examining the security of politicians. None did. The courts gave no recorded reasons for omitting the orders. Crown Prosecution Service records do not show whether the orders were considered.`,
  publishedAt: '2026-07-16',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `Six people prosecuted over threats against parliamentarians should have received five-year bans from standing for elected office, according to the Speaker's Conference examining the security of politicians.` },
    { type: 'paragraph', text: `None did.` },
    { type: 'paragraph', text: `The courts gave no recorded reasons for omitting the orders. Crown Prosecution Service records do not show whether the orders were considered. Four of the six defendants received restraining orders instead.` },
    { type: 'paragraph', text: `The penalty has existed since November 2023.` },
    { type: 'paragraph', text: `Under the Elections Act 2022, an adult convicted of specified offences can be disqualified from standing for, being elected to or holding most elected offices for five years where the court is satisfied that the offence was aggravated by hostility towards a candidate, elected office-holder or campaigner.` },
    { type: 'paragraph', text: `Once those conditions are met, the court must impose the order unless particular circumstances would make it unjust. If it decides not to impose one for that reason, it must explain why in open court.` },
    { type: 'paragraph', text: `The Speaker's Conference was told by the then Solicitor General, Lucy Rigby KC, about six recent cases in which an order should have been imposed. In a follow-up letter dated 8 August 2025, Rigby said the Director of Public Prosecutions had confirmed all six defendants met the legislative requirements for a disqualification order. None was made.` },
    { type: 'paragraph', text: `The Conference said no reasons had been given by the courts and the CPS's records did not establish whether disqualification had even been considered.` },
    { type: 'paragraph', text: `One CPS regional unit subsequently reminded prosecutors about the orders after a court failed to impose one in a case involving criminal damage to an MP's office.` },
    { type: 'paragraph', text: `The problem is particularly unusual because prosecutors are not normally required to apply for the sanction.` },
    { type: 'paragraph', text: `Current CPS guidance says that where the statutory conditions are satisfied the court must make the order unless doing so would be unjust. Prosecutors are nevertheless told to be alert to qualifying cases and to help the court with the evidence required.` },
    { type: 'paragraph', text: `The Conference concluded that the six cases suggested courts might be omitting the orders more widely.` },
    { type: 'paragraph', text: `It recommended that prosecutors should specifically draw them to courts' attention and that sentencing guidance should be amended so judges and magistrates know when they apply.` },
    { type: 'paragraph', text: `By March, the government had not established how often the orders were being used.` },
    { type: 'paragraph', text: `It said it was working with HM Courts and Tribunals Service to obtain the data and would decide how to publish it once that work was complete. It would then consider whether further guidance was needed for prosecutors, judges and magistrates.` },
    { type: 'paragraph', text: `The missing election bans sit inside a wider problem identified by the Speaker's Conference.` },
    { type: 'paragraph', text: `Britain has become considerably better at recording crimes reported against MPs than at showing what happens to those cases across the criminal justice system.` },
    { type: 'paragraph', text: `Later Freedom of Information disclosures from the National Police Chiefs' Council record 984 alleged crimes involving MPs in 2025, up from 905 in 2024, with a further 258 recorded between 1 January and 30 April 2026.` },
    { type: 'paragraph', text: `More than half of the 2025 total, 527, were recorded as malicious communications. There were 150 harassment offences and 53 reports classified as threats to kill. The figures cover alleged offences across all recorded classifications, not only threats, and are drawn from the Mercury and ECINS systems used by the Parliamentary Liaison and Investigation Team.` },
    { type: 'paragraph', text: `Those numbers describe reports to police. They do not show how many resulted in charges, convictions or particular sentences.` },
    { type: 'paragraph', text: `There is evidence that cases dealt with through Operation Bridger, the national policing system for protecting MPs away from Parliament, can produce better results than ordinary cases.` },
    { type: 'paragraph', text: `The Metropolitan Police told the Conference, in written evidence submitted separately from the Speaker's Conference's own report, that investment in Bridger had produced "better conviction rates in comparison with the general population".` },
    { type: 'paragraph', text: `For 2023–24 it also reported a higher rate of charge or summons outcomes, more cautions and other resolutions for malicious communications and harassment, fewer cases ending because of evidential difficulties and fewer in which the victim stopped supporting the investigation.` },
    { type: 'paragraph', text: `The Met did not publish the comparative conviction percentages in that evidence.` },
    { type: 'paragraph', text: `Its submission also acknowledged that the response to threats remained inconsistent across Britain's police forces. Different officers and forces could apply different thresholds when deciding whether conduct should be recorded as a crime or how it should be dealt with.` },
    { type: 'paragraph', text: `The Speaker's Conference reached the same conclusion.` },
    { type: 'paragraph', text: `It found significant inconsistency both between forces and within them. These offences are serious but relatively uncommon for individual officers, meaning someone investigating a threat against an MP may have little previous experience of a politically motivated case.` },
    { type: 'paragraph', text: `The problem continues when cases reach prosecutors.` },
    { type: 'paragraph', text: `Most criminal cases involving MPs are handled by the CPS's 14 regional teams. Chief Crown Prosecutors have to approve cases involving MPs personally, and reports are sent each month to senior CPS management. Particularly complex cases can be moved to central specialist lawyers.` },
    { type: 'paragraph', text: `The CPS told the Conference that this senior oversight was sufficient to produce consistent decisions.` },
    { type: 'paragraph', text: `The Conference could not establish whether that was true.` },
    { type: 'paragraph', text: `Although cases involving MPs are reported internally each month, the CPS does not collect structured data based on the victim's profession. It therefore cannot produce a national dataset showing all offences targeting politicians and what happened to them.` },
    { type: 'paragraph', text: `Justice minister Sarah Sackman KC accepted the problem during the inquiry.` },
    { type: 'paragraph', text: `She said the system needed to be able to track conviction rates, sentences and other outcomes.` },
    { type: 'paragraph', text: `The Conference recommended building what it called "full picture" data, following cases targeting elected officials from referral to the CPS through charging and sentencing, including the use of protective orders.` },
    { type: 'paragraph', text: `It also challenged the CPS's reliance on senior oversight.` },
    { type: 'paragraph', text: `"Consistent decision making is a function of expertise, not seniority," the report concluded.` },
    { type: 'paragraph', text: `It recommended a small specialist prosecution team dealing regularly with anti-democratic crimes and electoral law rather than leaving most cases to regional prosecutors who may encounter them rarely.` },
    { type: 'paragraph', text: `The government only partly accepted the recommendation on national data.` },
    { type: 'paragraph', text: `Its response in March said CPS management information existed for cases referred for charging decisions, but was compiled manually and depended upon individual prosecutors telling the central team that the victim was an elected official.` },
    { type: 'paragraph', text: `The government said that made the data insufficiently reliable for assessing the problem nationally and promised to consider other ways of building the dataset.` },
    { type: 'paragraph', text: `There has been more movement on the police side.` },
    { type: 'paragraph', text: `In March, Deputy Chief Constable Chris Balmer of Cambridgeshire Police was appointed as the National Police Chiefs' Council lead for defending democracy.` },
    { type: 'paragraph', text: `Every force now has a superintendent responsible for Operation Bridger. A further network of 66 Home Office-funded advisers operates through Operation Ford, which covers locally elected representatives as well as MPs.` },
    { type: 'paragraph', text: `A national Threat Assessment Centre has also been established to bring together intelligence about threats against local politicians.` },
    { type: 'paragraph', text: `Those changes may improve the police response without solving the problem further along the justice system.` },
    { type: 'paragraph', text: `In June, the Home Office was asked how many Operation Ford cases had resulted in investigations, arrests and charges.` },
    { type: 'paragraph', text: `It said it did not hold that information.` },
    { type: 'paragraph', text: `A second parliamentary answer that month asked how many offences the national operation had handled during the 2026 local elections.` },
    { type: 'paragraph', text: `Again, the Home Office said it did not collect the figure.` },
    { type: 'paragraph', text: `The difference between the two parts of the system is now unusually clear.` },
    { type: 'paragraph', text: `Police data can show that 984 alleged crimes involving MPs were recorded in 2025. It can show that 53 were classified as threats to kill and 527 as malicious communications.` },
    { type: 'paragraph', text: `The Met can say that Operation Bridger cases produce better charging and conviction outcomes than ordinary cases.` },
    { type: 'paragraph', text: `What the government still cannot publish is a national series showing how many of those cases were referred to prosecutors, how many were charged, how many ended in conviction, what sentences were imposed and whether the special sanctions Parliament created for political intimidation were used.` },
    { type: 'paragraph', text: `The six missing disqualification orders are one result of that gap.` },
    { type: 'paragraph', text: `The law required courts to impose the five-year sanction in qualifying cases unless doing so would be unjust, in which case reasons should have been given.` },
    { type: 'paragraph', text: `The Speaker's Conference was told of six cases where an order should have been imposed.` },
    { type: 'paragraph', text: `As of the government's March response, it was still trying to obtain the data needed to establish how often courts were using them.` },
  ],
  evidence: {
    recordsReviewed: [
      `House of Commons Speaker's Conference, The Speaker's Conference on the security of MPs, candidates and elections, Second Report, HC 1303, 27 October 2025, paragraph 139: the finding that in six recent cases an electoral disqualification order should have been imposed, that none was made, that no reasons were given by the courts and that CPS records did not establish whether the orders had been considered`,
      `House of Commons Speaker's Conference, HC 1303, paragraph 112: the Conference's conclusion that "consistent decision making is a function of expertise, not seniority" and its recommendation for a small specialist prosecution team, made after assessing the CPS's reliance on senior oversight and the absence of data showing whether that produces consistent outcomes`,
      `Lucy Rigby KC, then Solicitor General, letter to the Speaker's Conference, 8 August 2025: the underlying detail that the Director of Public Prosecutions identified six cases in which all defendants met the legislative requirements for a disqualification order, that none was made, that CPS records did not show whether the issue had been considered, and that four of the six defendants received restraining orders instead`,
      `Elections Act 2022, Part 5 and explanatory notes: the statutory conditions for a disqualification order, its five-year duration, the requirement for a court to impose it when the conditions are met unless doing so would be unjust, and the requirement to give reasons when the exception is used`,
      `Crown Prosecution Service, Sentencing: Ancillary Orders: current CPS guidance that prosecutors do not have to apply for an electoral disqualification order, but should identify relevant cases and assist the court with the evidential basis for making one`,
      `Metropolitan Police Service, written evidence SCS0047 to the Speaker's Conference, 24 April 2025: the Met's claim that Operation Bridger has produced "better conviction rates in comparison with the general population", and its 2023–24 findings of higher charge or summons outcomes and fewer evidential failures — the evidence does not provide the underlying comparative conviction percentages`,
      `National Police Chiefs' Council, Freedom of Information disclosure 2909/2026, 18 May 2026: 905 alleged crimes involving MPs in 2024, 984 in 2025 and 258 between 1 January and 30 April 2026, together with the 2025 offence breakdown of 527 malicious communications, 150 harassment offences and 53 threats to kill, drawn from Mercury and ECINS records accessible to the Parliamentary Liaison and Investigation Team`,
      `Speaker's Conference, Government Response, HC 1709, 5 March 2026: the government's partial acceptance of the recommendation for full criminal-justice data, its conclusion that existing manually compiled CPS information was not sufficiently reliable, continuing work to obtain data on electoral disqualification orders and plans for the Operation Ford Threat Assessment Centre`,
      `Home Office, Countering harassment and intimidation of elected representatives, 12 March 2026: the appointment of Chris Balmer as national policing lead for defending democracy, dedicated Operation Bridger coordinators in every force, the 66 Operation Ford advisers and creation of the national Threat Assessment Centre`,
      `Home Office parliamentary answers, 21 May and 15 June 2026: the department did not hold national figures for Operation Ford arrests, investigations and charges, or the number of offences handled during the 2026 local elections`,
    ],
    lastChecked: '4 October 2026',
  },
};

export default piece;
