import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'andy-burnham-the-record-behind-the-reputation',
  kicker: 'Labour Leadership',
  headline: `Andy Burnham: The Record Behind the Reputation`,
  standfirst: `Keir Starmer resigned as Labour leader on 22 June, four days after Andy Burnham won the Makerfield by-election with 54.8 per cent of the vote. Burnham is now the frontrunner to replace him. His record in Greater Manchester is more complicated than either his supporters or critics usually acknowledge.`,
  publishedAt: '2026-06-23',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `Keir Starmer resigned as Labour leader on 22 June, four days after Andy Burnham won the Makerfield by-election with 54.8 per cent of the vote and a majority of 9,231 over Reform UK.` },
    { type: 'paragraph', text: `Burnham is now the frontrunner to replace him.` },
    { type: 'paragraph', text: `He won Greater Manchester's mayoralty three times, taking 63.4 per cent of first preferences in 2017, 67.3 per cent in 2021 and 63.4 per cent of the vote in 2024. In Makerfield, he received 24,927 votes against Reform's 15,696.` },
    { type: 'paragraph', text: `An Ipsos poll conducted 5 to 9 June, before the by-election, found 26 per cent of Britons viewed him favourably and 33 per cent unfavourably, a net rating of minus seven. He was still the most popular current Labour politician tested and voters preferred him to Starmer as prime minister by 25 per cent to 12 per cent.` },
    { type: 'paragraph', text: `Burnham's strongest evidence of delivery is Greater Manchester's transport system.` },
    { type: 'paragraph', text: `The Bee Network completed bus franchising in January 2025, bringing decisions over 577 routes and around 1,600 buses under local control. Greater Manchester became the first area outside London to put its entire local bus network under franchising since deregulation in the 1980s.` },
    { type: 'paragraph', text: `The early results are measurable. Department for Transport guidance cites passenger numbers in the first franchised areas rising 14 per cent year on year and punctuality reaching 76 per cent, compared with about 66 per cent before franchising. Greater Manchester had already capped adult single bus fares at £2 in September 2022, saving around half the cost on some journeys, and introduced combined bus-and-tram tickets in September 2023 that it says made integrated travel around 20 per cent cheaper than buying the tickets separately.` },
    { type: 'paragraph', text: `That is not branding. Burnham used powers available to the mayor, faced opposition from incumbent operators and changed how a major public service is run.` },
    { type: 'paragraph', text: `Rail integration remains unfinished. Greater Manchester wants local rail services incorporated into the Bee Network later in the decade, but that depends partly on national rail reform. The buses are the delivered part.` },
    { type: 'paragraph', text: `His record on homelessness contains a clear broken promise.` },
    { type: 'paragraph', text: `Burnham took office in May 2017 promising to end rough sleeping in Greater Manchester by 2020. It was described by the combined authority as one of his top priorities. He admitted in 2019 that the target would be missed.` },
    { type: 'paragraph', text: `The official single-night count fell from 268 people in 2017 to 241 in 2018, 151 in 2019 and 125 in 2020. A Bed Every Night provided emergency accommodation and support to thousands of people, and the count kept falling after the missed deadline, reaching 89 in November 2021, the lowest figure since 2013.` },
    { type: 'paragraph', text: `It then rose for four consecutive years. By autumn 2025, the official snapshot recorded 197 people sleeping rough across Greater Manchester, more than double the 2021 figure and back above the 2018 level, though still below the 268 counted in 2017. The combined authority has attributed the recent rise partly to the freezing of Local Housing Allowance rates and increased evictions from the asylum system, trends it says have also affected other English regions.` },
    { type: 'paragraph', text: `The Clean Air Zone is the harder part of his record.` },
    { type: 'paragraph', text: `The original plan would have created a charging zone across almost 500 square miles of Greater Manchester. Charges proposed for non-compliant commercial vehicles ranged from £7.50 a day for taxis to £60 for buses and heavy goods vehicles.` },
    { type: 'paragraph', text: `The policy became deeply unpopular before it was due to begin in 2022.` },
    { type: 'paragraph', text: `But the simple version, that Burnham invented the scheme and abandoned it when protesters became loud enough, is not supported by the official record.` },
    { type: 'paragraph', text: `The ten Greater Manchester councils were under a legal direction from central government to bring nitrogen dioxide levels within statutory limits. A ministerial direction issued on 9 July 2019 specifically required a Class C charging Clean Air Zone, with compliance required by 2024 at the latest. Greater Manchester could not simply revoke or suspend it without the Secretary of State's approval.` },
    { type: 'paragraph', text: `Burnham nevertheless owned the local plan that was developed under that requirement and defended it while it was being prepared.` },
    { type: 'paragraph', text: `By late 2021, evidence gathered by Greater Manchester showed that pandemic-related supply shortages and inflation had driven the prices of some compliant commercial vehicles up by as much as 60 per cent. Burnham asked the government to pause the scheme, arguing that businesses could no longer afford the transition on the timetable originally assumed.` },
    { type: 'paragraph', text: `Defra agreed that conditions had changed. In February 2022 it said vehicle availability and second-hand prices meant the charging plan was unlikely to achieve compliance by the original deadline and allowed Greater Manchester to redesign it.` },
    { type: 'paragraph', text: `That does not make the abandoned work cost-free.` },
    { type: 'paragraph', text: `A Greater Manchester financial report published in January 2026 showed £210.9 million had been awarded by central government across the Clean Air Plan, of which £22.5 million had been returned. The remaining funding envelope was £188.4 million.` },
    { type: 'paragraph', text: `The same report put £41.6 million against implementation and operation of the proposed charging Clean Air Zone and £36.3 million against the wider development phase. It forecast total Clean Air Plan expenditure of £115.1 million by March 2026, including vehicle grants and charging infrastructure as well as work associated with the abandoned charging scheme.` },
    { type: 'paragraph', text: `It would therefore be wrong to call the entire £115.1 million wasted. Some spending funded cleaner vehicles and infrastructure that remained useful.` },
    { type: 'paragraph', text: `It would be equally wrong to pretend the reversal was free. Cameras were installed, signs erected, systems procured and contracts entered into for a charging scheme that never opened. Greater Manchester later had to negotiate contract changes and find alternative uses for equipment.` },
    { type: 'paragraph', text: `The replacement was not merely Burnham declaring his own scheme a success. On 30 January 2025, the Labour government approved a revised plan built around 117 new lower- and zero-emission buses and worth £86 million, concluding that this investment-led approach could meet legal air-quality limits faster than imposing charges. The replacement funds cleaner buses, taxis and traffic measures instead.` },
    { type: 'paragraph', text: `Burnham therefore has a legitimate defence for changing course. He also has to own the cost of reaching that point.` },
    { type: 'paragraph', text: `His time as Health Secretary presents another case where the criticism survives, but not in the form sometimes used against him.` },
    { type: 'paragraph', text: `The Healthcare Commission published its investigation into Mid Staffordshire NHS Foundation Trust in March 2009. Burnham became Health Secretary that June.` },
    { type: 'paragraph', text: `In July he appointed Robert Francis QC to conduct an independent inquiry into what had happened at Stafford Hospital. Burnham deliberately chose a non-statutory process rather than the full public inquiry being demanded by patients' families and MPs.` },
    { type: 'paragraph', text: `He defended that decision in Parliament in February 2010.` },
    { type: 'paragraph', text: `Burnham said he had considered a public inquiry but believed a lengthy and adversarial process could distract the hospital from improving care. The inquiry was designed primarily to examine what happened inside the trust and to hear from patients and their families. It did not have a remit to investigate fully how the wider regulatory and supervisory system had allowed the failures to continue.` },
    { type: 'paragraph', text: `That was a choice Burnham made.` },
    { type: 'paragraph', text: `The first Francis report then recommended a further investigation into the commissioning, supervisory and regulatory bodies surrounding the trust.` },
    { type: 'paragraph', text: `Burnham accepted that recommendation and commissioned a second, wider inquiry before Labour left office. After the 2010 election, Conservative Health Secretary Andrew Lansley converted that work into a statutory public inquiry under the Inquiries Act, giving it powers to compel witnesses and evidence.` },
    { type: 'paragraph', text: `So the strongest criticism is not that Burnham tried to prevent the systemic failures being examined. The evidence does not support that.` },
    { type: 'paragraph', text: `It is that when families were already demanding a full public inquiry, Burnham initially chose a narrower process held outside the statutory inquiry framework. Only after Francis's first investigation recommended examining the wider system did Burnham broaden the work.` },
    { type: 'paragraph', text: `His Hillsborough record went in the opposite direction.` },
    { type: 'paragraph', text: `In 2009, as Culture Secretary, Burnham announced the government's intention to waive the rules restricting disclosure of public records relating to the disaster. That process helped lead to Home Secretary Alan Johnson establishing the Hillsborough Independent Panel.` },
    { type: 'paragraph', text: `The panel eventually examined more than 450,000 pages of material. Its findings helped overturn the official account of the disaster and led ultimately to new inquests, where the 96 people then recognised as victims were found to have been unlawfully killed. A 97th victim, Andrew Devine, was formally recognised after his death in 2021.` },
    { type: 'paragraph', text: `Burnham did not single-handedly deliver Hillsborough justice. Families and campaigners had fought for it for decades, and Alan Johnson formally established the panel.` },
    { type: 'paragraph', text: `Burnham used his position in government to push their case when it mattered.` },
    { type: 'paragraph', text: `His confrontation with Boris Johnson's government over Greater Manchester's Tier 3 Covid restrictions strengthened the same political reputation.` },
    { type: 'paragraph', text: `In October 2020, Greater Manchester leaders said they needed at least £65 million to protect workers and businesses from the restrictions. The government offered £60 million. Negotiations collapsed over the final £5 million.` },
    { type: 'paragraph', text: `Burnham was highly visible in resisting Westminster. Whether that confrontation materially improved the eventual financial settlement is much harder to establish.` },
    { type: 'paragraph', text: `Burnham did not finish second in 2010 and fourth in 2015, as is sometimes stated.` },
    { type: 'paragraph', text: `He finished fourth in the 2010 contest, with 8.7 per cent in the first round, behind Ed Miliband, David Miliband and Ed Balls. In 2015 he finished second to Jeremy Corbyn with 19 per cent of the vote. Corbyn won outright with 59.5 per cent.` },
    { type: 'paragraph', text: `His latest route back to Westminster was plainly organised around his return.` },
    { type: 'paragraph', text: `Labour's NEC blocked him from seeking selection in the Gorton and Denton by-election, voting 8-1 against on 25 January, with only Deputy Leader Lucy Powell backing him. Labour subsequently lost the seat to Green candidate Hannah Spencer, who won 40.7 per cent against Labour's 25.4 per cent, with Labour pushed into third place behind Reform UK. Angela Rayner later said blocking Burnham had been a mistake.` },
    { type: 'paragraph', text: `In May, Makerfield MP Josh Simons resigned and said he was clearing a route for Burnham to return to Parliament. Other Labour candidates applied, but Burnham was the only person placed on the shortlist, so local Labour members did not choose between competing Labour candidates.` },
    { type: 'paragraph', text: `That process was engineered.` },
    { type: 'paragraph', text: `The election result was not.` },
    { type: 'paragraph', text: `Makerfield voters had 14 candidates in front of them. Burnham won 54.8 per cent and increased Labour's majority from 5,399 in 2024 to 9,231.` },
    { type: 'paragraph', text: `As of 23 June, Burnham is the clear frontrunner to replace Starmer. He has not yet published a full national leadership programme.` },
  ],
  evidence: {
    recordsReviewed: [
      `UK Parliament, Makerfield by-election result, 18 June 2026: confirms Burnham's 24,927 votes, 54.8 per cent share, 9,231 majority and 14-candidate field`,
      `Reuters, 22 June 2026: confirms Starmer's resignation and Burnham's position as the frontrunner to succeed him`,
      `Ipsos, national favourability and best-PM polling ahead of the Makerfield by-election, fieldwork 5-9 June 2026: supports Burnham's 26 per cent favourable, 33 per cent unfavourable rating, his standing as the most favourably viewed current Labour politician, and the 25 per cent to 12 per cent preference over Starmer as prime minister`,
      `Greater Manchester election records: supports Burnham's three mayoral victories in 2017, 2021 and 2024`,
      `Greater Manchester Combined Authority, Bus Franchising: confirms completion of full bus franchising on 5 January 2025, covering 577 routes and around 1,600 buses, and the September 2022 £2 fare cap and September 2023 AnyBus + Tram combined ticket`,
      `Department for Transport, bus franchising guidance: supports the Bee Network's 14 per cent patronage increase and 76 per cent punctuality figure, against about 66 per cent pre-franchising`,
      `Greater Manchester Combined Authority, rough sleeping single-night snapshot releases, 2017-2025: supports the 2020 count of 125, the November 2021 count of 89 (the lowest since 2013) and the subsequent four-year rise to 197 by autumn 2025, and Burnham's 2019 admission that the 2020 target would be missed`,
      `Ministry of Housing, Communities and Local Government, Rough Sleeping Snapshot, autumn 2025: provides the latest official snapshot available at the article date`,
      `Department for Environment, Food and Rural Affairs, Environment Act 1995 (Greater Manchester) Air Quality Direction 2019, 9 July 2019: establishes the legal requirement for a Class C charging Clean Air Zone and the 2024 compliance deadline`,
      `Defra and Greater Manchester Combined Authority, Clean Air Zone records, 2021 to 2025: establish the supply-chain evidence behind Burnham's pause request, the February 2022 Defra decision, and the 30 January 2025 approval of the £86 million investment-led replacement`,
      `Greater Manchester Air Quality Administration Committee, January 2026 expenditure report: supports the £210.9 million original award, £22.5 million returned, £188.4 million net funding envelope, £41.6 million allocated to CAZ implementation and operation expenditure and £115.1 million forecast total expenditure by March 2026`,
      `House of Commons Hansard, Mid Staffordshire NHS Foundation Trust, 24 February 2010: records Burnham's reasons for choosing a non-statutory first inquiry, its focus on the trust and patients, and his acceptance of Francis's recommendation for a wider second investigation`,
      `Mid Staffordshire NHS Foundation Trust Public Inquiry: confirms Francis recommended a wider investigation, Burnham accepted it and Lansley subsequently converted the second inquiry into a statutory public inquiry`,
      `Joint Committee on Human Rights, Human rights and the proposal for a Hillsborough Law: supports Burnham's 2009 role in pushing disclosure, the Panel's review of more than 450,000 pages, the 96 victims found unlawfully killed, and Andrew Devine's recognition as the 97th victim after his death in 2021`,
      `Greater Manchester Combined Authority and government statements on Tier 3 negotiations, October 2020: support the £65 million request, £60 million offer and the £5 million gap that ended talks`,
      `Commons Library, Labour leadership elections: confirms Burnham finished fourth in the 2010 contest with 8.7 per cent in the first round, and second in 2015 with 19 per cent of the vote to Jeremy Corbyn's 59.5 per cent`,
      `Reuters and Labour selection reporting, January and May 2026: confirms the NEC's 8-1 vote blocking Burnham from Gorton and Denton, the 26 February 2026 by-election result, Josh Simons' resignation to clear a route for Burnham, and that Burnham was the only candidate shortlisted by Labour for Makerfield`,
    ],
    lastChecked: '5 October 2026',
  },
};

export default piece;
