import type { EditorialEntry } from './types';

// Single-subject assessment of Andy Burnham's record against his reputation.
// Fact-checked against the same sources used for his MP biography (BBC, FT,
// Manchester Confidential, the Francis Report, Hillsborough inquiry findings).

const piece: EditorialEntry = {
  slug: 'andy-burnham-the-record-behind-the-reputation',
  kicker: 'Profile',
  headline: 'Andy Burnham: The Record Behind the Reputation',
  standfirst:
    'Tipped to lead Labour and the only major politician in Britain with positive favourability ratings. But does the record match the reputation?',
  publishedAt: '2026-06-23',
  authorByline: "The People's Chamber",
  body: [
    { type: 'paragraph', text: `Andy Burnham is the most talked about politician in Britain who has not yet been tested by the job everyone assumes he wants. He is widely expected to challenge Keir Starmer for the Labour leadership. He is described as "the only major politician in the country who enjoys positive favourability ratings." He won Makerfield on 18 June 2026 with 54.8 percent of the vote and a majority of 9,231 over Reform UK. He won three consecutive mayoral elections in Greater Manchester with 67 percent and 63 percent of the vote. The numbers suggest a politician with an extraordinary connection to voters that most of his contemporaries cannot match.` },
    { type: 'paragraph', text: `The question is whether the record matches the reputation.` },
    { type: 'paragraph', text: `Start with what he has delivered. The Bee Network franchised Greater Manchester's buses back under public control, the largest reversal of bus deregulation outside London since 1985. Tram and rail integration is planned by 2030. That is a measurable achievement. No other metro mayor in England has delivered transport reform on that scale.` },
    { type: 'paragraph', text: `His confrontation with Boris Johnson's government during the October 2020 Covid restrictions dispute was the moment that made him a national figure. He publicly refused the financial support offer for Greater Manchester communities facing Tier 3 restrictions, calling it inadequate. The standoff earned him the nickname "King of the North." Whether Greater Manchester ultimately received better terms as a result is debatable. That Burnham was the only regional leader willing to publicly fight the government is not.` },
    { type: 'paragraph', text: `The Hillsborough campaign remains the most significant thing he has done. In 2009, attending the 20th anniversary memorial as Culture Secretary, he was heckled by families of the 97 Liverpool fans killed in the crush at Sheffield Wednesday's ground in 1989. He launched a campaign for a new independent inquiry. The Hillsborough Independent Panel reported in 2012, establishing that police had altered statements and fabricated a narrative blaming fans. The 2016 inquest jury concluded that the 97 were unlawfully killed. Burnham fought to widen the inquiry until the truth came out. That fight lasted years and produced justice for families who had been ignored by every institution in the country.` },
    { type: 'paragraph', text: `Now look at what he has not delivered.` },
    { type: 'paragraph', text: `He pledged to end rough sleeping in Greater Manchester by 2020. In November 2019 he admitted he would miss the target. It has not been met. The "A Bed Every Night" scheme provided emergency accommodation. It did not solve the problem it was created to address. A pledge is a specific commitment with a specific deadline. This one was broken.` },
    { type: 'paragraph', text: `In 2020 he proposed the largest Clean Air Zone in Europe: charges of £7.50 to £60 a day on polluting vehicles across nearly 500 square miles. A Facebook protest group gained 50,000 members. Taxi drivers demonstrated outside town halls with signs bearing Burnham's face and the words "taxi trade killers." A sheep named Colin and a Shetland pony called Ernie were brought onto the number 471 bus between Bolton and Bury to highlight the impact on farms. Boris Johnson called the scheme "completely unworkable." Burnham backed down weeks before implementation in early 2022, calling it "a pre pandemic solution for a post pandemic world." The abandoned scheme cost taxpayers over £115 million. The total sum awarded by central government for the scrapped CAZ and its successor reached £211 million. The man who stood up to Johnson over Covid would not stand up to Facebook protesters over air quality. The "King of the North" was described as "the most unpopular person in Greater Manchester" during the Clean Air Zone crisis. He scrapped the policy when it became clear it would cost him votes.` },
    { type: 'paragraph', text: `His time as Health Secretary (2009 to 2010) carries the most uncomfortable question of all. At Mid Staffordshire NHS Foundation Trust, between 2005 and 2008, patients were left lying in their own waste, given the wrong medication, left without water and left to fall out of bed. Press reports estimated between 400 and 1,200 excess deaths. The Francis Report described "appalling and unnecessary suffering of hundreds of people" who were "failed by a system which ignored the warning signs." The Healthcare Commission published its devastating report in March 2009, three months before Burnham took office. But Burnham was the minister who decided what to do about it. In July 2009 he commissioned the first Francis inquiry. Its remit was deliberately narrow: it examined the trust, not the wider system. It did not ask why national supervisory bodies had missed warnings for years. The Cameron government later commissioned the full public inquiry with the broader remit Burnham had not given it. At Hillsborough he fought to widen an inquiry until the truth came out. At Mid Staffs he narrowed it. Both decisions were his.` },
    { type: 'pullQuote', text: `At Hillsborough he fought to widen an inquiry until the truth came out. At Mid Staffs he narrowed it. Both decisions were his.` },
    { type: 'paragraph', text: `He ran for the Labour leadership twice. He finished second to Ed Miliband in 2010 and a distant fourth behind Jeremy Corbyn in 2015. The 2015 campaign was widely regarded as directionless. In February 2026 the party's National Executive Committee blocked his candidacy for the Gorton and Denton by-election. The Green Party won the seat, breaking 95 years of continuous Labour representation. Angela Rayner later called the NEC's decision "a mistake." The path back to Parliament required Josh Simons to resign from Makerfield to create a vacancy. No other candidate made the shortlist. The return was engineered, not earned through open competition.` },
    { type: 'paragraph', text: `Writing in the Financial Times in May 2026, Stephen Bush observed that the policy offer Burnham was making as a prospective leader was to the left of what he had actually implemented during his mayoralty, which in turn was to the right of the stance of the Starmer government. He promises left. He governs centre. He proposes bold schemes and abandons them when they become unpopular. He pledges to end rough sleeping and misses the deadline. He commissions an inquiry and makes it too narrow to find the systemic answers.` },
    { type: 'paragraph', text: `Greater Manchester still faces housing pressures, health inequalities and economic disparities after nine years of his leadership. The combined authority budget exceeds £3 billion. The question is not whether Burnham has done more than most politicians. He has. The Bee Network exists. The Hillsborough families received justice. Three consecutive elections with margins above 50 percent is a record no other English politician outside London can match. The question is whether a man whose instinct when faced with serious opposition is to retreat, reframe and reposition is the right person to run a country where retreat is not an option.` },
    { type: 'paragraph', text: `Prime Ministers do not get to scrap their most important policy when a Facebook group reaches 50,000 members. They do not get to narrow the inquiry when the answers are uncomfortable. They do not get to promise left and govern centre without eventually being held to account for the gap. Burnham's favourability ratings are high because he has never been in a position where the country depended on him making an unpopular decision and holding his nerve. The Clean Air Zone suggests that when that moment arrives, he folds. Hillsborough suggests the opposite. Which version of Andy Burnham shows up is the only question that matters. The country will find out soon enough.` },
  ],
};

export default piece;
