import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'as6k2mwx9q',
  kicker: 'Immigration',
  headline: `£4.9bn on Asylum, and the Home Office Still Cannot Say How Many Failed Claimants Remain`,
  standfirst: `The Home Office and Ministry of Justice spent around £4.9 billion on the asylum system in 2024/25. A Public Accounts Committee report published in June found that the Home Office still cannot say with confidence how many failed asylum seekers remain in Britain — it knew where "some" were, but could not establish with certainty who had left the country and who was still here.`,
  publishedAt: '2026-07-14',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `The Home Office and Ministry of Justice spent around £4.9 billion on the asylum system in 2024/25.` },
    { type: 'paragraph', text: `The Home Office still cannot say with confidence how many failed asylum seekers remain in Britain.` },
    { type: 'paragraph', text: `That was one of the starkest findings in a Public Accounts Committee report published in June. MPs said the department knew where "some" failed asylum seekers were, but could not establish with certainty who had left the country and who was still here.` },
    { type: 'paragraph', text: `The committee said the system for monitoring failed asylum seekers required a complete overhaul.` },
    { type: 'paragraph', text: `Its finding sits alongside some genuine improvements elsewhere in the system.` },
    { type: 'paragraph', text: `The latest Home Office statistics available by 14 July show 93,525 people claimed asylum in the year ending March 2026, 12 per cent fewer than in the previous year. The number waiting for an initial decision fell to 48,758, down 55 per cent in a year and the lowest level since September 2019.` },
    { type: 'paragraph', text: `Returns have increased too.` },
    { type: 'paragraph', text: `There were 11,918 asylum-related returns in the year ending March 2026, 17 per cent more than a year earlier and the highest number in the Home Office's comparable series beginning in 2010. These include enforced and voluntary returns involving people who had made an asylum claim at some stage.` },
    { type: 'paragraph', text: `The system is therefore not simply deteriorating on every measure.` },
    { type: 'paragraph', text: `Its deeper problem is what happens when cases move from one part of the process to another.` },
    { type: 'paragraph', text: `The National Audit Office estimated that the Home Office and Ministry of Justice spent £4.9 billion on asylum in 2024/25. That figure does not include all costs borne by councils, which the auditors said could not be calculated reliably.` },
    { type: 'paragraph', text: `The largest component was asylum support.` },
    { type: 'paragraph', text: `The Home Office spent about £4 billion on support during the year. Around £2.7 billion was direct spending on accommodation. A wider £3.4 billion accommodation-and-support figure also included cash payments to asylum seekers and grants to councils for dispersal accommodation.` },
    { type: 'paragraph', text: `The Public Accounts Committee report itself uses both £2.7 billion and £3.4 billion in different passages. The underlying NAO breakdown shows why: £2.7 billion is direct accommodation expenditure; £3.4 billion covers accommodation and associated support.` },
    { type: 'paragraph', text: `The government has reduced some of that pressure.` },
    { type: 'paragraph', text: `At the end of March, 97,519 people were receiving asylum support, 9 per cent fewer than a year earlier. Of those, 20,885 were in hotels, down 35 per cent.` },
    { type: 'paragraph', text: `But clearing one backlog has repeatedly created another.` },
    { type: 'paragraph', text: `In 2023, the Home Office sharply increased initial asylum decisions in an attempt to clear older cases. The Public Accounts Committee found that this pushed more work into the appeals system, where around 70,000 people were waiting for an appeal decision and cases were taking close to 60 weeks to be heard.` },
    { type: 'paragraph', text: `The National Audit Office followed 5,000 people who had claimed asylum in January 2023.` },
    { type: 'paragraph', text: `By the time of its analysis, 41 per cent were still effectively in limbo. They had not been granted asylum, but their cases remained unresolved somewhere in the system. The group included failed asylum seekers as well as claims that had been withdrawn, suspended or otherwise remained open.` },
    { type: 'paragraph', text: `The government's information on people whose claims have definitively failed is weaker still.` },
    { type: 'paragraph', text: `The Home Office told the committee that the most recent published figure for failed asylum seekers in the system was just over 41,000 at the end of June 2023.` },
    { type: 'paragraph', text: `When MPs asked what had happened to those who had exhausted their appeal rights, officials said the department knew where "some of them" were. People who stopped complying with immigration bail conditions could be treated as absconders and traced by enforcement teams.` },
    { type: 'paragraph', text: `Officials also acknowledged that somebody could leave Britain without informing the Home Office, while somebody else could remain in the country without being detected.` },
    { type: 'paragraph', text: `A refused asylum claim therefore does not establish when somebody will leave Britain.` },
    { type: 'paragraph', text: `There may still be an appeal. Removal may be legally or practically impossible. A person may leave voluntarily without immediately being recorded as having done so. Others may disappear from contact.` },
    { type: 'paragraph', text: `The original version of this article cited a Home Office estimate that 55 per cent of people refused under new restrictions might remain in Britain.` },
    { type: 'paragraph', text: `That figure does not measure failed asylum seekers and should not be used that way.` },
    { type: 'paragraph', text: `It comes from the June 2026 impact assessment for the Immigration and Asylum Bill and relates specifically to people refused Article 8 family and private-life applications. The Home Office estimated, using a sample of 2022 cases, that about 55 per cent of those refused such claims might remain without legal status. It separately estimated that its Article 8 reforms could result in 11,700 additional refusals a year after appeals.` },
    { type: 'paragraph', text: `That is an immigration enforcement problem, but it is not evidence that 55 per cent of refused asylum seekers will remain.` },
    { type: 'paragraph', text: `The Public Accounts Committee found a more fundamental problem without needing that statistic.` },
    { type: 'paragraph', text: `Government departments still lack a single reliable view of people moving through the asylum system.` },
    { type: 'paragraph', text: `Information is spread between Home Office and Ministry of Justice systems, spreadsheets and local records. MPs said basic information including the number of absconders and repeated appeals was incomplete, inconsistent or unavailable.` },
    { type: 'paragraph', text: `Responsibility is split too.` },
    { type: 'paragraph', text: `The Home Office controls asylum decisions, support and removals. The Ministry of Justice oversees the tribunal system through which appeals pass. Local authorities deal with consequences ranging from housing pressures to people presenting as homeless after leaving Home Office accommodation.` },
    { type: 'paragraph', text: `The government has created a new asylum group within the Home Office and a cross-government asylum system board. It has also introduced the Immigration and Asylum Bill, including plans for a new independent appeals body intended to accelerate cases.` },
    { type: 'paragraph', text: `The Public Accounts Committee said those changes could help.` },
    { type: 'paragraph', text: `It also found that departments had still not agreed clear outcomes for the system as a whole or shown how the new structures would exercise authority when priorities conflict.` },
    { type: 'paragraph', text: `Accommodation illustrates the same problem.` },
    { type: 'paragraph', text: `MPs said councils still lacked a meaningful say over where asylum accommodation was placed. The Home Office told the committee it had improved engagement and introduced regional planning arrangements, but its previous commitment to give councils a greater role had been delayed until September 2026.` },
    { type: 'paragraph', text: `Stoke Heath in Shropshire provided a recent example.` },
    { type: 'paragraph', text: `The Home Office planned to use newly built homes at Dutton Close for asylum accommodation despite objections from Shropshire Council and residents about the rural location and access to services. After weeks of opposition, the Home Office withdrew the site from the asylum dispersal programme on 10 July.` },
    { type: 'paragraph', text: `That decision does not prove that every asylum accommodation proposal is imposed without consultation. It does show why councils have been asking for a meaningful role before locations are selected rather than after disputes begin.` },
    { type: 'paragraph', text: `The government's target is to reduce annual asylum spending by at least £1 billion by 2028/29 compared with 2024/25.` },
    { type: 'paragraph', text: `There is now evidence that fewer people are waiting for an initial decision, fewer supported asylum seekers are in hotels and more asylum-related returns are taking place.` },
    { type: 'paragraph', text: `The Public Accounts Committee's unresolved question sits further down the system.` },
    { type: 'paragraph', text: `It has instructed the Home Office to provide its best estimate of how many failed asylum seekers remain in Britain, what proportion it is still in contact with, how many it does not know the whereabouts of and how long it expects their removal to take.` },
    { type: 'paragraph', text: `As of 14 July, that estimate had not been published.` },
  ],
  evidence: {
    recordsReviewed: [
      `Committee of Public Accounts, An analysis of the asylum system, 5 June 2026: establishes the £4.9 billion Home Office and Ministry of Justice cost, weaknesses in end-to-end management, delays in appeals, incomplete data on failed asylum seekers and the committee's demand for a current estimate of how many remain in Britain`,
      `National Audit Office, An analysis of the asylum system, 10 December 2025: provides the detailed 2024/25 spending breakdown: around £4 billion in Home Office asylum support expenditure, £2.7 billion of direct accommodation spending and £3.4 billion covering accommodation and associated support; notes that the £4.9 billion system estimate excludes some council costs`,
      `Home Office, Immigration system statistics, year ending March 2026, published 21 May 2026: records 93,525 people claiming asylum, down 12 per cent; 48,758 awaiting an initial decision, down 55 per cent and the lowest level since September 2019; 97,519 people receiving asylum support, down 9 per cent; and 20,885 supported asylum seekers in hotels, down 35 per cent`,
      `Home Office, returns statistics, year ending March 2026: records 11,918 asylum-related returns, up 17 per cent on the previous year and the highest volume in the series beginning in 2010`,
      `Home Office, Immigration and Asylum Bill 2026: impact assessment, 30 June 2026: shows that the 55 per cent estimate concerns refused Article 8 family and private-life applicants, not refused asylum claims, and sets out the modelling behind the estimate`,
      `Shropshire Council, Dutton Close update, 10 July 2026: confirms that the Home Office withdrew the Stoke Heath development from the asylum dispersal programme following its review`,
    ],
    lastChecked: '5 October 2026',
  },
};

export default piece;
