import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'awsucrmvr1',
  kicker: 'Local Government',
  headline: `Council Tax Has Risen 66% Since 2010. The Bill Still Does Not Tell You Which Council Is Better Run`,
  standfirst: `The average Band D council tax bill in England was £1,439 in 2010/11. For 2026/27 it is £2,392 — an increase of £953, or 66 per cent in cash terms. The difference between areas is even larger: Dorset charges £2,765 and Wandsworth £1,028. But that £1,737 gap cannot sensibly be read as £1,737 worth of difference in council performance.`,
  publishedAt: '2026-06-23',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `The average Band D council tax bill in England was £1,439 in 2010/11.` },
    { type: 'paragraph', text: `For 2026/27 it is £2,392.` },
    { type: 'paragraph', text: `That is an increase of £953, or 66 per cent in cash terms. It is not an inflation-adjusted comparison. After being frozen nationally in 2011/12, the average Band D bill has risen in every financial year since. This year's increase is £111, or 4.9 per cent.` },
    { type: 'paragraph', text: `Where a household lives can make an even bigger difference.` },
    { type: 'paragraph', text: `The government's official figures put the average Band D bill in Dorset at £2,765 and Wandsworth at £1,028. The difference is £1,737 a year.` },
    { type: 'paragraph', text: `Those numbers are real. Treating them as a league table of council performance is not.` },
    { type: 'paragraph', text: `Dorset and Wandsworth do not have identical funding systems, tax bases or precepting authorities. The final bill can include money for a council, police, fire, a combined authority and parish or town councils. The services each authority is responsible for also differ.` },
    { type: 'paragraph', text: `Even the government now explicitly recognises that some councils can raise much more from their local tax base than others.` },
    { type: 'paragraph', text: `Its Fair Funding Review says the strength of a council tax base depends heavily on factors including historic house and land values and is generally not something councils themselves created. The new funding system attempts to compensate councils with weaker tax bases through central funding.` },
    { type: 'paragraph', text: `That makes council tax an awkward measure of value for money.` },
    { type: 'paragraph', text: `A high bill can reflect high spending, but it can also reflect a weak tax base, greater social care need, rural service costs, parish precepts or the way central funding has historically been distributed. A low bill does not automatically prove a council is more efficient.` },
    { type: 'paragraph', text: `The pressure to increase bills is nevertheless widespread.` },
    { type: 'paragraph', text: `For 2026/27, 274 of the 384 authorities covered by council tax referendum rules used the maximum increase available to them. Another 50 came close to the maximum. Seventeen made no change and four reduced their charge.` },
    { type: 'paragraph', text: `The limits are not the same for every type of authority.` },
    { type: 'paragraph', text: `Councils responsible for adult social care are normally allowed increases of just under 5 per cent without a referendum: up to 3 per cent for general spending and a further 2 per cent for adult social care.` },
    { type: 'paragraph', text: `District councils in two-tier areas operate under a different limit, generally 3 per cent or £5 at Band D, whichever permits the larger increase. Police and fire authorities have separate cash limits. Several financially distressed councils have been given higher limits for 2026/27.` },
    { type: 'paragraph', text: `The result is a system in which increases close to the permitted maximum have become routine, but describing that as every council automatically putting bills up by 5 per cent would be wrong.` },
    { type: 'paragraph', text: `Adult social care is a major reason the pressure exists.` },
    { type: 'paragraph', text: `Of the 153 authorities responsible for it, 142 used the full additional social care flexibility this year. The remaining 11 used some of it. None declined it entirely.` },
    { type: 'paragraph', text: `That additional 2026/27 precept is expected to raise £688 million and accounts for about £35 of the national average Band D bill.` },
    { type: 'paragraph', text: `That £35 should not be mistaken for the total amount of council tax supporting social care. Each year's increase becomes part of the following year's council tax baseline. The government says calculating the full cumulative amount attributable to social care would require reconstructing every council's decisions since the precept was introduced in 2016/17.` },
    { type: 'paragraph', text: `The underlying spending is much larger.` },
    { type: 'paragraph', text: `English local authorities have budgeted £28.7 billion for adult social care in 2026/27, excluding NHS transfers, and another £17 billion for children's social care.` },
    { type: 'paragraph', text: `Together those two services account for about £45.7 billion of planned net service expenditure. Across all local authorities and single-purpose bodies covered by the government statistics, adult social care represents 19 per cent of service expenditure and children's social care another 11 per cent.` },
    { type: 'paragraph', text: `That is one reason judging a council mainly by potholes, bin collections or the appearance of a town centre can give a distorted impression of where its money goes.` },
    { type: 'paragraph', text: `A large share is spent on services most residents do not encounter routinely: residential care, home support for disabled and elderly adults, children's placements, safeguarding and help for families in crisis.` },
    { type: 'paragraph', text: `That does not make questions about visible services illegitimate. It helps explain why higher council tax does not necessarily result in cleaner streets or faster planning decisions.` },
    { type: 'paragraph', text: `Council tax also does not fund local government on its own.` },
    { type: 'paragraph', text: `For 2026/27, councils budgeted £151.3 billion of revenue expenditure. Central government grants are expected to finance about 54.5 per cent of that total, council tax about 30.9 per cent, with most of the remainder coming from retained business rates and other sources.` },
    { type: 'paragraph', text: `The bill arriving through the letterbox is therefore only one part of a much larger funding system.` },
    { type: 'paragraph', text: `That system has come under increasingly visible financial strain.` },
    { type: 'paragraph', text: `Since 2018, seven English local authorities have issued Section 114 reports saying they could not balance their budgets. Northamptonshire, Croydon, Slough, Thurrock, Woking, Birmingham and Nottingham have all done so, with Croydon and Nottingham issuing more than one.` },
    { type: 'paragraph', text: `Calling that bankruptcy is convenient shorthand but legally wrong.` },
    { type: 'paragraph', text: `Councils cannot go bankrupt in the way a company can. A Section 114 report means the chief finance officer believes forecast expenditure cannot be met from available resources. New spending is then heavily restricted while the authority deals with the deficit.` },
    { type: 'paragraph', text: `Nor did all seven councils fail for the same reason.` },
    { type: 'paragraph', text: `Commercial borrowing played a major role in some. Woking accumulated more than £2 billion of debt after years of property investment. Thurrock suffered huge losses from investments including renewable energy businesses. Reviews of Slough and Woking identified serious accounting and financial-management failures.` },
    { type: 'paragraph', text: `Other pressures are systemic.` },
    { type: 'paragraph', text: `The National Audit Office found in 2025 that 42 councils had received more than £5 billion of Exceptional Financial Support. That generally does not mean Whitehall simply handed them £5 billion. The mechanism largely allows councils to use capital receipts or borrowing to meet day-to-day spending that would normally have to be financed from revenue.` },
    { type: 'paragraph', text: `The government has since changed the funding formula and introduced a three-year settlement.` },
    { type: 'paragraph', text: `Its Fair Funding Review 2.0 is the first major reassessment in years of how differences in local need and councils' ability to raise tax should affect central funding. The government itself said the previous system relied on outdated formulas and that authorities it considered disadvantaged had tended to increase council tax further.` },
    { type: 'paragraph', text: `That acknowledgement complicates the usual argument that high council tax simply means a council is badly run.` },
    { type: 'paragraph', text: `Some councils plainly have been badly run. The Section 114 investigations provide evidence of poor investment decisions, weak controls and accounting failures.` },
    { type: 'paragraph', text: `But a council can also levy a high bill because it has expensive statutory responsibilities and fewer high-value properties over which to spread the cost.` },
    { type: 'paragraph', text: `The tax base itself is built on an increasingly peculiar foundation.` },
    { type: 'paragraph', text: `Every home in England is placed into one of eight council tax bands according to what it would have been worth on 1 April 1991. A house built this year is assigned a hypothetical 1991 value.` },
    { type: 'paragraph', text: `Band D still means a property judged to have been worth between £68,001 and £88,000 thirty-five years ago.` },
    { type: 'paragraph', text: `That matters when comparing areas whose property markets have moved very differently since 1991.` },
    { type: 'paragraph', text: `It also helps explain why the £1,737 gap between Dorset and Wandsworth cannot sensibly be read as £1,737 worth of difference in council performance.` },
    { type: 'paragraph', text: `There is evidence of pressure on services. An industry survey of council highway departments published this year found 16 per cent of the local road network in England and Wales was reported to have less than five years of structural life remaining, despite higher maintenance budgets. The estimated backlog of carriageway repairs reached £18.6 billion. Those figures come from the Asphalt Industry Alliance's survey rather than a government inspection of every road, but they demonstrate the scale of the maintenance problem councils themselves are reporting.` },
    { type: 'paragraph', text: `Measuring whether households receive value for council tax therefore requires more than ranking the size of the bill.` },
    { type: 'paragraph', text: `It means separating the money controlled by the billing council from police, fire, county and parish precepts. It means comparing authorities with the same responsibilities. It means allowing for social care need, tax base and central funding before deciding that one council charging £2,600 is less efficient than another charging £1,800.` },
    { type: 'paragraph', text: `It also means measuring actual outcomes: road condition, planning times, children's services inspections, adult social care performance, complaints, reserves, debt and audit findings.` },
    { type: 'paragraph', text: `The government is now redesigning the funding system partly because it accepts that councils have very different abilities to raise money from the same tax.` },
    { type: 'paragraph', text: `The tax itself is still being calculated from property values fixed on 1 April 1991.` },
  ],
  evidence: {
    recordsReviewed: [
      `Ministry of Housing, Communities and Local Government, Council Tax levels set by local authorities in England 2026 to 2027: supports the £2,392 national Band D average, £2,765 Dorset and £1,028 Wandsworth figures, 4.9 per cent annual increase, the 274/50/17/4 referendum-compliance breakdown, and the 142/11/0 adult social care precept breakdown, £688 million additional revenue and £35 Band D contribution`,
      `Department for Communities and Local Government, historic council tax statistics, including Council Tax levels set by local authorities in England 2011 to 2012: supports the £1,439 average Band D bill in 2010/11 and the national freeze in 2011/12`,
      `Ministry of Housing, Communities and Local Government, Local authority revenue expenditure and financing: 2026-27 budget: supports the £28.7 billion adult social care and £17.0 billion children's social care budgets, the £151.3 billion total revenue expenditure, the 54.5 per cent/30.9 per cent financing split, and the 19 per cent/11 per cent service-expenditure shares`,
      `Ministry of Housing, Communities and Local Government, Fair Funding Review 2.0 and resources-adjustment technical note: supports the government's assessment that councils have different tax-raising capacities, the role of historic property values and the new equalisation approach`,
      `House of Commons Library, Why are local authorities going 'bankrupt'? and What happens if a council go bankrupt?: supports the list of Section 114 authorities since 2018 and explains why a Section 114 report is not legally a bankruptcy`,
      `National Audit Office, Local government financial sustainability, February 2025: supports the finding that seven authorities had issued ten Section 114 reports since 2018 and that 42 councils had received more than £5 billion of Exceptional Financial Support`,
      `Ministry of Housing, Communities and Local Government, local government investment reforms, May 2026: supports the government statement that Woking accumulated more than £2 billion of debt and the subsequent move towards stronger monitoring of council borrowing and investment`,
      `Valuation Office Agency, council tax valuation guidance: confirms that English council tax bands remain based on property values at 1 April 1991, including notional 1991 valuations for homes built later`,
      `Asphalt Industry Alliance, ALARM Survey 2026: supports the survey finding that 16 per cent of the local road network in England and Wales was reported to have less than five years of structural life remaining and the £18.62 billion estimated repair backlog`,
    ],
    lastChecked: '5 October 2026',
  },
};

export default piece;
