import type { EditorialEntry } from './types';

// Launch editorial for The People's Chamber council rankings series.
// Every figure independently fact-checked against non-partisan sources
// (MHCLG / GOV.UK council tax statistics, House of Commons Library,
// Institute for Government, Asphalt Industry Alliance ALARM survey).

const piece: EditorialEntry = {
  slug: 'awsucrmvr1',
  kicker: 'Reading the Record',
  headline: 'The Council Tax Problem',
  standfirst:
    'Council tax has risen every year for over a decade, now £2,392 on average and as much as £2,765 a year. What has the increase actually bought?',
  publishedAt: '2026-06-23',
  authorByline: "opengovt",
  body: [
    { type: 'paragraph', text: `Council tax was supposed to be local. It was supposed to be visible. It was supposed to create a direct relationship between taxpayers and the services they received in return. Instead, it has become one of the most frustrating bills in modern Britain and one of the least scrutinised.` },
    { type: 'paragraph', text: `In 2010/11, the average Band D council tax bill in England was £1,439. In 2026/27 it reached £2,392. That is a 66 percent increase in 16 years. The bill has risen every single year for over a decade. In Dorset it climbed to £2,765, the highest in the country. In Wandsworth it remained just £1,028. Two households living in the same nation, under the same government, paying into the same public service model, face council tax bills separated by £1,737 a year. The gap between the cheapest and most expensive council is 169 percent. That is not a policy difference. That is two countries sharing a tax system.` },
    { type: 'paragraph', text: `Every spring, millions of households receive another letter informing them that council tax is rising again. The explanations are familiar. Social care costs are increasing. Inflation is putting pressure on budgets. Government funding remains tight. In 2025/26, 295 of the 384 councils subject to referendum principles used the maximum flexibility available to them. Only eight made no increase or reduced their bills. Councils can raise council tax by up to 5 percent a year, 3 percent core increase plus a 2 percent adult social care precept, without holding a local referendum. The cap is low enough to sound like a constraint and high enough that almost everyone rises to meet it. In practice, it guarantees that bills climb by close to 5 percent every year with no public vote required.` },
    { type: 'paragraph', text: `The bill rises. The services often feel as though they are standing still.` },
    { type: 'paragraph', text: `Social care is the engine of the increase and the excuse for it. Adult social care is the single largest item in an upper tier council's budget, and together with children's services it accounts for around two thirds of what county and unitary authorities spend. The social care precept added £34 to the average Band D bill in 2025/26. Of the 153 authorities responsible for adult social care, 147 used the full precept available to them and the remaining six used part of it. Every council that could charge more for social care did. The money is needed. The question is whether residents know how much of their bill is being driven by services most of them will not use until they are old, and whether they have any meaningful say in the matter.` },
    { type: 'paragraph', text: `Meanwhile, several councils have not just struggled. They have collapsed. Northamptonshire. Croydon. Slough. Thurrock. Woking. Birmingham. Each issued Section 114 notices, the local government equivalent of declaring bankruptcy. Between them they accumulated more than £5 billion in debt and deficit. Some faced government intervention. One, Northamptonshire, was abolished entirely and replaced by two new unitary authorities. These are not obscure rural districts. Birmingham is the largest local authority in Europe. Thurrock lost hundreds of millions on a single investment strategy. Croydon issued three Section 114 notices in two years. The residents of those areas are still paying the consequences through higher bills and reduced services. The councils that failed are also the councils that were supposed to be held accountable by the same system that failed to prevent the crisis.` },
    { type: 'paragraph', text: `Roads provide the most visible symptom. An estimated 16 percent of the local road network is reported to have less than five years of structural life remaining. Potholes remain a permanent feature of local politics. Housing waiting lists affect hundreds of thousands of households. Planning delays frustrate residents and businesses. Waste collection disputes dominate local news cycles. None of these problems are unique to a single authority. All of them shape public perceptions of value.` },
    { type: 'paragraph', text: `The frustration is not necessarily that council tax is high. The frustration is that the relationship between cost and performance appears invisible. Parents can compare school performance. Patients can compare hospital waiting times. Consumers can compare almost any product they purchase. Comparing councils remains far harder. The information exists, scattered across audit reports, government datasets, inspectorate findings and financial statements that few residents have the time or patience to read. The result is a strange form of accountability. Authorities can increase bills year after year while residents struggle to determine whether services are improving, declining or surviving.` },
    { type: 'paragraph', text: `Most residents understand that social care is expensive. Most understand that inflation increases costs. Most understand that councils do not control every factor affecting their budgets. What they increasingly struggle to understand is why the bill rises seem automatic while improvements feel optional.` },
    { type: 'paragraph', text: `If a household is paying £2,392 a year in council tax and their roads are potholed, their planning applications take months and their bins are collected less often than they were five years ago, they are entitled to ask what the 66 percent increase since 2010 actually bought.` },
    { type: 'paragraph', text: `That is why opengovt is launching a series of council rankings examining not only who charges the most, but who delivers the most. The most expensive councils. The most indebted councils. The councils receiving the most complaints. The councils providing the best value. The councils delivering the least despite charging the most. Good councils should not be hidden among poor ones. Poor councils should not be protected by complexity.` },
    { type: 'paragraph', text: `Council tax is no longer a minor local charge. For many households it is one of the largest bills they pay all year, rivalling energy costs and approaching mortgage payments. A system that charges residents up to £2,765 a year, rises by close to 5 percent annually without a public vote, funds a social care system most working age taxpayers rarely see, and has produced at least six effective bankruptcies in the last eight years is a system that has earned the scrutiny it is about to receive.` },
  ],
};

export default piece;
