import type { EditorialEntry } from './types';

// Each MP added one at a time and fact-checked against public sources
// (BBC, Guardian, FT, Standards Committee findings, Hansard, court
// reports) before the entry is committed to this file.

const piece: EditorialEntry = {
  slug: 'biggest-westminster-scandals-among-serving-mps-2026',
  kicker: 'Investigation',
  headline: 'The biggest Westminster scandals among serving MPs, 2026',
  standfirst:
    'The MPs who broke the rules, the law or the trust of their constituents, and are still in the Commons. Compiled from Standards Committee findings, criminal records, registered interests disputes and published investigations. Each entry independently fact-checked.',
  publishedAt: '2026-06-08',
  authorByline: "The People's Chamber",
  body: [
    {
      type: 'mpEntry',
      rank: 1,
      name: 'Rupert Lowe',
      memberId: 5158,
      party: 'Restore Britain',
      topLine: 'Suspended by Reform UK: March 2025. KC report 25 March 2025 found credible evidence of unlawful harassment of two women. High Court refused to halt the parliamentary investigation, 14 May 2026.',
      paragraphs: [
        "Rupert Lowe was elected MP for Great Yarmouth on 4 July 2024 as one of five Reform UK MPs in the party's first Westminster breakthrough. He took the seat from the Conservatives with 14,385 votes against Labour's Keir Cozens on 12,959, a majority of 1,426 in a constituency Brandon Lewis had held for the Conservatives since 2010. Within eight months Lowe had been suspended from Reform UK. Within a year he had founded a rival party. He now sits as the sole MP for Restore Britain, a party that did not exist when he entered Parliament.",
        'In December 2024 an incident allegedly involving verbal threats against Reform UK chairman Zia Yusuf was referred to the Metropolitan Police for assessment. Separately, two female employees, one in Lowe\'s parliamentary office and one in his constituency office, brought complaints of bullying and discriminatory behaviour. Reform UK suspended Lowe in March 2025 and instructed Jacqueline Perry KC to investigate. Perry\'s report, published 25 March 2025, concluded there was "credible evidence of unlawful harassment of two women by both Mr Lowe and male members of his team". Both complainants resigned within months of starting, saying they believed they would have been sacked otherwise. Lowe denied all allegations, called the process a "political assassination" and stated publicly that Nigel Farage "must never become prime minister".',
        'On 23 July 2025 the Independent Complaints and Grievance Scheme, Parliament\'s internal misconduct body, commenced a formal investigation. Lowe applied to the High Court for judicial review to halt it, arguing procedural unfairness, perversity and illegality. The preliminary hearing was held on 17 March 2026 before Mr Justice Chamberlain, who handed down judgment on 14 May 2026 in R (Lowe) v ICGS [2026] EWHC 1163 (Admin). The Court held that the matter lay outside its jurisdiction: the ICGS investigation falls within the exclusive cognisance of the House of Commons and is protected by parliamentary privilege. The internal investigation can now proceed.',
        'While fighting the parliamentary investigation Lowe set up his own political operation. Restore Britain was founded on 30 June 2025 as a pressure group, announced as a political party on 13 February 2026, and formally registered with the Electoral Commission on 20 March 2026. By June 2026 it claimed more than 96,000 members and a single MP, Lowe himself. He has positioned the party to the right of Reform UK on immigration, drawing some interest from Elon Musk in early 2026. He defends his 1,426 majority in Great Yarmouth under a party banner that did not exist eighteen months ago, while a parliamentary misconduct investigation his lawyers failed to stop continues against him.',
      ],
      verdict: 'A serving MP who lost a workplace harassment finding, lost his party, lost his attempt to stop Parliament investigating him, and now sits for a party of one in a constituency he holds by 1,426 votes.',
    },
    {
      type: 'mpEntry',
      rank: 2,
      name: 'Angela Rayner',
      memberId: 4356,
      party: 'Labour',
      topLine: 'Resigned: 5 September 2025. Independent ethics adviser found she had breached the Ministerial Code over a £40,000 stamp duty underpayment. HMRC concluded the underpayment was neither careless nor deliberate and imposed no penalty, 14 May 2026.',
      paragraphs: [
        "Angela Rayner served as Deputy Prime Minister and Secretary of State for Housing, Communities and Local Government from July 2024 until her resignation on 5 September 2025. She was forced out after the Prime Minister's independent ethics adviser found she had breached the Ministerial Code over a £40,000 stamp duty underpayment on a seaside flat. She had spent years attacking Conservative ministers for precisely the kind of tax arrangements that ended her own time in government.",
        'The first storm came in 2024 over the 2015 sale of a former council house on Vicarage Road in Stockport. Rayner had bought the property in 2007 under the Right to Buy scheme with a 25 percent discount and sold it eight years later for a £48,500 profit. Questions over whether the house was her principal residence at the time of sale, which would have determined the capital gains tax position, intensified after Lord Ashcroft\'s unauthorised biography alleged discrepancies following her 2010 marriage to Mark Rayner, who owned a separate property on Lowndes Lane. Greater Manchester Police, HMRC and Stockport Council all investigated. In May 2024 GMP concluded that "no further police action will be taken". HMRC and the council took no further action either. Rayner had promised to resign if found guilty of any criminal offence. She was not.',
        'In May 2025 Rayner paid £30,000 in stamp duty on an £800,000 flat in Hove, classifying it as her primary residence. Had the flat been classified as a second home, the correct duty would have been £70,000. The classification turned on the status of her family home in Ashton-under-Lyne, which had been transferred into a trust established by court order for her severely disabled son following an NHS settlement linked to his premature birth. Her name had been removed from the Ashton-under-Lyne deeds during her divorce, but she had described the property as her primary residence in other contexts. The Telegraph reported the discrepancy on 28 August 2025. Rayner admitted the underpayment on 3 September and referred herself to Sir Laurie Magnus, the Prime Minister\'s independent adviser on ministerial standards. On 5 September Magnus published his finding: Rayner had "acted with integrity" and in "good faith" but had breached the Ministerial Code because she had failed to seek specialist tax advice despite her solicitors explicitly recommending she do so, and could not therefore be considered to have met the "highest possible standards of proper conduct". Rayner resigned within hours from all three of her posts. The reshuffle that followed sent David Lammy to Deputy PM while keeping the Justice brief, moved Yvette Cooper to Foreign Secretary, Shabana Mahmood to the Home Office and Steve Reed to Housing. With Rachel Reeves remaining as Chancellor, three of the four Great Offices of State were for the first time in British history held by women simultaneously.',
        'On 14 May 2026, eight months after her resignation, HMRC concluded that Rayner\'s stamp duty underpayment had been "neither careless nor deliberate" and imposed no penalty. The unpaid duty had already been settled. By then she had lost her government posts and her party role. What made the original scandal lethal was the parallel record. In 2018 Rayner had accused Health Secretary Jeremy Hunt of "sleaze" for using a "Tory tax loophole" to save nearly £100,000 in stamp duty on seven apartments. She had called for Nadhim Zahawi\'s resignation over a £5 million tax settlement. Her own stamp duty arrangements bore uncomfortable resemblance to the conduct she had spent years condemning. She has not ruled out a future Labour leadership challenge against Keir Starmer.',
      ],
      verdict: 'A serving Deputy Prime Minister who built her career on attacking Tory tax conduct, resigned over a tax error of her own, was cleared of any deliberate wrongdoing eight months later, and may still come back to lead her party.',
    },
    {
      type: 'mpEntry',
      rank: 3,
      name: 'Diane Abbott',
      memberId: 172,
      party: 'Independent',
      topLine: 'Suspended from Labour twice for the same comments about racism. First suspension: 23 April 2023, whip restored 28 May 2024. Second suspension: 17 July 2025, after she told the BBC she did not regret the 2023 letter. Now sits as an Independent. The investigation into her second suspension remains ongoing.',
      paragraphs: [
        "Diane Abbott was elected in 1987 as Britain's first Black female MP, representing Hackney North and Stoke Newington. Thirty eight years later she has been suspended from the Labour Party twice for the same comments about racism and currently sits as an Independent. The second suspension is more damaging than the first because it happened after she was given a second chance and chose not to take it.",
        'On 23 April 2023, Abbott wrote a letter to The Observer arguing that Jewish, Irish and Traveller people "undoubtedly experience prejudice" but are "not all their lives subject to racism". She compared their experience to that of "redheads" and wrote that "at the height of slavery, there were no white-seeming people manacled on the slave ships". Sir Keir Starmer himself called the letter "antisemitic". The Board of Deputies of British Jews described it as "disgraceful". Abbott withdrew the letter the same day and apologised, claiming it had been an initial draft sent by mistake. The Jewish Chronicle later reported that the identical letter had been sent to The Observer twice from her own email account, three hours apart, and that she had made no attempt to revise it in the seven days afterwards. The Labour whip was suspended and an NEC investigation began. The NEC concluded its inquiry in December 2023, issued a formal warning for conduct judged "prejudicial and grossly detrimental to the Labour Party", and required Abbott to complete an antisemitism awareness module, which she completed in February 2024. The whip was not restored for several more months. Reports emerged of attempts to broker a deal under which Abbott would stand down before the 2024 election. The Sunday Times reported she had been offered a peerage; Abbott publicly denied it. The whip was finally restored on 28 May 2024 and she was re-elected for Hackney North and Stoke Newington at the July 2024 general election with a 60 percent vote share.',
        'On 17 July 2025, Abbott gave a BBC Radio interview with Jim Naughtie. Asked whether she regretted the 2023 letter, she replied: "No, not at all." She repeated the substance of her original remarks: "Clearly, there must be a difference between racism which is about colour and other types of racism, because you can see a Traveller or a Jewish person walking down the street, you don\'t know." The Labour Party administratively suspended her the same day. The whip was withdrawn again. She now sits as an Independent. By 2025 the "draft sent in error" defence was no longer available: she had been formally warned, completed an antisemitism awareness course, been readmitted to the party, won re-election under the Labour banner, and then stated publicly that she did not regret the comments that caused the original suspension.',
        'Abbott served as Shadow Home Secretary under Jeremy Corbyn. She spent decades campaigning on racial justice, civil liberties and public services. She endured racist abuse throughout her career on a scale few politicians have experienced. No subsequent controversy erases any of that. But the scandal has come to define the closing phase of her parliamentary career. A politician who broke barriers on race and representation now sits as an Independent because she refused to accept that her comments about Jewish, Irish and Traveller experiences of racism were wrong. The Labour Party that she helped build over four decades has suspended her twice. At 72 she is among the longest serving MPs in the current Parliament. Whether the whip is restored or this suspension becomes permanent will determine how her career ends.',
      ],
      verdict: 'A trailblazing parliamentary career, four decades long, ending with the same letter to a newspaper and the same refusal to retract it that began the first suspension.',
    },
    {
      type: 'mpEntry',
      rank: 4,
      name: 'Suella Braverman',
      memberId: 4475,
      party: 'Reform UK',
      topLine: 'Sacked as Home Secretary twice. October 2022: leaked a draft ministerial statement from her personal email to the wrong recipient. November 2023: published an article in The Times accusing the Met of bias without Downing Street approval. Defected to Reform UK on 26 January 2026.',
      paragraphs: [
        'Suella Braverman is the only politician in modern British history to be sacked as Home Secretary twice. The first time, in October 2022, she leaked a confidential cabinet document from her personal email account. The second time, in November 2023, she published an article in The Times accusing the Metropolitan Police of bias without Downing Street approval. Between and around these two sackings she generated more sustained controversy than almost any other serving minister of her generation. She no longer sits as a Conservative.',
        'The first sacking came on 19 October 2022. Braverman sent a draft written ministerial statement on immigration from her personal email intending it for Sir John Hayes, the senior backbench MP she had been seeking advice from. She sent it to the wrong recipient. The document reached someone uninvolved who passed it on. She described the breach as a "technical infringement" of the ministerial code and resigned. Six days later, after Liz Truss\'s government collapsed, Rishi Sunak reappointed her to the same role, prompting questions about whether her return was part of a leadership deal. The speed awareness course episode followed. Braverman had been caught speeding in June 2022 while Attorney General. Rather than attend a standard group speed awareness course she asked civil servants to arrange a private one-on-one session, reportedly over concerns that points on her licence would raise her car insurance premium. Sunak consulted his ethics adviser but did not order an investigation, concluding the conduct did not amount to a breach while noting "a better course of action could have been taken to avoid giving rise to the perception of impropriety". Braverman accepted a fine and penalty points.',
        'The inflammatory rhetoric was not incidental. It was central to her political strategy. She described sending asylum seekers to Rwanda as her "dream" at the 2022 Conservative conference. She wrote in the Mail on Sunday that child grooming gangs in the UK were "almost all British-Pakistani". The Independent Press Standards Organisation ruled the claim "significantly misleading" because it generalised data from specific cases in Rotherham, Rochdale and Telford into a national characterisation. She accused asylum seekers of "gaming the system" by pretending to be gay or transgender. She called homelessness a "lifestyle choice" and proposed banning charities from giving tents to rough sleepers. In June 2025, however, Baroness Casey\'s national review of grooming gangs found a "disproportionate number of men of South Asian, particularly Pakistani, heritage" among suspects in Greater Manchester, West and South Yorkshire local data, criticising authorities for "shying away from the ethnicity of the people involved". Starmer u-turned and launched a full national statutory inquiry on 14 June 2025. Braverman wrote to IPSO demanding retraction of its 2023 ruling. IPSO refused. The position now is that the original phrasing was found misleading but the substance she had been condemned for stating was partially vindicated.',
        'The final sacking as Home Secretary came on 13 November 2023. Braverman wrote an article for The Times ahead of Armistice Day accusing the Metropolitan Police of taking "a more sympathetic attitude to those who hold pro-Palestinian views" and of double standards in policing protests. The article was published without Downing Street approval, breaching the convention that ministerial public statements are cleared by Number 10. Violence occurred around the Cenotaph on Armistice Day. Sunak sacked her the following Monday. After the 2024 election Braverman briefly announced she would run for the Conservative leadership but withdrew before nominations closed after failing to secure a single public endorsement from a Conservative MP. Her 2022 supporters had defected to Robert Jenrick and Priti Patel. On 26 January 2026 she defected to Reform UK, telling broadcasters the Conservative Party had "left the building" and accusing her old party of betrayal over its handling of the European Convention on Human Rights. Nigel Farage appointed her Reform UK frontbench spokesperson for Education, Skills and Equalities on 17 February 2026. She defends Fareham and Waterlooville under the Reform banner at the next general election.',
      ],
      verdict: 'Two sackings, one leak to the wrong recipient, one IPSO ruling partially vindicated two years later, one leadership bid that collapsed without a single public endorsement, and one defection. She commanded attention at every stage; what she delivered beyond attention remains harder to identify.',
    },
  ],
};

export default piece;
