import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'bk7m3wq9x2',
  kicker: 'The Leadership',
  headline: `Burnham Says Warehouses Can Fund High Street Tax Cuts. He Has Not Shown the Sums`,
  standfirst: `Andy Burnham says higher business rates on warehouses will fund cuts for pubs and high-street businesses. An outside estimate puts his proposed Small Business Rates Relief changes alone at around £880 million a year. The existing warehouse surcharge raises roughly £90 million a year. Burnham has not published the rate he would charge, the properties he would target or the revenue he expects.`,
  publishedAt: '2026-07-07',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `Andy Burnham says he will stick to Labour's promises not to raise income tax, VAT or employee National Insurance.` },
    { type: 'paragraph', text: `He also told Andrew Marr on LBC:` },
    { type: 'paragraph', text: `"There is some room within that manifesto for movement on tax."` },
    { type: 'paragraph', text: `His example was business rates.` },
    { type: 'paragraph', text: `Burnham said there was a case for charging higher rates on warehouses and large developments on the outskirts of cities so that pubs and high-street businesses could pay less. He repeated his proposal for a 20 per cent reduction for pubs and said some high-street businesses could be removed from business rates altogether.` },
    { type: 'paragraph', text: `The principle is not new.` },
    { type: 'paragraph', text: `Since April, England has already operated lower business-rates multipliers for qualifying retail, hospitality and leisure properties worth less than £500,000, alongside a higher multiplier for properties worth £500,000 or more.` },
    { type: 'paragraph', text: `The standard multiplier is 48p for larger properties below £500,000. The high-value multiplier is 50.8p. Retail, hospitality and leisure properties below the £500,000 threshold receive lower rates of 38.2p or 43p depending on their size.` },
    { type: 'paragraph', text: `The Treasury says the higher rate applies to just over 21,000 properties.` },
    { type: 'paragraph', text: `Among them are around 1,900 distribution warehouses. The Treasury estimates those warehouses will pay an additional £270 million between 2026/27 and 2028/29 because of the higher multiplier. It explicitly says revenue from the high-value multiplier helps fund the lower rates given to retail, hospitality and leisure businesses.` },
    { type: 'paragraph', text: `Burnham is therefore proposing to push an existing redistribution further rather than inventing a new principle.` },
    { type: 'paragraph', text: `His package is also broader than a 20 per cent pub discount.` },
    { type: 'paragraph', text: `During the Makerfield campaign he proposed increasing the rateable-value threshold for full Small Business Rates Relief from £12,000 to £18,000, with tapered relief extending to £21,000 rather than £15,000. He also proposed taking some single-site shops, cafes and other high-street businesses out of business rates.` },
    { type: 'paragraph', text: `There are price estimates for parts of that plan.` },
    { type: 'paragraph', text: `Property consultant Colliers reported in June that Burnham had put the additional support for pubs at about £100 million.` },
    { type: 'paragraph', text: `More significantly, analysis published on 6 July by property-tax firm Ryan estimated that raising the Small Business Rates Relief thresholds could reduce business-rates liabilities by around £880 million a year and take more than 140,000 additional small premises out of the tax altogether.` },
    { type: 'paragraph', text: `The £880 million figure is not a Treasury costing and it is not an observed cost. It is an outside estimate based on government property data.` },
    { type: 'paragraph', text: `But it means the problem with Burnham's proposal is not that nobody has attempted to put a price on it.` },
    { type: 'paragraph', text: `It is that Burnham has not published the other side of the calculation.` },
    { type: 'paragraph', text: `He has not said how high warehouse rates would rise, how many properties would pay the higher charge, how much revenue it would produce or how that figure relates to the relief he wants to provide.` },
    { type: 'paragraph', text: `The existing system gives some scale.` },
    { type: 'paragraph', text: `The Treasury expects the current high-value multiplier to raise an additional £270 million from 1,900 distribution warehouses over three years, roughly £90 million a year on average.` },
    { type: 'paragraph', text: `Ryan's estimate for Burnham's proposed Small Business Rates Relief changes alone is around £880 million a year.` },
    { type: 'paragraph', text: `Those figures are not directly interchangeable. Burnham could impose a substantially larger increase than the current surcharge, broaden the properties affected or find money elsewhere. His proposals have also included action against empty high-street properties and higher contributions from online businesses.` },
    { type: 'paragraph', text: `But the difference is large enough that the funding mechanism needs to be shown rather than assumed.` },
    { type: 'paragraph', text: `There is another complication.` },
    { type: 'paragraph', text: `England's existing high-value multiplier is not a warehouse tax. It applies to all properties with a rateable value of at least £500,000.` },
    { type: 'paragraph', text: `That includes warehouses, but also large shops, offices and other expensive commercial properties. The legislation allows the high-value multiplier to be set as much as 10p above the standard multiplier. The current difference is 2.8p.` },
    { type: 'paragraph', text: `If Burnham simply raises that multiplier, the bill does not fall exclusively on online warehouses.` },
    { type: 'paragraph', text: `If he intends to target warehouses differently from other high-value properties, the mechanism has not yet been published.` },
    { type: 'paragraph', text: `That matters because the political pitch is much simpler than the tax system underneath it.` },
    { type: 'paragraph', text: `A giant distribution centre outside a town paying more so that a family pub on its high street can pay less is an easy argument to make.` },
    { type: 'paragraph', text: `There is also a defensible policy case for it. Business rates fall heavily on businesses that need physical premises. The government has already decided that retail, hospitality and leisure properties warrant lower multipliers and that high-value properties should contribute more towards them.` },
    { type: 'paragraph', text: `Burnham's question is whether that transfer should go further.` },
    { type: 'paragraph', text: `His answer so far is yes.` },
    { type: 'paragraph', text: `The arithmetic is less developed.` },
    { type: 'paragraph', text: `Burnham has said he will keep Labour's fiscal rules and defended himself against suggestions that he would be loose with the public finances. "I am not indisciplined when it comes to the public finances," he told Marr.` },
    { type: 'paragraph', text: `That makes the missing funding calculation more important, not less.` },
    { type: 'paragraph', text: `The proposal now has an outside estimate of its potential cost. There is an existing warehouse surcharge against which the scale can be compared. There is even an existing legal mechanism that could be increased.` },
    { type: 'paragraph', text: `What Burnham has not published is the rate he would charge, the tax base he would use and the revenue he expects it to raise.` },
    { type: 'paragraph', text: `Until those numbers exist, saying warehouses will pay for the high-street tax cuts is a proposal, not a funded plan.` },
  ],
  evidence: {
    recordsReviewed: [
      `LBC, Andy Burnham interview with Andrew Marr, 2 July 2026: records Burnham's commitment to Labour's manifesto tax pledges, his statement that there is room for movement on tax, his proposal for higher rates on warehouses and his 20 per cent pub reduction`,
      `HM Treasury, Effects of the business rates retail, hospitality and leisure multipliers and high-value multiplier, 26 November 2025: sets out the business-rates regime applying from April 2026, including just over 21,000 properties within the high-value multiplier, around 1,900 distribution warehouses and an estimated £270 million of additional warehouse revenue over three years`,
      `HM Treasury, Business rates: forward look: confirms that the high-value multiplier applies to properties worth £500,000 or more and that legislation allows it to be set up to 10p above the standard multiplier`,
      `HM Treasury, pubs and live music venues relief, 27 January 2026: confirms the existing 15 per cent relief for eligible pubs and live music venues during 2026/27 and the planned real-terms freeze for the following two years`,
      `Association of Convenience Stores, 6 July 2026: records Burnham's proposed increase in the full Small Business Rates Relief threshold from £12,000 to £18,000 and the tapered threshold from £15,000 to £21,000`,
      `Colliers, What could an Andy Burnham government mean for business rates?, 19 June 2026: records the wider high-street proposals and Burnham's estimate that the additional pub support would cost about £100 million`,
      `Ryan analysis reported by Press Association, 5 to 6 July 2026: estimates that Burnham's proposed changes to Small Business Rates Relief could reduce liabilities by around £880 million a year and remove more than 140,000 additional premises from business rates; this is an external model rather than a government costing`,
    ],
    lastChecked: '5 October 2026',
  },
};

export default piece;
