import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'bm4k9mxw7r',
  kicker: 'Housing',
  headline: `Government Revives Help to Buy Model Before Publishing Rules Meant to Fix Its Targeting Problem`,
  standfirst: `Andy Burnham announced Your First Home on 26 September: an equity-loan scheme for first-time buyers requiring a 2.5 per cent deposit, with government providing up to 20 per cent of the purchase price. The household income cap and local property price limits intended to target it better than Help to Buy will not be published until the Budget. The latest evaluation of Help to Buy found that 46 per cent of customers said they could not have bought without it; earlier NAO-examined research put that figure at 37 per cent.`,
  publishedAt: '2026-09-26',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `Prime Minister Andy Burnham announced on 26 September that the government is bringing back an equity-loan scheme for first-time buyers, before publishing the income limits and local property price caps intended to make sure the support reaches people who could not otherwise afford a home.` },
    { type: 'paragraph', text: `Under Your First Home, buyers in England are expected to need a deposit of 2.5 per cent, with government providing an equity loan worth up to 20 per cent of the price of a qualifying new-build property. The loan will have an initial interest-free period. Developers taking part will also be required to contribute towards the scheme, although the size of that contribution has not yet been announced.` },
    { type: 'paragraph', text: `The final cost, implementation timetable, household income cap and local property price limits are due to be set out at the Budget. Ministers say those restrictions will ensure the scheme is targeted at first-time buyers who would otherwise struggle to purchase.` },
    { type: 'paragraph', text: `The previous Help to Buy equity-loan scheme ran from 2013 to 2023 and had the same basic structure: public money reduced the deposit and mortgage required to buy a new-build home. Evidence published since then shows that it helped many people into home ownership, but that a substantial proportion of recipients could have bought without it.` },
    { type: 'paragraph', text: `The latest government-commissioned evaluation, published on 15 September, found that 46 per cent of Help to Buy customers said they could not have bought a home without the scheme. The remaining 54 per cent said they could have bought a home without Help to Buy, although they used the scheme to buy the property they wanted.` },
    { type: 'paragraph', text: `Earlier research examined by the National Audit Office had put the proportion unable to buy any property without support even lower, at 37 per cent. It found that around three-fifths of participants could have bought some property without Help to Buy and that 31 per cent, around 65,000 households at that stage of the scheme, could have bought the property they wanted without it.` },
    { type: 'paragraph', text: `Those figures come from different studies and periods and should not be treated as directly interchangeable. Both, however, found significant numbers of recipients who were not wholly dependent on the scheme to become homeowners.` },
    { type: 'paragraph', text: `The government says Your First Home will address that through household income limits and local price caps. Those thresholds are not yet public.` },
    { type: 'paragraph', text: `Its econometric analysis estimates that around 15 per cent of new homes built in England during Help to Buy 1 and Help to Buy 2 between 2013 and 2023 were attributable to the scheme. The evaluation also calculates a net present social value of £25.1 billion in 2024/25 prices and classifies Help to Buy as delivering "very high" value for money. That assessment includes the value created by additional housing supply and the fact that government recovers money as equity loans are repaid. The evaluation puts the scheme's net public-sector cost at about £3.6 billion after loan redemptions, interest and fees are taken into account.` },
    { type: 'paragraph', text: `The evaluation found evidence of increased housing supply from the early years of Help to Buy, but no further increase when the maximum equity loan available in London was raised in 2016. It also found little evidence of a large change in supply when the scheme ended in 2023. High loan-to-value mortgages had become more widely available by the later phase of Help to Buy, reducing the extent to which some buyers needed government support.` },
    { type: 'paragraph', text: `For small and medium-sized developers, the evaluation found statistically significant positive effects on profit margins from 2016 onwards compared with matched firms that did not participate. It found similar patterns among larger developers, although the lack of a meaningful non-participating comparison group made the effect harder to isolate. The National Audit Office had already found that five large developers accounted for just over half of Help to Buy sales in the period it examined, and that the scheme contributed to increases in housebuilders' sales and profits.` },
    { type: 'paragraph', text: `Investors expect Your First Home to benefit the sector again. The FTSE index of British housebuilders rose 16 per cent after the government confirmed the new scheme, with Reuters reporting that builders including Persimmon, Barratt Redrow, Bellway and Taylor Wimpey were expected to be among the main beneficiaries because of their exposure to lower-priced new-build homes. Reuters also noted that part of the rally may have reflected investors closing short positions.` },
    { type: 'paragraph', text: `The latest evaluation also found some effect on house prices, although the scale was uneven and should not be reduced to one national figure. Around the England-Wales border, the estimated price effect was small, up to about 2 per cent. The report found stronger evidence that Help to Buy contributed to price growth in some areas that were already relatively expensive, while its analysis of London produced mixed results. Help to Buy properties themselves were estimated to carry a premium of around 1 per cent compared with similar new-build homes outside the scheme.` },
    { type: 'paragraph', text: `Government also shares the property-market risk created by equity loans. When the property is sold, the state receives the same percentage of its market value as the original equity stake. Rising prices increase the value of that stake; falling prices reduce it. The NAO previously warned that Help to Buy therefore exposed government to significant housing-market risk while tying up substantial public financial capacity.` },
    { type: 'paragraph', text: `That risk looks different depending on who receives the loan. Public exposure may be easier to justify where the buyer genuinely could not purchase without assistance. The previous scheme also provided support to many households who said they could have bought a home anyway.` },
    { type: 'paragraph', text: `Your First Home is intended to narrow that group through income and local price limits. The government has announced the equity-loan structure before publishing those limits, the developer contribution, the final cost or the implementation timetable. Those details are due at the Budget.` },
  ],
  evidence: {
    recordsReviewed: [
      `Ministry of Housing, Communities and Local Government, "New first-time buyer scheme to be confirmed at Budget", 26 September 2026: proposed 2.5 per cent deposit, 20 per cent government equity loan, new-build restriction, developer contribution, planned income and local property price caps, and the decision to publish final costs and implementation details at the Budget`,
      `Ministry of Housing, Communities and Local Government, "Evaluation of the Help to Buy scheme", 15 September 2026: latest independent evaluation of Help to Buy's effects on home ownership, housing supply, developer finances, house prices and value for money`,
      `Help to Buy evaluation findings report, September 2026: finding that 46 per cent of customers said they could not have bought without Help to Buy, estimate that around 15 per cent of new-build supply over 2013 to 2023 resulted from the scheme, £25.1 billion net present social value calculation, £3.6 billion net public-sector cost, developer profit-margin findings and house-price analysis`,
      `National Audit Office, "Help to Buy: Equity Loan scheme – progress review", June 2019: earlier 37 per cent figure, estimate that around three-fifths of participants could have bought without the scheme, the 31 per cent able to buy the property they wanted anyway, five large developers accounting for just over half of sales, and the government's exposure to property-market risk`,
      `Reuters, "UK housebuilder shares rally on help for first-time buyers", 28 September 2026: 16 per cent rise in the British housebuilder index, developers expected to benefit (Persimmon, Barratt Redrow, Bellway, Taylor Wimpey) and the qualification that short-covering contributed to the market move`,
    ],
    lastChecked: '3 October 2026',
  },
};

export default piece;
