import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'bm4k9mxw7r',
  kicker: 'Housing',
  headline: `Government Revives Help to Buy Model Despite Evidence Most Previous Users Could Have Bought Without It`,
  standfirst: `The government has announced Your First Home, an equity-loan scheme for first-time buyers requiring a 2.5 per cent deposit. Government research into the previous Help to Buy scheme found that only 37 per cent of participants could not have bought any property without state support. Income limits and local price caps will not be published until the Budget.`,
  publishedAt: '2026-09-26',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `The government says its new first-time buyer scheme will help people who cannot otherwise afford to buy a home.` },
    { type: 'paragraph', text: `Its own evidence from the last time Britain tried this model suggests that will be difficult to guarantee.` },
    { type: 'paragraph', text: `Under Your First Home, buyers in England are expected to need a deposit of just 2.5 per cent. Government would provide an equity loan worth up to 20 per cent of the price of a qualifying new-build home, with an initial interest-free period.` },
    { type: 'paragraph', text: `Ministers say the scheme will tackle the deposit barrier for people who would be unable to afford their first home without help.` },
    { type: 'paragraph', text: `But the previous Help to Buy equity-loan scheme had almost exactly the same problem to solve, and government research later found that only 37 per cent of participants could not have bought any property without it.` },
    { type: 'paragraph', text: `Around three-fifths could have bought a home without state support, although not necessarily the property they wanted.` },
    { type: 'paragraph', text: `Almost a third, an estimated 65,000 households, could have bought the property they wanted anyway.` },
    { type: 'paragraph', text: `That does not mean Help to Buy achieved nothing. It helped large numbers of first-time buyers and increased new-build sales.` },
    { type: 'paragraph', text: `But it does mean the central targeting problem is already known.` },
    { type: 'paragraph', text: `The government is reviving the equity-loan model before publishing the income limits and local price caps it says will prevent the same thing happening again.` },
    { type: 'paragraph', text: `Those details will not appear until the Budget. The final cost and implementation timetable have not yet been published either.` },
    { type: 'paragraph', text: `The policy has therefore been announced before the public can see the rules that will determine whether government money reaches people who genuinely need it.` },
    { type: 'heading', level: 2, text: `Developers benefited from the previous scheme` },
    { type: 'paragraph', text: `There is another complication.` },
    { type: 'paragraph', text: `A major government evaluation of Help to Buy, published this month, found that participating developers benefited financially from the scheme.` },
    { type: 'paragraph', text: `The study found statistically significant positive effects on revenues, profit before tax and profit margins for a sample of small and medium-sized developers across 2016 to 2023. It found a similar pattern among larger developers, though that finding was harder to pin down statistically, because essentially all large developers took part in the scheme, leaving no real comparison group to measure against.` },
    { type: 'paragraph', text: `The same evaluation also found that Help to Buy contributed to higher property prices overall, with homes in England running roughly 2 per cent more expensive than they otherwise would have been, based on a comparison with the unaffected Welsh side of the border, and the increase was larger still in areas that were already less affordable before the scheme arrived.` },
    { type: 'paragraph', text: `That matters because Your First Home will again be restricted to new-build properties from developers signed up to the scheme.` },
    { type: 'paragraph', text: `The government says developers will have to contribute towards the cost.` },
    { type: 'paragraph', text: `How much they will contribute has not yet been published.` },
    { type: 'paragraph', text: `Investors did not wait for the detail.` },
    { type: 'paragraph', text: `Housebuilder shares jumped sharply after the announcement: Persimmon rose 15 per cent, Barratt Redrow, Bellway and Taylor Wimpey each gained around 12 per cent, and Vistry gained 10 per cent. Reuters reported the move "could mark the biggest boost yet" for a sector that has struggled with high borrowing costs, inflation and weak demand.` },
    { type: 'paragraph', text: `That is not evidence that housebuilders are being improperly subsidised.` },
    { type: 'paragraph', text: `It does show where the market expects a large part of the benefit to land.` },
    { type: 'paragraph', text: `Help to Buy created a similar tension.` },
    { type: 'paragraph', text: `It was designed to help buyers, but because it could only be used on new-build homes, it also created a large stream of demand for developers.` },
    { type: 'paragraph', text: `The National Audit Office found that five large housebuilders, Persimmon, Barratt, Taylor Wimpey, Bellway and Redrow, accounted for just over half of all Help to Buy sales during the period it examined.` },
    { type: 'heading', level: 2, text: `The supply effect weakened over time` },
    { type: 'paragraph', text: `The latest government evaluation reaches a more nuanced conclusion.` },
    { type: 'paragraph', text: `It says Help to Buy did increase home ownership and housing supply, particularly in its early years, estimating that around 15 per cent of all new-build homes built in England between 2013 and 2023 were a direct result of the scheme. It also concludes the scheme represented "very high value for money" overall, putting its net present social value at £25.1 billion at 2024/25 prices over its ten-year lifetime, once the value of additional housing supply and the financial returns on the government's equity stakes were factored in.` },
    { type: 'paragraph', text: `But it also found the effect on housing supply weakened over time.` },
    { type: 'paragraph', text: `The evaluation found no evidence that increasing the maximum London loan in 2016, or introducing regional price caps under the later phase of the scheme, produced any further increase in supply. It also found little evidence of a substantial effect on new housing supply when the scheme ended in England in 2023.` },
    { type: 'paragraph', text: `That complicates the government's claim that Your First Home will "boost housing supply."` },
    { type: 'paragraph', text: `It may stimulate demand.` },
    { type: 'paragraph', text: `Whether that produces genuinely additional homes rather than helping buyers compete for homes developers were already going to build is a different question, and the evaluation's own findings suggest that link was strongest early on and largely absent by the scheme's later years.` },
    { type: 'paragraph', text: `The earlier scheme did produce additional housing. The National Audit Office estimated around 78,000 additional new-build sales had resulted from Help to Buy by December 2018.` },
    { type: 'paragraph', text: `But the same report warned that government was also taking significant property-market risk and tying up substantial public financial capacity in equity loans.` },
    { type: 'heading', level: 2, text: `The government is taking property market risk again` },
    { type: 'paragraph', text: `Your First Home will expose the government to the same basic risk.` },
    { type: 'paragraph', text: `If property prices rise, the value of the government's equity stake rises.` },
    { type: 'paragraph', text: `If they fall, taxpayers share the loss.` },
    { type: 'paragraph', text: `That can still be a sensible trade if the scheme helps people who would otherwise remain locked out of home ownership.` },
    { type: 'paragraph', text: `The problem comes when government takes that risk for households who could have bought anyway.` },
    { type: 'paragraph', text: `That is precisely what happened under the previous system.` },
    { type: 'paragraph', text: `The government says this version will be better targeted.` },
    { type: 'paragraph', text: `It plans household income limits and local property price caps.` },
    { type: 'paragraph', text: `Those may fix some of the old weaknesses.` },
    { type: 'paragraph', text: `But until the thresholds are published, there is no way to judge whether they actually will.` },
    { type: 'heading', level: 2, text: `Subsidising demand does not create another house` },
    { type: 'paragraph', text: `There is also a more basic housing-policy question.` },
    { type: 'paragraph', text: `Helping someone assemble a deposit does not create another house.` },
    { type: 'paragraph', text: `The government says Your First Home will stimulate developers to build more because buyers will be easier to find.` },
    { type: 'paragraph', text: `That happened to some extent under Help to Buy, most clearly in its first few years.` },
    { type: 'paragraph', text: `But the government's own latest evaluation suggests the supply effect became much weaker later on, with no measurable boost even from expanding the scheme's loan limits or introducing price caps designed to spread its reach.` },
    { type: 'paragraph', text: `If the present constraint on housebuilding is planning, infrastructure, financing or construction costs rather than simply a shortage of willing buyers, subsidising demand can only do so much.` },
    { type: 'heading', level: 2, text: `The useful measures are harder than loan numbers` },
    { type: 'paragraph', text: `That is why the new scheme should not be judged by how many equity loans are issued.` },
    { type: 'paragraph', text: `How many recipients genuinely could not have bought without it?` },
    { type: 'paragraph', text: `How many extra homes were built because of it?` },
    { type: 'paragraph', text: `How much did developers gain?` },
    { type: 'paragraph', text: `Did new-build prices rise faster in areas where the scheme was heavily used?` },
    { type: 'paragraph', text: `And what return did taxpayers receive on the money tied up in equity loans?` },
    { type: 'paragraph', text: `The government has already run this experiment once.` },
    { type: 'paragraph', text: `It knows the benefits.` },
    { type: 'paragraph', text: `It also knows where the money leaked beyond the people the policy was meant to help.` },
    { type: 'paragraph', text: `If Your First Home is going to avoid repeating those mistakes, the missing rules matter more than the announcement.` },
  ],
  evidence: {
    recordsReviewed: [
      'GOV.UK, 26 September 2026: "New first-time buyer scheme to be confirmed at Budget" — Your First Home design (2.5% deposit, up to 20% government equity loan, initial interest-free period, new-build-only from signed-up developers, developer contribution requirement with amount unpublished, income cap and local price cap details deferred to Budget, "boost housing supply" claim)',
      'National Audit Office, "Help to Buy: Equity Loan scheme" progress review — 37% figure (buyers who could not have bought any property without scheme); "around three-fifths" and "31%/65,000 households could have bought the property they wanted"; five-developer concentration (Persimmon 14.8%, Barratt 13.3%, Taylor Wimpey 11.9%, Bellway 6.7%, Redrow 3.7%, summing to just over half of scheme sales); 78,000 additional new-build sales estimate as of December 2018; significant property-market risk and public financial capacity tied up in equity loans',
      'Government evaluation of the Help to Buy scheme, evaluation findings report, September 2026 — statistically significant developer financial benefits for SMEs 2016–2023; similar but statistically less certain pattern for large developers; ~2% average house-price uplift (larger in less-affordable areas); ~15% of 2013–2023 new-build supply attributed to scheme; no further supply increase from 2016 London loan increase or regional price caps; no substantial supply effect when scheme ended in 2023; £25.1bn net present social value / "very high value for money" conclusion',
      'Reuters reporting, 26 September 2026 — housebuilder share-price moves: Persimmon +15%, Barratt Redrow/Bellway/Taylor Wimpey +12%, Vistry +10%; "could mark the biggest boost yet" framing (via AOL syndication)',
    ],
    lastChecked: '30 September 2026',
  },
};

export default piece;
