import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'bn6k4qxw27',
  kicker: 'The Leadership',
  headline: `Burnham Became Labour Leader With 379 MP Nominations and No Membership Ballot`,
  standfirst: `Andy Burnham became Labour leader on Friday without a vote of the party's membership. He did not defeat another candidate. No other Labour MP secured enough nominations to reach the ballot. He received nominations from 379 Labour MPs and 23 affiliated organisations and is expected to enter Downing Street on Monday.`,
  publishedAt: '2026-07-18',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `Andy Burnham became Labour leader on Friday without a vote of the party's membership.` },
    { type: 'paragraph', text: `He did not defeat another candidate. No other Labour MP secured enough nominations to reach the ballot.` },
    { type: 'paragraph', text: `By the time Burnham was formally declared leader at Labour's special conference on 17 July, he had received nominations from 379 Labour MPs and 23 affiliated organisations.` },
    { type: 'paragraph', text: `He is expected to become Prime Minister on Monday, when Keir Starmer leaves office and the King invites his successor to form a government. Burnham's elevation to the Labour leadership does not itself make him Prime Minister.` },
    { type: 'paragraph', text: `Labour's rules allowed exactly what happened.` },
    { type: 'paragraph', text: `Candidates needed nominations from at least 20 per cent of Labour MPs before moving to the later stages of the contest. MP nominations opened on 9 July and closed at 6pm on 15 July, not 16 July. Affiliate nominations closed the following evening.` },
    { type: 'paragraph', text: `Labour's published timetable provided for a special conference on 17 July if only one candidate was validly nominated. Had more than one candidate qualified, members and affiliated supporters would instead have voted in August.` },
    { type: 'paragraph', text: `Burnham had effectively ended the contest within days.` },
    { type: 'paragraph', text: `On the first day of nominations he received 322 nominations from Labour's 403 MPs. At that point he was one nomination short of leaving too few remaining Labour MPs for anybody else to reach the required threshold.` },
    { type: 'paragraph', text: `By 13 July his total had reached 349.` },
    { type: 'paragraph', text: `Steve Reed, Communities Secretary and a close ally of Starmer, was among those who joined Burnham's supporters, leaving no mathematical route for another candidate to qualify.` },
    { type: 'paragraph', text: `The final total was higher still.` },
    { type: 'paragraph', text: `At Friday's special conference, Labour's returning officer announced that Burnham had received 379 MP nominations. One other prospective candidate, Catherine West, had received one nomination and therefore did not qualify.` },
    { type: 'paragraph', text: `West herself subsequently backed Burnham.` },
    { type: 'paragraph', text: `This is not unprecedented.` },
    { type: 'paragraph', text: `Gordon Brown also became Labour leader without a membership ballot in 2007.` },
    { type: 'paragraph', text: `Brown secured 313 MP nominations. John McDonnell had 29 and could no longer reach the 45 nominations then required. Brown was therefore the sole candidate and was formally installed as Labour leader at a special conference on 24 June 2007.` },
    { type: 'paragraph', text: `He became Prime Minister three days later.` },
    { type: 'paragraph', text: `Burnham is therefore not the first uncontested Labour leader of the modern era. He is the first since Brown.` },
    { type: 'paragraph', text: `There was unease inside Labour about repeating that process.` },
    { type: 'paragraph', text: `Former armed forces minister Al Carns had been discussed as a possible challenger and argued that a contest could force a debate over Labour's direction.` },
    { type: 'paragraph', text: `He withdrew before nominations opened.` },
    { type: 'paragraph', text: `"I'd hoped a leadership contest would give us the opportunity for a proper debate."` },
    { type: 'paragraph', text: `Carns said months of internal Labour politics were not what the country needed and gave Burnham his support instead.` },
    { type: 'paragraph', text: `Some Labour MPs made the same broader argument: that an uncontested succession denied members the opportunity to test Burnham's programme before he entered Downing Street.` },
    { type: 'paragraph', text: `But polling does not support the simpler claim that Labour voters themselves overwhelmingly wanted a contest.` },
    { type: 'paragraph', text: `Lord Ashcroft's polling published on 7 July found that voters overall preferred a contested Labour leadership election by 50 per cent to 27 per cent.` },
    { type: 'paragraph', text: `Among people who voted Labour in 2024, however, Burnham taking over without a leadership election was preferred by a seven-point margin. Among people currently leaning Labour, the margin in favour of an uncontested succession was 26 points.` },
    { type: 'paragraph', text: `Burnham also had more policy on the table than the original criticism of a content-free coronation suggests.` },
    { type: 'paragraph', text: `In a speech at Manchester's People's History Museum on 29 June, he proposed establishing No 10 North, an extension of the Prime Minister's Office based in Manchester and intended to coordinate greater devolution across Britain.` },
    { type: 'paragraph', text: `He said it would coordinate a ten-year economic strategy built around reform of essential utilities, reindustrialisation and regeneration.` },
    { type: 'paragraph', text: `He proposed giving regions greater influence over public investment, expanding public control of services including water, energy, transport and housing, supporting place-based industrial strategies and overseeing what he described as the biggest council-house building programme since the post-war period.` },
    { type: 'paragraph', text: `Those proposals set a clear direction.` },
    { type: 'paragraph', text: `They did not amount to a fully costed programme for government.` },
    { type: 'paragraph', text: `Burnham did not provide a price for the council-house programme, quantify the cost of his plans for utilities or explain in detail how the industrial investment he proposed would be financed.` },
    { type: 'paragraph', text: `He did say his programme would operate within sound public finances and Rachel Reeves's fiscal rules.` },
    { type: 'paragraph', text: `The absence of a leadership contest removed the normal mechanism through which those plans might have been challenged by a rival candidate and tested by Labour members before Burnham took office.` },
    { type: 'paragraph', text: `It did not mean Burnham arrived without policies.` },
    { type: 'paragraph', text: `Nor did it mean Labour's rules had been bypassed.` },
    { type: 'paragraph', text: `Burnham received overwhelming support from the parliamentary party, cleared the nomination requirements and became leader under the procedure Labour had established for a single valid candidate.` },
    { type: 'paragraph', text: `What Labour members did not get was a choice between competing programmes.` },
    { type: 'paragraph', text: `On Monday, Burnham is expected to enter Downing Street with 379 Labour MPs behind his leadership and no separate vote from the party membership.` },
  ],
  evidence: {
    recordsReviewed: [
      `Labour Party, Leadership Election 2026 timetable: establishes the 9 July opening of PLP nominations, 15 July closing deadline, affiliate stage, 17 July special conference and August ballot timetable that would have applied in a contested election`,
      `Labour Party, Andy Burnham elected Leader of the Labour Party, 17 July 2026: confirms Burnham's election, 379 MP nominations and support from 23 affiliated organisations`,
      `Labour Party, affiliate nomination results: records the final affiliate nominations at the close of the 16 July deadline`,
      `Reuters, 10 July 2026: records Burnham receiving 322 of 403 Labour MP nominations on the opening day and explains why one more nomination would have made a rival candidacy mathematically impossible`,
      `House of Commons Library, Leadership elections: Labour Party: records Gordon Brown's uncontested 2007 leadership, his 313 nominations and the failure of John McDonnell to reach the required threshold`,
      `UK Government historical record on Gordon Brown: confirms Brown became Labour leader on 24 June 2007 and Prime Minister on 27 June 2007`,
      `ITV News, 9 July 2026: records Al Carns withdrawing from consideration and his statement that he had hoped a leadership contest would allow a proper debate`,
      `Lord Ashcroft Polls, 7 July 2026: finds voters overall preferred a contested election by 50 per cent to 27 per cent, while 2024 Labour voters and current Labour leaners were more supportive of Burnham taking over without one`,
      `People's History Museum, 29 June 2026, and Andy Burnham's speech: confirm Burnham used the museum to set out his plans for No 10 North, greater devolution, public control of utilities, reindustrialisation, regeneration and council housebuilding`,
    ],
    lastChecked: '5 October 2026',
  },
};

export default piece;
