import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'britains-most-disgraced-politicians',
  kicker: 'Political Accountability',
  headline: `Eleven Political Scandals, and What Actually Brought Them Down`,
  standfirst: `At Newry Crown Court on 22 June, a jury convicted Jeffrey Donaldson of 18 sexual offences. His case belongs in any account of political disgrace — but it does not fit the comforting old line that the cover-up is always worse than the original offence. Sometimes the original offence is worse.`,
  publishedAt: '2026-06-22',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `At Newry Crown Court on 22 June, a jury convicted Jeffrey Donaldson of 18 sexual offences against two women who were children when the abuse took place.` },
    { type: 'paragraph', text: `The former DUP leader was found guilty of one count of rape, 13 counts of indecent assault and four counts of gross indecency. The offences stretched from 1985 to 2008. He was remanded in custody and told to expect a lengthy prison sentence.` },
    { type: 'paragraph', text: `His wife Eleanor had been ruled medically unfit to stand trial. In a separate trial of the facts, the jury found that she had carried out acts of aiding and abetting. That process cannot produce a criminal conviction and should not be described as one.` },
    { type: 'paragraph', text: `Donaldson's case belongs in any account of political disgrace, but it does not fit the comforting old line that the cover-up is always worse than the original offence.` },
    { type: 'paragraph', text: `Sometimes the original offence is worse.` },
    { type: 'paragraph', text: `The distinction becomes clearer when Donaldson is put alongside the scandals that have ended other British political careers.` },
    { type: 'paragraph', text: `John Profumo's political career did not end simply because the Secretary of State for War had an affair with Christine Keeler.` },
    { type: 'paragraph', text: `It ended because he went to the House of Commons on 22 March 1963 and said: "There was no impropriety whatsoever in my acquaintanceship with Miss Keeler."` },
    { type: 'paragraph', text: `He then threatened legal action against anyone repeating the allegations outside Parliament.` },
    { type: 'paragraph', text: `On 5 June, his resignation was announced after he admitted the statement was false. The Commons later formally resolved that Profumo had committed a "grave contempt" of the House by making a statement containing words he later admitted were untrue.` },
    { type: 'paragraph', text: `Lord Denning's subsequent inquiry did not find that Profumo had caused a national security breach through the Soviet connection.` },
    { type: 'paragraph', text: `The lie to Parliament was enough.` },
    { type: 'paragraph', text: `Profumo then spent four decades working for Toynbee Hall in east London, eventually becoming its president and receiving a CBE for his charitable work. That later record does not change what ended his political career.` },
    { type: 'paragraph', text: `One claim often repeated in modern retellings should also be removed from the story. Stephen Ward's 1963 conviction was not quashed in 2024. The Criminal Cases Review Commission declined in 2017 to refer it back to the Court of Appeal.` },
    { type: 'paragraph', text: `Jonathan Aitken was Chief Secretary to the Treasury when The Guardian and Granada's World in Action investigated who had paid his bill at the Ritz in Paris.` },
    { type: 'paragraph', text: `The original allegation concerned hospitality from people connected to Saudi business interests while Aitken had served as a defence procurement minister.` },
    { type: 'paragraph', text: `Aitken sued.` },
    { type: 'paragraph', text: `He promised to fight with "the simple sword of truth and the trusty shield of British fair play".` },
    { type: 'paragraph', text: `The libel case collapsed when evidence showed his account was false. He later pleaded guilty to perjury and perverting the course of justice, including preparing a false witness statement signed by his daughter. In June 1999 he was sentenced to 18 months in prison.` },
    { type: 'paragraph', text: `Mr Justice Scott Baker told him he had spent years weaving a "web of deceit".` },
    { type: 'paragraph', text: `Whatever sanction the original hotel payment might have produced, it did not send him to prison.` },
    { type: 'paragraph', text: `His response to the allegation did.` },
    { type: 'paragraph', text: `Jeffrey Archer went further.` },
    { type: 'paragraph', text: `In 1987 he won £500,000 damages from the Daily Star after suing over an allegation that he had slept with Monica Coghlan.` },
    { type: 'paragraph', text: `Fourteen years later an Old Bailey jury found that Archer had used a false diary and sought a false alibi in connection with that libel action.` },
    { type: 'paragraph', text: `He was convicted of two counts of perverting the course of justice and two counts of perjury and sentenced to four years.` },
    { type: 'paragraph', text: `The original £500,000 judgment therefore became part of the scandal itself. Archer had used the courts to obtain damages while presenting evidence later found to be false.` },
    { type: 'paragraph', text: `The criminal case did not establish every allegation originally printed about his private life.` },
    { type: 'paragraph', text: `It did establish that he had perverted justice and committed perjury while trying to win the libel case.` },
    { type: 'paragraph', text: `That was enough to put him in Belmarsh.` },
    { type: 'paragraph', text: `Chris Huhne's scandal began with something most motorists would regard as irritating rather than career-ending.` },
    { type: 'paragraph', text: `His car was caught speeding in 2003.` },
    { type: 'paragraph', text: `Instead of accepting the penalty points himself, Huhne arranged for his then wife, Vicky Pryce, to take them.` },
    { type: 'paragraph', text: `The deception remained hidden for years.` },
    { type: 'paragraph', text: `When it eventually reached court, Huhne initially denied the charge. He resigned as Energy Secretary in February 2012 after prosecutors decided there was sufficient evidence to charge him.` },
    { type: 'paragraph', text: `On the first day of his trial in February 2013 he changed his plea to guilty.` },
    { type: 'paragraph', text: `Huhne and Pryce were each sentenced to eight months for perverting the course of justice. The judge said the points swap had been deliberate and that the deception had lasted for years.` },
    { type: 'paragraph', text: `The speeding offence was minor.` },
    { type: 'paragraph', text: `Falsifying who had been driving was not.` },
    { type: 'paragraph', text: `The parliamentary expenses scandal produced a different category of failure.` },
    { type: 'paragraph', text: `Denis MacShane did not go to prison because he lied when confronted about a harmless initial mistake.` },
    { type: 'paragraph', text: `Between 2005 and 2008 he submitted 19 claims supported by invoices purporting to come from the European Policy Institute.` },
    { type: 'paragraph', text: `The Commons investigation found that the organisation had no formal structure of the kind the invoices suggested, MacShane controlled its bank account, and the invoices were generated by him using false names.` },
    { type: 'paragraph', text: `The Commissioner summarised the arrangement brutally: "In effect, he was sending the invoice to himself and writing his own cheque."` },
    { type: 'paragraph', text: `The claims totalled £12,900.` },
    { type: 'paragraph', text: `MacShane later pleaded guilty to false accounting. Mr Justice Sweeney sentenced him to six months in prison in December 2013. The judge recorded that MacShane himself had created the false invoices and signed an invented name on them.` },
    { type: 'paragraph', text: `Eric Illsley's method was cruder.` },
    { type: 'paragraph', text: `He was paid £39,204 in second-home expenses between 2005 and 2008 against actual costs of roughly £25,000. Claims included telephone costs of up to £650 a quarter when the real bill was around £34 to £36.` },
    { type: 'paragraph', text: `He pleaded guilty to three counts of false accounting and was sentenced to 12 months.` },
    { type: 'paragraph', text: `In these cases there was no need for an elaborate second scandal to destroy the career.` },
    { type: 'paragraph', text: `Submitting false claims for public money was itself the criminal conduct.` },
    { type: 'paragraph', text: `Charlie Elphicke was convicted at Southwark Crown Court in July 2020 of three counts of sexual assault against two women.` },
    { type: 'paragraph', text: `In September, Mrs Justice Whipple sentenced the former Conservative MP and government whip to two years in prison. She called him a sexual predator who had used his success and respectability as cover.` },
    { type: 'paragraph', text: `The conviction has to be separated from the Conservative Party's earlier handling of the allegations.` },
    { type: 'paragraph', text: `Elphicke lost the whip in November 2017 after allegations were referred to police.` },
    { type: 'paragraph', text: `On 12 December 2018, while that police investigation was still unresolved, the Conservatives restored the whip to Elphicke and Andrew Griffiths in time for both men to participate in the confidence vote on Theresa May's leadership.` },
    { type: 'paragraph', text: `Elphicke had not been convicted at that point and denied wrongdoing.` },
    { type: 'paragraph', text: `The criticism is therefore not that the party ignored a conviction it already knew about.` },
    { type: 'paragraph', text: `It is that it restored the political privileges of an MP under an active investigation because a leadership vote was taking place that evening.` },
    { type: 'paragraph', text: `He was later charged, tried and convicted.` },
    { type: 'paragraph', text: `Those stages should not be collapsed into one another.` },
    { type: 'paragraph', text: `Owen Paterson was not convicted of a criminal offence.` },
    { type: 'paragraph', text: `His scandal was parliamentary.` },
    { type: 'paragraph', text: `The Commons Committee on Standards found that while being paid by Randox Laboratories and Lynn's Country Foods, Paterson repeatedly approached ministers and public officials in breach of Parliament's paid advocacy rules.` },
    { type: 'paragraph', text: `The Committee identified 14 prohibited approaches and described the case as "egregious". It recommended a 30-sitting-day suspension.` },
    { type: 'paragraph', text: `The government's response turned a standards case involving one MP into a much larger political crisis.` },
    { type: 'paragraph', text: `On 3 November 2021 Conservative MPs were whipped to support an amendment delaying consideration of Paterson's case and creating a new committee which could reconsider it.` },
    { type: 'paragraph', text: `The amendment passed by 250 votes to 232.` },
    { type: 'paragraph', text: `The government abandoned the plan after the backlash. Paterson resigned.` },
    { type: 'paragraph', text: `Randox's subsequent Covid contracts belong in the story only with care.` },
    { type: 'paragraph', text: `The National Audit Office found that the government awarded Randox and its partner contracts with a maximum value of £776.9 million between January 2020 and December 2021. £463.5 million of that value was awarded directly without competition.` },
    { type: 'paragraph', text: `The NAO also found serious gaps in the government's documentation.` },
    { type: 'paragraph', text: `It did not find evidence that the contracts had been awarded improperly.` },
    { type: 'paragraph', text: `There is therefore evidence that Paterson breached lobbying rules while being paid by Randox and evidence that Randox later received very large government contracts.` },
    { type: 'paragraph', text: `That is not evidence that Paterson caused those contracts to be awarded.` },
    { type: 'paragraph', text: `The stronger scandal is the one Parliament actually proved, followed by the government's attempt to change the disciplinary process after the finding.` },
    { type: 'paragraph', text: `Chris Pincher's scandal followed yet another route.` },
    { type: 'paragraph', text: `The Commons Standards Committee found in 2023 that Pincher had groped two people at the Carlton Club in June 2022.` },
    { type: 'paragraph', text: `It concluded that his conduct was deeply inappropriate, constituted an abuse of power and caused significant damage to the reputation of the Commons. It recommended an eight-week suspension.` },
    { type: 'paragraph', text: `The political crisis had already happened a year earlier.` },
    { type: 'paragraph', text: `After the Carlton Club allegations became public, Downing Street initially said Boris Johnson had not known about specific earlier allegations when he appointed Pincher Deputy Chief Whip in February 2022.` },
    { type: 'paragraph', text: `Former Foreign Office permanent secretary Simon McDonald then publicly contradicted that account.` },
    { type: 'paragraph', text: `McDonald said there had been a formal complaint in 2019, that the complaint had been upheld, and that Johnson had been briefed in person about the investigation and its outcome.` },
    { type: 'paragraph', text: `Johnson subsequently acknowledged that he had been told and said appointing Pincher had been a mistake.` },
    { type: 'paragraph', text: `The disclosure helped trigger the ministerial resignations that ended Johnson's premiership.` },
    { type: 'paragraph', text: `The scandal was not simply what Pincher did at the Carlton Club.` },
    { type: 'paragraph', text: `It was also the contradiction between what Downing Street first said the Prime Minister knew and what the documentary and witness record later showed.` },
    { type: 'paragraph', text: `John Stonehouse scarcely needs embellishment.` },
    { type: 'paragraph', text: `The former Labour minister disappeared from a Miami beach in November 1974 and was presumed dead.` },
    { type: 'paragraph', text: `He had in fact travelled to Australia using false identities taken from dead constituents.` },
    { type: 'paragraph', text: `Australian police arrested him on Christmas Eve. After extradition to Britain, Stonehouse represented himself during a 68-day trial and was convicted of fraud offences in 1976. He received a seven-year prison sentence.` },
    { type: 'paragraph', text: `He remained an MP through much of the criminal process and did not finally resign his Walsall North seat until August 1976.` },
    { type: 'paragraph', text: `The espionage part of the story requires more careful wording than it often receives.` },
    { type: 'paragraph', text: `Czechoslovak defector Josef Frolík accused Stonehouse of working for the country's intelligence service. Harold Wilson told Parliament in 1974 that the Security Service had investigated the allegation and advised him there was no evidence supporting it at the time.` },
    { type: 'paragraph', text: `In 2009, Christopher Andrew's authorised history of MI5 reached a different conclusion and identified Stonehouse as a Soviet-bloc agent.` },
    { type: 'paragraph', text: `That is a finding in MI5's authorised history, based on later intelligence material.` },
    { type: 'paragraph', text: `It was never a criminal conviction for espionage.` },
    { type: 'paragraph', text: `Stonehouse was already a convicted fraudster who had faked his own death. The spy allegation did not need to carry the scandal.` },
    { type: 'paragraph', text: `Donaldson's conviction brings the comparison back to where it started.` },
    { type: 'paragraph', text: `He was a former DUP leader, a 27-year Westminster MP and one of the central figures in modern unionism.` },
    { type: 'paragraph', text: `The jury did not convict him of misleading Parliament, breaching lobbying rules, false accounting or trying to conceal an embarrassing private indiscretion.` },
    { type: 'paragraph', text: `It convicted him of sexual offences against two people who were children when the offending took place.` },
    { type: 'paragraph', text: `That makes the usual lesson drawn from scandals such as Profumo, Aitken or Huhne inadequate.` },
    { type: 'paragraph', text: `Profumo's affair became politically fatal because he lied to Parliament.` },
    { type: 'paragraph', text: `Aitken's hotel bill became an 18-month prison sentence because he committed perjury and tried to pervert justice.` },
    { type: 'paragraph', text: `Huhne's three penalty points became an eight-month sentence because he transferred them to somebody else and maintained the deception.` },
    { type: 'paragraph', text: `Paterson's paid advocacy finding became a government crisis because ministers tried to suspend the normal standards process.` },
    { type: 'paragraph', text: `Pincher's misconduct became a crisis for Johnson because Downing Street's account of what the Prime Minister knew did not survive contact with the evidence.` },
    { type: 'paragraph', text: `There is no equivalent argument available for Donaldson.` },
    { type: 'paragraph', text: `His political career was not destroyed because of how he dealt with a lesser scandal after the event.` },
    { type: 'paragraph', text: `A jury convicted him of rape and 17 other sexual offences against children.` },
    { type: 'paragraph', text: `He left Newry Crown Court in custody.` },
  ],
  evidence: {
    recordsReviewed: [
      `House of Commons Hansard, John Profumo personal statement, 22 March 1963: primary record of Profumo's declaration that there had been "no impropriety whatsoever" in his relationship with Christine Keeler and his threat of legal action against anyone repeating the allegation outside Parliament`,
      `House of Commons, Privilege (Mr Profumo), 20 June 1963: records the Commons finding that Profumo's false personal statement amounted to grave contempt of the House`,
      `Criminal Cases Review Commission reporting on Stephen Ward, 2017: confirms the Commission declined to refer Ward's 1963 conviction back to the Court of Appeal; it has not been quashed`,
      `Old Bailey reporting on Jonathan Aitken, January and June 1999: supports his guilty pleas to perjury and perverting the course of justice and his 18-month sentence`,
      `Old Bailey reporting on Jeffrey Archer, July 2001: confirms his convictions on two counts of perjury and two counts of perverting the course of justice and his four-year sentence`,
      `Southwark Crown Court, sentencing remarks in R v Huhne and Pryce, 11 March 2013: primary judicial record of the points-swapping offence and the sentences imposed`,
      `House of Commons Standards and Privileges Committee, Mr Denis MacShane, 2012, and Central Criminal Court sentencing remarks, 23 December 2013: support the 19 false invoices, £12,900 claimed, MacShane's control of the European Policy Institute account and his later false-accounting sentence`,
      `House of Commons and contemporary court reporting on Eric Illsley: supports his false-accounting conviction, the £39,204 second-home expenses claimed against actual costs of around £25,000, the telephone claims and his 12-month sentence`,
      `Southwark Crown Court reporting and House of Commons Standards Committee records concerning Charlie Elphicke: support his three sexual-assault convictions, two-year sentence and the 12 December 2018 restoration of the whip ahead of the confidence vote on Theresa May's leadership`,
      `House of Commons Committee on Standards, Mr Owen Paterson, October 2021: primary source for the 14 paid-advocacy breaches, outside payments and the description of the case as egregious`,
      `National Audit Office, Investigation into the government's contracts with Randox Laboratories Ltd: supports the £776.9 million total contract value, the £463.5 million awarded directly without competition between January 2020 and December 2021, and the NAO finding that it had not seen evidence the contracts were awarded improperly`,
      `House of Commons Committee on Standards, Christopher Pincher, 6 July 2023, and parliamentary evidence from Boris Johnson: support the findings about Pincher's conduct and the evidence that Johnson had previously been briefed about the 2019 complaint`,
      `House of Commons and Commons Library records concerning John Stonehouse: support his continued parliamentary membership during the criminal proceedings and his resignation in August 1976`,
      `Christopher Andrew, The Defence of the Realm, as reported on publication in 2009: supports the later conclusion in MI5's authorised history that Stonehouse had acted as a Czechoslovak intelligence agent, while distinguishing that conclusion from a criminal conviction`,
      `Newry Crown Court proceedings, 22 June 2026: confirms Jeffrey Donaldson's conviction on one count of rape, 13 counts of indecent assault and four counts of gross indecency against two victims who were children, and his remand in custody, and Eleanor Donaldson's trial of the facts finding of aiding and abetting`,
    ],
    lastChecked: '5 October 2026',
  },
};

export default piece;
