import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'cq4r8vn2mp',
  kicker: 'Local Government',
  headline: `England's Ten Highest Council Tax Areas, and Who Actually Takes the Money`,
  standfirst: `Dorset has the highest average Band D council tax in England this year at £2,765.02. But five of the ten highest areas are district council areas where most of the bill is not set by the district council at all — it goes to county councils, police, fire services and parish or town councils. In two of them, the district council did not increase its own charge at all this year.`,
  publishedAt: '2026-07-03',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `Dorset has the highest average Band D council tax in England this year at £2,765.02.` },
    { type: 'paragraph', text: `Lewes is second at £2,756.17. Nottingham is third.` },
    { type: 'paragraph', text: `The government's official figures produce a top ten that is very different from simply looking at which councils appear expensive or have recently been in financial trouble. Five of the ten are district council areas where most of the bill is not set by the district council at all. It goes to county councils, police, fire services and parish or town councils.` },
    { type: 'paragraph', text: `That distinction changes what the figures mean.` },
    { type: 'paragraph', text: `In Wealden, which has the fifth-highest average Band D bill in England, the district council froze its own charge at £221.14. In Newark and Sherwood, ranked tenth, the district council also froze its share at £198.60.` },
    { type: 'paragraph', text: `Residents still face some of the highest overall bills in the country because those councils collect money on behalf of several other authorities.` },
    { type: 'paragraph', text: `The national figure is £2,392 for an average Band D property in 2026/27, including parish precepts. The ten highest areas average about £2,726, roughly £334 more.` },
    { type: 'paragraph', text: `Band D is a standard comparison rather than the bill paid by the average household. England's average council tax per dwelling, after accounting for the actual mix of property bands and discounts, is £1,868.` },
    { type: 'paragraph', text: `Dorset has England's highest average Band D council tax.` },
    { type: 'paragraph', text: `Unlike the district councils further down the list, Dorset Council is a unitary authority. It is responsible for expensive services including adult and children's social care as well as highways, waste, planning and other local services.` },
    { type: 'paragraph', text: `Its own Band D element is £2,205.90. Dorset Police adds £322.58 and Dorset and Wiltshire Fire and Rescue adds £96.95. The difference between that £2,625.43 core bill and the published area average comes from parish and town council precepts, which vary around Dorset.` },
    { type: 'paragraph', text: `The average total rose by £134.72, or 5.1 per cent, from last year.` },
    { type: 'paragraph', text: `Lewes is almost level with Dorset, but the money goes somewhere very different.` },
    { type: 'paragraph', text: `Lewes District Council itself sets only £242.02 of the average Band D bill. East Sussex County Council takes £1,960.29, Sussex Police £281.91 and East Sussex Fire and Rescue £117.49. Town and parish councils add an average £154.46.` },
    { type: 'paragraph', text: `So calling £2,756 a "Lewes District Council charge" would be misleading. The district council controls less than a tenth of it.` },
    { type: 'paragraph', text: `The rest mainly pays for services delivered above district level, including social care, highways, education, policing and fire.` },
    { type: 'paragraph', text: `Nottingham is the highest-ranked major city and sits only 78p below Lewes.` },
    { type: 'paragraph', text: `Here the comparison with the council itself is much more meaningful. Nottingham City Council is a unitary authority and its own element of the Band D bill is £2,342.08. Police adds £311.10 and the fire authority £102.21.` },
    { type: 'paragraph', text: `The city council element rose by 3.5 per cent for 2026/27.` },
    { type: 'paragraph', text: `Nottingham's financial history remains relevant. It issued a Section 114 notice in 2023 after years of serious financial problems, including losses at the council-owned Robin Hood Energy company. But the current bill should not simply be described as the price of that collapse. Council tax is paying for the authority's present services and funding requirements, not an itemised repayment of past mistakes.` },
    { type: 'paragraph', text: `Rutland illustrates another problem with simple league tables.` },
    { type: 'paragraph', text: `Its council froze the general council tax component for 2026/27 and applied only the 2 per cent adult social care increase. Rutland County Council's own Band D charge is £2,263.33. Police adds £315.23 and fire £91.65, before town and parish precepts.` },
    { type: 'paragraph', text: `Rutland is fourth in England on the government's average area Band D measure. Rutland County Council said in a March press release that it had fallen to eighth nationally, but that release quoted the council's own £2,263.33 element rather than the full bill and did not explain a methodology that reproduces an eighth-place ranking. MHCLG's published area figures put Rutland behind only Dorset, Lewes and Nottingham.` },
    { type: 'paragraph', text: `Rutland says just over 80 per cent of its funding now comes from council tax, compared with a national average of around 61 per cent, reflecting its unusually small tax base and comparatively low government grant funding.` },
    { type: 'paragraph', text: `Its high bill therefore does not come from a large increase this year. The average area figure rose by only about 2.5 per cent, one of the smallest increases among the ten highest-charging areas.` },
    { type: 'paragraph', text: `Wealden has England's fifth-highest average Band D bill even though Wealden District Council froze its own charge.` },
    { type: 'paragraph', text: `Its share remains £221.14.` },
    { type: 'paragraph', text: `The council itself says it keeps only a small part of the council tax it collects. Most goes to East Sussex County Council, with further amounts going to Sussex Police, the fire authority and 42 parish and town councils.` },
    { type: 'paragraph', text: `East Sussex County Council alone charges £1,960.29 at Band D.` },
    { type: 'paragraph', text: `A ranking which simply labels the whole £2,728 bill as Wealden's therefore attributes more than £2,500 of other authorities' charges to the district council.` },
    { type: 'paragraph', text: `Gateshead has the highest average Band D bill in the North East.` },
    { type: 'paragraph', text: `Its own council element is £2,396.07 after a 4.99 per cent rise, including the 2 per cent adult social care precept. The council approved that increase alongside £10.9 million of budget reductions and planned use of reserves.` },
    { type: 'paragraph', text: `Gateshead is a metropolitan authority, so unlike Lewes or Wealden it is itself responsible for many of the high-cost services that dominate local government spending, particularly adult and children's social care.` },
    { type: 'paragraph', text: `The remaining part of the £2,715.81 total comes from police and fire precepts.` },
    { type: 'paragraph', text: `Bristol's bill is easier to unpick because there is no parish average distorting the comparison.` },
    { type: 'paragraph', text: `Bristol City Council charges £2,310.05 at Band D. Avon and Somerset Police adds £308.20 and the fire authority £95.43.` },
    { type: 'paragraph', text: `That produces a total of £2,713.68.` },
    { type: 'paragraph', text: `The total is about £322 above the England average and rose by about 5 per cent from 2025/26.` },
    { type: 'paragraph', text: `As a unitary authority, Bristol is responsible for social care as well as the more visible services residents tend to associate with councils. Comparing its bill directly with a shire district that does not provide those services gives a distorted picture of relative efficiency.` },
    { type: 'paragraph', text: `West Devon Borough Council's own Band D charge is £277.46.` },
    { type: 'paragraph', text: `Devon County Council charges another £1,891.17. Police and fire add £412.88 between them, and the average parish precept adds about £123.82.` },
    { type: 'paragraph', text: `Almost 70 per cent of the average total therefore comes from Devon County Council alone.` },
    { type: 'paragraph', text: `West Devon increased its own element by 2.99 per cent. The overall area bill rose by 5.1 per cent because the final bill combines decisions made by several different bodies.` },
    { type: 'paragraph', text: `Rother District Council charges £216.95 at Band D.` },
    { type: 'paragraph', text: `Before parish or town council charges are added, East Sussex County Council, Sussex Police, the fire authority and Rother produce a combined Band D bill of £2,576.64.` },
    { type: 'paragraph', text: `Local precepts then vary substantially.` },
    { type: 'paragraph', text: `A Band D property in East Guldeford pays no parish precept and has a total bill of £2,576.64. In Etchingham, the parish element takes the same Band D bill to £2,792.48. Battle is £2,752.80.` },
    { type: 'paragraph', text: `The government's £2,700.95 figure is therefore an area average. It is not the exact bill sent to every Band D household in Rother.` },
    { type: 'paragraph', text: `Newark and Sherwood is perhaps the clearest example of why this table should not be used as a league table of district council performance.` },
    { type: 'paragraph', text: `The district council froze its own Band D charge at £198.60 for 2026/27.` },
    { type: 'paragraph', text: `Nottinghamshire County Council charges £1,970.13, Nottinghamshire Police £311.10 and the fire service £102.21. Parish charges are then added according to where the household is located.` },
    { type: 'paragraph', text: `In Alverton, for example, the total Band D bill is £2,582.04. In Balderton it is £2,712.45. Edwinstowe is £2,690.26.` },
    { type: 'paragraph', text: `The government's £2,682.10 figure averages those local variations across the district.` },
    { type: 'paragraph', text: `The ten highest official figures are therefore: Dorset £2,765.02; Lewes £2,756.17; Nottingham £2,755.39; Rutland £2,737.58; Wealden £2,728.43; Gateshead £2,715.81; Bristol £2,713.68; West Devon £2,705.33; Rother £2,700.95; and Newark and Sherwood £2,682.10.` },
    { type: 'paragraph', text: `Liverpool, Walsall, Reading, Northumberland, Newcastle and Coventry do not make the top ten on the government's 2026/27 area Band D measure. Liverpool is 13th and Walsall 21st. Coventry, at £2,516.72, is well outside the highest group.` },
    { type: 'paragraph', text: `The figures still tell residents something important about what a Band D household can face.` },
    { type: 'paragraph', text: `They do not, by themselves, tell residents whether their council is well run.` },
    { type: 'paragraph', text: `A unitary council responsible for social care cannot sensibly be judged against a district council responsible for waste collection, planning and housing services as though they were selling the same product. Nor can a district council be blamed for the county, police, fire and parish charges it is legally required to collect.` },
    { type: 'paragraph', text: `In two of England's ten most expensive council tax areas, Wealden and Newark and Sherwood, the district council did not increase its own charge at all this year.` },
    { type: 'paragraph', text: `They still appear fifth and tenth on the national table.` },
  ],
  evidence: {
    recordsReviewed: [
      `Ministry of Housing, Communities and Local Government, Council Tax levels set by local authorities in England 2026 to 2027, 25 March 2026: the principal official dataset; supports the £2,392 England average, the definition of area Band D, inclusion of adult social care and parish precepts, the £1,868 average per dwelling, the individual-authority data in Tables 8 to 10, and the full area Band D ranking (Dorset through Newark and Sherwood, plus Liverpool at 13th, Walsall at 21st and Coventry at £2,516.72)`,
      `Dorset Council and Dorset Police and Crime Commissioner, 2026/27 council tax information: supports Dorset's council element and the £322.58 police precept`,
      `Lewes District Council and East Sussex council tax records: supports Lewes District Council's £242.02 Band D element and the division of the wider bill between county, police, fire and parish authorities`,
      `Nottingham City Council, Bands and Charges 2026/27: supports Nottingham's £2,755.39 total and the breakdown between the city council, police and fire authority`,
      `Rutland County Council, 2026/27 budget and council tax information: supports the council's general council tax freeze, 2 per cent adult social care increase, £2,263.33 council element and funding-reliance figures; Rutland's own March 2026 press release claiming an "eighth" national ranking is not reconcilable with MHCLG's published area Band D figures, which place Rutland fourth`,
      `Wealden District Council, Our Spending Plans 2026/27: supports the £221.14 district element and its decision not to increase that element for 2026/27`,
      `Gateshead Council, Budget and Council Tax Level 2026/27: supports the £2,396.07 Gateshead element, 4.99 per cent increase and accompanying budget reductions and use of reserves`,
      `Bristol City Council, Council Tax Notice 2026 to 2027: supports the £2,713.68 total and its division between Bristol City Council, police and fire`,
      `Rother District Council, Council Tax 2026/27: supports Rother's £216.95 district charge, the £2,576.64 pre-parish total and the substantial variation in final bills between parishes`,
      `Newark and Sherwood District Council, Revenue Budget and Council Tax Setting 2026/27: supports the frozen £198.60 district element and the £1,970.13 Nottinghamshire County Council, £311.10 police and £102.21 fire precepts`,
    ],
    lastChecked: '5 October 2026',
  },
};

export default piece;
