import type { EditorialEntry } from './types';

// The ten highest council tax bills in England, 2026/27. Migrated from the
// stand-alone /council-tax page into the Investigations section so it shares
// the editorial chrome and typography. Figures are Band D, all precepts
// included. England average Band D 2026/27: £2,392.
const piece: EditorialEntry = {
  slug: 'cq4r8vn2mp',
  kicker: 'Council Tax',
  headline: 'The Ten Highest Council Tax Bills in England',
  standfirst:
    'The ten most expensive councils in England now charge a Band D bill of between £2,517 and £2,755 a year, every one of them well above the England average. Ranked, with an assessment of what residents get for the money.',
  publishedAt: '2026-06-30',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: 'Council tax has climbed again. The ten most expensive authorities in England now charge a Band D bill of between £2,517 and £2,755 a year, and every one of them sits well above the England average of £2,392. Together the ten charge a combined Band D bill of £26,493, an average of £2,649.' },
    { type: 'paragraph', text: 'The figures below are Band D for 2026/27 and include all precepts: council, police, fire, regional authority and parish where applicable. Each authority is ranked by its total bill, with an assessment of what residents actually receive in return.' },

    {
      type: 'councilEntry',
      rank: 1,
      name: 'Nottingham',
      councilSlug: 'nottingham',
      topLine: "England's most expensive major city for council tax. Band D 2026/27: £2,755, which is £363 above the England average.",
      paragraphs: [
        'Nottingham residents now pay the third highest council tax in England, behind only Dorset and Lewes. Among major cities it is the most expensive in the country. For a city that declared itself bankrupt three years ago, that fact lands heavily.',
        'For years, Nottingham City Council pursued ambitious projects and investments intended to generate income and reduce reliance on central government funding. The most famous was Robin Hood Energy, a council owned energy company that ultimately collapsed after losses running into tens of millions of pounds.',
        'The council effectively declared itself bankrupt in 2023 after issuing a Section 114 notice.',
        "To be fair, today's leadership inherited much of the fallout and has spent much of its time repairing rather than building. Financial controls have tightened and spending has come under greater scrutiny.",
        'Yet residents paying £2,755 a year are entitled to ask a difficult question: why should they carry the burden of mistakes they never made? That annual bill is £363 above the England average. A Band D household in Nottingham pays nearly three times what an equivalent household in Wandsworth pays.',
        "Nottingham remains a vibrant city. Its universities, businesses and cultural institutions are genuine strengths. The city deserves better than the governance failures that have defined much of the council's recent history.",
      ],
      verdict:
        'A city with enormous potential governed by an authority still trying to rebuild trust. Charging the highest council tax of any major English city while recovering from financial collapse makes value for money almost impossible to justify.',
    },
    {
      type: 'councilEntry',
      rank: 2,
      name: 'Rutland',
      councilSlug: 'rutland',
      topLine: "England's smallest county with England's second highest bill. Band D 2026/27: £2,738, which is £346 above the England average.",
      paragraphs: [
        'Rutland has a simple problem. It is tiny.',
        "Being England's smallest historic county means delivering services to approximately 41,000 residents while carrying many of the same responsibilities as authorities serving populations ten or twenty times larger. With fewer than 17,000 taxable properties, the same fixed costs are divided among far fewer households.",
        'The result is predictable: the second highest council tax in England.',
        'Unlike some councils on this list, Rutland is not associated with scandal, financial collapse or major governance failures. In many respects it is a reasonably well run authority. The £66.57 increase from 2025/26 was the smallest rise on this list, suggesting the council is not aggressively hiking charges.',
        'The problem is perception.',
        'Residents paying nearly £2,740 annually are not comparing themselves to local government accounting spreadsheets. They are comparing themselves to neighbouring areas where council tax is often hundreds of pounds lower.',
        'Road maintenance, transport links and access to services remain recurring concerns. Many residents accept the logic behind higher taxation but question whether the gap has become too large.',
        "Rutland's biggest weakness is that competence rarely feels exciting. Residents are effectively paying a premium simply because geography and demographics make local government more expensive.",
      ],
      verdict: 'Sensibly managed but expensive. The bill reflects structural reality more than exceptional service.',
    },
    {
      type: 'councilEntry',
      rank: 3,
      name: 'Gateshead',
      councilSlug: 'gateshead',
      topLine: 'The highest council tax in the North East. Band D 2026/27: £2,716, which is £324 above the England average.',
      paragraphs: [
        'Gateshead residents pay the highest council tax in the North East and the third highest on this list. For that price, residents might reasonably expect streets polished to a shine, public services running like clockwork and neighbourhoods that look like a showcase for local government success.',
        'The reality is more complicated.',
        "Gateshead Council has a strong case when it points to years of government funding reductions, rising demand for adult social care and increasing pressure on children's services. The council's own explanation is direct: a low tax base means areas like Gateshead appear to have disproportionately high council tax compared to other authorities. They are not wrong. These are genuine financial burdens faced by councils across the country.",
        'The council can also point to real achievements. Regeneration around Gateshead Quays has transformed parts of the borough. Investment has attracted visitors, businesses and cultural institutions. In terms of ambition, Gateshead has often looked more forward thinking than many comparable northern authorities.',
        'Yet residents do not live in regeneration brochures.',
        'Away from the waterfront developments and flagship projects, a different picture emerges. Concerns about litter, anti social behaviour, struggling high streets and tired public spaces remain familiar complaints. Many residents paying over £2,700 a year are entitled to ask why visible neighbourhood improvements do not always seem to match the scale of the tax bill landing on their doormat.',
        'Supporters argue the council is being judged unfairly. Social care now consumes huge portions of local authority budgets, leaving less money available for the services residents actually see.',
        "Critics counter that this explanation has become too convenient. Every council faces pressures. Gateshead's residents are paying more than almost anybody else. The higher the bill climbs, the less patience people have for explanations.",
        'For a council charging £2,716 a year, competence is not enough. Residents expect excellence.',
      ],
      verdict:
        'Ambitious and financially pressured, but charging premium prices creates premium expectations. Too often, residents still feel they are paying luxury rates for standard local government.',
    },
    {
      type: 'councilEntry',
      rank: 4,
      name: 'Bristol',
      councilSlug: 'bristol',
      topLine: 'A progressive city with very expensive problems. Band D 2026/27: £2,714, which is £322 above the England average.',
      paragraphs: [
        "Bristol is one of Britain's most successful cities. It attracts investment, graduates, technology firms and creative industries. On paper, it should be thriving.",
        'Yet Bristol residents paying over £2,700 a year often wonder where the money is going. The £130 increase from last year was among the steepest on this list.',
        'Housing affordability remains one of the city’s biggest failures. Congestion frustrates commuters daily. Homelessness remains highly visible. Public services operate under constant strain.',
        'The council excels at developing ambitious visions. Climate strategies, transport plans and regeneration projects rarely lack ambition.',
        'Delivery is another matter.',
        'Critics argue Bristol has become a city where consultation documents multiply faster than practical improvements. Residents often hear about long term transformation while dealing with short term frustrations.',
        "Supporters counter that Bristol's growth creates many of its challenges. More people means greater pressure on housing, roads and services.",
        'That is true, but it also means taxpayers reasonably expect solutions.',
      ],
      verdict: 'Dynamic city, frustrating council. Strong on ideas, weaker on execution.',
    },
    {
      type: 'councilEntry',
      rank: 5,
      name: 'Liverpool',
      councilSlug: 'liverpool',
      topLine: 'A great city, a troubled council. Band D 2026/27: £2,674, which is £282 above the England average.',
      paragraphs: [
        "Liverpool is one of Britain's great cities.",
        'Liverpool City Council is another matter.',
        'Government intervention followed serious concerns about governance, planning and procurement. Few councils have faced such public scrutiny in recent years.',
        'The city itself has undergone remarkable transformation. Tourism, culture, universities and private investment have changed Liverpool dramatically.',
        'Unfortunately, much of that progress has occurred alongside repeated questions about how the council conducts its business.',
        'The authority has improved since intervention began. Reforms have been implemented and oversight strengthened.',
        'But trust lost is not easily regained.',
        'Residents paying over £2,670 annually are entitled to ask why a council charging so much needed central government intervention in the first place. The £127 year on year increase means the bill is climbing faster than many household incomes.',
      ],
      verdict: 'Improving, but past failures continue to undermine confidence.',
    },
    {
      type: 'councilEntry',
      rank: 6,
      name: 'Walsall',
      councilSlug: 'walsall',
      topLine: 'Paying more, expecting more. Band D 2026/27: £2,627, which is £235 above the England average.',
      paragraphs: [
        "Walsall's council tax bill places it among the most expensive authorities in England, more than £230 above the national average. That comes as a surprise to some residents who struggle to identify obvious signs of premium service.",
        "The council deserves praise for maintaining financial stability and achieving strong results in children's services. Those are not small accomplishments.",
        'Yet outside official reports, many residents tell a different story.',
        'Town centre decline, anti social behaviour and economic stagnation dominate local conversations. Too many areas appear stuck between regeneration promises and visible reality.',
        "The council's defence is familiar: demand is rising, funding is tight and social care consumes growing proportions of the budget.",
        'All true.',
        'The problem is that residents rarely judge councils on adult social care budgets. They judge them on the streets they walk down every day.',
      ],
      verdict:
        "Strong in some critical services but struggling to convince residents they are getting value from one of England's highest tax bills.",
    },
    {
      type: 'councilEntry',
      rank: 7,
      name: 'Reading',
      councilSlug: 'reading',
      topLine: 'Prosperity with a premium price tag. Band D 2026/27: £2,613, which is £221 above the England average.',
      paragraphs: [
        'Reading benefits from something many councils would envy: a strong economy.',
        'Major employers, excellent transport connections and proximity to London should provide advantages that many local authorities can only dream about.',
        'Yet residents still face a council tax bill more than £220 above the national average.',
        'The council is generally regarded as competent and financially stable. There are no major scandals or dramatic failures.',
        'The criticism is more subtle.',
        'Residents often feel they are paying premium prices for ordinary outcomes. Housing remains expensive. Congestion remains severe. Public services remain under pressure.',
        'A prosperous town should make local government easier, not harder.',
      ],
      verdict: 'Competent administration, but residents are paying luxury prices for a service that often feels standard.',
    },
    {
      type: 'councilEntry',
      rank: 8,
      name: 'Northumberland',
      councilSlug: 'northumberland',
      topLine: 'Paying for distance. Band D 2026/27: £2,597, which is £205 above the England average.',
      paragraphs: [
        'Northumberland is unique on this list because geography explains much of the cost.',
        'The county stretches across vast rural areas. Roads must be maintained across enormous distances. Services must reach isolated communities. Transport costs are higher. Everything costs more.',
        "Unlike urban authorities, Northumberland cannot rely on dense populations to spread costs. The £132 year on year increase reflects both rising service costs and the structural disadvantage of serving England's most sparsely populated county.",
        'The council’s challenge is convincing residents that higher taxation genuinely reflects those realities rather than inefficiency.',
        'In fairness, the authority performs relatively well compared with many rural counterparts. Tourism investment, road maintenance and local services generally avoid the crises seen elsewhere.',
        'Yet rural residents still complain about disappearing services, weak transport links and growing isolation.',
      ],
      verdict: 'Expensive but largely understandable. Geography is a more convincing explanation than incompetence.',
    },
    {
      type: 'councilEntry',
      rank: 9,
      name: 'Newcastle',
      councilSlug: 'newcastle',
      topLine: 'Two cities in one. Band D 2026/27: £2,542, which is £150 above the England average.',
      paragraphs: [
        'Newcastle tells two very different stories.',
        'The first is the city centre. Regeneration, investment, universities and business growth have helped transform Newcastle into one of northern England’s strongest urban economies.',
        'The second story lies beyond the showcase areas.',
        'Residents frequently raise concerns about road conditions, litter, anti social behaviour and neighbourhood decline. Critics argue that the city often looks strongest where visitors spend time and weakest where residents live.',
        'The council deserves credit for attracting investment and navigating difficult financial pressures.',
        'But a council tax bill exceeding £2,500, with a £129 increase this year alone, creates expectations that extend beyond the city centre.',
      ],
      verdict: 'Strong regeneration record, inconsistent neighbourhood experience.',
    },
    {
      type: 'councilEntry',
      rank: 10,
      name: 'Coventry',
      councilSlug: 'coventry',
      topLine: 'Regeneration without universal reward. Band D 2026/27: £2,517, which is £125 above the England average.',
      paragraphs: [
        'Coventry has spent years reinventing itself.',
        'City of Culture status, regeneration projects and substantial investment have reshaped large parts of the city. Few councils can point to such visible transformation.',
        'Yet the council faces a recurring criticism.',
        'Residents see cranes, construction projects and ambitious announcements, but often struggle to identify equivalent improvements in everyday services.',
        'Road conditions, neighbourhood maintenance and local concerns frequently receive less attention than headline grabbing regeneration schemes.',
        'Supporters argue the council is planning for the future.',
        'Critics argue residents live in the present.',
        'Both sides have a point.',
        'The challenge facing Coventry is proving that investment eventually benefits every part of the city rather than a select number of flagship projects.',
      ],
      verdict:
        'Ambitious and forward looking, but many residents remain unconvinced they are receiving full value for a £2,517 annual bill.',
    },

    { type: 'paragraph', text: 'All figures are Band D council tax for 2026/27, including all precepts: council, police, fire, regional authority and parish where applicable. The England average Band D bill for 2026/27 is £2,392.' },
  ],
};

export default piece;
