import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'cr4k9mxw7r',
  kicker: 'Justice',
  headline: `Rape Case Backlog Rises 26% as Government Announces Specialist Courts`,
  standfirst: `Crown Court rape cases increased 26 per cent in a year, and there were a record 16,089 open sexual offence cases by June 2026. The government has announced specialist courtrooms with fixed trial dates and private facilities at every Crown Court. The backlog is still rising and one in four listed trials is still being rearranged.`,
  publishedAt: '2026-09-21',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `The government has announced specialist rape and serious sexual offence courtrooms in every Crown Court, with fixed trial dates, private waiting areas and extra support for victims.` },
    { type: 'paragraph', text: `The problem is that the rape backlog is still getting worse.` },
    { type: 'paragraph', text: `By the end of June, there were 16,089 open sexual offence cases in the Crown Court, the highest number on record, representing 20 per cent of the entire open caseload.` },
    { type: 'paragraph', text: `Open rape cases had risen 26 per cent in a year.` },
    { type: 'paragraph', text: `More than 23,700 Crown Court cases had already been waiting at least a year.` },
    { type: 'paragraph', text: `Around 11 per cent of them were rape cases, which works out at roughly 2,600 rape cases waiting more than 12 months.` },
    { type: 'paragraph', text: `That is the context for the government's latest reform.` },
    { type: 'paragraph', text: `Ministers say specialist courtrooms and fixed trial dates will make the process less traumatic for victims and reduce the uncertainty caused by delayed or moved hearings.` },
    { type: 'paragraph', text: `There is a clear case for that.` },
    { type: 'paragraph', text: `The government's own figures show why: rape cases that reached the Crown Court in 2025 took an average of 424 days to complete, and, in the government's own words, "too many victims" were withdrawing before their case was even heard.` },
    { type: 'paragraph', text: `But better rooms do not solve the capacity problem on their own.` },
    { type: 'heading', level: 2, text: `Rape cases are arriving faster` },
    { type: 'paragraph', text: `The pressure is not only coming from old cases stuck in the system.` },
    { type: 'paragraph', text: `The number of rape cases entering the Crown Court also reached a record in the latest quarter.` },
    { type: 'paragraph', text: `There were 1,516 rape cases received, including a 19 per cent annual rise in adult rape cases and a 10 per cent increase in child rape cases.` },
    { type: 'paragraph', text: `At the same time, the Crown Court as a whole disposed of fewer cases than a year earlier.` },
    { type: 'paragraph', text: `That is how backlogs grow.` },
    { type: 'paragraph', text: `More cases arrive.` },
    { type: 'paragraph', text: `Fewer are finished.` },
    { type: 'paragraph', text: `And the queue gets older.` },
    { type: 'heading', level: 2, text: `The system is still cancelling and moving trials` },
    { type: 'paragraph', text: `One of the government's selling points is that rape victims will receive fixed trial dates.` },
    { type: 'paragraph', text: `The latest court data explains why ministers think that is necessary.` },
    { type: 'paragraph', text: `Only 44 per cent of Crown Court trials began effectively as listed in the latest quarter.` },
    { type: 'paragraph', text: `Another 31 per cent cracked before trial, usually because of a guilty plea or some other change.` },
    { type: 'paragraph', text: `But 25 per cent were ineffective, meaning the trial had to be rearranged.` },
    { type: 'paragraph', text: `The largest single reason was overlisting.` },
    { type: 'paragraph', text: `That accounted for 27 per cent of ineffective trials.` },
    { type: 'paragraph', text: `Another 24 per cent were caused by the prosecution or defence not being ready.` },
    { type: 'paragraph', text: `In the same quarter, 6,197 trials were vacated before they started, 13 per cent more than a year earlier.` },
    { type: 'paragraph', text: `In 12 per cent of those cases, the reason was an anticipated lack of court time.` },
    { type: 'paragraph', text: `That is not a minor scheduling problem.` },
    { type: 'paragraph', text: `It is evidence of a court system operating beyond comfortable capacity.` },
    { type: 'heading', level: 2, text: `The wait is already more than a year for many defendants` },
    { type: 'paragraph', text: `Across jury trials generally, the median time from a case reaching the Crown Court to completion reached 418 days for defendants who pleaded not guilty.` },
    { type: 'paragraph', text: `From charge to completion, the median for that same group was 445 days, both series peaks.` },
    { type: 'paragraph', text: `By comparison, the median charge-to-completion time across all Crown Court defendants, including guilty pleas and cracked cases, was 189 days.` },
    { type: 'paragraph', text: `Rape cases sit at the slower end of that range: the 424-day average the government itself cites for 2025 shows they are not simply caught up in general court delay, but running close to the timescales seen for contested jury trials specifically.` },
    { type: 'paragraph', text: `The overall Crown Court backlog has reached 80,829 open cases, another record, a 3 per cent rise on the previous year.` },
    { type: 'paragraph', text: `The median age of an open case has risen to 203 days, also the highest in the series.` },
    { type: 'paragraph', text: `The backlog is not just large.` },
    { type: 'paragraph', text: `It is ageing.` },
    { type: 'heading', level: 2, text: `Better courtrooms are not the same as more court capacity` },
    { type: 'paragraph', text: `The specialist-court programme includes measures that could make the process less distressing for victims.` },
    { type: 'paragraph', text: `Private waiting areas and entrances. Facilities to pre-record evidence and observe sentencing remotely. Trauma-informed training for all court staff. A single point of contact for victims. Fixed trial dates instead of floating lists.` },
    { type: 'paragraph', text: `Those are practical improvements.` },
    { type: 'paragraph', text: `But they do not automatically create more judges, prosecutors, barristers or sitting days.` },
    { type: 'paragraph', text: `A courtroom can be designated as specialist.` },
    { type: 'paragraph', text: `That does not guarantee someone is available to hear the case.` },
    { type: 'paragraph', text: `The rollout is planned over the next two years and the government describes it as backed by "a multi-million cash injection."` },
    { type: 'paragraph', text: `It does not give a single clear figure for the total cost or say how much extra trial capacity will actually be created.` },
    { type: 'paragraph', text: `That is the part that should be measured.` },
    { type: 'paragraph', text: `How many additional rape trials can the system hear? How many extra sitting days will be created? How many judges and prosecutors are available?` },
    { type: 'paragraph', text: `Without those numbers, the physical courtroom upgrade risks being mistaken for a capacity increase.` },
    { type: 'heading', level: 2, text: `Delay can make cases collapse` },
    { type: 'paragraph', text: `The government itself acknowledges that "too many" victims withdraw before trial.` },
    { type: 'paragraph', text: `That means delay is not simply administrative inconvenience.` },
    { type: 'paragraph', text: `It can affect whether a case survives at all.` },
    { type: 'paragraph', text: `Someone reporting rape may spend more than a year waiting for a trial while being asked to remain engaged with the justice system and prepare to give evidence.` },
    { type: 'paragraph', text: `If that date is then moved, the wait starts stretching again.` },
    { type: 'paragraph', text: `The government's move towards fixed dates is therefore sensible.` },
    { type: 'paragraph', text: `It is also an admission that the current system has not been giving rape victims enough certainty.` },
    { type: 'heading', level: 2, text: `The government is improving the room while the queue gets longer` },
    { type: 'paragraph', text: `The specialist-court programme may make a real difference to individual victims.` },
    { type: 'paragraph', text: `It may reduce the number of last-minute changes.` },
    { type: 'paragraph', text: `It may make giving evidence less traumatic.` },
    { type: 'paragraph', text: `But it is being introduced into a system where open rape cases are up 26 per cent in a year; sexual offence cases have reached a record 16,089; around 2,600 rape cases have already been waiting more than a year; rape cases took an average of 424 days to complete in 2025; and one in four listed Crown Court trials still has to be rearranged.` },
    { type: 'paragraph', text: `That is the harder story.` },
    { type: 'paragraph', text: `The government is trying to make rape trials work better.` },
    { type: 'paragraph', text: `But unless it also creates enough capacity to hear them, victims may still be waiting behind a growing queue.` },
    { type: 'paragraph', text: `A better courtroom matters.` },
    { type: 'paragraph', text: `So does getting into it.` },
  ],
  evidence: {
    recordsReviewed: [
      'GOV.UK, 21 September 2026: "Specialist rape courts rolled out across the country" — programme features (fixed trial dates, private entrances and waiting rooms, pre-recorded evidence, trauma-informed staff training, single point of contact), two-year rollout, "multi-million cash injection" funding language, 424-day average rape case completion time for 2025, acknowledgment that "too many" victims withdraw before trial',
      'Ministry of Justice, Criminal Court Statistics Quarterly: April to June 2026 — 16,089 open sexual offence cases (series peak, 20% of open caseload); 26% annual rise in open rape cases; 80,829 total open cases (3% annual rise); 23,706 cases open a year or more (11% rape, ~2,600); 1,516 rape cases received (19% adult rise, 10% child rise); trial effectiveness: 44% effective, 31% cracked, 25% ineffective; ineffective-trial causes: 27% overlisting, 24% prosecution/defence not ready; 6,197 vacated trials (up 13%, 12% due to anticipated lack of court time); median receipt-to-completion 418 days and charge-to-completion 445 days for not-guilty jury trials; 189-day median across all defendants; median open-case age 203 days',
    ],
    lastChecked: '30 September 2026',
  },
};

export default piece;
