import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'dk9m2xq7w4',
  kicker: 'Safeguarding',
  headline: `DUP Says Members Had Information About Donaldson. No Complaint Reached Party Officers`,
  standfirst: `DUP leader Gavin Robinson said on 29 June that it was "clear" some current and former members of his party had information about Jeffrey Donaldson's conduct before his arrest and did not pass it through the party's reporting channels. That does not establish that those members knew Donaldson was sexually abusing children. The distinction is now central to an independent review commissioned by the DUP after Donaldson was convicted of 18 sexual offences against two women when they were children.`,
  publishedAt: '2026-07-16',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `DUP leader Gavin Robinson said on 29 June that it was "clear" some current and former members of his party had information about Jeffrey Donaldson's conduct before his arrest and did not pass it through the party's reporting channels.` },
    { type: 'paragraph', text: `That does not establish that those members knew Donaldson was sexually abusing children.` },
    { type: 'paragraph', text: `The distinction is now central to an independent review commissioned by the DUP after Donaldson was convicted at Newry Crown Court on 22 June of 18 sexual offences against two women when they were children. The jury found him guilty of one count of rape, 13 counts of indecent assault and four counts of gross indecency. The offences took place between 1985 and 2008. He was remanded in custody awaiting sentencing.` },
    { type: 'paragraph', text: `Four days after the verdict, the DUP said allegations emerging publicly suggested that some people may have known about "inappropriate behaviour" which had never been reported to party officers. It commissioned a specialist review.` },
    { type: 'paragraph', text: `Robinson went further three days later. He said there were former and current members who had information they had not shared, leaving the party unable to act formally. But he also maintained that the DUP itself had not been made aware of the allegations that subsequently emerged.` },
    { type: 'paragraph', text: `Some of what is already publicly known illustrates why those statements need separating from Donaldson's convictions.` },
    { type: 'paragraph', text: `DUP minister Paul Givan said he had heard rumours about Donaldson's behaviour involving adults, but said they were not rumours about offences against children and were not criminal in nature.` },
    { type: 'paragraph', text: `Stormont Speaker Edwin Poots separately said "quite a number of people within the DUP" knew that a woman had raised concerns about Donaldson. Poots said he had been told that Donaldson was sending the woman texts she did not want. He said nothing reported to him suggested criminal behaviour or a safeguarding issue, and that the woman did not want to take the matter further.` },
    { type: 'paragraph', text: `Those accounts may prove relevant to how the party handled warnings about a powerful politician. They are not evidence that party members knew about the child sexual offences for which Donaldson was later convicted.` },
    { type: 'paragraph', text: `The DUP says it never received a complaint, either internally or externally, about improper or criminal behaviour by Donaldson before the case became public.` },
    { type: 'paragraph', text: `PSNI Chief Constable Jon Boutcher has also urged caution about speculation surrounding the case. On 2 July he said the first allegations against Donaldson were made to the PSNI in March 2024 and that Donaldson was arrested three weeks later. He described some of the wider claims circulating after the trial as unfounded and warned that criminal proceedings had not yet concluded.` },
    { type: 'paragraph', text: `The DUP's review is supposed to establish what happened inside the party before that point.` },
    { type: 'paragraph', text: `On 9 July, the party published an initial set of terms of reference. The review, led by former Child Exploitation and Online Protection Centre chief Jim Gamble and his iNEQE Safeguarding Group, is to establish what, if any, information was known within the DUP concerning allegations of inappropriate conduct relating to safeguarding.` },
    { type: 'paragraph', text: `It is specifically supposed to identify who knew, when they knew, who the information came from and whether it took the form of an eyewitness account, formal complaint, disclosure, concern, rumour or warning. It will also examine what action was or was not taken.` },
    { type: 'paragraph', text: `Members are to be given a confidential route to provide information, and iNEQE will examine the party's safeguarding and reporting arrangements.` },
    { type: 'paragraph', text: `That is considerably more precise than simply asking who "knew about Donaldson". A rumour about legal behaviour between adults, an unwanted message, a safeguarding warning and a disclosure of sexual abuse are not equivalent pieces of information.` },
    { type: 'paragraph', text: `As of 16 July, however, the complete rules governing the review had not been published.` },
    { type: 'paragraph', text: `The DUP's 9 July announcement said the full terms of reference would be published by iNEQE when its dedicated website launched. That means the public had not yet been told, in the material released by the party, what access the reviewers would have to internal messages and documents, how non-cooperation would be handled, whether current and former members could be required to provide material, when the review was expected to finish or what commitment existed to publish its eventual findings.` },
    { type: 'paragraph', text: `The DUP has described the exercise as "entirely independent" of the party. Independence of the reviewers and the powers available to them are separate questions. A privately commissioned safeguarding review is not the same thing as a statutory inquiry with powers to compel evidence.` },
    { type: 'paragraph', text: `There is already another review running at Stormont.` },
    { type: 'paragraph', text: `The Northern Ireland Assembly published its terms on 10 July. Its inquiry is narrower, covering possible abuse or inappropriate behaviour while Donaldson was an MLA between 2003 and 2010 or visiting Parliament Buildings as an MP. It has a public timetable: information can be submitted between 10 July and 21 August, with a report due to the Clerk and Chief Executive by 28 August.` },
    { type: 'paragraph', text: `Its published terms also require the reviewer to consider how much of the findings, or a summary, can be made public.` },
    { type: 'paragraph', text: `The DUP review has also encountered a separate challenge over the organisation chosen to conduct it.` },
    { type: 'paragraph', text: `iNEQE was already carrying out an independent governance and safeguarding review for the Presbyterian Church in Ireland, commissioned in March after the church acknowledged serious safeguarding failures and following the opening of a statutory inquiry by the Charity Commission for Northern Ireland.` },
    { type: 'paragraph', text: `On 15 July, the Northern Ireland Survivor Council raised concerns about iNEQE undertaking both pieces of work. Its safeguarding spokeswoman Marcella Leonard said Donaldson's victims had disclosed abuse to the church and argued that running the two reviews through the same organisation created a risk of information becoming blurred between them.` },
    { type: 'paragraph', text: `That is a concern raised by the council, not evidence that information has actually been mixed or that iNEQE lacks independence. Gamble offered to meet the council and said his priority was to hear from victims and explain the safeguards surrounding the reviews.` },
    { type: 'paragraph', text: `Donaldson's crimes also span a period much longer than his DUP membership. He joined the party in 2004 after leaving the Ulster Unionist Party, while the offences for which he was convicted ran from 1985 until 2008. A DUP review can therefore answer questions about what happened within the DUP, but not what institutions outside it knew across the whole period in which the offences occurred.` },
    { type: 'paragraph', text: `The evidence available so far supports a narrower question than some of the political argument that has followed the conviction.` },
    { type: 'paragraph', text: `Senior DUP figures accept that some members possessed information about Donaldson which was never formally reported. Public accounts show that at least some of that information concerned behaviour towards adults which those involved say was not understood to be criminal or related to child safeguarding.` },
    { type: 'paragraph', text: `What has not yet been established is whether anybody in the DUP received a more serious warning, disclosure or complaint, whether Donaldson's position affected how it was handled, or whether the party's procedures were capable of dealing with concerns about its own leader.` },
    { type: 'paragraph', text: `Those are precisely the questions the review has been commissioned to answer.` },
    { type: 'paragraph', text: `As of 16 July, the DUP had not yet published its full terms of reference.` },
  ],
  evidence: {
    recordsReviewed: [
      `Democratic Unionist Party, statement announcing the review, 26 June 2026: the party's acknowledgement that some people may have known about inappropriate behaviour which was not reported to party officers`,
      `Democratic Unionist Party, Statement – Democratic Unionist Party, 9 July 2026: the initial terms of reference, the appointment of iNEQE and Jim Gamble, the party's assertion that it had received no complaint about Donaldson's behaviour, and the statement that fuller terms would be published later`,
      `UTV, interview and reporting on Gavin Robinson, 29 June 2026: Robinson's statement that current and former members held information which had not been shared through party channels`,
      `UTV, 26 June 2026: Paul Givan's account that rumours he had heard concerned adults and were not understood to involve criminal behaviour or offences against children`,
      `Press Association reporting on Edwin Poots, 30 June 2026: Poots's account of concerns involving unwanted texts and his statement that nothing relayed to him suggested a criminal or safeguarding matter`,
      `PSNI Chief Constable Jon Boutcher, Northern Ireland Policing Board evidence reported by UTV, 2 July 2026: the statement that the first allegations to PSNI were made in March 2024 and Boutcher's warning against unsupported speculation`,
      `Northern Ireland Assembly, Review of Alleged Abuse or Inappropriate Behaviour Associated with Jeffrey Donaldson in Parliament Buildings, 10 July 2026: the Assembly review's scope, public timetable, reporting deadline and published terms of reference`,
      `Presbyterian Church in Ireland, Independent Governance & Safeguarding Review appointed, 27 March 2026: iNEQE's separate appointment to review governance and safeguarding within the church`,
      `UTV, 15 July 2026: the Northern Ireland Survivor Council's concerns about iNEQE conducting both reviews and Jim Gamble's response`,
      `Newry Crown Court proceedings, reported by Reuters and Press Association, 22 June 2026: the 18 guilty verdicts, their breakdown, the period covered by the offences and Donaldson's remand in custody pending sentence`,
    ],
    lastChecked: '4 October 2026',
  },
};

export default piece;
