import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'dn4p8rk2wq',
  kicker: 'Defence',
  headline: `Government Says Its Defence Plan Will Support 60,000 More Jobs. Its Model Does Not Count the Jobs Lost Elsewhere`,
  standfirst: `The government says its Defence Investment Plan will support nearly 60,000 additional jobs by 2029/30. Its own methodology does not estimate how many jobs may disappear from the spending programmes being cut to pay for it. The Ministry of Defence made that limitation explicit in a methodology paper published on 8 July.`,
  publishedAt: '2026-07-09',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `The government says its Defence Investment Plan will support nearly 60,000 additional jobs by 2029/30.` },
    { type: 'paragraph', text: `Its own methodology does not estimate how many jobs may disappear from the spending programmes being cut to pay for it.` },
    { type: 'paragraph', text: `The Ministry of Defence made that limitation explicit in a methodology paper published on 8 July.` },
    { type: 'paragraph', text: `Its forecast estimates direct and supply-chain jobs supported by future defence spending. It assumes 53 per cent of Ministry of Defence expenditure continues to go to UK industry and projects historical spending-per-job ratios forward.` },
    { type: 'paragraph', text: `The department says the resulting figures provide only a "broad indication" of potential employment. It has not designated them as Official Statistics because they do not sufficiently meet the required quality standard.` },
    { type: 'paragraph', text: `Most importantly, the methodology says:` },
    { type: 'paragraph', text: `"We do not try to estimate the 'crowding out' of jobs elsewhere in the economy."` },
    { type: 'paragraph', text: `That omission matters because much of the additional defence spending is being financed by reducing investment elsewhere.` },
    { type: 'paragraph', text: `The government announced an extra £15 billion for defence between 2026/27 and 2029/30.` },
    { type: 'paragraph', text: `It has so far identified £10.3 billion of funding. The remaining £4.7 billion will not be identified until the 2026 Budget.` },
    { type: 'paragraph', text: `Four billion pounds is to come from cutting 1 per cent from departmental capital budgets across government.` },
    { type: 'paragraph', text: `The Department for Energy Security and Net Zero must find another £2 billion.` },
    { type: 'paragraph', text: `The Department for Transport must provide up to £700 million from roads spending.` },
    { type: 'paragraph', text: `The government has also identified asset sales, changes within the Ministry of Defence and Treasury support for international commitments and procurement as part of the package.` },
    { type: 'paragraph', text: `Those are not all equivalent to cancelling infrastructure.` },
    { type: 'paragraph', text: `Some savings may come from efficiencies, delays, asset sales or projects which had not yet been contractually committed.` },
    { type: 'paragraph', text: `But some projects are explicitly at risk.` },
    { type: 'paragraph', text: `The government has named the A38 Derby Junctions and A46 Newark Bypass as schemes that could be cancelled to contribute to the roads savings.` },
    { type: 'paragraph', text: `As of 9 July, neither cancellation had been finally decided. Both were due to go through consultation.` },
    { type: 'paragraph', text: `That is narrower than saying the road schemes have already been cancelled.` },
    { type: 'paragraph', text: `The position on energy is less transparent.` },
    { type: 'paragraph', text: `The £2 billion reduction is spread across the four years to 2029/30 and includes £400 million of financial transactions. Ministers say the Department for Energy Security and Net Zero will still have the fastest-growing capital budget of any department over the Spending Review period and that the clean-power mission, renewable energy and nuclear investment will be protected.` },
    { type: 'paragraph', text: `They have not yet published the programmes that will lose money.` },
    { type: 'paragraph', text: `The funding statement says more detailed plans will come in the autumn.` },
    { type: 'paragraph', text: `That means claims that particular projects have already been sacrificed need treating cautiously.` },
    { type: 'paragraph', text: `The Acorn carbon capture project in north-east Scotland is one example.` },
    { type: 'paragraph', text: `The government committed £200 million of development funding to Acorn in the 2025 Spending Review. As recently as 5 June, energy minister Michael Shanks told Parliament that the government continued to support Acorn and the Viking carbon-capture clusters and was working with them towards the next investment stage.` },
    { type: 'paragraph', text: `There was no published evidence by 9 July that Acorn had been selected for the £2 billion of energy savings.` },
    { type: 'paragraph', text: `The risk to energy investment is real. Naming Acorn as a casualty before ministers identify the cuts is not.` },
    { type: 'paragraph', text: `The employment argument is more complicated.` },
    { type: 'paragraph', text: `The Transition Security Project, a research organisation critical of expanding military spending, modelled the jobs effect of moving investment from other departments into defence.` },
    { type: 'paragraph', text: `Its estimate is that the funding settlement could mean around 10,000 fewer UK jobs on a net basis by 2029/30 than if the money remained in the programmes being cut.` },
    { type: 'paragraph', text: `That is a modelled estimate, not 10,000 identified workers who have been given redundancy notices.` },
    { type: 'paragraph', text: `The researchers started with the government's own claim that higher defence spending will support an additional 60,000 direct and indirect jobs.` },
    { type: 'paragraph', text: `The increase in annual defence spending between their reference year and 2029/30 works out at about £25.2 billion. On that basis, the government's forecast is equivalent to roughly 2.4 additional direct and indirect UK jobs for each £1 million of additional defence spending.` },
    { type: 'paragraph', text: `The researchers then compared that with employment intensity in sectors losing capital funding.` },
    { type: 'paragraph', text: `Using Office for National Statistics data, they estimated that £1 million of transport output supports about 11.5 jobs, while the equivalent figure for energy and net-zero activity is around 10.` },
    { type: 'paragraph', text: `Applying those ratios to the capital reductions produces nearly twice as many jobs displaced from the affected sectors as the extra defence spending is estimated to support, leaving a net reduction of around 10,000 jobs in their model.` },
    { type: 'paragraph', text: `There are reasons not to treat that number as a prediction carved in stone.` },
    { type: 'paragraph', text: `The sectors do not purchase identical things.` },
    { type: 'paragraph', text: `Defence contracts can support highly paid engineering, manufacturing and research jobs with different productivity and supply-chain effects from construction. Infrastructure projects also import goods and equipment. The precise projects that will bear many of the government cuts have not yet been announced.` },
    { type: 'paragraph', text: `The Ministry of Defence's own forecast carries substantial uncertainty too.` },
    { type: 'paragraph', text: `It assumes the share of defence spending going to UK industry remains fixed at 53 per cent until 2030. It uses recent average expenditure per job rather than modelling individual future programmes. It does not know in advance which industrial sectors all the new spending will fall into.` },
    { type: 'paragraph', text: `Its methodology also acknowledges that future efficiency improvements could reduce the number of jobs supported.` },
    { type: 'paragraph', text: `So there are two models here, not an observed result.` },
    { type: 'paragraph', text: `The government models almost 60,000 additional defence-related jobs.` },
    { type: 'paragraph', text: `The Transition Security Project uses that claim alongside employment data from the sectors losing capital investment and arrives at a net jobs reduction.` },
    { type: 'paragraph', text: `Only one of those calculations was included in the government's launch.` },
    { type: 'paragraph', text: `Keir Starmer said every pound in the Defence Investment Plan would "work twice", strengthening national security while delivering economic growth and supporting more than half a million defence-related jobs by the end of the decade.` },
    { type: 'paragraph', text: `The defence rationale is substantial.` },
    { type: 'paragraph', text: `The plan includes £5 billion for drones and autonomous systems, £11 billion for weapons and munitions, investment in new energetics factories, £8.6 billion for the Global Combat Air Programme and £64 billion associated with renewal of the nuclear deterrent.` },
    { type: 'paragraph', text: `Russia's war in Ukraine has demonstrated the rate at which ammunition and equipment can be consumed in a major conflict. The government has also committed through NATO to a substantially higher defence-spending trajectory.` },
    { type: 'paragraph', text: `A government can reasonably decide that national security is worth funding even if another form of public investment would support more jobs per pound.` },
    { type: 'paragraph', text: `That is a defence argument.` },
    { type: 'paragraph', text: `It is different from claiming the reallocation is unambiguously a jobs programme.` },
    { type: 'paragraph', text: `Andrea Egan, general secretary of Unison, attacked the trade-off after the employment analysis was published, saying cuts to government departments used to finance military spending would cost jobs and leave less money for schools and hospitals.` },
    { type: 'paragraph', text: `The government rejects that characterisation. It says the reductions come from capital spending rather than day-to-day frontline budgets and that defence itself already supports hundreds of thousands of jobs.` },
    { type: 'paragraph', text: `Both points can be true.` },
    { type: 'paragraph', text: `A nurse's salary is not being transferred directly into a missile contract.` },
    { type: 'paragraph', text: `Capital budgets that would otherwise finance roads, energy schemes and other investment are nevertheless being reduced to increase defence spending.` },
    { type: 'paragraph', text: `Those projects employ people too.` },
    { type: 'paragraph', text: `The unresolved £4.7 billion makes the calculation harder still.` },
    { type: 'paragraph', text: `The government had not identified that money by 9 July. If it is eventually raised through further reductions to departmental capital spending, the employment trade-off would grow. If ministers fund it another way, it may not.` },
    { type: 'paragraph', text: `The Transition Security Project estimates that proportional departmental cuts used to find the remaining £4.7 billion could more than double its estimated net job effect.` },
    { type: 'paragraph', text: `That scenario is not government policy as currently specified. The Budget will determine how the missing money is found.` },
    { type: 'paragraph', text: `The government therefore has two separate gaps in the case it presented on 30 June.` },
    { type: 'paragraph', text: `It has not yet identified £4.7 billion of the £15 billion funding package.` },
    { type: 'paragraph', text: `And when it says the plan will support almost 60,000 additional jobs, its published methodology does not count employment lost from the capital programmes being reduced to finance it.` },
  ],
  evidence: {
    recordsReviewed: [
      `Ministry of Defence, Estimates of future jobs supported by the Defence Investment Plan, 8 July 2026: explains the methodology behind the government's jobs estimates, states that they are not Official Statistics, records the 53 per cent UK-industry assumption and confirms that the model does not estimate jobs crowded out elsewhere in the economy`,
      `Ministry of Defence and HM Treasury, Defence Investment Plan Funding Explainer, 30 June 2026: sets out the £15 billion additional package, £10.3 billion of identified funding, £4.7 billion still to be found, 1 per cent reductions to departmental capital budgets, £2 billion of DESNZ savings and reductions to roads funding; gives the nuclear deterrent figure as £64 billion`,
      `HM Treasury written answer 14469, 6 July 2026: confirms that the A38 Derby Junctions and A46 Newark Bypass were being considered for cancellation but that no final decision had yet been taken`,
      `Department for Energy Security and Net Zero written answer on Acorn and Viking, 5 June 2026: confirms continuing development support for both carbon-capture clusters before publication of the Defence Investment Plan`,
      `Transition Security Project, Buying the Dip: The Defence Investment Plan Will Lead to Domestic Unemployment, 3 July 2026: provides the model estimating around 10,000 fewer net jobs by 2029/30 and explains how the government's defence employment estimate was compared with employment intensity in sectors losing capital investment`,
      `Guardian, 2 July 2026: reports the Transition Security Project analysis, the transport and energy employment ratios used, Unison's response and the government's defence of its employment claims`,
      `Prime Minister's Office, £15 billion new funding boost to transform armed forces and keep the UK safe, 30 June 2026: source for Starmer's "work twice" quote; gives the nuclear deterrent figure as "more than £63 billion" — the article uses £64 billion, the figure given in three of the four government documents including the Defence Secretary's Commons statement`,
    ],
    lastChecked: '5 October 2026',
  },
};

export default piece;
