import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'dw4k9mxw7r',
  kicker: 'Environment',
  headline: `Government Says Waste Criminals Have 'No Hiding Place'. Its Own Documents Can't Agree When the System Will Actually Close`,
  standfirst: `From 1 October, around 12,000 permitted waste sites in England must record incoming loads digitally under a new compulsory tracking regime. Waste collectors are not yet included. The government's press release says carriers must join from spring 2027; its implementation guidance says October 2027. The evidence base for the policy's £900 million annual waste-crime estimate was last refreshed in 2018/19.`,
  publishedAt: '2026-10-01',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `The government says waste criminals now have "no hiding place" under a new digital tracking system launched across England.` },
    { type: 'paragraph', text: `The compulsory system does not yet cover the whole waste chain, and the government's own paperwork does not agree on when it will.` },
    { type: 'paragraph', text: `From 1 October, around 12,000 permitted waste sites must digitally record the loads they receive, including the waste carrier's details and the waste classification code. Ministers say this will make it harder for criminals to hide behind false paperwork and give the Environment Agency a clearer picture of where waste ends up, by flagging discrepancies between what carriers report collecting and what sites report receiving.` },
    { type: 'paragraph', text: `The gap is what happens before that waste reaches a legal site.` },
    { type: 'paragraph', text: `Here the government's own documents give conflicting timelines. Defra's press release says the system will extend to waste collectors "from spring 2027." Its separate implementation guidance says mandatory digital tracking for carriers, brokers and dealers does not begin until October 2027. Those are two different dates for the same gap, published by the same department, in the same announcement cycle. Until whichever date turns out to be correct, that part of the service remains in development.` },
    { type: 'paragraph', text: `That matters because the operators most likely to avoid the legitimate system are also the ones least likely to deliver waste to a permitted site in the first place.` },
    { type: 'paragraph', text: `Illegal dumping, rogue carriers and unlawful waste sites are not automatically captured simply because legal sites now record what arrives through their gates.` },
    { type: 'paragraph', text: `So the government's "no hiding place" claim is ahead of the system it has actually launched, and, on the evidence of its own documents, ahead of a system whose finish date it has not yet settled internally.` },
    { type: 'paragraph', text: `Defra's technical implementation guidance is more cautious than the press release. It describes the rollout as incremental, built so that "a firm foundation... delivers some of the intended benefits," with further functionality "added as we learn from testing the core elements," moving toward "a more complete end-to-end waste tracking service" later.` },
    { type: 'paragraph', text: `The press release does not lead with that distinction, or with the fact that its own stated collector timeline does not match the department's guidance document.` },
    { type: 'heading', level: 2, text: `Waste crime costs about £900m a year, on data last properly measured in 2018/19` },
    { type: 'paragraph', text: `There is a serious problem behind the policy.` },
    { type: 'paragraph', text: `Defra estimates waste crime costs England around £900 million a year, in 2020 prices, derived from a more specific £924 million figure for 2018/19, set out in a 2021 study commissioned by the Environmental Services Association. The cost covers illegal waste sites, illegal burning, fly-tipping, misclassification and fraud, illegal exports, breaches of waste permits, and the enforcement cost this all imposes on local authorities and the Environment Agency.` },
    { type: 'paragraph', text: `A digital trail could make enforcement easier.` },
    { type: 'paragraph', text: `If regulators can see what waste was produced, who moved it and where it ended up, unusual patterns become easier to spot.` },
    { type: 'paragraph', text: `That is the logic behind the new system.` },
    { type: 'paragraph', text: `But the strongest version of that logic depends on tracking the waste from one end of the chain to the other.` },
    { type: 'paragraph', text: `That is not what starts today.` },
    { type: 'paragraph', text: `For the first phase, compulsory reporting is concentrated on permitted receiving sites.` },
    { type: 'paragraph', text: `The collection and transport side of the chain follows later, at a date the government's own documents currently state two different ways.` },
    { type: 'paragraph', text: `That leaves a fairly obvious blind spot.` },
    { type: 'paragraph', text: `A compliant transfer station will report what it receives.` },
    { type: 'paragraph', text: `A rogue operator dumping waste in a field may never enter the digital trail at all.` },
    { type: 'paragraph', text: `And the £900 million figure used to justify closing that gap rests on waste-crime data that is now several years old. The Regulatory Policy Committee, reviewing Defra's own impact assessment, noted the analysis "would have benefitted from" evaluating how waste crime costs have changed since that 2018/19 baseline, a gap in the evidence that the government has not yet filled.` },
    { type: 'heading', level: 2, text: `Legitimate businesses start paying before the full system exists` },
    { type: 'paragraph', text: `The new regime also carries a significant cost for compliant firms.` },
    { type: 'paragraph', text: `The Regulatory Policy Committee accepted Defra's estimate that mandatory digital waste tracking will impose an equivalent annual net direct cost of around £40.8 million on business.` },
    { type: 'paragraph', text: `The estimated business net present cost is about £174 million over the appraisal period.` },
    { type: 'paragraph', text: `Set against that, the RPC's assessment puts the policy's overall net present value, once the wider social benefits of reduced waste crime and better enforcement are included, at a positive £172.1 million. On the government's own figures, this is not a policy that costs society money overall; it is one that shifts a real, quantified cost onto compliant businesses now in exchange for a benefit the RPC expects to be larger, but has not yet been delivered, measured, or, per its own caveat, fully evidenced.` },
    { type: 'paragraph', text: `The RPC still judged the assessment fit for purpose, writing that it "provides sufficient evidence and analysis... to validate the EANDCB."` },
    { type: 'paragraph', text: `But the RPC's sign-off came with two specific qualifications the government's announcement does not mention: that the benefit estimates "may be overestimated as a result of quantifying baseline costs of a new IT system but not the potential benefits" with equal rigour, and that the evidence underpinning the headline waste-crime cost has not been refreshed since 2018/19.` },
    { type: 'paragraph', text: `So the issue is not that the scheme is obviously poor value, the RPC's own numbers say the opposite.` },
    { type: 'paragraph', text: `It is that legitimate operators start carrying a quantified cost now, against a benefit that the government's own regulator says may be overstated, delivered through a system whose most important remaining phase does not yet have one agreed start date.` },
    { type: 'heading', level: 2, text: `The weakest point is exactly where criminals operate` },
    { type: 'paragraph', text: `This is the central weakness in the launch.` },
    { type: 'paragraph', text: `A permitted waste site is already inside the regulatory system.` },
    { type: 'paragraph', text: `The government knows where it is. It can inspect it. It can require records.` },
    { type: 'paragraph', text: `The harder part has always been the movement of waste outside compliant channels.` },
    { type: 'paragraph', text: `Who collected it? Where did it go? Was the carrier registered? Was the paperwork accurate? Did the waste arrive at the destination listed?` },
    { type: 'paragraph', text: `Digital tracking can eventually help answer those questions.` },
    { type: 'paragraph', text: `But the collection-side obligations are not mandatory yet, and the government cannot currently tell the public, consistently, when they will be.` },
    { type: 'paragraph', text: `That means the part of the chain most vulnerable to disappearing waste remains both the least complete part of the new system and the part with the least certain timeline.` },
    { type: 'heading', level: 2, text: `The test comes whenever the carrier phase actually lands` },
    { type: 'paragraph', text: `The real value of digital waste tracking will be easier to judge once carriers, brokers and dealers are also inside the compulsory system, whether that arrives in spring 2027 as the launch announcement says, or October 2027 as the implementation guidance says.` },
    { type: 'paragraph', text: `At that point regulators should be able to follow waste from collection to destination rather than relying mainly on what arrives at permitted sites.` },
    { type: 'paragraph', text: `Then the questions become measurable.` },
    { type: 'paragraph', text: `Did illegal waste sites fall? Did fly-tipping decline? Did prosecutions increase? Did regulators identify false transfers more quickly?` },
    { type: 'paragraph', text: `Did the £40 million-plus annual compliance cost produce the roughly £172 million net benefit the RPC's own modelling implies it should?` },
    { type: 'paragraph', text: `And was the £900 million justification for the whole programme ever updated with waste-crime data more recent than 2018/19?` },
    { type: 'paragraph', text: `Until then, the government has launched an important piece of the system, not the finished product, and has not yet decided, in its own paperwork, exactly when the rest of it arrives.` },
    { type: 'paragraph', text: `The digital trail is getting longer.` },
    { type: 'paragraph', text: `It is not yet complete, and the government does not currently agree with itself about when it will be.` },
  ],
  evidence: {
    recordsReviewed: [
      'GOV.UK, 1 October 2026: "No hiding place: new tracking system exposes waste criminals like never before" — 12,000-site figure, 1 October 2026 start date, recording requirements (carrier details, waste classification codes), Environment Agency enforcement use, "spring 2027" collector-rollout date',
      'GOV.UK, "Digital waste tracking service" implementation guidance — incremental rollout description; October 2026 (England/Wales) and January 2027 (Scotland/Northern Ireland) receiving-site dates; October 2027 mandatory date for waste collectors (conflicts with press release\'s "spring 2027")',
      'The Digital Waste Tracking (England) Regulations 2026, impact assessment — £900m/year (2020 prices) waste-crime cost estimate; underlying £924m figure for 2018/19; basis in 2021 Eunomia/ESA "Counting the Cost of UK Waste Crime" study; categories covered (illegal sites, burning, fly-tipping, misclassification, exports, permit breaches, enforcement costs)',
      'RPC opinion on the impact of mandatory digital waste tracking — £40.8m EANDCB; £174.1m business net present cost; +£172.1m overall net present value; "fit for purpose" rating; caveat that benefits "may be overestimated"; caveat that waste-crime evidence base not updated since 2018/19',
    ],
    lastChecked: '1 October 2026',
  },
};

export default piece;
