import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'em7k4mxw9n',
  kicker: 'Criminal Justice',
  headline: `5,043 People With Electronic Monitoring Orders Had No Equipment Assigned`,
  standfirst: `More than 5,000 people subject to electronic monitoring orders had no monitoring equipment assigned to them at the end of June. Another 1,596 had equipment installed but it had not communicated with the monitoring system for at least 14 days. The figures were published after the National Audit Office warned that the government did not know accurately how many people who should have been monitored were not being monitored.`,
  publishedAt: '2026-08-02',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `More than 5,000 people subject to electronic monitoring orders had no monitoring equipment assigned to them at the end of June.` },
    { type: 'paragraph', text: `Another 1,596 had equipment installed but it had not communicated with the monitoring system for at least 14 days.` },
    { type: 'paragraph', text: `The figures were published by the Ministry of Justice on 23 July, after the National Audit Office warned that the government did not know accurately how many people who should have been monitored were not being monitored.` },
    { type: 'paragraph', text: `The new data make the position clearer, but they do not mean 6,639 offenders were simply walking around without working tags.` },
    { type: 'paragraph', text: `Of the 5,043 people without equipment, 27 per cent had not been at the address when installation was attempted. Another 18 per cent were recorded as being in custody. Eighteen per cent had experienced a problem with the installation or equipment. Other reasons included medical problems, access difficulties, withdrawal of consent and cases still within the two-day installation period.` },
    { type: 'paragraph', text: `The total nevertheless represented 15 per cent of people with an electronic monitoring order.` },
    { type: 'paragraph', text: `Court bail accounted for the largest group without equipment, at 2,704 people. Another 1,585 were subject to post-release monitoring, 608 had community or suspended-sentence requirements and 146 were in the immigration system.` },
    { type: 'paragraph', text: `Among people who did have equipment assigned, 1,596 devices were not actively communicating, equivalent to 6 per cent of that group. The Ministry defines this as no signal having been received for at least 14 days.` },
    { type: 'paragraph', text: `That can happen because somebody has failed to charge a device, damaged or interfered with it, because of a technical fault or because of a loss of power. The figure does not establish how many involved deliberate non-compliance.` },
    { type: 'paragraph', text: `The new numbers matter because they supersede a much less reliable picture available only weeks earlier.` },
    { type: 'paragraph', text: `When the National Audit Office examined the system, HM Prison and Probation Service was reviewing about 8,900 cases recorded as having an active electronic monitoring order but no tag. That was around 24 per cent of the cases recorded as requiring electronic monitoring.` },
    { type: 'paragraph', text: `HMPPS already knew some of those records were wrong. Expired orders had remained on the system as active cases. Devices that had stopped communicating for 14 days or more were meanwhile still being counted inside the supposedly tagged population.` },
    { type: 'paragraph', text: `The Ministry subsequently carried out manual case reviews and reconciled supplier records against other justice data before publishing the June figures.` },
    { type: 'paragraph', text: `That means the apparent fall from roughly 8,900 cases under review in March to 5,043 people without equipment in June cannot be treated as evidence that almost 4,000 people were successfully tagged in the meantime. The Ministry says further assurance work and the closure of expired records accounted for part of the reduction.` },
    { type: 'paragraph', text: `Problems had already appeared much earlier in the contract.` },
    { type: 'paragraph', text: `Serco took over fitting and monitoring in May 2024. The backlog of visits to install, inspect or remove equipment rose from about 1,200 that month to 7,000 in October 2024, before falling below 400 in November. The NAO found that people had not always been tagged on time and officials had not always received breach information promptly during the early period of the contract.` },
    { type: 'paragraph', text: `Performance subsequently improved, but one of the contract measures gives an incomplete picture.` },
    { type: 'paragraph', text: `Serco met its target for 95 per cent of adult installation visits in February 2026. That target measures whether two attempts to install the equipment were made within the required time.` },
    { type: 'paragraph', text: `Only 62 per cent of the people visited had actually been successfully fitted with equipment after those two attempts.` },
    { type: 'paragraph', text: `Some failures were outside Serco's control. A person may not be home, may refuse installation or may be in custody.` },
    { type: 'paragraph', text: `There are also delays after equipment detects a possible breach.` },
    { type: 'paragraph', text: `Serco's contract can allow between 29 and 53 hours from a breach occurring before the completed evidence is required to reach the officials responsible for acting on it. In practice, the NAO found Serco was averaging about 20 hours in February 2026, faster than the contractual maximum.` },
    { type: 'paragraph', text: `What happens after that is less clear.` },
    { type: 'paragraph', text: `Police and probation staff told auditors that shortages of staff and poor information could delay responses. The NAO found no national data showing how quickly enforcement agencies respond to breaches. It also found that courts and the Ministry do not routinely analyse what subsequently happens in electronic-monitoring bail cases.` },
    { type: 'paragraph', text: `The volume of alerts adds to the workload.` },
    { type: 'paragraph', text: `A Ministry-commissioned review estimated that electronic monitoring generates between 530,000 and three million alerts a year. Only between 10 and 50 per cent progressed to a breach pack for officials to consider.` },
    { type: 'paragraph', text: `For the minority of breach packs where an outcome was recorded, between 20 and 27 per cent of the total, nearly half ended in no further action.` },
    { type: 'paragraph', text: `That is narrower than saying half of all electronic-monitoring alerts resulted in nothing happening. The available records do not support that claim.` },
    { type: 'paragraph', text: `Probation capacity is another constraint.` },
    { type: 'paragraph', text: `The NAO estimated that the service was around 2,200 full-time-equivalent staff short in March 2026. HMPPS expected that shortfall to fall to about 1,500 by September. Police were also expected to face additional demand, including an estimated 4,200 extra bail-breach cases a year resulting in custody as the reforms take effect. The National Police Chiefs' Council estimated increased electronic-monitoring demand would cost forces about £20 million a year, while telling the NAO that no additional police funding had been provided specifically for it.` },
    { type: 'paragraph', text: `The government is nevertheless expanding the system substantially.` },
    { type: 'paragraph', text: `The Ministry estimated in September 2025 that up to 22,000 additional people a year could require electronic monitoring from 2027. The government has allocated up to £175 million between 2026 and 2029 for the expansion.` },
    { type: 'paragraph', text: `That includes new uses of the technology.` },
    { type: 'paragraph', text: `A £5 million proximity-monitoring pilot will test tags intended to alert authorities when certain domestic abuse or stalking offenders approach their victims. The government is also expanding GPS monitoring of burglars and thieves and giving probation staff greater access to location data.` },
    { type: 'paragraph', text: `There is evidence supporting the wider use of tagging.` },
    { type: 'paragraph', text: `A Ministry of Justice evaluation published in 2025 found that radio-frequency curfew monitoring was associated with lower proven reoffending among comparable offenders. Another evaluation of GPS monitoring for people released after acquisitive offences found a seven percentage point reduction in the 12-month reoffending rate, from 33.2 per cent to 26.2 per cent, for the group studied.` },
    { type: 'paragraph', text: `The argument for electronic monitoring is therefore not simply theoretical. For some groups, the government's own evaluations indicate measurable benefits.` },
    { type: 'paragraph', text: `The operational problems are much older.` },
    { type: 'paragraph', text: `In 2022 the National Audit Office reported that HMPPS had written off £98 million after abandoning its Gemini electronic-monitoring case-management system. Auditors said the department's poor evidence base meant Parliament still did not have a clear view of what more than a decade of electronic-monitoring reform had achieved.` },
    { type: 'paragraph', text: `Four years later, the evidence on some individual tagging schemes has improved.` },
    { type: 'paragraph', text: `The system used to deliver them has not reached the same point.` },
    { type: 'paragraph', text: `The NAO concluded in July that electronic monitoring was still not working as intended and that the Ministry, HMPPS, police, probation and other agencies did not yet have a joined-up understanding of capacity and risk across the system. It warned that expanding the service before those weaknesses were addressed increased risks to performance and public protection.` },
    { type: 'paragraph', text: `By 30 June, the Ministry could at least put a number on one part of the problem.` },
    { type: 'paragraph', text: `5,043 people with electronic monitoring orders had no equipment assigned. Another 1,596 had equipment which had not communicated for at least 14 days.` },
    { type: 'paragraph', text: `The government now has better data on who is not being actively monitored.` },
    { type: 'paragraph', text: `The next expansion begins while it is still trying to make the existing system respond reliably when the equipment is missing, disconnected or reports a breach.` },
  ],
  evidence: {
    recordsReviewed: [
      `Ministry of Justice, Annex: Management Information, Electronic Monitoring Status Statistics: June 2026, 23 July 2026: establishes that 5,043 people with electronic monitoring orders had no equipment assigned, the reasons recorded for non-installation and the 1,596 cases where installed equipment had not communicated for at least 14 days`,
      `Ministry of Justice, Electronic Monitoring Statistics Publication, England and Wales: June 2026, 23 July 2026: provides the wider caseload figures and explains the data-cleaning exercise which closed expired orders that had remained recorded as active`,
      `National Audit Office, Electronic monitoring: improving resilience to meet increasing demand, 10 July 2026: provides the 8,900 cases under review, fitting performance, breach-processing times, alert volumes, probation staffing shortfall, planned expansion and the NAO's conclusion on system-wide risks`,
      `Ministry of Justice, Assessing the effectiveness of Radio Frequency Electronic Monitoring, 2025: reports the impact evaluation of curfew monitoring and its relationship with proven reoffending`,
      `Ministry of Justice, Impact evaluation of the acquisitive crime electronic monitoring project: 12 month+ cohort, 28 August 2025: evaluates GPS tagging of prison leavers convicted of acquisitive offences`,
      `Ministry of Justice and HM Prison and Probation Service, electronic-monitoring expansion announcement, 19 March 2026: sets out the £5 million proximity-monitoring pilot and wider planned use of GPS and electronic monitoring`,
      `National Audit Office, Electronic monitoring: a progress update, 8 June 2022: records the £98 million loss on the abandoned Gemini system and the earlier lack of evidence about the effectiveness of the electronic-monitoring programme`,
    ],
    lastChecked: '5 October 2026',
  },
};

export default piece;
