import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'ew4k9mxn7r',
  kicker: 'Local Government',
  headline: `35 Councils Need £1.5bn of Exceptional Financial Support as Government Adds Another £91m`,
  standfirst: `Thirty-five English councils need around £1.5 billion of Exceptional Financial Support in 2026/27. The government has announced a further £91 million for 14 of them to reform high-cost services. The number of councils needing exceptional support has grown from 30 last year, and the mechanism itself does not remove the underlying financial pressures.`,
  publishedAt: '2026-09-15',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `Thirty-five English councils need around £1.5 billion of Exceptional Financial Support this year, as the government commits a further £91 million trying to reduce the cost of services pushing some authorities deeper into financial trouble.` },
    { type: 'paragraph', text: `The £91 million will go to 14 councils already receiving exceptional support — though not all of it this year. £41 million is allocated for 2026-27, with the remaining £50 million following in 2027-28.` },
    { type: 'paragraph', text: `They include Bradford, Brighton and Hove, Haringey, Havering, Isle of Wight, Isles of Scilly, Lambeth, Redbridge, Redcar and Cleveland, Sefton, Stoke-on-Trent, Trafford, Waltham Forest and West Berkshire.` },
    { type: 'paragraph', text: `The government says the money will fund projects aimed at cutting the cost of adult social care, children's services, SEND transport and temporary accommodation.` },
    { type: 'paragraph', text: `Some councils will use AI and new digital systems.` },
    { type: 'paragraph', text: `Others will spend the money on more basic interventions.` },
    { type: 'paragraph', text: `Haringey, for example, plans to buy homes to reduce reliance on expensive temporary accommodation supplied by external providers, "helping more people move on into settled housing" and joining up services.` },
    { type: 'paragraph', text: `The programme is intended to help councils stop returning for repeated financial support.` },
    { type: 'paragraph', text: `The government itself describes the aim as breaking a "cycle of dependence on exceptional support".` },
    { type: 'paragraph', text: `That wording matters.` },
    { type: 'paragraph', text: `Exceptional support is no longer confined to a handful of councils facing isolated crises.` },
    { type: 'paragraph', text: `Government figures show that 35 councils require around £1.5 billion of it in 2026/27.` },
    { type: 'heading', level: 2, text: `The same 14 councils already need around £460 million` },
    { type: 'paragraph', text: `The 14 councils receiving the new £91 million transformation fund have already been approved or provisionally approved for around £460.4 million of Exceptional Financial Support this year.` },
    { type: 'paragraph', text: `The largest amounts include:` },
    { type: 'paragraph', text: `Haringey, £84 million.` },
    { type: 'paragraph', text: `Bradford, £78 million.` },
    { type: 'paragraph', text: `Havering, £77 million.` },
    { type: 'paragraph', text: `Redbridge, £70 million.` },
    { type: 'paragraph', text: `West Berkshire, £30 million.` },
    { type: 'paragraph', text: `Lambeth, £20 million.` },
    { type: 'paragraph', text: `Waltham Forest, £19 million.` },
    { type: 'paragraph', text: `Redcar and Cleveland, £18.451 million.` },
    { type: 'paragraph', text: `Brighton and Hove, £15 million.` },
    { type: 'paragraph', text: `Trafford, £12.65 million.` },
    { type: 'paragraph', text: `Isle of Wight, £12.9 million.` },
    { type: 'paragraph', text: `Sefton, £12 million.` },
    { type: 'paragraph', text: `Stoke-on-Trent, £10.5 million.` },
    { type: 'paragraph', text: `Isles of Scilly, £926,000.` },
    { type: 'paragraph', text: `The new £91 million is therefore not being spent on councils with healthy finances experimenting with service reform.` },
    { type: 'paragraph', text: `It is being targeted at authorities already under enough pressure to require special financial treatment from central government.` },
    { type: 'paragraph', text: `A note on the wider total: the government's detailed EFS allocations table actually lists 40 recipient bodies once a housing revenue account authority and two police-related bodies are included, summing to roughly £1.58 billion, a slightly larger figure than the "35 councils, £1.5 billion" headline, which appears to count general fund councils only. Both figures are real; they are simply measuring a marginally different population of recipients.` },
    { type: 'heading', level: 2, text: `Exceptional Financial Support is not a normal grant` },
    { type: 'paragraph', text: `The name can give the impression that Whitehall simply gives councils extra money.` },
    { type: 'paragraph', text: `That is not generally how the system works.` },
    { type: 'paragraph', text: `Exceptional Financial Support usually gives an authority permission to use capital resources, sell assets or borrow in order to fund day-to-day spending that would normally have to be covered from annual income.` },
    { type: 'paragraph', text: `That can help a council set a legally balanced budget.` },
    { type: 'paragraph', text: `It does not necessarily remove the underlying gap between what the authority spends and what it can sustainably afford.` },
    { type: 'paragraph', text: `A council can therefore survive one financial year while still carrying the same structural pressures into the next.` },
    { type: 'paragraph', text: `That is why repeated use of the mechanism matters.` },
    { type: 'paragraph', text: `Government figures show 30 councils received exceptional support in 2025/26.` },
    { type: 'paragraph', text: `This year the number has risen to 35.` },
    { type: 'heading', level: 2, text: `The pressures are increasingly familiar` },
    { type: 'paragraph', text: `The government says high-cost services such as adult social care, children's services, SEND and temporary accommodation are driving some councils into repeated financial difficulty.` },
    { type: 'paragraph', text: `These are not obscure budget lines.` },
    { type: 'paragraph', text: `They are among the largest and fastest-growing areas of local authority spending.` },
    { type: 'paragraph', text: `Councils have limited room to reduce them because much of the demand is statutory.` },
    { type: 'paragraph', text: `An authority cannot simply stop supporting a child in care or refuse to meet a legal duty to house a homeless family.` },
    { type: 'paragraph', text: `That helps explain why several councils are now trying to redesign the service itself rather than simply cut it.` },
    { type: 'heading', level: 2, text: `Temporary accommodation is becoming a financial trap` },
    { type: 'paragraph', text: `Haringey's project is particularly revealing.` },
    { type: 'paragraph', text: `The council plans to use transformation money to acquire homes so that families can be moved out of more expensive temporary accommodation supplied by outside providers.` },
    { type: 'paragraph', text: `The logic is simple.` },
    { type: 'paragraph', text: `If a council is spending large amounts every year renting emergency accommodation from private landlords, hotels or specialist providers, buying property may eventually be cheaper.` },
    { type: 'paragraph', text: `But that also exposes how expensive the present system has become.` },
    { type: 'paragraph', text: `Councils can find themselves paying high nightly rates for temporary housing while simultaneously struggling to balance their own budgets.` },
    { type: 'paragraph', text: `If those costs are then partly covered through borrowing or asset sales authorised under Exceptional Financial Support, the financial chain becomes circular.` },
    { type: 'paragraph', text: `Public money is used to keep councils solvent while councils continue making high payments to private accommodation providers.` },
    { type: 'paragraph', text: `That deserves closer examination.` },
    { type: 'heading', level: 2, text: `The AI headline risks hiding the real story` },
    { type: 'paragraph', text: `The government has promoted some of the £91 million programme as a technology and AI initiative.` },
    { type: 'paragraph', text: `Redbridge will use AI-powered home devices designed to detect and prevent falls, intended to help people live independently for longer.` },
    { type: 'paragraph', text: `Trafford plans to bring the council's information onto a single, more reliable computer system and use technology, including AI, to make services smarter.` },
    { type: 'paragraph', text: `Those projects may reduce costs.` },
    { type: 'paragraph', text: `But they are not the central issue.` },
    { type: 'paragraph', text: `Some councils are buying property.` },
    { type: 'paragraph', text: `Others are changing children's services or SEND transport.` },
    { type: 'paragraph', text: `The programme is less an AI revolution than an attempt to make high-cost statutory services affordable enough that councils stop needing repeated financial intervention.` },
    { type: 'heading', level: 2, text: `The test is whether the councils come back again` },
    { type: 'paragraph', text: `The government says lessons learned from these 14 authorities will help it understand "what works and what doesn't" — a more modest promise than simply rolling out successful projects sector-wide, and one that implicitly concedes some of this money may not pay off.` },
    { type: 'paragraph', text: `That means the programme has a clear test.` },
    { type: 'paragraph', text: `Did temporary accommodation spending fall?` },
    { type: 'paragraph', text: `Did social-care costs stabilise?` },
    { type: 'paragraph', text: `Did SEND transport become cheaper?` },
    { type: 'paragraph', text: `Did councils reduce reliance on asset sales and borrowing?` },
    { type: 'paragraph', text: `And most importantly:` },
    { type: 'paragraph', text: `Did the same authorities stop needing Exceptional Financial Support?` },
    { type: 'paragraph', text: `If they do, the £91 million may prove to have been money well spent.` },
    { type: 'paragraph', text: `If they do not, it will suggest the government has funded another round of temporary fixes without addressing the financial pressures underneath.` },
    { type: 'heading', level: 2, text: `A scheme called exceptional now covers 35 councils` },
    { type: 'paragraph', text: `The larger issue is what the growth of the support scheme says about local government in England.` },
    { type: 'paragraph', text: `Thirty-five councils needing £1.5 billion of exceptional support in one financial year is no longer a tiny fringe of isolated failures.` },
    { type: 'paragraph', text: `Some councils have unquestionably made poor local decisions.` },
    { type: 'paragraph', text: `Others have suffered governance failures.` },
    { type: 'paragraph', text: `But the same pressures recur across authorities with very different political leadership and geography.` },
    { type: 'paragraph', text: `Social care.` },
    { type: 'paragraph', text: `Children's services.` },
    { type: 'paragraph', text: `SEND.` },
    { type: 'paragraph', text: `Homelessness.` },
    { type: 'paragraph', text: `Temporary accommodation.` },
    { type: 'paragraph', text: `The question is becoming harder to avoid.` },
    { type: 'paragraph', text: `England may not be dealing with 35 separate council crises.` },
    { type: 'paragraph', text: `It may be dealing with one structural local-government funding problem showing up in 35 different places.` },
    { type: 'paragraph', text: `The £91 million transformation fund is supposed to help break that cycle.` },
    { type: 'paragraph', text: `By the government's own numbers, the cycle already exists — and only £41 million of that fund arrives this year, with the rest not due until 2027-28.` },
  ],
  evidence: {
    recordsReviewed: [
      'Ministry of Housing, Communities and Local Government / GOV.UK, 15 September 2026: "Councils\' high-cost services to be transformed through £91m fund" — 14 councils, £41m/£50m split, Haringey/Redbridge/Trafford project descriptions',
      'GOV.UK, "Exceptional Financial Support for local authorities for 2026-27" — individual EFS allocations for all 14 named councils; wider table of 40 recipient bodies (~£1.58bn)',
      'GOV.UK, "Local authority revenue expenditure and financing: 2026-27 budget, England" — headline figure of 35 councils requiring ~£1.5bn of EFS in 2026/27',
      'GOV.UK, "Exceptional Financial Support for local authorities" (collection) — how EFS works mechanically (capital receipts, asset sales, borrowing against revenue); 30-council figure for 2025/26',
    ],
    lastChecked: '30 September 2026',
  },
};

export default piece;
