import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'ew4k9mxn7r',
  kicker: 'Local Government',
  headline: `Government Adds £91m Reform Fund as 35 Councils Are Approved for £1.5bn of Exceptional Support`,
  standfirst: `The government is giving 14 financially troubled councils £91 million to redesign expensive services in an attempt to reduce their reliance on Exceptional Financial Support. Those same 14 authorities have already been approved for about £460.4 million of Exceptional Financial Support in 2026/27. Across England, 35 councils have been approved for £1.5 billion this year.`,
  publishedAt: '2026-09-15',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `The government is giving 14 financially troubled councils £91 million to redesign expensive services in an attempt to reduce their reliance on Exceptional Financial Support.` },
    { type: 'paragraph', text: `Those same 14 authorities have already been approved for about £460.4 million of Exceptional Financial Support in 2026/27.` },
    { type: 'paragraph', text: `Across England, the government's official budget statistics say 35 councils have been approved for £1.5 billion of Exceptional Financial Support this year. Some authorities may use only part of what has been approved.` },
    { type: 'paragraph', text: `The £91 million is separate funding intended to reduce those underlying pressures. It will be spread over two years, with £41 million in 2026/27 and £50 million in 2027/28. The Ministry of Housing, Communities and Local Government says the projects are intended to help break what it calls a "cycle of dependence on exceptional support".` },
    { type: 'paragraph', text: `The 14 councils are Bradford, Brighton and Hove, Haringey, Havering, Isle of Wight, Isles of Scilly, Lambeth, Redbridge, Redcar and Cleveland, Sefton, Stoke-on-Trent, Trafford, Waltham Forest and West Berkshire.` },
    { type: 'paragraph', text: `Their existing Exceptional Financial Support approvals range from £926,000 for the Isles of Scilly to £84 million for Haringey. Bradford has £78 million agreed in principle, Havering £77 million and Redbridge £70 million. Adding the 14 current-year allocations gives approximately £460.4 million.` },
    { type: 'paragraph', text: `Exceptional Financial Support is not normally an additional grant covering a council's deficit.` },
    { type: 'paragraph', text: `It is usually provided through a capitalisation direction, allowing an authority to meet day-to-day revenue costs using capital resources that would not normally be available for that purpose. That can include borrowing or proceeds from selling assets. Government guidance says councils are expected, as far as possible, to meet the cost of that support over time.` },
    { type: 'paragraph', text: `The mechanism can allow a council to set a legally balanced budget without removing the financial pressure that produced the deficit.` },
    { type: 'paragraph', text: `Use of it has expanded sharply.` },
    { type: 'paragraph', text: `Government records show 19 councils received Exceptional Financial Support in 2024/25. The number rose to 30 in 2025/26. The official 2026/27 budget statistics put the current figure at 35.` },
    { type: 'paragraph', text: `The detailed 2026/27 EFS guidance contains 36 general-fund council entries rather than 35 because the EFS approval tables and councils' budget returns are not measuring exactly the same thing. The official budget release notes that some authorities do not expect to use all of the support approved to them, or may not budget to use it through the revenue account.` },
    { type: 'paragraph', text: `Separate entries on the EFS guidance page for a housing revenue account, police-related support and revised assistance from previous years should not be added to the £1.5 billion current-year council figure. Some of those entries relate explicitly to earlier financial years.` },
    { type: 'paragraph', text: `The new £91 million programme is concentrated on services that councils say are driving some of their largest spending pressures.` },
    { type: 'paragraph', text: `Haringey plans to buy homes to reduce reliance on external temporary-accommodation providers. Bradford will change its SEND transport and support system. Brighton and Hove plans to integrate reablement more closely with NHS services. Redbridge will use home technology, including devices intended to detect falls, to help more residents remain independent. Stoke-on-Trent is redesigning frontline children's social work.` },
    { type: 'paragraph', text: `Trafford will receive £7.5 million to modernise its council systems and use technology including AI. Redbridge is also receiving £7.5 million, while Bradford has the largest transformation allocation at £12.7 million.` },
    { type: 'paragraph', text: `The spending pressures behind those projects can also be seen in the national figures.` },
    { type: 'paragraph', text: `English councils have budgeted £28.7 billion for adult social care in 2026/27, 5.2 per cent higher in real terms than the previous year's budget.` },
    { type: 'paragraph', text: `Children's social care expenditure is budgeted at £17 billion, up 7.4 per cent in real terms.` },
    { type: 'paragraph', text: `Housing services spending is expected to rise 14.3 per cent, driven partly by a 14.7 per cent increase in spending on homelessness.` },
    { type: 'paragraph', text: `Those increases do not prove that every council receiving Exceptional Financial Support has the same underlying problem.` },
    { type: 'paragraph', text: `Several EFS authorities have also experienced serious local governance or financial-management failures. Croydon, Slough, Thurrock, Woking and Warrington are among councils listed by government as subject to statutory intervention.` },
    { type: 'paragraph', text: `But the £91 million programme itself is aimed largely at pressures that recur across local government: adult social care, children's services, SEND and homelessness.` },
    { type: 'paragraph', text: `The government has also changed the wider funding system. In February it introduced the first multi-year Local Government Finance Settlement in a decade and says it is changing how money is distributed between authorities. It has also announced reforms to children's services, homelessness and SEND financing.` },
    { type: 'paragraph', text: `The £91 million fund is therefore being used as a more targeted experiment alongside those larger changes.` },
    { type: 'paragraph', text: `MHCLG says lessons from the 14 councils will be used to establish "what works and what doesn't" and influence future funding decisions.` },
    { type: 'paragraph', text: `Haringey's housing project gives one example of what that means in practice. The council intends to spend money upfront acquiring homes so it can reduce the amount paid to external temporary-accommodation providers later.` },
    { type: 'paragraph', text: `That approach can be measured against subsequent spending on temporary accommodation and the number of households moved into settled housing.` },
    { type: 'paragraph', text: `The same applies to the other projects. Bradford's SEND changes can be measured against transport costs and service demand. Redbridge's technology can be tested against social-care use. Stoke-on-Trent's changes can be compared with children's-service costs and outcomes.` },
    { type: 'paragraph', text: `The government's announcement does not publish numerical targets showing how much those projects are expected to reduce each authority's Exceptional Financial Support requirement.` },
    { type: 'paragraph', text: `Nor does it specify how many of the 14 councils it expects to leave the EFS system as a result of the £91 million programme.` },
    { type: 'paragraph', text: `The starting position is measurable. The 14 councils receiving transformation funding have around £460.4 million of Exceptional Financial Support approved for 2026/27. Across England, official statistics put Exceptional Financial Support at £1.5 billion for 35 councils, compared with 30 councils the previous year. Only £41 million of the new transformation fund is scheduled to be spent during the current financial year.` },
  ],
  evidence: {
    recordsReviewed: [
      `Ministry of Housing, Communities and Local Government, "Councils' high-cost services to be transformed through £91m fund", 15 September 2026: the £91 million programme, £41 million/£50 million funding split, 14 participating councils, individual transformation allocations, project descriptions and the government's stated aim of reducing reliance on Exceptional Financial Support`,
      `MHCLG, "Exceptional Financial Support for local authorities for 2026-27", updated 18 August 2026: individual 2026/27 EFS approvals, including the approximately £460.4 million combined current-year allocation for the 14 transformation-fund councils, and distinguishing general-fund council support from HRA, police and previous-year entries`,
      `MHCLG, "Local authority revenue expenditure and financing: 2026-27 budget, England", 11 June 2026: the official figure of 35 councils and £1.5 billion of Exceptional Financial Support, and the 2026/27 expenditure figures for adult social care, children's social care, housing and homelessness`,
      `MHCLG, "Exceptional Financial Support for local authorities for 2025-26": the 30-council figure for 2025/26`,
      `MHCLG, "Exceptional Financial Support for local authorities for 2024-25": the 19-council figure for 2024/25`,
      `MHCLG, "Best value standards and intervention: a statutory guide for best value authorities": the mechanics of Exceptional Financial Support, including the usual use of capitalisation directions, borrowing and capital receipts to meet revenue costs`,
    ],
    lastChecked: '3 October 2026',
  },
};

export default piece;
