import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'fr9k2mxw7q',
  kicker: 'Surveillance',
  headline: `17 Facial Recognition Deployments at London Stations Produced No Watchlist Matches`,
  standfirst: `British Transport Police used live facial recognition at seven London railway stations on 17 occasions between February and July without producing a confirmed match to anybody on its watchlists. One person was stopped after the system generated an alert. Police established that they were not the person being sought. No arrest resulted from facial recognition during any of the 17 deployments.`,
  publishedAt: '2026-08-04',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `British Transport Police used live facial recognition at seven London railway stations on 17 occasions between February and July without producing a confirmed match to anybody on its watchlists.` },
    { type: 'paragraph', text: `One person was stopped after the system generated an alert. Police established that they were not the person being sought. No arrest resulted from facial recognition during any of the 17 deployments.` },
    { type: 'paragraph', text: `The figures were disclosed by the Department for Transport in a written answer to Conservative MP Shivani Raja. BTP began what it described as a six-month pilot at London Bridge on 11 February, followed by Waterloo and Euston later that week. The cameras were subsequently deployed at King's Cross, St Pancras, Liverpool Street and Victoria, with several stations visited repeatedly. The latest operation covered by the answer was at King's Cross on 11 July.` },
    { type: 'paragraph', text: `The same answer contained a result which needs separating from the performance of the facial recognition system itself.` },
    { type: 'paragraph', text: `BTP reported 13 arrests "linked to the deployment of LFR" and said crime was lower at the locations while the equipment was operating. But the department also said explicitly that nobody had been arrested specifically as a result of facial recognition. It did not identify the offences behind the 13 arrests, explain how they were linked to the deployments or quantify the reported reduction in crime.` },
    { type: 'paragraph', text: `The published evidence therefore supports two different findings. Officers carrying out the operations made arrests, but the facial recognition system had not identified any of the people responsible for them.` },
    { type: 'paragraph', text: `BTP designed the trial specifically to find people it believed might pass through the railway network. Its policy says proactive deployments should be based on crime data and intelligence, while watchlists can contain people wanted for serious offences, people wanted by courts and people subject to certain court orders. Location decisions can take account of where offenders live, where they have offended and intelligence suggesting they may use a particular station.` },
    { type: 'paragraph', text: `That makes the absence of a confirmed match relevant to the evaluation, but it does not by itself establish that the technology cannot identify wanted people.` },
    { type: 'paragraph', text: `Other police forces have reported very different results. In its December 2025 consultation on facial recognition, the Home Office said the Metropolitan Police recorded 962 arrests between September 2024 and September 2025 as a direct result of using live facial recognition. Those deployments involved different watchlists, locations and policing operations, so the figure is not directly comparable with BTP's trial. It does show that zero matches on the railway cannot simply be treated as evidence that the underlying technology does not work.` },
    { type: 'paragraph', text: `BTP's own policy recognises that evaluating a deployment requires more than counting arrests.` },
    { type: 'paragraph', text: `The force says it should publish the location and duration of each operation, the size of the watchlist, the number of alerts, confirmed false and true alerts, the false-alert rate and an estimate of the number of faces scanned. Its performance framework also calls for monitoring arrests and charges resulting directly from facial-recognition alerts and crime levels in the areas where it is deployed.` },
    { type: 'paragraph', text: `The Department for Transport's parliamentary answer did not provide those wider performance figures. It gave the dates, stations and headline outcomes, but not the number of faces processed or the watchlist size at each of the 17 operations. Those figures matter because one false alert among a few thousand scans and one among hundreds of thousands describe very different levels of performance.` },
    { type: 'paragraph', text: `The false alert occurred against a system designed to include a police officer between the software and any enforcement decision. BTP says an alert is not treated as an identification. An officer compares the live image with the watchlist image and decides whether to approach the person. The force's policy records a "confirmed false alert" where an individual is engaged and officers then establish that they are not the person shown on the watchlist.` },
    { type: 'paragraph', text: `BTP had also promised visible notice of the technology. Its policy requires advance publication of deployments, signs immediately before the recognition area and reasonable alternative routes for people who do not want their image captured. Officers are specifically told that they have no power to require somebody to cooperate with having their face scanned. Images which do not generate an alert are automatically deleted, according to the force.` },
    { type: 'paragraph', text: `That does not mean the system operates on consent. BTP's legal mandate says consent is impractical for live facial recognition and instead relies on law-enforcement provisions in the Data Protection Act alongside other legal powers and safeguards.` },
    { type: 'paragraph', text: `There is no dedicated Act of Parliament setting out a single statutory regime for overt police facial recognition.` },
    { type: 'paragraph', text: `BTP says its primary authority to deploy the technology comes from common-law policing powers, alongside legislation including the Police and Criminal Evidence Act, Human Rights Act, Data Protection Act and Equality Act. The force cites the Court of Appeal's judgment in the Bridges case, which recognised a legal basis for police use of facial recognition but also required an accessible framework governing matters such as watchlists, safeguards and decision-making.` },
    { type: 'paragraph', text: `The Home Office reached a similar conclusion about the structure of the law in December 2025. It said police facial recognition currently rests on a "patchwork" of common law, data protection, human rights and equalities law and police guidance. The government said the existing framework was complicated and difficult for the public to understand and proposed a more specific legal framework together with a new statutory oversight body.` },
    { type: 'paragraph', text: `That consultation did not say existing police use was unlawful. Policing minister Sarah Jones said there was a legal framework in which facial recognition could already be used, while arguing that wider deployment required clearer and more specific rules.` },
    { type: 'paragraph', text: `BTP's pilot was therefore operating under the existing framework while the government was considering how that framework should be replaced or tightened.` },
    { type: 'paragraph', text: `The first 17 deployments provide only a partial answer to whether the railway trial was worthwhile. They show that no person on the relevant watchlists had been identified by the system by 11 July and that one passenger had been stopped following an incorrect alert. They also show that officers made 13 other arrests during operations, although the Department for Transport's answer does not provide enough information to attribute those arrests to the facial recognition technology itself.` },
    { type: 'paragraph', text: `BTP's own evaluation framework requires considerably more: how many faces were processed, how large the watchlists were, what happened to crime at the deployment sites and how many arrests or charges resulted directly from an alert.` },
    { type: 'paragraph', text: `Until those measures are brought together, the strongest result available from the parliamentary answer is narrower. Seventeen deployments had produced one false alert and no confirmed watchlist match.` },
  ],
  evidence: {
    recordsReviewed: [
      `UK Parliament, written question 18207, "Railway Stations: Biometrics", answered by Department for Transport minister Keir Mather, 4 August 2026: the 17 deployments, stations and dates, no confirmed watchlist matches, one false alert, no arrests specifically following facial recognition, and the separate claim of 13 arrests linked to the deployments and reduced crime while LFR was operating`,
      `British Transport Police, "Overt Live Facial Recognition Policy", version 2.5: BTP's deployment criteria, watchlist rules, public-notification requirements, alternative routes, performance metrics, publication requirements and planned crime-reduction measures`,
      `British Transport Police, "Live Facial Recognition: Legal Mandate", 10 February 2026: the force's reliance on common-law policing powers, PACE, human-rights and data-protection law; its treatment of consent; and its account of the Bridges judgments`,
      `British Transport Police, "British Transport Police to launch trial of Live Facial Recognition technology today", 11 February 2026: the launch date, purpose of the pilot, officer review of alerts, deletion of non-matching images and availability of alternative routes`,
      `Home Office, "Consultation on a new legal framework for law enforcement use of biometrics, facial recognition and similar technologies", 4 December 2025: the government's description of the current legal framework, its proposal for more specific legislation and statutory oversight, and the Metropolitan Police figure of 962 arrests attributed to LFR between September 2024 and September 2025`,
    ],
    lastChecked: '3 October 2026',
  },
};

export default piece;
