import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'gw4k9mxn7r',
  kicker: 'Public Ownership',
  headline: `Government Opens Door to Water Ownership but Stops Short of Walking Through It`,
  standfirst: `The government has announced what it calls a "pathway to stronger public control" of England's water industry. No water company is being taken into public ownership. The distinction matters.`,
  publishedAt: '2026-09-30',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `The government has announced what it calls a "pathway to stronger public control" of England's water industry.` },
    { type: 'paragraph', text: `For now, however, no water company is being taken into public ownership.` },
    { type: 'paragraph', text: `The change announced this week is considerably narrower.` },
    { type: 'paragraph', text: `Ministers intend to repeal rules dating from the privatisation of the industry that restrict government shareholdings in England's major water and sewerage companies to between 1 and 3 per cent, with the exact limit varying by company.` },
    { type: 'paragraph', text: `Removing those restrictions would give a future government considerably more freedom to intervene in a water company.` },
    { type: 'paragraph', text: `It does not itself constitute an intervention.` },
    { type: 'paragraph', text: `No shares are being bought. No company is being nationalised. No amount of money has been allocated for acquisitions.` },
    { type: 'paragraph', text: `And the government has not said what proportion of a water company it would actually be prepared to own.` },
    { type: 'paragraph', text: `The distinction matters.` },
    { type: 'paragraph', text: `The Department for Environment, Food and Rural Affairs said the change would give government "flexibility to consider a wide range of possible future interventions, including on ownership models".` },
    { type: 'paragraph', text: `That is a possibility rather than a policy.` },
    { type: 'paragraph', text: `The announcement also makes clear that ministers expect private capital to remain central to the system, saying that securing the long-term future of the sector "relies on continued private sector investment".` },
    { type: 'paragraph', text: `That leaves a much bigger question unanswered.` },
    { type: 'paragraph', text: `If a major water company fails financially, how far is the government actually prepared to go?` },
    { type: 'heading', level: 2, text: `A restriction, not a ban on nationalisation` },
    { type: 'paragraph', text: `The existing rules originate in the privatisation settlement created by the Water Act 1989 and the Water (Target Investment Limit) Order 1990.` },
    { type: 'paragraph', text: `They restrict government shareholdings in the privatised water companies to between 1 and 3 per cent, with the precise limit differing between companies.` },
    { type: 'paragraph', text: `But those rules have not made nationalisation legally impossible.` },
    { type: 'paragraph', text: `In May, the government told Parliament that the current legislation limited government holdings to around 3 per cent, and that bringing a water company into public ownership would require new primary legislation and compensation for existing owners.` },
    { type: 'paragraph', text: `The forthcoming legislation will make that process easier by removing the shareholding restrictions, but ministers would still need to decide to use those powers and determine how any acquisition was financed.` },
    { type: 'paragraph', text: `The government was taking a markedly different position only months ago.` },
    { type: 'paragraph', text: `In April it told Parliament that it had "no intention to nationalise the water industry" and therefore had "no current plans to assess the financial or non-financial costs" of comparing private and public ownership.` },
    { type: 'paragraph', text: `That position now looks considerably less absolute.` },
    { type: 'paragraph', text: `Prime Minister Andy Burnham, speaking to the Commons for the first time since taking office, has since described Britain's water industry as "a leaking monument to that approach — a country run in the private rather than public interest".` },
    { type: 'paragraph', text: `Yet the latest announcement still stops well short of committing his government to public ownership.` },
    { type: 'heading', level: 2, text: `The £100 billion problem` },
    { type: 'paragraph', text: `The obvious obstacle is cost.` },
    { type: 'paragraph', text: `There is no agreed figure for buying England's water companies.` },
    { type: 'paragraph', text: `Defra estimated in September 2025 that nationalising the sector could cost about £100 billion, using the industry's regulatory capital value as a proxy.` },
    { type: 'paragraph', text: `The House of Commons Library records that Ofwat's regulatory capital value for the industry is now just over £117 billion.` },
    { type: 'paragraph', text: `An analysis commissioned by Thames Water creditors and produced by Frontier Economics in July 2026 put the potential figure at £144 billion by 2030, accounting for planned capital investment over the current price control period.` },
    { type: 'paragraph', text: `A fourth figure complicates matters further. The Office for Budget Responsibility has calculated the question differently again: it put water companies' debts and other liabilities at £91 billion against £12 billion in financial assets and £94 billion in non-financial assets, concluding that moving the sector onto the public balance sheet could increase public sector net financial liabilities by around £78 billion, a measure of the impact on the government's books, not an acquisition price.` },
    { type: 'paragraph', text: `Those figures should be treated cautiously.` },
    { type: 'paragraph', text: `Regulatory capital value was created to help determine the returns companies can earn and the bills customers pay. It is not necessarily the price a government would have to pay shareholders.` },
    { type: 'paragraph', text: `Different legal structures, distressed companies, individual acquisitions and even the accounting basis used to frame the question could each produce very different numbers.` },
    { type: 'paragraph', text: `But the scale explains why removing a legal restriction is much easier than announcing wholesale nationalisation.` },
    { type: 'heading', level: 2, text: `Thames Water changes the calculation` },
    { type: 'paragraph', text: `The more significant possibility is therefore not the government buying every water company.` },
    { type: 'paragraph', text: `It is selective intervention.` },
    { type: 'paragraph', text: `Thames Water has become the obvious test case.` },
    { type: 'paragraph', text: `The Independent Water Commission, in its final report, found no clear evidence of a causal link between ownership models and environmental or operational performance. Sir Jon Cunliffe, who chaired the commission, said: "on the data and comparable metrics available, the truth is that we did not see evidence of a causal link between ownership models and a range of environmental and other performance indicators."` },
    { type: 'paragraph', text: `But in an earlier address on the commission's plans, Cunliffe had already identified financial resilience as a separate problem, warning that "decisions by a number of companies about structure and debt historically have left them more exposed — as we have seen in the extreme example of Thames Water."` },
    { type: 'paragraph', text: `His conclusion in the final report was significant. What mattered, he said, was not simply whether ownership was public or private, but "the business model of the owners, the level of return they seek on their investment, their time horizon for that return, their preference for dividends or capital gain and their willingness to invest further in their company for a fair return."` },
    { type: 'paragraph', text: `That distinction may explain the government's emerging position.` },
    { type: 'paragraph', text: `Rather than committing billions of pounds to nationalising the entire industry, ministers could acquire stakes in individual companies when financial failure, poor performance or restructuring creates an opportunity.` },
    { type: 'paragraph', text: `The legislation announced this week would remove one of the obstacles to doing so.` },
    { type: 'heading', level: 2, text: `The unanswered questions` },
    { type: 'paragraph', text: `The announcement therefore matters.` },
    { type: 'paragraph', text: `But "stronger public control" remains undefined.` },
    { type: 'paragraph', text: `The government has not said whether it would buy minority stakes, controlling stakes or entire companies.` },
    { type: 'paragraph', text: `It has not said how acquisitions would be valued.` },
    { type: 'paragraph', text: `It has not said whether taxpayers would receive dividends if public money was invested.` },
    { type: 'paragraph', text: `It has not said whether government investment would come ahead of existing shareholders or creditors when a company was restructured.` },
    { type: 'paragraph', text: `And its announcement does not name Thames Water, or any other company, as a candidate for these powers.` },
    { type: 'paragraph', text: `Until those questions are answered, the government has not announced public ownership of England's water industry.` },
    { type: 'paragraph', text: `It has removed a lock from the door.` },
    { type: 'paragraph', text: `Whether ministers ever open it is another matter.` },
  ],
  evidence: {
    recordsReviewed: [
      'Department for Environment, Food and Rural Affairs / GOV.UK, 29 September 2026: "Pathway to stronger public control of the water industry revealed"',
      'House of Commons Library, CBP-12194, 14 September 2026: "Ownership of the water sector" — cost estimates, legal history, OBR and Frontier Economics figures',
      'UK Parliament written question answered 22 May 2026: Defra confirmation of the 3 per cent shareholding limit and nationalisation requirements',
      'UK Parliament written question answered 16 April 2026: government statement of "no intention to nationalise the water industry"',
      'Sir Jon Cunliffe, speech on the Independent Water Commission\'s final report (GOV.UK)',
      'Sir Jon Cunliffe, address on the Water Commission\'s future plans (GOV.UK) — source for Thames Water debt-structure quote',
      'Andy Burnham, statement to the House of Commons, 1 September 2026 — "leaking monument" quote',
    ],
    lastChecked: '30 September 2026',
  },
};

export default piece;
