import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'gx4k9mxw7r',
  kicker: 'Rail',
  headline: `Britain Pays Billions to Lease Its Trains. Now Government Is Asking Whether It Should Own Them`,
  standfirst: `For 30 years, Britain's railway has financed its trains through private leasing companies. The government has now said public ownership of future rolling stock should be assessed case by case. Franchised operators spent £4.1 billion on rolling stock in 2024/25; rolling-stock companies paid out £275 million in dividends the same year. Ministers say buying trains could produce "substantial savings" but have not published the calculations.`,
  publishedAt: '2026-09-28',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `For more than 30 years, Britain has largely accepted that passenger trains should be privately owned and leased back to the railway.` },
    { type: 'paragraph', text: `The government has now decided that arrangement should no longer be the default.` },
    { type: 'paragraph', text: `Under a new Great British Railways strategy, future fleets will be assessed case by case to determine whether taxpayers get better value from leasing trains, buying them outright or using another financing model.` },
    { type: 'paragraph', text: `That change matters because the railway is already spending billions on rolling stock.` },
    { type: 'paragraph', text: `In 2024/25, franchised passenger operators spent £4.1 billion on rolling stock, comprising £2.7 billion on leases from rolling-stock companies and £1.5 billion on maintenance, offset slightly by £61 million of other rolling-stock income, while government funding still covered nearly half of the wider operational railway's costs.` },
    { type: 'paragraph', text: `The government says rolling-stock companies have also paid more than £2.5 billion in dividends over the past decade, an average of roughly £250 million a year, broadly in line with the £275 million ROSCOs paid out in 2024/25 alone, even after that figure fell 19 per cent on the year before.` },
    { type: 'paragraph', text: `Ministers are now saying that, in some cases, buying trains instead could produce "substantial savings."` },
    { type: 'paragraph', text: `What they have not published is the calculation showing how substantial.` },
    { type: 'paragraph', text: `There is no national estimate of how much taxpayers could save, which fleets would be cheaper to own, how much public borrowing would be required or how long it would take before ownership became cheaper than leasing.` },
    { type: 'heading', level: 2, text: `The answer goes back to privatisation` },
    { type: 'paragraph', text: `After three decades of treating leasing as normal, the government is reopening the most basic question in the system.` },
    { type: 'paragraph', text: `Why does the railway rent so many of the trains it depends on?` },
    { type: 'paragraph', text: `Rather than the train operating companies owning large fleets themselves, much of the rolling stock was placed with specialist leasing companies, commonly known as ROSCOs.` },
    { type: 'paragraph', text: `Operators then rent the trains they need.` },
    { type: 'paragraph', text: `That avoids the government or operator having to find billions upfront for new rolling stock. Leasing companies provide the capital, take ownership risk and can potentially move trains between operators over their working life.` },
    { type: 'paragraph', text: `There are sensible reasons for doing it that way.` },
    { type: 'paragraph', text: `The problem is that the market has never behaved quite like a normal rental market.` },
    { type: 'paragraph', text: `A train built for one route cannot necessarily be moved easily onto another.` },
    { type: 'paragraph', text: `Platform lengths differ. Electrification differs. Signalling systems differ. Depots are designed around particular fleets. Drivers and maintenance staff need training.` },
    { type: 'paragraph', text: `Once a fleet is established on a railway, replacing it can be expensive and disruptive.` },
    { type: 'paragraph', text: `That can weaken the negotiating position of the company leasing it.` },
    { type: 'heading', level: 2, text: `Two reviews later, the safeguard is still in place` },
    { type: 'paragraph', text: `The Office of Rail and Road has been dealing with this issue for years.` },
    { type: 'paragraph', text: `The Competition Commission's 2007 market investigation identified problems restricting effective competition in the rolling-stock leasing market. Its remedies, including a Transparency Order requiring leasing companies to disclose information when offering used trains to operators, were made in 2009 and took effect in February 2010.` },
    { type: 'paragraph', text: `When ORR revisited the question in a full review in 2020, it found that the original competition concerns identified by the Competition Commission "have not been alleviated."` },
    { type: 'paragraph', text: `It reviewed the safeguard again last year. Its final decision, published in December 2025, concluded the Transparency Order "continues to be appropriate and proportionate" and recommended keeping it in place, with updated wording to reflect subsequent legislative changes.` },
    { type: 'paragraph', text: `Two reviews five years apart have now reached the same underlying position: the safeguard introduced in 2009 is still doing a job the regulator does not think the market can do on its own.` },
    { type: 'paragraph', text: `That makes the latest government announcement more significant.` },
    { type: 'paragraph', text: `This is not a perfectly competitive market that ministers have suddenly decided to nationalise for ideological reasons.` },
    { type: 'paragraph', text: `The regulator itself still believes special competition safeguards are necessary.` },
    { type: 'paragraph', text: `ORR is separately examining the rolling-stock maintenance market, including long-term contracts, cost transparency and whether maintenance arrangements are genuinely competitive when contracts come up for renewal. That review is expected to conclude in autumn 2026.` },
    { type: 'paragraph', text: `So two parts of the same system are now under scrutiny: how trains are financed, and how they are maintained.` },
    { type: 'heading', level: 2, text: `The government's position has shifted quickly` },
    { type: 'paragraph', text: `Earlier this year, ministers were still arguing against taking on the cost of acquiring privately owned rolling stock.` },
    { type: 'paragraph', text: `Now the new strategy explicitly says public ownership should be considered whenever it offers better value.` },
    { type: 'paragraph', text: `Existing leasing contracts will remain in place, so there is no immediate plan to buy the current fleet from private owners.` },
    { type: 'paragraph', text: `The change applies mainly to future purchases.` },
    { type: 'paragraph', text: `That avoids the potentially huge upfront cost of buying everything already in service.` },
    { type: 'paragraph', text: `It also means the financial consequences will emerge slowly.` },
    { type: 'paragraph', text: `Every time Great British Railways needs a new fleet, it will have to compare the cost of borrowing money and owning the trains with the lifetime cost of paying somebody else to own them.` },
    { type: 'paragraph', text: `That sounds obvious.` },
    { type: 'paragraph', text: `The remarkable thing is that the government says this is the first time in 30 years the railway will take such a coordinated approach across trains, track, depots and maintenance.` },
    { type: 'paragraph', text: `Britain has therefore spent decades paying leasing charges without a system-wide policy requiring public ownership to be tested alongside them each time.` },
    { type: 'heading', level: 2, text: `Public money still pays the bills` },
    { type: 'paragraph', text: `The dividend figures make the absence of a published comparison harder to ignore.` },
    { type: 'paragraph', text: `Private rolling-stock owners are entitled to make a return on capital they put at risk.` },
    { type: 'paragraph', text: `A dividend is not, by itself, evidence of overcharging.` },
    { type: 'paragraph', text: `But every pound paid to investors is part of the lifetime cost of the leasing model.` },
    { type: 'paragraph', text: `If government can borrow more cheaply than private companies and keep trains in service for decades, public ownership may sometimes be cheaper.` },
    { type: 'paragraph', text: `If private owners manage residual-value risk better, secure cheaper maintenance or move assets more efficiently, leasing may still win.` },
    { type: 'paragraph', text: `That is precisely why the missing comparison matters.` },
    { type: 'paragraph', text: `The government is telling taxpayers that outright ownership may save them substantial sums without showing them the numbers behind that conclusion.` },
    { type: 'paragraph', text: `There is another reason to watch this closely.` },
    { type: 'paragraph', text: `The railway remains heavily dependent on public money.` },
    { type: 'paragraph', text: `ORR recorded £11.9 billion of government funding for the operational rail industry in 2024/25, a 7 per cent fall from the year before, and confirmed this still represents nearly half, 46 per cent, of the industry's income. Passenger fares generated £11.5 billion, up 8.3 per cent on the year.` },
    { type: 'paragraph', text: `So the distinction between "private" train ownership and public spending is not as clean as it first appears.` },
    { type: 'paragraph', text: `The trains may sit on private balance sheets.` },
    { type: 'paragraph', text: `A railway supported by billions of pounds of public funding still pays the bills.` },
    { type: 'heading', level: 2, text: `The comparison has not been published` },
    { type: 'paragraph', text: `Great British Railways will now have the chance to test whether owning some future fleets produces better value.` },
    { type: 'paragraph', text: `That could vindicate the leasing model in some cases.` },
    { type: 'paragraph', text: `It could expose expensive decisions in others.` },
    { type: 'paragraph', text: `What should not happen is another 30 years in which one model survives largely because it was already there.` },
    { type: 'paragraph', text: `The government says public ownership could save substantial sums.` },
    { type: 'paragraph', text: `Taxpayers should now be shown exactly how much.` },
  ],
  evidence: {
    recordsReviewed: [
      'GOV.UK, 28 September 2026: "Government explores buying trains over leasing in new rail strategy" — GBR to assess ownership vs leasing vs other financing case by case; leasing no longer the default for new trains; £2.5bn decade-long ROSCO dividend figure; "substantial savings" language (unquantified); existing leasing contracts remain; "more than £4bn a year" leasing-and-maintenance cost claim; "first time in 30 years" coordinated-approach claim',
      'ORR Data Portal, Rail Industry Finance statistics, April 2024 to March 2025 — precise £4.1bn rolling-stock figure (£2.7bn leasing / £1.5bn maintenance / £61m other income); £11.9bn government funding (down 7% year-on-year, 46% of industry income); £11.5bn fares (up 8.3%); £275m ROSCO dividend total for 2024/25 (down 19% on prior year)',
      'ORR, Review of the Rolling Stock Transparency Order 2009 — Final Decision, 4 December 2025 — Transparency Order "continues to be appropriate and proportionate"; to be retained with updated wording. Distinct from the "have not been alleviated" finding, which is from ORR\'s earlier final report of 28 April 2020',
      'ORR, Rolling Stock Maintenance Market Review, Statement of Scope, 29 April 2026 — scope of ongoing maintenance-market review; expected autumn 2026 conclusion',
    ],
    lastChecked: '30 September 2026',
  },
};

export default piece;
