import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'hn4k9mxw7r',
  kicker: 'Accountability',
  headline: `Department Leading Grenfell Reforms Referred to CPS After Three Years Under Investigation`,
  standfirst: `The Ministry of Housing, Communities and Local Government was told by the Metropolitan Police in 2023 that it was under investigation for a potential health and safety offence connected to Grenfell. That fact was not made public until 30 September 2026, when police confirmed a file had been sent to the CPS. For three years the department simultaneously oversaw the government's building safety reform programme and knew it was itself under investigation.`,
  publishedAt: '2026-09-30',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `The government department responsible for leading much of the post-Grenfell building safety reform programme has been referred to the Crown Prosecution Service over a potential health and safety offence connected to the disaster.` },
    { type: 'paragraph', text: `The Ministry of Housing, Communities and Local Government said it was told by the Metropolitan Police in 2023 that it was itself under investigation.` },
    { type: 'paragraph', text: `That fact was not made public until 30 September 2026, when police confirmed that a file relating to the department had been sent to prosecutors.` },
    { type: 'paragraph', text: `The CPS will now decide whether the evidential and public-interest tests for any prosecution are met.` },
    { type: 'paragraph', text: `No charge has been brought against the department, and the referral should not be treated as evidence of criminal liability.` },
    { type: 'paragraph', text: `Seventy-two people died when Grenfell Tower burned in June 2017. Their families have waited more than nine years for the criminal process to reach this stage.` },
    { type: 'paragraph', text: `For three years, the department knew it was a subject of the criminal investigation while simultaneously overseeing and reporting on the government's response to the failures exposed by Grenfell.` },
    { type: 'paragraph', text: `MHCLG says it did not discuss its position publicly because it wanted to protect the integrity of the police investigation.` },
    { type: 'paragraph', text: `That is a clear and defensible reason for limiting disclosure.` },
    { type: 'paragraph', text: `It also meant Parliament and the public were not told that the department directing part of the response to Grenfell was itself being investigated in relation to it.` },
    { type: 'heading', level: 2, text: `Police are considering a possible health and safety offence` },
    { type: 'paragraph', text: `The Metropolitan Police has referred a file concerning MHCLG to the CPS for consideration of a potential breach of the Health and Safety at Work Act 1974.` },
    { type: 'paragraph', text: `The department is one part of a much wider criminal investigation.` },
    { type: 'paragraph', text: `The Met has submitted files concerning 20 companies and organisations and 54 individuals.` },
    { type: 'paragraph', text: `Potential offences across the investigation include corporate manslaughter, gross negligence manslaughter, health and safety offences, fraud-related offences and misconduct in public office.` },
    { type: 'paragraph', text: `Those offence categories apply across the wider investigation and should not be read as allegations against MHCLG specifically.` },
    { type: 'paragraph', text: `The department's own statement refers only to a possible Health and Safety at Work Act offence.` },
    { type: 'paragraph', text: `The CPS has said charging decisions are expected before the tenth anniversary of the fire in June 2027.` },
    { type: 'heading', level: 2, text: `The department says government failed` },
    { type: 'paragraph', text: `Housing Secretary Angela Rayner did not attempt to distance the state from the underlying failures.` },
    { type: 'paragraph', text: `In the department's statement, she said: "The Government failed in its fundamental duty to keep the residents of Grenfell Tower safe."` },
    { type: 'paragraph', text: `She added: "On behalf of the British state, I am sorry."` },
    { type: 'paragraph', text: `That acknowledgment is significant.` },
    { type: 'paragraph', text: `The Grenfell Tower Inquiry found extensive failures across government, regulators, manufacturers, contractors and other organisations.` },
    { type: 'paragraph', text: `The criminal process is now dealing with a narrower question: whether any of those failures crossed the threshold for criminal charges.` },
    { type: 'paragraph', text: `The CPS referral involving MHCLG does not answer that question.` },
    { type: 'paragraph', text: `It confirms only that police believe the evidence relating to the department warrants independent prosecutorial review.` },
    { type: 'heading', level: 2, text: `MHCLG has spent the past three years reporting on reform` },
    { type: 'paragraph', text: `The timing creates the harder public-interest issue.` },
    { type: 'paragraph', text: `Since being notified of the investigation in 2023, MHCLG has continued to lead major parts of the government's building safety response.` },
    { type: 'paragraph', text: `It has published progress reports.` },
    { type: 'paragraph', text: `It has overseen remediation programmes.` },
    { type: 'paragraph', text: `It has been responsible for implementing recommendations from the Grenfell Tower Inquiry.` },
    { type: 'paragraph', text: `And throughout that period, the public was not told that police were examining the department itself.` },
    { type: 'paragraph', text: `The department says silence was necessary to protect the investigation.` },
    { type: 'paragraph', text: `There is no evidence in the material released so far that the department's status affected the policies it subsequently pursued.` },
    { type: 'paragraph', text: `But there is now a legitimate distinction to make between two separate roles.` },
    { type: 'paragraph', text: `MHCLG has been both the department responsible for implementing lessons from Grenfell and an organisation whose earlier conduct was being examined by police.` },
    { type: 'paragraph', text: `That potential tension should have been visible once disclosure became possible.` },
    { type: 'heading', level: 2, text: `Half the inquiry recommendations are still unfinished, and so are thousands of buildings` },
    { type: 'paragraph', text: `The referral also comes while implementation of the Grenfell Inquiry's recommendations remains incomplete.` },
    { type: 'paragraph', text: `MHCLG's own September progress report records 61 recommendations being tracked.` },
    { type: 'paragraph', text: `Thirty had been completed.` },
    { type: 'paragraph', text: `Thirty-one were still in progress, including 19 of the 28 recommendations aimed at the construction industry, the sector at the centre of the original failures.` },
    { type: 'paragraph', text: `The government says it expects all recommendations to be implemented by the end of 2029, partly because some require further legislation.` },
    { type: 'paragraph', text: `That does not mean the government has made no progress.` },
    { type: 'paragraph', text: `Nine further recommendations had been completed since the previous update in May.` },
    { type: 'paragraph', text: `But the clearer measure of how much remains undone is not the recommendation count. It is the buildings themselves. As of July 2026, the government was still monitoring 4,697 buildings with unsafe cladding. Remediation had only started on 2,551 of them (54 per cent) and was fully complete on just 1,833, or 39 per cent of the total.` },
    { type: 'paragraph', text: `More than nine years after the fire, most of the buildings the government itself is tracking for the same kind of danger that killed 72 people in Grenfell Tower are not yet fixed.` },
    { type: 'paragraph', text: `The department now has to continue implementing those reforms while cooperating with prosecutors considering evidence about its own historical conduct.` },
    { type: 'heading', level: 2, text: `This is not proof that the reforms themselves are compromised` },
    { type: 'paragraph', text: `That distinction matters.` },
    { type: 'paragraph', text: `The police referral does not show that current building safety reforms are ineffective.` },
    { type: 'paragraph', text: `It does not show that present ministers or officials committed any offence.` },
    { type: 'paragraph', text: `And it does not establish that MHCLG will ultimately be prosecuted.` },
    { type: 'paragraph', text: `The Metropolitan Police has spent years reviewing an enormous body of evidence.` },
    { type: 'paragraph', text: `Its investigation examined the roles of more than 15,000 individuals and 700 organisations, gathered 165 million electronic files, took around 14,700 statements, and produced more than 12,600 pages of summary material for prosecutors.` },
    { type: 'paragraph', text: `A referral to the CPS is one stage in that process.` },
    { type: 'paragraph', text: `The CPS may decide that no charge should be brought.` },
    { type: 'heading', level: 2, text: `But the disclosure changes how the department's role should be understood` },
    { type: 'paragraph', text: `Until this week, government reporting on Grenfell reform was largely framed around what departments were doing in response to the failures identified by the Inquiry.` },
    { type: 'paragraph', text: `The disclosure adds another layer.` },
    { type: 'paragraph', text: `One of the departments responsible for delivering those reforms had itself been under criminal investigation since 2023.` },
    { type: 'paragraph', text: `The government had a reasonable argument for not commenting publicly while that investigation was active.` },
    { type: 'paragraph', text: `But now that the information is public, the department should explain as much as the criminal process allows.` },
    { type: 'paragraph', text: `When in 2023 was it notified? Which part of MHCLG's historical conduct was under examination? Which senior officials were told? Were ministers informed at the time? Did the department put any additional governance or conflict safeguards in place once it knew it was under investigation? And was Parliament ever informed privately through an appropriate mechanism?` },
    { type: 'paragraph', text: `Those are not questions about guilt.` },
    { type: 'paragraph', text: `They are questions about how a department manages accountability when it is both responsible for reform and itself part of the historical conduct under scrutiny, and about why, nine years on, most of the buildings it is responsible for making safe still are not.` },
    { type: 'paragraph', text: `The criminal process will decide whether there is a case to answer.` },
    { type: 'paragraph', text: `The transparency question exists already.` },
  ],
  evidence: {
    recordsReviewed: [
      'GOV.UK, "Statement from MHCLG Secretary of State," 30 September 2026 — 2023 notification date, Health and Safety at Work Act 1974 reference, Angela Rayner quotes ("The Government failed..." and "On behalf of the British state, I am sorry"), department\'s stated reason for non-disclosure, 72 deaths / nine-year wait figures',
      'Metropolitan Police, "Met submits all Grenfell files to the CPS for charging decisions" — 20 companies/organisations and 54 individuals referred, five potential offence categories (corporate manslaughter, gross negligence manslaughter, health and safety, fraud-related, misconduct in public office), investigation scale (15,000+ individuals, 700+ organisations, 165 million electronic files, ~14,700 statements, 12,600+ pages of summary material), June 2027 charging-decision commitment',
      'GOV.UK, Grenfell Tower Inquiry government progress report, September 2026 — 61 tracked recommendations (30 complete, 31 in progress, including 28/19 construction-industry breakdown), nine recommendations completed since May 2026 update, end-of-2029 implementation target, July 2026 remediation figures (4,697 buildings monitored, 2,551 with remediation started, 1,833 complete)',
    ],
    lastChecked: '30 September 2026',
  },
};

export default piece;
