import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'hn4k9mxw7r',
  kicker: 'Accountability',
  headline: `MHCLG, RBKC and London Fire Brigade Among Bodies Referred to CPS After Grenfell Investigation`,
  standfirst: `The Ministry of Housing, Communities and Local Government, the Royal Borough of Kensington and Chelsea and the London Fire Brigade are among the organisations referred to the Crown Prosecution Service following the Metropolitan Police's Grenfell investigation. MHCLG said it was notified in 2023 that it was under investigation, a fact not previously made public. RBKC is understood to face potential consideration of corporate manslaughter as well as health and safety offences; MHCLG's statement specifies only a Health and Safety at Work Act offence.`,
  publishedAt: '2026-09-30',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `The government department leading much of the post-Grenfell building safety programme has been referred to the Crown Prosecution Service over a potential health and safety offence connected to the disaster.` },
    { type: 'paragraph', text: `The Ministry of Housing, Communities and Local Government said it was told by the Metropolitan Police in 2023 that it was itself under investigation. That had not previously been made public. On 30 September, the department said police had referred a file relating to MHCLG to prosecutors for consideration of a potential breach of the Health and Safety at Work Act 1974.` },
    { type: 'paragraph', text: `MHCLG is not the only public body in the file. The Royal Borough of Kensington and Chelsea, Grenfell Tower's landlord, and the London Fire Brigade have separately confirmed they are also among the organisations referred to the CPS as part of the same submission. RBKC's position differs from MHCLG's in one significant respect: it is understood to be facing potential consideration of corporate manslaughter, as well as Health and Safety at Work Act and Fire Safety Order offences, while MHCLG's own statement specifies only the Health and Safety at Work Act offence, not manslaughter. The Met's press release does not name either body, and the detail comes from RBKC and the LFB's own separate confirmations, reported by trade press including Social Housing and Inside Housing.` },
    { type: 'paragraph', text: `No charge has been brought against any of them. The referral is not a finding of criminal liability. The CPS will now decide whether the evidence meets the test for prosecution.` },
    { type: 'paragraph', text: `Seventy-two people died in the Grenfell Tower fire in June 2017. The Metropolitan Police said the criminal investigation has examined more than 15,000 individuals and 700 organisations. Its submission to the CPS covers 20 companies and organisations and 54 individuals, with possible offences across the wider investigation including corporate manslaughter, gross negligence manslaughter, health and safety offences, fraud-related offences and misconduct in public office. Those offence categories apply to the investigation as a whole, not specifically to MHCLG.` },
    { type: 'paragraph', text: `Housing Secretary Angela Rayner said the government had "failed in its fundamental duty" to keep Grenfell residents safe and apologised on behalf of the British state. She also said the police investigation had been conducted independently of government.` },
    { type: 'paragraph', text: `MHCLG says it did not discuss its own status publicly because it wanted to protect the integrity of the investigation. The published statement does not say when during 2023 the department was notified.` },
    { type: 'paragraph', text: `During that period the department continued to oversee major parts of the government response to Grenfell, including building remediation and implementation of recommendations from the public inquiry.` },
    { type: 'paragraph', text: `Its latest progress report, published on 10 September, records 61 recommendations being tracked. Thirty had been completed and 31 remained in progress. Of 28 recommendations concerning the construction industry, nine were complete and 19 were still being worked on. The government says it expects all outstanding recommendations to be implemented by the end of 2029, partly because some require legislation.` },
    { type: 'paragraph', text: `At the end of July, MHCLG was monitoring 4,697 residential buildings over 11 metres with unsafe cladding. Work had started on 2,551 of them, or 54 per cent. Remediation had been completed on 1,833 buildings, 39 per cent of those being monitored. The department estimates that the 4,697 buildings it is monitoring represent between 64 and 81 per cent of all residential buildings over 11 metres expected to enter its remediation programmes.` },
    { type: 'paragraph', text: `Those figures describe current delivery. They do not show that the criminal investigation affected the department's later building safety work, and the material published so far provides no evidence that present ministers or officials are personally implicated in the conduct being considered by prosecutors. The police investigation concerns historical conduct connected to Grenfell; the current department is also responsible for carrying through many of the reforms intended to address what the Inquiry found.` },
    { type: 'paragraph', text: `The Metropolitan Police says the scale of its investigation explains much of the delay. Investigators gathered 165 million electronic files, took 14,700 statements and produced more than 12,600 pages of summary reports for prosecutors. The CPS has said charging decisions are expected before the tenth anniversary of the fire in June 2027.` },
    { type: 'paragraph', text: `MHCLG's 30 September statement confirms that the department knew from 2023 that it was a subject of that investigation. It does not say which ministers were informed at the time, which senior officials knew, or whether any additional governance arrangements were introduced while the department continued to oversee the government's Grenfell response.` },
  ],
  evidence: {
    recordsReviewed: [
      `Ministry of Housing, Communities and Local Government, "Statement from MHCLG Secretary of State", 30 September 2026: the 2023 notification, the department's reason for not previously discussing its status, the potential Health and Safety at Work Act offence, and Angela Rayner's statement on government responsibility`,
      `Metropolitan Police, "Met submits all Grenfell files to the CPS for charging decisions", 30 September 2026: the 20 companies and organisations, 54 individuals, potential offence categories, scale of the investigation and expected CPS timetable`,
      `Social Housing and Inside Housing trade press reporting, 30 September–1 October 2026: RBKC's and the London Fire Brigade's separate confirmations that they are also referred to the CPS, and the distinction between RBKC's potential corporate manslaughter exposure and MHCLG's Health and Safety at Work Act-only referral`,
      `MHCLG, Grenfell Tower Inquiry Government Progress Report, September 2026: the 61 tracked recommendations, completion figures, construction-industry breakdown, 2029 timetable and remediation data for 4,697 buildings`,
    ],
    lastChecked: '3 October 2026',
  },
};

export default piece;
