import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'hw9k4mxq2t',
  kicker: 'Water & Utilities',
  headline: `South East Water's Bosses Are Gone. Its Turnaround Plan Still Has to Be Written`,
  standfirst: `South East Water has lost its chair and chief executive after MPs declared they had no confidence in the company's leadership. Regulators have since formally found breaches of statutory and licence obligations, accepted legally enforceable undertakings and required the company to produce plans it has not yet completed. An independent monitor will report directly to Ofwat on whether those plans are delivered.`,
  publishedAt: '2026-07-20',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `South East Water has lost its chair and chief executive after MPs declared they had no confidence in the company's leadership.` },
    { type: 'paragraph', text: `Regulators have now gone further.` },
    { type: 'paragraph', text: `On 14 July, Ofwat concluded three investigations into South East Water, found breaches of its statutory and licence obligations and accepted legally enforceable undertakings intended to force changes to the way the company operates.` },
    { type: 'paragraph', text: `What South East Water does not yet have is the finished plan showing how those changes will be delivered.` },
    { type: 'paragraph', text: `Ofwat is requiring the company to produce a Performance Improvement Plan, a separate Remediation Plan and a financing plan. An independent monitor will report directly to the regulator on whether the company delivers them.` },
    { type: 'paragraph', text: `The intervention follows years of supply failures and the collapse of confidence in the company's leadership after Tunbridge Wells lost reliable drinking water in November and December 2025.` },
    { type: 'paragraph', text: `Around 24,000 properties were affected. More than 60,000 people experienced little or no drinking water for several days and remained under a boil-water notice until 12 December. Schools, medical facilities, care settings and businesses were disrupted.` },
    { type: 'paragraph', text: `South East Water initially blamed an unforeseeable change in raw water quality.` },
    { type: 'paragraph', text: `The Drinking Water Inspectorate reached a different conclusion.` },
    { type: 'paragraph', text: `Its investigation, published in April, found that the incident was foreseeable and preventable. It identified longstanding problems with process control, monitoring, maintenance and operational management at Pembury water treatment works rather than exceptional raw-water conditions.` },
    { type: 'paragraph', text: `The Inspectorate placed South East Water into a formal transformation programme, which it describes as one of its most significant interventions and one used when repeated failures cannot be dealt with adequately through individual enforcement actions.` },
    { type: 'paragraph', text: `The Environment, Food and Rural Affairs Committee reached an equally severe conclusion on 1 May.` },
    { type: 'paragraph', text: `Its report found that South East Water had failed to monitor important risks, maintain assets, prepare adequately for outages and learn from earlier incidents. It said the company had been warned repeatedly about weaknesses in its system and had failed to build sufficient resilience into parts of its network.` },
    { type: 'paragraph', text: `The committee said it had no confidence in either the executive or non-executive leadership.` },
    { type: 'paragraph', text: `Chair Chris Train resigned as the report was published. Chief executive David Hinton announced his resignation a week later. Parliament's own account subsequently said the committee's report had prompted both departures.` },
    { type: 'paragraph', text: `South East Water announced John Halsall as chief executive-designate on 22 June, subject to regulatory approval. Lisa Clement had taken over as interim chair.` },
    { type: 'paragraph', text: `Changing the people at the top did not resolve the regulatory breaches.` },
    { type: 'paragraph', text: `Ofwat had already been investigating South East Water's water-supply resilience since November 2023. In March this year it proposed a £22.46 million penalty, equal to 8 per cent of relevant turnover.` },
    { type: 'paragraph', text: `The regulator found that between 2020 and 2023 South East Water had failed to maintain an efficient water-supply system, had not adequately maintained infrastructure including reservoirs, boreholes and major pipes and had repeatedly failed to learn from previous interruptions.` },
    { type: 'paragraph', text: `More than 286,000 people were affected by the incidents considered in that investigation.` },
    { type: 'paragraph', text: `A separate investigation examined South East Water's customer service during the outages between November 2025 and January 2026. Ofwat concluded that it would otherwise have imposed an £8 million penalty, equivalent to 2.85 per cent of relevant turnover, for failing to provide customers with adequate information and support, failing to supply enough bottled water to everyone who needed it and again failing to learn from earlier incidents.` },
    { type: 'paragraph', text: `Ofwat did not impose either that penalty or the £22.46 million proposed in the earlier supply-resilience case. Instead, it accepted a £30.5 million shareholder-funded redress package and legally enforceable undertakings covering the two investigations.` },
    { type: 'paragraph', text: `A conventional fine would have been a financial penalty paid to the Treasury. The replacement package requires the money to be spent on measures intended to improve resilience and support affected communities.` },
    { type: 'paragraph', text: `Of the £30.5 million, £13 million is reserved for work forming part of a future Remediation Plan. Another £16 million will pay for measures including water storage at vulnerable sites, smart meters and other demand-management work. The remaining £1.5 million will go into a community fund for areas affected by serious supply failures.` },
    { type: 'paragraph', text: `South East Water argued that replacing the fine with the package meant the money would directly benefit customers rather than simply being paid as a penalty. It accepted Ofwat's findings and apologised for the disruption.` },
    { type: 'paragraph', text: `The arrangement is not voluntary in the ordinary sense.` },
    { type: 'paragraph', text: `The undertakings were accepted under section 19 of the Water Industry Act and can be enforced by Ofwat. The regulator concluded that the commitments were sufficient at this stage to secure compliance, meaning it was no longer required to impose an enforcement order for the same breaches.` },
    { type: 'paragraph', text: `Ofwat is also responding to a separate financial problem.` },
    { type: 'paragraph', text: `Moody's downgraded the debt rating of South East Water's financing company to below investment grade on 28 May. That left South East Water in breach of a licence condition requiring it to maintain two investment-grade credit ratings.` },
    { type: 'paragraph', text: `Ofwat imposed no financial penalty for that breach.` },
    { type: 'paragraph', text: `Instead, South East Water must prepare a financing plan, restore two investment-grade ratings and develop and publish a Performance Improvement Plan addressing supply resilience, operational performance and the causes of interruptions.` },
    { type: 'paragraph', text: `It must also pay for an independent monitor appointed by Ofwat to oversee the company's wider operational and financial turnaround.` },
    { type: 'paragraph', text: `The regulatory settlement therefore does more than the original government response published four days earlier.` },
    { type: 'paragraph', text: `Defra's response to the EFRA report, published on 10 July, acknowledged that South East Water's performance was unacceptable and said the resignations of its chair and chief executive were appropriate.` },
    { type: 'paragraph', text: `It did not announce a government takeover or direct intervention in the ownership of the company. Instead, ministers pointed to the enforcement processes already under way at Ofwat and the Drinking Water Inspectorate and to wider reform of the water industry.` },
    { type: 'paragraph', text: `The government's response said South East Water was already funded to make the improvements required and now had to demonstrate "credible leadership, a robust plan and early evidence of delivery".` },
    { type: 'paragraph', text: `Six days after that response was received by the committee, Ofwat's final decisions made the absence of a completed plan explicit.` },
    { type: 'paragraph', text: `The regulator has required South East Water to produce one.` },
    { type: 'paragraph', text: `It must commission an independent review of the root causes of its supply failures. That review will inform a Remediation Plan which Ofwat must approve. The company must separately produce its Performance Improvement Plan and publish updates on delivery.` },
    { type: 'paragraph', text: `This follows years in which regulators had already identified many of the underlying problems.` },
    { type: 'paragraph', text: `The EFRA Committee found that the two main water regulators had written jointly to South East Water for four consecutive years warning that its water-resource planning did not adequately address the balance between supply and demand.` },
    { type: 'paragraph', text: `Ofwat found the company had failed to maintain sufficient headroom in its eastern region since 2018.` },
    { type: 'paragraph', text: `The Drinking Water Inspectorate audited Pembury in March 2024 and identified deficiencies in capacity, resilience, maintenance and treatment management. South East Water submitted a formal risk report in September that year, and the DWI subsequently served a Regulation 28 improvement notice requiring work at the site.` },
    { type: 'paragraph', text: `Before the November 2025 failure, South East Water then failed to carry out jar tests which the DWI had required to help manage treatment problems at Pembury.` },
    { type: 'paragraph', text: `The committee concluded that the company was effectively "flying blind" as conditions deteriorated.` },
    { type: 'paragraph', text: `There is evidence in South East Water's favour on one part of the longer argument.` },
    { type: 'paragraph', text: `The company has maintained that the regulatory funding system left too little capacity for resilience investment. The EFRA Committee said spending allowances may indeed have made some investment choices harder, and noted that Competition and Markets Authority decisions in March 2026 had partially supported South East Water's case for greater resilience allowances.` },
    { type: 'paragraph', text: `But the committee also found that responsibility for making credible investment cases rested with the company, and that South East Water had either failed to make those cases or had not pursued them through earlier price reviews.` },
    { type: 'paragraph', text: `The government plans to replace the existing fragmented regulatory structure with a single water regulator through its proposed Clean Water Bill.` },
    { type: 'paragraph', text: `That legislation was included in the 2026 King's Speech. As recently as 9 July, Defra minister Emma Hardy said only that it would be introduced "in due course". No introduction date had been announced by 20 July.` },
    { type: 'paragraph', text: `South East Water is therefore no longer in the position it was when MPs published their report in May.` },
    { type: 'paragraph', text: `Its chair and chief executive are leaving. The DWI has placed it in a transformation programme. Ofwat has formally found legal and licence breaches. £30.5 million has been committed to remediation and customer measures. An independent monitor will oversee its recovery.` },
    { type: 'paragraph', text: `What remains untested is whether any of that produces a reliable water supply.` },
    { type: 'paragraph', text: `The Performance Improvement Plan intended to demonstrate how South East Water will turn itself around had still to be produced.` },
  ],
  evidence: {
    recordsReviewed: [
      `Environment, Food and Rural Affairs Committee, Failures at South East Water, 1 May 2026: documents the failures at Pembury and elsewhere, repeated regulatory warnings, weaknesses in maintenance, planning, investment, customer support and governance, and the committee's loss of confidence in the company's leadership`,
      `Government Response to Failures at South East Water, published 10 July 2026: records Defra's response to the resignations, the company's continuing regulatory breaches and the government's proposed wider water-sector reforms`,
      `Drinking Water Inspectorate, Event Assessment Letter – Water Quality, Tunbridge Wells loss of supply, 14 April 2026: finds the November and December 2025 incident foreseeable and preventable, identifies longstanding operational, monitoring, maintenance and management failures, and records the March 2024 audit of Pembury works and the subsequent Regulation 28(4) improvement notice`,
      `Ofwat, South East Water supply-resilience final decision, 14 July 2026: establishes breaches of section 37 of the Water Industry Act and licence conditions, the £22.46 million penalty Ofwat otherwise intended to impose and the enforceable undertakings accepted in its place`,
      `Ofwat, South East Water customer-service final decision, 14 July 2026: records breaches relating to customer support and communication during the 2025 and 2026 incidents and the £8 million penalty, equivalent to 2.85 per cent of relevant turnover, that Ofwat otherwise intended to impose`,
      `Ofwat, £30.5 million redress package and independent monitor, 14 July 2026: sets out the allocation of the shareholder-funded package and the requirement for independent oversight, remediation and a Performance Improvement Plan`,
      `Ofwat, South East Water licence Condition P26 decision, 14 July 2026: records the investment-grade credit-rating breach and requirements for a financing plan, Performance Improvement Plan and independent monitor`,
      `South East Water, response to Ofwat undertakings, 14 July 2026: gives the company's explanation for agreeing the redress package and its acceptance of Ofwat's findings`,
      `South East Water, announcement of John Halsall as CEO-designate, 22 June 2026: records the appointment intended to replace David Hinton and the company's stated plans for operational change`,
      `UK Parliament written answer 15844, 9 July 2026, and the 2026 King's Speech: confirm that the Clean Water Bill had been announced but that ministers had not provided a specific introduction date, saying it would be brought forward "in due course"`,
    ],
    lastChecked: '5 October 2026',
  },
};

export default piece;
