import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'hx4m2kq9w7',
  kicker: 'Drug Pricing',
  headline: `NHS Paid 70p for These Tablets. Eight Years Later It Was £88`,
  standfirst: `In April 2008, the NHS was being charged 70p for a pack of 10mg hydrocortisone tablets. By March 2016, the reimbursement figure had reached £88. Annual NHS spending on the drug rose from around £500,000 to more than £80 million. On 28 July, the Court of Appeal upheld the Competition and Markets Authority's finding that the companies responsible had abused a dominant market position by charging excessive and unfair prices.`,
  publishedAt: '2026-07-28',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `In April 2008, the NHS was being charged 70p for a pack of 10mg hydrocortisone tablets.` },
    { type: 'paragraph', text: `By March 2016, the reimbursement figure had reached £88.` },
    { type: 'paragraph', text: `For the 20mg version, the corresponding figure rose from £1.07 to £102.74. The medicine itself was not new. Hydrocortisone tablets had been sold in Britain since 1955.` },
    { type: 'paragraph', text: `Those figures need distinguishing from the manufacturer's own selling price.` },
    { type: 'paragraph', text: `The Court of Appeal records that Auden Mckenzie launched the generic 10mg tablets at £4.54 a pack and the 20mg tablets at £5.14. Its selling prices subsequently peaked at £72.14 and £72.19 respectively. The higher £88 and £102.74 figures cited by the CMA in 2016 reflected what the NHS was being charged through the reimbursement system, rather than Auden's own transaction price.` },
    { type: 'paragraph', text: `Both measures show the same extraordinary movement in the cost of an old medicine, but they are not interchangeable.` },
    { type: 'paragraph', text: `On 28 July, the Court of Appeal upheld the Competition and Markets Authority's finding that Auden Mckenzie and its successor Actavis UK had abused a dominant market position by charging excessive and unfair prices for hydrocortisone tablets.` },
    { type: 'paragraph', text: `Lord Justice Zacaroli said none of the arguments put forward on appeal came "near" to displacing the findings of the CMA and Competition Appeal Tribunal.` },
    { type: 'paragraph', text: `The case began with a change that should normally have made a medicine cheaper.` },
    { type: 'paragraph', text: `Merck Sharp & Dohme had sold hydrocortisone under the brand name Hydrocortone. In April 2008 it sold the brand and marketing authorisations for the 10mg and 20mg tablets to Auden Mckenzie.` },
    { type: 'paragraph', text: `Auden removed the brand and relaunched the tablets as generic medicines.` },
    { type: 'paragraph', text: `Branded medicines were subject to price controls. Generic medicines were not, because the system assumed that competing manufacturers would enter the market and force prices down.` },
    { type: 'paragraph', text: `That competition did not arrive for years.` },
    { type: 'paragraph', text: `The Court of Appeal records that immediately before de-branding the 10mg tablets sold for 70p and the 20mg tablets for £1.07.` },
    { type: 'paragraph', text: `Auden relaunched them at £4.54 and £5.14.` },
    { type: 'paragraph', text: `By 1 October 2008, less than six months after acquiring the licences, its selling prices had reached £22.28 for 10mg tablets and £23.74 for 20mg tablets. The CMA chose that date as the beginning of the infringement period even though, as the court noted, large price increases had already taken place.` },
    { type: 'paragraph', text: `Prices continued rising.` },
    { type: 'paragraph', text: `The 10mg selling price eventually reached £72.14 a pack and the 20mg price £72.19. The CMA calculated that a price incorporating the cost of supplying the tablets plus a reasonable return was between £2.17 and £4.50 for the 10mg version and between £2.91 and £5.20 for the 20mg version.` },
    { type: 'paragraph', text: `The Court of Appeal said it was common ground that the prices charged were vastly above that calculation.` },
    { type: 'paragraph', text: `There had been no improvement to the tablets, their manufacture or their distribution, and no investment or innovation in the medicine capable of explaining the increase.` },
    { type: 'paragraph', text: `The absence of normal generic competition was not accidental.` },
    { type: 'paragraph', text: `The CMA found that Auden entered agreements with two companies which were preparing competing versions of the tablets.` },
    { type: 'paragraph', text: `Waymade was preparing 10mg and 20mg hydrocortisone. AMCo, now part of Advanz Pharma, was developing a 10mg version.` },
    { type: 'paragraph', text: `Instead of competing independently, they received payments while remaining out of the market.` },
    { type: 'paragraph', text: `The CMA found that Auden paid Waymade £1.8 million during the relevant agreement and paid AMCo £21 million. Actavis UK continued paying AMCo after taking over the hydrocortisone business in 2015.` },
    { type: 'paragraph', text: `The 20mg agreement with Waymade ran from July 2011 until April 2015.` },
    { type: 'paragraph', text: `The 10mg arrangement involved Waymade briefly in October 2012 before AMCo became Auden's counterparty. It continued until June 2016.` },
    { type: 'paragraph', text: `The CMA concluded that the agreements delayed independent competition and helped preserve Auden and later Actavis UK's ability to charge high prices.` },
    { type: 'paragraph', text: `The effect on NHS spending was substantial.` },
    { type: 'paragraph', text: `Annual NHS spending on hydrocortisone tablets was around £500,000 in 2007. By 2016 it was more than £80 million.` },
    { type: 'paragraph', text: `Hydrocortisone is used by people whose adrenal glands do not produce enough cortisol, including people with Addison's disease. For those patients it is not an optional treatment. Severe adrenal insufficiency can become life-threatening.` },
    { type: 'paragraph', text: `The Court of Appeal rejected the argument that the importance of the medicine to patients justified the prices charged.` },
    { type: 'paragraph', text: `The CMA had already included a reasonable return in its calculation of what the drug could cost. The court noted that patient benefit did not explain why Auden's tablets should command such a premium when competing hydrocortisone products were medically equivalent.` },
    { type: 'paragraph', text: `What happened when competitors finally entered the market was also part of the evidence against the companies.` },
    { type: 'paragraph', text: `The first competing immediate-release 10mg product arrived in October 2015. More followed during 2016 and 2017.` },
    { type: 'paragraph', text: `Prices then fell.` },
    { type: 'paragraph', text: `The Court of Appeal records that Auden and Actavis UK's 10mg selling price had fallen to £20.23 by July 2018. By the time of the CMA's 2021 decision, its 10mg product was selling at £2.99 and its 20mg product at £1.19.` },
    { type: 'paragraph', text: `Competing products were also selling for only a few pounds a pack.` },
    { type: 'paragraph', text: `The CMA found excessive and unfair pricing of the 10mg tablets from October 2008 until July 2018 and of the 20mg tablets from October 2008 until January 2017.` },
    { type: 'paragraph', text: `Its findings on the anti-competitive agreements have also survived the appeals process.` },
    { type: 'paragraph', text: `The existence of the 20mg market-sharing agreement was not appealed. The 10mg agreement went through a more complicated series of judgments after the Competition Appeal Tribunal initially found a procedural problem in the CMA's case. The Court of Appeal overturned that ruling in 2024, leaving the CMA's finding that the agreement breached competition law intact.` },
    { type: 'paragraph', text: `The remaining uncertainty is over the size of the penalties.` },
    { type: 'paragraph', text: `The CMA originally imposed fines totalling £266.5 million across the companies involved. The Competition Appeal Tribunal later reduced Allergan's liability by about £26 million because it did not control Actavis UK during part of 2016.` },
    { type: 'paragraph', text: `The penalties currently stand at about £240 million.` },
    { type: 'paragraph', text: `The Court of Appeal has not overturned the infringement findings.` },
    { type: 'paragraph', text: `It has sent the penalty appeals back to the Competition Appeal Tribunal because it concluded that the tribunal had not adequately addressed the companies' arguments over the fines.` },
    { type: 'paragraph', text: `Zacaroli said that did not mean the Court of Appeal had accepted those arguments. The tribunal must now consider them properly and explain its conclusions.` },
    { type: 'paragraph', text: `A separate CAT hearing concerning penalties for the 10mg anti-competitive agreement is listed for January 2027.` },
    { type: 'paragraph', text: `The amount ultimately paid in fines therefore remains unsettled.` },
    { type: 'paragraph', text: `Eighteen years after Auden bought the licences, the Court of Appeal has upheld the findings that the prices were excessive and unfair.` },
  ],
  evidence: {
    recordsReviewed: [
      `Court of Appeal, Auden McKenzie (Pharma Division) Ltd and others v Competition and Markets Authority, [2026] EWCA Civ 974, 28 July 2026: the acquisition and de-branding history, actual selling prices, dates of the infringements, Cost Plus calculations, lack of investment or innovation justifying the increases, entry of competitors, subsequent price falls, rejection of the substantive appeals and remission of the penalty issues to the Competition Appeal Tribunal`,
      `Competition and Markets Authority, "Pharmaceutical company accused of overcharging NHS", 16 December 2016: the historic NHS charging figures of 70p to £88 for 10mg tablets and £1.07 to £102.74 for 20mg tablets by March 2016 — these figures should not be confused with Auden/Actavis's own selling prices subsequently examined by the courts`,
      `Competition and Markets Authority, Hydrocortisone tablets: alleged excessive and unfair pricing, anti-competitive agreements and abusive conduct, case 50277: the infringement periods, procedural history, Court of Appeal outcomes and current status of the case`,
      `Competition and Markets Authority, "CMA finds drug companies overcharged NHS", 15 July 2021: the £21 million paid to AMCo, £1.8 million paid to Waymade, the duration and nature of the anti-competitive agreements and the original £266.5 million penalties`,
      `Competition and Markets Authority, "Court upholds CMA findings that firms charged excessive and unfair prices for lifesaving NHS-funded medicine", 28 July 2026: annual NHS spending rising from around £500,000 in 2007 to more than £80 million in 2016, the present approximately £240 million penalty total following the earlier reduction, and the January 2027 CAT hearing on the 10mg agreement penalty`,
    ],
    lastChecked: '4 October 2026',
  },
};

export default piece;
