import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'hx7n4qw2mk',
  kicker: 'Policing',
  headline: `Operation Hexagon Arrested an Oldham Campaigner. GMP Has Never Reviewed What the Operation Did`,
  standfirst: `In March this year, Greater Manchester Police was asked what Operation Hexagon's official scope was. The force did not provide a document setting it out. It replied that the information was already in the public domain through a Google search. The same Freedom of Information request asked whether Hexagon had ever been reviewed for its legality, conduct or effectiveness. GMP's answer was no.`,
  publishedAt: '2026-07-16',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `In March this year, Greater Manchester Police was asked a straightforward question about Operation Hexagon: what was its official scope?` },
    { type: 'paragraph', text: `The force did not provide a document setting it out. It replied that the information was already in the public domain through a Google search.` },
    { type: 'paragraph', text: `The same Freedom of Information request asked whether Hexagon had ever been reviewed for its legality, conduct or effectiveness.` },
    { type: 'paragraph', text: `GMP's answer was no.` },
    { type: 'paragraph', text: `Operation Hexagon ran for roughly two and a half years during one of the most bitter periods in Oldham's argument over historic child sexual exploitation. It dealt with allegations being made online, supported the independent review into Oldham's safeguarding failures and resulted in police action against at least one prominent campaigner.` },
    { type: 'paragraph', text: `What it was actually established to do is harder to pin down because the official descriptions have changed.` },
    { type: 'paragraph', text: `In December 2020, Assistant Chief Constable Nick Bailey gave the clearest contemporary explanation. He said Hexagon had been established as GMP's policing response to work already under way between the force and Oldham Council and had acted as the joint Gold Group for police and council activity.` },
    { type: 'paragraph', text: `It concerned allegations made on social media about named individuals. Some related to child welfare and safeguarding. Others alleged different criminal offences.` },
    { type: 'paragraph', text: `Bailey said GMP had consequently broadened the investigation to cover "any and all allegations of criminality". Where police believed the evidential threshold had been met, matters were referred to the Crown Prosecution Service. At that point, he said, none of those referrals concerned child sexual exploitation or the safeguarding of children.` },
    { type: 'paragraph', text: `That account does not support the claim that Hexagon was simply an operation created to investigate people who spoke about grooming gangs.` },
    { type: 'paragraph', text: `Nor was it simply the police investigation into the alleged abusers.` },
    { type: 'paragraph', text: `The independent Oldham safeguarding review shows that Hexagon covered both sides of that divide. Its terms of reference said active criminal enquiries would not be duplicated by the review and that GMP would instead share progress from Operation Hexagon with the reviewers. The review team also obtained a confidential GMP investigation produced under Hexagon which examined information held by police about alleged CSE risks in Oldham shisha bars and involving private hire drivers.` },
    { type: 'paragraph', text: `GMP's October 2020 internal work had been commissioned after concerns were raised on social media.` },
    { type: 'paragraph', text: `The independent review later found serious safeguarding failures in Oldham, including in the treatment of a girl identified as Sophie, while finding no evidence that senior managers or councillors had sought to cover up the existence of CSE. It also found no evidence of widespread exploitation in the particular settings it examined, including shisha bars, children's homes and the taxi trade.` },
    { type: 'paragraph', text: `Hexagon therefore sat in an unusual position. Police were examining allegations about historic exploitation and institutional conduct while also investigating possible criminal offences arising from the wider online dispute surrounding those allegations.` },
    { type: 'paragraph', text: `Raja Miah was one of the people caught by that second part.` },
    { type: 'paragraph', text: `Miah had built a large online following by publishing allegations about grooming, politicians, council officers and public bodies in Oldham. On 23 July 2021, GMP arrested him on suspicion of racially aggravated public-order and malicious communications offences connected with social-media posts.` },
    { type: 'paragraph', text: `There is now public evidence that the arrest was linked to Operation Hexagon.` },
    { type: 'paragraph', text: `In a later complaint by Miah against the Oldham Times, the newspaper supplied IPSO with its correspondence with GMP. The press regulator recorded that police had confirmed the action against him was taken in connection with Operation Hexagon. IPSO did not find that the newspaper had invented the connection.` },
    { type: 'paragraph', text: `That does not establish that Miah was arrested because he exposed child sexual exploitation or because police wanted to silence criticism. The suspected offences concerned his own online communications, and allegations that his prosecution was politically motivated were denied by those involved.` },
    { type: 'paragraph', text: `It does establish that Hexagon was capable of reaching beyond investigation of the underlying CSE allegations and into the conduct of people taking part in the public battle around them.` },
    { type: 'paragraph', text: `By July 2022, Oldham Council was describing the operation differently.` },
    { type: 'paragraph', text: `Asked directly whether the council had been involved in an operation targeting whistleblowers, council leader Amanda Chadderton said Hexagon was a GMP initiative "examining the community impact of historic Child Sexual Exploitation being made online". She said Oldham Council supported the operation but that requests for its paperwork would have to be directed to GMP.` },
    { type: 'paragraph', text: `That description is narrower than Bailey's account from 2020, which described a joint Gold Group considering social-media allegations involving named people and investigating any criminality arising from them.` },
    { type: 'paragraph', text: `There is even disagreement over when the operation began.` },
    { type: 'paragraph', text: `Bailey said publicly in December 2020 that Hexagon had been established in August 2019. GMP's March 2026 Freedom of Information response says it ran from September 2019 to February 2022. The force did not explain the difference.` },
    { type: 'paragraph', text: `The same FOI request asked for investigative methods, the types of people subjected to police action, Oldham Council's involvement and the number of convictions resulting from Hexagon.` },
    { type: 'paragraph', text: `GMP refused the wider request on cost grounds. It said the information was not centrally retrievable and that officers who had worked on the operation would have to be contacted individually. The force said it did not even hold a complete list of all officers involved in a form that could readily be extracted.` },
    { type: 'paragraph', text: `That makes the absence of any subsequent review more significant.` },
    { type: 'paragraph', text: `Hexagon was organised at Gold Group level, involved cooperation between a police force and a local authority, remained active for more than two years and was operating while GMP itself was under serious criticism over its past treatment of CSE victims.` },
    { type: 'paragraph', text: `In June 2022, after the independent safeguarding review was finally published, GMP created a separate investigation, Operation Sherwood, to examine possible offences involving ten survivors highlighted in that report.` },
    { type: 'paragraph', text: `Hexagon had ended four months earlier.` },
    { type: 'paragraph', text: `Andy Burnham was Mayor of Greater Manchester throughout the operation. Since 2017 the mayor has also exercised the functions of the Police and Crime Commissioner, with a statutory responsibility to hold GMP's Chief Constable to account. Day-to-day operational policing decisions remained with the Chief Constable.` },
    { type: 'paragraph', text: `There is no published evidence that Burnham ordered Operation Hexagon, selected anybody for investigation or directed Miah's arrest.` },
    { type: 'paragraph', text: `The operation was, however, connected to an Oldham assurance review commissioned through Greater Manchester's mayoral arrangements. Its published terms said the review reported formally through the deputy mayor and that GMP would provide the review team with updates from Hexagon.` },
    { type: 'paragraph', text: `The public record still does not show what scrutiny the mayoral policing system applied specifically to Hexagon while it was running.` },
    { type: 'paragraph', text: `In June this year, the Home Office was asked whether it had ever received briefings on the operation. It said Hexagon had been established independently by GMP and that the department was not aware of receiving any briefings.` },
    { type: 'paragraph', text: `GMP's own position is now unusually stark.` },
    { type: 'paragraph', text: `It says Operation Hexagon ended in February 2022. It says there has been no internal or external review assessing its legality, conduct or effectiveness. Asked in 2026 to explain its official scope, the force pointed the requester towards a Google search.` },
  ],
  evidence: {
    recordsReviewed: [
      `Greater Manchester Police, Freedom of Information response 01/FOI/26/016442/N, 20 March 2026: GMP's stated September 2019 to February 2022 dates, the absence of a review of Hexagon's legality, conduct or effectiveness, and the force's refusal of much of the request on cost grounds`,
      `Assistant Chief Constable Nick Bailey statement, December 2020, reported by the Local Democracy Reporting Service and Oldham Chronicle: the contemporary description of Hexagon as a joint Gold Group dealing with social-media allegations involving named people and a broadened investigation into alleged criminality`,
      `Newsam and Ridgway, The review into historic safeguarding practices in the borough of Oldham, June 2022: shows that the independent review was to receive progress reports from Operation Hexagon and that reviewers examined a confidential GMP investigation produced under Hexagon concerning shisha bars and private hire drivers`,
      `Greater Manchester Combined Authority, Oldham safeguarding review summary, 20 June 2022: supports the findings of serious safeguarding failures including the case of Sophie, alongside the finding that no evidence of a senior-level cover-up or widespread CSE in the specific settings examined was found`,
      `Oldham Council, public questions, 13 July 2022: records the council leader's description of Hexagon as examining the community impact of historic CSE claims made online and confirms the council supported the GMP initiative`,
      `IPSO, Miah v The Oldham Times, ruling published 12 May 2022: records that the newspaper supplied correspondence in which GMP confirmed police action against Raja Miah had been taken in connection with Operation Hexagon`,
      `Greater Manchester Combined Authority, policing responsibilities: confirms that the Mayor exercises Police and Crime Commissioner functions and is responsible for holding the Chief Constable and GMP to account, while operational policing remains the responsibility of the Chief Constable`,
      `Home Office written parliamentary answer, 8 July 2026: states that Operation Hexagon was established independently by GMP and that the Home Office was not aware of having received briefings on it`,
      `Greater Manchester Combined Authority CSE timeline: confirms that Operation Sherwood was launched in June 2022 to investigate potential offences involving ten survivors identified by the Oldham assurance review`,
    ],
    lastChecked: '4 October 2026',
  },
};

export default piece;
