import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'ia4k9mxw7r',
  kicker: 'Accountability',
  headline: `Government Publishes £209m Crime Law Costing Five Months After Parliament Passed It`,
  standfirst: `The government published a £208.9 million cost estimate for criminal-law measures in the Crime and Policing Act five months after the legislation received Royal Assent in April 2026. The figure is more than double the £97 million estimated at Bill stage. The enactment-stage document carries a blank date field and no ministerial signature.`,
  publishedAt: '2026-09-29',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `The government has published a £208.9 million cost estimate for criminal-law measures in the Crime and Policing Act five months after the legislation received Royal Assent.` },
    { type: 'paragraph', text: `The final impact assessment, published on 29 September, puts the ten-year net present cost of the measures at £208.9 million, with average annual costs of £24.5 million.` },
    { type: 'paragraph', text: `The Act became law on 29 April 2026. The final enactment-stage assessment was not published until 29 September.` },
    { type: 'paragraph', text: `That timing matters because the equivalent criminal-law package attached to the original Bill in February 2025 carried a much lower estimate of £97 million over ten years.` },
    { type: 'paragraph', text: `The two figures are not directly comparable measure for measure. The legislation changed as it passed through Parliament and the final Act contains additional provisions.` },
    { type: 'paragraph', text: `But that is precisely why the final costing matters.` },
    { type: 'paragraph', text: `Parliament ultimately approved a broader and more expensive package than the one originally assessed, yet the enactment-stage document setting out the £208.9 million estimate appeared months after the law was passed.` },
    { type: 'heading', level: 2, text: `Police, prisons and probation carry most of the cost` },
    { type: 'paragraph', text: `The latest assessment estimates annual police costs of £8.9 million.` },
    { type: 'paragraph', text: `His Majesty's Prison and Probation Service accounts for another £15 million a year.` },
    { type: 'paragraph', text: `Court costs are put at £200,000 annually and legal aid at £400,000.` },
    { type: 'paragraph', text: `The main drivers are changes to intimate-image offences and new offences covering rape and other penetrative sexual activity with a child under 16 by an adult who did not reasonably believe the child was 16 or over.` },
    { type: 'paragraph', text: `The assessment assumes the package will eventually create about 5,000 additional police-recorded crimes each year, leading to more than 400 prosecutions and 300 convictions annually once the measures reach steady state.` },
    { type: 'paragraph', text: `Those are not trivial consequences for a criminal justice system already carrying severe pressure in courts and prisons.` },
    { type: 'paragraph', text: `Yet MPs did not have this final enactment-stage assessment in front of them before Royal Assent.` },
    { type: 'heading', level: 2, text: `The cost estimate has more than doubled since the original Bill` },
    { type: 'paragraph', text: `The February 2025 criminal-law assessment estimated a ten-year cost of £97 million.` },
    { type: 'paragraph', text: `The final figure is £208.9 million.` },
    { type: 'paragraph', text: `That is an increase of almost £112 million.` },
    { type: 'paragraph', text: `It would be wrong to present that as a simple government forecasting error.` },
    { type: 'paragraph', text: `The final Act contains measures that were not part of the earlier package, and other provisions were amended during the Bill's passage.` },
    { type: 'paragraph', text: `What is not clear from the 29 September publication is when ministers first knew the final package would cost around £209 million.` },
    { type: 'paragraph', text: `That is now the important question.` },
    { type: 'paragraph', text: `If the higher figure was available before April, why was it not published before Parliament finished considering the legislation?` },
    { type: 'paragraph', text: `If it was only calculated afterwards, why was the final economic assessment not completed before enactment?` },
    { type: 'paragraph', text: `Either answer would tell us something important about the quality of scrutiny surrounding the Bill.` },
    { type: 'heading', level: 2, text: `The published document is visibly unfinished in places` },
    { type: 'paragraph', text: `There is another oddity.` },
    { type: 'paragraph', text: `The enactment-stage assessment carries no visible date on its front page.` },
    { type: 'paragraph', text: `The field marked "Date" is blank.` },
    { type: 'paragraph', text: `The section for the responsible minister's signature also contains the template wording "SELECT SIGNATORY", with no visible ministerial signature or date.` },
    { type: 'paragraph', text: `That contrasts sharply with the earlier 2025 assessment.` },
    { type: 'paragraph', text: `The Bill-stage version was dated 13 February 2025 and carried a ministerial signature dated 21 February 2025.` },
    { type: 'paragraph', text: `The absence of a signature on the new published version does not prove it was never approved internally.` },
    { type: 'paragraph', text: `But it raises an obvious question about when the assessment was finalised and signed off.` },
    { type: 'paragraph', text: `For a document published five months after enactment, that is not a minor presentational detail.` },
    { type: 'heading', level: 2, text: `The benefits are not costed` },
    { type: 'paragraph', text: `The assessment says the measures are intended to protect victims, close gaps in the criminal law and improve public confidence.` },
    { type: 'paragraph', text: `Those may be substantial benefits.` },
    { type: 'paragraph', text: `But the government says it has not been possible to identify any monetised benefits.` },
    { type: 'paragraph', text: `That means the document contains a detailed monetary estimate of the costs but no financial value for the benefits.` },
    { type: 'paragraph', text: `Again, that does not mean the measures are poor value.` },
    { type: 'paragraph', text: `Putting a cash figure on preventing intimate-image abuse, sexual offending or other serious harm would be difficult and potentially artificial.` },
    { type: 'paragraph', text: `But it does mean the £208.9 million is largely a cost calculation rather than a conventional cost-benefit case.` },
    { type: 'paragraph', text: `The government is asking readers to accept that the social gains justify the expenditure without attempting to quantify those gains financially.` },
    { type: 'paragraph', text: `That may be reasonable.` },
    { type: 'paragraph', text: `It also makes parliamentary scrutiny of the assumptions behind the cost side more important.` },
    { type: 'heading', level: 2, text: `The Act changed substantially during its passage` },
    { type: 'paragraph', text: `The government did publish Bill-stage impact assessments before the Act was passed.` },
    { type: 'paragraph', text: `The GOV.UK collection shows the original impact-assessment page was created when the Bill was introduced in February 2025 and was updated as the legislation progressed, with further assessments covering individual measures added as late as December 2025, well after the criminal-law package itself had been costed.` },
    { type: 'paragraph', text: `So this is not a case where Parliament received no economic analysis at all.` },
    { type: 'paragraph', text: `The issue is narrower.` },
    { type: 'paragraph', text: `The final package Parliament enacted was different from the original Bill.` },
    { type: 'paragraph', text: `The newly published document is specifically marked "Stage: Enactment" and assesses the measures in the Act as passed.` },
    { type: 'paragraph', text: `That is the version that shows the £208.9 million cost.` },
    { type: 'paragraph', text: `And that is the version the public did not receive until September.` },
    { type: 'heading', level: 2, text: `Impact assessments are supposed to aid scrutiny before decisions are settled` },
    { type: 'paragraph', text: `The point of an impact assessment is not simply to create an archive after legislation becomes law.` },
    { type: 'paragraph', text: `It is supposed to expose likely costs, assumptions, risks and alternatives while decisions can still be challenged.` },
    { type: 'paragraph', text: `In this case, the final document says the criminal-law package will cost police, courts, legal aid, prisons and probation about £24.5 million a year.` },
    { type: 'paragraph', text: `It predicts thousands of additional recorded crimes and hundreds of extra prosecutions and convictions.` },
    { type: 'paragraph', text: `Those figures affect staffing, prison demand and court capacity.` },
    { type: 'paragraph', text: `They would have been relevant to MPs and peers deciding whether the final package was properly resourced.` },
    { type: 'paragraph', text: `Publishing them five months later reduces their usefulness as a tool of parliamentary scrutiny.` },
    { type: 'heading', level: 2, text: `The government should now answer one simple question` },
    { type: 'paragraph', text: `The key issue is not whether the offences themselves should exist.` },
    { type: 'paragraph', text: `Many address serious gaps in the criminal law.` },
    { type: 'paragraph', text: `The issue is when Parliament knew what the final package was expected to cost.` },
    { type: 'paragraph', text: `The government should publish the audit trail.` },
    { type: 'paragraph', text: `When was the £208.9 million estimate first produced? When was it approved? Was it shown to ministers before Royal Assent? Was it provided to Parliament in any unpublished form?` },
    { type: 'paragraph', text: `And why does the public version of the enactment-stage assessment carry no visible date or ministerial signature?` },
    { type: 'paragraph', text: `The Home Office and Ministry of Justice have now put the final costing into the public domain.` },
    { type: 'paragraph', text: `They have not yet explained why it arrived after the law.` },
  ],
  evidence: {
    recordsReviewed: [
      'GOV.UK, "Crime and Policing Act 2026: impact assessments," published 29 September 2026 — publication date, Royal Assent date (29 April 2026), collection listing the three enactment-stage assessments (criminal law, abortion, other measures)',
      'Home Office/Ministry of Justice, "Crime and Policing Act: criminal law measures economic impact assessment" (enactment stage) — £208.9m ten-year net present cost; £24.5m average annual cost; agency breakdown (£8.9m police, £15.0m HMPPS, £0.2m HMCTS, £0.4m Legal Aid Agency); 5,000 recorded crimes/400+ prosecutions/300+ convictions steady-state estimate; Measure 1H wording on under-16 penetrative offences; blank Date field; "SELECT SIGNATORY" placeholder; no monetised benefits identified',
      'Home Office/Ministry of Justice, "Crime and Policing Bill: criminal law measures impact assessment" (Bill stage, February 2025) — original £97.0m ten-year net present cost; £9.7m average annual cost; document dated 13 February 2025; ministerial signature dated 21 February 2025',
      'GOV.UK, "Crime and Policing Bill 2025: impact assessments" collection — criminal law measures assessment first published 25 February 2025 alongside Bill introduction; further measure-specific assessments (crossbows, bladed articles) added as late as 3 December 2025 as the Bill progressed',
    ],
    lastChecked: '30 September 2026',
  },
};

export default piece;
