import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'k3p9w7nx2d',
  kicker: 'Defence',
  headline: `96 Days After Saying Work Would Begin on the A38 and A46, Government Put Both at Risk to Fund Defence`,
  standfirst: `On 26 March, the government's Road Investment Strategy said work would begin on the A38 Derby Junctions and A46 Newark Bypass during the five-year road period. Ninety-six days later, the Defence Investment Plan funding document named both as candidates for cancellation. Neither has entered its main construction contract. No final decision has been taken.`,
  publishedAt: '2026-07-01',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `On 26 March, the government published its five-year investment plan for England's motorways and major A-roads.` },
    { type: 'paragraph', text: `The Road Investment Strategy committed more than £27 billion between 2026 and 2031. For the A38 Derby Junctions and the A46 Newark Bypass, it did not use the language of future development. It said: "Work will also begin in the Midlands on both the A38 Derby Junctions and A46 Newark Bypass, which will be completed in the next road period." Its investment map classified both under "Major Enhancements: Starting in RIS3."` },
    { type: 'paragraph', text: `Ninety-six days later, both were named as candidates for cancellation.` },
    { type: 'paragraph', text: `The government's Defence Investment Plan funding document, published on 30 June, says the Department for Transport will find up to £700 million from roads funding and consult on reductions to the same Road Investment Strategy. It names the A38 and A46 specifically, saying neither has entered its main construction contract and both are less advanced than other schemes. No final decision has been taken.` },
    { type: 'paragraph', text: `The money is being redirected towards defence. Keir Starmer announced an additional £15 billion of Ministry of Defence spending power between 2026/27 and 2029/30. The government has identified £10.3 billion of financing measures so far, including reductions to departmental capital budgets, transport and energy spending, asset sales and Treasury support. Another £4.7 billion is marked for funding at Budget 2026.` },
    { type: 'paragraph', text: `The road schemes were not simply aspirations on a map.` },
    { type: 'paragraph', text: `The A38 Derby Junctions scheme already had development consent. Its original 2021 approval was quashed by the High Court and sent back for redetermination; the Secretary of State re-approved the Development Consent Order in August 2023. A further legal challenge to that 2023 decision followed, and by March 2025 the outstanding legal issues had been resolved. National Highways confirmed on 6 August 2025 that funding for the scheme had been secured following the Spending Review.` },
    { type: 'paragraph', text: `The A46 Newark Bypass was also funded following the 2025 Spending Review. Its Development Consent Order was granted on 1 October 2025, giving National Highways permission for widening between Farndon roundabout and the A1, and a new dual-carriageway section between the A1 and Winthorpe roundabout.` },
    { type: 'paragraph', text: `By March this year, RIS3 had moved both into the category of schemes where work would begin during the current road period, rather than the pipeline of schemes being developed during RIS3 for construction in RIS4.` },
    { type: 'paragraph', text: `That is a stronger commitment than the phrase "schemes to be developed," which is how the Department for Transport's accompanying press release described the same projects. The release promised businesses and regions "long-term certainty" from the £27 billion programme and said the investment would give industry confidence to plan and invest.` },
    { type: 'paragraph', text: `The A38 project is intended to replace the Kingsway, Markeaton and Little Eaton roundabouts around Derby with grade-separated junctions, separating local and through traffic. The A46 scheme would dual the remaining single-carriageway section around Newark between Farndon and Winthorpe, improving the route towards the A1 and Humber ports.` },
    { type: 'paragraph', text: `Neither had entered its main construction contract by 30 June. The Defence Investment Plan document gives that as the reason both are candidates for savings: cancelling them would be less disruptive than halting schemes already under construction. The Department for Transport is also examining other, uncommitted roads funding, so the A38 and A46 are not necessarily the only schemes that will ultimately lose money. They are, however, the only individual road schemes named in the defence document for possible cancellation.` },
    { type: 'paragraph', text: `East Midlands Mayor Claire Ward said she was not told before the announcement. She said she learned of it while Starmer was delivering his Defence Investment Plan speech, and said: "I cannot understand why the only region being asked to lose £900m of investment into its roads is the East Midlands." She called the proposal unacceptable. Her £900 million figure is her own estimate of the investment represented by the two schemes, not the amount the Treasury expects to save by cancelling them; the government is seeking up to £700 million from roads funding overall, and has not said that cancelling the A38 and A46 specifically would produce that sum, or that Ward's figure would translate directly into cash for defence.` },
    { type: 'paragraph', text: `Lincoln MP and Foreign Office minister Hamish Falconer also objected. He described the A46 upgrade as well advanced, long awaited, good value for money and of strategic importance to Lincoln and the wider region, and said: "I will be seeking an urgent meeting with the incoming prime minister, incoming chancellor and incoming secretary of state for transport to discuss this decision and explore whether there is a credible route forward."` },
    { type: 'paragraph', text: `Starmer did not conceal the trade-off. He said the defence increase would be financed partly by reallocating capital budgets across government, and that some roads and energy projects which were important but not immediately vital would no longer go ahead as planned.` },
    { type: 'paragraph', text: `The £298 billion figure attached to the Defence Investment Plan is separate from the new spending. It represents the Ministry of Defence's total planned investment across the four years to 2029/30 under the plan; the newly announced increase within that is £15 billion.` },
    { type: 'paragraph', text: `In August 2025, National Highways said funding for both schemes had been confirmed. The A38 had development consent, with its legal challenges resolved by March 2025. The A46 received consent in October. On 26 March, the government's statutory Road Investment Strategy said work would begin on both during the five-year road period. On 30 June, it put both forward for possible cancellation to help finance defence.` },
    { type: 'paragraph', text: `The consultation will determine whether either survives.` },
  ],
  evidence: {
    recordsReviewed: [
      `Department for Transport, Road Investment Strategy 3: 2026 to 2031, 26 March 2026: states that work will begin on the A38 Derby Junctions and A46 Newark Bypass during RIS3, with completion in the next road period, and classifies both under "Major Enhancements: Starting in RIS3" in the investment map; independently verified against the print-edition PDF`,
      `Department for Transport and National Highways, Major renewal of ageing English roads delivered with £27 billion investment, 26 March 2026: describes the settlement as giving businesses and regions long-term certainty and lists the A38 and A46 among schemes being progressed during RIS3, using the weaker phrase "schemes to be developed"`,
      `HM Treasury and Ministry of Defence, Defence Investment Plan Funding Explainer, 30 June 2026: records the £15 billion additional defence package, £10.3 billion of identified financing, £4.7 billion for Budget 2026, and up to £700 million of roads savings; names the A38 and A46 as candidates for cancellation while stating no final decision has been taken; its financing table includes a separate "Further Department for Transport savings" line totalling £0.8 billion over four years, which the accompanying text does not fully itemise beyond the £700 million roads figure`,
      `Prime Minister's Office, Defence Investment Plan speech, 30 June 2026: records Starmer's statement that capital spending would be reallocated towards defence and that some road and energy schemes would no longer proceed as planned`,
      `Planning Inspectorate / Secretary of State for Transport, A38 Derby Junctions Development Consent Order decision letter, 17 August 2023, and Mair Bain v Secretary of State for Transport case record (Climate Litigation Database): recording the original 2021 consent being quashed by the High Court on 18 March 2021 and remade in 2023`,
      `National Highways, A38 Derby Junctions project page, 6 August 2025: confirms funding for the scheme was secured following the 2025 Spending Review`,
      `Planning Inspectorate, A46 Newark Bypass development consent decision announced, 1 October 2025: confirms development consent and describes the widening and new dual-carriageway works authorised`,
      `National Highways, A46 Newark Bypass project page: confirms funding was secured following the 2025 Spending Review, ahead of the October 2025 consent decision`,
      `TransportXtra, Labour mayor reacts angrily to proposals to scrap A38 and A46 projects, 1 July 2026: source for Claire Ward's quote and her £900 million estimate`,
      `BritBrief, Labour Minister and Reform MP Slam Cuts to Road Projects for Defence, 1 July 2026: source for Hamish Falconer's quote and his description of the A46 scheme`,
    ],
    lastChecked: '5 October 2026',
  },
};

export default piece;
