import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'k9m4qxw7n2',
  kicker: 'Asylum Accommodation',
  headline: `Home Office Plans 3,750 More Asylum Places Before It Has a Performance Regime for Existing Large Sites`,
  standfirst: `The Home Office is considering three former military sites capable of accommodating around 3,750 asylum seekers between them. Two could remain in use for at least ten years. It is planning that expansion while still developing the performance regime for the large asylum sites it already operates. Five months after promising revised KPIs by February 2026, border security minister Alex Norris told MPs in July that a dedicated framework for Wethersfield and Crowborough was still being developed.`,
  publishedAt: '2026-07-21',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `The Home Office is considering three former military sites capable of accommodating around 3,750 asylum seekers between them.` },
    { type: 'paragraph', text: `Two could remain in use for at least ten years.` },
    { type: 'paragraph', text: `The department has not said how the 3,750 places would be divided between MoD Bicester in Oxfordshire, MoD Barnham in Suffolk and Linton-on-Ouse in North Yorkshire.` },
    { type: 'paragraph', text: `It is planning that expansion while still developing the performance regime for the large asylum sites it already operates.` },
    { type: 'paragraph', text: `In January, after criticism from the Home Affairs Committee, the Home Office said revised performance measures for asylum accommodation would be finalised by February 2026.` },
    { type: 'paragraph', text: `They were not.` },
    { type: 'paragraph', text: `In a letter to MPs on 3 July, border security minister Alex Norris said there was still no dedicated Key Performance Indicator regime for either Wethersfield or Crowborough and that one was still being developed. The Home Office said the eventual system would also apply to future large sites.` },
    { type: 'paragraph', text: `The committee described the position more plainly on 15 July: the government was proceeding with three proposed large sites without a performance framework in place to hold their operators to account.` },
    { type: 'paragraph', text: `The expansion was announced on 29 June.` },
    { type: 'paragraph', text: `Norris told Parliament that Barnham, Bicester and Linton-on-Ouse could eventually provide accommodation for around 3,750 people, subject to feasibility work, planning permission and other approvals. No final decision has yet been made on any of the three.` },
    { type: 'paragraph', text: `The individual Home Office factsheets are less informative about capacity.` },
    { type: 'paragraph', text: `Each contains a section headed with the question of how many people would be accommodated at the site.` },
    { type: 'paragraph', text: `For Bicester, the answer says the Home Office "does not give a live commentary" on the number of asylum seekers housed at accommodation sites and would increase occupancy gradually. Barnham and Linton carry effectively the same response.` },
    { type: 'paragraph', text: `There are no asylum seekers living at any of the three proposed sites.` },
    { type: 'paragraph', text: `The department is therefore declining to give planned site capacities using wording normally associated with changing occupancy at sites already in operation.` },
    { type: 'paragraph', text: `It has nevertheless been willing to give the combined planning figure of around 3,750 to Parliament.` },
    { type: 'paragraph', text: `The factsheets are clearer about how long the sites could remain.` },
    { type: 'paragraph', text: `Bicester would be used for a minimum of ten years. Barnham would also be used for a minimum of ten years. Linton-on-Ouse would operate for at least three. All three are intended for single adult male asylum seekers aged between 18 and 65.` },
    { type: 'paragraph', text: `The Home Office describes former military accommodation as part of its effort to stop using asylum hotels.` },
    { type: 'paragraph', text: `Hotel use has fallen substantially. The department said in June that fewer than 170 asylum hotels remained, down from around 400 at the peak, and that the number of asylum seekers in hotels had fallen from 56,000 in 2023 to around 21,000.` },
    { type: 'paragraph', text: `Large sites provide the Home Office with more predictable blocks of accommodation than finding thousands of individual hotel or rented places. That is a genuine operational advantage.` },
    { type: 'paragraph', text: `The record of the existing large-site programme is less reassuring.` },
    { type: 'paragraph', text: `The Home Affairs Committee concluded last October that the Home Office had repeatedly rushed the development of large sites, cut corners and spent more than expected. It said Wethersfield had improved significantly after opening but that lessons which should have been learned from earlier accommodation at Napier Barracks were instead being worked out after residents had arrived.` },
    { type: 'paragraph', text: `The committee also found that Wethersfield still had no appropriate performance-management regime.` },
    { type: 'paragraph', text: `This was not a new problem.` },
    { type: 'paragraph', text: `The National Audit Office had reported that the Home Office was working on Wethersfield performance measures in January 2024. By October 2025 they had still not been agreed. The government then told MPs that revised KPIs would be finalised by February 2026.` },
    { type: 'paragraph', text: `Five months after that deadline, Norris told the committee they remained under development.` },
    { type: 'paragraph', text: `The absence of dedicated KPIs does not mean the Home Office conducts no oversight.` },
    { type: 'paragraph', text: `Norris said officials maintain an on-site presence, review incidents, examine records and work directly with providers. Existing asylum accommodation contracts also contain broader performance measures.` },
    { type: 'paragraph', text: `But the department itself accepts that those measures are not suitable for large sites. Its July letter says a dedicated framework is still being negotiated.` },
    { type: 'paragraph', text: `The absence is more consequential given that the government is proposing sites designed to operate for years rather than months.` },
    { type: 'paragraph', text: `Bicester and Barnham could still be accommodating asylum seekers in the mid-2030s if they open and remain for the minimum period stated by the Home Office.` },
    { type: 'paragraph', text: `The department has also not yet published the full costs of the proposed sites. Asked about Bicester, Norris told Parliament that costs would be reported through the Home Office annual report and accounts "in the usual way". Internal site assessments and value-for-money assessments are not routinely published.` },
    { type: 'paragraph', text: `Wethersfield shows why headline running costs need careful treatment.` },
    { type: 'paragraph', text: `The Home Office told the Home Affairs Committee that accommodating somebody there cost about £132 a night, compared with £144.98 in a hotel.` },
    { type: 'paragraph', text: `But the committee found that the Wethersfield comparison excluded £105 million of acquisition, lease and set-up costs.` },
    { type: 'paragraph', text: `The committee did not conclude that large sites could never work.` },
    { type: 'paragraph', text: `After visiting Wethersfield, MPs reported improvements including better Home Office oversight, stronger working with local services and the introduction of on-site asylum interviews. Some of the men they met were satisfied with the accommodation, while others were deeply unhappy with it.` },
    { type: 'paragraph', text: `Its conclusion was that large sites required careful preparation, proper services, close local working and meaningful performance monitoring.` },
    { type: 'paragraph', text: `Health evidence from Wethersfield also provides a warning about the people who may be placed in such accommodation.` },
    { type: 'paragraph', text: `Doctors of the World and Médecins Sans Frontières treated 301 Wethersfield residents through an external medical service. Among those assessed using a psychological-distress measure, 62 per cent presented with severe mental distress and about 30 per cent reported suicidal thoughts.` },
    { type: 'paragraph', text: `Those figures cannot be treated as prevalence rates for the whole camp because the sample consisted of people who had sought medical help. They do show the level of need encountered among patients using the service.` },
    { type: 'paragraph', text: `The government is now increasing Wethersfield's normal operating capacity from 800 to 1,245 and intends to continue using it beyond its existing April 2027 planning period.` },
    { type: 'paragraph', text: `Essex County Council said 766 people were living there when the expansion was announced in June. It has raised concerns about the effect on police, health services and nearby towns, although some of its public claims about crime and antisocial behaviour have not been accompanied by incident totals which would allow them to be tested independently.` },
    { type: 'paragraph', text: `Crowborough provides a less alarming comparison.` },
    { type: 'paragraph', text: `The East Sussex site began receiving asylum seekers in January and has a maximum capacity of 540. Wealden District Council said in June that it was close to full occupancy.` },
    { type: 'paragraph', text: `The council also reports continuing protests around the site, but the evidence available so far does not establish that its opening produced the surge in local crime predicted by some opponents.` },
    { type: 'paragraph', text: `Linton-on-Ouse has a more direct precedent.` },
    { type: 'paragraph', text: `The previous government proposed using the former RAF base for asylum accommodation in 2022. The plan did not proceed.` },
    { type: 'paragraph', text: `The current Home Office says one factor was the Ministry of Defence withdrawing availability of the site. It says this time it will apply lessons from the earlier assessment, strengthen engagement with local partners and ensure infrastructure and services are considered before any final decision.` },
    { type: 'paragraph', text: `That is a narrower account than saying the 2022 proposal was simply defeated by local opposition or threatened litigation. Both formed part of the political history, but the Home Office now identifies the withdrawal of MoD availability as part of why the scheme did not proceed.` },
    { type: 'paragraph', text: `The department has also provided more detail about consultation than the original draft suggested.` },
    { type: 'paragraph', text: `The National Police Coordination Centre was informed about the latest large-site announcement on 17 June and relevant police forces on 18 June. MPs were contacted on 24 and 25 June, while council chief executives and leaders were approached on 25 June and around the date of the announcement.` },
    { type: 'paragraph', text: `That was advance notice measured in days, not a long process of local consultation. But it means claims that councils or police were given no warning need to be made site by site rather than applied to all three proposals.` },
    { type: 'paragraph', text: `Bicester illustrates another timing problem in the original account.` },
    { type: 'paragraph', text: `As of 21 July, the Home Office had not yet submitted the Urgent Crown Development application subsequently used for the site. Parliament had been told in June that the planning route for Bicester and Barnham had not yet been finally determined.` },
    { type: 'paragraph', text: `The Bicester Urgent Crown Development application was published later, in September. It should not be described as having already happened in an article dated 21 July.` },
    { type: 'paragraph', text: `The Home Office says no final decision on Bicester, Barnham or Linton will be taken until feasibility, planning and other approvals have been completed.` },
    { type: 'paragraph', text: `That is a fair basis for not pretending every detail is settled.` },
    { type: 'paragraph', text: `It does not explain every omission.` },
    { type: 'paragraph', text: `The government has publicly estimated that the three sites could provide around 3,750 places. Its own factsheets say Bicester and Barnham could operate for at least ten years and Linton for at least three.` },
    { type: 'paragraph', text: `They still do not tell residents how that 3,750 capacity would be divided between the three communities.` },
    { type: 'paragraph', text: `And before those sites are added to the system, the dedicated performance regime promised for the large sites already operating is still unfinished.` },
  ],
  evidence: {
    recordsReviewed: [
      `Home Office, written ministerial statement, "Asylum accommodation", 29 June 2026: the proposed use of Bicester, Barnham and Linton-on-Ouse, the combined capacity of around 3,750, the requirement for further feasibility and planning work, and the government's hotel-closure policy`,
      `House of Commons Hansard, "Asylum Accommodation", 29 June 2026: Alex Norris's announcement of the three proposed sites and his statement that planning routes and final decisions had not yet been settled`,
      `Home Office, MoD Bicester, MoD Barnham and MoD Linton-on-Ouse factsheets, July 2026: the minimum ten-year proposed use at Bicester and Barnham, minimum three-year use at Linton, intended single-adult-male population and the Home Office's refusal to provide individual capacity figures using its "live commentary" formulation`,
      `Alex Norris MP to the Home Affairs Committee, 3 July 2026: the absence of a dedicated large-site KPI regime at Wethersfield and Crowborough and the Home Office's statement that a framework was still being developed for existing and future large sites`,
      `Home Affairs Committee, publication of correspondence on large asylum sites, 15 July 2026: the committee's finding that the government was progressing Bicester, Barnham and Linton without a dedicated performance framework for large sites`,
      `Home Affairs Committee, The Home Office's management of asylum accommodation, 27 October 2025: findings on Wethersfield, large-site performance monitoring, the £132 nightly running-cost comparison, exclusion of £105 million of acquisition, lease and set-up expenditure, and the committee's assessment of lessons from previous large-site projects`,
      `Home Office response to the Home Affairs Committee, 22 January 2026: the department's commitment to finalise revised asylum-accommodation KPIs by February 2026`,
      `Essex County Council and Braintree District Council, Wethersfield updates, June 2026: the 766 occupancy figure at the time of the announced expansion, proposed operating capacity of 1,245 and plans to continue the site's use beyond April 2027`,
      `Doctors of the World UK and Médecins Sans Frontières, A Lonely Place: How Wethersfield is harming asylum seekers, May 2025: the clinical findings on severe mental distress and suicidal ideation among patients seen by the charities, with the limitation that the patients were not a representative sample of all Wethersfield residents`,
      `Wealden District Council and Home Office, Crowborough updates: the January 2026 opening, maximum capacity of 540 and the council's June report that the site was close to full occupancy`,
      `Alex Norris MP to the Home Affairs Committee, 7 July 2026: the government's explanation of the failed 2022 Linton-on-Ouse proposal, its latest engagement timetable with police, MPs and councils, and its stated intention to apply lessons from earlier large-site projects`,
    ],
    lastChecked: '4 October 2026',
  },
};

export default piece;
