import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'kn4r9mxw7q',
  kicker: 'Online Safety',
  headline: `Government Wants Every Phone to Block Nude Images for Under-18s, but Has Not Published Accuracy Standards`,
  standfirst: `The government intends to make it impossible for under-18s to take, view or send nude images by requiring operating systems and apps to detect nudity on-device. Technical standards for accuracy, an acceptable false-positive rate and the age-verification architecture have not yet been published. The legislation does not yet exist.`,
  publishedAt: '2026-09-09',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `The government wants smartphones and apps to make it impossible for under-18s to take, view or send nude images.` },
    { type: 'paragraph', text: `But ministers have not yet published the technical standards that would determine whether the system works, how often legitimate images could be wrongly blocked, or exactly how adults will prove their age to switch the restrictions off.` },
    { type: 'paragraph', text: `The proposal goes well beyond removing illegal material from social media.` },
    { type: 'paragraph', text: `It would require operating systems and potentially individual apps to identify nudity before an image is viewed, captured or shared.` },
    { type: 'paragraph', text: `The government says the technology can operate privately on the device.` },
    { type: 'paragraph', text: `That avoids the most obvious privacy concern of photographs being routinely uploaded to government or technology companies for inspection.` },
    { type: 'paragraph', text: `But it creates another question.` },
    { type: 'paragraph', text: `A machine-learning system inside the phone would still be deciding whether a private image can be taken, seen or transmitted.` },
    { type: 'paragraph', text: `The government has not yet said what error rate would be acceptable when that decision is wrong.` },
    { type: 'heading', level: 2, text: `Existing technology does not currently impose the prohibition ministers want` },
    { type: 'paragraph', text: `Apple and Google already operate nudity-detection technology.` },
    { type: 'paragraph', text: `Apple's Communication Safety system uses on-device machine learning to identify images that may contain nudity. Sensitive images can be blurred and users can receive warnings before viewing or sending them. Apple says it does not receive any indication that nudity was detected and has no access to the photos or videos. The one exception is if a child chooses to report a sender, at which point the flagged content is sent to Apple for review.` },
    { type: 'paragraph', text: `Google uses similar on-device technology through Android SafetyCore, which classifies content locally and does not send classified content, results, or identifiable data back to Google's servers. It powers the sensitive-content warnings in Google Messages.` },
    { type: 'paragraph', text: `That demonstrates that nudity detection can operate without automatically sending private photographs elsewhere.` },
    { type: 'paragraph', text: `But the government's proposal is substantially more restrictive.` },
    { type: 'paragraph', text: `Existing systems generally warn users or place additional controls around sensitive content.` },
    { type: 'paragraph', text: `Ministers want under-18s prevented from taking, viewing or sending nude imagery altogether, including through the phone camera and third-party applications.` },
    { type: 'paragraph', text: `That turns safeguarding software into a device-level prohibition.` },
    { type: 'heading', level: 2, text: `Every image may have to pass through a classifier` },
    { type: 'paragraph', text: `Ministers have previously said they want comprehensive nudity detection to operate at operating-system level.` },
    { type: 'paragraph', text: `In practice, that means software must assess images at some point as they are taken, received, displayed or transmitted.` },
    { type: 'paragraph', text: `Government says this can happen locally, pointing to the existing Apple and Google technologies as proof that this assessment can be done on the device, without sending the image to government, law enforcement or the technology provider.` },
    { type: 'paragraph', text: `That is an important safeguard.` },
    { type: 'paragraph', text: `It does not remove the problem of accuracy.` },
    { type: 'paragraph', text: `A classifier deciding whether an image contains nudity still has to distinguish between sexual material and other images containing skin.` },
    { type: 'paragraph', text: `Medical photographs, breastfeeding, art, family photographs, changing-room images and sexual-health material can all create edge cases.` },
    { type: 'paragraph', text: `Under the government's proposed approach, that classification may determine whether the image can be accessed at all.` },
    { type: 'heading', level: 2, text: `Ministers have not published an acceptable false-positive rate` },
    { type: 'paragraph', text: `Conservative MP Wendy Morton asked the government in June what technical standards it would require, and whether it would publish an independent assessment of accuracy and false-positive rates.` },
    { type: 'paragraph', text: `Responding for the Home Office, Natalie Fleet said the government's period of engagement with industry would "focus on further refining technical solutions to prevent nude imagery from being taken, shared or viewed", which would include "consideration of accuracy thresholds."` },
    { type: 'paragraph', text: `That is not a commitment to publish an independent assessment, or to set a specific false-positive standard.` },
    { type: 'paragraph', text: `That is one of the largest gaps in the proposal.` },
    { type: 'paragraph', text: `A warning system can tolerate a degree of error because the user can often choose to continue.` },
    { type: 'paragraph', text: `A system designed to make an action impossible cannot.` },
    { type: 'paragraph', text: `If the software wrongly identifies a legitimate medical or family image as nude content, an under-18 user may simply be prevented from taking or viewing it.` },
    { type: 'paragraph', text: `The government has not yet said how such errors will be appealed, corrected or overridden.` },
    { type: 'heading', level: 2, text: `Age verification becomes part of the operating system` },
    { type: 'paragraph', text: `The proposal also depends on the device knowing whether its user is under or over 18.` },
    { type: 'paragraph', text: `Government says adults should be able to access nude imagery only after robust age assurance: "The only way for any user to take, view or send nude images should be for an adult to verify their age through a robust age-assurance process."` },
    { type: 'paragraph', text: `That raises another set of unanswered questions.` },
    { type: 'paragraph', text: `Who performs the check?` },
    { type: 'paragraph', text: `The phone manufacturer?` },
    { type: 'paragraph', text: `Apple or Google?` },
    { type: 'paragraph', text: `The mobile network?` },
    { type: 'paragraph', text: `A third-party age-verification provider?` },
    { type: 'paragraph', text: `And what information must the adult surrender to prove they are over 18?` },
    { type: 'paragraph', text: `The Information Commissioner's Office said in May that it has not yet seen "new, viable and privacy friendly" age-assurance solutions come forward from industry.` },
    { type: 'paragraph', text: `The government has not yet published the final architecture for this proposal.` },
    { type: 'paragraph', text: `The policy therefore depends on two systems working correctly at the same time.` },
    { type: 'paragraph', text: `One must decide what counts as nudity.` },
    { type: 'paragraph', text: `The other must decide whether the user is a child.` },
    { type: 'heading', level: 2, text: `"Impossible" is a very high bar` },
    { type: 'paragraph', text: `The government's language is unusually absolute.` },
    { type: 'paragraph', text: `Its stated objective is to make it impossible for under-18s to take, view or send nude images.` },
    { type: 'paragraph', text: `But the government has not yet explained how that promise will survive older phones, unsupported operating systems, modified devices, sideloaded apps, cloud services or other workarounds.` },
    { type: 'paragraph', text: `Wendy Morton also asked about several of those specific routes — VPNs, sideloaded apps, encrypted messaging, cloud storage, web browsers and older devices — and whether any guidance would be "resilient to circumvention."` },
    { type: 'paragraph', text: `The government's answer said it was "engaging with industry, with a focus on the primary operating system providers" and would "continue to consider potential circumventions." It did not explain how each named route would actually be prevented.` },
    { type: 'paragraph', text: `The September announcement itself acknowledges that the technical problem is complex and that further work is needed before legislation is introduced: "Given the complexity of this issue, it is vital that we take the time to get this legislation right."` },
    { type: 'paragraph', text: `That is more cautious than the promise that the activity will become impossible.` },
    { type: 'heading', level: 2, text: `The proposal does not necessarily require breaking encryption` },
    { type: 'paragraph', text: `One criticism should be avoided unless the legislation changes substantially.` },
    { type: 'paragraph', text: `On-device nudity detection does not automatically require an encrypted messaging service to be broken.` },
    { type: 'paragraph', text: `An image can be classified on the device before it is encrypted or after it is decrypted.` },
    { type: 'paragraph', text: `Apple's existing system demonstrates that local analysis can operate alongside private messaging.` },
    { type: 'paragraph', text: `The more precise issue is different.` },
    { type: 'paragraph', text: `The proposed system would give operating-system software greater control over what users are permitted to capture and transmit, even where the underlying message remains encrypted.` },
    { type: 'paragraph', text: `That is a significant policy choice in its own right.` },
    { type: 'heading', level: 2, text: `The harm the government is targeting is real` },
    { type: 'paragraph', text: `The proposal is being driven by a genuine child-safety problem.` },
    { type: 'paragraph', text: `The Internet Watch Foundation says it actioned 266,397 reports containing at least one self-generated child sexual abuse image or video in 2025 — 85 per cent of all the reports it actioned that year.` },
    { type: 'paragraph', text: `The IWF also reports that sexually coerced extortion is heavily concentrated among teenage boys: in 2025, 14-to-17-year-old boys accounted for 98 per cent of the older-teen sextortion reports it analysed.` },
    { type: 'paragraph', text: `The public-interest issue is therefore not whether the government has identified a serious problem.` },
    { type: 'paragraph', text: `It has.` },
    { type: 'paragraph', text: `The test is whether the intervention is technically reliable and proportionate.` },
    { type: 'heading', level: 2, text: `Legislation follows a failed voluntary push` },
    { type: 'paragraph', text: `On 8 June, the government gave technology companies three months to strengthen protections voluntarily, saying: "If companies do not act within 3 months, the government will bring forward legislation to force them to activate the technology."` },
    { type: 'paragraph', text: `On 9 September, ministers announced that legislation was now being prepared.` },
    { type: 'paragraph', text: `Government said Apple and Google had made "progress, marking a start in our efforts to tackle online child sexual exploitation and abuse," but that this did "not meet the scale of the government's ambition."` },
    { type: 'paragraph', text: `What it has not published is a detailed account of what the companies failed to do.` },
    { type: 'paragraph', text: `There is no public scorecard showing which safeguards were requested, which were implemented and which remained outstanding.` },
    { type: 'paragraph', text: `That makes it difficult to judge why legislation became necessary after the three-month period.` },
    { type: 'heading', level: 2, text: `Apps may face separate obligations` },
    { type: 'paragraph', text: `The proposal could eventually operate at more than one layer.` },
    { type: 'paragraph', text: `Government says it is exploring legislation that could require apps used by children "to prevent them from accessing or sharing nudity, ensuring the whole ecosystem changes" — in addition to controls imposed through the operating system.` },
    { type: 'paragraph', text: `That could mean the same image being assessed by the phone, the app and the online service.` },
    { type: 'paragraph', text: `The government has not yet published how those overlapping systems would interact or which provider would be responsible when classifications differ.` },
    { type: 'paragraph', text: `Again, those details matter more than the headline.` },
    { type: 'heading', level: 2, text: `Nothing has yet been made impossible` },
    { type: 'paragraph', text: `The most important qualification is that the legislation does not yet exist.` },
    { type: 'paragraph', text: `The government says it intends to prepare legislation and introduce it as soon as possible.` },
    { type: 'paragraph', text: `It has also left the door open to reconsidering legislation altogether: "If companies implement solutions themselves, we will reassess whether this is necessary."` },
    { type: 'paragraph', text: `So claims that Britain has already stopped under-18s taking or sending nude images would be wrong.` },
    { type: 'paragraph', text: `What the government has announced is an intention.` },
    { type: 'paragraph', text: `The difficult engineering, privacy and enforcement questions are still being worked through.` },
    { type: 'paragraph', text: `The proposal may ultimately provide a powerful protection against grooming, sextortion and the spread of intimate images involving children.` },
    { type: 'paragraph', text: `But the government has announced the outcome before publishing the technical standard capable of delivering it.` },
    { type: 'paragraph', text: `Until it explains how accurate the system must be, how adults will prove their age, how legitimate images will be handled and how the rules will survive obvious workarounds, the promise that nude images will become "impossible" for under-18s remains exactly that.` },
    { type: 'paragraph', text: `A promise.` },
  ],
  evidence: {
    recordsReviewed: [
      'GOV.UK, 9 September 2026: "UK to have world\'s strongest online child safety laws as government prepares legislation on nude images" — OS/app requirements, age-assurance language, Apple/Google assessment, reassessment clause',
      'GOV.UK, 8 June 2026: "New plans to stop children taking, sharing or viewing nude images" — three-month voluntary compliance deadline',
      'UK Parliament written questions answered 29 June 2026 (10622 and 10623), asked by Wendy Morton MP, answered by Natalie Fleet MP — no commitment to publish accuracy/false-positive standard; non-specific answer on VPN/sideloading/encryption circumvention routes',
      'Apple, Communication Safety documentation — on-device detection, no server upload except reporter-triggered review',
      'Google, SafetyCore documentation — local classification, no classified content or results sent to Google servers',
      'Internet Watch Foundation, 2025 Annual Data & Insights Report — 266,397 self-generated-content reports (85% of all); 98% of older-teen sextortion reports involving boys aged 14–17',
      'Information Commissioner\'s Office, statement on age assurance, 21 May 2026 — no "new, viable and privacy friendly" solutions seen from industry',
    ],
    lastChecked: '30 September 2026',
  },
};

export default piece;
