import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'kv4n9mxw7r',
  kicker: 'Social Care',
  headline: `Government Plans £15bn-a-Year Pension Saving Before Full Cost of National Care Service Is Known`,
  standfirst: `The government will change the State Pension triple lock from April 2030, saving around £15 billion a year by the end of the 2030s in cash terms. Part of those savings will fund a new National Care Service offering free personal care. The full design and cost of the service will not be known until Baroness Casey's commission reports in summer 2027, and the service will not launch until the next Parliament.`,
  publishedAt: '2026-09-29',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `The government plans to change the State Pension triple lock from 2030 and use part of the resulting savings to help fund a new National Care Service.` },
    { type: 'paragraph', text: `By the end of the 2030s, the pension change is expected to save around £15 billion a year in cash terms compared with keeping the current triple lock unchanged.` },
    { type: 'paragraph', text: `The problem is that the government has not yet settled the full design or cost of the care service those savings are meant to support.` },
    { type: 'paragraph', text: `Baroness Casey's commission on adult social care is not due to report until summer 2027. The National Care Service is planned for the next Parliament and will be introduced in stages.` },
    { type: 'paragraph', text: `That means ministers have a clearer idea of how much they want to save from future pension spending than they do of the final cost of the service receiving the money.` },
    { type: 'paragraph', text: `The government says the National Care Service will be fully funded and will not rely on borrowing.` },
    { type: 'paragraph', text: `For now, that promise rests on a system that has not yet been fully designed.` },
    { type: 'heading', level: 2, text: `The triple lock changes in 2030, not before` },
    { type: 'paragraph', text: `The triple lock currently raises the State Pension each year by the highest of earnings growth, inflation or 2.5 per cent.` },
    { type: 'paragraph', text: `That formula stays in place until April 2030.` },
    { type: 'paragraph', text: `From then, the government says pensions will continue to rise by at least inflation or 2.5 per cent, with further increases where necessary to stop pensions falling too far behind earnings, so that over time the State Pension is still expected to track average earnings.` },
    { type: 'paragraph', text: `Nobody's State Pension is being cut in cash terms.` },
    { type: 'paragraph', text: `But future pensions will be lower than they would have been if the existing triple lock had continued.` },
    { type: 'paragraph', text: `DWP estimates the difference will be worth around £15 billion a year by 2039/40 and around £50 billion a year by 2049/50 in nominal terms.` },
    { type: 'paragraph', text: `In today's prices, the estimated savings are around £11 billion and £30 billion respectively.` },
    { type: 'paragraph', text: `That is not an accounting technicality.` },
    { type: 'paragraph', text: `It is money future pensioners would otherwise have received under the present formula.` },
    { type: 'heading', level: 2, text: `Free personal care is not the same as a free care home` },
    { type: 'paragraph', text: `The government intends to redirect part of that spending into social care.` },
    { type: 'paragraph', text: `There is a clear argument for doing so.` },
    { type: 'paragraph', text: `England's care system leaves many people facing substantial costs, while councils spend heavily on adult social care and families often have to navigate a complicated means-tested system.` },
    { type: 'paragraph', text: `But the phrase "free social care" would go too far.` },
    { type: 'paragraph', text: `The proposed National Care Service is intended to provide free personal care, described by the government as help with things like "eating, bathing and using the toilet."` },
    { type: 'paragraph', text: `It will not automatically make care homes free.` },
    { type: 'paragraph', text: `Accommodation, food and other living costs, what the government calls "bed and board," would remain outside the promise, subject to existing means-tested contributions.` },
    { type: 'paragraph', text: `That distinction matters.` },
    { type: 'paragraph', text: `A person entering residential care could receive free personal care but still face a large bill for the room and other charges.` },
    { type: 'paragraph', text: `The government says around one in seven older adults can currently face lifetime care costs above £100,000.` },
    { type: 'paragraph', text: `How much of those bills would actually disappear under the new system is not yet clear.` },
    { type: 'paragraph', text: `That will depend on the final design.` },
    { type: 'heading', level: 2, text: `The funding sequence is the wrong way round` },
    { type: 'paragraph', text: `Normally, a government would design a service, cost it and then decide how to pay for it.` },
    { type: 'paragraph', text: `Here, one of the main funding sources is already being set out while the final service is still being developed.` },
    { type: 'paragraph', text: `That creates a simple accountability problem.` },
    { type: 'paragraph', text: `If the care service costs less than expected, what happens to the remaining pension savings?` },
    { type: 'paragraph', text: `If it costs more, where does the extra money come from?` },
    { type: 'paragraph', text: `And how much of the money saved by changing the triple lock will actually be transferred into care rather than absorbed elsewhere in public spending?` },
    { type: 'paragraph', text: `Those answers are not yet available.` },
    { type: 'heading', level: 2, text: `Some will lose from the pension change and never use the care service` },
    { type: 'paragraph', text: `There is also a wider distributional question.` },
    { type: 'paragraph', text: `Future pensioners will receive less than they would have under the current triple lock.` },
    { type: 'paragraph', text: `In return, people who need personal care are promised a service free at the point of use.` },
    { type: 'paragraph', text: `Some people will experience both sides of that change.` },
    { type: 'paragraph', text: `They may receive a slightly lower pension than under the old formula and later benefit from free personal care.` },
    { type: 'paragraph', text: `Others may lose from the pension change and never use the care service.` },
    { type: 'paragraph', text: `That does not make the policy unfair by definition.` },
    { type: 'paragraph', text: `It does mean the government is making a significant choice about how money for older people is distributed.` },
    { type: 'paragraph', text: `The DWP modelling suggests the change does not automatically push pensioners into poverty.` },
    { type: 'paragraph', text: `Its own projections show relative pensioner poverty after housing costs falling from around 14 per cent in 2024/25 to around 8 per cent in 2049/50, even under the revised, less generous uprating system.` },
    { type: 'paragraph', text: `That is important context.` },
    { type: 'paragraph', text: `This is not a cash cut to existing pensions.` },
    { type: 'paragraph', text: `It is a decision to make future pension spending grow more slowly than it would under the current triple lock.` },
    { type: 'heading', level: 2, text: `The savings are projected to reach £50 billion a year by 2050` },
    { type: 'paragraph', text: `The difference is expected to become very large.` },
    { type: 'paragraph', text: `By 2049/50, the government estimates the saving at around £50 billion a year in cash terms.` },
    { type: 'paragraph', text: `That is why the link to social care deserves close scrutiny.` },
    { type: 'paragraph', text: `The National Care Service could become one of the biggest changes to the welfare state in decades.` },
    { type: 'paragraph', text: `It could also become one of the largest shifts in spending between different groups of older people.` },
    { type: 'paragraph', text: `For now, the government has given much more detail about the money it expects not to spend on pensions than about the service that money is supposed to build.` },
    { type: 'heading', level: 2, text: `The final test` },
    { type: 'paragraph', text: `How much was actually saved from the State Pension?` },
    { type: 'paragraph', text: `How much of that went into social care?` },
    { type: 'paragraph', text: `How many people received free personal care?` },
    { type: 'paragraph', text: `And after all of that, how much were families still paying themselves?` },
    { type: 'paragraph', text: `Until those figures exist, the promise that the new care service is "fully funded" remains a forecast rather than a result.` },
  ],
  evidence: {
    recordsReviewed: [
      'GOV.UK, 29 September 2026: "Prime Minister Andy Burnham sets out plans for a new National Care Service" — NCS proposal (free personal care based on need, introduced in phases, "fully funded – and not through borrowing"); personal-care examples ("eating, bathing and using the toilet"); exclusion of "bed and board"; triple lock reform wording and April 2030 start date; "one in seven" older adults facing lifetime costs above £100,000; Baroness Casey commission summer 2027 reporting date',
      'DWP, "State Pension uprating" analysis, 2026 — projected savings from adjusted triple lock: £15bn (2039/40) and £50bn (2049/50) nominal; £11bn and £30bn respectively in today\'s prices; current and adjusted uprating formulas; relative pensioner poverty after housing costs projected to fall from around 14% in 2024/25 to around 8% in 2049/50 under revised system',
    ],
    lastChecked: '30 September 2026',
  },
};

export default piece;
