import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'kxlkhj1jgj',
  kicker: 'Political Standards',
  headline: `Ten Westminster Controversies, and What Was Actually Proved`,
  standfirst: `A minister resigning over a breach of the Ministerial Code is not the same thing as an MP being suspended by their party. A parliamentary standards finding is not the same thing as an allegation. A political U-turn is not misconduct at all. Across ten of the most prominent political controversies of the current Parliament, the record ranges from established breaches to live investigations, internal party discipline and arguments about hypocrisy in which nobody has been found to have broken any rule.`,
  publishedAt: '2026-06-08',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `A minister resigning over a breach of the Ministerial Code is not the same thing as an MP being suspended by their party. A parliamentary standards finding is not the same thing as an allegation. A political U-turn is not misconduct at all.` },
    { type: 'paragraph', text: `Those distinctions have become blurred in Westminster, where scandals often travel much faster than the findings that eventually resolve them.` },
    { type: 'paragraph', text: `Across ten of the most prominent political controversies of the current Parliament, the record ranges from established breaches of parliamentary rules to live investigations, internal party discipline and arguments about hypocrisy in which nobody has been found to have broken any rule.` },
    { type: 'paragraph', text: `Some cases became more serious after investigation. Others became less so.` },
    { type: 'paragraph', text: `Nigel Farage has one established parliamentary standards case against him and another investigation that remains open.` },
    { type: 'paragraph', text: `On 20 January 2026, Parliamentary Commissioner for Standards Daniel Greenberg published his decision that Farage had breached Rule 5 of the MPs' Code of Conduct 17 times by registering financial interests after the 28-day deadline.` },
    { type: 'paragraph', text: `The late registrations were worth about £384,065 in total, but describing all of that sum as "outside earnings" is wrong. The commissioner's schedule includes both earnings and registrable benefits, including travel and accommodation. The entries were between three and 120 days late.` },
    { type: 'paragraph', text: `The Commissioner nevertheless decided against referring Farage to the Committee on Standards. He accepted that the failures were inadvertent and resulted from staffing and administrative problems, while warning that MPs with extensive outside interests were responsible for ensuring those interests were properly tracked and registered. Farage accepted responsibility, apologised and the breaches were dealt with through the rectification procedure.` },
    { type: 'paragraph', text: `A separate standards investigation opened on 13 May 2026 over an alleged failure to register an interest. That investigation concerns the £5 million provided by Christopher Harborne which Farage says was intended to meet security costs. As of 8 June, no finding had been made. Parliament does not publish further details while such an investigation is under way.` },
    { type: 'paragraph', text: `The original draft also described Farage as being under Essex Police and Electoral Commission investigations over spending in Clacton during the 2024 election.` },
    { type: 'paragraph', text: `He was not.` },
    { type: 'paragraph', text: `Essex Police said in December 2025 that it could not open an investigation because the statutory time limit for prosecution had expired. The Electoral Commission separately decided not to investigate after saying it had identified no spending that should have been declared but was not.` },
    { type: 'paragraph', text: `The unresolved case is therefore the Harborne registration inquiry, not three simultaneous investigations.` },
    { type: 'paragraph', text: `Angela Rayner's case produced two findings which need to be reported together.` },
    { type: 'paragraph', text: `Sir Laurie Magnus, the Independent Adviser on Ministerial Standards, concluded in September 2025 that Rayner had underpaid approximately £40,000 of stamp duty on a property in Hove and had breached the Ministerial Code.` },
    { type: 'paragraph', text: `But Magnus also found that she had acted in good faith, had twice received written advice indicating that the lower rate applied and had intended to pay the correct tax. Her mistake was failing to follow recommendations to obtain specialist tax advice despite the unusual trust arrangements surrounding her family home.` },
    { type: 'paragraph', text: `Rayner resigned as Deputy Prime Minister on 5 September 2025.` },
    { type: 'paragraph', text: `HMRC subsequently reached a more favourable conclusion on the tax question itself. In May 2026 it determined that her error had not been careless or deliberate and imposed no penalty. The additional £40,000 of stamp duty was paid.` },
    { type: 'paragraph', text: `That does not overturn Magnus's Ministerial Code finding. The two bodies were applying different tests.` },
    { type: 'paragraph', text: `Rayner breached the standards expected of a minister because she failed to obtain specialist advice when advised to do so. HMRC later concluded that her conduct did not meet the legal threshold for a tax penalty.` },
    { type: 'paragraph', text: `The original comparison with Jeremy Hunt and Nadhim Zahawi went too far. Rayner had criticised both Conservative politicians over tax controversies, but that does not make their arrangements "precisely" equivalent to hers.` },
    { type: 'paragraph', text: `Suella Braverman did not get sacked as Home Secretary twice.` },
    { type: 'paragraph', text: `Her first departure, on 19 October 2022, was a resignation.` },
    { type: 'paragraph', text: `Braverman had used a personal email account to send material relating to a forthcoming Written Ministerial Statement on migration. She intended to send it to Conservative MP Sir John Hayes and inadvertently also sent it to another recipient.` },
    { type: 'paragraph', text: `In her subsequent account to the Home Affairs Committee, Braverman said she had made a mistake, accepted responsibility and resigned. She acknowledged breaching the Ministerial Code.` },
    { type: 'paragraph', text: `Rishi Sunak reappointed her Home Secretary six days later.` },
    { type: 'paragraph', text: `Her second departure was different. Sunak sacked her on 13 November 2023 after a series of disputes culminating in an article for The Times attacking the Metropolitan Police. Downing Street had sought changes to the piece which were not made before publication.` },
    { type: 'paragraph', text: `That record is striking enough without rewriting the first resignation as another dismissal.` },
    { type: 'paragraph', text: `The claim that later findings on grooming gangs "partially vindicated" Braverman's earlier claim that offenders were "almost all British-Pakistani" does not hold up. Baroness Casey subsequently found disproportionate representation of men of South Asian, particularly Pakistani, heritage in data from some areas and criticised authorities for avoiding discussion of ethnicity. That does not retrospectively establish Braverman's much broader national claim, which IPSO had found significantly misleading.` },
    { type: 'paragraph', text: `Rupert Lowe's case has three separate processes which should not be collapsed into one.` },
    { type: 'paragraph', text: `Reform UK commissioned Jacqueline Perry KC to examine complaints by two women who had worked for Lowe. Her March 2025 report found credible evidence supporting allegations of harassment and criticised the culture in his offices. Lowe denied the allegations.` },
    { type: 'paragraph', text: `That was a report commissioned by his political party. It was not a court judgment.` },
    { type: 'paragraph', text: `Parliament's Independent Complaints and Grievance Scheme subsequently began its own process.` },
    { type: 'paragraph', text: `Lowe went to the High Court seeking judicial review of that parliamentary investigation. On 14 May 2026 Mr Justice Chamberlain ruled that the matter fell within Parliament's exclusive jurisdiction and could not be challenged in that way through the courts.` },
    { type: 'paragraph', text: `The judgment did not decide whether the underlying harassment allegations were true. It decided that the High Court could not supervise Parliament's handling of the complaint because of parliamentary privilege.` },
    { type: 'paragraph', text: `As of 8 June 2026, the parliamentary process had not produced a published final finding.` },
    { type: 'paragraph', text: `That is materially different from saying Lowe "lost a workplace harassment finding" and then lost an appeal against it.` },
    { type: 'paragraph', text: `Tulip Siddiq resigned as Economic Secretary to the Treasury in January 2025 after questions about properties linked to people associated with the former Bangladeshi government of her aunt, Sheikh Hasina.` },
    { type: 'paragraph', text: `Sir Laurie Magnus examined her position under the Ministerial Code.` },
    { type: 'paragraph', text: `His conclusion was not that Siddiq had been cleared only because records were missing.` },
    { type: 'paragraph', text: `Magnus said he had found no evidence of impropriety. He also said that the passage of time and absence of records meant he could not obtain comprehensive assurance on every question concerning the UK properties. He criticised Siddiq for failing to recognise the reputational risk created by her family's political connections.` },
    { type: 'paragraph', text: `Those findings can coexist. No impropriety was established, but Magnus could not resolve every historical property question.` },
    { type: 'paragraph', text: `The position in Bangladesh subsequently became much more serious than the original draft states.` },
    { type: 'paragraph', text: `On 1 December 2025, a Bangladeshi court sentenced Siddiq in absentia to two years in prison in a corruption case concerning the alleged unlawful allocation of land. Siddiq rejected the proceedings as politically motivated and fundamentally unfair. Labour said she had not received a fair legal process and that it could not recognise the judgment.` },
    { type: 'paragraph', text: `The UK ethics inquiry and the Bangladeshi criminal proceedings are separate. Magnus did not rule on the Bangladeshi prosecution, and the Bangladeshi judgment does not retrospectively change what Magnus found about her compliance with the Ministerial Code.` },
    { type: 'paragraph', text: `Diane Abbott's case is party discipline, not a parliamentary standards finding.` },
    { type: 'paragraph', text: `Labour first suspended the whip in 2023 after her letter to The Observer argued that Jewish, Irish and Traveller people experienced prejudice differently from Black people. Abbott withdrew the letter and apologised.` },
    { type: 'paragraph', text: `The whip was restored before the 2024 general election.` },
    { type: 'paragraph', text: `On 17 July 2025, she was suspended again after telling the BBC that she did not regret the substance of the remarks. Labour said the second administrative suspension would remain in place pending an investigation.` },
    { type: 'paragraph', text: `Abbott has not been found by the Parliamentary Commissioner for Standards to have broken the MPs' Code over those remarks. Nor is this a criminal or regulatory case.` },
    { type: 'paragraph', text: `Labour is entitled to enforce its own rules on its MPs. Whether its treatment of Abbott has been fair or proportionate is a political argument rather than an established finding of impropriety.` },
    { type: 'paragraph', text: `The same distinction applies to Lee Anderson.` },
    { type: 'paragraph', text: `The Conservative Party withdrew the whip from Anderson in February 2024 after he said that "Islamists" had "got control" of London Mayor Sadiq Khan. Anderson refused to apologise and joined Reform UK the following month.` },
    { type: 'paragraph', text: `That was a party disciplinary decision.` },
    { type: 'paragraph', text: `It was not a Parliamentary Commissioner finding and it did not establish financial, ministerial or legal misconduct.` },
    { type: 'paragraph', text: `Anderson's history of deliberately provocative statements is relevant to judging his politics. It does not turn every controversial statement into an ethics breach.` },
    { type: 'paragraph', text: `Zarah Sultana's inclusion exposes the central problem with describing all ten cases as a "culture of impropriety".` },
    { type: 'paragraph', text: `Sultana lost the Labour whip on 23 July 2024 after voting for an SNP amendment calling for the two-child benefit limit to be abolished. Parliament records her affiliation as Independent from that date until she became a Your Party MP in November 2025.` },
    { type: 'paragraph', text: `She had rebelled against her party.` },
    { type: 'paragraph', text: `There was no allegation that she had taken money, misled Parliament, breached the MPs' Code or behaved improperly in public office.` },
    { type: 'paragraph', text: `The policy position for which she rebelled was later adopted by the Labour government. The two-child limit ended on 6 April 2026.` },
    { type: 'paragraph', text: `That does not prove Labour was wrong to discipline MPs for breaking the whip. Governments routinely discipline rebellions even where policy subsequently changes.` },
    { type: 'paragraph', text: `Nor does the later restoration of the whip to other MPs prove Sultana had secretly been kept out because of her positions on Gaza. The chronology may support questions about Labour's handling of her, but it does not establish the leadership's motive.` },
    { type: 'paragraph', text: `This is a case about party control, political principle and a subsequent policy reversal. It is not a corruption or standards case.` },
    { type: 'paragraph', text: `Keir Starmer's entry contains two straightforward numerical errors.` },
    { type: 'paragraph', text: `Labour won 411 seats at the 2024 general election, not 412. It received 33.7 per cent of the UK vote.` },
    { type: 'paragraph', text: `Calling that a "412-seat majority" compounds the mistake. Seats won and parliamentary majority are not the same measure.` },
    { type: 'paragraph', text: `The gifts figure is sound if described properly. Sky News calculated from the Register of Members' Financial Interests that Starmer had registered £107,145 in gifts, benefits and hospitality since December 2019, more than any other MP in that category at the time of its September 2024 analysis.` },
    { type: 'paragraph', text: `That was politically damaging, particularly because Labour had entered government promising higher standards. But most of the £107,145 figure consists of declared interests. The existence of a declaration is not itself evidence of impropriety.` },
    { type: 'paragraph', text: `The polling figure also needs correcting.` },
    { type: 'paragraph', text: `YouGov recorded Starmer at net -57 in January 2026, which it described as his lowest rating to that point and the joint-lowest it had recorded for any prime minister other than Liz Truss. The draft's -61 figure is not supported by that series.` },
    { type: 'paragraph', text: `Low approval ratings, Sue Gray's departure, changes to Labour's policy platform and the decision to means-test Winter Fuel Payment may all be legitimate material in an assessment of Starmer's premiership.` },
    { type: 'paragraph', text: `They are not ethics findings.` },
    { type: 'paragraph', text: `David Lammy's transformation from one of Donald Trump's fiercest British critics into the Foreign Secretary required to work with him is a substantial political story.` },
    { type: 'paragraph', text: `It is not evidence of impropriety.` },
    { type: 'paragraph', text: `Lammy had previously called Trump a "racist KKK and Nazi sympathiser" and used other highly inflammatory descriptions. As Foreign Secretary in January 2025, he argued that much of the world welcomed Trump's return and said Britain had to work with the elected US administration.` },
    { type: 'paragraph', text: `Readers can reasonably judge that as pragmatism, hypocrisy or the unavoidable difference between opposition rhetoric and diplomacy.` },
    { type: 'paragraph', text: `There is no standards finding involved.` },
    { type: 'paragraph', text: `The Chagos section also needs factual correction.` },
    { type: 'paragraph', text: `Britain and Mauritius announced a political agreement on 3 October 2024. The government explicitly described it as such and said a treaty would follow.` },
    { type: 'paragraph', text: `The treaty itself was signed on 22 May 2025.` },
    { type: 'paragraph', text: `Under the associated financial arrangements, the UK agreed payments of £165 million a year for the first three years and £120 million a year for years four to 13. The arrangements also included a £40 million Chagossian trust fund, not £45 million. A separate development partnership was funded at £45 million a year for 25 years.` },
    { type: 'paragraph', text: `Whether that agreement represents good foreign policy is a legitimate subject for scrutiny. It does not belong in a catalogue of impropriety merely because Lammy previously used language about Trump which became inconvenient after he entered government.` },
    { type: 'paragraph', text: `The more revealing divide across these ten cases is procedural.` },
    { type: 'paragraph', text: `Farage has 17 established parliamentary registration breaches and another standards investigation remains open. Rayner breached the Ministerial Code but was subsequently found by HMRC not to have acted carelessly or deliberately. Braverman admitted a Ministerial Code breach and resigned before later being dismissed for a separate political dispute. Lowe faces unresolved parliamentary allegations after a party-commissioned KC found credible evidence supporting complaints. Siddiq has a UK ethics finding that identified no impropriety and a separate Bangladeshi conviction she says resulted from an unfair political process.` },
    { type: 'paragraph', text: `Abbott, Anderson and Sultana were disciplined by their political parties. Starmer's gifts and polling record produced political damage rather than a comparable misconduct finding. Lammy's Trump reversal is a question of political consistency.` },
    { type: 'paragraph', text: `As of 8 June 2026, Parliament's register still lists the separate Rule 5 investigation into Farage, opened on 13 May, as unresolved. Parliament does not publish the underlying details of live ICGS complaints.` },
  ],
  evidence: {
    recordsReviewed: [
      `Parliamentary Commissioner for Standards, Nigel Farage rectification decision, 20 January 2026: establishes 17 breaches of Rule 5, the individual late registrations, their values and the Commissioner's decision to use rectification rather than referral to the Committee on Standards`,
      `UK Parliament, current investigations by the Parliamentary Commissioner for Standards: records the separate Rule 5 investigation into Nigel Farage opened on 13 May 2026 and explains that details of current ICGS cases are not published`,
      `Electoral Commission and Essex Police reporting on the Clacton spending allegations, December 2025: records that the Commission decided not to investigate and that police did not open an investigation because the statutory prosecution period had expired`,
      `Independent Adviser on Ministerial Standards, advice concerning Angela Rayner, 5 September 2025: finds that Rayner acted in good faith but failed to obtain specialist tax advice and therefore breached the Ministerial Code`,
      `HMRC outcome reported 14 May 2026: records that Rayner paid the additional £40,000 of SDLT but HMRC found she had not acted carelessly or deliberately and imposed no penalty`,
      `Home Office, Suella Braverman letter to the Home Affairs Committee, 31 October 2022: Braverman's own account confirms that she accepted responsibility and resigned after the email breach`,
      `High Court, R (Lowe) v Independent Complaints and Grievance Scheme [2026] EWHC 1163 (Admin), 14 May 2026: records Lowe's judicial review challenge to Parliament's complaints process`,
      `Jacqueline Perry KC investigation reporting, 25 March 2025: records the finding of credible evidence supporting harassment complaints and Lowe's denial of the allegations`,
      `Independent Adviser findings and reporting on Tulip Siddiq: records Magnus's finding of no evidence of impropriety alongside unresolved historical property questions, and Siddiq's December 2025 conviction in absentia in Bangladesh, which she rejects as unfair and politically motivated`,
      `Reporting on Diane Abbott's suspension, 17 July 2025: records Labour's second administrative suspension of Abbott pending investigation after she stood by the substance of her earlier comments`,
      `UK Parliament, Zarah Sultana parliamentary career: records her change from Labour to Independent on 23 July 2024 and to Your Party in November 2025`,
      `Department for Work and Pensions, Universal Credit guidance: confirms that the two-child limit ended on 6 April 2026`,
      `House of Commons Library, 2024 general election results: records Labour's 411 seats and 33.7 per cent vote share`,
      `House of Commons Register analysis by Sky News, September 2024: supports the £107,145 figure for Starmer's registered gifts, benefits and hospitality since December 2019`,
      `YouGov, political favourability ratings, January 2026: records Starmer's then-low of net -57 and compares it with previous prime ministers`,
      `UK-Mauritius joint statement, 3 October 2024, and signed treaty, 22 May 2025: distinguish the original political agreement from the later treaty and establish the subsequent financial arrangements`,
    ],
    lastChecked: '5 October 2026',
  },
};

export default piece;
