import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'm2v9k7qx4r',
  kicker: 'Media and Power',
  headline: `Britain Updated Its Media-Merger Rules in 2025. Streaming Ownership Was Still Outside the Test`,
  standfirst: `Lisa Nandy is considering intervening in Paramount Skydance's proposed takeover of Warner Bros Discovery because of its potential effect on media plurality in Britain. Her statement to Parliament identified a problem in the law she would use to do it: on-demand programme services are not currently inside the ownership-plurality test.`,
  publishedAt: '2026-07-02',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `Lisa Nandy is considering intervening in Paramount Skydance's proposed takeover of Warner Bros Discovery because of its potential effect on media plurality in Britain.` },
    { type: 'paragraph', text: `Her statement to Parliament on 30 June identified a problem in the law she would use to do it.` },
    { type: 'paragraph', text: `The Enterprise Act already contains public-interest tests covering news plurality and concentration of control over traditional media enterprises.` },
    { type: 'paragraph', text: `It does not currently put on-demand programme services inside the same ownership-plurality test.` },
    { type: 'paragraph', text: `Nandy told Parliament that if she intervenes on that ground, she will use powers in the Act to add a new public-interest consideration covering streaming and video-on-demand services.` },
    { type: 'paragraph', text: `That is narrower than saying Britain lacks the legal machinery to examine the merger.` },
    { type: 'paragraph', text: `The Enterprise Act anticipated that circumstances could arise which its original list of public-interest considerations did not cover. Section 42 allows a Culture Secretary to issue an intervention notice on a consideration that is not yet specified in section 58 if, in the Secretary of State's opinion, it ought to be. The government must then move to have that consideration formally added.` },
    { type: 'paragraph', text: `The gap is therefore in the standing media-plurality test, not in the government's ability to respond to an unforeseen type of merger.` },
    { type: 'paragraph', text: `Nandy's proposed wording would require consideration of whether there is sufficient plurality of people controlling "media enterprises, or the enterprises providing on-demand programme services or both" serving a UK audience. She said the existing legislation was written when viewing was predominantly through linear broadcasting and does not capture the full effect of mergers involving streaming services.` },
    { type: 'paragraph', text: `The transaction is large enough to expose that distinction.` },
    { type: 'paragraph', text: `Paramount agreed in February to buy Warner Bros Discovery in a deal valuing WBD at $81 billion in equity and $110 billion including debt. The companies said they expected the transaction to close in the third quarter of 2026, subject to regulatory approvals.` },
    { type: 'paragraph', text: `The combined group would bring together Paramount+ and HBO Max, CBS and CBS News with CNN, Nickelodeon with Cartoon Network, and Paramount Pictures with Warner Bros.` },
    { type: 'paragraph', text: `In Britain, Nandy specifically named Channel 5, TNT Sports, Cartoon Network, Nickelodeon and CNN International, along with Paramount+ and HBO Max, when explaining why she believed the merger could affect UK audiences.` },
    { type: 'paragraph', text: `TNT Sports needs a qualification. As of 2 July 2026, Companies House still listed both British Telecommunications plc and the Warner Bros Discovery-linked entity Dni Foreign Holdings Limited as active persons with significant control of TNT Sports Broadcasting Ltd, with no cessation recorded for either — consistent with BT's own reporting that its UK and Ireland sports business remained a 50:50 joint venture, with Warner Bros Discovery holding an option to acquire BT's half that had not been reported as exercised.` },
    { type: 'paragraph', text: `Britain had already tried to update its media-merger rules for changing viewing habits.` },
    { type: 'paragraph', text: `Nandy opened a consultation in November 2024 after Ofcom recommended broadening a regime designed around newspapers and broadcasters. The government said at the time that the law had not kept pace with technology.` },
    { type: 'paragraph', text: `The reform that followed concentrated principally on news.` },
    { type: 'paragraph', text: `In May 2025, the government decided to bring online news publications and periodical news magazines into the regime and broaden the existing news public-interest tests. It rejected a much wider approach that could have captured any entity creating news, saying that could impose disproportionate burdens.` },
    { type: 'paragraph', text: `The resulting secondary legislation came into force in July 2025.` },
    { type: 'paragraph', text: `It changed section 58 so that tests concerning accurate news, freedom of opinion and plurality of views applied to "news media", defined as newspapers and broadcast news programmes. It also broadened the ownership-plurality provision across newspaper and broadcasting enterprises.` },
    { type: 'paragraph', text: `It did not add general video-on-demand services to that ownership test.` },
    { type: 'paragraph', text: `Less than a year later, Paramount-Warner has brought exactly that omission into a live merger decision.` },
    { type: 'paragraph', text: `This does not mean the 2025 reform failed at what it was designed to do. It was primarily aimed at bringing online journalism into rules written for print and broadcasting.` },
    { type: 'paragraph', text: `But the government described that exercise as modernising the media-merger regime for the digital age. The Paramount transaction has shown that one increasingly important part of that digital market remained outside the specified ownership-plurality test.` },
    { type: 'paragraph', text: `The Competition and Markets Authority is examining a different question.` },
    { type: 'paragraph', text: `It formally opened its merger inquiry on 9 June to assess competition in the UK. Nandy's proposed intervention would add examination of wider public-interest issues, with Ofcom reporting on media plurality if she issues the intervention notice.` },
    { type: 'paragraph', text: `The two tests should not be confused.` },
    { type: 'paragraph', text: `A merger can pass competition scrutiny while still raising questions about concentration of media ownership, editorial independence or the number of separate organisations controlling services consumed by the public.` },
    { type: 'paragraph', text: `The US Department of Justice reached its competition decision on 12 June. It closed its antitrust investigation after concluding that the merger was unlikely to harm American consumers in streaming, linear television or film production. It went further on streaming, saying the combined business could provide stronger competition to larger subscription services.` },
    { type: 'paragraph', text: `That finding does not answer Nandy's media-plurality question, and it does not amount to worldwide regulatory clearance of the transaction.` },
    { type: 'paragraph', text: `Nor had the transaction cleared every US regulatory process by 2 July. Paramount had separately asked the Federal Communications Commission to permit the level of foreign investment expected in the combined company. A US national-security review of that request had begun in June.` },
    { type: 'paragraph', text: `Nandy had also used the existing British media public-interest regime earlier in the year.` },
    { type: 'paragraph', text: `In February she issued an intervention notice over Daily Mail and General Trust's proposed purchase of the Telegraph, relying on the existing tests covering plurality of views in news media and plurality of people controlling media enterprises.` },
    { type: 'paragraph', text: `Paramount-Warner requires something additional because part of the audience Nandy wants Ofcom to consider receives content through services the existing ownership test does not expressly cover.` },
    { type: 'paragraph', text: `The parties have until 6 July to respond to her concerns.` },
    { type: 'paragraph', text: `Nandy has not yet issued an intervention notice. If she does, Ofcom would examine the media-public-interest considerations and the CMA would report on jurisdiction and competition before she decided whether a more detailed investigation was required.` },
    { type: 'paragraph', text: `The Secretary of State's role in these cases has historically been treated as quasi-judicial, with ministers expected to follow a fair and impartial process. There is no evidence that the timetable was chosen for political reasons or to constrain whoever succeeds Starmer.` },
    { type: 'paragraph', text: `The documented problem is simpler.` },
    { type: 'paragraph', text: `Britain modernised its media-merger rules in 2025 because audiences had moved online.` },
    { type: 'paragraph', text: `The reform brought online news into the system.` },
    { type: 'paragraph', text: `It did not bring general streaming services into the standing test for concentration of media ownership.` },
    { type: 'paragraph', text: `A year later, one of the world's largest media mergers has forced the Culture Secretary to use the Enterprise Act's catch-all mechanism to propose doing precisely that.` },
  ],
  evidence: {
    recordsReviewed: [
      `House of Commons, Lisa Nandy, Paramount-WBD Merger: Public Interest Considerations, 30 June 2026: records Nandy's "minded to intervene" decision, the UK services under consideration, the absence of on-demand programme services from the existing ownership-plurality consideration, her proposed new test and the 6 July deadline for representations`,
      `Enterprise Act 2002, sections 42, 58 and 58A: establishes the existing media public-interest considerations and the power to intervene using a consideration not yet specified in section 58 where the Secretary of State considers that it ought to be specified, subject to subsequent finalisation`,
      `Department for Culture, Media and Sport, Consultation on updating the media mergers regime, November 2024, and government response, May 2025: shows that the previous modernisation focused on online news publications and news programmes and records the government's reasons for not adopting a substantially broader definition`,
      `The Enterprise Act 2002 (Amendment of Section 58 Considerations) Order 2025: came into force on 24 July 2025 and extended the relevant public-interest considerations to "news media", defined as newspapers and broadcast news programmes; it did not extend the ownership test generally to video-on-demand services`,
      `Paramount Skydance, merger announcement, 27 February 2026: records the $81 billion equity value, $110 billion enterprise value and expected third-quarter 2026 completion, subject to approvals`,
      `Competition and Markets Authority, Paramount / Warner Bros Discovery merger inquiry: records the commencement of the UK competition investigation on 9 June 2026`,
      `Companies House, TNT Sports Broadcasting Ltd, persons with significant control: records British Telecommunications plc and Dni Foreign Holdings Limited (Warner Bros Discovery-linked) as active persons with significant control as of 2 July 2026, with no cessation recorded for either, consistent with the sports joint venture remaining 50:50 owned`,
      `BT Group, full-year results to 31 March 2026, published 21 May 2026, and BT Group Annual Report 2026: state that the sports joint venture known externally as TNT Sports remained owned 50:50 by BT and Warner Bros Discovery, with equal voting rights, and that WBD retained a call option over BT's 50 per cent interest`,
      `US Department of Justice Antitrust Division, 12 June 2026: records the closure of the US antitrust investigation and its conclusion that the transaction was unlikely to harm competition in streaming, linear television or film production`,
      `Federal Communications Commission record of Paramount foreign-ownership proceedings: records the separate foreign-investment review that was still under consideration in June 2026`,
      `Department for Culture, Media and Sport / CMA, DMGT-Telegraph merger inquiry, February 2026: provides a recent example of Nandy issuing a Public Interest Intervention Notice under the existing media-plurality considerations`,
    ],
    lastChecked: '5 October 2026',
  },
};

export default piece;
