import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'm7k4qxw9n2',
  kicker: 'The Treasury',
  headline: `John Healey Resigned Over Treasury Restraint. Five Weeks Later He Was Put in Charge of the Treasury`,
  standfirst: `Five weeks ago, John Healey resigned as defence secretary because he said the Treasury would not provide enough money for Britain's armed forces. On 20 July, Andy Burnham made him Chancellor of the Exchequer. Healey now controls the department whose spending restraint helped prompt his resignation.`,
  publishedAt: '2026-07-20',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `Five weeks ago, John Healey resigned as defence secretary because he said the Treasury would not provide enough money for Britain's armed forces.` },
    { type: 'paragraph', text: `On 20 July, Andy Burnham made him Chancellor of the Exchequer.` },
    { type: 'paragraph', text: `Healey's resignation letter to Keir Starmer on 11 June said the Prime Minister had been unable, and the Treasury unwilling, to commit the resources required for defence.` },
    { type: 'paragraph', text: `"I would not be able to accept a DIP settlement that does not give our forces the resources they need," he wrote, referring to the Defence Investment Plan. "I am now left with no other option than to submit my resignation."` },
    { type: 'paragraph', text: `He now controls the department whose spending restraint helped prompt that resignation.` },
    { type: 'paragraph', text: `The appointment was a genuine surprise.` },
    { type: 'paragraph', text: `In the days before Burnham entered Downing Street, Shabana Mahmood was widely reported to be the favourite for the Treasury. Ed Miliband had also been discussed as a possible chancellor.` },
    { type: 'paragraph', text: `On 19 July, ITV political editor Robert Peston said his working assumption was that Mahmood would get the job. The Guardian had reported four days earlier that senior Labour figures expected the same.` },
    { type: 'paragraph', text: `Instead, Mahmood remained home secretary, Miliband became foreign secretary and Healey went to No 11.` },
    { type: 'paragraph', text: `Healey is not new to the Treasury.` },
    { type: 'paragraph', text: `He served as Economic Secretary from 2002 to 2005 and Financial Secretary from 2005 to 2007. Before that he had been parliamentary private secretary to Gordon Brown when Brown was chancellor.` },
    { type: 'paragraph', text: `His appointment therefore puts one of Burnham's most economically experienced senior ministers into the job, despite Healey having spent the previous six years concentrating principally on defence.` },
    { type: 'paragraph', text: `It also gives him responsibility for resolving the argument which led him to leave government.` },
    { type: 'paragraph', text: `As defence secretary, Healey had pushed for more military spending than Starmer and Rachel Reeves were prepared to fund. His resignation accused the previous government of failing to match its security commitments with money.` },
    { type: 'paragraph', text: `As chancellor, he will now have to decide how increased defence spending competes with the NHS, welfare, local government, investment and every other call on the public finances.` },
    { type: 'paragraph', text: `That is a more concrete test of the appointment than the fact that nobody voted specifically for John Healey to become chancellor.` },
    { type: 'paragraph', text: `British voters never directly elect chancellors.` },
    { type: 'paragraph', text: `They do not directly elect prime ministers either.` },
    { type: 'paragraph', text: `At a general election, voters elect their constituency MP. The Prime Minister is appointed by the monarch according to the constitutional convention that the person appointed must be able to command the confidence of the House of Commons. The Prime Minister then chooses the government's ministers.` },
    { type: 'paragraph', text: `Burnham becoming Prime Minister without a general election was therefore constitutionally normal.` },
    { type: 'paragraph', text: `Labour still holds the Commons majority won at the 2024 election. Burnham became an MP again by winning the Makerfield by-election on 18 June with 24,927 votes, or 54.8 per cent of those cast. He was subsequently chosen as Labour leader and became Prime Minister on 20 July.` },
    { type: 'paragraph', text: `The relevant question is not whether the constitution required another election. It did not.` },
    { type: 'paragraph', text: `It is how far Burnham and Healey intend to change the economic programme on which Labour won the election in 2024 before asking the wider electorate to approve a new one.` },
    { type: 'paragraph', text: `This is the live question, because Burnham has already ruled out an immediate general election and said before taking office that he would govern within Labour's existing manifesto.` },
    { type: 'paragraph', text: `That manifesto was explicit on several of the constraints facing a chancellor.` },
    { type: 'paragraph', text: `Labour promised not to increase the rates of income tax, National Insurance or VAT. It committed itself to fiscal rules intended to balance day-to-day spending with revenues and reduce debt as a share of the economy over the forecast period. It also promised economic stability, higher investment and a rise in defence spending.` },
    { type: 'paragraph', text: `Healey therefore has an inherited electoral programme even though he has no personal manifesto as chancellor.` },
    { type: 'paragraph', text: `What voters do not yet have is a detailed account of how Burnham's government intends to reconcile that programme with its own changes in direction.` },
    { type: 'paragraph', text: `Healey's appointment itself points to one of those tensions.` },
    { type: 'paragraph', text: `As defence secretary, he concluded that the money available under Starmer was insufficient. Burnham has now put him in charge of deciding whether more can be found and, if so, what has to give elsewhere.` },
    { type: 'paragraph', text: `There are similar questions around Burnham's wider economic programme. He has talked about a more interventionist approach to industry, greater regional investment and a different relationship between government and essential services.` },
    { type: 'paragraph', text: `But on his first day in office there was no new Budget, spending review or fiscal plan showing how those priorities fitted together.` },
    { type: 'paragraph', text: `That is not unusual on the afternoon a government is reshuffled. Nor does a new chancellor normally publish a personal manifesto on appointment.` },
    { type: 'paragraph', text: `It does mean that the change in personnel has arrived before the detailed economic programme.` },
    { type: 'paragraph', text: `The first substantial opportunity for Healey to set that out will be through the Treasury.` },
    { type: 'paragraph', text: `His appointment was formally approved by the King on 20 July alongside the rest of Burnham's first Cabinet. The government's announcement confirmed Mahmood would remain at the Home Office and Miliband would take the Foreign Office.` },
    { type: 'paragraph', text: `The political contrast with five weeks earlier is difficult to miss.` },
    { type: 'paragraph', text: `On 11 June, Healey's position was that the Treasury had refused to provide enough money to meet Britain's defence needs.` },
    { type: 'paragraph', text: `On 20 July, responsibility for making those choices became his.` },
  ],
  evidence: {
    recordsReviewed: [
      `Prime Minister's Office, Ministerial Appointments: July 2026, 20 July 2026: John Healey's appointment as Chancellor of the Exchequer, Ed Miliband as Foreign Secretary and the composition of Burnham's first Cabinet`,
      `UK Parliament, John Healey parliamentary career: Healey's service as Economic Secretary to the Treasury from 2002 to 2005 and Financial Secretary from 2005 to 2007, as well as his period as defence secretary`,
      `GOV.UK, John Healey biography: his appointment as chancellor on 20 July 2026 and his previous Treasury and defence roles`,
      `John Healey resignation letter and contemporary reporting, 11 June 2026: Healey's reason for resigning as defence secretary, including his criticism that the Treasury had been unwilling to provide the resources he believed defence required`,
      `Reuters, "Former defence minister Healey named as new UK finance minister", 20 July 2026: the unexpected nature of Healey's appointment and the connection between his June resignation over defence funding and his subsequent move to the Treasury`,
      `The Guardian, "Shabana Mahmood expected to be named Andy Burnham's chancellor", 15 July 2026, and ITV News, cabinet preview, 19 July 2026: the contemporaneous expectation that Mahmood was the frontrunner and that Miliband was also seriously discussed before Healey's appointment`,
      `UK Parliament, General elections: the constitutional distinction between electing MPs and appointing a prime minister, and confirmation that voters do not directly elect the Prime Minister`,
      `House of Commons Library, How is the Prime Minister appointed?, 22 June 2026, and Commanding confidence, 29 June 2026: the constitutional requirement that a government and prime minister command the confidence of the House of Commons and the process for changing prime minister during a Parliament`,
      `UK Parliament, Makerfield by-election result, 18 June 2026: Burnham's 24,927 votes, 54.8 per cent vote share and 9,231 majority on his return to the Commons`,
      `Labour Party, Andy Burnham elected Labour leader, 17 July 2026: Burnham's election as Labour leader before his appointment as Prime Minister`,
      `Labour Party, Change: Labour Party Manifesto 2024 and fiscal plan: the existing electoral commitments inherited by Burnham's government, including the main tax pledges and fiscal rules`,
    ],
    lastChecked: '4 October 2026',
  },
};

export default piece;
