import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'mi5k7qxw9n',
  kicker: 'National Security',
  headline: `MI5 Gave False Evidence to the Courts After an Officer Lied About What He Told the BBC`,
  standfirst: `In June 2020, a senior MI5 officer told a BBC journalist that Agent X was an MI5 informant. Less than two years later, MI5 gave the High Court a witness statement saying that had never happened. The statement was false. A 213-page investigation published on 16 July has now established that the officer who made the original disclosure knew throughout that he had done so and later fabricated an account denying it.`,
  publishedAt: '2026-07-16',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `In June 2020, a senior MI5 officer telephoned a BBC journalist who was investigating a man known only as Agent X.` },
    { type: 'paragraph', text: `The officer told him that Agent X was an MI5 informant.` },
    { type: 'paragraph', text: `Less than two years later, MI5 gave the High Court a witness statement saying that had never happened.` },
    { type: 'paragraph', text: `The statement was false.` },
    { type: 'paragraph', text: `The same account was subsequently relied on before the Investigatory Powers Tribunal and in a High Court judicial review. MI5 also used it to persuade its independent watchdog that it had maintained its longstanding policy of neither confirming nor denying the identity of intelligence sources.` },
    { type: 'paragraph', text: `A 213-page investigation published on 16 July has now established how that happened.` },
    { type: 'paragraph', text: `Sir John Goldring, the Deputy Investigatory Powers Commissioner, concluded that the officer who made the original disclosure knew throughout that he had done so and later fabricated an account denying it.` },
    { type: 'paragraph', text: `"His lies formed the foundation of MI5's false account," Goldring found.` },
    { type: 'paragraph', text: `The report goes considerably further than the earlier explanation offered by MI5.` },
    { type: 'paragraph', text: `Its initial internal investigation had concluded that the officer, identified only as Officer 2, had simply forgotten the conversations and had not deliberately misled anyone. An external review by former government lawyer Sir Jonathan Jones KC did not disagree.` },
    { type: 'paragraph', text: `Goldring rejected that explanation.` },
    { type: 'paragraph', text: `He found that Officer 2 knew he had departed from MI5's secrecy policy, failed to make the records required of him and later lied when asked what he had told the BBC.` },
    { type: 'paragraph', text: `A second senior officer, Officer 3, also played a central role.` },
    { type: 'paragraph', text: `When Officer 2 initially said he could not remember whether he had revealed Agent X's status but thought that he had not, Officer 3 reported the position more definitively, telling colleagues that the policy had not been breached.` },
    { type: 'paragraph', text: `Another officer told him that it had.` },
    { type: 'paragraph', text: `That information did not reach the lawyers preparing MI5's case.` },
    { type: 'paragraph', text: `By December 2023, the contradiction had become harder to miss.` },
    { type: 'paragraph', text: `At a meeting involving officers familiar with Agent X's case, one made it "absolutely clear" to Officer 3 that the informant's status had been disclosed, and said that horse had bolted.` },
    { type: 'paragraph', text: `Goldring found that Officer 3 shut down that intervention, continued to withhold Officer 2's original uncertainty and later bore "considerable responsibility" for the continuation of MI5's false account.` },
    { type: 'paragraph', text: `The false evidence concerned a man whose conduct was already causing serious concern.` },
    { type: 'paragraph', text: `Agent X is a foreign national whose identity remains protected by a court order. He worked as a covert human intelligence source for MI5 while involved in extremist circles.` },
    { type: 'paragraph', text: `His former partner, known publicly as Beth, alleges that he subjected her to sustained abuse and used his connection to MI5 to frighten her into silence. Goldring's report records her allegation that he told her his relationship with the Security Service made him "untouchable".` },
    { type: 'paragraph', text: `When BBC journalist Daniel De Simone contacted MI5 in June 2020, he was investigating whether Agent X was genuinely a violent extremist rather than merely pretending to be one as part of his intelligence work.` },
    { type: 'paragraph', text: `MI5 believed publication could put Agent X's life in danger.` },
    { type: 'paragraph', text: `The handling team decided that the BBC might be persuaded not to identify him if the service explained that he was working for MI5.` },
    { type: 'paragraph', text: `Officer 2 made the calls.` },
    { type: 'paragraph', text: `Goldring found that proper authorisation to abandon the neither-confirm-nor-deny policy was never obtained from the Director General or Deputy Director General, as it should have been.` },
    { type: 'paragraph', text: `Officer 2 nevertheless told De Simone almost immediately that Agent X was an MI5 source. Over a series of conversations he went further, discussing the status of other intelligence sources as well.` },
    { type: 'paragraph', text: `The BBC journalist did not accept MI5's explanation of Agent X.` },
    { type: 'paragraph', text: `He told Officer 2 that he believed the man was genuinely violent and abusive. In an email sent after their first conversation he described allegations including domestic abuse, sexual violence and attempted murder.` },
    { type: 'paragraph', text: `By December 2021, the BBC was putting another set of allegations to MI5. Its right-of-reply email described Agent X as a dangerous extremist and misogynist who had physically and psychologically abused two women and threatened sexual abuse of children.` },
    { type: 'paragraph', text: `Those remained allegations, but MI5 knew they were being made.` },
    { type: 'paragraph', text: `The Security Service then sought to prevent the BBC from identifying Agent X.` },
    { type: 'paragraph', text: `In January 2022, an MI5 corporate witness known as Witness A submitted evidence saying that during the 2020 conversations Officer 2 had neither confirmed nor denied that Agent X was an intelligence source.` },
    { type: 'paragraph', text: `The special advocates appointed to examine secret material questioned that claim after reading Agent X's file.` },
    { type: 'paragraph', text: `MI5 checked again.` },
    { type: 'paragraph', text: `At a meeting on 17 February 2022, Officer 2 gave what Goldring has now concluded was a fabricated account. MI5 then assured the special advocates that its secrecy policy had been maintained.` },
    { type: 'paragraph', text: `The High Court granted the injunction.` },
    { type: 'paragraph', text: `The order still allowed the BBC to report the central allegations against Agent X and MI5's handling of him, but prevented his identification.` },
    { type: 'paragraph', text: `Beth subsequently brought her own case against the Security Service in the Investigatory Powers Tribunal, alleging that MI5 had failed to protect her.` },
    { type: 'paragraph', text: `Whether MI5 had previously revealed Agent X's status became important to that case.` },
    { type: 'paragraph', text: `MI5 continued to say it had not.` },
    { type: 'paragraph', text: `Its own regulator had doubts.` },
    { type: 'paragraph', text: `IPCO inspectors examined Agent X's file in 2022 and concluded that there were reasonable grounds to believe his status had been disclosed to the BBC. They also found problems with record keeping and MI5's management of the case.` },
    { type: 'paragraph', text: `MI5 disputed the disclosure finding.` },
    { type: 'paragraph', text: `When Investigatory Powers Commissioner Sir Brian Leveson asked for contemporaneous evidence supporting MI5's position, the service could not provide it. Instead, it relied partly on the same evidence which had already been submitted to the High Court.` },
    { type: 'paragraph', text: `IPCO eventually removed its finding that MI5 had broken the secrecy policy.` },
    { type: 'paragraph', text: `That finding was correct the first time.` },
    { type: 'paragraph', text: `The false account then reached the Investigatory Powers Tribunal.` },
    { type: 'paragraph', text: `In June 2024, the tribunal concluded in strong terms that MI5 had gone to "extensive lengths" to maintain its neither-confirm-nor-deny policy.` },
    { type: 'paragraph', text: `That conclusion was based on a false premise.` },
    { type: 'paragraph', text: `Beth had sought confirmation of whether Agent X worked for MI5 because she said he had used that status as part of his abuse of her. She offered to receive the information privately within a confidentiality arrangement.` },
    { type: 'paragraph', text: `The tribunal refused.` },
    { type: 'paragraph', text: `The position began to collapse later that year because the BBC possessed something MI5 did not appear to have: contemporaneous evidence of the original conversations.` },
    { type: 'paragraph', text: `De Simone had taken notes.` },
    { type: 'paragraph', text: `He had also recorded calls.` },
    { type: 'paragraph', text: `In November 2024, the BBC told MI5 that Officer 2 had disclosed Agent X's status from the beginning. The following month MI5 representatives were shown a contemporaneous note and heard a recording.` },
    { type: 'paragraph', text: `By February 2025, MI5 and the Attorney General accepted that false evidence had been given.` },
    { type: 'paragraph', text: `In May, the Security Service took the exceptional step of publicly confirming that Agent X had indeed been an MI5 informant.` },
    { type: 'paragraph', text: `The courts were not satisfied with MI5's explanation for what had happened.` },
    { type: 'paragraph', text: `The service conducted an internal investigation and commissioned Sir Jonathan Jones to carry out an external review. Both essentially concluded that mistakes had been made but that nobody had deliberately set out to mislead the court.` },
    { type: 'paragraph', text: `In July 2025, the Divisional Court said those investigations suffered from such serious deficiencies that their conclusions could not safely be relied upon.` },
    { type: 'paragraph', text: `It called for another investigation under the Investigatory Powers Commissioner.` },
    { type: 'paragraph', text: `Goldring's investigation reached a different conclusion about Officer 2.` },
    { type: 'paragraph', text: `He found that the officer had not forgotten.` },
    { type: 'paragraph', text: `"He has not told the truth," the report says.` },
    { type: 'paragraph', text: `Goldring also found wider organisational failures. Important conversations had gone unrecorded. Evidence in Agent X's own file which should have prompted further inquiry was missed. Officers who knew that MI5's account was questionable did not ensure it was corrected.` },
    { type: 'paragraph', text: `The legal process had weaknesses too.` },
    { type: 'paragraph', text: `The duty of candour, the particularly demanding obligation on public authorities to give courts a complete and accurate account, was not expressly explained to Witness A or to the officers whose evidence fed into his statements.` },
    { type: 'paragraph', text: `Goldring said the deeper problem was not simply a failure to explain the rule. Officers knew they were providing information for legal proceedings and were still required to be truthful and open.` },
    { type: 'paragraph', text: `The report also criticises MI5's record keeping.` },
    { type: 'paragraph', text: `Goldring said he was struck by how few contemporaneous notes had been made of important meetings. That made it harder both to establish what happened and for MI5 to meet its disclosure obligations later.` },
    { type: 'paragraph', text: `Investigatory Powers Commissioner Sir Brian Leveson described the findings as serious.` },
    { type: 'paragraph', text: `He said effective oversight of intelligence agencies depends on complete candour because regulators and courts cannot independently recreate every secret operation for themselves.` },
    { type: 'paragraph', text: `IPCO's published summary describes "serious and systemic failures" and says a false account was allowed to "take hold and persist".` },
    { type: 'paragraph', text: `MI5 Director General Sir Ken McCallum has apologised again.` },
    { type: 'paragraph', text: `He said the service recognised "without hesitation" the seriousness of its failings, apologised to the courts for the incorrect evidence and the delay in discovering it, and apologised to Beth for the additional distress caused by MI5's handling of her claim.` },
    { type: 'paragraph', text: `MI5 says it has changed its record-keeping processes, revised how evidence is prepared for court and updated policies and training for identifying people who may be at risk of harm.` },
    { type: 'paragraph', text: `Beth's case against the Security Service was settled in March 2026 without an admission of liability.` },
    { type: 'paragraph', text: `MI5 acknowledged that it had relied on incorrect evidence, said its record keeping had fallen below the required standard and apologised for prolonging the litigation.` },
    { type: 'paragraph', text: `Home Secretary Shabana Mahmood has now announced further oversight measures.` },
    { type: 'paragraph', text: `She said she would strengthen the arrangements through which the Home Secretary holds the MI5 Director General accountable, introduce more independent senior challenge to MI5's internal reform programme and increase scrutiny of the service's litigation strategy.` },
    { type: 'paragraph', text: `Her statement also makes clear that the judicial process is not finished.` },
    { type: 'paragraph', text: `The unresolved issue is contempt of court.` },
    { type: 'paragraph', text: `When the Divisional Court examined the false evidence in 2025, it said giving false evidence in a witness statement can amount to contempt.` },
    { type: 'paragraph', text: `It considered MI5's own investigations too unreliable to decide whether proceedings should be started against any individual and postponed that decision until the independent investigation had been completed.` },
    { type: 'paragraph', text: `That investigation is now complete.` },
    { type: 'paragraph', text: `It has found that a senior MI5 officer fabricated an account, that his lies became the foundation for false evidence, that another senior officer bore considerable responsibility for allowing the falsehood to continue and that opportunities to correct the courts were repeatedly missed.` },
    { type: 'paragraph', text: `As of 16 July, the High Court and Investigatory Powers Tribunal had not announced what they would do next.` },
  ],
  evidence: {
    recordsReviewed: [
      `Sir John Goldring, Deputy Investigatory Powers Commissioner, Investigation into the provision of false evidence to the High Court and the Investigatory Powers Tribunal in relation to Agent X, July 2026: the chronology of the BBC contacts, the false evidence, findings against Officers 2 and 3, failures of record keeping and candour, MI5's responses to IPCO and the litigation history`,
      `Investigatory Powers Commissioner's Office, statement on the Agent X investigation, 16 July 2026: the description of serious and systemic failures, the failure to obtain proper authority to depart from NCND, the persistence of the false account and the continuing IPCO scrutiny of MI5's reforms`,
      `Divisional Court, HM Attorney General for England and Wales v British Broadcasting Corporation; R (Beth) v Investigatory Powers Tribunal [2025] EWHC 1669 (KB), 2 July 2025: the finding that false evidence misled the High Court and IPT, the deficiencies in MI5's original investigations and the decision to postpone consideration of possible contempt proceedings pending a further independent investigation`,
      `Investigatory Powers Tribunal, Beth v Security Service [2025] UKIPTrib 8, case IPT/22/10/CH, 30 July 2025: the tribunal's concerns about the misleading evidence, the importance of candour in closed proceedings and its request for a further investigation`,
      `Investigatory Powers Commissioner's Office, statement on its earlier inspection of Agent X, 2 July 2025: IPCO's original conclusion that Agent X's status had been disclosed, MI5's successful challenge to that finding and the lack of contemporaneous records supporting MI5's account`,
      `MI5 Director General statement, 16 July 2026: Sir Ken McCallum's apologies and the changes MI5 says it has made to record keeping, court evidence and safeguarding procedures`,
      `MI5 Director General statement, 17 March 2026: the settlement of Beth's Investigatory Powers Tribunal claim without admission of liability and MI5's apology for relying on incorrect evidence and prolonging her case`,
      `Home Secretary, Written Ministerial Statement HCWS285, 16 July 2026: the government's response, planned strengthening of Home Secretary oversight, independent challenge and scrutiny of MI5 litigation, and confirmation that the courts will determine the next steps in the continuing legal proceedings`,
    ],
    lastChecked: '4 October 2026',
  },
};

export default piece;
