import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'mk4n9mxw7r',
  kicker: 'Industry',
  headline: `Government Calls £600m-a-Year Industry Subsidy a Bill Cut`,
  standfirst: `The British Industrial Competitiveness Scheme will relieve eligible manufacturers of up to £40 per megawatt hour in policy costs, worth around £600 million a year in total. A comparable scheme, the British Industry Supercharger, has been running since April 2024. No evaluation of what firms did with that support has been published.`,
  publishedAt: '2026-10-01',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `The government says more than 10,000 manufacturers will get electricity bills cut by up to 25 per cent under a new scheme intended to boost investment, jobs and British industry.` },
    { type: 'paragraph', text: `The saving is real for the companies that qualify.` },
    { type: 'paragraph', text: `But the cost has not disappeared.` },
    { type: 'paragraph', text: `The British Industrial Competitiveness Scheme is expected to be worth around £600 million a year, with eligible firms exempted from several policy costs currently built into industrial electricity bills, worth up to around £40 per megawatt hour.` },
    { type: 'paragraph', text: `Government will use a mixture of Exchequer funding and changes elsewhere in the energy system to stop those costs simply being passed straight on to households and other businesses.` },
    { type: 'paragraph', text: `That makes the policy less a straightforward bill cut than a decision about who should pay.` },
    { type: 'paragraph', text: `Selected manufacturers will pay less.` },
    { type: 'paragraph', text: `The cost will be carried elsewhere.` },
    { type: 'paragraph', text: `The headline says bills are being "slashed".` },
    { type: 'paragraph', text: `The underlying policy is a subsidy.` },
    { type: 'heading', level: 2, text: `The relief does not come from cheaper electricity` },
    { type: 'paragraph', text: `The companies receiving support are not necessarily buying electricity at a lower wholesale price.` },
    { type: 'paragraph', text: `Instead, the government is removing some of the policy charges normally added to their bills.` },
    { type: 'paragraph', text: `Eligible firms will receive relief from costs linked to the Renewables Obligation, Feed-in Tariffs and the Capacity Market.` },
    { type: 'paragraph', text: `Those schemes still exist.` },
    { type: 'paragraph', text: `The costs associated with them still have to be met.` },
    { type: 'paragraph', text: `The policy changes who carries them.` },
    { type: 'paragraph', text: `That is a legitimate political choice, but it should be described accurately.` },
    { type: 'paragraph', text: `Government is not solving the underlying problem of expensive electricity.` },
    { type: 'paragraph', text: `It is shielding selected industries from part of the bill.` },
    { type: 'paragraph', text: `That distinction matters because the scheme is due to run until 2035, with a formal review in 2030 to check whether it is still delivering its aim cost-effectively as prices evolve.` },
    { type: 'paragraph', text: `A decade-long subsidy stops being emergency support. It becomes part of the structure of the market.` },
    { type: 'heading', level: 2, text: `The government has run this experiment before, and has not shown its working` },
    { type: 'paragraph', text: `Ministers say lower electricity costs will allow manufacturers to invest, expand and create jobs.` },
    { type: 'paragraph', text: `This is not the government's first attempt at that argument.` },
    { type: 'paragraph', text: `The British Industry Supercharger, a related scheme worth an estimated £320 to £410 million a year, has been compensating energy-intensive firms for network charges since April 2024, two and a half years before this latest scheme opened for applications. No evaluation of what recipient firms actually did with that support has been published. The only public assessment of the Supercharger's case was a pre-launch subsidy-control review, which noted it was relying on "anecdotal evidence" of firms considering relocation abroad rather than any measured data on investment, jobs or production.` },
    { type: 'paragraph', text: `The government is now asking the public to accept a second, larger scheme on the same promise, without having published results from the first one.` },
    { type: 'paragraph', text: `As of its own April 2026 response to the BICS design consultation, no quantified estimate of this scheme's investment impact existed. The only published expectation was the qualitative claim that, because high energy costs have "consistently been cited as a significant barrier to investment," the scheme "should result in increased investment and growth." A fuller impact assessment, to be scrutinised by the Regulatory Policy Committee, was promised for later in the year, alongside the scheme's supporting legislation.` },
    { type: 'paragraph', text: `The scheme is now open for applications, running from 1 October to 30 November 2026, with support due to begin from 2027, while the political case continues to rest on an investment claim that has not been quantified and a predecessor scheme whose results have not been published.` },
    { type: 'paragraph', text: `Energy costs are a real constraint for British manufacturing.` },
    { type: 'paragraph', text: `But reducing one input cost does not guarantee that firms spend the saving on new factories, machinery or jobs.` },
    { type: 'paragraph', text: `Some may invest.` },
    { type: 'paragraph', text: `Some may use the relief to protect margins.` },
    { type: 'paragraph', text: `Some may simply become less uncompetitive than they were before.` },
    { type: 'paragraph', text: `Those are different outcomes, and nothing published so far tells us which one is happening.` },
    { type: 'heading', level: 2, text: `The safeguard against distorting competition does not exist yet` },
    { type: 'paragraph', text: `The government's own consultation acknowledges that the design can create differences between firms operating in the same market.` },
    { type: 'paragraph', text: `A business producing both eligible and ineligible products may receive cheaper electricity across parts of its operation while a competitor outside the scheme does not. The consultation itself warns this "carries a risk of potential distortive effects" on businesses in sectors outside the scheme's scope, where an eligible firm could pass savings through to its non-eligible activities and gain an advantage over competitors who get no support at all.` },
    { type: 'paragraph', text: `The mechanism meant to stop that has not actually been built.` },
    { type: 'paragraph', text: `Pro-rating support by the share of a firm's revenue or electricity use tied to eligible production is a proposal out for consultation, not a settled rule. The government has not yet decided whether it will pro-rate at all, or instead set a minimum threshold of "eligible activity" and give qualifying firms the full exemption regardless of their other output.` },
    { type: 'paragraph', text: `If ministers choose certain industries for lower electricity costs, firms just outside the boundary may reasonably ask why they are still paying the full rate, and for now there is no finished answer to that question.` },
    { type: 'heading', level: 2, text: `£600 million a year needs a measurable return` },
    { type: 'paragraph', text: `The scheme could run for close to a decade.` },
    { type: 'paragraph', text: `At around £600 million a year, the total support could run into several billion pounds over its lifetime, on top of the hundreds of millions already committed annually through the Supercharger.` },
    { type: 'paragraph', text: `That does not make it poor value.` },
    { type: 'paragraph', text: `If it keeps major manufacturers in Britain, secures investment and prevents industrial decline, the economic return could be substantial.` },
    { type: 'paragraph', text: `But that claim should be measured rather than assumed, and the government has had two and a half years with a comparable scheme in which it could have started measuring.` },
    { type: 'paragraph', text: `Government should be able to show how many firms received support; how much each sector saved; how much private investment followed; how many jobs were created or protected; whether production increased; and whether supported firms remained in Britain because of the scheme.` },
    { type: 'paragraph', text: `None of that evidence exists yet for the scheme already running. There is no reason to expect it will arrive faster for this one.` },
    { type: 'heading', level: 2, text: `The government is treating a symptom` },
    { type: 'paragraph', text: `There is a larger problem underneath the announcement.` },
    { type: 'paragraph', text: `British industrial electricity prices are high enough that ministers now believe direct intervention is necessary, for the second time in under three years.` },
    { type: 'paragraph', text: `The new scheme helps selected firms cope with that.` },
    { type: 'paragraph', text: `It does not explain why the underlying price problem exists, why the first attempt to fix it has not been evaluated, or when manufacturers will be able to compete without support.` },
    { type: 'paragraph', text: `That is the more uncomfortable question.` },
    { type: 'paragraph', text: `If the government believes British industry needs £600 million a year of relief on top of what it is already spending, the problem is bigger than one energy-bill scheme, and so is the government's obligation to show what the money has actually bought.` },
    { type: 'paragraph', text: `The subsidy may be justified.` },
    { type: 'paragraph', text: `But it should not be confused with a cure.` },
    { type: 'paragraph', text: `The saving is real.` },
    { type: 'paragraph', text: `So is the bill.` },
    { type: 'paragraph', text: `And so is the bill before it, which nobody has yet accounted for.` },
  ],
  evidence: {
    recordsReviewed: [
      'GOV.UK, 1 October 2026: "Applications open for scheme to slash electricity bills for over 10,000 manufacturers" — scheme overview, 10,000+ eligible firms, up to 25 per cent bill reduction, £600m/year value, Exchequer plus energy-system funding mechanism',
      'GOV.UK, Subsidy Advice Unit referral page for the British Industrial Competitiveness Scheme — formal subsidy-control documentation',
      'GOV.UK, "British Industrial Competitiveness Scheme: consultation on scheme eligibility and approach" — distortion-risk wording; pro-rating proposal as consultation (not final rule); 2035 end date with 2030 review',
      'Written Ministerial Statement, "British Industrial Competitiveness Scheme," 16 April 2026 — £40/MWh policy-cost relief figure; Renewables Obligation, Feed-in Tariffs, Capacity Market as relieved charges',
      'Government response to the BICS eligibility consultation, April 2026 — no quantified investment-impact estimate; qualitative "should result in increased investment and growth" expectation; Regulatory Policy Committee impact assessment promised for later in 2026 alongside supporting legislation',
      'Subsidy Advice Unit, final report on the British Industry Supercharger, pre-launch assessment — £320 to £410 million/year estimate; reliance on "anecdotal evidence" of relocation risk; no outcomes evaluation published',
      'Catalyst Commercial, British Industry Supercharger guidance — 1 April 2024 launch date; network-charging compensation increased from 60 per cent to 90 per cent from 1 April 2026',
    ],
    lastChecked: '1 October 2026',
  },
};

export default piece;
