import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'ms9k4qxw7n',
  kicker: 'Modern Slavery',
  headline: `Government Plans £1m Forced-Labour Reporting Fines. Companies Still Will Not Have to Check Their Supply Chains`,
  standfirst: `Companies that fail to comply with Britain's modern-slavery reporting rules could face substantial fines under legislation now before Parliament. The proposed rules are considerably tougher than the existing system. They still would not require a company to carry out human-rights due diligence on its supply chain. Under the Immigration and Asylum Bill, a business could state that it had carried out no assessment of whether forced labour risks existed, explain why it had not done so, and still comply with the reporting requirement.`,
  publishedAt: '2026-07-16',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `Companies that fail to comply with Britain's modern-slavery reporting rules could face substantial fines under legislation now before Parliament.` },
    { type: 'paragraph', text: `The proposed rules are considerably tougher than the existing system.` },
    { type: 'paragraph', text: `They still would not require a company to carry out human-rights due diligence on its supply chain.` },
    { type: 'paragraph', text: `Under the Immigration and Asylum Bill, a business could state that it had carried out no assessment of whether forced labour risks existed, explain why it had not done so and still comply with the reporting requirement.` },
    { type: 'paragraph', text: `It could likewise report that it had no due-diligence process and give its reasons.` },
    { type: 'paragraph', text: `The new offence is therefore not having forced labour somewhere in a supply chain, or even necessarily failing to investigate it. The proposed financial sanction is aimed at failing to comply with the strengthened disclosure rules.` },
    { type: 'paragraph', text: `That distinction goes to the centre of a debate which Parliament's Joint Committee on Human Rights has been having with the government for a year.` },
    { type: 'paragraph', text: `The committee concluded in July 2025 that transparency reporting had not prevented goods linked to forced labour from entering the British market. It called for a different system: mandatory human-rights due diligence, an import ban on goods linked to forced labour and a route for victims to bring claims against companies in British courts.` },
    { type: 'paragraph', text: `Those measures are not in the Immigration and Asylum Bill.` },
    { type: 'paragraph', text: `The bill instead strengthens section 54 of the Modern Slavery Act 2015, the existing transparency regime.` },
    { type: 'paragraph', text: `Section 54 currently applies to commercial organisations operating in Britain with annual turnover of at least £36 million. They must publish an annual slavery and human-trafficking statement.` },
    { type: 'paragraph', text: `The present law is unusually permissive. A company can comply by saying that it has taken no steps to ensure that slavery and human trafficking are absent from its business or supply chains.` },
    { type: 'paragraph', text: `There is no standard list of information every statement must contain and no requirement to produce evidence proving its claims. The Joint Committee said an independent review in 2019 estimated that about 40 per cent of eligible companies were not complying with the reporting requirement at all.` },
    { type: 'paragraph', text: `The Secretary of State can seek an injunction against a company that fails to comply. The committee found that power had never been used.` },
    { type: 'paragraph', text: `The new bill would close several of those gaps.` },
    { type: 'paragraph', text: `Statements would have to contain information about an organisation's structure, operations and supply chains. They would have to identify parts of the business where forced-labour risks exist, as far as that information is reasonably available, and describe steps taken to assess and reduce those risks.` },
    { type: 'paragraph', text: `Companies would have to describe their policies, any due-diligence processes they had implemented, staff training and how effective they believed their actions had been.` },
    { type: 'paragraph', text: `Senior figures would also have to certify the statement and declare that it was accurate to the best of their knowledge and belief.` },
    { type: 'paragraph', text: `The duty would also be extended beyond companies.` },
    { type: 'paragraph', text: `Public authorities above a budget threshold to be set by ministers would have to publish equivalent statements. That would extend the section 54-style reporting regime into parts of the public sector for the first time, although other modern-slavery rules already apply to areas of public procurement.` },
    { type: 'paragraph', text: `The most obvious change is enforcement.` },
    { type: 'paragraph', text: `The bill gives the Secretary of State power to create a financial-penalty system for organisations which, without reasonable excuse, fail to comply with the reporting duties.` },
    { type: 'paragraph', text: `The maximum permitted by those future regulations would be the higher of £1 million or 1 per cent of the organisation's turnover. For a public authority, the percentage would apply to its budget.` },
    { type: 'paragraph', text: `That means the ceiling could exceed £1 million for a sufficiently large organisation.` },
    { type: 'paragraph', text: `But the bill does not itself issue those fines. It gives ministers power to make further regulations establishing the penalty regime, including who will enforce it, how amounts will be decided and how appeals will work.` },
    { type: 'paragraph', text: `The relevant provisions would also come into force on dates appointed by the Secretary of State.` },
    { type: 'paragraph', text: `Lord David Alton, chair of the Joint Committee on Human Rights, welcomed the changes on 15 July.` },
    { type: 'paragraph', text: `He said the bill implemented three recommendations made by the committee last year: stronger reporting requirements, penalties for non-compliance and extension of the reporting duty to public bodies.` },
    { type: 'paragraph', text: `He warned organisations not to treat compliance as "simply a rubber stamping exercise".` },
    { type: 'paragraph', text: `The bill does remove the present ability to file one short declaration saying that no action has been taken.` },
    { type: 'paragraph', text: `What replaces it, however, remains a disclosure regime rather than a mandatory prevention regime.` },
    { type: 'paragraph', text: `Schedule 5 expressly allows an organisation to say that it has not assessed whether forced-labour risks exist and explain why.` },
    { type: 'paragraph', text: `It can state that it has implemented no due-diligence process and explain why.` },
    { type: 'paragraph', text: `It can say it provided no modern-slavery training and explain why.` },
    { type: 'paragraph', text: `It can also state that it has not assessed whether its efforts to prevent slavery were effective, again providing reasons.` },
    { type: 'paragraph', text: `Those answers would be less comfortable to publish than today's blanket declaration. Investors, customers, campaigners and public bodies would be able to see more clearly what a company had not done.` },
    { type: 'paragraph', text: `But the legislation does not turn each of those missing actions into a breach in its own right.` },
    { type: 'paragraph', text: `The Joint Committee drew precisely this distinction in its 2025 report.` },
    { type: 'paragraph', text: `It described transparency reporting as a passive process in which organisations state publicly what they have done.` },
    { type: 'paragraph', text: `Human-rights due diligence is different. It requires companies proactively to investigate risk and try to prevent harm, potentially through supplier conditions, risk assessments and audits.` },
    { type: 'paragraph', text: `The committee concluded that relying on voluntary due diligence was not effectively tackling forced labour and recommended making it compulsory throughout supply chains.` },
    { type: 'paragraph', text: `The government did not accept that recommendation at the time.` },
    { type: 'paragraph', text: `Its formal response in October said mandatory due diligence would be considered as part of a wider review of responsible business conduct.` },
    { type: 'paragraph', text: `The government gave a similar answer when the committee called for goods produced with forced labour to be prohibited from entering Britain.` },
    { type: 'paragraph', text: `It said an import ban was under consideration rather than committing to one.` },
    { type: 'paragraph', text: `The committee's proposal for a civil "failure to prevent forced labour" action, allowing victims to seek compensation from companies, was also left for the review.` },
    { type: 'paragraph', text: `Nine months later, the Immigration and Asylum Bill has brought forward the committee's recommendations on reporting.` },
    { type: 'paragraph', text: `It has not brought forward those wider proposals.` },
    { type: 'paragraph', text: `Reporting becomes useful only once somebody can establish what is actually happening further down a supply chain.` },
    { type: 'paragraph', text: `The limits of Britain's existing enforcement system are visible in a case involving cotton from Xinjiang.` },
    { type: 'paragraph', text: `In June 2024, the Court of Appeal ruled that the National Crime Agency had misunderstood the law when it decided not to investigate whether cotton products imported from the Xinjiang Uyghur Autonomous Region could constitute criminal property under the Proceeds of Crime Act.` },
    { type: 'paragraph', text: `The court rejected the idea that investigators first had to identify a specific item of criminal property before opening an investigation. It also held that paying market value for goods did not automatically cleanse property produced through criminal conduct further down a supply chain.` },
    { type: 'paragraph', text: `The decision was sent back to the NCA for reconsideration.` },
    { type: 'paragraph', text: `More than two years later, Parliament was still waiting for that reconsideration.` },
    { type: 'paragraph', text: `On 15 July, Alton wrote to NCA director general Graeme Biggar saying that, as far as the committee was aware, the agency had still not made a fresh decision on whether to investigate.` },
    { type: 'paragraph', text: `The committee asked the NCA to explain when it would decide and whether it planned any other action to address the risk of forced-labour goods entering Britain.` },
    { type: 'paragraph', text: `The letter does not establish that any particular British company knowingly imported or sold goods produced through forced labour.` },
    { type: 'paragraph', text: `It establishes something narrower.` },
    { type: 'paragraph', text: `A court found in June 2024 that the NCA's original refusal to investigate cotton imports had been based on misunderstandings of the law. By 15 July 2026, the parliamentary committee monitoring the issue said it was still unaware of a replacement decision.` },
    { type: 'paragraph', text: `On the same day, the Home Office gave another indication of the limits of the system.` },
    { type: 'paragraph', text: `Asked about shipping data which could help expose forced labour in supply chains, it said it received some manifest information but had no plans to publish detailed records because of legal, personal-data and commercial-sensitivity concerns.` },
    { type: 'paragraph', text: `It added that the Home Office "does not routinely assess whether goods entering the UK may have been produced using forced labour", although it shares relevant intelligence with law-enforcement and other government partners when information is identified.` },
    { type: 'paragraph', text: `The government's case for the reporting reforms is still substantial.` },
    { type: 'paragraph', text: `At present a large company can comply with section 54 by admitting it has done nothing. Some eligible companies do not file statements at all. There is no routine financial penalty. Statements vary in content and quality.` },
    { type: 'paragraph', text: `The Immigration and Asylum Bill would make those disclosures more detailed, force organisations to explain areas of inaction and create the machinery for substantial penalties.` },
    { type: 'paragraph', text: `It would also bring qualifying public authorities into the same reporting system.` },
    { type: 'paragraph', text: `Those are material changes.` },
    { type: 'paragraph', text: `They do not implement the more fundamental recommendation made by the Joint Committee last year: that companies should be legally required to investigate and address forced-labour risks rather than merely provide a fuller account of what they chose to do.` },
    { type: 'paragraph', text: `Under the bill as introduced, a company could still tell the government that it carried out no forced-labour risk assessment and no human-rights due diligence.` },
    { type: 'paragraph', text: `It would just have to say so properly.` },
  ],
  evidence: {
    recordsReviewed: [
      `Immigration and Asylum Bill, Bill 105, introduced 30 June 2026, clauses 44–49 and Schedule 5: the proposed mandatory content of modern-slavery statements, extension to qualifying public authorities, certification requirements, the ability to report that no risk assessment or due-diligence process was undertaken, and the power to introduce financial penalties capped at the higher of £1 million or 1 per cent of turnover or budget`,
      `Immigration and Asylum Bill, clause 52: the reporting and enforcement provisions do not automatically commence on Royal Assent and may be brought into force by regulations on dates appointed by the Secretary of State`,
      `Joint Committee on Human Rights, Forced Labour in the UK's Supply Chains, Sixth Report of Session 2024–25, HC 633 / HL Paper 159, 24 July 2025: the £36 million existing threshold, the ability under current law to report that no steps were taken, the committee's citation of the 2019 independent review's estimate of non-compliance, the distinction between transparency reporting and human-rights due diligence, and recommendations for mandatory due diligence, import restrictions and access to justice`,
      `Independent Review of the Modern Slavery Act 2015, final report, 2019: the original estimate that around 40 per cent of eligible companies were not complying with section 54, and the finding that the Secretary of State's injunction power had not been used and no penalties had been issued`,
      `Joint Committee on Human Rights, "Chair welcomes stronger forced labour supply chain safeguards in Immigration and Asylum Bill", 15 July 2026: Lord Alton's welcome for the three reporting reforms, his warning against treating them as a rubber-stamping exercise and the committee's statement that its wider recommendations on mandatory due diligence and access to justice remain separate`,
      `Government response to the Joint Committee on Human Rights report, HC 1404, 16 October 2025: the government's decision to consider mandatory human-rights due diligence, a forced-labour import ban and a civil failure-to-prevent action through its Responsible Business Conduct Review rather than commit to them in its response`,
      `Court of Appeal, R (World Uyghur Congress) v National Crime Agency [2024] EWCA Civ 715, 27 June 2024: the ruling that the NCA's earlier decision on whether to investigate cotton imports was based on errors of law and that the decision had to be reconsidered`,
      `Lord Alton to Graeme Biggar, Director General of the National Crime Agency, 15 July 2026: the committee's statement that, more than two years after the Court of Appeal judgment, it was unaware of a fresh NCA decision on whether to investigate, and its request for a timetable and details of other action on forced-labour imports`,
      `Home Office written answers HL1647 and HL1648, tabled by Lord Alton on 6 July 2026 and answered by Lord Hanson on 15 July 2026: the government's position on shipping-manifest data and its statement that the Home Office does not routinely assess whether imported goods may have been produced using forced labour`,
    ],
    lastChecked: '4 October 2026',
  },
};

export default piece;
