import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'nh4k9mxw7r',
  kicker: 'Health',
  headline: `Government Hails £1.5bn NHS Investment as Its Own Figures Show a £15.9bn Repair Backlog`,
  standfirst: `The government announced more than £1.5 billion for NHS buildings on 9 September, describing the package as investment in safer, more resilient hospitals. Around £1.3 billion of the total is for maintenance, safety and resilience work on an estate carrying a repair backlog of £15.9 billion, more than triple the £4.9 billion recorded in 2015/16. The money comes from the existing £6.75 billion Estates Safety Fund already announced as part of the health capital settlement, not a separate September allocation.`,
  publishedAt: '2026-09-09',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `The government has announced more than £1.5 billion for NHS buildings, saying the money will make hospitals safer, more resilient and better equipped.` },
    { type: 'paragraph', text: `Most of it is not new capacity.` },
    { type: 'paragraph', text: `Around £1.3 billion is being used for maintenance, safety and resilience work on an NHS estate carrying a repair backlog of £15.9 billion.` },
    { type: 'paragraph', text: `That backlog has more than tripled from £4.9 billion in 2015/16 to £15.9 billion in 2024/25, and the government's own capital plan says the highest-risk categories within that backlog are the ones growing fastest.` },
    { type: 'paragraph', text: `The government's own ten-year capital plan says there were more than 4,100 incidents of service disruption caused by estates failures in 2024/25, including electrical problems, water ingress and fire-safety issues severe enough to close wards.` },
    { type: 'paragraph', text: `So the central fact is not simply that ministers are investing £1.5 billion.` },
    { type: 'paragraph', text: `It is that the NHS estate has accumulated a maintenance problem roughly ten times larger, and the parts of that problem getting worse fastest are the most dangerous ones.` },
    { type: 'paragraph', text: `There is a sound case for the spending. Hospitals cannot function safely if roofs leak, electrical systems fail or wards have to close because buildings are no longer fit for use.` },
    { type: 'paragraph', text: `But maintenance spending should be described as maintenance spending.` },
    { type: 'paragraph', text: `It is not the same thing as building new hospitals, adding beds or expanding clinical capacity.` },
    { type: 'paragraph', text: `The distinction matters because the government's announcement groups all of that activity under the broad language of investment.` },
    { type: 'paragraph', text: `The largest share, £1.3 billion of the roughly £1.53 billion total, is going on keeping the existing estate working.` },
    { type: 'paragraph', text: `The remainder is split between £32 million for cooling, ventilation and heat-resilience work, and £200 million for ten named "major projects." Even that smaller, more capacity-sounding slice turns out to be mostly about the same underlying problem. Of the ten projects, several are explicitly framed by the government as replacing failing or obsolete buildings rather than adding net capacity: £26 million at Stepping Hill Hospital in Stockport for a new pathology building "to protect the testing services doctors rely on," £25 million at Wycombe Hospital for a new clinical building that will "allow services to move out of an ageing tower," and £1 million at Southend Hospital for planning work toward replacing another ageing tower. A smaller number represent genuine additions, including new operating theatres at Bristol Royal Infirmary and the Royal Free, a new children's ward at Lister Hospital, and 14 new mental health bedrooms in Essex, but even by the government's own project-by-project description, replacement and resilience work dominates the "major projects" line as much as it dominates the headline £1.3 billion.` },
    { type: 'paragraph', text: `The money is also not a separate £1.5 billion Treasury allocation created in September.` },
    { type: 'paragraph', text: `The Department of Health says the package comes from the existing £6.75 billion Estates Safety Fund, which had already been announced as part of the government's wider health capital settlement.` },
    { type: 'paragraph', text: `That means the September announcement is mainly about allocating part of an existing funding envelope.` },
    { type: 'paragraph', text: `It does not represent another £1.5 billion added on top.` },
    { type: 'paragraph', text: `There is another qualification.` },
    { type: 'paragraph', text: `The government says more than 950 projects are involved.` },
    { type: 'paragraph', text: `But the published list is described as an initial set approved to move into detailed design, with the government itself saying "more schemes will be confirmed in future as NHS investment plans are finalised."` },
    { type: 'paragraph', text: `Some projects still require further business-case approval before final scope and cost are settled.` },
    { type: 'paragraph', text: `So "950 projects funded" would go too far.` },
    { type: 'paragraph', text: `Some have been given permission to progress.` },
    { type: 'paragraph', text: `That is not the same thing as completed work.` },
    { type: 'paragraph', text: `The condition of the estate explains why ministers are having to spend this money at all.` },
    { type: 'paragraph', text: `Government figures show the maintenance backlog has climbed steadily for years.` },
    { type: 'paragraph', text: `A growing share is categorised as high or significant risk, meaning the work is no longer cosmetic, and the government's own data shows that growth is concentrated precisely in those highest-risk categories.` },
    { type: 'paragraph', text: `Delayed maintenance can affect patient safety, infection control, heating, ventilation and the basic ability of hospitals to keep services open.` },
    { type: 'paragraph', text: `The ten-year capital plan acknowledges that estates failures are already causing disruption, recording over 4,100 such incidents in a single year.` },
    { type: 'paragraph', text: `That is the uncomfortable backdrop to the latest announcement.` },
    { type: 'paragraph', text: `The government is not simply modernising hospitals.` },
    { type: 'paragraph', text: `It is trying to catch up with years of deferred maintenance, using money that was committed before this announcement and the clearest new elements of which are, on the government's own account, still mostly about replacing buildings that are failing rather than expanding what the NHS can do.` },
    { type: 'paragraph', text: `That does not make the programme poor value.` },
    { type: 'paragraph', text: `It makes the presentation important.` },
    { type: 'paragraph', text: `If £1.3 billion is being spent because buildings are unsafe, unreliable or overdue for repair, that is the story.` },
    { type: 'paragraph', text: `Calling all of it an "investment" risks making remedial spending sound like expansion.` },
    { type: 'paragraph', text: `The public should also be able to see whether the backlog actually falls.` },
    { type: 'paragraph', text: `That gives the programme a straightforward test.` },
    { type: 'paragraph', text: `How much of the £15.9 billion backlog is removed? How many high-risk defects are cleared? How many estates-related service disruptions occur next year? And how much of the money goes on fixing existing failures rather than adding new capacity, including within the ten "major projects," where the government's own descriptions suggest replacement is still doing most of the work?` },
    { type: 'paragraph', text: `Those figures will tell us more than the size of the original announcement.` },
    { type: 'paragraph', text: `The NHS needs the repairs.` },
    { type: 'paragraph', text: `What it does not need is maintenance being mistaken for transformation.` },
  ],
  evidence: {
    recordsReviewed: [
      'Department of Health, "Over £1.5 billion to help NHS withstand year-round pressure," 9 September 2026 — £1.5bn+ total, £1.3bn maintenance/safety/resilience figure, £32m heat-resilience allocation, £200m/10-project breakdown (Stepping Hill £26m, Bristol Royal Infirmary £41m, Queen Elizabeth Hospital Gateshead £12m, Wycombe Hospital £25m, Crystal Centre/Linden Centre Essex £15m, Lister Hospital £11m, Southend Hospital £1m, St George\'s Hospital Stafford £25m, Royal Free Hospital £32m, John Howard Centre £25m), £6.75bn Estates Safety Fund as funding source, 950+ projects "approved to proceed to detailed design stage" wording',
      'Government, 10-year capital plan for health and social care — £15.9bn repair backlog in 2024/25, £4.9bn figure for 2015/16, more-than-tripling of the backlog, highest-risk categories growing most rapidly, 4,100+ service disruption incidents from estates failures (fire safety, electrical infrastructure, water ingress) in 2024/25',
    ],
    lastChecked: '9 September 2026',
  },
};

export default piece;
