import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'nq7x4km2wp',
  kicker: 'Housing',
  headline: `Regulator Calls £54.7bn of Social Housing Finance 'New Borrowing'. Its Own Report Says Much of It Is Refinancing.`,
  standfirst: `England's large social landlords expect to spend £59 billion repairing and maintaining existing homes over the next five years while increasing development. The Regulator of Social Housing's press release describes £54.7 billion as "new borrowing". Its own report says a substantial part of that sum replaces existing loans as they mature.`,
  publishedAt: '2026-10-06',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `England's large social landlords expect to spend £59 billion repairing and maintaining existing homes over the next five years while increasing the number of new homes in their development plans.` },
    { type: 'paragraph', text: `Paying for it will require substantially more debt.` },
    { type: 'paragraph', text: `The Regulator of Social Housing forecasts that debt drawn and repayable across the sector will reach £133.2 billion by 2031, £9 billion higher than landlords forecast for the same year in their previous plans, a 7 per cent increase. Debt relative to turnover has increased from 3.9 times to 4.0 times.` },
    { type: 'paragraph', text: `The regulator's press release describes another figure prominently: "£54.7bn of new borrowing" required over the first five years.` },
    { type: 'paragraph', text: `Its underlying report describes that figure differently. The £54.7 billion is the value of new financing facilities landlords expect to raise. Those facilities include loans replacing existing borrowing as it reaches maturity. Landlords also expect to make £34.7 billion of loan repayments during the same period. The regulator concludes that at least £20 billion of the £54.7 billion represents additional borrowing to finance new expenditure.` },
    { type: 'paragraph', text: `Refinancing £1 billion of debt that already exists and borrowing another £1 billion are not the same thing. The press release does not make that distinction. It calls the full £54.7 billion "new borrowing". The regulator's own report, in the section setting out the financing facilities landlords expect to raise, says some of it replaces existing facilities.` },
    { type: 'paragraph', text: `The sector will still become considerably more indebted. Debt forecast for 2031 has risen from £124.2 billion in last year's plans to £133.2 billion in the latest set. The regulator says this is a larger increase than seen in recent forecasts and reflects, in part, the money required for higher development.` },
    { type: 'paragraph', text: `There is also considerably more spending behind the borrowing. Landlords forecast £59 billion of repairs and maintenance expenditure over five years, up from £54 billion in the previous plans. The regulator says that is an 8 per cent nominal increase and about 5 per cent in real terms.` },
    { type: 'paragraph', text: `They expect to complete 285,000 new homes during the same period, 11,000 more than forecast last year, although still fewer than the 292,000 included in the 2024 plans and 321,000 in the 2023 plans.` },
    { type: 'paragraph', text: `General-needs Social Rent homes increase from about 63,000 in last year's forecasts to 101,000. Affordable Rent falls from 97,000 to 68,000. Planned market-sale and other non-social rented homes continue to decline. "Record investment" should not be read as record housebuilding. The record is in spending on existing homes. Development has recovered modestly from last year but remains below earlier plans.` },
    { type: 'paragraph', text: `More government grant is helping to support the programme. Landlords forecast net grant receipts of £16.3 billion over five years, £6.8 billion more than in the previous forecasts, a 72 per cent increase. The regulator says the increase will largely reflect bids under the £39 billion Social and Affordable Homes Programme.` },
    { type: 'paragraph', text: `Those forecasts were drawn up before the first allocations were known. In August, the government announced nearly £10 billion for the first wave of the programme, intended to support more than 70,000 homes through councils, housing associations and other providers. The regulator says future business plans will have to be revised to reflect which bids actually succeeded.` },
    { type: 'paragraph', text: `The extra investment is therefore being supported by a combination of grant, borrowing and higher rental income. Social housing rents can now generally increase by CPI plus one percentage point a year under the government's ten-year rent settlement. September 2025 CPI was 3.8 per cent, allowing landlords to increase affected rents by up to 4.8 per cent in the first year of these forecasts. Landlords do not have to impose the maximum increase.` },
    { type: 'paragraph', text: `From April 2027, landlords with some Social Rent properties below formula rent will also be able to increase those rents by up to an additional £1 a week. That allowance rises to £2 from April 2028 until formula rent is reached.` },
    { type: 'paragraph', text: `The regulator says the higher-than-previously-assumed rent increase and rent convergence have improved forecast operating margins. Rental income per home is expected to reach about £8,000 by 2031, compared with £7,700 in the previous forecasts.` },
    { type: 'paragraph', text: `That has helped stop one important financial measure deteriorating further. The regulator uses EBITDA MRI interest cover to measure the extent to which operating income covers financing costs after repairs and maintenance spending. Across the sector, average interest cover over the first five forecast years is 106.6 per cent. The equivalent figure in the previous plans was 106.4 per cent. The regulator describes the latest figures as indicating that the financial position "may be beginning to stabilise" after several years in which successive forecasts became weaker.` },
    { type: 'paragraph', text: `Last year, the regulator noted that landlords' business plans routinely predicted improving interest cover later in their forecast periods, but that "historically the forecast improvements have not subsequently been achieved." The current plans again expect interest cover to improve, from 88 per cent in 2027 to 117 per cent by 2031. Whether that improvement materialises will not be known for years.` },
    { type: 'paragraph', text: `The largest housing associations have the least headroom. Twenty providers owning more than 40,000 social homes each account for 45 per cent of the homes in the regulator's dataset and half its turnover. Their average five-year interest cover is 101.9 per cent, compared with 106.6 per cent across the sector. At 100 per cent, operating earnings after repairs would equal financing costs under this measure.` },
    { type: 'paragraph', text: `Those large landlords also forecast the highest repair costs, averaging £4,638 per home each year, including £562 for building and fire-safety work. The regulator says this partly reflects their concentration in London and the South East and their greater exposure to high-rise buildings.` },
    { type: 'paragraph', text: `The forecasts were largely prepared in early 2026 and submitted in June. The regulator explicitly says business plans "should not therefore be seen as predictions of the future." Its modelling using more recent interest-rate assumptions produces around £640 million of additional financing costs over five years and could reduce sector interest cover by up to 3.3 percentage points. More recent inflation forecasts work in the other direction: substituting those assumptions could improve cashflow by about £2.5 billion and lift interest cover by as much as 11 percentage points, because rents are linked to inflation as well as landlords' costs.` },
    { type: 'paragraph', text: `Providers currently plan 434,000 social and low-cost home ownership properties over the ten years to 2036, 27 per cent more than in the previous forecasts. But most of the later programme has not been contracted. The proportion committed falls from 87 per cent of homes planned for 2027 to 34 per cent in 2029, 6 per cent in 2032 and just 1 per cent in each of 2035 and 2036. The regulator says the ability to delay or cancel development programmes is a mitigation providers cite in their own stress-testing, to protect their financial position if conditions deteriorate.` },
    { type: 'paragraph', text: `And the £54.7 billion described publicly as "new borrowing" is not £54.7 billion of additional debt. The regulator's own report says a substantial part of it is refinancing existing loans.` },
  ],
  evidence: {
    recordsReviewed: [
      `Regulator of Social Housing, 2026 Financial Forecasts of Private Registered Providers, 6 October 2026: primary source for debt, financing facilities, loan repayments, development, repairs, grant, interest cover, rent assumptions, provider segmentation, economic sensitivity modelling and contractual commitments, including the £54.7bn new-facilities figure, the £34.7bn loan repayments figure and the "at least £20bn" new-borrowing conclusion in its financing section, and the quote that the financial position "may be beginning to stabilise"`,
      `Regulator of Social Housing, "Social housing landlords to invest record amounts in repairs and new homes", 6 October 2026: uses the wording "£54.7bn of new borrowing" without distinguishing refinancing from additional borrowing`,
      `Regulator of Social Housing, 2025 Financial Forecasts of Private Registered Providers, 15 January 2026: previous forecast set, including the £124.2bn 2031 debt figure, the 106.4 per cent five-year interest-cover figure, the £54bn repairs spending figure and the regulator's warning that forecast improvements in interest cover had historically not subsequently been achieved`,
      `Regulator of Social Housing, Rent Standard 2026, 2 February 2026: confirms the ten-year settlement under which social landlords may generally increase Social Rent and Affordable Rent by up to CPI plus one percentage point annually`,
      `Ministry of Housing, Communities and Local Government, Social Rent convergence outcome, 2026: confirms the additional weekly convergence increases permitted from April 2027 for Social Rent properties below formula rent`,
      `Ministry of Housing, Communities and Local Government, first Social and Affordable Homes Programme allocations, 24 to 25 August 2026: confirms nearly £10 billion in initial allocations intended to support more than 70,000 homes within the wider £39 billion programme`,
    ],
    lastChecked: '6 October 2026',
  },
};

export default piece;
