import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'pb4k9mxw7r',
  kicker: 'Economic Crime',
  headline: `Government Adds 500 More Economic Crime Officers Without a Recovery Target to Match`,
  standfirst: `Home Secretary Shabana Mahmood announced on 15 September that the government will fund more than 500 additional enforcement specialists for economic crime, as part of a £550 million anti-money laundering and asset recovery strategy covering 2026 to 2029. The strategy does not attach a number to how much extra criminal money the new investment is expected to recover.`,
  publishedAt: '2026-09-15',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `Home Secretary Shabana Mahmood announced on 15 September that the government will fund more than 500 additional enforcement specialists for economic crime, as part of a £550 million anti-money laundering and asset recovery strategy covering 2026 to 2029. "We are putting 500 more officers on the trail of dirty money, going after the criminal bosses behind organised crime and stripping them of the funds they use to fuel drug trafficking, people smuggling and other serious crime," she said.` },
    { type: 'paragraph', text: `Of the £550 million, £520 million comes from the Economic Crime Levy, paid by businesses already regulated under anti-money laundering rules. A further £30 million comes from a high-streets package announced at Budget 2025. The strategy's stated goals are recovering more criminal assets, dismantling more laundering networks and improving prosecutions, intelligence and supervision.` },
    { type: 'paragraph', text: `The strategy does not attach a number to any of those goals. It lists assets recovered as one of the indicators that will be monitored, but does not state how large an increase would count as success. A Theory of Change and outcomes framework, including indicators for the new measures, is still being developed and will be produced later, alongside promised mid-point and final progress reports.` },
    { type: 'paragraph', text: `The previous economic crime plan took a different approach. When Economic Crime Plan 2 launched in March 2023, the Home Office and HM Treasury announced £400 million — £200 million from government, £200 million from the levy — and an uplift of 475 financial-crime investigators, tied to a specific ten-year objective: recover an additional £1 billion in criminal assets.` },
    { type: 'paragraph', text: `The new strategy says 99 per cent of those 475 posts have now been recruited. The Home Office has not yet published a process evaluation of what that staffing uplift achieved; the strategy says the evaluation is due later in 2026. A progress report from September 2025 said the department was still exploring whether an impact evaluation could establish what measurable changes, if any, were caused by the additional staff. The government is adding a further 500 enforcement specialists before that question about the first 475 has been answered.` },
    { type: 'paragraph', text: `Asset recovery has risen in the period since the 2023 plan. Official statistics for 2025/26 show £345.3 million recovered through confiscation, forfeiture and civil recovery powers, 20 per cent more than the previous year and 29 per cent higher in real terms than in 2020/21.` },
    { type: 'paragraph', text: `That total is not evenly spread across the three powers. Forfeiture receipts rose 28 per cent to £155.9 million. Civil recovery rose from £7.5 million to £38.5 million. Confiscation receipts, the largest single category, fell 5 per cent to £150.9 million.` },
    { type: 'paragraph', text: `A further £1.1 billion of assets was denied to criminals during the year, including £677 million under restraint orders and £376.4 million seized or frozen under forfeiture powers. That money was not accessible to criminals while legal processes continued, but it is not the same as money recovered by the state, and the Home Office itself cautions against treating the two figures as interchangeable.` },
    { type: 'paragraph', text: `Victims received £26.1 million through confiscation-order proceeds in 2025/26, 45 per cent less than the previous year, though still above the six-year median. The figure covers only compensation paid through confiscation receipts, not every form of criminal-justice compensation.` },
    { type: 'paragraph', text: `The National Crime Agency assesses that it is a realistic possibility that more than £100 billion is laundered through or within the UK, or through UK-registered corporate structures, each year. A separate Home Office analysis published alongside the new strategy puts the identified proceeds of certain profit-driven crimes in England and Wales in 2023/24 at least £21.9 billion. The Home Office says explicitly that this second figure should not be used as a measure of anti-money laundering performance or treated as an estimate of assets available to be recovered, since criminal proceeds may already have been spent, moved overseas, concealed or otherwise placed beyond reach.` },
    { type: 'paragraph', text: `Part of the £550 million is funded through changes to the Economic Crime Levy that took effect in April 2026. Firms with UK revenues above £1 billion moved from a £500,000 to a £1 million annual charge. A new £500,000 band was introduced for businesses with revenues between £500 million and £1 billion. Treasury estimates these changes will raise an additional £110 million in 2027/28 and around £115 million a year after that — revenue from the rate change itself, not the total £520 million the strategy draws from the levy.` },
    { type: 'paragraph', text: `Some recovered money already returns to enforcement. In 2025/26, £129.6 million was distributed to Proceeds of Crime Act agencies through the Asset Recovery Incentivisation Scheme, with a further £12.8 million awarded to 18 projects through its central funding pot.` },
    { type: 'paragraph', text: `The strategy sets out detailed delivery milestones for individual reforms and says tracking will tighten once the outcomes framework is built, with a progress report at the programme's midpoint and another at its end. What it does not yet say is how much higher than £345.3 million the government expects annual recovery to be by 2029, or what scale of change in the 475-officer uplift's results would justify the judgment that a further 500 specialists are worth the money.` },
  ],
  evidence: {
    recordsReviewed: [
      `Home Office and HM Treasury, "Anti-money laundering and asset recovery strategy: 2026 to 2029", 15 September 2026: the £550 million total, the £520 million Economic Crime Levy and £30 million high-streets funding, the 500 additional officers, the strategy's objectives, the absence of a quantified recovery target, the 99 per cent recruitment claim for the 2023 posts, and the planned Theory of Change, outcomes framework and progress reports`,
      `Home Secretary Shabana Mahmood, statement accompanying the strategy's publication, 15 September 2026: ministerial quote and personal attribution of the announcement`,
      `Home Office and HM Treasury, "New plan puts UK at the forefront of fight against economic crime", 30 March 2023: the Economic Crime Plan 2 commitment of £400 million (£200 million government, £200 million levy), 475 additional investigators, and the ten-year £1 billion recovery target`,
      `Home Office, Economic Crime Plan 2 outcomes progress report, 2 September 2025: status of the 475-post staffing programme and the department's statement that it was still exploring whether an impact evaluation could attribute measurable outcomes to the uplift`,
      `Home Office, Asset Recovery Statistics: financial years ending 2021 to 2026, published 10 September 2026, updated 15 September 2026: the £345.3 million total recovered, the confiscation, forfeiture and civil-recovery breakdown, the £1.1 billion denied and its components, victim compensation figures, ARIS distributions, and the real-terms comparison with 2020/21`,
      `Home Office, "The proceeds of crime in England and Wales 2023 to 2024", September 2026: the £21.9 billion estimate and the department's explicit statement that it should not be used as a measure of anti-money laundering performance or as an estimate of recoverable assets`,
      `National Crime Agency, National Strategic Assessment 2024: the assessment that more than £100 billion is laundered through or within the UK, or UK-registered corporate structures, each year`,
      `HM Revenue & Customs, "Economic Crime Levy: changes to bands and charges", updated 21 January 2026: the levy band changes, the April 2026 effective date, and Treasury's revenue estimates for the rate change`,
    ],
    lastChecked: '3 October 2026',
  },
};

export default piece;
