import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'pb4k9mxw7r',
  kicker: 'Economic Crime',
  headline: `UK Will Spend £500m More Fighting Dirty Money, but Government Has Set No Public Recovery Target`,
  standfirst: `The government is committing more than £500 million over three years to financial-crime enforcement and recruiting 500 additional officers. In 2025/26, authorities recovered £345.3 million in criminal assets, up 20 per cent on the year before. The government has published no target for what the new investment is expected to return.`,
  publishedAt: '2026-09-15',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `The government is committing more than £500 million over three years to financial-crime enforcement and recruiting 500 additional officers across police forces, the National Crime Agency and Crown Prosecution Service.` },
    { type: 'paragraph', text: `But it has not published a clear cash-recovery target showing what that investment is expected to deliver.` },
    { type: 'paragraph', text: `The gap matters because the scale of the problem is enormous.` },
    { type: 'paragraph', text: `The government says more than £100 billion is laundered through the UK or UK corporate structures every year.` },
    { type: 'paragraph', text: `Against that, authorities recovered £345.3 million in criminal assets in 2025/26.` },
    { type: 'paragraph', text: `Those two figures are not directly comparable.` },
    { type: 'paragraph', text: `The £100 billion estimate covers suspected annual money-laundering activity, while the £345.3 million recovery figure includes assets from a wider range of crimes and cases that may stretch back years.` },
    { type: 'paragraph', text: `But they show why the announcement needs a harder test than "more officers".` },
    { type: 'paragraph', text: `The real question is what measurable improvement the extra £500 million is supposed to buy.` },
    { type: 'heading', level: 2, text: `The money will come from a higher levy on regulated businesses` },
    { type: 'paragraph', text: `The £500 million is not simply coming from general taxation.` },
    { type: 'paragraph', text: `It will be funded through the Economic Crime Levy, which is paid by businesses already regulated under anti-money-laundering rules.` },
    { type: 'paragraph', text: `That includes banks, financial firms, accountancy businesses, law firms, estate agents and crypto businesses.` },
    { type: 'paragraph', text: `The government increased the levy from April 2026.` },
    { type: 'paragraph', text: `Businesses with UK revenues above £1 billion now face an annual charge of £1 million, double the previous £500,000 rate.` },
    { type: 'paragraph', text: `A new £500,000 band has also been created for businesses with revenues between £500 million and £1 billion.` },
    { type: 'paragraph', text: `The Treasury estimates the changes will raise an extra £110 million in 2027/28 and about £115 million a year in each year after that.` },
    { type: 'paragraph', text: `So the announcement is also a tax-and-enforcement story.` },
    { type: 'paragraph', text: `The government is increasing the cost imposed on regulated businesses in order to expand the financial-crime system.` },
    { type: 'paragraph', text: `That may be justified.` },
    { type: 'paragraph', text: `But it makes the absence of a measurable outcome target harder to ignore.` },
    { type: 'heading', level: 2, text: `Asset recovery has improved` },
    { type: 'paragraph', text: `The latest figures are not all bad.` },
    { type: 'paragraph', text: `Authorities recovered £345.3 million in 2025/26, up 20 per cent on the previous year.` },
    { type: 'paragraph', text: `In nominal terms, recoveries were 57 per cent higher than in 2020/21. In real terms, the government's own statistics record a 29 per cent increase over the same period, from £272.4 million to £352.2 million at 2026/27 prices.` },
    { type: 'paragraph', text: `The total included:` },
    { type: 'paragraph', text: `£150.9 million from confiscation orders.` },
    { type: 'paragraph', text: `£155.9 million from forfeiture, up 28 per cent year-on-year.` },
    { type: 'paragraph', text: `£38.5 million from civil recovery, a fivefold increase on the previous year's £7.5 million.` },
    { type: 'paragraph', text: `Bank-account forfeiture rose sharply, from £65 million to £100.4 million in one year.` },
    { type: 'paragraph', text: `That gives the government a reasonable argument that stronger enforcement is already producing results.` },
    { type: 'paragraph', text: `The harder question is whether the next £500 million produces a return on the same scale.` },
    { type: 'heading', level: 2, text: `Confiscation went backwards` },
    { type: 'paragraph', text: `Not every part of the system improved.` },
    { type: 'paragraph', text: `Confiscation receipts fell from £158 million in 2024/25 to £150.9 million in 2025/26, a decline of 5 per cent.` },
    { type: 'paragraph', text: `The overall rise in asset recovery came from forfeiture and civil recovery instead.` },
    { type: 'paragraph', text: `That distinction matters because the government tends to present one large recovery number.` },
    { type: 'paragraph', text: `Underneath it, performance varies depending on the legal route used to take the assets.` },
    { type: 'heading', level: 2, text: `Courts ordered far more than was actually collected` },
    { type: 'paragraph', text: `There is another important number buried in the statistics.` },
    { type: 'paragraph', text: `Courts imposed £367.3 million in confiscation orders during 2025/26, a 64 per cent jump from £223.9 million the year before, and the highest annual figure across the full six-year reporting period.` },
    { type: 'paragraph', text: `Actual confiscation receipts were £150.9 million.` },
    { type: 'paragraph', text: `Those figures cannot simply be subtracted from each other because money collected in one year may relate to orders made in earlier years.` },
    { type: 'paragraph', text: `But they expose a longstanding problem.` },
    { type: 'paragraph', text: `Identifying criminal benefit is not the same as actually recovering the money.` },
    { type: 'paragraph', text: `The government should therefore be judged on assets collected, not just orders made or money frozen.` },
    { type: 'heading', level: 2, text: `Only £26 million went back to victims through confiscation proceeds` },
    { type: 'paragraph', text: `The government says stronger asset recovery will help return money to victims.` },
    { type: 'paragraph', text: `The latest statistics show £26.1 million was paid to victims through confiscation-order proceeds in 2025/26.` },
    { type: 'paragraph', text: `That was 45 per cent lower than the previous year, even though it still sat 29 per cent above the six-year median.` },
    { type: 'paragraph', text: `That figure does not represent every form of victim compensation in the criminal justice system.` },
    { type: 'paragraph', text: `But it is relevant to the government's claim that recovering criminal money directly benefits victims.` },
    { type: 'paragraph', text: `Of the £345.3 million recovered through the mechanisms covered by the statistics, only a fraction was recorded as victim compensation through confiscation orders.` },
    { type: 'heading', level: 2, text: `More than £1 billion was frozen or restrained, but that is not the same as recovered` },
    { type: 'paragraph', text: `The government also points to the value of assets denied to criminals.` },
    { type: 'paragraph', text: `In 2025/26, authorities blocked access to around £1.1 billion.` },
    { type: 'paragraph', text: `That included £677 million under restraint orders, a 37 per cent increase, and £376.4 million seized or frozen under forfeiture powers.` },
    { type: 'paragraph', text: `That sounds close to £1.1 billion recovered.` },
    { type: 'paragraph', text: `It is not.` },
    { type: 'paragraph', text: `A restraint order or seizure can stop someone accessing property while legal proceedings continue.` },
    { type: 'paragraph', text: `The asset may later be recovered, released or disputed.` },
    { type: 'paragraph', text: `The figure that matters most to the taxpayer is the value ultimately confiscated or forfeited.` },
    { type: 'paragraph', text: `That was £345.3 million.` },
    { type: 'heading', level: 2, text: `Recovered money already funds more enforcement` },
    { type: 'paragraph', text: `The government already recycles some criminal assets back into law enforcement.` },
    { type: 'paragraph', text: `Under the Asset Recovery Incentivisation Scheme, agencies involved in confiscation and recovery receive a share of proceeds.` },
    { type: 'paragraph', text: `In 2025/26, £129.6 million was distributed to Proceeds of Crime Act agencies through the scheme.` },
    { type: 'paragraph', text: `A further £12.8 million was awarded across 18 projects through the ARIS Top Slice budget, supporting confiscation enforcement, cryptocurrency capability and border asset recovery activity.` },
    { type: 'paragraph', text: `That means the new £500 million is being added to a system that already uses criminal proceeds to fund further enforcement.` },
    { type: 'paragraph', text: `The missing number is the full cost of that system.` },
    { type: 'paragraph', text: `The government publishes how much money is recovered.` },
    { type: 'paragraph', text: `It does not, in this announcement, publish one consolidated annual figure showing how much police forces, the NCA, prosecutors, courts and specialist investigators spend recovering it.` },
    { type: 'paragraph', text: `Without that figure, it is impossible to calculate a simple financial return.` },
    { type: 'heading', level: 2, text: `The 500 extra officers need to be counted properly` },
    { type: 'paragraph', text: `The headline promise is specific: 500 additional officers.` },
    { type: 'paragraph', text: `They will be deployed across police forces, the NCA and the CPS.` },
    { type: 'paragraph', text: `But the announcement does not say how many each organisation will receive, how many will be warranted police officers, how many will be financial investigators or intelligence staff, how many will be prosecutors, when all 500 will be in post, or whether any replace roles whose existing funding was due to end.` },
    { type: 'paragraph', text: `Those details should eventually be checked against actual headcount.` },
    { type: 'paragraph', text: `Otherwise, "500 new officers" risks remaining an announcement number long after the programme begins.` },
    { type: 'heading', level: 2, text: `Operation Destabilise shows what targeted enforcement can achieve` },
    { type: 'paragraph', text: `The government points to the NCA's Operation Destabilise, aimed at disrupting Russian money-laundering networks, as evidence of the value of specialist investigations.` },
    { type: 'paragraph', text: `It says the operation resulted in 119 arrests and more than £25 million in cash and cryptocurrency seizures in less than 12 months.` },
    { type: 'paragraph', text: `That is a real enforcement result.` },
    { type: 'paragraph', text: `But the same caution applies.` },
    { type: 'paragraph', text: `Seized assets are not always permanently recovered assets.` },
    { type: 'paragraph', text: `The legal process still matters.` },
    { type: 'paragraph', text: `That distinction is especially important when government announcements combine arrests, seizures, freezing orders and final recoveries into the same narrative.` },
    { type: 'paragraph', text: `They measure different stages of the process.` },
    { type: 'heading', level: 2, text: `The £100 billion estimate remains the uncomfortable backdrop` },
    { type: 'paragraph', text: `The government, citing NCA estimates, says more than £100 billion is laundered through the UK or UK corporate structures every year.` },
    { type: 'paragraph', text: `That does not mean there is a £100 billion pot sitting in British bank accounts waiting for police to seize it.` },
    { type: 'paragraph', text: `Money laundering can involve international transactions, shell companies and funds moving through multiple jurisdictions.` },
    { type: 'paragraph', text: `But the estimate demonstrates the scale of the problem.` },
    { type: 'paragraph', text: `Recovering £345 million in a year can be both an improvement and still represent a small outcome against a vast criminal economy.` },
    { type: 'paragraph', text: `That is why the government's new investment should come with measurable expectations.` },
    { type: 'heading', level: 2, text: `£500 million in. What should come out?` },
    { type: 'paragraph', text: `The government has announced a precise input.` },
    { type: 'paragraph', text: `More than £500 million.` },
    { type: 'paragraph', text: `Five hundred officers.` },
    { type: 'paragraph', text: `Three years.` },
    { type: 'paragraph', text: `What it has not announced is an equally precise outcome.` },
    { type: 'paragraph', text: `There is no published target saying how much additional criminal money should be recovered.` },
    { type: 'paragraph', text: `No target showing how much more should reach victims.` },
    { type: 'paragraph', text: `No public return-on-investment measure.` },
    { type: 'paragraph', text: `No published benchmark for how much the additional officers should increase confiscation or forfeiture.` },
    { type: 'paragraph', text: `That makes future accountability unnecessarily difficult.` },
    { type: 'paragraph', text: `If recoveries rise to £500 million, is that success? £750 million? £1 billion?` },
    { type: 'paragraph', text: `Without a target, almost any increase can later be presented as evidence that the programme worked.` },
    { type: 'paragraph', text: `The government has a credible case for spending more on financial-crime enforcement.` },
    { type: 'paragraph', text: `Asset recovery is rising and the amount of money believed to move through Britain's laundering system remains enormous.` },
    { type: 'paragraph', text: `But if regulated businesses are being charged hundreds of millions of pounds more to fund the crackdown, the public should be able to measure what that money achieves.` },
    { type: 'paragraph', text: `The policy currently tells us exactly what is going in.` },
    { type: 'paragraph', text: `It is much less clear about what is expected to come out.` },
  ],
  evidence: {
    recordsReviewed: [
      'Home Office / GOV.UK, 15 September 2026: "Hundreds of new officers to hunt down dirty money networks" — £500m/three-year commitment, 500-officer deployment across police/NCA/CPS, NCA £100bn laundering estimate, Operation Destabilise (119 arrests, £25m+ seizures)',
      'Home Office, Asset recovery statistics, financial years ending 2021 to 2026 — £345.3m total (up 20% year-on-year, up 57% nominal/29% real since 2020/21); confiscation £150.9m (down 5%); forfeiture £155.9m (up 28%); civil recovery £38.5m (up fivefold from £7.5m); bank-account forfeiture £65m → £100.4m; confiscation orders imposed £367.3m vs receipts £150.9m; victim compensation £26.1m (down 45% year-on-year but 29% above six-year median); restraint orders £677m (up 37%); seizure/forfeiture freeze £376.4m; ARIS distribution £129.6m; ARIS Top Slice £12.8m across 18 projects',
      'HM Treasury / GOV.UK, "Economic Crime Levy: changes to bands and charges" — new £1m Band D (revenues >£1bn, double the previous £500,000); new £500,000 Band C (revenues £500m–£1bn); April 2026 effective date; revenue estimates £110m (2027/28), ~£115m per year thereafter',
    ],
    lastChecked: '30 September 2026',
  },
};

export default piece;
