import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'pc7m3wq9k2',
  kicker: 'Child Welfare',
  headline: `Private Providers Control 74% of Children's Home Places. DfE Still Cannot Say What a Fair Price Is`,
  standfirst: `Private companies provide 74 per cent of children's home places in England. The Department for Education told MPs it still does not fully understand what a reasonable price for residential care should be. That leaves councils buying places in a market where they have a legal duty to find a home for a child, shortages can leave them competing against one another for the same beds, and the department responsible does not have direct sight of the contracts behind the prices being charged.`,
  publishedAt: '2026-07-03',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `Private companies provide 74 per cent of children's home places in England.` },
    { type: 'paragraph', text: `The Department for Education told MPs it still does not fully understand what a reasonable price for residential care should be.` },
    { type: 'paragraph', text: `That leaves councils buying places in a market where they have a legal duty to find a home for a child, shortages can leave them competing against one another for the same beds, and the department responsible for the system does not have direct sight of the contracts and financial information behind the prices being charged.` },
    { type: 'paragraph', text: `The Public Accounts Committee examined the system in January. Private providers were running 84 per cent of children's homes and supplying 74 per cent of places. Seven of the ten largest providers were owned by private equity.` },
    { type: 'paragraph', text: `The committee found that DfE did not fully understand their finances, including debt levels and financial risks. The department told MPs it needed legislation to obtain more information from providers.` },
    { type: 'paragraph', text: `That legislation has now passed.` },
    { type: 'paragraph', text: `The Children's Wellbeing and Schools Act gives ministers powers to require financial information from major providers and, if they decide it is necessary, to cap profits made from children's homes and independent fostering agencies. No profit cap has yet been set. The government has described it as a measure to be used if its other reforms fail to reduce excessive profits.` },
    { type: 'paragraph', text: `The problem it is trying to fix has been documented for years.` },
    { type: 'paragraph', text: `In 2022, the Competition and Markets Authority examined financial information from 15 of the largest private children's social care providers across England, Scotland and Wales.` },
    { type: 'paragraph', text: `For children's homes, operating profit margins averaged 22.6 per cent between 2016 and 2020. Average weekly prices rose from £2,977 to £3,830 over the same period, an increase of 3.5 per cent a year after inflation. Average operating profit rose from £702 to £910 per placement per week.` },
    { type: 'paragraph', text: `Those figures should not be presented as the profit margin of every children's home today.` },
    { type: 'paragraph', text: `The CMA's sample covered large providers and the financial period ended in 2020. The Public Accounts Committee also heard that many smaller and practitioner-led providers do not make profits on the same scale.` },
    { type: 'paragraph', text: `But the government has not produced more recent market-wide evidence showing that the problem identified by the CMA has disappeared. Its own impact assessment for the new profit-cap power still cites the CMA's findings as evidence that profits among major providers are excessive.` },
    { type: 'paragraph', text: `The largest companies now control a substantial part of the market.` },
    { type: 'paragraph', text: `Ofsted's latest ownership analysis, using data from March 2025, found that the 20 largest owners controlled a quarter of all children's homes in England.` },
    { type: 'paragraph', text: `The biggest was Amalfi Midco Limited, the ownership group containing CareTech, with 220 homes and 877 places. G Square Healthcare Private Equity LLP, which owns the Keys group, had 156 homes and 621 places. Between them they owned 9 per cent of all children's homes in England.` },
    { type: 'paragraph', text: `Large private providers are not simply extracting money from a market they did nothing to create. They have also supplied much of its additional capacity.` },
    { type: 'paragraph', text: `The CMA found that growth in provision in England and Wales had been driven largely by private companies. It also warned against simply banning profit or imposing badly designed price controls because reducing the incentive to open homes could make an existing shortage worse.` },
    { type: 'paragraph', text: `Its preferred solution was to change the balance of power between councils and providers by improving commissioning and increasing the supply of suitable places.` },
    { type: 'paragraph', text: `Four years later, that work is unfinished.` },
    { type: 'paragraph', text: `The Public Accounts Committee found that councils still compete with one another for placements, particularly when a child needs a home at short notice. DfE accepted recommendations for regional commissioning in 2022, but pilots in Greater Manchester and the South East did not begin until 2025.` },
    { type: 'paragraph', text: `The government's response to the committee now says it wants every council to become part of a Regional Care Cooperative, with national implementation targeted for spring 2029.` },
    { type: 'paragraph', text: `In the meantime, the cost has continued to rise.` },
    { type: 'paragraph', text: `English councils spent £3.1 billion on residential care in 2023-24, almost twice the amount five years earlier. The number of children in residential care rose by 10 per cent over the same period.` },
    { type: 'paragraph', text: `Average council spending per child in residential care rose from £239,800 in 2019-20 to £318,400 in 2023-24, with both figures expressed in 2023-24 prices.` },
    { type: 'paragraph', text: `Some individual placements cost vastly more.` },
    { type: 'paragraph', text: `An LGA survey published in 2023 asked 121 councils for the cost of their single most expensive placement. The median was £16,450 a week. The highest reported placement cost £63,000 a week.` },
    { type: 'paragraph', text: `That £63,000 figure was one extreme case, not the normal price of a children's home place. The survey found the typical council's highest-cost placement was much lower.` },
    { type: 'paragraph', text: `More revealing was what councils said was causing the prices. Ninety-eight per cent cited a lack of choice in available placements. Ninety-three per cent also cited increasingly complex needs among children.` },
    { type: 'paragraph', text: `Those two explanations can exist together. A child requiring round-the-clock specialist support is expensive to care for regardless of who owns the home. But scarcity makes the council's negotiating position weaker once only a handful of providers can meet that child's needs.` },
    { type: 'paragraph', text: `The consequences are not confined to council accounts.` },
    { type: 'paragraph', text: `The Public Accounts Committee found that 49 per cent of children in residential care were living more than 20 miles from their original home. The Association of Directors of Children's Services told MPs that long-distance placements make it harder for social workers to maintain relationships with children and understand the support available around them.` },
    { type: 'paragraph', text: `At a single count in September 2024, 775 children were in unregistered accommodation, where Ofsted cannot routinely inspect the care being provided. The committee said those placements lasted an average of six months (185 days).` },
    { type: 'paragraph', text: `Running an unregistered children's home is illegal. The children themselves have done nothing wrong by being placed there.` },
    { type: 'paragraph', text: `The committee linked the problem to the shortage of suitable registered places, particularly for children with complex needs.` },
    { type: 'paragraph', text: `Councils also told Parliament that rising placement costs were affecting what they could spend elsewhere. Written evidence from the County Councils Network said authorities trying to balance their budgets had reduced non-statutory services, including some services intended to prevent children eventually needing to enter care.` },
    { type: 'paragraph', text: `The government is now putting more money into prevention. Its 2026-27 local government settlement includes a £3.1 billion Children, Families and Youth Grant, with £2.4 billion over the multi-year settlement for the Families First Partnership programme. Ministers say the aim is to help families earlier and reduce the number of children entering care.` },
    { type: 'paragraph', text: `It is also creating a new financial oversight system for the largest providers.` },
    { type: 'paragraph', text: `DfE expects about 40 providers, covering roughly 42 per cent of the looked-after children's placement market, to fall within it initially. They will have to provide financial information and contingency plans intended to give government and councils warning if a major provider is at risk of collapse.` },
    { type: 'paragraph', text: `That deals with one of the risks identified by the CMA: large providers carrying enough debt that a sudden failure could disrupt children's placements.` },
    { type: 'paragraph', text: `It does not by itself establish what councils should be paying.` },
    { type: 'paragraph', text: `The Public Accounts Committee asked DfE directly about prices. The department said it did not have direct visibility of contracts because councils negotiate them, acknowledged that greater price transparency would strengthen councils' position and said it "does not fully understand what constitutes a reasonable price for residential care."` },
    { type: 'paragraph', text: `That is where the system stands after a CMA investigation in 2022, an independent care review the same year, and a new Act of Parliament giving ministers powers to intervene. National rollout of the Regional Care Cooperative model meant to end council competition for places is not due until spring 2029.` },
  ],
  evidence: {
    recordsReviewed: [
      `House of Commons Public Accounts Committee, Financial sustainability of children's care homes, 16 January 2026 (HC 1233): the figures for private ownership and capacity, private equity ownership, DfE's lack of financial visibility, competition between councils, distant placements, and the 775 children in unregistered accommodation as at September 2024 with a mean placement length of 185 days`,
      `HM Treasury, Government Response to the Committee of Public Accounts on the Fifty-seventh to the Sixty-first Reports of Session 2024-26: DfE's response to the PAC findings and the government's target of spring 2029 for its Regional Care Cooperative model`,
      `Department for Education, CSC Financial Oversight Scheme: Regulatory Impact Assessment: the plan to bring an initial 40 providers, covering approximately 42 per cent of the market, within the financial oversight scheme`,
      `Competition and Markets Authority, Children's social care market study: final report, 10 March 2022: the 22.6 per cent average operating margin among large children's home providers 2016-2020, the £2,977 to £3,830 weekly price increase, the 3.5 per cent real annual increase, operating profit figures, findings on debt and shortages, and the CMA's warning about the possible effect of blunt profit or price controls on capacity`,
      `Ofsted, Ownership of children's social care providers in England 2025, 27 November 2025: current ownership concentration, including the 20 largest owners' 25 per cent share and the size of the Amalfi Midco (CareTech) and G Square (Keys) ownership groups`,
      `Department for Education, Children's Social Care Profit Cap: Regulatory Impact Assessment: the government's case for taking a statutory profit-cap power and its continued reliance on CMA evidence on profits among large providers`,
      `Children's Wellbeing and Schools Act 2026, section 17: the statutory power for ministers to limit profits of non-local-authority children's home and fostering providers and require information necessary to administer such a cap`,
      `Local Government Association, High-cost children's social care placements survey, November 2023: the £16,450 median highest-cost placement, £63,000 maximum and councils' evidence that lack of placement choice and increasingly complex needs were driving exceptionally high costs`,
      `National Audit Office, Managing children's residential care, September 2025: the £3.1 billion spent on residential care in 2023-24, the 96 per cent five-year cost increase, the 10 per cent rise in the number of children in residential care, and average council spending per child rising from £239,800 (2019-20) to £318,400 (2023-24), both in 2023-24 prices`,
      `Ministry of Housing, Communities and Local Government, Provisional local government finance settlement 2026 to 2027: the £3.1 billion Children, Families and Youth Grant and the £2.4 billion multi-year Families First Partnership allocation`,
    ],
    lastChecked: '5 October 2026',
  },
};

export default piece;
