import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'pf7k3mxw9q',
  kicker: 'Environment',
  headline: `Ministers Accept PFAS Pollution Could Be Irreversible but Give No Date for Consumer Restrictions`,
  standfirst: `On 6 July, the government responded to a parliamentary proposal to begin phasing PFAS out of products such as food packaging, cookware and school uniforms from 2027. It did not accept the timetable. Ministers said they would wait to see how the EU's proposed wider restriction deals with non-essential consumer products. The same response says there is "plausible evidence" that continued PFAS emissions could cause serious or irreversible pollution.`,
  publishedAt: '2026-07-16',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `On 6 July, the government responded to a parliamentary proposal to begin phasing PFAS out of products such as food packaging, cookware and school uniforms from 2027.` },
    { type: 'paragraph', text: `It did not accept the timetable.` },
    { type: 'paragraph', text: `Instead, ministers said they would consider regulatory and non-regulatory options and wait to see how the European Union's proposed wider restriction deals with non-essential consumer products. The same government response says there is "plausible evidence" that continued PFAS emissions could cause serious or irreversible pollution because the chemicals persist for so long in the environment.` },
    { type: 'paragraph', text: `PFAS are a family of thousands of chemicals used for properties including resistance to heat, water, oil and stains. They can be found in products ranging from medical equipment and firefighting foams to textiles, packaging and non-stick cookware. Some uses are difficult to replace. Others are not.` },
    { type: 'paragraph', text: `The Environmental Audit Committee proposed drawing that distinction more sharply. Its April report recommended an "essential use" approach, with exemptions where PFAS were genuinely needed and alternatives were unavailable. It specifically called for restrictions on non-essential consumer uses, including food packaging, cookware and school uniforms, to begin from 2027.` },
    { type: 'paragraph', text: `The government has not said when those products will be restricted.` },
    { type: 'paragraph', text: `Defra said an essential-use system across the whole PFAS family would be complicated, that alternatives need to be assessed for safety and performance, and that restrictions could impose costs on consumers and businesses. It also warned against replacing one PFAS with another chemical that later proves similarly problematic.` },
    { type: 'paragraph', text: `There is evidence for that caution. PFAS are used in medical devices, protective equipment, semiconductors, energy technologies and defence equipment where substitutes can be technically difficult or expensive. The committee itself accepted that some uses may need exemptions while alternatives are developed.` },
    { type: 'paragraph', text: `But the dispute is not principally about those uses. MPs asked ministers to start with consumer products they regarded as non-essential.` },
    { type: 'paragraph', text: `The government said it intends to draw from final EU regulatory decisions unless there are compelling reasons to diverge. The European Chemicals Agency's scientific committees have already backed an EU-wide PFAS restriction with targeted exemptions, but the process is not finished. Its socio-economic committee was still considering consultation responses in July and was expected to adopt its final opinion by the end of 2026. The European Commission would then decide whether to put restrictions to EU member states.` },
    { type: 'paragraph', text: `Britain's own chemicals system is also being reworked. The government says reforms to UK REACH, intended partly to make it easier to draw on EU decisions rather than repeat scientific assessments, will be introduced by December 2028.` },
    { type: 'paragraph', text: `PFAS regulation in Britain did not begin with this year's plan. In 2023, the Health and Safety Executive and Environment Agency completed a regulatory review which identified persistence, mobility and uncertainty over long-term health and environmental effects as reasons for concern. One of its main recommendations was to pursue restrictions on PFAS in firefighting foams because they are a major source of direct emissions.` },
    { type: 'paragraph', text: `That restriction is progressing. A six-month consultation on the proposal ended in February this year, and on 9 July HSE opened the next consultation stage after concluding that restrictions on PFAS in firefighting foams were an appropriate way to reduce risks to health and the environment.` },
    { type: 'paragraph', text: `The government's February PFAS Plan contains other measures. It proposes a statutory limit for PFAS in public drinking water in England, further monitoring of soils and waters, testing of food packaging, guidance on contaminated land and work to reduce emissions from industrial sites.` },
    { type: 'paragraph', text: `Existing controls have produced measurable improvements in some areas. The Environment Agency says concentrations of the older PFAS chemicals PFOS and PFOA in English rivers have fallen by around 30 per cent since 2016. The government also says there is currently no evidence of PFAS above its 0.1 micrograms-per-litre guidance level in public drinking water supplies in England and Wales.` },
    { type: 'paragraph', text: `The scale of existing contamination is harder to resolve.` },
    { type: 'paragraph', text: `An Environment Agency-commissioned study modelled the possible cost of remediating high-risk PFAS sites in England. Depending on the assumptions used, it estimated between 2,900 and 10,200 sites, with remediation costs ranging from £31 billion to £121 billion.` },
    { type: 'paragraph', text: `Those figures are not a government spending forecast and do not mean taxpayers face a £121 billion bill. They are modelled scenarios intended to show the possible financial scale of contamination. The eventual cost would depend on which sites require remediation, what work is necessary and whether companies responsible for pollution can be identified and made to pay.` },
    { type: 'paragraph', text: `The committee recommended that ministers consult by March 2027 on a national PFAS remediation fund, consider a levy on PFAS emissions and increase central funding for councils where no responsible polluter can be found.` },
    { type: 'paragraph', text: `The government accepted that remediation costs could be significant and said there was a "strong case" for making polluters pay wherever possible. Defra's own commissioned research found that a levy on PFAS manufacture and imports could help reduce emissions and apply that principle, although it also identified possible effects on competitiveness and consumer prices. Ministers did not commit to the committee's remediation fund or its March 2027 consultation deadline, saying instead that levies and other financing mechanisms remained under consideration.` },
    { type: 'paragraph', text: `Consumers are being asked to wait too. The committee wanted standardised labelling and interim limits while PFAS-containing products remained on sale. The government did not adopt either proposal. It said industry was often best placed to improve information voluntarily and that mandatory limits across thousands of chemicals and many different products would require further evidence and assessment.` },
    { type: 'paragraph', text: `That leaves the government pursuing restrictions where work is already advanced, particularly firefighting foams, while monitoring, testing and researching the wider problem and looking towards the EU before deciding how far consumer restrictions should go.` },
    { type: 'paragraph', text: `Its February PFAS Plan says the persistence of the chemicals means action "should not be unnecessarily delayed". In July, ministers accepted that continued emissions present a plausible risk of serious or irreversible pollution.` },
    { type: 'paragraph', text: `They have still given no date for restricting PFAS in the non-essential consumer products MPs asked them to tackle from 2027.` },
  ],
  evidence: {
    recordsReviewed: [
      `Environmental Audit Committee, Addressing the risks from Perfluoroalkyl and Polyfluoroalkyl Substances (PFAS), 23 April 2026: the proposed essential-use approach, the recommended 2027 phase-out of PFAS in non-essential consumer products, the remediation recommendations and evidence on existing contamination`,
      `UK Government response to the Environmental Audit Committee, published 6 July 2026: the government's acknowledgement of a plausible risk of serious or irreversible pollution, its position on consumer restrictions, EU alignment, labelling, remediation funding and UK REACH reform`,
      `Defra, PFAS Plan: building a safer future together, 3 February 2026: the government's existing programme on monitoring, drinking water, contaminated land, industrial emissions and its statement that action should not be unnecessarily delayed`,
      `Environment Agency, PFAS: Evaluating the economic burden of remediating high-risk sites: the modelled estimate of £31 billion to £121 billion to remediate between 2,900 and 10,200 high-risk sites in England`,
      `Health and Safety Executive, UK REACH work on PFAS in firefighting foams: the history of the 2023 regulatory review and the restriction process subsequently taken forward for firefighting foams`,
      `European Chemicals Agency, PFAS universal restriction process, March to June 2026: the status of the proposed EU-wide restriction, the scientific committees' support for a broad restriction with targeted derogations and the expected timetable for the final socio-economic opinion`,
    ],
    lastChecked: '4 October 2026',
  },
};

export default piece;
