import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'pk9v2mrx4t',
  kicker: 'Public Spending',
  headline: `Prison Expansion Programme Wrote Off £24m Without Naming the Projects`,
  standfirst: `HM Prison and Probation Service wrote off almost £24 million from its prison expansion programme after construction projects were reduced in scope and a supplier failed. The published accounts do not identify the three losses individually — no names, no per-project amounts, no prison places affected. The losses sit inside a programme already running four years late and nearly double its original budget.`,
  publishedAt: '2026-08-03',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `HM Prison and Probation Service wrote off almost £24 million from its prison expansion programme after construction projects were reduced in scope and a supplier failed.` },
    { type: 'paragraph', text: `The Ministry of Justice's consolidated accounts put the loss at exactly £23,996,152. HMPPS's own accounts say it comprised three constructive losses during 2024/25.` },
    { type: 'paragraph', text: `The published accounts do not identify the three losses individually.` },
    { type: 'paragraph', text: `They do not name the prisons, give the amount lost on each project, state how many prison places were affected or say how much of the £24 million resulted from supplier failure rather than projects being abandoned or reduced.` },
    { type: 'paragraph', text: `That means the original description of three prison projects being cancelled goes further than the accounts support.` },
    { type: 'paragraph', text: `HMPPS says the losses arose from construction costs already incurred on "descoped build projects within existing prison sites" and from supplier failure. It says work had commenced before expected completion costs increased materially, partly because of the extent of asbestos contamination. The affected projects were subsequently judged not to represent value for money.` },
    { type: 'paragraph', text: `Three accounting losses therefore do not necessarily mean three cancelled prison schemes.` },
    { type: 'paragraph', text: `A constructive loss is also more specific than money simply disappearing. HM Treasury defines it as expenditure where procurement has taken place correctly but what was bought later proves unnecessary or less useful than when it was ordered. Significant constructive losses are reported to Parliament through departmental accounts.` },
    { type: 'paragraph', text: `Treasury guidance says public bodies should keep records showing the nature, gross amount and cause of each loss. It also says individual losses above £300,000 should be noted separately in annual accounts. HMPPS states that it made four loss payments above £300,000 during 2024/25, then reports the three prison-capacity constructive losses together as a £24 million total. The note does not publish their individual values.` },
    { type: 'paragraph', text: `Other government records provide names for some of the problems affecting the prison construction programme, but they do not allow the £24 million to be reconstructed.` },
    { type: 'paragraph', text: `The National Audit Office reported that construction company ISG went into administration in September 2024 while acting as the Ministry's main contractor for 3,634 planned prison places, equivalent to 17 per cent of the expansion portfolio. HMPPS expected the collapse to delay individual projects by between three and 18 months.` },
    { type: 'paragraph', text: `In June 2026, the Ministry told Parliament that ISG had been due to complete construction or maintenance projects at dozens of prisons. Replacement contractors had been appointed.` },
    { type: 'paragraph', text: `The same answer disclosed that planned Category D expansions at HMP Leyhill and HMP Springhill had been removed from the prison supply programmes. HMPPS was still constructing around 100 Rapid Deployment Cells at Leyhill under a separate programme.` },
    { type: 'paragraph', text: `None of those disclosures establishes that Leyhill, Springhill or an ISG project accounts for any particular part of the £23,996,152 write-off.` },
    { type: 'paragraph', text: `The £24 million is not expected to be the final loss.` },
    { type: 'paragraph', text: `HMPPS said further constructive losses "of a similar order" were expected in its 2025/26 accounts. Those would cover construction, demobilisation and remediation costs incurred after March 2025.` },
    { type: 'paragraph', text: `It did not give an estimated figure. "Similar order" is not precise enough to double the £24 million and present the result as an expected total.` },
    { type: 'paragraph', text: `As of 3 August 2026, the HMPPS 2025/26 annual report and accounts had not been published. The government's HMPPS annual reporting collection still listed the 2024/25 accounts as the latest set of agency accounts.` },
    { type: 'paragraph', text: `The losses occurred inside a prison expansion programme that was already substantially over its original timetable and expected cost.` },
    { type: 'paragraph', text: `In October 2021, the government committed to delivering 20,000 additional prison places by the mid-2020s. HMPPS's plans at the time envisaged completing the portfolio by July 2026.` },
    { type: 'paragraph', text: `By September 2024 it had delivered 6,518 places, against at least 11,317 that it had expected to have completed by December that year. HMPPS subsequently moved the overall completion date to 2031.` },
    { type: 'paragraph', text: `By March 2025 the number delivered had reached around 6,500. The government's current strategy treats the remaining approximately 14,000 places as the programme still to be delivered by 2031.` },
    { type: 'paragraph', text: `Costs moved in the same direction.` },
    { type: 'paragraph', text: `The NAO found that the portfolio's forecast cost at the 2021 Spending Review was £5.2 billion. By September 2024, HMPPS expected it to cost between £9.4 billion and £10.1 billion, an increase of between £4.2 billion and £4.9 billion.` },
    { type: 'paragraph', text: `The watchdog attributed the wider overruns to more than inflation. It found that overambitious timetables and unachievable budgets had been approved, that HMPPS had not sufficiently understood the scope of some programmes and that an internal review found significant work had been excluded from some early budgets to allow projects to progress. Construction inflation and supplier failures then added further pressure.` },
    { type: 'paragraph', text: `The three £24 million losses sit somewhere inside that programme.` },
    { type: 'paragraph', text: `The public accounts establish that work had begun, costs had been incurred and some construction expenditure was subsequently written off. They establish that asbestos, rising completion costs and supplier failure contributed.` },
    { type: 'paragraph', text: `They do not identify which projects consumed the £23,996,152, how much was lost on each one, how many planned prison places disappeared with them or which supplier accounted for the supplier-failure element.` },
    { type: 'paragraph', text: `Further construction, demobilisation and remediation losses had already been incurred after March 2025. HMPPS said they would be disclosed in the following year's accounts.` },
    { type: 'paragraph', text: `Those accounts had not been published by 3 August.` },
  ],
  evidence: {
    recordsReviewed: [
      `Ministry of Justice, Annual Report and Accounts 2024/25, Parliamentary Accountability section: gives the exact £23,996,152 constructive loss and attributes it to descoped prison-building projects and supplier failure, with increased completion costs partly caused by asbestos contamination`,
      `HM Prison and Probation Service, Annual Report and Accounts 2024/25: establishes that the £24 million comprised three constructive losses and records the expectation of further losses of a similar order for construction, demobilisation and remediation expenditure after March 2025`,
      `HM Treasury, Managing Public Money: defines constructive losses and sets out requirements for recording losses and bringing significant losses to Parliament's attention`,
      `National Audit Office, Increasing the capacity of the prison estate to meet demand, 4 December 2024: establishes the original timetable, 6,518 places delivered by September 2024, revised 2031 completion date, forecast cost of £9.4 billion to £10.1 billion against £5.2 billion in approved estimated funding in 2021, ISG's exposure within the programme and wider weaknesses in programme planning and risk management`,
      `Ministry of Justice, written answer 5024, 8 June 2026: identifies projects affected by ISG's administration, confirms replacement contractors had been appointed and records that the Category D expansions at HMP Leyhill and HMP Springhill had been descoped`,
      `HMPPS Annual Report and Accounts 2024/25, Performance Report: records around 6,500 places delivered by March 2025 and describes the remaining 14,000 places as due for delivery by 2031`,
      `GOV.UK, HMPPS annual reporting collection: shows that as of the article date the 2024/25 accounts remained the latest published HMPPS annual report and accounts`,
    ],
    lastChecked: '5 October 2026',
  },
};

export default piece;
