import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'power-for-sale-20-politicians-who-cashed-in',
  kicker: 'Investigation',
  headline: 'Power For Sale? The 20 Politicians Who Cashed In After Leaving Office',
  standfirst:
    "Twenty politicians who turned public office into private income, some after leaving government, some while still serving. A few broke the rules. Many did not. The pattern is the point: a system built to protect the appearance of propriety more than propriety itself, where former power is converted into private leverage and then wrapped in technical compliance. From Cameron's Greensill texts to Hancock's jungle paycheque, the watchdog could bark from the porch while the caravan of private opportunity rolled on.",
  publishedAt: '2026-06-10',
  authorByline: "The People's Chamber",
  body: [
    {
      type: 'paragraph',
      text: 'This is a record of twenty figures who turned proximity to power into money. The entries are ordered by the severity and prominence of the case, from the clearest breaches to the quieter, perfectly legal cases that are arguably more revealing. In several of these, no rule was broken at all. That is precisely why they matter.',
    },

    { type: 'heading', level: 3, text: '1. David Cameron' },
    { type: 'paragraph', text: 'Cameron was an adviser to Greensill Capital from 2018. BBC Panorama reported he earned approximately £7.2 million from the company before it collapsed. Between 5 March and 26 June 2020, he and his staff sent ministers and officials 45 messages on behalf of Greensill, including texts to the Chancellor, seeking access to the Covid Corporate Financing Facility and other emergency government lending schemes. The Treasury rejected the approaches, and the Treasury Committee found Cameron did not break the rules governing lobbying by former ministers, but said those rules were of "insufficient strength" and that he showed a "significant lack of judgement." That is Westminster code for: legal, but rotten.' },
    { type: 'paragraph', text: 'A separate Cabinet Office inquiry led by Nigel Boardman found that Lex Greensill had enjoyed "a privileged, and sometimes extraordinarily privileged, relationship with government," including a desk and security pass within the Cabinet Office despite being neither a civil servant nor a special adviser. The Boardman report questioned whether there was any need for Greensill to have been given a government role at all.' },
    { type: 'paragraph', text: 'The moral problem is obvious. Cameron had occupied the highest office in the country. After leaving, he texted former colleagues on behalf of a finance company seeking access to emergency government support, while holding a significant personal economic interest in the firm. When Greensill collapsed, the public was left staring at a familiar swamp: former power converted into private leverage, then wrapped in technical compliance. The scandal mattered because it revealed how Britain’s rules protected the appearance of propriety more than propriety itself. Cameron did not just walk through the revolving door. He installed a brass handle on it.' },

    { type: 'heading', level: 3, text: '2. Owen Paterson' },
    { type: 'paragraph', text: 'The Commons Standards Committee found Paterson’s actions constituted an "egregious case of paid advocacy" and that he "repeatedly used his privileged position to benefit two companies for whom he was a paid consultant, and that this has brought the House into disrepute." The two companies were Randox, a clinical diagnostics firm paying him £100,000 per year, and Lynn’s Country Foods, a meat processor paying approximately £12,000 per year. Together they paid him nearly three times his parliamentary salary.' },
    { type: 'paragraph', text: 'The Parliamentary Commissioner for Standards, Kathryn Stone, found he breached the paid advocacy rule on at least 34 occasions between October 2016 and February 2020: three approaches to the Food Standards Agency on behalf of Randox relating to antibiotics testing in milk, seven approaches to the FSA on behalf of Lynn’s Country Foods, and four approaches to ministers at the Department for International Development on behalf of Randox relating to blood testing technology. He also breached the declaration rules by failing to declare his interest as a paid consultant to Lynn’s in four emails, used his parliamentary office for 16 business meetings with clients, and sent letters on House of Commons headed notepaper relating to his business interests.' },
    { type: 'paragraph', text: 'The committee recommended a 30-day suspension. The government initially tried to rewrite the standards mechanism that had caught him, turning one MP’s misconduct into a wider corruption row. That rescue operation collapsed within 24 hours. Paterson resigned rather than face the suspension.' },
    { type: 'paragraph', text: 'Paterson’s defence leaned heavily on the claim that he was raising serious public safety issues. The committee did not accept that as an answer to the rule breaches. The public does not elect MPs to become premium access consultants. This case remains one of Westminster’s clearest examples of private money contaminating public duty.' },

    { type: 'heading', level: 3, text: '3. George Osborne' },
    { type: 'paragraph', text: 'After leaving the Treasury, Osborne accumulated roles at a speed that made monetisation look like a business plan. BlackRock, the world’s largest asset manager, paid him £650,000 per year for four days’ work per month. He earned £786,450 from 15 speeches in 2016 alone. He accepted the editorship of the Evening Standard while still an MP. He chaired the Northern Powerhouse Partnership and accepted a Kissinger Fellowship. He later became chairman of an advisory panel at Exor.' },
    { type: 'paragraph', text: 'The Public Administration and Constitutional Affairs Committee explicitly criticised his announcement of the Evening Standard editorship without waiting for ACOBA’s advice, calling it "disrespect for Acoba and for the business appointment rules" that "sets an unhelpful example to others in public life who may be tempted to do the same." The same committee called ACOBA a "toothless regulator" and said that unless it was given statutory powers, the system would remain open to "similar abuses."' },
    { type: 'paragraph', text: 'The deeper issue was judgement. A former Chancellor taking a senior role at a giant investment firm was always going to raise questions about access, insight and influence. Becoming editor of a major London newspaper while still representing Tatton added another layer of absurdity. A petition calling for Osborne to "pick a job" reached 100,000 signatures. Osborne exposed the old system’s central weakness. It relied on restraint from people with every incentive not to show any.' },

    { type: 'heading', level: 3, text: '4. Boris Johnson' },
    { type: 'paragraph', text: 'Johnson’s record after office is a catalogue of repeated rule breaches. ACOBA said his announcement of a Daily Mail column, reportedly worth £1 million per year, was "a clear and unambiguous breach of the government’s rules and requirements of the Ministerial Code." He gave ACOBA just 30 minutes’ notice before the announcement went public, a day after becoming the first former prime minister found to have lied to Parliament. Lord Pickles, ACOBA’s chairman, wrote that the current rules were "designed to offer guidance when ‘good chaps’ could be relied on to observe the letter and the spirit of the rules" and that "if it ever existed, that time has long passed."' },
    { type: 'paragraph', text: 'That was not a one-off. In 2018, ACOBA found he had also broken the rules by failing to seek advice before signing a Daily Telegraph contract after leaving the Foreign Secretary role, calling it "unacceptable." In 2024, he was found to have broken the rules again over talks with Venezuelan President Nicolás Maduro, arranged through a hedge fund, without consulting ACOBA. In each case, the result was the same: outrage, watchdog letters, no serious consequence.' },
    { type: 'paragraph', text: 'Deputy Prime Minister Oliver Dowden acknowledged the Daily Mail breach but said further action would be "disproportionate." That is why Johnson belongs near the top. His case showed the absurdity of a watchdog that could identify breaches but not bite. ACOBA could bark from the porch while the caravan of private opportunity rolled on.' },

    { type: 'heading', level: 3, text: '5. Matt Hancock' },
    { type: 'paragraph', text: 'After serving as Health Secretary during the pandemic, Hancock signed up for ITV’s I’m a Celebrity, reportedly for £400,000, and Channel 4’s SAS: Who Dares Wins, for a further £45,000. ACOBA found he breached the Business Appointment Rules by failing to seek and await advice before either role was announced or taken up. Lord Pickles wrote to the Cabinet Office that "failing to seek and await advice before these roles were announced or taken up in this case is a breach of the Government’s rules and the requirements set out in the ministerial code."' },
    { type: 'paragraph', text: 'Hancock argued he had consulted ACOBA’s website and concluded that "one-off media appearances such as these do not count as an appointment or employment." Lord Pickles replied that "the rules are clear that an application is required where individuals plan a series of media activities and it is for Acoba to assess the associated risks." That was thin soup. These were not passing interviews. They were substantial commercial television commitments with production schedules and contractual obligations.' },
    { type: 'paragraph', text: 'This was not a classic lobbying scandal. It was reputation laundering by cheque. Hancock had held one of the most consequential offices in modern British government during a national trauma. The move into reality television looked like a man trying to convert public anger into screen time, then screen time into rehabilitation. Hancock did not merely leave government. He tried to edit the memory of it under studio lights.' },

    { type: 'heading', level: 3, text: '6. Peter Mandelson' },
    { type: 'paragraph', text: 'No British politician has done more to blur the boundary between political influence and commercial consultancy than Peter Mandelson. Long before "revolving door" became a popular phrase, Mandelson was effectively building the business model.' },
    { type: 'paragraph', text: 'After leaving government in 2010, he co-founded Global Counsel, a strategic advisory firm selling political insight, access and expertise to major corporate clients. A former architect of government policy turning political capital into commercial capital. Global Counsel attracted blue chip clients precisely because it was associated with one of Westminster’s most connected operators.' },
    { type: 'paragraph', text: 'What makes the Mandelson case significant is scale. This was not a retired politician sitting on a company board. It was the industrialisation of influence. The consultancy model offered corporations a guide to navigating government while preserving plausible deniability about lobbying.' },
    { type: 'paragraph', text: 'Whether one regards that as legitimate expertise or sophisticated influence peddling depends largely on one’s faith in Westminster. Mandelson’s career after politics became the template many others would follow. The revolving door did not merely spin. It became a profitable business in its own right.' },

    { type: 'heading', level: 3, text: '7. Grant Shapps' },
    { type: 'paragraph', text: 'After leaving office as Defence Secretary in July 2024, Shapps sought approval from ACOBA in November 2024 to chair Cambridge Aerospace, describing it as a civilian aerospace start-up. ACOBA approved the role on the condition that he played no part in its defence-related work until two years after leaving office. The problem emerged on 10 April 2025, when Cambridge Aerospace announced a contract to supply the UK and its Gulf allies with "Skyhammer" interceptor missiles, a multi million pound defence contract with the Ministry of Defence.' },
    { type: 'paragraph', text: 'Sir Laurie Magnus, the Independent Adviser on Ministers’ Standards, said the announcement "appears to be at direct variance with your original description of the role." He concluded that Shapps had "allowed a perception of impropriety to develop" and "failed to uphold the standards expected in the rules." Shapps claimed he was "one of several co-founders" rather than an active chairman, that he had never chaired the board or been a company director, and that he had "no involvement" with the missile contract. He declined to answer a series of detailed questions from Sir Laurie, citing "legal obligations of confidentiality."' },
    { type: 'paragraph', text: 'The controversy goes beyond technical compliance. As Defence Secretary, Shapps had dealt directly with defence contractors, procurement and military policy. A company initially presented as civilian turned out to have substantial defence ambitions. By the time concerns emerged publicly, the safeguards already looked inadequate. The episode became another example of a system relying heavily on trust, self reporting and voluntary restraint from the very people most likely to benefit from relaxed oversight.' },

    { type: 'heading', level: 3, text: '8. Rishi Sunak' },
    { type: 'paragraph', text: 'Sunak occupies a different category from many names on this list because his appointments were largely approved and transparent. The controversy stems less from misconduct and more from symbolism.' },
    { type: 'paragraph', text: 'Within a relatively short period of leaving Downing Street, Sunak accepted advisory roles connected to major technology and artificial intelligence companies. The optics were difficult. A former Prime Minister, with access to world leaders, regulators and policymakers, moving directly into firms operating in sectors that governments are actively trying to regulate inevitably fuels public suspicion.' },
    { type: 'paragraph', text: 'The issue is not whether Sunak broke rules. There is no evidence that he did. The issue is whether the rules themselves are sufficient. Modern technology companies spend enormous sums attempting to shape regulation. Hiring former heads of government is rarely an act of charity.' },
    { type: 'paragraph', text: 'His case illustrates a broader problem. The revolving door no longer revolves only between government and finance. Increasingly it links politics, technology and artificial intelligence. The sums involved are larger, the regulatory stakes higher and the opportunities for perceived conflicts even greater. The concern is less about what Sunak has done than about what the system now normalises.' },

    { type: 'heading', level: 3, text: '9. Nick Clegg' },
    { type: 'paragraph', text: 'Clegg did not join a conventional company. He joined one of the world’s most powerful technology platforms, eventually becoming President of Global Affairs at Meta, one of the most senior executive positions in the company. His job was to help one of the most controversial corporations on Earth manage its relationship with governments, regulators and public opinion.' },
    { type: 'paragraph', text: 'That is precisely why critics viewed the appointment as a textbook revolving door case. Clegg had spent years at the highest levels of government dealing with regulation, privacy, international relations and public policy. Those skills suddenly became available to a company facing pressure on all those fronts.' },
    { type: 'paragraph', text: 'There has never been evidence of wrongdoing. The concern is structural. Meta was not paying for coding skills or engineering expertise. It was paying for political judgement, networks and credibility.' },
    { type: 'paragraph', text: 'The broader significance of the appointment is that it marked a shift in where political influence is valued. Previous generations drifted into banking, defence or energy. Clegg demonstrated that Silicon Valley now competes for former senior politicians with the same enthusiasm once shown by investment banks. The result reinforced a growing public perception that political careers increasingly serve as apprenticeships for more lucrative private sector opportunities rather than destinations in themselves.' },

    { type: 'heading', level: 3, text: '10. Theresa Villiers' },
    { type: 'paragraph', text: 'Villiers generated less publicity than Cameron or Osborne, but her post government appointments became part of the wider debate surrounding political influence for hire.' },
    { type: 'paragraph', text: 'Having held senior positions including Northern Ireland Secretary and Environment Secretary, Villiers possessed extensive experience across highly regulated sectors. Subsequent advisory and consultancy work inevitably attracted scrutiny because of the overlap between former ministerial responsibilities and commercial interests.' },
    { type: 'paragraph', text: 'The controversy was never centred on a single explosive scandal. Instead it reflected a cumulative problem that Westminster has repeatedly failed to solve. Ministers spend years building relationships with regulators, civil servants, industry groups and stakeholders. Once they leave office, those same relationships can become commercially valuable.' },
    { type: 'paragraph', text: 'Her case demonstrates the quieter side of the revolving door. Not every controversy arrives with dramatic headlines. Sometimes the criticism arises because the public increasingly struggles to distinguish between policy expertise, lobbying and consultancy. When those categories begin to overlap, confidence in government inevitably suffers, even when no rule has been broken.' },

    { type: 'heading', level: 3, text: '11. Stephen Hammond' },
    { type: 'paragraph', text: 'While serving as a Conservative MP, Hammond accumulated a substantial portfolio of advisory and consultancy positions across sectors including finance, healthcare and infrastructure. All were declared according to parliamentary rules, yet legality was never the central issue.' },
    { type: 'paragraph', text: 'Hammond was not merely giving occasional speeches. He was receiving significant payments from private organisations seeking strategic advice while simultaneously sitting in Parliament and participating in debates affecting regulated industries. Transparency campaigners repeatedly pointed to Hammond as an example of why Westminster’s rules were inadequate. The concern was not necessarily that he changed policy in exchange for payment. Rather, it was that companies were willing to pay substantial sums precisely because he was an MP with insider knowledge, political contacts and influence.' },
    { type: 'paragraph', text: 'The deeper problem is perception. Parliament is supposed to be a full time public duty. Hammond’s extensive outside interests helped fuel the growing belief that some MPs operate as part time legislators and part time consultants. Even when rules are followed, public confidence suffers when elected representatives appear to have one foot in Westminster and the other in a corporate boardroom.' },

    { type: 'heading', level: 3, text: '12. Geoffrey Cox' },
    { type: 'paragraph', text: 'Cox earned hundreds of thousands of pounds through legal work while serving as an MP, including advising the government of the British Virgin Islands, a British Overseas Territory facing a corruption inquiry commissioned by the UK government itself. Everything was declared. Much of it was technically permissible. Yet the scale of the earnings transformed a procedural issue into a political scandal.' },
    { type: 'paragraph', text: 'The central question was simple: how can an MP properly represent constituents while simultaneously undertaking legal work generating vastly greater income than a parliamentary salary? The BVI work proved particularly controversial because it involved defending the interests of a government under scrutiny from UK authorities. A former Attorney General, the government’s own senior law officer, was being paid to resist an investigation that the UK government had initiated.' },
    { type: 'paragraph', text: 'Cox became the face of a wider problem. Westminster’s rules were designed for a period when MPs occasionally practised law or medicine. They were not designed for an era in which some MPs could earn multiples of their parliamentary salary from external clients. His case highlighted a growing disconnect between what is technically permitted and what many voters regard as acceptable.' },

    { type: 'heading', level: 3, text: '13. Andrew Mitchell' },
    { type: 'paragraph', text: 'Mitchell’s revolving door controversy never reached the explosive scale of Cameron’s Greensill affair, yet it illustrates the persistent concerns surrounding former ministers moving into advisory roles linked to sectors they once helped oversee.' },
    { type: 'paragraph', text: 'Having served as Secretary of State for International Development, Mitchell possessed an extensive network spanning government, international organisations, charities and business. Mitchell accepted advisory and consultancy roles after government service, each raising familiar questions about influence and access.' },
    { type: 'paragraph', text: 'Unlike some names on this list, Mitchell was not accused of misconduct. Modern lobbying often operates through advice, introductions and strategic guidance rather than direct pressure on ministers. Former cabinet ministers possess exactly the knowledge companies seek. His case highlights an uncomfortable truth about the revolving door debate. The greatest influence is often exercised quietly, through relationships and understanding rather than dramatic lobbying campaigns.' },

    { type: 'heading', level: 3, text: '14. Nadhim Zahawi' },
    { type: 'paragraph', text: 'Zahawi’s business background and subsequent tax controversy ensured that scrutiny followed him long after leaving ministerial office. He settled a tax dispute with HMRC involving a penalty, which Sir Laurie Magnus, the Independent Adviser on Ministers’ Standards, investigated. Magnus found that Zahawi had been "insufficiently transparent" about his tax affairs and that his conduct amounted to a "serious breach of the Ministerial Code." He was dismissed as Conservative Party Chairman in January 2023.' },
    { type: 'paragraph', text: 'Although not a classic revolving door case, Zahawi became closely associated with concerns about the intersection of wealth, business interests and political power. His career demonstrated how reputational damage accumulates. A politician may survive one controversy, then another, but eventually a broader narrative takes hold. His story reinforced a growing public suspicion that Westminster’s safeguards are often reactive rather than preventative, identifying problems only after they become politically toxic.' },

    { type: 'heading', level: 3, text: '15. Sajid Javid' },
    { type: 'paragraph', text: 'Javid’s case highlights a revolving door running in both directions. Before entering politics, he built a successful career at Deutsche Bank, reportedly becoming a Managing Director in his early 30s. After leaving government, having served as Chancellor and Health Secretary, he returned to advisory and commercial work connected to sectors that government actively regulates.' },
    { type: 'paragraph', text: 'No serious allegation of misconduct has been established. Nevertheless, a former Chancellor and Health Secretary possesses deep knowledge of economic policy, regulation, public spending and government decision making. Those insights are immensely valuable to private firms.' },
    { type: 'paragraph', text: 'The broader concern is systemic. Modern governments frequently recruit ministers from finance, then see them return to finance after public service. The result is a political class whose professional networks often overlap heavily with the industries they regulate. The question is not whether Javid broke rules. It is whether a democratic system can maintain public confidence when the route from boardroom to cabinet table and back again appears so well travelled.' },

    { type: 'heading', level: 3, text: '16. Amber Rudd' },
    { type: 'paragraph', text: 'Rudd’s post government career illustrates how the revolving door debate has expanded beyond lobbying into the broader question of whether former ministers should profit from expertise acquired in public office. After leaving frontline politics, including service as Home Secretary, she accepted advisory and non executive positions in sectors including energy, finance and corporate governance.' },
    { type: 'paragraph', text: 'None of these appointments produced a major scandal. There was no Greensill moment, no Commons investigation and no formal finding of misconduct. Companies increasingly seek strategic advice from former ministers because they understand how Whitehall works, how decisions are made and which political pressures matter.' },
    { type: 'paragraph', text: 'Rudd’s case highlights the limitations of Britain’s oversight system. The rules largely focused on direct lobbying, while many of the most commercially valuable forms of influence occur through advice, introductions and insight. Those activities are harder to regulate and often perfectly legal. What makes her case noteworthy is not personal controversy but what it reveals about Westminster’s culture. Former ministers are routinely treated as valuable corporate assets precisely because of their public service.' },

    { type: 'heading', level: 3, text: '17. Richard Harrington' },
    { type: 'paragraph', text: 'Harrington was formally criticised for failing to comply with the business appointment rules after leaving office. The former business minister accepted positions without first obtaining the necessary approval from ACOBA, prompting a public rebuke.' },
    { type: 'paragraph', text: 'The significance was not the size of the jobs involved but what it exposed about enforcement. Britain’s post ministerial rules relied heavily on voluntary compliance. If a former minister simply ignored the process, the consequences were often little more than public embarrassment.' },
    { type: 'paragraph', text: 'Harrington’s case became a demonstration of the system’s weakness. The rules existed. The approval process existed. Yet there was little practical deterrent for those who failed to follow them. Critics argued that a regulatory framework that depends on politicians voluntarily policing themselves is not really a regulatory framework at all. His episode became another piece of evidence cited by campaigners arguing that Britain’s revolving door regime was too weak, too dependent on trust and too reluctant to impose meaningful sanctions.' },

    { type: 'heading', level: 3, text: '18. Emma Reynolds' },
    { type: 'paragraph', text: 'Reynolds presents a different version of the revolving door. She moved between politics and the financial services sector before returning to government. Before returning to Parliament’s front bench and later ministerial office, Reynolds worked in senior public affairs and policy roles for major financial organisations, including TheCityUK. Those jobs were entirely legitimate and openly declared.' },
    { type: 'paragraph', text: 'The controversy arose because financial services is one of the most heavily regulated sectors in Britain, and governments are constantly making decisions that affect it. Critics argued that movement between political office and financial lobbying risks creating an appearance of regulatory capture, even where no improper behaviour occurs.' },
    { type: 'paragraph', text: 'Reynolds is hardly unique. Westminster is full of politicians who have worked in lobbying, public affairs or corporate relations. Her case matters because it demonstrates how normalised the practice has become. The public increasingly sees politics, lobbying and corporate advocacy as overlapping professions rather than distinct spheres.' },

    { type: 'heading', level: 3, text: '19. Alan Milburn' },
    { type: 'paragraph', text: 'After serving as Health Secretary, Milburn built a substantial portfolio career involving consultancy, advisory work and private sector healthcare interests, including roles connected to Bridgepoint Capital, a private equity firm with health sector investments.' },
    { type: 'paragraph', text: 'The controversy stemmed from obvious questions. Few politicians possessed greater knowledge of the National Health Service or health policy. When somebody with that background begins advising organisations operating in healthcare markets, concerns about conflicts of interest become inevitable.' },
    { type: 'paragraph', text: 'The NHS occupies a unique place in British politics. Public sensitivity is therefore particularly acute when former health ministers appear to profit from healthcare related work after leaving office. Milburn never became synonymous with scandal in the way Cameron later would. Instead, he became something more significant: an early warning sign. His career showed how former ministers could build highly lucrative private sector roles rooted largely in expertise acquired while exercising public power.' },

    { type: 'heading', level: 3, text: '20. Patricia Hewitt' },
    { type: 'paragraph', text: 'In March 2010, Channel 4’s Dispatches and The Sunday Times conducted a joint undercover investigation, with reporters posing as representatives of a fictitious American lobbying company. The investigation ensnared six politicians in total: Stephen Byers, Geoff Hoon, Patricia Hewitt, Margaret Moran, Adam Ingram and Sir John Butterfill. Byers was recorded offering himself "like a sort of cab for hire" for up to £5,000 a day. Hoon offered to lead delegations to ministers and said he charged £3,000 a day. Hewitt was recorded claiming she had helped to obtain a key seat on a government advisory group for a client paying her £3,000 a day.' },
    { type: 'paragraph', text: 'All four sitting MPs (Byers, Hoon, Hewitt and Moran) were suspended from the Labour Party pending investigation. However, the subsequent Standards and Privileges Committee investigation dismissed complaints against Hewitt and Ingram. The committee found there was "no suggestion" Hewitt had engaged in any lobbying of ministers and that she had taken the necessary steps regarding her private sector work. Byers received a two year pass suspension, Hoon a five year suspension for a "particularly serious breach."' },
    { type: 'paragraph', text: 'Hewitt was formally cleared, and that distinction matters. The episode proved politically damaging because the broadcast footage appeared to confirm public suspicions, regardless of what the formal investigation subsequently found. The scandal landed during a period of already low public trust following the parliamentary expenses crisis. The questions raised then remain largely unresolved today.' },
  ],
};

export default piece;
