import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'px4n9mxw7r',
  kicker: 'Justice',
  headline: `Government Calls Tagging Regime Britain's Toughest Ever as Inspectors Warn of 'False Sense of Assurance'`,
  standfirst: `From 1 October, the government says offenders leaving prison will face the toughest supervision in British history, with expanded tagging, new location restriction zones and near-live data access for probation staff. Two days earlier, HM Inspectorate of Probation warned the system risks creating a "false sense of assurance" if technology is not matched by effective practice. The National Audit Office said in July that further expansion "will not be effective or efficient" without fixing weaknesses in governance and data quality that the department has already identified.`,
  publishedAt: '2026-10-01',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `The government says offenders leaving prison from today will face the toughest supervision in British history.` },
    { type: 'paragraph', text: `Two days earlier, inspectors warned that the electronic monitoring system at the heart of that promise risks creating a "false sense of assurance."` },
    { type: 'paragraph', text: `The new regime expands tagging, introduces "world-first" restriction zones confining some high-risk sexual and violent offenders to an area just a few miles wide, bans others from pubs, clubs and public events such as football matches, and gives probation staff near-live access to location data. Random drug testing for thousands of offenders is due to launch next year. Ministers say this will help spot breaches faster and keep offenders away from victims and sensitive locations.` },
    { type: 'paragraph', text: `There is a defensible reason for doing it. Prisons are under severe pressure and electronic monitoring can allow more offenders to be managed in the community while still imposing restrictions on where they go and what they do.` },
    { type: 'paragraph', text: `But expanding the technology is not the same as proving the supervision works.` },
    { type: 'paragraph', text: `On 29 September, HM Inspectorate of Probation and HM Inspectorate of Constabulary and Fire & Rescue Services published an early briefing from a joint inspection of electronic monitoring.` },
    { type: 'paragraph', text: `Chief Inspector of Probation Martin Jones said "electronic monitoring is expanding rapidly, but the systems, processes and frontline practice needed to make it effective have not kept pace." He warned there is "a real danger that electronic monitoring creates a false sense of assurance if the technology is not matched by effective professional practice," and that doing so risks "overpromising and underdelivering on public protection."` },
    { type: 'paragraph', text: `That warning lands awkwardly beside the government's claim that offenders will now be under unprecedented control.` },
    { type: 'paragraph', text: `The Ministry of Justice says near-live access to location data will help probation staff act quickly when somebody breaches a restriction.` },
    { type: 'paragraph', text: `The independent evidence says the problem has never simply been whether a tag can generate data.` },
    { type: 'paragraph', text: `It is what happens once the data arrives.` },
    { type: 'paragraph', text: `The National Audit Office found in July that police and probation staff often lacked either the information or the capacity to respond quickly to breaches. It also found high volumes of alerts and breach notifications creating significant work with limited value. Where outcomes were recorded, nearly half ended with no further action.` },
    { type: 'paragraph', text: `That does not mean the alerts were pointless. Some will have represented low-level or explainable breaches.` },
    { type: 'paragraph', text: `It does mean that generating more data can also generate more workload.` },
    { type: 'paragraph', text: `The government is now adding more people, more restrictions and more location information to a system auditors already considered inefficient.` },
    { type: 'paragraph', text: `The NAO's conclusion was blunter than a general warning to tread carefully: "Further expansion of the EM system will not be effective or efficient unless MoJ and HMPPS work with stakeholders to address weaknesses in governance, data quality and system-wide inefficiencies to support a more reliable and responsive service."` },
    { type: 'paragraph', text: `The expansion has gone ahead anyway, and at scale.` },
    { type: 'paragraph', text: `The NAO's report confirms the government has already allocated up to £175 million to fund the expansion over the 2026 to 2029 spending review period, on top of a Ministry of Justice projection that up to 22,000 additional people a year may need to be tagged from 2027 onwards. That is a substantial addition of load onto a system the same report says is not yet working as intended.` },
    { type: 'paragraph', text: `There has been progress since the worst of the earlier failures.` },
    { type: 'paragraph', text: `Serco, which fits and monitors tags under the current contract, improved its timeliness after serious early problems. The backlog of visits to fit, check or remove tags peaked at around 7,000 in October 2024 and had fallen below 400 by the following month.` },
    { type: 'paragraph', text: `By February 2026, Serco was meeting its 95 per cent timeliness target for fitting visits.` },
    { type: 'paragraph', text: `But even then, a tag was successfully fitted in only 62 per cent of cases within the contractor's first two attempts.` },
    { type: 'paragraph', text: `The number of people in the system is already large.` },
    { type: 'paragraph', text: `Official figures show 27,847 people were assigned electronic monitoring equipment at the end of June 2026, a 3 per cent fall from 28,687 at the end of March, reflecting 22,322 order completions against 19,512 new orders in between. Even with that net fall, the churn through the system each quarter runs into tens of thousands of cases.` },
    { type: 'paragraph', text: `The government plans to expand further.` },
    { type: 'paragraph', text: `The Ministry of Justice says there will now be a presumption that offenders are electronically monitored after release, backed by £100 million for tagging as part of a wider £700 million package for probation and community punishment. It also says 1,300 additional probation staff are being recruited.` },
    { type: 'paragraph', text: `Those extra staff matter because the NAO estimated in March that probation was around 2,200 staff short.` },
    { type: 'paragraph', text: `So even after the announced recruitment, staffing remains part of the test rather than a solved problem.` },
    { type: 'paragraph', text: `There is another important distinction in the older data.` },
    { type: 'paragraph', text: `The NAO said HMPPS was reviewing around 8,900 cases (24 per cent of all those required to be tagged) in March, to determine how many people subject to monitoring requirements were not actually being monitored.` },
    { type: 'paragraph', text: `That figure should not be described as 8,900 offenders simply walking around with broken or missing tags.` },
    { type: 'paragraph', text: `The NAO said the review included some cases that remained active in error, while devices disconnected for 14 days or more were counted separately.` },
    { type: 'paragraph', text: `But the fact that HMPPS did not have a clean answer for how many of a quarter of its entire tagged caseload were genuinely unmonitored was itself a problem.` },
    { type: 'paragraph', text: `A supervision system cannot provide much reassurance if the department running it is uncertain about who is actually being monitored.` },
    { type: 'paragraph', text: `The government is also relying on tagging more heavily because of decisions being made elsewhere in the criminal justice system.` },
    { type: 'paragraph', text: `The new sentencing framework brings some offenders to an earlier possible release point, while the government says those convicted of rape, "serious and historic child sex offences such as grooming," manslaughter, and death by dangerous or drunk driving will continue to be excluded and kept in custody longer.` },
    { type: 'paragraph', text: `That increases the importance of community supervision.` },
    { type: 'paragraph', text: `If offenders spend less time in custody, the controls imposed after release have to work.` },
    { type: 'paragraph', text: `The government's case is therefore stronger than a simple law-and-order slogan.` },
    { type: 'paragraph', text: `It needs electronic monitoring because prison capacity is constrained and because more of the sentence is being managed outside prison for some offenders.` },
    { type: 'paragraph', text: `But that makes the inspectorate warning more important, not less.` },
    { type: 'paragraph', text: `The question is not whether a GPS tag knows where somebody is.` },
    { type: 'paragraph', text: `It usually does.` },
    { type: 'paragraph', text: `The question is whether probation and police can interpret the information, distinguish serious risk from noise and act quickly enough when something matters.` },
    { type: 'paragraph', text: `The government says the new system represents the toughest supervision in British history.` },
    { type: 'paragraph', text: `Its own independent watchdogs are saying something more cautious, in increasingly direct terms: expansion now, the NAO says, will not work unless the underlying weaknesses are fixed first, and £175 million and a projected 22,000 extra cases a year are being committed before that fix has happened.` },
    { type: 'paragraph', text: `The technology has expanded faster than the system around it.` },
    { type: 'paragraph', text: `Until that gap closes, tougher restrictions on paper do not automatically mean tougher supervision in practice.` },
  ],
  evidence: {
    recordsReviewed: [
      'GOV.UK, 1 October 2026: "Toughest restrictions ever imposed on offenders on licence" — scheme design (presumption of tagging, world-first restriction zones, pub/club/event bans, random drug testing from next year, near-live location data), £100m/£700m funding figures, 1,300 additional probation staff, sentencing-framework exclusions (rape, serious/historic child sex offences including grooming, manslaughter, death by dangerous/drunk driving)',
      'HM Inspectorate of Probation / HMICFRS, "Electronic monitoring in practice" early briefing, 29 September 2026 — Chief Inspector Martin Jones quotes on expansion outpacing frontline practice, "false sense of assurance" warning, "overpromising and underdelivering on public protection" risk',
      'National Audit Office, "Electronic monitoring: improving resilience to meet increasing demand," July 2026 — breach-response findings, "nearly half no further action" outcome figure, Serco backlog (peak ~7,000 October 2024, below 400 following month), 95% timeliness target met by February 2026, 62% fitting success within two attempts, ~2,200 probation staff shortfall, 8,900 cases/24% review figure, £175m 2026 to 2029 expansion funding, 22,000 additional people projected annually from 2027, direct "not effective or efficient" wording on further expansion without fixing governance/data weaknesses',
      'Ministry of Justice, Electronic Monitoring Statistics Publication, England and Wales: June 2026 — 27,847 individuals assigned EM equipment at 30 June 2026 (down 3% from 28,687 at 31 March 2026); 19,512 new orders against 22,322 completions between April and June 2026',
    ],
    lastChecked: '1 October 2026',
  },
};

export default piece;
