import type { EditorialEntry } from './types';

// Third in the Harborne / Reform crypto series. Every claim verified: the bill
// text and drafting errors are quoted verbatim from the published PDF; the
// deletion, £18.2bn Rich List figure, £20,000 stablecoin cap column and the
// Bank dropping it, the digital-pound lobbying, and the £275,650 Stack BTC
// investment are all sourced (The Nerve, Sunday Times, Telegraph, Bloomberg).
// Hardened: Farage's denials are included, the approach for comment is noted,
// and it ends on the open question rather than an asserted conclusion.
const piece: EditorialEntry = {
  slug: 'q7m3k9xw2r',
  kicker: 'Money and Power',
  headline: 'The Only Bill Reform UK Ever Wrote',
  standfirst:
    'Cryptocurrency did not appear in Reform UK’s 2024 manifesto. Within a year the party had published the only draft bill in its history, and every major provision would benefit the commercial interests of the donor who funds two thirds of it. The bill has since been quietly deleted. Here is the documented record.',
  publishedAt: '2026-07-01',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: 'Cryptocurrency was not mentioned in Reform UK’s 2024 manifesto. Not once. The word does not appear. The party’s official position on digital assets was a single line on page 24 opposing a Central Bank Digital Currency. That was it.' },
    { type: 'paragraph', text: 'Less than a year later, in May 2025, Nigel Farage stood on stage at the Bitcoin 2025 conference in Las Vegas and held up a printed copy of the Cryptoassets and Digital Finance Bill. He told the audience: “Months of work, ladies and gentlemen, we will campaign for this and we’ll put it in place when we win the next general election.” It was the first and only draft bill Reform UK has ever published.' },
    { type: 'paragraph', text: 'The bill proposed six things. A flat 10 percent capital gains tax on all cryptocurrency gains, cutting the current rate from 24 percent by more than half. A sovereign Bitcoin Reserve Fund held as part of the UK’s official reserves, managed by the Treasury, with quarterly reporting to Parliament. A legal duty on HMRC to build systems to accept Bitcoin for tax payments. A ban on banks refusing service to crypto users, with the burden of proof reversed so the bank must justify any refusal rather than the customer proving discrimination. A two year regulatory sandbox giving crypto firms temporary exemption from financial services rules. And a 90 day time limit on any government taskforce examining crypto policy, to prevent what the bill calls “bureaucratic drift.”' },
    { type: 'paragraph', text: 'At the same conference, Farage announced that Reform UK had become the first UK political party to accept donations in Bitcoin and Ethereum.' },
    { type: 'paragraph', text: 'The bill was removed from Reform UK’s website at the end of May 2026. The landing page at reformparty.uk/cryptobill and the PDF at reformparty.uk/reform-crypto-bill.pdf both now return 404 errors. Reform UK’s website is configured to block the Wayback Machine from archiving its pages through robots.txt, meaning no archived copy exists on the internet’s standard preservation tool. The only surviving public copy is on Scribd, uploaded by a third party the day after the Las Vegas launch. When The Nerve contacted Reform UK to ask why the bill was removed and whether the party still supported its provisions, they did not respond.' },
    { type: 'paragraph', text: 'The deletion came after it was reported that Farage was being investigated by the Parliamentary Standards Commissioner over a £5 million personal gift from Christopher Harborne, a British Thai billionaire who owns approximately 12 percent of Tether, the company that issues the world’s most traded stablecoin. Harborne’s wealth is estimated at £18.2 billion by the Sunday Times 2026 Rich List. His fortune depends substantially on the success of stablecoins and the wider cryptocurrency ecosystem.' },
    { type: 'paragraph', text: 'Harborne has donated more than £22 million to Reform UK and its predecessor the Brexit Party, roughly two thirds of all funding the party has received since its foundation. The £5 million personal gift to Farage was made in the spring of 2024, weeks before Farage reversed his decision not to stand for Parliament. It was not declared. It is now the subject of a formal inquiry by the Standards Commissioner and is being assessed by the Electoral Commission.' },
    { type: 'pullQuote', text: 'The bill’s provisions and the donor’s commercial interests are a matter of public record.' },
    { type: 'paragraph', text: 'Section 1 of the bill would cut capital gains tax on crypto from 24 percent to 10 percent. Every crypto holder in Britain would benefit, including Harborne.' },
    { type: 'paragraph', text: 'Section 4 would create a sovereign Bitcoin Reserve Fund as part of the UK’s official reserves. A UK government reserve holding Bitcoin would legitimise the wider cryptocurrency ecosystem on which Harborne’s wealth depends. The bill specifies that “Bitcoin must be the principal holding of the Fund” and that its objectives include “signalling confidence in digital assets.”' },
    { type: 'paragraph', text: 'Section 5 would require HMRC to accept Bitcoin for tax payments from the day the bill comes into force. Bitcoin is named specifically as an approved cryptoasset in the legislation.' },
    { type: 'paragraph', text: 'Section 3 would make it illegal for banks to refuse service to crypto users and reverse the burden of proof so the bank must justify any refusal. This directly addresses the anti-money-laundering practice of “de-risking,” in which banks close accounts they judge to be high risk. Tether and businesses connected to it have faced banking difficulties. The bill would make those refusals legally challengeable.' },
    { type: 'paragraph', text: 'Four months after launching the bill, Farage and Reform chairman Zia Yusuf wrote a column in the Telegraph attacking the Bank of England’s £20,000 cap on individual holdings of sterling stablecoins. Removing the cap would benefit stablecoin issuers. Harborne owns 12 percent of the world’s largest one. The Bank subsequently dropped the cap.' },
    { type: 'paragraph', text: 'Farage also lobbied the Bank of England to abandon plans for a state-backed digital pound, which he called “the ultimate form of tyranny.” A state-backed digital pound would compete directly with commercial stablecoins like Tether.' },
    { type: 'paragraph', text: 'Farage personally invested £275,650 in Stack BTC, a bitcoin business chaired by former Chancellor Kwasi Kwarteng.' },
    { type: 'paragraph', text: 'The drafting quality of the bill itself has drawn scrutiny. Section 2(5) does not parse as a complete sentence. Section 4(6)(c) contains a typographical error, writing “though” instead of “through.” Section 6(5) uses the American spelling “endeavors” in a document formatted as an Act of the UK Parliament. The Nerve described it as reading like “this was made up by a schoolkid.” It is the only draft legislation the party has ever produced.' },
    { type: 'paragraph', text: 'Phil Brickell MP, chair of the All Party Parliamentary Group on Anti-Corruption and Responsible Tax, said: “I think Reform have realised they’ve been caught out and are now backtracking. But this issue will not go away until Farage discloses the contents of correspondence and meetings he has had with his cryptobillionaire donors.”' },
    { type: 'paragraph', text: 'Farage has said he speaks to Harborne “maybe once a month, maybe once every six weeks” and has insisted “I’ve not promised him a single thing in return for his donation.” He told the BBC the £5 million was “none of your business” and said he could spend it on “cars if I want to.” He has described himself as someone who “can’t be bought by anybody.” Harborne, who almost never comments publicly, said in a statement to the Telegraph that he gave the money out of “great admiration for the decades of work [Farage] had done to achieve Brexit,” and Reform has said the gift was made on a completely unconditional basis.' },
    { type: 'paragraph', text: 'The documented record is this. A party that did not mention cryptocurrency in its manifesto produced, within a year, the only draft bill it has ever published. That bill would cut crypto tax by more than half, create a government Bitcoin reserve, force banks to serve crypto businesses and allow tax payments in Bitcoin. The provisions of the bill and the commercial interests of the party’s largest donor are a matter of public record. Both are documented above. The bill has been deleted from the party’s website. The party’s website blocks internet archiving. The party did not respond when asked why.' },
    { type: 'paragraph', text: 'Those are the facts. What they add up to is for the reader to decide.' },
    { type: 'cta', text: 'Read the documented record: Christopher Harborne, Nigel Farage and £30 million', href: '/editorials/hb9k2xq7mw' },
  ],
};

export default piece;
