import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'qm4n9mxw7r',
  kicker: 'Regeneration',
  headline: `Government Announces £210m High Street 'Boost' Using Money Already Earmarked for Regeneration`,
  standfirst: `The government announced a £210 million package on 25 September to tackle derelict buildings and struggling high streets in England. Its own announcement states the money comes from funding already earmarked for high-street support and regeneration. At least £10 million of the package appears in at least two earlier government documents published since March 2026, inside a £301 million high-street programme announced that month.`,
  publishedAt: '2026-09-25',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `The government has announced a £210 million package to tackle boarded-up shops, derelict buildings and struggling high streets across England.` },
    { type: 'paragraph', text: `The money is real.` },
    { type: 'paragraph', text: `What is less clear from the headline is that it is not a new £210 million addition to public spending.` },
    { type: 'paragraph', text: `At the bottom of the government's own announcement, the Ministry of Housing, Communities and Local Government states that the package comes from funding already earmarked for high-street support and regeneration.` },
    { type: 'paragraph', text: `That makes the announcement a decision about how existing money will be used, rather than a fresh £210 million injection.` },
    { type: 'paragraph', text: `The distinction matters because ministers presented the package as new action to revive town centres, with £125 million for a Derelict Buildings Fund, £65 million for community assets at risk of closure (pubs, sports clubs and similar businesses), £10 million for High Street Rental Auctions and £10 million for a new regional Co-operative Development Programme.` },
    { type: 'paragraph', text: `There is a defensible case for the spending. Empty commercial buildings can drag down footfall and confidence, while government evaluation of an earlier regeneration programme found that targeted high-street investment was associated with a stronger recovery in footfall than comparable towns.` },
    { type: 'paragraph', text: `But that does not turn previously allocated money into new money.` },
    { type: 'paragraph', text: `The government's presentation should be judged against what had already been announced.` },
    { type: 'paragraph', text: `In March, MHCLG announced a £301 million High Streets Innovation Partnerships programme, describing it as funding to revive struggling high streets and turn town centres into mixed-use spaces including homes, health services, libraries and community hubs.` },
    { type: 'paragraph', text: `By June, the department was describing a £61 million Community Right to Buy Fund as part of that same £301 million package.` },
    { type: 'paragraph', text: `A separate government document setting out plans for music venues, published later in the year, also confirmed that £10 million of that same funding commitment would go toward High Street Rental Auctions "to bring vacant properties back into use."` },
    { type: 'paragraph', text: `The September £210 million announcement again allocates £10 million to High Street Rental Auctions.` },
    { type: 'paragraph', text: `That strongly suggests at least that portion of the new headline package is money already sitting inside the earlier high-street programme, referenced independently in at least two separate government documents before September's announcement, rather than an additional £10 million announced on top of it.` },
    { type: 'paragraph', text: `The government does not claim otherwise in the small print. It explicitly says the £210 million comes from previously earmarked MHCLG funding.` },
    { type: 'paragraph', text: `The problem is the gap between that accounting reality and the political presentation.` },
    { type: 'paragraph', text: `A reader seeing a new £210 million high-street package could reasonably assume government spending on regeneration had just increased by £210 million.` },
    { type: 'paragraph', text: `The department's own wording shows that is not what happened.` },
    { type: 'heading', level: 2, text: `Several high-street packages have now been announced in the same year` },
    { type: 'paragraph', text: `The September package is only the latest in a series.` },
    { type: 'paragraph', text: `On 2 February, government confirmed £150 million for high streets, targeted at areas with empty shops and declining town centres.` },
    { type: 'paragraph', text: `In March came the £301 million High Streets Innovation Partnerships programme.` },
    { type: 'paragraph', text: `In June, ministers announced the £61 million Community Right to Buy Fund as part of that wider £301 million package.` },
    { type: 'paragraph', text: `Now September brings another £210 million headline.` },
    { type: 'paragraph', text: `Those figures cannot simply be added together.` },
    { type: 'paragraph', text: `Some sit inside wider funding envelopes already announced.` },
    { type: 'paragraph', text: `That is precisely why every new package needs to say clearly whether the money is additional, reallocated or simply the next tranche of a previously announced pot.` },
    { type: 'paragraph', text: `In this case, government has supplied the answer.` },
    { type: 'paragraph', text: `The £210 million was already earmarked.` },
    { type: 'heading', level: 2, text: `The £125 million Derelict Buildings Fund is new in design, not necessarily in money` },
    { type: 'paragraph', text: `The largest part of the September announcement is a new £125 million Derelict Buildings Fund.` },
    { type: 'paragraph', text: `Local authorities will be able to use it to convert vacant shopping centres, cinemas and other disused buildings into community hubs, health centres, workspaces or other uses.` },
    { type: 'paragraph', text: `That may be a genuinely new programme.` },
    { type: 'paragraph', text: `But a new programme is not the same thing as new spending.` },
    { type: 'paragraph', text: `Government can create a new fund by reallocating money from an existing departmental settlement.` },
    { type: 'paragraph', text: `That appears to be what has happened here.` },
    { type: 'paragraph', text: `The distinction is important for assessing whether ministers have increased the resources available to high streets or simply renamed and redirected money they already controlled.` },
    { type: 'paragraph', text: `The press release does not provide a detailed reconciliation showing which previous budget lines supplied each part of the £210 million.` },
    { type: 'paragraph', text: `Without that, it is difficult to determine how much represents a new commitment within an existing envelope and how much was already attached to programmes announced earlier in the year.` },
    { type: 'heading', level: 2, text: `There is evidence that regeneration money can work` },
    { type: 'paragraph', text: `The policy should not be dismissed simply because the funding is recycled.` },
    { type: 'paragraph', text: `An evaluation of the earlier Towns Fund, published by MHCLG on 17 July 2026, found measurable benefits.` },
    { type: 'paragraph', text: `In the ten towns with case-study projects specifically targeting civic pride, pride in place improved by a statistically significant 3.8 percentage points following project completion, against no change nationally or in wider local authorities over the same 2023 to 2025 period.` },
    { type: 'paragraph', text: `Towns that received Future High Streets Fund money also recorded a 6.7 per cent stronger recovery in footfall than similar non-funded towns, reaching 97.9 per cent of pre-pandemic footfall against 91.3 per cent in the towns that received no funding.` },
    { type: 'paragraph', text: `That is useful evidence in favour of targeted regeneration spending.` },
    { type: 'paragraph', text: `It is also a reminder that the useful question is not how many funding announcements government can produce.` },
    { type: 'paragraph', text: `It is what happens after the money is allocated.` },
    { type: 'paragraph', text: `The September announcement promises renovated buildings, protected pubs and clubs, new community spaces and more occupied shops.` },
    { type: 'paragraph', text: `Those outcomes should be measured against actual vacancy rates, footfall and completed projects rather than against the size of the original headline.` },
    { type: 'heading', level: 2, text: `High Street Rental Auctions are still at an early stage` },
    { type: 'paragraph', text: `The government is putting another £10 million of the package towards High Street Rental Auctions.` },
    { type: 'paragraph', text: `The policy allows councils, after a statutory process, to arrange the letting of qualifying commercial premises that have remained vacant for prolonged periods.` },
    { type: 'paragraph', text: `There are signs the policy can produce results.` },
    { type: 'paragraph', text: `Rugby Borough Council reported in September that five long-term empty units had been let through rental auctions.` },
    { type: 'paragraph', text: `But implementation across England remains uneven.` },
    { type: 'paragraph', text: `Some councils were still consulting on whether and where to use the powers during 2026.` },
    { type: 'paragraph', text: `That makes it too early to treat High Street Rental Auctions as a proven national solution to commercial vacancy.` },
    { type: 'paragraph', text: `The government is putting more money behind the policy before a full national outcome picture is available, and that £10 million appears to be the same £10 million already attached to this purpose inside the March commitment, not fresh resource for an unproven programme.` },
    { type: 'paragraph', text: `That may be reasonable for an emerging programme, but it should be described as expansion, not success already achieved, and it should not be counted twice in the public's sense of what government has committed.` },
    { type: 'heading', level: 2, text: `The bigger problem is announcement accounting` },
    { type: 'paragraph', text: `There is nothing inherently wrong with government repurposing money.` },
    { type: 'paragraph', text: `Departments routinely alter programmes as priorities change.` },
    { type: 'paragraph', text: `A £125 million fund can still improve town centres even if the Treasury authorised the overall spending months earlier.` },
    { type: 'paragraph', text: `The accountability problem starts when the same underlying funding can generate several political announcements.` },
    { type: 'paragraph', text: `A £301 million high-street programme announced in March can contain individual funds announced again later, confirmed in at least two further documents published across the following six months.` },
    { type: 'paragraph', text: `Those funds can then appear inside another £210 million package in September.` },
    { type: 'paragraph', text: `Each announcement may be technically accurate.` },
    { type: 'paragraph', text: `But without careful accounting, the public can be left with an inflated impression of how much additional money government has actually committed.` },
    { type: 'paragraph', text: `The September press release contains the crucial sentence itself: the £210 million is from funding already earmarked for high-street support and regeneration.` },
    { type: 'paragraph', text: `That should not be treated as small print.` },
    { type: 'paragraph', text: `It is the central fact needed to understand the announcement.` },
    { type: 'paragraph', text: `The government has changed how £210 million will be spent.` },
    { type: 'paragraph', text: `It has not found another £210 million.` },
  ],
  evidence: {
    recordsReviewed: [
      'GOV.UK, "Boarded-up high streets brought back to life with £210m boost," 25 September 2026 — £210m total and breakdown (£125m Derelict Buildings Fund, £65m community assets, £10m High Street Rental Auctions, £10m Co-operative Development Programme), "funding already earmarked for high street support and regeneration" wording',
      'GOV.UK, "High streets revived and children given safe places to play," 21 March 2026 — £301 million High Streets Innovation Partnerships programme and its stated purpose',
      'GOV.UK, "Pubs, shops and local assets protected with communities in charge," 16 June 2026 — £61 million Community Right to Buy Fund confirmed as "part of the £301 million announced by the government"',
      'GOV.UK, "Turn It Up: our plan for music" — independent confirmation that £10 million of the same funding commitment was earmarked for High Street Rental Auctions',
      'MHCLG, Towns Fund evaluation: final findings, 17 July 2026 — 3.8 percentage-point pride-in-place improvement in ten case-study towns; 6.7% footfall recovery advantage for Future High Streets Fund towns vs similar non-funded towns (97.9% vs 91.3% of pre-pandemic footfall)',
      'UK Parliament, Written Ministerial Statement, 2 February 2026 — £150 million high streets commitment confirmed',
    ],
    lastChecked: '25 September 2026',
  },
};

export default piece;
