import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'qn4k9mxw7r',
  kicker: 'Accountability',
  headline: `Government Rewrites Public Consultation Rules While Keeping New Guidance Unpublished`,
  standfirst: `The Cabinet Office is rewriting the rules governing public consultation while keeping its replacement guidance unpublished. Ministers have confirmed the existing Consultation Principles will be amended, and that new internal guidance already circulated to departments will not be placed in the Commons Library. Departments are already operating under the new instructions.`,
  publishedAt: '2026-09-10',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `The government is rewriting the rules that tell Whitehall when and how to consult the public, as ministers push departments to make decisions faster and rely less on formal consultation.` },
    { type: 'paragraph', text: `The Cabinet Office announced on 10 September that departments will be expected to reduce what it calls unnecessary "box-ticking" consultations, arguing that ministers have become too dependent on lengthy administrative processes instead of making decisions.` },
    { type: 'paragraph', text: `But a subsequent parliamentary answer revealed something the announcement did not.` },
    { type: 'paragraph', text: `The Cabinet Office has already circulated new general guidance to departments and says there is currently no plan to place it in the House of Commons Library. It has also confirmed that the existing government-wide Consultation Principles will be amended.` },
    { type: 'paragraph', text: `That means ministers and officials are already being given new instructions about consultation before the replacement public rules have been published.` },
    { type: 'heading', level: 2, text: `Ministers told to use their power` },
    { type: 'paragraph', text: `The change forms part of a wider attempt to strengthen ministerial control over Whitehall.` },
    { type: 'paragraph', text: `On 7 September, Chancellor John Healey, First Secretary Louise Haigh and Attorney General Ellie Reeves wrote jointly to ministers saying the government intended to act "with the full agency that sits with the executive, and which flows from our command of a majority in the House of Commons."` },
    { type: 'paragraph', text: `The letter told ministers they should be "empowered to accept higher levels of risk where you feel it is warranted," and that legal caution should not hold up a decision where there is merely "a tenable legal argument" for it, rather than certainty.` },
    { type: 'paragraph', text: `It also stated plainly that "there is no general duty of consultation", a legal position that underpins everything that followed three days later.` },
    { type: 'paragraph', text: `Three days later the Cabinet Office announced the consultation reforms.` },
    { type: 'paragraph', text: `It said ministers had been told to end the "comfort blanket" of unnecessary consultation and argued that excessive process had delayed decisions for years.` },
    { type: 'paragraph', text: `The government says a bespoke AI tool identified around 7,000 consultation duties across the statute book.` },
    { type: 'paragraph', text: `It cited two examples.` },
    { type: 'paragraph', text: `The introduction of folic acid into flour was delayed for seven years, becoming "trapped in duplicate consultations" despite overwhelmingly positive responses. Between 2019 and 2023, the government asked the public three times for views on legislation to microchip cats — including, at one stage, gathering views on the legal definition of a cat.` },
    { type: 'paragraph', text: `The Cabinet Office argues that such exercises demonstrate how consultation can become an obstacle to decisions rather than a way of improving them.` },
    { type: 'heading', level: 2, text: `Existing rules already say not to consult unnecessarily` },
    { type: 'paragraph', text: `There is an awkward feature of that argument.` },
    { type: 'paragraph', text: `The existing Cabinet Office Consultation Principles already tell departments not to consult simply for the sake of it. Principle 2 is explicit: "Do not consult for the sake of it. Ask departmental lawyers whether you have a legal duty to consult."` },
    { type: 'paragraph', text: `They say consultation should happen while policy is still at "a formative stage," that departments should not seek opinions on matters where ministers have already reached a final decision, and that the length of a consultation should be judged against "the nature and impact of the proposal" rather than run to a fixed template.` },
    { type: 'paragraph', text: `The current rules also contain safeguards.` },
    { type: 'paragraph', text: `Departments are told to give enough information for people to understand a proposal and respond intelligently.` },
    { type: 'paragraph', text: `They should consider the full range of people, businesses and voluntary bodies affected by the policy.` },
    { type: 'paragraph', text: `They should explain the responses received and how these informed the final decision.` },
    { type: 'paragraph', text: `And they should normally publish that response within 12 weeks of the consultation closing.` },
    { type: 'paragraph', text: `The principles have no independent force of law.` },
    { type: 'paragraph', text: `But they establish the government's own standard for how departments should seek public views.` },
    { type: 'paragraph', text: `The Cabinet Office has now confirmed that those principles will be changed.` },
    { type: 'paragraph', text: `It has not yet published the replacement version.` },
    { type: 'heading', level: 2, text: `Internal guidance will not currently be released through Parliament` },
    { type: 'paragraph', text: `The position emerged after Conservative MP Mike Wood questioned the Cabinet Office about the government's new approach.` },
    { type: 'paragraph', text: `He asked whether the Consultation Principles would be amended and whether new general guidance already circulated by officials would be placed in the Commons Library.` },
    { type: 'paragraph', text: `Cabinet Office minister Mark Ferguson confirmed the principles would change: "we will amend the Cabinet Office Consultation Principles."` },
    { type: 'paragraph', text: `He added:` },
    { type: 'paragraph', text: `"There is no current plan to place the new general guidance in the library."` },
    { type: 'paragraph', text: `The answer does not mean the document is legally secret, nor does it establish that ministers are concealing improper instructions.` },
    { type: 'paragraph', text: `But it means Parliament and the public cannot currently compare the guidance being used inside Whitehall with the existing published standards.` },
    { type: 'paragraph', text: `That matters because the government is not merely shortening individual consultations.` },
    { type: 'paragraph', text: `It is changing the framework departments use to decide whether a formal consultation should happen at all.` },
    { type: 'heading', level: 2, text: `Legal duties to consult remain` },
    { type: 'paragraph', text: `The reforms do not give ministers an unrestricted power to stop consulting.` },
    { type: 'paragraph', text: `Some consultation requirements are written directly into legislation.` },
    { type: 'paragraph', text: `Public bodies can also acquire a legal duty to consult because they have promised to do so, because an established practice creates a legitimate expectation, or because failing to consult in particular circumstances would be procedurally unfair.` },
    { type: 'paragraph', text: `When a consultation is legally required, public bodies must still follow principles developed through case law.` },
    { type: 'paragraph', text: `Those include consulting while proposals remain genuinely open, providing enough information for meaningful responses, allowing adequate time and conscientiously considering what people say.` },
    { type: 'paragraph', text: `These are commonly known as the Gunning principles.` },
    { type: 'paragraph', text: `Mike Wood put the same pressure on this question, asking the Attorney General's Office directly whether it intended to legislate to remove them.` },
    { type: 'paragraph', text: `Responding on the Attorney General's behalf, Andy Slaughter said the government "currently has no plans to legislate to disapply the Gunning principles," which will still apply in exceptional circumstances.` },
    { type: 'paragraph', text: `But the answer also reveals how narrowly the government now wants formal consultation used. Those exceptional circumstances are: where there is a statutory requirement to consult, where failing to consult would be "conspicuously unfair", or where ministers themselves decide there is good reason to seek outside views through a formal consultation.` },
    { type: 'paragraph', text: `That leaves significant discretion with ministers.` },
    { type: 'heading', level: 2, text: `Infrastructure is part of the same push` },
    { type: 'paragraph', text: `The consultation changes sit alongside a wider programme aimed at speeding up major infrastructure decisions.` },
    { type: 'paragraph', text: `The Cabinet Office says Parliament will be empowered to "designate and approve the country's most important infrastructure projects" with enhanced protection from legal challenge, while a fixed "Challenge Window" is intended to ensure that points of legal challenge are identified and addressed earlier in the process, rather than surfacing after consent has already been granted.` },
    { type: 'paragraph', text: `The government's 7 September letter also argues that administrative and legal risk have increasingly constrained executive decision-making, hence its explicit instruction that ministers should accept a merely "tenable" legal argument rather than requiring certainty before acting.` },
    { type: 'paragraph', text: `The stated aim is to make ministers take greater responsibility for decisions rather than outsourcing difficult choices to regulators, consultations and other processes.` },
    { type: 'paragraph', text: `For major infrastructure, that could reduce delays.` },
    { type: 'paragraph', text: `It could also reduce the opportunities available to residents, businesses, environmental organisations and other affected groups to influence a proposal before a final decision is taken.` },
    { type: 'paragraph', text: `The effect will depend heavily on what replaces the current system.` },
    { type: 'heading', level: 2, text: `Government promises a different form of public participation` },
    { type: 'paragraph', text: `The Cabinet Office says fewer traditional consultations will not mean the end of public involvement.` },
    { type: 'paragraph', text: `It argues that long written exercises can favour organised interest groups and people already familiar with government processes rather than providing an accurate picture of wider public opinion.` },
    { type: 'paragraph', text: `Ministers have promised a new approach to public participation and new guidance on engagement later this autumn.` },
    { type: 'paragraph', text: `There is a reasonable argument for reform.` },
    { type: 'paragraph', text: `A consultation launched after ministers have effectively made their decision gives the appearance of participation without necessarily transferring any influence to the people responding.` },
    { type: 'paragraph', text: `The existing consultation rules themselves recognise that problem.` },
    { type: 'paragraph', text: `The unanswered question is what replaces those exercises.` },
    { type: 'paragraph', text: `A system involving earlier engagement with genuinely affected communities could give the public more influence rather than less.` },
    { type: 'paragraph', text: `A system that simply gives ministers greater freedom to decide that consultation is unnecessary would produce the opposite result.` },
    { type: 'paragraph', text: `At present, the government has published the argument for reducing consultation but not the complete framework that will govern what comes next.` },
    { type: 'heading', level: 2, text: `The test will be what disappears` },
    { type: 'paragraph', text: `The significance of the reform will therefore not be measured by how many pages of guidance Whitehall removes.` },
    { type: 'paragraph', text: `It will be measured by the decisions that would previously have been consulted on but no longer are.` },
    { type: 'paragraph', text: `The Cabinet Office has already told departments to reduce unnecessary consultations.` },
    { type: 'paragraph', text: `It has already circulated additional general guidance.` },
    { type: 'paragraph', text: `And it has confirmed that the public Consultation Principles will be rewritten.` },
    { type: 'paragraph', text: `But the internal guidance has not been placed in Parliament's Library, while the replacement public rules have yet to appear.` },
    { type: 'paragraph', text: `Ministers argue that government has become too reluctant to exercise the authority voters gave it, and their own letter states there is "no general duty of consultation" underpinning that argument in law.` },
    { type: 'paragraph', text: `The counterweight is straightforward.` },
    { type: 'paragraph', text: `Consultation is not supposed to prevent elected governments making decisions.` },
    { type: 'paragraph', text: `It is supposed to ensure they hear from the people affected before they make them.` },
    { type: 'paragraph', text: `Whether the government's reforms remove empty bureaucracy or weaken that opportunity will depend on a document the public has not yet seen.` },
  ],
  evidence: {
    recordsReviewed: [
      'Cabinet Office / GOV.UK, 10 September 2026: "Box-ticking consultations scrapped to speed up delivery" — ~7,000 consultation duties, folic acid and cat-microchipping examples, infrastructure Challenge Window',
      'Joint ministerial letter, 7 September 2026 (Healey, Haigh, Reeves): "The simplification and agency of government" — "full agency"/Commons-majority language, "tenable legal argument" instruction, "no general duty of consultation"',
      'UK Parliament written question answered 15 September 2026, asked by Mike Wood MP, answered by Cabinet Office minister Mark Ferguson — Consultation Principles to be amended; no plan to place new guidance in Commons Library',
      'Cabinet Office, Consultation Principles 2018 — Principle 2 (do not consult for its own sake), formative stage requirement, Principles 5/6/9/10 on proportionality, affected groups, explaining responses, 12-week publication',
      'UK Parliament written question answered 21 September 2026, asked by Mike Wood MP, answered by Andy Slaughter MP — no plans to disapply the Gunning principles; three remaining circumstances for formal consultation',
    ],
    lastChecked: '30 September 2026',
  },
};

export default piece;
