import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'qn4k9mxw7r',
  kicker: 'Accountability',
  headline: `Cabinet Office Circulates New Consultation Guidance Before Publishing Replacement Rules`,
  standfirst: `The Cabinet Office is changing the rules Whitehall uses to decide when the public should be formally consulted, while general guidance supporting the new approach has already been circulated inside government. The replacement Consultation Principles have not yet been published. A Cabinet Office minister told Parliament there is "no current plan" to place the new internal guidance in the Commons Library.`,
  publishedAt: '2026-09-10',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `The Cabinet Office is changing the rules Whitehall uses to decide when the public should be formally consulted, while general guidance supporting the new approach has already been circulated inside government.` },
    { type: 'paragraph', text: `The department has confirmed that the existing Cabinet Office Consultation Principles will be amended. Asked in Parliament whether the new general guidance would be placed in the House of Commons Library, Cabinet Office minister Mark Ferguson said there was "no current plan" to do so.` },
    { type: 'paragraph', text: `That does not mean the guidance is secret or that it will never be published elsewhere. The Cabinet Office has separately promised more detailed public-participation guidance later in the autumn.` },
    { type: 'paragraph', text: `For now, departments have been given a new cross-government direction on consultation before the replacement public principles have appeared.` },
    { type: 'paragraph', text: `The change began with a letter sent to all ministers on 7 September by Chancellor John Healey, First Secretary Louise Haigh and Attorney General Ellie Reeves.` },
    { type: 'paragraph', text: `It says the government will reassert that there is "no general duty of consultation" and that the default should be for ministers to reach decisions and act. Formal consultation, the letter says, should generally be reserved for three situations: where legislation requires it, where not consulting would be conspicuously unfair, or where ministers decide formal consultation is the right way to seek outside views.` },
    { type: 'paragraph', text: `The letter also says departments should reconsider consultation afresh even where government has historically consulted on an issue or previously promised to do so. Officials would circulate new general guidance, with more detailed guidance on public participation to follow.` },
    { type: 'paragraph', text: `That is a narrower starting point than the current published Consultation Principles.` },
    { type: 'paragraph', text: `The 2018 principles already tell departments "Do not consult for the sake of it" and instruct officials to check whether there is a legal duty before launching a consultation. They also say consultation should take place while proposals remain at a formative stage, should give people enough information to respond intelligently and should be targeted at the people and organisations affected.` },
    { type: 'paragraph', text: `The existing rules say responses should explain what consultees said and how those views informed policy. Government responses should normally be published within 12 weeks or departments should explain the delay. The document itself has no legal force and remains subject to statutory and other legal requirements.` },
    { type: 'paragraph', text: `The government is therefore not introducing the idea that pointless consultation should be avoided. That is already written into the rules.` },
    { type: 'paragraph', text: `The change is in the proposed default.` },
    { type: 'paragraph', text: `The current principles describe consultation as one part of an ongoing process of engagement and set standards for how it should be conducted. The September ministerial letter says formal consultation should take place only in the limited circumstances it identifies, while ministers should otherwise be more willing to decide and proceed.` },
    { type: 'paragraph', text: `The Cabinet Office says a bespoke AI tool has identified approximately 7,000 statutory duties to consult across the statute book. The figure was confirmed in a parliamentary answer on 14 September.` },
    { type: 'paragraph', text: `The government says it intends during this Parliament to unwind thousands of consultation and reporting requirements, beginning from a presumption that requirements should be repealed and retained only by exception. Departments have been told to look for opportunities to remove duties through legislation already being prepared.` },
    { type: 'paragraph', text: `Finding a statutory consultation requirement with an AI tool does not remove it. Duties written into legislation will continue to apply until Parliament changes the law.` },
    { type: 'paragraph', text: `The Cabinet Office has used folic-acid fortification and cat microchipping as examples of what it regards as consultation becoming excessive.` },
    { type: 'paragraph', text: `Its 10 September announcement says adding folic acid to flour was delayed for seven years amid duplicate consultations despite strong support, while government sought public views three times between 2019 and 2023 on compulsory cat microchipping, including on the legal definition of a cat.` },
    { type: 'paragraph', text: `The department argues that fewer lengthy written exercises could allow government to make decisions faster while replacing some formal consultations with earlier and more direct public participation.` },
    { type: 'paragraph', text: `That approach is not incompatible with the existing principles. The 2018 document already says consultation is not limited to formal written exercises and encourages informal, iterative and digital engagement where appropriate.` },
    { type: 'paragraph', text: `What has not yet been published is the complete replacement framework showing how departments should decide when those less formal methods are sufficient.` },
    { type: 'paragraph', text: `The legal duties that sit outside Cabinet Office guidance also remain.` },
    { type: 'paragraph', text: `Conservative MP Mike Wood asked the Attorney General whether the government intended to legislate to disapply the principles derived from the 1985 Gunning case and subsequent consultation case law.` },
    { type: 'paragraph', text: `Solicitor General Andy Slaughter replied on 21 September that the government "currently has no plans" to do so. He said the principles would continue to apply in circumstances where formal consultation is legally required.` },
    { type: 'paragraph', text: `The Gunning requirements, subsequently endorsed by the Supreme Court, include consulting while proposals remain at a formative stage, providing enough information for an intelligent response, allowing adequate time and conscientiously considering the responses before reaching the final decision.` },
    { type: 'paragraph', text: `The government is therefore changing its administrative approach rather than abolishing consultation law.` },
    { type: 'paragraph', text: `The same September letter also tells ministers to accept greater legal risk in decision-making. It says that where there is a "tenable legal argument", ministers may choose to proceed even when lawyers consider the legal risk high. Updated guidance for government lawyers was promised alongside that instruction.` },
    { type: 'paragraph', text: `That forms part of a wider attempt to increase ministerial control over decisions that the government says have become slowed by process, regulators, legal caution and external consultation.` },
    { type: 'paragraph', text: `The consultation changes are already partly in operation.` },
    { type: 'paragraph', text: `The letter to ministers has been published. Departments have been told to reduce unnecessary formal consultations. The Cabinet Office says approximately 7,000 statutory consultation duties have been identified. It has confirmed that the 2018 Consultation Principles will be amended.` },
    { type: 'paragraph', text: `The replacement Consultation Principles have not yet been published.` },
    { type: 'paragraph', text: `The Cabinet Office has also confirmed that there is currently no plan to place the new general guidance circulated to departments in the Commons Library. More detailed public-participation guidance is promised later in the autumn.` },
  ],
  evidence: {
    recordsReviewed: [
      `HM Treasury, Cabinet Office and Attorney General's Office, "The Simplification and Agency of Government: Letter to all ministers", 7 September 2026: the new default approach to formal consultation, the three circumstances identified for its use, the direction to reconsider historic consultation practices, plans to repeal statutory consultation requirements and the instruction on accepting legal risk where a tenable legal argument exists`,
      `Cabinet Office, "'Box-ticking' consultations scrapped to speed up delivery", 10 September 2026: the government's public explanation of the reforms, the folic-acid and cat-microchipping examples, the approximately 7,000 consultation duties and the promise of new public-participation guidance in the autumn`,
      `UK Parliament, Written Question 27471, answered 15 September 2026: confirmation that the Cabinet Office Consultation Principles will be amended and that there is currently no plan to place the new general guidance in the House of Commons Library`,
      `Cabinet Office, Consultation Principles 2018: the existing requirements not to consult unnecessarily, to consult while policy remains formative, provide sufficient information, target affected groups, explain how responses informed policy and normally publish consultation responses within 12 weeks`,
      `UK Parliament, Written Question 28761, answered 21 September 2026: the government's statement that it has no current plans to legislate to disapply the Gunning principles and its description of the circumstances in which formal consultation remains required`,
      `High Court and UK Supreme Court consultation case law: the established requirements that consultation take place at a formative stage, provide sufficient information, allow adequate time and conscientiously consider responses`,
      `UK Parliament, Written Question 27254, answered 14 September 2026: confirmation that the Cabinet Office AI tool identified approximately 7,000 statutory consultation duties`,
    ],
    lastChecked: '3 October 2026',
  },
};

export default piece;
