import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'rk9m4qxw7d',
  kicker: 'Accountability',
  headline: `Starmer Sacked Olly Robbins Over Mandelson Vetting. MPs Say the Facts Had Not Been Established`,
  standfirst: `Sir Olly Robbins was dismissed as the Foreign Office's most senior civil servant over the decision to grant Peter Mandelson security clearance. Three months later, the Foreign Affairs Committee found that Robbins had inherited an appointment No 10 had already announced, obtained royal approval for and presented to the United States. It concluded that his dismissal appeared to have taken place "without full due process and the establishment of the facts".`,
  publishedAt: '2026-07-30',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `Sir Olly Robbins was dismissed as the Foreign Office's most senior civil servant over the decision to grant Peter Mandelson security clearance.` },
    { type: 'paragraph', text: `Three months later, the Foreign Affairs Committee reached a different conclusion about how responsibility should be divided.` },
    { type: 'paragraph', text: `It found that Robbins had inherited an appointment which No 10 had already announced, obtained royal approval for and presented to the United States. Foreign Office officials understood that nothing was supposed to prevent Mandelson becoming ambassador and that they were expected to make the appointment work.` },
    { type: 'paragraph', text: `The committee said Robbins believed he was carrying out the Prime Minister's wishes when he approved the clearance. It concluded that his subsequent dismissal appeared to have taken place "without full due process and the establishment of the facts".` },
    { type: 'paragraph', text: `That conclusion does not clear Robbins of responsibility for what happened.` },
    { type: 'paragraph', text: `He accepted that he was accountable for the decision to grant clearance. He approved it without seeing the written UK Security Vetting recommendation himself, failed to make a separate record of his reasoning and later signed a response to Parliament which did not disclose that UKSV had recommended against clearance.` },
    { type: 'paragraph', text: `But the committee's reconstruction of the appointment shows that the security decision Robbins made on 29 January 2025 came at the end of a process whose political direction had been established before he arrived at the Foreign Office.` },
    { type: 'paragraph', text: `Keir Starmer received the Cabinet Office's final due-diligence advice on Mandelson on 11 December 2024. He decided to appoint him on 18 December. The appointment was publicly announced on 20 December.` },
    { type: 'paragraph', text: `Security vetting did not begin until 23 December.` },
    { type: 'paragraph', text: `The Foreign Affairs Committee found no formal process for making a political appointment of this kind.` },
    { type: 'paragraph', text: `Sir Philip Barton, who was then permanent under-secretary at the Foreign Office and head of the Diplomatic Service, first learned of the decision on 15 December and had not been consulted about whether Mandelson should be appointed. The committee was also surprised that the then foreign secretary had not been consulted on the choice.` },
    { type: 'paragraph', text: `The Cabinet Office's due-diligence report was not shared with the Foreign Office. Sir Philip was told that the Prime Minister had seen it and knew about the risks, but he did not see it himself.` },
    { type: 'paragraph', text: `By the time Robbins took over the department on 20 January 2025, much of the appointment had already happened.` },
    { type: 'paragraph', text: `The King had approved it. The US government had granted agrément. Mandelson's appointment had been announced. He had access to the Foreign Office building and basic IT and was receiving highly classified briefings on a case-by-case basis.` },
    { type: 'paragraph', text: `He was also already on the government payroll.` },
    { type: 'paragraph', text: `Of the paperwork subsequently examined by MPs, the committee found that only Mandelson's employment contract, received after his vetting had been approved, clearly stated that the appointment was conditional on security clearance.` },
    { type: 'paragraph', text: `Robbins described what followed as an "atmosphere of constant chasing" from No 10.` },
    { type: 'paragraph', text: `He told MPs that his office and the foreign secretary's office received frequent enquiries asking when the process would be completed.` },
    { type: 'paragraph', text: `"There was never any interest, as far as I can recall, in 'whether', but only an interest in 'when'," he said.` },
    { type: 'paragraph', text: `The committee did not find that No 10 had ordered the Foreign Office to lower its security standards. Robbins and Ian Collard, the department's security director, both said the pressure had not changed their professional judgment.` },
    { type: 'paragraph', text: `Morgan McSweeney, Starmer's former chief of staff, told the committee that No 10's role was to make sure the Prime Minister's decisions were implemented quickly and denied that officials had been asked to skip steps.` },
    { type: 'paragraph', text: `The committee nevertheless concluded that FCDO officials understood that "nothing would prevent this appointment and they had to make it work". Reversing the decision after the public announcement, royal approval and US agreement would have been politically embarrassing and risked damaging relations with Washington.` },
    { type: 'paragraph', text: `UK Security Vetting completed its work on 28 January.` },
    { type: 'paragraph', text: `Its written summary recommended that Mandelson should not receive Developed Vetting clearance. The form had two red boxes marked, including "high concern" and "clearance denied or withdrawn".` },
    { type: 'paragraph', text: `The Foreign Office granted clearance the following day.` },
    { type: 'paragraph', text: `That sequence sounds simpler than the system actually was.` },
    { type: 'paragraph', text: `At the time, UKSV's conclusion was a recommendation to the Foreign Office rather than a binding decision. The FCDO was one of the departments allowed to make the final decision itself and could grant clearance where it believed the risks identified by the vetters could be managed.` },
    { type: 'paragraph', text: `Starmer acknowledged that arrangement when he addressed the Commons in April. "For the Foreign Office, the final decision on developed vetting clearance is made by Foreign Office officials, not UKSV," he said.` },
    { type: 'paragraph', text: `Robbins also did not see the UKSV summary which has since become central to the argument over his decision.` },
    { type: 'paragraph', text: `He told MPs he had never seen the document or the red-box assessment before it was subsequently made public.` },
    { type: 'paragraph', text: `His oral briefing was different in tone.` },
    { type: 'paragraph', text: `According to Robbins, he was told that UKSV regarded Mandelson as a "borderline case" and was leaning towards recommending against clearance. The Foreign Office security team believed the most serious risks could be managed or mitigated.` },
    { type: 'paragraph', text: `Robbins said he was also told that the risks in the vetting assessment did not relate to Mandelson's relationship with Jeffrey Epstein.` },
    { type: 'paragraph', text: `The distinction between the written recommendation and the oral briefing is one of the unresolved parts of the case.` },
    { type: 'paragraph', text: `Neither Robbins nor Collard, who briefed him, had seen the UKSV summary document. The Foreign Affairs Committee said it was surprised that the person taking the final decision and the person briefing him had not seen it.` },
    { type: 'paragraph', text: `It recommended that future decision-makers should see all appropriate documents.` },
    { type: 'paragraph', text: `Robbins did not claim that responsibility belonged elsewhere.` },
    { type: 'paragraph', text: `"I was accountable," he told MPs.` },
    { type: 'paragraph', text: `He said the Foreign Office's personnel-security specialists were experienced in assessing risks affecting diplomats, that he trusted their judgment and that he backed their recommendation to grant clearance with safeguards.` },
    { type: 'paragraph', text: `But the record of those safeguards is incomplete.` },
    { type: 'paragraph', text: `Robbins told MPs that the decision and mitigations were recorded in the secure vetting system. The Foreign Affairs Committee found little documentary evidence showing what the mitigations actually were, how they had been decided or how they were communicated to Mandelson and others who would have been required to implement them.` },
    { type: 'paragraph', text: `Some relevant material has been withheld at the request of the Metropolitan Police as part of an ongoing investigation.` },
    { type: 'paragraph', text: `The committee therefore said it could not determine whether the safeguards were sufficient to protect national security.` },
    { type: 'paragraph', text: `Its criticism of the wider record was stronger.` },
    { type: 'paragraph', text: `More than 1,500 pages had been released following a Humble Address requiring the government to hand over documents relating to Mandelson's appointment. Despite that volume of material, the committee found no proper audit trail showing how some of the central decisions had been reached.` },
    { type: 'paragraph', text: `It called record-keeping across the process "appalling" and said the Civil Service Code requirement to keep accurate official records had not been met. Its criticism applied to both the Foreign Office and No 10.` },
    { type: 'paragraph', text: `Robbins was directly responsible for one part of that problem.` },
    { type: 'paragraph', text: `He made no separate contemporaneous note explaining his own reasoning when the clearance decision was escalated to him.` },
    { type: 'paragraph', text: `He argued that the final decision and mitigations were recorded in the secure system and that detailed vetting information could not appropriately be recorded through ordinary private-office channels. MPs remained dissatisfied with the absence of a fuller record.` },
    { type: 'paragraph', text: `There was a second problem after Mandelson was dismissed as ambassador in September 2025.` },
    { type: 'paragraph', text: `The Foreign Affairs Committee asked whether security concerns had been raised during vetting and how the Foreign Office had dealt with them.` },
    { type: 'paragraph', text: `A response signed by Robbins and the then foreign secretary said that UKSV had carried out the vetting and that the process had concluded with the FCDO granting clearance. It did not disclose that UKSV had recommended denial.` },
    { type: 'paragraph', text: `The committee later said the answers it received amounted to "partial truths", although it stopped short of saying that it had been lied to.` },
    { type: 'paragraph', text: `Robbins's defence was that national security vetting had deliberately been kept separate from ministers and that they were normally informed of its final outcome, not the confidential findings behind it.` },
    { type: 'paragraph', text: `He told the committee that this was not a private interpretation he had invented after the event. The Foreign Office had used the same position in briefing ministers and Parliament, and the wording had been discussed with the Cabinet Office and No 10.` },
    { type: 'paragraph', text: `He maintained in April that opening individual vetting files to political scrutiny risked damaging the system by discouraging people from disclosing sensitive information candidly.` },
    { type: 'paragraph', text: `Starmer rejected that interpretation.` },
    { type: 'paragraph', text: `In his Commons statement on 20 April, he accepted that detailed personal vetting information had to remain protected but argued that there was no legal bar preventing officials from telling an appointing minister that UKSV had recommended refusing clearance.` },
    { type: 'paragraph', text: `He said that if he had known of the recommendation before Mandelson went to Washington, he would not have proceeded with the appointment.` },
    { type: 'paragraph', text: `He also described the failure to tell ministers in September 2025, when the Foreign Secretary was answering Parliament about the vetting process, as "absolutely unforgivable".` },
    { type: 'paragraph', text: `Starmer had learned on 14 April 2026 that UKSV had recommended against clearance.` },
    { type: 'paragraph', text: `Robbins was out of the Foreign Office two days later.` },
    { type: 'paragraph', text: `The Prime Minister subsequently told Parliament that he had asked Robbins why the UKSV recommendation had been overridden, had not accepted his explanation and had therefore sacked him.` },
    { type: 'paragraph', text: `Robbins gave a different account of the process surrounding his removal.` },
    { type: 'paragraph', text: `He told the Foreign Affairs Committee five days after losing his post that some of the allegations now being made about his accountability and the Foreign Office's decision-making had not been put to him before he received his dismissal letter.` },
    { type: 'paragraph', text: `Asked why he had been dismissed, he said: "I don't fully understand the reasons that I am in the position I am in."` },
    { type: 'paragraph', text: `The committee eventually sided with him on that narrower question.` },
    { type: 'paragraph', text: `Its conclusion on Robbins's dismissal was not unanimous. The paragraph was proposed by Conservative MP Sir John Whittingdale and approved by six votes to one.` },
    { type: 'paragraph', text: `It said Robbins believed he was carrying out Starmer's wishes and delivering the outcome No 10 wanted. Given that he had been told the vetting case was borderline and that mitigations could be put in place, the committee said it was unsurprising that he approved it.` },
    { type: 'paragraph', text: `It then concluded that his dismissal "seems to have been taken without full due process and the establishment of the facts".` },
    { type: 'paragraph', text: `That finding does not answer whether Robbins's original decision was correct.` },
    { type: 'paragraph', text: `The committee said it still could not understand how Mandelson had been appointed if he was considered a national-security risk. It found no evidence from which it could assess whether the promised mitigations were adequate.` },
    { type: 'paragraph', text: `It also criticised Robbins and other officials for failing to find a way of telling ministers that the vetting process had contained serious concerns without disclosing the confidential details behind them.` },
    { type: 'paragraph', text: `Starmer has accepted responsibility for choosing Mandelson.` },
    { type: 'paragraph', text: `"I should not have appointed Peter Mandelson," he told the Commons in April. "I take personal responsibility for that decision."` },
    { type: 'paragraph', text: `He has since changed the rules so that political appointments cannot be publicly announced before security vetting has been completed and commissioned Sir Adrian Fulford to review the wider national-security vetting system.` },
    { type: 'paragraph', text: `Robbins had been brought back into government little more than a year before his dismissal.` },
    { type: 'paragraph', text: `His appointment as Foreign Office permanent under-secretary was announced in January 2025 with the approval of Starmer and then foreign secretary David Lammy. Lammy described him as "exactly the person" needed to reshape the department, citing his experience across economic and security policy.` },
    { type: 'paragraph', text: `Robbins had previously been Theresa May's chief official negotiator on Brexit, a permanent secretary at the Department for Exiting the European Union, a senior Home Office official and a national-security adviser before leaving government in 2019.` },
    { type: 'paragraph', text: `On 13 July 2026, he began judicial-review proceedings over his dismissal.` },
    { type: 'paragraph', text: `According to the FDA, the civil-service union representing him, Robbins argues that the Prime Minister had no statutory power to dismiss him as head of the Diplomatic Service, that there was no fair procedure and that the reasons provided were irrational. He also argues that rather than being obliged to disclose the internal UKSV recommendation to ministers, the vetting rules required him not to do so.` },
    { type: 'paragraph', text: `Those are Robbins's legal arguments. The High Court had not ruled on them when this article was published.` },
    { type: 'paragraph', text: `The Foreign Affairs Committee did not decide those legal questions either.` },
    { type: 'paragraph', text: `What it established was the chronology.` },
    { type: 'paragraph', text: `Starmer chose Mandelson before security vetting had started. The appointment was announced before it had finished. The Foreign Office's serving permanent secretary and the foreign secretary had not been properly consulted on the original choice. Robbins arrived after royal approval, US agreement and the public announcement, with No 10 pressing his department to complete the process.` },
    { type: 'paragraph', text: `Robbins then approved clearance after being told orally that UKSV was leaning against a borderline case and that the risks could be managed. He did so without seeing a written UKSV form which described those concerns more starkly.` },
    { type: 'paragraph', text: `The committee found serious failures on both sides of that sequence.` },
    { type: 'paragraph', text: `It also found that when Starmer dismissed Robbins less than 48 hours after learning of the UKSV recommendation, the facts surrounding those failures had not yet been fully established.` },
  ],
  evidence: {
    recordsReviewed: [
      `House of Commons Foreign Affairs Committee, The appointment of Peter Mandelson as British Ambassador to the United States, HC 504, 9 July 2026: the appointment chronology; absence of a formal political-appointment process; failure to consult the Foreign Office permanent secretary and foreign secretary; No 10 pressure; the committee's findings on Robbins's understanding of the Prime Minister's wishes; the missing audit trail; the limitations of the evidence on mitigations; and the majority conclusion that Robbins's dismissal appeared to occur without full due process and establishment of the facts`,
      `Foreign Affairs Committee, oral evidence of Sir Oliver Robbins, 21 April 2026: Robbins's account of No 10's "constant chasing", his description of the UKSV case as it was orally presented to him, his statement that he had not seen the UKSV summary, his acceptance of accountability for the clearance decision, his defence of the confidentiality of vetting and his evidence about the circumstances of his dismissal`,
      `Prime Minister's statement on the appointment of Peter Mandelson, House of Commons, 20 April 2026: Starmer's account of when he learned of the UKSV recommendation, his explanation of the FCDO's then-existing authority to make the final vetting decision, his assertion that ministers should have been told, his criticism of the September 2025 response to Parliament and his acceptance of responsibility for appointing Mandelson`,
      `Foreign Secretary Yvette Cooper, letter to the Foreign Affairs Committee, 18 April 2026: the appointment of an interim permanent under-secretary following Robbins's departure and the Foreign Secretary's concern that information about Mandelson's vetting had not previously been supplied to ministers or Parliament`,
      `Cabinet Office and Foreign, Commonwealth and Development Office, "New Permanent Under-Secretary Appointed at the Foreign, Commonwealth & Development Office", 8 January 2025: Robbins's appointment, its approval by the Prime Minister and foreign secretary, and David Lammy's stated reasons for bringing him back into government`,
      `FDA, "Robbins submits legal challenge of his dismissal", 14 July 2026: the existence and stated grounds of Robbins's application for judicial review — claims remain allegations in live proceedings and had not been determined by the court at the time of publication`,
    ],
    lastChecked: '4 October 2026',
  },
};

export default piece;
