import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'rm4n9mxw7r',
  kicker: 'Accountability',
  headline: `Government Misses Compensation Reform Deadline as Claimants Report Being Retraumatised`,
  standfirst: `The government has missed its own deadline to set out whether it will create an independent body to design and run compensation schemes for people harmed by public bodies. A Public Accounts Committee survey found 76 per cent of claimants said the process had been distressing or retraumatising. The same administrative failures keep appearing across Windrush, Horizon, infected blood and LGBT veterans schemes.`,
  publishedAt: '2026-09-09',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `The government has missed its own deadline to set out whether it will create an independent body to design and run compensation schemes for people harmed by public bodies.` },
    { type: 'paragraph', text: `A Public Accounts Committee report published on 9 September says government had promised a substantive statement by summer 2026. None had appeared by the time the committee reported.` },
    { type: 'paragraph', text: `The committee records recurring problems across compensation arrangements for Windrush victims, people affected by the Post Office Horizon scandal, infected blood victims and LGBT veterans.` },
    { type: 'paragraph', text: `By February 2026, around £3.5 billion had been paid across the seven schemes examined by the National Audit Office, with up to another £11.4 billion potentially still to be paid. The infected blood scheme accounts for most of that future liability.` },
    { type: 'paragraph', text: `The committee also surveyed 572 people with experience of compensation and financial-recognition schemes. Of those respondents, 76 per cent said the claims process had been distressing or retraumatising. Fifty-three per cent said evidence they were asked to provide felt unreasonable or too difficult to obtain, while 53 per cent said timescales and next steps had not been communicated to them regularly. A further 13 per cent said they seldom received regular updates.` },
    { type: 'paragraph', text: `The survey was not a representative poll of every claimant. It was distributed through organisations supporting people involved in the schemes, and people applying to the Infected Blood Compensation Scheme made up the largest group of respondents. The committee nevertheless found similar complaints across Horizon, Windrush and LGBT veterans schemes.` },
    { type: 'paragraph', text: `The PAC says compensation schemes can require extensive records to establish eligibility even where documents no longer exist or events took place decades ago. Sixty-three per cent of survey respondents described the overall claims process as "extremely difficult", with another 23 per cent calling it "somewhat difficult". The committee found that burdensome evidential rules can drive claimants towards legal help, increasing both cost and delay, and that access to that support varies between schemes.` },
    { type: 'paragraph', text: `The Ministry of Defence accepted that LGBT veterans had not always received the regular updates they had been promised. The Home Office acknowledged that Windrush claimants initially received too little information about progress and expected timescales, while representatives of Horizon claimants reported stress and anxiety caused by not knowing what was happening with their cases.` },
    { type: 'paragraph', text: `As of January 2026, 27 Windrush claims had been in progress for between 12 and 18 months and another 15 for longer than 18 months. Under the Horizon Shortfall Scheme, 2,049 claims had taken more than a year to pay, equivalent to around a fifth of claims paid, while the longest settled claim took 1,395 working days.` },
    { type: 'paragraph', text: `Departments told the committee that some long-running claims are delayed at the claimant's request because revisiting the underlying events can itself be distressing. The Home Office and Department for Business and Trade nevertheless accepted that claims taking more than 1,000 working days were not acceptable.` },
    { type: 'paragraph', text: `Government has repeatedly underestimated how compensation schemes will operate in practice. The Horizon Shortfall Scheme was initially expected to receive only a few hundred applications. By its original November 2020 deadline, 2,417 had arrived. After the scheme reopened, more than 10,000 further applications followed.` },
    { type: 'paragraph', text: `The Windrush scheme was changed after its launch following criticism from Parliament, claimants' representatives and caseworkers. The Home Office later introduced a £500,000 community fund partly to address low trust that was deterring some eligible people from applying.` },
    { type: 'paragraph', text: `The PAC wants future schemes to be designed with affected communities before they open. The Cabinet Office told the committee that co-design was essential to building trust, while representatives of infected blood victims, Windrush claimants and subpostmasters described problems they believed could have been avoided through earlier involvement.` },
    { type: 'paragraph', text: `Most of the schemes examined are administered by the same department or organisation associated with the original harm. The Infected Blood Compensation Scheme was the only scheme in the NAO sample administered independently of the body responsible for the underlying failure.` },
    { type: 'paragraph', text: `The PAC said this arrangement damages trust and recommended that the Cabinet Office provide comprehensive plans for an independent body capable of designing and administering compensation schemes across government. It wants the government to explain how such a body would be funded and organised.` },
    { type: 'paragraph', text: `The Cabinet Office has not rejected the idea. It told MPs that there were advantages to consistent independent administration but also raised concerns that a single organisation might struggle to create schemes tailored to very different groups and forms of harm. Officials said ministers were considering both the benefits and the difficulties.` },
    { type: 'paragraph', text: `A Department for Business and Trade-led ministerial group has been examining options for improving future compensation arrangements and the feasibility of an independent body.` },
    { type: 'paragraph', text: `Officials currently meet through a cross-Whitehall network every eight weeks to share lessons and good practice. The NAO found those meetings useful, but the PAC said informal coordination does not ensure that knowledge is retained or consistently applied when the next compensation scheme is created. The NAO and the Post Office Horizon IT Inquiry have both previously recommended a standing mechanism to preserve lessons from compensation programmes, and the PAC has now asked government to set out how it will create a formal structure for doing so.` },
    { type: 'paragraph', text: `The government therefore has two related decisions still outstanding: whether compensation schemes should continue to be designed and administered largely department by department, and how lessons from earlier schemes will be retained when future programmes are created.` },
  ],
  evidence: {
    recordsReviewed: [
      `House of Commons Committee of Public Accounts, "Government compensation schemes", Twelfth Report of Session 2026–27 (HC 88), 9 September 2026: the missed summer 2026 statement, the "not materialised" finding, recommendation for an independent compensation body, absence of permanent central oversight, claimant-experience findings, evidence requirements, communication failures, processing delays and recommendations for co-design`,
      `National Audit Office, "Government's compensation and financial recognition schemes", April 2026: the £3.5 billion paid and £11.4 billion potentially outstanding (against a total anticipated cost of close to £14.9 billion, of which the Infected Blood Compensation Scheme accounts for £12.8 billion), the seven-scheme sample, the 572-respondent survey and all its percentage findings, the Horizon Shortfall Scheme application and delay figures, the Windrush delay figures, and the £500,000 community fund`,
      `Public Accounts Committee, oral and written evidence for "Government compensation schemes: update": departmental evidence on Windrush, Horizon, LGBT veterans and infected blood schemes, co-design, long-running claims and the government's consideration of an independent compensation body`,
    ],
    lastChecked: '3 October 2026',
  },
};

export default piece;
