import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'rm4n9mxw7r',
  kicker: 'Accountability',
  headline: `Government Missed Its Own Deadline to Fix Compensation Schemes as Claimants Report Being Retraumatised`,
  standfirst: `The government missed its own deadline to publish plans for reforming how it compensates victims of state failures. A Public Accounts Committee survey found 76 per cent of claimants said the process was itself distressing or retraumatising. The committee says the same administrative failures, slow decisions, unreasonable evidence demands and poor communication, keep appearing across Windrush, Horizon, infected blood and LGBT veterans schemes because each one is designed almost from scratch.`,
  publishedAt: '2026-09-09',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `The government missed its own deadline to set out how it would reform compensation schemes for people harmed by public bodies, while a new parliamentary report found that three quarters of claimants said the process itself was distressing or retraumatising.` },
    { type: 'paragraph', text: `The Public Accounts Committee says ministers had promised a substantive statement on reform by summer 2026.` },
    { type: 'paragraph', text: `By 9 September, it had not appeared.` },
    { type: 'paragraph', text: `That delay matters because the complaints are not confined to one scheme.` },
    { type: 'paragraph', text: `The committee examined compensation arrangements linked to Windrush, the Post Office Horizon scandal, infected blood and LGBT veterans, among others. Its conclusion is that Whitehall keeps reproducing the same problems: slow decisions, difficult evidence requirements, poor communication and processes that feel more like litigation than redress.` },
    { type: 'paragraph', text: `In a survey of 572 people carried out for the inquiry, 76 per cent said making a claim was itself distressing or retraumatising.` },
    { type: 'paragraph', text: `Fifty-three per cent said requests for evidence felt unreasonable or too difficult.` },
    { type: 'paragraph', text: `Fifty-three per cent also said they were not given regular updates about timescales or what would happen next.` },
    { type: 'paragraph', text: `The government has a reasonable argument for not designing every scheme in exactly the same way. Windrush, infected blood and Horizon involve different legal issues, different evidence and different forms of loss.` },
    { type: 'paragraph', text: `But that does not explain why the administrative failures keep looking so similar.` },
    { type: 'paragraph', text: `The committee says each scheme still tends to be designed almost from scratch.` },
    { type: 'paragraph', text: `That means lessons about evidence, communication, appeals and trauma are not being consistently built into the next scheme.` },
    { type: 'paragraph', text: `The result is a system in which people who have already been failed by the state can end up spending years proving that failure to another part of the state.` },
    { type: 'paragraph', text: `The committee's own language on this point is blunt: "Trust collapses when people have to rely on the same body that caused them harm to manage the compensation process."` },
    { type: 'paragraph', text: `Its solution is structural.` },
    { type: 'paragraph', text: `It wants the Cabinet Office to set out comprehensive plans for an independent body capable of designing and administering government compensation schemes across departments, properly resourced to build claimant trust, rather than leaving each department to build its own machinery when a scandal emerges.` },
    { type: 'paragraph', text: `The government had already said it would make a substantive statement on that question by summer 2026.` },
    { type: 'paragraph', text: `It missed the deadline.` },
    { type: 'paragraph', text: `That is the strongest accountability point.` },
    { type: 'paragraph', text: `Whitehall is not being surprised by these complaints for the first time.` },
    { type: 'paragraph', text: `The problems have already been identified.` },
    { type: 'paragraph', text: `Victims have already described the same patterns across multiple schemes.` },
    { type: 'paragraph', text: `Parliament has already pressed government for a cross-departmental answer.` },
    { type: 'paragraph', text: `The promised answer is late.` },
    { type: 'paragraph', text: `The committee also found that delays remain one of the biggest sources of harm.` },
    { type: 'paragraph', text: `Some respondents said they had been waiting years.` },
    { type: 'paragraph', text: `Others said they feared they or relatives would die before receiving compensation.` },
    { type: 'paragraph', text: `The uncertainty can be as damaging as the delay itself.` },
    { type: 'paragraph', text: `People often do not know how long their claim will take or what stage it has reached.` },
    { type: 'paragraph', text: `The committee cites LGBT veterans as one example where regular updates had been promised but were not consistently provided.` },
    { type: 'paragraph', text: `Evidence requirements are another recurring problem.` },
    { type: 'paragraph', text: `Schemes can ask claimants to produce documents connected to events that happened decades earlier, even where records are incomplete, inaccessible or held by the state itself.` },
    { type: 'paragraph', text: `The committee says some criteria fail to take proper account of age, illness, bereavement or the simple difficulty of reconstructing old events, and has called for evidence thresholds to be set with input from the communities affected.` },
    { type: 'paragraph', text: `That creates a peculiar imbalance.` },
    { type: 'paragraph', text: `Government may already accept that a broad injustice occurred.` },
    { type: 'paragraph', text: `The individual claimant can still be required to prove their own part of it through a process they experience as adversarial.` },
    { type: 'paragraph', text: `The committee also criticises schemes for being designed without enough involvement from the people expected to use them, calling instead for co-design with affected communities before any scheme launches.` },
    { type: 'paragraph', text: `That can produce digital systems that do not suit older claimants, eligibility rules that exclude carers or relatives, and compensation structures that divide people affected by the same scandal into different categories.` },
    { type: 'paragraph', text: `Those are not obscure administrative details.` },
    { type: 'paragraph', text: `They determine who gets paid, how long it takes and whether some people give up before they reach the end.` },
    { type: 'paragraph', text: `There is evidence that this happens.` },
    { type: 'paragraph', text: `The committee warns that lack of trust can itself discourage eligible people from coming forward.` },
    { type: 'paragraph', text: `That makes the design of a compensation scheme part of the remedy, not just the bureaucracy surrounding it.` },
    { type: 'paragraph', text: `The government's position has usually been that it wants schemes to be fair, efficient and tailored to the circumstances of each case.` },
    { type: 'paragraph', text: `That is a legitimate aim.` },
    { type: 'paragraph', text: `The record described by the committee is much less reassuring.` },
    { type: 'paragraph', text: `Across different departments and different scandals, the same complaints keep returning.` },
    { type: 'paragraph', text: `People wait.` },
    { type: 'paragraph', text: `They chase updates.` },
    { type: 'paragraph', text: `They gather evidence.` },
    { type: 'paragraph', text: `They challenge decisions.` },
    { type: 'paragraph', text: `They seek legal help.` },
    { type: 'paragraph', text: `And in some cases they spend years fighting the same public system that has already accepted something went badly wrong.` },
    { type: 'paragraph', text: `The Public Accounts Committee is now arguing that the model itself is the problem.` },
    { type: 'paragraph', text: `Government said it would respond by summer.` },
    { type: 'paragraph', text: `It did not.` },
    { type: 'paragraph', text: `Until it does, the state is still compensating people for one failure through a system Parliament says risks creating another.` },
  ],
  evidence: {
    recordsReviewed: [
      'House of Commons Public Accounts Committee, "Government compensation schemes" report, 9 September 2026 — 572-respondent survey and exact figures (76 per cent distress/retraumatisation, 53 per cent unreasonable evidence requests, 53 per cent no regular updates), schemes examined (Windrush, Post Office Horizon, infected blood, LGBT veterans), "trust collapses" quote, independent-body recommendation (resourcing, co-design, evidence thresholds, performance metrics), confirmation summer 2026 statement deadline was missed',
      'UK Parliament Committees, "Government compensation schemes: update" correspondence listing — checked for further detail on the summer 2026 statement commitment; committee report is primary source used for that finding',
    ],
    lastChecked: '9 September 2026',
  },
};

export default piece;
