import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'rs8k4mxw9n',
  kicker: 'Homelessness',
  headline: `Burnham Pledges to End Long-Term Rough Sleeping but Gives No Date for Reaching Zero`,
  standfirst: `Andy Burnham has committed his government to ending long-term rough sleeping across the UK "at the earliest opportunity", backed by an initial £340 million programme. The announcement does not say when that should happen. It sits on top of an existing government target to halve long-term rough sleeping in England by the end of this Parliament, measured from a published baseline of 3,427 people.`,
  publishedAt: '2026-07-21',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `Andy Burnham has committed his government to ending long-term rough sleeping across the UK "at the earliest opportunity", backed by an initial £340 million programme.` },
    { type: 'paragraph', text: `The announcement does not say when that should happen.` },
    { type: 'paragraph', text: `It does, however, sit on top of an existing government target which is more measurable than Burnham's new pledge. Since December, ministers have been committed to halving long-term rough sleeping in England by the end of this Parliament, measured from a published baseline of 3,427 people.` },
    { type: 'paragraph', text: `Burnham has therefore increased the stated ambition from halving long-term rough sleeping to ending it, without setting a new date for reaching zero.` },
    { type: 'paragraph', text: `The £340 million announced on his first day as Prime Minister is described by government as the first phase of a wider five-year programme. It is intended to provide 1,200 homes and intensive support for at least 3,000 people who have experienced severe or long-term homelessness. Further measures are promised before the autumn.` },
    { type: 'paragraph', text: `The announcement does not give allocations by local area, say how much of the £340 million will pay for homes and how much will pay for support, or provide annual spending figures.` },
    { type: 'paragraph', text: `It also describes the £340 million as "additional" funding without explaining in the announcement whether that means additional Treasury funding or money allocated from existing departmental budgets.` },
    { type: 'paragraph', text: `The starting point for judging progress already exists.` },
    { type: 'paragraph', text: `Government guidance published in May says 3,427 people in England were recorded as sleeping rough long term over the month in November 2025. Councils have been told to set local targets contributing to a 50 per cent reduction by the end of Parliament.` },
    { type: 'paragraph', text: `That measure is different from the better-known annual rough sleeping count.` },
    { type: 'paragraph', text: `The latest annual snapshot estimated that 4,793 people were sleeping rough on a single night in England in autumn 2025, the highest figure since the current methodology began in 2010 and the fourth annual increase in succession.` },
    { type: 'paragraph', text: `The 4,793 cannot be used as the baseline for Burnham's promise because the government is specifically targeting long-term rough sleeping.` },
    { type: 'paragraph', text: `Its definition is based on people seen sleeping rough over a month who meet the government's long-term criteria. The November baseline of 3,427 is therefore the relevant existing measure.` },
    { type: 'paragraph', text: `Burnham's announcement did not withdraw the target to halve that figure by the end of Parliament. Nor did it replace it with a dated target for eliminating long-term rough sleeping altogether.` },
    { type: 'paragraph', text: `That leaves two commitments operating at once: a measurable English target to halve long-term rough sleeping by the end of Parliament, and Burnham's wider promise to end it "at the earliest opportunity".` },
    { type: 'paragraph', text: `There is another unresolved distinction.` },
    { type: 'paragraph', text: `Burnham said he was committing the government to ending long-term rough sleeping "across the UK". The £340 million announcement does not explain how the programme will operate in Scotland, Wales or Northern Ireland, where housing and homelessness policy is devolved.` },
    { type: 'paragraph', text: `The National Plan to End Homelessness on which the existing halving target is based explicitly applies to England.` },
    { type: 'paragraph', text: `Burnham's record in Greater Manchester gives the new commitment an unusually clear precedent.` },
    { type: 'paragraph', text: `When he became mayor in May 2017, ending rough sleeping by 2020 was one of his stated priorities. Greater Manchester Combined Authority described the commitment at the time as ending rough sleeping by 2020, with no one having to sleep on the streets of the city-region by then.` },
    { type: 'paragraph', text: `He did not meet that deadline.` },
    { type: 'paragraph', text: `By May 2019, Burnham was publicly acknowledging the uncertainty himself. Asked whether he would fulfil the manifesto pledge, he said: "The honest answer is I don't know."` },
    { type: 'paragraph', text: `He argued that A Bed Every Night, his emergency accommodation programme, gave Greater Manchester a chance to get close.` },
    { type: 'paragraph', text: `The numbers subsequently improved substantially.` },
    { type: 'paragraph', text: `The official single-night count for Greater Manchester had reached 268 in 2017. By 2021 it was 89, a fall of 179 people, or about two thirds. GMCA attributed the improvement to a combination of A Bed Every Night, Housing First and the response during the coronavirus pandemic.` },
    { type: 'paragraph', text: `That is a significant achievement, but it was not the end of rough sleeping and the reduction did not hold.` },
    { type: 'paragraph', text: `The count rose to 149 in 2023 and 154 in 2024. The 2025 figure was 197, leaving Greater Manchester below its 2017 level but with rough sleeping more than twice the 2021 low.` },
    { type: 'paragraph', text: `The national pattern moved in much the same direction.` },
    { type: 'paragraph', text: `England's annual single-night figure fell from 4,751 in 2017 to 2,443 in 2021 before increasing to 3,069 in 2022, 3,898 in 2023, 4,667 in 2024 and 4,793 in 2025.` },
    { type: 'paragraph', text: `Those figures complicate Burnham's use of the pandemic response as evidence that rough sleeping can simply be ended with sufficient political will.` },
    { type: 'paragraph', text: `Everyone In was unusually effective at moving people off the streets quickly. By the end of November 2020, more than 33,000 people who were sleeping rough or at risk of doing so had been helped to find accommodation. Of those, 23,273 had moved into settled accommodation or a longer-term rough sleeping pathway and 9,866 remained in emergency accommodation.` },
    { type: 'paragraph', text: `But it did not permanently end rough sleeping.` },
    { type: 'paragraph', text: `The National Audit Office recorded a continued flow of people onto the streets during 2020 even while Everyone In was operating. After the pandemic measures receded, the annual count began rising again.` },
    { type: 'paragraph', text: `Greater Manchester followed a similar course.` },
    { type: 'paragraph', text: `Burnham's A Bed Every Night programme created emergency accommodation alongside support intended to move people into more permanent housing. By 2025 it was providing more than 600 bed spaces across the city-region.` },
    { type: 'paragraph', text: `The fact that the annual snapshot subsequently rose again does not show that A Bed Every Night failed. Without it, rough sleeping might have been higher. Nor can the rise be attributed to one policy or one mayor.` },
    { type: 'paragraph', text: `Greater Manchester officials have pointed to housing costs, pressures on local services, asylum accommodation changes and shortages of affordable housing. In 2025, Burnham argued that national welfare policy and the shortage of social housing were making it harder for local government to sustain earlier reductions.` },
    { type: 'paragraph', text: `Those are also reasons a national programme may be able to do things that a mayoral programme could not.` },
    { type: 'paragraph', text: `Burnham now controls policies affecting housing, welfare and public services which were outside his powers in Greater Manchester. His government had already inherited a National Plan to End Homelessness containing measures on prevention, supported housing and closer working between councils and other public bodies.` },
    { type: 'paragraph', text: `The £340 million adds a larger intervention focused on people who have been sleeping rough for long periods.` },
    { type: 'paragraph', text: `What it does not yet add is a dated definition of success beyond the existing halving target.` },
    { type: 'paragraph', text: `The government knows the baseline. Its May guidance puts long-term rough sleeping at 3,427 people in November 2025. It knows the existing interim destination: a 50 per cent reduction by the end of Parliament. Councils are already required to prepare plans against it.` },
    { type: 'paragraph', text: `Burnham has now promised to go further and end long-term rough sleeping altogether.` },
    { type: 'paragraph', text: `The 20 July announcement does not say by when.` },
  ],
  evidence: {
    recordsReviewed: [
      `Prime Minister's Office and Ministry of Housing, Communities and Local Government, "New PM says government can bring back hope to Britain, and launches drive to end rough sleeping at the earliest opportunity", 20 July 2026: Burnham's commitment to end long-term rough sleeping across the UK, the £340 million announcement, 1,200 homes, support for at least 3,000 people and the description of the funding as the first phase of a five-year programme`,
      `Prime Minister's Office, "Andy Burnham's first speech as Prime Minister", 20 July 2026: Burnham's first Downing Street instruction to end rough sleeping and the wording of his first speech in office`,
      `Ministry of Housing, Communities and Local Government, A National Plan to End Homelessness, 11 December 2025: the pre-existing target to halve long-term rough sleeping by the end of Parliament, the wider policy programme and the fact that the plan applies to England`,
      `MHCLG, Long-Term Rough Sleeping Partnership Plan guidance, 20 May 2026: the November 2025 baseline of 3,427 people sleeping rough long term, the 50 per cent end-of-Parliament target and the requirement for councils to establish local targets and action plans`,
      `MHCLG, Rough sleeping snapshot in England: autumn 2025, 26 February 2026: the 4,793 single-night England figure, its status as a record under the current methodology and the four consecutive annual increases, together with the national series used for comparison`,
      `Greater Manchester Combined Authority, "Ending rough sleeping by 2020 - new Mayor puts words into action", May 2017: Burnham's original Greater Manchester pledge and its 2020 deadline`,
      `Andy Burnham, speech on homelessness, May 2019, published by Greater Manchester Combined Authority: Burnham's acknowledgement before the deadline that he did not know whether the 2020 pledge would be achieved`,
      `Greater Manchester Combined Authority, official rough-sleeping releases for 2021 and 2024: the fall to 89 people in 2021 from 268 in 2017 and the subsequent rise to 149 in 2023 and 154 in 2024`,
      `National Audit Office, Investigation into the housing of rough sleepers during the COVID-19 pandemic, January 2021: the scale and results of Everyone In, including more than 33,000 people helped by November 2020, 23,273 moved into settled accommodation or longer-term pathways and the continuing flow of people onto the streets`,
    ],
    lastChecked: '4 October 2026',
  },
};

export default piece;
