import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'se9k4m2xq7',
  kicker: 'Public Spending',
  headline: `MPs Approved £1.15 Trillion of Departmental Resources. Most Estimates Were Never Debated`,
  standfirst: `The House of Commons passed a bill appropriating more than £1.15 trillion of departmental resources for 2026/27. Its second and third readings on 1 July were completed without substantive debate. That is not an accidental shortcut — it is how Supply legislation works. But most departmental Estimates never received their own Commons debate before Parliament approved them.`,
  publishedAt: '2026-07-13',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `The House of Commons has passed a bill appropriating more than £1.15 trillion of departmental resources for 2026/27.` },
    { type: 'paragraph', text: `Its second and third readings on 1 July were completed without substantive debate.` },
    { type: 'paragraph', text: `That does not mean MPs suddenly voted to spend £1.15 trillion of new money.` },
    { type: 'paragraph', text: `The number needs unpacking.` },
    { type: 'paragraph', text: `The Supply and Appropriation (Main Estimates) Bill brings together authority already granted earlier in the year with the additional resources requested through the Main Estimates. The total annual resource appropriation is £1,154,943,006,000.` },
    { type: 'paragraph', text: `Of that, £634.48 billion is additional resource authority provided through the Main Estimates legislation. The bill also authorises a further £514.78 billion in cash to be issued from the Consolidated Fund.` },
    { type: 'paragraph', text: `The total cash appropriation for the year is lower than the resource figure, at £936.82 billion.` },
    { type: 'paragraph', text: `"Resources" and cash are not interchangeable.` },
    { type: 'paragraph', text: `Government Estimates include current and capital expenditure and accounting items that do not necessarily involve an equivalent cash payment during the year. Calling the £1.15 trillion simply "public expenditure" therefore makes the number sound more straightforward than it is.` },
    { type: 'paragraph', text: `Nor is it the entire British state.` },
    { type: 'paragraph', text: `The Main Estimates seek parliamentary authority for central government departmental spending. Some expenditure is authorised separately under existing statutes and is not subject to the annual Supply process.` },
    { type: 'paragraph', text: `The striking part is not that MPs secretly approved £1.15 trillion in one vote.` },
    { type: 'paragraph', text: `It is how Parliament scrutinises the spending plans before giving them legal effect.` },
    { type: 'paragraph', text: `The Main Estimates were published by the Treasury on 29 April. There is a separate Estimate for each department, running to hundreds of pages in total. Select committees can examine departmental memoranda and question ministers before the Commons reaches its formal approval stage.` },
    { type: 'paragraph', text: `But only a small number of Estimates receive debate on the floor of the House.` },
    { type: 'paragraph', text: `This year MPs were given two Main Estimates days.` },
    { type: 'paragraph', text: `On 29 June they debated Cabinet Office spending on security and resilience, the Northern Ireland Office, and Home Office and Ministry of Justice spending on criminal justice.` },
    { type: 'paragraph', text: `On 30 June they debated Culture, Media and Sport spending on sport and youth services, Department of Health and Social Care spending on pharmaceutical procurement, and Department for Work and Pensions spending priorities and performance.` },
    { type: 'paragraph', text: `Six subjects received dedicated Commons debate.` },
    { type: 'paragraph', text: `The rest did not.` },
    { type: 'paragraph', text: `After the selected debates finished on 30 June, the Commons approved the remaining departmental Estimates through what Parliament calls a roll-up motion.` },
    { type: 'paragraph', text: `That is standard procedure.` },
    { type: 'paragraph', text: `An Estimate selected for debate can be amended, but MPs can only propose a reduction. They cannot increase spending because only the government can initiate expenditure.` },
    { type: 'paragraph', text: `Estimates that are not selected for debate cannot be individually amended at all. They are grouped together and MPs can approve or reject the package as a whole.` },
    { type: 'paragraph', text: `The Commons Library describes Parliament's role plainly: after the selected Estimates have been considered, a roll-up motion covers all the others.` },
    { type: 'paragraph', text: `That is where most departments' spending plans pass through the Chamber.` },
    { type: 'paragraph', text: `The Supply Bill then converts those approvals into statutory authority.` },
    { type: 'paragraph', text: `On 1 July, the Supply and Appropriation (Main Estimates) Bill came back before MPs for its second reading.` },
    { type: 'paragraph', text: `Hansard records the entire proceeding:` },
    { type: 'paragraph', text: `"Motion made, and Question put forthwith."` },
    { type: 'paragraph', text: `The question was agreed.` },
    { type: 'paragraph', text: `The bill was read a second time.` },
    { type: 'paragraph', text: `The question on third reading was then put immediately.` },
    { type: 'paragraph', text: `It was agreed again, and the bill passed the Commons.` },
    { type: 'paragraph', text: `There was no committee stage examining individual clauses and no further debate over whether particular departments should receive the sums contained in the bill.` },
    { type: 'paragraph', text: `That is not an accidental shortcut taken by this government.` },
    { type: 'paragraph', text: `It is how Supply legislation works.` },
    { type: 'paragraph', text: `The Commons debates selected Estimates beforehand. Once those Supply resolutions have been agreed, the subsequent bill gives them legal force. Parliamentary procedure deliberately prevents the Supply Bill itself becoming another opportunity to reopen individual spending decisions.` },
    { type: 'paragraph', text: `The House of Lords has an even narrower role.` },
    { type: 'paragraph', text: `The bill is a Money Bill. The Lords is due to take its remaining stages on 14 July, but normal parliamentary practice treats Supply and Appropriation Bills as formal business rather than an opportunity to rewrite Commons spending decisions.` },
    { type: 'paragraph', text: `There is a reason for some of this machinery.` },
    { type: 'paragraph', text: `Budgets cannot operate if hundreds of individual spending lines can be reopened indefinitely. Departments also face scrutiny through select committees, the National Audit Office, the Public Accounts Committee, departmental accounts, Budgets and Spending Reviews.` },
    { type: 'paragraph', text: `The Main Estimates themselves are not where ministers first invent most of the spending.` },
    { type: 'paragraph', text: `They seek parliamentary authority for plans largely established through the Spending Review and subsequent fiscal events. The 2026/27 Estimates reflect plans from the 2025 Spending Review and later updates.` },
    { type: 'paragraph', text: `But the constitutional position is still striking.` },
    { type: 'paragraph', text: `Parliament exists partly to control taxation and expenditure. The Estimates process is the formal mechanism through which the government obtains permission to use resources and draw money from the Consolidated Fund.` },
    { type: 'paragraph', text: `For 2026/27, the spending-control totals in the Main Estimates include about £520 billion of resource DEL, £135 billion of capital DEL, £424 billion of resource AME and £75 billion of capital AME.` },
    { type: 'paragraph', text: `Those figures cover the NHS, welfare, schools, prisons, defence, policing, government departments and hundreds of public bodies.` },
    { type: 'paragraph', text: `Yet the Commons does not debate every departmental Estimate before approving it.` },
    { type: 'paragraph', text: `It does not even have enough Estimates days to do so.` },
    { type: 'paragraph', text: `The normal system provides two Commons days for the Main Estimates and one for Supplementary Estimates later in the financial cycle. Topics are selected following bids from backbench MPs.` },
    { type: 'paragraph', text: `That gives Parliament concentrated scrutiny of a handful of areas rather than detailed Chamber examination of every department.` },
    { type: 'paragraph', text: `The original claim that MPs "just voted through £1.15 trillion in public spending" therefore gets the accounting and the procedure wrong.` },
    { type: 'paragraph', text: `The £1.15 trillion is the full-year resource appropriation, including authority previously granted. It is not £1.15 trillion of new cash expenditure. MPs did not approve it all through one unnoticed vote.` },
    { type: 'paragraph', text: `The underlying transparency problem is more mundane and more defensible.` },
    { type: 'paragraph', text: `The spending plans were published.` },
    { type: 'paragraph', text: `The figures were available.` },
    { type: 'paragraph', text: `MPs had opportunities to scrutinise them through committees and six subjects received dedicated Estimates Day debates.` },
    { type: 'paragraph', text: `Then the remaining Estimates were grouped together for approval.` },
    { type: 'paragraph', text: `The next day, the legislation giving statutory effect to the package passed its second and third readings without substantive debate.` },
    { type: 'paragraph', text: `Most departmental Estimates never received their own Commons debate before Parliament approved them.` },
  ],
  evidence: {
    recordsReviewed: [
      `HM Treasury, Main Supply Estimates 2026 to 2027, 29 April 2026: sets out departmental spending plans for 2026/27 and explains that the Estimates seek parliamentary authority for the voted element of plans established through the Spending Review and subsequent fiscal events`,
      `House of Commons Library, Main Estimates: Government spending plans for 2026/27: explains the spending totals and the parliamentary process, including Estimates Days, roll-up motions and MPs' ability to reduce but not increase selected Estimates`,
      `House of Commons, business for 29 and 30 June 2026: records the six subjects selected for debate across the two Main Estimates days`,
      `Hansard, Main Estimates 2026/27, 30 June 2026: records Commons approval of the outstanding Estimates and the resolutions on further current resources, capital resources and Consolidated Fund cash`,
      `Hansard, Supply and Appropriation (Main Estimates) Bill, 1 July 2026: records the second and third readings being put forthwith and agreed without substantive debate`,
      `Hansard Society, guide to parliamentary Supply: explains that Supply resolutions provide political approval before Supply and Appropriation legislation provides the legal authority, and that the subsequent legislation is not an opportunity to amend the spending plans`,
      `Supply and Appropriation (Main Estimates) legislation for 2026/27: records £634.484 billion of additional Main Estimates resource authority, £514.775 billion of additional cash authority, total annual resource appropriation of £1.154943 trillion and total annual cash appropriation of £936.824 billion`,
    ],
    lastChecked: '5 October 2026',
  },
};

export default piece;
