import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'siicjkcsr6',
  kicker: 'Parliament',
  headline: `Lords Advanced Three Reform Bills. Ministers Said No to All Three`,
  standfirst: `Three private members' bills dealing with problems Parliament has argued over for years passed their second readings in the House of Lords on 17 July. One addresses financial protection for unmarried couples. Another would criminalise deceptive sexual relationships by undercover officers. The third would allow UK courts to make preliminary genocide findings. The government declined to support any of them in their present form.`,
  publishedAt: '2026-07-19',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `Three private members' bills dealing with problems Parliament has argued over for years passed their second readings in the House of Lords on Friday.` },
    { type: 'paragraph', text: `One would give financial protection to some unmarried couples when they separate or a partner dies. Another would make it a criminal offence for undercover officers and other covert operatives to enter intimate sexual relationships with people they are targeting. The third would allow UK courts to make preliminary findings of genocide or a serious risk of genocide.` },
    { type: 'paragraph', text: `All three were allowed to proceed to committee stage.` },
    { type: 'paragraph', text: `The government declined to support any of them in their present form.` },
    { type: 'paragraph', text: `The clearest change in government policy concerns cohabitation.` },
    { type: 'paragraph', text: `England and Wales have no equivalent to divorce law allowing courts generally to redistribute an unmarried couple's finances when their relationship ends. Property disputes can instead depend on ordinary property and trust law.` },
    { type: 'paragraph', text: `Around 3.5 million couples were cohabiting in the UK in 2025. The Ministry of Justice says the absence of a dedicated statutory framework can leave economically weaker partners, particularly those who have reduced their earnings to care for children, with limited protection following separation.` },
    { type: 'paragraph', text: `The problem was examined by the Law Commission almost two decades ago.` },
    { type: 'paragraph', text: `Its 2007 report recommended a statutory scheme allowing qualifying former cohabitants to seek financial relief following separation. Further recommendations in 2011 concerned inheritance where a cohabitant dies without a will.` },
    { type: 'paragraph', text: `The Conservative-led government announced in September 2011 that it would not implement the 2007 recommendations during that Parliament. Similar cohabitation recommendations on intestacy were put aside in 2013.` },
    { type: 'paragraph', text: `Lord Marks of Henley-on-Thames has repeatedly tried to revive the proposals through private members' legislation. Versions of his Cohabitation Rights Bill were introduced in 2013, 2014, 2015, 2016, 2017 and 2020. None became law.` },
    { type: 'paragraph', text: `Scotland took a different route much earlier. Sections 25 to 29 of the Family Law (Scotland) Act 2006 established statutory provisions for cohabitants, including claims for financial provision following separation. Most of the Act came into force on 4 May 2006.` },
    { type: 'paragraph', text: `The position in England and Wales has now moved.` },
    { type: 'paragraph', text: `Labour promised in its 2024 manifesto to strengthen protections for women in cohabiting relationships. On 5 June this year, the Ministry of Justice opened its A fairer end to relationships consultation, covering financial provision following separation and inheritance where a cohabitant dies without a will.` },
    { type: 'paragraph', text: `The consultation runs until 14 August.` },
    { type: 'paragraph', text: `That means the government and Lord Marks now agree that legislation is needed. They disagree about its design.` },
    { type: 'paragraph', text: `Lord Marks' bill is largely compensation-based. It would allow courts to address economic advantages and disadvantages created during a relationship.` },
    { type: 'paragraph', text: `The government prefers a needs-based model, aimed particularly at ensuring that financially vulnerable former partners and children have adequate provision after separation.` },
    { type: 'paragraph', text: `Justice minister Baroness Levitt told the Lords on Friday that ministers could not support Lord Marks' bill because legislating now would pre-empt the consultation and because the government was not persuaded by its compensation model.` },
    { type: 'paragraph', text: `She nevertheless went further than previous governments.` },
    { type: 'paragraph', text: `She said ministers were committed to cohabitation reform and had "committed to legislating when parliamentary time allows" after considering the consultation responses.` },
    { type: 'paragraph', text: `The present government therefore cannot fairly be described as simply refusing to act on cohabitation. It has committed itself to legislation.` },
    { type: 'paragraph', text: `It has not said when that legislation will be introduced.` },
    { type: 'paragraph', text: `The second bill exposes a different gap.` },
    { type: 'paragraph', text: `The Undercover Policing Inquiry was established in 2015 after revelations about officers who had infiltrated political and campaign groups, sometimes maintaining intimate sexual relationships under false identities and, in some cases, fathering children.` },
    { type: 'paragraph', text: `Public evidential hearings finally began in November 2020.` },
    { type: 'paragraph', text: `Its first interim report, published in 2023, found serious failures in the Metropolitan Police's Special Demonstration Squad. But Sir John Mitting deliberately postponed general conclusions on deceptive sexual relationships until more evidence had been heard.` },
    { type: 'paragraph', text: `The inquiry therefore has not yet made its final recommendations on that issue.` },
    { type: 'paragraph', text: `Current College of Policing guidance says it is never acceptable for an undercover officer to have an intimate sexual relationship with somebody they have been deployed to infiltrate, target or encounter.` },
    { type: 'paragraph', text: `It is not an absolute prohibition.` },
    { type: 'paragraph', text: `The same guidance allows for circumstances where an officer believes refusing sexual activity would create an immediate threat to themselves or somebody else, provided any conduct is limited to what is necessary to deal with the danger.` },
    { type: 'paragraph', text: `Baroness Hamwee's Conduct of Undercover Policing and Surveillance Operatives Bill would replace that position with a criminal offence.` },
    { type: 'paragraph', text: `It would prohibit intimate sexual relationships involving people targeted or encountered during a deployment and would also create offences for those intentionally encouraging or assisting the conduct. The maximum sentence proposed is life imprisonment.` },
    { type: 'paragraph', text: `Parliament has been close to this argument before.` },
    { type: 'paragraph', text: `During passage of the legislation governing authorised criminal conduct by covert human intelligence sources in 2021, the Lords backed an amendment preventing authorisation of conduct amounting to sexual offences and other serious crimes. Parliament eventually enacted the Covert Human Intelligence Sources (Criminal Conduct) Act without creating the specific offence now proposed by Hamwee.` },
    { type: 'paragraph', text: `The government accepts the historical conduct was wrong.` },
    { type: 'paragraph', text: `It still opposes Hamwee's bill.` },
    { type: 'paragraph', text: `Lord Katz, responding for ministers on Friday, said the bill was drafted so broadly that it could interfere with legitimate undercover operations, including online operations against child sexual offenders, and could capture informants whose existing personal relationships were unrelated to their covert work.` },
    { type: 'paragraph', text: `He told peers that the government was likely to seek to block the bill if it reached the Commons.` },
    { type: 'paragraph', text: `That came one day after the Home Office opened a consultation on whether the Undercover Policing Inquiry itself should continue in its existing form.` },
    { type: 'paragraph', text: `The inquiry was originally expected to report within about three years. By July 2026 it had spent over £138 million and remained unfinished more than a decade after it was established.` },
    { type: 'paragraph', text: `Home Secretary Shabana Mahmood said ministers were concerned about both its cost and the delay in producing answers for people affected by undercover policing. Sir John Mitting is due to retire in 2027.` },
    { type: 'paragraph', text: `The government says it will consider the inquiry's recommendations when they arrive.` },
    { type: 'paragraph', text: `Hamwee's argument is that Parliament does not need another inquiry recommendation to decide that deceptive sexual relationships by undercover officers should be specifically prohibited in law.` },
    { type: 'paragraph', text: `The Lords gave her bill a second reading.` },
    { type: 'paragraph', text: `The government has already indicated what is likely to happen if it reaches the Commons.` },
    { type: 'paragraph', text: `The third bill has an even longer parliamentary history.` },
    { type: 'paragraph', text: `Lord Alton of Liverpool first introduced a Genocide Determination Bill in June 2016. Further versions appeared in 2017, 2019, 2020 and 2023. None reached the statute book.` },
    { type: 'paragraph', text: `The current bill would allow an affected person, group or representative organisation to ask the High Court in England and Wales or Northern Ireland, or the Court of Session in Scotland, for a preliminary determination that genocide had occurred or that there was a serious risk of it occurring.` },
    { type: 'paragraph', text: `A successful determination would then require the government to refer the matter to appropriate international bodies where the relevant jurisdictional requirements were met.` },
    { type: 'paragraph', text: `The bill is intended to address an awkward feature of longstanding British policy.` },
    { type: 'paragraph', text: `Successive governments have said genocide should be formally determined by competent courts rather than politicians. Lord Alton and his supporters argue that this can create a circular problem where no suitable court has a practical route to decide the question.` },
    { type: 'paragraph', text: `The government accepts that there is a problem but rejects his proposed solution.` },
    { type: 'paragraph', text: `Lord Katz said the bill would introduce a novel form of preliminary determination by UK courts with no settled basis in international law, and warned that it risked drawing judges into decisions with political and foreign-policy consequences. Lord Wolfson, speaking for the Conservatives, separately questioned what practical effect a UK finding would have where no international court or body had jurisdiction.` },
    { type: 'paragraph', text: `The government agreed with the objective of preventing genocide but said the bill did not provide the correct constitutional mechanism.` },
    { type: 'paragraph', text: `All three bills nevertheless cleared second reading on 17 July and were committed to Committees of the Whole House.` },
    { type: 'paragraph', text: `That is more than a debate with no formal consequence. Second reading is the stage at which a House agrees to the principle of a bill and allows it to continue through Parliament.` },
    { type: 'paragraph', text: `It is not remotely the same thing as passing a law.` },
    { type: 'paragraph', text: `Private members' bills still have to survive committee, report and third reading in the Lords, repeat those stages in the Commons and secure enough parliamentary time to complete the process. Government opposition can make that extremely difficult.` },
    { type: 'paragraph', text: `The position after Friday is therefore different for each proposal.` },
    { type: 'paragraph', text: `After recommendations dating back to 2007, the government now accepts the case for cohabitation legislation but wants to write its own version after the current consultation.` },
    { type: 'paragraph', text: `On undercover policing, ministers condemn the conduct the bill targets but want to wait for the inquiry and say Hamwee's proposed offence could damage legitimate covert operations.` },
    { type: 'paragraph', text: `On genocide determination, ministers accept the underlying problem but continue to reject the domestic-court mechanism Lord Alton has been proposing in various forms for a decade.` },
    { type: 'paragraph', text: `The three bills are now heading for committee stage.` },
    { type: 'paragraph', text: `None has a date for that stage yet.` },
  ],
  evidence: {
    recordsReviewed: [
      `House of Lords Minutes, 17 July 2026: records second reading and referral to Committee of the Whole House for the Conduct of Undercover Policing and Surveillance Operatives Bill, Genocide Determination Bill and Cohabitation Rights Bill`,
      `House of Lords Hansard, Cohabitation Rights Bill, 17 July 2026: records the government's rejection of Lord Marks' particular model, its preference for a needs-based system and its commitment to legislate after consultation when parliamentary time allows`,
      `Ministry of Justice, A fairer end to relationships, 5 June 2026: sets out the government's proposals on financial provision and inheritance for cohabitants and records the scale of cohabitation in the UK`,
      `Law Commission implementation records: record the 2007 recommendations on financial consequences of cohabitation breakdown, the later inheritance recommendations and previous governments' decisions not to implement them at the time`,
      `Family Law (Scotland) Act 2006 and commencement order: establish Scotland's statutory cohabitation provisions and their commencement on 4 May 2006`,
      `House of Lords Hansard, Conduct of Undercover Policing and Surveillance Operatives Bill, 17 July 2026: records the existing policing guidance, arguments for a statutory prohibition and the government's statement that it was likely to seek to block the bill in the Commons`,
      `Undercover Policing Inquiry, Tranche 1 interim report, 29 June 2023: records the inquiry's scope, the start of evidential hearings in November 2020 and Sir John Mitting's decision to defer general conclusions on deceptive sexual relationships until later stages`,
      `Home Office consultation and Written Ministerial Statement on the Undercover Policing Inquiry, 16 July 2026: the consultation records expenditure of more than £138 million and the inquiry's original three-year expectation; Mahmood's statement confirms that Sir John Mitting will retire in 2027`,
      `House of Lords Hansard and Parliamentary Bills records on the Covert Human Intelligence Sources (Criminal Conduct) Act 2021: record earlier parliamentary attempts to place statutory limits on serious conduct by covert sources`,
      `Genocide Determination Bill [HL], 2026, and previous bill records: establish the mechanism proposed by Lord Alton and the repeated introduction of related bills since 2016`,
      `House of Lords Hansard, Genocide Determination Bill, 17 July 2026: records the government's continued policy that genocide findings should be made by competent courts, Lord Katz's objections to the jurisdiction and constitutional mechanism proposed in the bill, and Lord Wolfson's separate question about the consequence of an absence of international jurisdiction`,
    ],
    lastChecked: '5 October 2026',
  },
};

export default piece;
