import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'skq4m9xw2t',
  kicker: 'Opinion',
  headline: 'State of the UK',
  standfirst:
    'Different parties, different slogans, and the same mistakes repeated in a different accent.',
  publishedAt: '2026-07-04',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: 'Britain is not being failed by one bad government. That would be too easy. The deeper problem is that governments of different colours keep arriving in Westminster, changing the slogan on the door, then repeating the same mistakes with a different accent.' },
    { type: 'paragraph', text: 'The country is run for the next headline, not the next decade. Ministers are moved before they know the machinery they are meant to control. England has had eleven Education Secretaries since 2010, and Gillian Keegan was still in post when RAAC concrete forced schools shut in 2023, a risk her department had been warned about for years before it became an emergency. Policies are announced before the sums are nailed down. Keir Starmer’s final defence plan promised £15 billion in extra spending while leaving a reported £4.7 billion gap for Andy Burnham to fill, a gap Burnham reportedly learned about on the same day it was made public. Reviews are ordered, strategies renamed, targets relaunched. By the time anyone asks what actually changed, the minister responsible is usually in another job, on the back benches, or writing a memoir about public service.' },
    { type: 'paragraph', text: 'This is how Britain keeps getting reform without repair.' },
    { type: 'paragraph', text: 'HS2 showed the system in daylight. Sold to the public at £37 billion, it is now expected to cost more than £100 billion, with the Manchester and Leeds legs cancelled and no minister since George Osborne willing to say plainly who got the price wrong. Overpromise, underprice, delay, deny, cut, rename, repeat. The same pattern runs through defence procurement, where costs drift and deadlines slip; through the courts, where a Crown Court backlog of more than 80,000 cases has turned delay into part of the punishment; and through local government finance, where councils from Birmingham to Woking have been handed duties they cannot afford and then blamed by the same ministers who set their budgets. Britain can announce ambition. It cannot finish enough of what it starts.' },
    { type: 'paragraph', text: 'The failure is not only money, though money matters. It is maintenance. Governments prefer new schemes because new schemes come with speeches, logos and cameras. Maintenance means fixing school buildings before the concrete becomes a national scandal, and RAAC was eventually found in more than 200 schools and education settings, years after the Department for Education had been told the risk existed. Maintenance means funding prisons before they are almost full, not relying on early-release schemes to keep occupancy below crisis point. It means dealing with SEND before families spend years fighting councils for help their children are already entitled to in law, while the government quietly extends the accounting device that hides £9 billion in council SEND deficits rather than funding the shortfall itself. None of that photographs well. So it is left until it breaks loudly enough to embarrass someone.' },
    { type: 'paragraph', text: 'Accountability is the old trick. Ministers claim credit when something works and scatter blame when it does not. The previous government. The civil service. Councils. Courts. Contractors. Regulators. Global markets. Bad weather. Everyone and everything is responsible except the people who asked to be in charge. Civil servants shape decisions without public responsibility. Private contractors take public money without enough fear of failure. Inquiries arrive years late, say what everyone suspected, and the machine bows its head before carrying on. The Independent Inquiry into Child Sexual Abuse took seven years to report and by January 2025 not one of its 20 recommendations had been implemented.' },
    { type: 'paragraph', text: 'Westminster hoards power and exports blame. Local government is expected to handle housing, social care, homelessness, children’s services, potholes, libraries and bins while living off unstable funding settlements and emergency grants. Councils get the anger. Whitehall keeps the control. Then ministers tour the country promising to listen, as though listening fills a budget gap or repairs a collapsed service.' },
    { type: 'paragraph', text: 'The economy sits underneath it all. Weak productivity since the financial crisis has left Britain arguing over scarcity. Tax feels high because it is: Rachel Reeves has raised it by around £66 billion across two Budgets, pushing the burden to a 70-year high. Services feel poor because too much public money is swallowed by the cost of not fixing things properly the first time. Every few years voters are told that a new plan will unlock growth. Growth is not unlocked by a lectern, a backdrop and a minister in a rolled-up shirt. Britain keeps choosing delay and then pretending to be surprised when delay sends the bill.' },
    { type: 'paragraph', text: 'The public is rarely given the full price before the policy is sold. Politicians promise better services without higher taxes, lower taxes without cuts, lower immigration without labour shortages, net zero without costs, new homes without upsetting anyone, and social care reform without saying who pays. Honesty is treated as the dangerous option. Failure is treated as manageable.' },
    { type: 'paragraph', text: 'That is why trust has collapsed. People do not just think government is failing. They think it is performing. They see the announcement, the pledge, the reset, the relaunch, the blame, the inquiry and the silence after it. They have watched this play too many times.' },
    { type: 'paragraph', text: 'What is failing Britain is not simply Labour, the Conservatives, coalition government or one bad prime minister. It is a political culture that rewards noise over competence, evasion over responsibility and survival over repair.' },
    { type: 'paragraph', text: 'The country does not need another grand plan with a patriotic title. It needs government that can count, build, maintain, admit failure, publish results and stay with a problem long enough to fix it. Until that changes, Britain will keep getting new menus from the same broken kitchen.' },
  ],
};

export default piece;
