import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'skq4m9xw2t',
  kicker: 'Opinion',
  headline: `State of the UK: Britain Keeps Funding the Consequences of Delayed Decisions`,
  standfirst: `On 30 June, Keir Starmer announced another £15 billion for defence over the next four years. The remaining £4.7 billion has not yet been allocated. The Defence Investment Plan arrives in a country already carrying the cost of decisions that were priced too late, postponed for years or repeatedly redesigned.`,
  publishedAt: '2026-07-04',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `On 30 June, Keir Starmer announced another £15 billion for defence over the next four years.` },
    { type: 'paragraph', text: `The government's funding document published alongside the plan identified where £10.3 billion would come from. Departments will lose 1 per cent of their capital budgets, government assets will be sold, and further savings will come from transport and energy programmes.` },
    { type: 'paragraph', text: `The remaining £4.7 billion has not yet been allocated. The Treasury says it will be found at Budget 2026.` },
    { type: 'paragraph', text: `There may be perfectly defensible reasons for that. Governments regularly settle spending decisions across several fiscal events, and ministers argue that higher defence spending is necessary as the security situation deteriorates.` },
    { type: 'paragraph', text: `But the Defence Investment Plan arrives in a country already carrying the cost of decisions that were priced too late, postponed for years or repeatedly redesigned.` },
    { type: 'paragraph', text: `HS2 is the clearest example.` },
    { type: 'paragraph', text: `The useful comparison is not between the railway's earliest headline price and today's number because the scope has changed too much for that to be honest. The Manchester and Leeds sections have been cancelled, and today's programme is substantially different from the railway first proposed.` },
    { type: 'paragraph', text: `The comparable figures are bad enough.` },
    { type: 'paragraph', text: `The Department for Transport now estimates that completing the remaining HS2 programme will cost between £87.7 billion and £102.7 billion. The National Audit Office says that is roughly double the 2020 estimate for Phase One. By March this year, £46.8 billion had already been spent, including money on the cancelled northern sections.` },
    { type: 'paragraph', text: `The NAO identified scope changes, inefficient delivery and underestimating how long construction would take as the main causes of the increase.` },
    { type: 'paragraph', text: `HS2 was reset in 2020. It was reset again in 2025. The latest cost range is still not the final assured baseline. That is due in spring 2027.` },
    { type: 'paragraph', text: `Cancelling the remaining railway is no longer an easy escape. The Department for Transport concluded this year that completing it represents better value than stopping, partly because so much has already been built and committed.` },
    { type: 'paragraph', text: `Britain is therefore in the peculiar position of spending close to £50 billion on a railway before it has a final reliable estimate of what the finished railway will cost.` },
    { type: 'paragraph', text: `At the end of March, the Crown Court in England and Wales had 80,061 open cases. More than 22,000 had been open for at least a year, a series peak.` },
    { type: 'paragraph', text: `There was some improvement. Courts disposed of slightly more cases than they received during the quarter, and disposals reached a post-pandemic quarterly high. The backlog fell by fewer than 100 cases.` },
    { type: 'paragraph', text: `So the latest figures do not show a system getting rapidly worse. They show how difficult it has become to recover once a backlog reaches this size.` },
    { type: 'paragraph', text: `For 2026-27, 35 English councils were given in-principle Exceptional Financial Support because they said financial pressures were otherwise unmanageable. Thirty councils received support for 2025-26 and 19 for 2024-25.` },
    { type: 'paragraph', text: `That does not mean every council reached trouble for the same reason, or that Whitehall caused every financial failure. Woking's problems, for example, include huge debts accumulated through its own historic commercial investment decisions.` },
    { type: 'paragraph', text: `Nor is Exceptional Financial Support simply a cheque from central government. Much of it takes the form of capitalisation directions allowing councils to meet costs through borrowing or capital resources that would not normally be available for day-to-day spending.` },
    { type: 'paragraph', text: `It is still supposed to be exceptional.` },
    { type: 'paragraph', text: `The number of councils using it shows how much strain has become embedded in the system.` },
    { type: 'paragraph', text: `Special educational needs finance provides an even clearer example of a bill accumulating before government decided who would ultimately carry it.` },
    { type: 'paragraph', text: `For years, councils were permitted to keep growing Dedicated Schools Grant deficits separate from their main accounts under a statutory accounting override. That prevented the deficits immediately destabilising council finances, but it did not make the underlying cost disappear.` },
    { type: 'paragraph', text: `The current government has now gone considerably further than the original draft of this article suggested. It is not merely extending the accounting device.` },
    { type: 'paragraph', text: `In February, ministers announced that central government would cover 90 per cent of councils' historic high-needs deficits accumulated up to the end of March 2026, subject to councils agreeing local SEND reform plans. The government expects that support to be worth more than £5 billion.` },
    { type: 'paragraph', text: `That is a substantial intervention and should be described as one.` },
    { type: 'paragraph', text: `The statutory override nevertheless remains until March 2028. The remaining 10 per cent of historic deficits stays with councils, while the government has yet to set out precisely how deficits arising during 2026-27 and 2027-28 will be treated.` },
    { type: 'paragraph', text: `The history of school buildings shows how financial pressure can move in the opposite direction: costs postponed through inadequate maintenance eventually returning as an emergency.` },
    { type: 'paragraph', text: `A RAAC panel failed at a school in 2018. The Department for Education subsequently issued warnings and guidance rather than simply ignoring the problem. But it did not know how widespread RAAC was across the school estate.` },
    { type: 'paragraph', text: `By July 2021 the department had escalated the risk of structural failure across school buildings. In October that year it judged the likelihood "very likely," partly because it still could not establish the prevalence of RAAC.` },
    { type: 'paragraph', text: `After further unexpected failures in 2023, the department ordered schools to stop using affected spaces shortly before the beginning of term.` },
    { type: 'paragraph', text: `A final list published in February 2024 identified 234 schools and colleges with confirmed RAAC. Of those, 119 required extensive rebuilding or refurbishment, 110 needed smaller remediation projects, and the remaining five had alternative arrangements already in place.` },
    { type: 'paragraph', text: `The government is now funding its removal.` },
    { type: 'paragraph', text: `That is repair. It is also more expensive and disruptive than knowing the condition of the estate early enough to manage deterioration systematically.` },
    { type: 'paragraph', text: `These pressures sit inside an economy that has made government harder to finance.` },
    { type: 'paragraph', text: `The Office for Budget Responsibility estimates that trend productivity grew by an average of only 0.6 per cent a year between 2010 and 2019, compared with 2.1 per cent in the decade before the financial crisis. It now expects trend productivity growth to reach about 1 per cent by 2030.` },
    { type: 'paragraph', text: `Weak productivity means slower growth in the tax base and living standards. It leaves governments with less room to absorb mistakes.` },
    { type: 'paragraph', text: `Taxes are already moving in the other direction. The OBR expects National Accounts taxes to rise from about 35 per cent of GDP in 2024-25 to just over 38 per cent from 2029-30, the highest level in its series.` },
    { type: 'paragraph', text: `That increase cannot fairly be attributed to Rachel Reeves alone. The OBR says much of it comes from a mixture of policies introduced by successive governments, including freezes in personal tax thresholds, higher corporation tax, increases in employer National Insurance and the latest Budget measures.` },
    { type: 'paragraph', text: `The result is an awkward combination: historically high taxation alongside public systems that still require emergency money, accounting protections or repeated resets.` },
    { type: 'paragraph', text: `There has been real repair as well. The SEND deficits are finally being largely transferred away from councils. RAAC removal is being funded. Crown Court disposals have improved. The current HS2 plan is more realistic about uncertainty than some of the estimates that preceded it.` },
    { type: 'paragraph', text: `Those measures also show how long some problems were allowed to accumulate before the state confronted their cost.` },
    { type: 'paragraph', text: `The government's new Defence Investment Plan contains £15 billion of additional spending. Its own funding table identifies £10.3 billion of funding and leaves the rest for the next Budget.` },
    { type: 'paragraph', text: `The final line for the remaining £4.7 billion reads simply: "To be funded at Budget 2026."` },
  ],
  evidence: {
    recordsReviewed: [
      `HM Treasury and Ministry of Defence, The Defence Investment Plan Funding Explainer, 30 June 2026: the £15 billion additional spending figure, £10.3 billion of identified funding, departmental capital reductions and £4.7 billion left to Budget 2026`,
      `National Audit Office, HS2 programme reset, June 2026: the £46.8 billion spent by March 2026, current £87.7 billion to £102.7 billion cost range, comparison with the 2020 Phase One estimate and identified causes of cost increases`,
      `Department for Transport, HS2 Phase 1: decision to continue delivery following programme reset, May 2026: the current cost and schedule ranges and the decision that completing the remaining programme provides better value than cancellation`,
      `Ministry of Justice, Criminal court statistics quarterly: January to March 2026, 25 June 2026: the 80,061 Crown Court open caseload, the series-peak figure of over 22,000 cases open for a year or more, and the post-COVID quarterly disposal high`,
      `House of Commons Library, Local Government Finance Settlement 2026/27 to 2028/29 (CBP-10485); Ministry of Housing, Communities and Local Government, Exceptional Financial Support records for 2024-25, 2025-26 and 2026-27: the 35 councils given in-principle support for 2026-27 (confirmed 23 February 2026, total just over £1.5 billion), the 30 for 2025-26 and 19 for 2024-25, and the use of capitalisation arrangements`,
      `Ministry of Housing, Communities and Local Government, Local Government Finance Settlement 2026-27, 11 February 2026: the decision to fund 90 per cent of historic high-needs SEND deficits accrued to the end of March 2026, projected at more than £5 billion, conditional on local SEND reform plans, and the continuation of the statutory override until March 2028`,
      `Department for Education, Government confirms plans to permanently remove RAAC from all schools and colleges in England, February 2024: the history of the 2018 RAAC failure, the 2023 emergency closures, and the final 234-setting figure, broken down as 119 requiring School Rebuilding Programme works, 110 receiving smaller-scale grant funding, and 5 with alternative arrangements`,
      `National Audit Office, Department for Education departmental overview 2022-23: the department's escalation of school-building structural risk in 2021 and its uncertainty over the prevalence of RAAC`,
      `Office for Budget Responsibility, Economic and fiscal outlook, November 2025: the long-term productivity comparison (0.6 per cent 2010-2019 versus 2.1 per cent pre-crisis, forecast to reach 1.0 per cent by 2030) and the forecast tax burden rising from 35 per cent of GDP in 2024-25 to just over 38 per cent from 2029-30`,
    ],
    lastChecked: '5 October 2026',
  },
};

export default piece;
