import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'st6k9mxq4w',
  kicker: 'Student Finance',
  headline: `MPs Say Student Loans Were Mis-Sold as Governments Rewrote the Terms`,
  standfirst: `In 2018, a Department for Education presentation gave prospective students one example of what repayment might cost. A graduate earning £27,000 would repay £15 a month. Neither that presentation nor an earlier one made clear that governments retained the power to change important loan terms after the money had been borrowed. The Treasury Committee says that amounted to mis-selling.`,
  publishedAt: '2026-07-16',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `In 2018, a Department for Education presentation explaining student finance gave prospective students one example of what repayment might cost.` },
    { type: 'paragraph', text: `A graduate earning £27,000 would repay £15 a month.` },
    { type: 'paragraph', text: `A later presentation put the same £15 repayment beside everyday spending including a £14 mobile phone bill and £17 for cinema visits or gigs. Neither presentation made clear that governments retained the power to change important loan terms after the money had been borrowed.` },
    { type: 'paragraph', text: `The Treasury Committee says that amounted to mis-selling.` },
    { type: 'paragraph', text: `Its report, published on 7 July, reached that conclusion after examining government promotional material, correspondence with the Student Loans Company and evidence from ministers and finance experts. The finding is not a court judgment and does not expose the government to the legal consequences a regulated lender might face. Student loans have been specifically excluded from much of the consumer protection law governing commercial credit.` },
    { type: 'paragraph', text: `That exemption is unusually important because Plan 2 borrowers have repeatedly had one of their central repayment terms changed.` },
    { type: 'paragraph', text: `When the coalition government set out the new student finance system in 2010, it said graduates would repay 9 per cent of earnings above £21,000 and that the threshold would be increased annually in line with earnings from 2016. Vince Cable repeated the commitment when announcing the final package that December.` },
    { type: 'paragraph', text: `The threshold did not rise as promised.` },
    { type: 'paragraph', text: `The Conservative government consulted in 2015 on freezing it at £21,000. Its preferred option applied the freeze to people who had already taken out Plan 2 loans as well as future borrowers. The consultation said that option produced the largest reduction in government debt. Ministers also argued that earnings had grown more slowly than expected, leaving the £21,000 threshold higher relative to average pay than had originally been intended.` },
    { type: 'paragraph', text: `The threshold stayed at £21,000 for the 2016-17 and 2017-18 repayment years. It was then raised to £25,000 and began increasing again before being held at £27,295 for four years from 2021-22 to 2024-25.` },
    { type: 'paragraph', text: `The Labour government has now decided to freeze it again.` },
    { type: 'paragraph', text: `Rachel Reeves's 2025 Budget set the Plan 2 repayment threshold at £29,385 for 2026-27 and said it would remain there for the following three years, until April 2030. Graduates continue to repay 9 per cent of earnings above the threshold, so holding it still while pay rises means some borrowers make repayments who otherwise would not and others pay more than they would under an uprated threshold.` },
    { type: 'paragraph', text: `The Treasury's stated justification is that the change makes the student loan system more financially sustainable and increases repayments from graduates, who on average earn more, rather than placing the cost on workers who did not attend university.` },
    { type: 'paragraph', text: `The Office for Budget Responsibility estimates that the changes will increase cash receipts by around £400 million a year in the medium term. Treasury costings put the additional amount at £255 million in 2027-28, £290 million in 2028-29 and £355 million in 2029-30.` },
    { type: 'paragraph', text: `There was another change in the Budget that received considerably less attention.` },
    { type: 'paragraph', text: `Plan 2 graduates can pay interest ranging from RPI to RPI plus three percentage points depending on their income. Two earnings thresholds determine where a borrower sits on that scale.` },
    { type: 'paragraph', text: `The OBR recorded that the government had frozen both the repayment threshold and the interest-rate thresholds for three years from 2027-28. The Budget document itself announced only the repayment-threshold freeze.` },
    { type: 'paragraph', text: `When the Treasury Committee raised the second freeze with Chief Secretary to the Treasury Lucy Rigby, she told MPs she had not been aware of it. The committee cited that episode as part of its concern about the way changes to student loans are communicated.` },
    { type: 'paragraph', text: `The committee's mis-selling finding goes further back than the latest Budget.` },
    { type: 'paragraph', text: `It identified three practices which it said crossed that line.` },
    { type: 'paragraph', text: `Department for Education videos and presentations told students that repayment thresholds would move with earnings but did not explain that future governments could change those arrangements retrospectively. The department also used promotional material comparing low monthly repayments with costs such as mobile phone bills and cinema tickets, a comparison the committee said became inaccurate for graduates earning more.` },
    { type: 'paragraph', text: `The third finding concerned the Student Loans Company.` },
    { type: 'paragraph', text: `It does tell applicants that regulations can change and therefore the terms of their loans may change. But the warning sits within its guide to the terms and conditions rather than being presented as a prominent acknowledgement during the application process. The committee said that also amounted to mis-selling.` },
    { type: 'paragraph', text: `The legal position is different from an ordinary commercial loan.` },
    { type: 'paragraph', text: `Section 8 of the Sale of Student Loans Act 2008 excludes the loans from regulation under the Consumer Credit Act and the Financial Services and Markets Act. The Student Loans Company told the committee that the loans are statutory rather than contractual. Their substantive conditions are established through regulations made under legislation.` },
    { type: 'paragraph', text: `That means the government's ability to alter the rules was not itself hidden in law. Baroness Smith of Malvern, the skills minister, rejected comparisons with scandals such as payment protection insurance, telling MPs that the legislation and terms allowed provisions to be changed in future.` },
    { type: 'paragraph', text: `The committee's complaint is about how clearly that power was explained to the people borrowing the money.` },
    { type: 'paragraph', text: `Students were shown government material saying the repayment threshold would rise with earnings. A Department for Education video similarly said it would be adjusted in line with future earnings. The committee found no accompanying warning in those materials that ministers could later abandon that policy for borrowers who had already taken out their loans.` },
    { type: 'paragraph', text: `The Student Loans Company told MPs that applicants are directed to a guide, must confirm they have read information about their loans and can follow links to the underlying regulations. It does not provide each applicant with the complete body of regulations constituting the substantive terms.` },
    { type: 'paragraph', text: `The committee wants future government student-loan advertising to meet standards comparable to the FCA's Consumer Duty and financial promotions rules even though those requirements do not legally apply. It also wants future borrowers told explicitly that later governments can retrospectively alter loan conditions.` },
    { type: 'paragraph', text: `It has gone further by recommending that future student loans should become contractual agreements, limiting governments' ability to worsen existing borrowers' terms without compensation. It also wants Reeves to reverse the latest repayment-threshold freeze at the next Budget.` },
    { type: 'paragraph', text: `The committee received more than 52,000 responses to its public survey, although that exercise was a consultation rather than a representative opinion poll. Its mis-selling conclusions do not depend on those responses alone. They are based in part on the Department for Education's own surviving promotional material.` },
    { type: 'paragraph', text: `The £29,385 threshold is currently due to remain frozen from April 2027 until April 2030.` },
    { type: 'paragraph', text: `The Budget that announced that freeze did not say that the income thresholds determining Plan 2 interest rates were being frozen as well. That change appeared in the OBR's accompanying documents instead.` },
  ],
  evidence: {
    recordsReviewed: [
      `House of Commons Treasury Committee, Student loans: Broken and unfair?, 7 July 2026: the committee's three findings of mis-selling, its examination of Department for Education promotional material, the statutory consumer-protection exemptions, evidence from ministers and the Student Loans Company, and its recommendations`,
      `Department for Business, Innovation and Skills, Changes to tuition fees and higher education, 2010: contemporary government announcement stating that the £21,000 Plan 2 repayment threshold would be increased annually in line with earnings from 2016`,
      `Department for Business, Innovation and Skills, An improved higher education package, 8 December 2010: Vince Cable's announcement confirming annual earnings uprating of the £21,000 threshold from 2016`,
      `Department for Business, Innovation and Skills, Consultation on freezing the student loan repayment threshold, 2015, and government response: the first decision to apply a threshold freeze to existing Plan 2 borrowers and the government's financial-sustainability rationale`,
      `Student Loans Company, Income Contingent Student Loan repayment plans and interest rates: the historical Plan 2 repayment thresholds and current repayment structure`,
      `HM Treasury, Budget 2025, 26 November 2025: the decision to freeze the £29,385 Plan 2 repayment threshold from April 2027 and the government's stated justification for the measure`,
      `HM Treasury, Budget 2025 policy costings: the forecast fiscal effects of the Plan 2 threshold measure, including £255 million in 2027-28 and £355 million in 2029-30`,
      `Office for Budget Responsibility, Economic and fiscal outlook, November 2025: the finding that both repayment and interest-rate thresholds were frozen and the estimate that the changes increase cash receipts by around £400 million a year in the medium term`,
    ],
    lastChecked: '4 October 2026',
  },
};

export default piece;
