import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'td4k9mxw7r',
  kicker: 'Devolution',
  headline: `Government Gives English Mayors Power to Set an Uncapped Tax on Overnight Stays`,
  standfirst: `English mayors and strategic authority leaders will be able to impose an uncapped percentage tax on overnight accommodation stays. Fifty-eight per cent of consultation respondents supported a national rate cap. Sixty per cent opposed the percentage-based model. The government rejected both majority positions.`,
  publishedAt: '2026-09-10',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `English mayors and Foundation Strategic Authority leaders will be allowed to impose a new tax on overnight stays without a national cap on the rate, despite most respondents to the government's consultation supporting one.` },
    { type: 'paragraph', text: `The new Overnight Visitor Levy will apply to paid accommodation such as hotels, B&Bs and short-term lets.` },
    { type: 'paragraph', text: `The government says the money can be used to support transport, public spaces, tourism and other local priorities.` },
    { type: 'paragraph', text: `But the consultation response shows that ministers rejected the majority view on several of the most important parts of the scheme.` },
    { type: 'paragraph', text: `Fifty-eight per cent of respondents supported a national cap on the maximum rate.` },
    { type: 'paragraph', text: `The government decided not to introduce one.` },
    { type: 'paragraph', text: `Sixty per cent opposed the government's preferred percentage-based charging model.` },
    { type: 'paragraph', text: `The government chose it anyway.` },
    { type: 'paragraph', text: `And when asked whether accommodation providers should be legally responsible for paying the levy to the authority, more respondents opposed the proposal than supported it.` },
    { type: 'paragraph', text: `Consultations are not referendums and governments are entitled to reject the responses they receive.` },
    { type: 'paragraph', text: `But the figures complicate the presentation of the policy as a locally driven settlement shaped by consultation.` },
    { type: 'heading', level: 2, text: `No national ceiling` },
    { type: 'paragraph', text: `The government wants strategic authorities to decide whether to introduce the levy and to set the rate locally.` },
    { type: 'paragraph', text: `It considered putting a national ceiling on that rate.` },
    { type: 'paragraph', text: `The consultation response says 706 of the 1,223 respondents, or 58 per cent, supported a cap, while 19 per cent opposed one and 23 per cent did not answer the question.` },
    { type: 'paragraph', text: `Ministers rejected the idea, arguing that a cap "could create market-distorting effects, such as the cap operating as a default rate regardless of local market conditions."` },
    { type: 'paragraph', text: `That means Parliament is being asked to create a new local tax power without setting a maximum percentage that can be charged.` },
    { type: 'paragraph', text: `The government's argument is that local leaders should decide what is appropriate for their own areas.` },
    { type: 'paragraph', text: `That gives mayors and strategic authority leaders greater fiscal freedom.` },
    { type: 'paragraph', text: `It also means the eventual cost to visitors will depend heavily on where they stay.` },
    { type: 'heading', level: 2, text: `Government chose the percentage model despite opposition` },
    { type: 'paragraph', text: `The levy will be charged as a percentage of the accommodation price rather than as a flat nightly fee.` },
    { type: 'paragraph', text: `The government's stated case is explicitly about protecting cheaper stays: it says charging by percentage will "protect budget holidays" because a cheap room attracts a smaller charge than an expensive one.` },
    { type: 'paragraph', text: `But the consultation response shows strong opposition.` },
    { type: 'paragraph', text: `Sixty per cent of respondents opposed a percentage model.` },
    { type: 'paragraph', text: `Only 21 per cent supported it, with 19 per cent giving no answer.` },
    { type: 'paragraph', text: `Accommodation providers raised concerns about administrative complexity and market distortion.` },
    { type: 'paragraph', text: `Ministers decided the proportionality argument outweighed those concerns.` },
    { type: 'paragraph', text: `The consequence is that the tax will automatically rise when accommodation prices rise.` },
    { type: 'paragraph', text: `That includes peak periods such as school holidays.` },
    { type: 'paragraph', text: `The government's own assessment records concerns that families could face higher charges when room prices are already elevated during those periods.` },
    { type: 'heading', level: 2, text: `Hotels and landlords will become tax collectors` },
    { type: 'paragraph', text: `Hotels, B&Bs and other accommodation businesses will be responsible for paying the levy to strategic authorities and mayors.` },
    { type: 'paragraph', text: `The government says it will work with businesses to make the system as simple as possible.` },
    { type: 'paragraph', text: `But the tax will still create a new administrative obligation.` },
    { type: 'paragraph', text: `Providers will need to calculate the amount due, keep records and submit payments through the system eventually established by local authorities.` },
    { type: 'paragraph', text: `The consultation found more opposition than support for placing the legal liability on accommodation providers: 46 per cent disagreed, against 28 per cent in favour and 26 per cent giving no answer, citing compliance risks and administrative burdens.` },
    { type: 'paragraph', text: `The government nevertheless retained that model.` },
    { type: 'paragraph', text: `For large hotel groups, adapting booking software may be manageable.` },
    { type: 'paragraph', text: `For independent B&Bs and holiday-let businesses, another tax registration and reporting system may be more significant.` },
    { type: 'heading', level: 2, text: `Not every taxed stay will be a holiday` },
    { type: 'paragraph', text: `The language around the policy repeatedly describes visitors and tourists.` },
    { type: 'paragraph', text: `But the tax is based primarily on paid accommodation, not on the reason for the stay.` },
    { type: 'paragraph', text: `That distinction matters.` },
    { type: 'paragraph', text: `A hotel room may be occupied by a tourist.` },
    { type: 'paragraph', text: `It may also be occupied by somebody travelling for work, attending a funeral or visiting a relative in hospital.` },
    { type: 'paragraph', text: `The government has proposed national exemptions for some clearly non-tourism or non-commercial accommodation, including temporary accommodation, shelters, refuges and campsites, with local leaders free to add further exemptions of their own.` },
    { type: 'paragraph', text: `But it has deliberately resisted building large numbers of visitor-specific exemptions into the national system because that would require accommodation businesses to determine why somebody is travelling.` },
    { type: 'paragraph', text: `That keeps administration simpler.` },
    { type: 'paragraph', text: `It also means people who do not regard themselves as tourists may still pay a visitor levy.` },
    { type: 'heading', level: 2, text: `Disabled travellers were identified as a possible problem` },
    { type: 'paragraph', text: `The government's own consultation response identifies another unresolved issue.` },
    { type: 'paragraph', text: `Respondents warned that accessible hotel rooms can sometimes cost more than standard accommodation.` },
    { type: 'paragraph', text: `Because the levy is percentage-based, a higher room price could produce a higher tax.` },
    { type: 'paragraph', text: `The government says it does not hold data comparing the price of accessible and non-accessible rooms in England.` },
    { type: 'paragraph', text: `Respondents also raised the position of disabled travellers who need a carer to occupy a separate room, warning they "may also be disproportionately affected under both flat rate and percentage-based levy models."` },
    { type: 'paragraph', text: `The final impact will depend on exemptions individual authorities choose to introduce.` },
    { type: 'paragraph', text: `That leaves another important part of the policy to local discretion.` },
    { type: 'heading', level: 2, text: `Revenue does not have to be spent only on tourism` },
    { type: 'paragraph', text: `The government says levy proceeds can support local priorities including high streets, transport, public spaces and attractions.` },
    { type: 'paragraph', text: `That means this is broader than a narrowly ring-fenced tourism tax.` },
    { type: 'paragraph', text: `Local leaders will determine how revenues are used.` },
    { type: 'paragraph', text: `That flexibility may allow money to be directed where visitor pressure is greatest.` },
    { type: 'paragraph', text: `But it also means accommodation businesses cannot assume every pound collected will be returned directly to the tourism sector.` },
    { type: 'paragraph', text: `The government says authorities will have to consult locally and publish plans before introducing a levy.` },
    { type: 'paragraph', text: `Mayors and Foundation Strategic Authority leaders are expected to set out spending plans by early 2028.` },
    { type: 'heading', level: 2, text: `The government is creating the tax before the collection system is finished` },
    { type: 'paragraph', text: `The broad policy has been settled.` },
    { type: 'paragraph', text: `The machinery has not.` },
    { type: 'paragraph', text: `Government says it will provide strategic authorities with powers to administer and collect the tax, together with a compliance framework, with legislation to follow.` },
    { type: 'paragraph', text: `But detailed questions around registration, enforcement, package holidays, booking platforms and local administration are still being worked through.` },
    { type: 'paragraph', text: `That creates a familiar pattern.` },
    { type: 'paragraph', text: `The political announcement comes first.` },
    { type: 'paragraph', text: `The operational detail follows.` },
    { type: 'paragraph', text: `The success of the levy will therefore depend less on the principle of charging visitors and more on the system eventually built to collect it.` },
    { type: 'paragraph', text: `If administration is cheap and revenues are substantial, the model may give local authorities a useful new source of funding.` },
    { type: 'paragraph', text: `If compliance costs are high and rates vary widely between neighbouring areas, the burden could become more visible than the benefit.` },
    { type: 'heading', level: 2, text: `The consultation tells a different story from the press release` },
    { type: 'paragraph', text: `The government presents the levy as another step in shifting power away from Westminster.` },
    { type: 'paragraph', text: `There is a coherent argument for that.` },
    { type: 'paragraph', text: `English local government has comparatively little tax-raising autonomy, and visitor levies are common internationally.` },
    { type: 'paragraph', text: `But the detailed consultation response is more uncomfortable than the announcement.` },
    { type: 'paragraph', text: `Most respondents opposed the percentage model.` },
    { type: 'paragraph', text: `Most supported a national cap.` },
    { type: 'paragraph', text: `More opposed placing legal liability on accommodation providers than supported it.` },
    { type: 'paragraph', text: `Government chose all three anyway.` },
    { type: 'paragraph', text: `That does not invalidate the policy.` },
    { type: 'paragraph', text: `It does show why the word "consultation" should never be confused with consent.` },
    { type: 'paragraph', text: `The real test will come when the first mayor publishes a rate.` },
    { type: 'paragraph', text: `At that point the argument stops being about devolution in principle.` },
    { type: 'paragraph', text: `It becomes much simpler:` },
    { type: 'paragraph', text: `how much extra will a night away cost, how much will the tax raise, how much will it cost to administer, and where will the money actually go?` },
  ],
  evidence: {
    recordsReviewed: [
      'Ministry of Housing, Communities and Local Government / GOV.UK, 10 September 2026: "Local leaders handed powers to drive investment in communities" — eligible authorities, percentage-model rationale, collection responsibility, exemptions, early-2028 spending-plan timeline',
      'Government response to the Overnight Visitor Levy consultation — 706/1,223 (58%) for national cap vs 19% against; 60% opposing percentage model vs 21% supporting; 46% opposing provider liability vs 28% supporting; "market-distorting effects" cap reasoning; accessible-room and carer\'s-room findings; government confirmation it holds no comparative accessible/non-accessible room pricing data',
    ],
    lastChecked: '30 September 2026',
  },
};

export default piece;
