import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'ten-worst-performing-councils-england',
  kicker: 'Local Government',
  headline: `Ten of England's Most Serious Council Failures`,
  standfirst: `There is no official league table of England's worst councils, and pretending there is would create more certainty than the evidence allows. This ranking looks at the severity of documented failures since 2018: Section 114 notices, Best Value findings, unsustainable debt, government intervention, failures of financial control and the length of the recovery required.`,
  publishedAt: '2026-06-08',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `There is no official league table of England's worst councils, and pretending there is would create more certainty than the evidence allows.` },
    { type: 'paragraph', text: `A district council such as Woking cannot sensibly be compared with Birmingham simply by looking at debt or spending. A Section 114 notice measures financial inability to balance a budget, not the quality of every service. Government intervention can be triggered by financial failure, governance failure or both.` },
    { type: 'paragraph', text: `This ranking therefore looks at the severity of documented failures since 2018: Section 114 notices, Best Value findings, unsustainable debt, government intervention, failures of financial control and the length of the recovery required.` },
    { type: 'paragraph', text: `On that basis, some of the original figures need correcting. In particular, Woking's £1.2 billion figure was not its debt. Croydon did not legally go bankrupt three times. Nottingham's 2021 Section 114 notice was not caused by Robin Hood Energy. Liverpool's commissioners left in 2024.` },
    { type: 'paragraph', text: `The underlying record is serious enough without making it worse.` },
    { type: 'paragraph', text: `Woking remains the clearest example of a council allowing borrowing and commercial activity to grow beyond anything its ordinary finances could support.` },
    { type: 'paragraph', text: `An external assurance review in 2023 reported borrowing of about £1.8 billion. Woking's later accounts described debt exceeding £2 billion.` },
    { type: 'paragraph', text: `When its Section 114 notice was issued in June 2023, the council estimated a £1.2 billion negative General Fund position against core funding of only £16 million. Those are different figures. The £1.2 billion was not the amount Woking had borrowed. It was the estimated hole in the General Fund after accounting for impaired loans and years of inadequate provision for repaying debt.` },
    { type: 'paragraph', text: `The council's problems went beyond one development.` },
    { type: 'paragraph', text: `Large sums had been lent to council-owned companies and regeneration ventures. The external review found a commercial investment programme of a scale disproportionate to the council's resources and concluded that Woking lacked the capacity and capability to manage the risks it had accumulated.` },
    { type: 'paragraph', text: `The Section 114 report also found that the Minimum Revenue Provision, the amount councils are required to set aside to repay borrowing, had been calculated incorrectly for years. The correction added about £95 million to the charge for 2023/24 alone.` },
    { type: 'paragraph', text: `Government commissioners remain in place. Their March 2026 report found significant progress in governance, finance and the commercial programme, so the picture is no longer one of an authority simply continuing the behaviour that caused the collapse. But the financial legacy remains. Commissioners said delivering the recovery plan while preparing for local government reorganisation continued to present a significant challenge.` },
    { type: 'paragraph', text: `Woking does not need an invented ratio to make the point. A council with ordinary annual resources measured in tens of millions accumulated debt measured in billions.` },
    { type: 'paragraph', text: `Birmingham's September 2023 Section 114 notice identified an £87 million in-year budget gap and an estimated equal pay liability of between £650 million and £760 million.` },
    { type: 'paragraph', text: `The council had already paid approximately £1.1 billion settling equal pay claims during the previous decade. Its entire annual revenue budget was then about £750 million.` },
    { type: 'paragraph', text: `The Oracle finance system compounded the problem, but the original draft overstated its cost.` },
    { type: 'paragraph', text: `Government intervention documents put the estimated cost of resolving the Oracle implementation at about £100 million, not simply "hundreds of millions". They also identified failures to deliver planned savings and wider weaknesses in financial governance.` },
    { type: 'paragraph', text: `The problems did not disappear once commissioners arrived in October 2023.` },
    { type: 'paragraph', text: `By late 2025, commissioners said the £87 million gap and £760 million estimated equal pay liability used when they arrived had been reasonable figures. They also said there had been a further £375 million gap in the 2024/25 budget with no savings initially identified to meet it.` },
    { type: 'paragraph', text: `There has since been progress. The commissioners' latest published assessment before this article found improvements in areas including equal pay and adult and children's services.` },
    { type: 'paragraph', text: `It also described that progress as fragile and slower than anticipated. An assurance plan published in February 2026 set out what Birmingham would have to achieve before commissioners could recommend ending the intervention.` },
    { type: 'paragraph', text: `Birmingham's failure was not one unpaid bill or one broken computer system. Equal pay, Oracle, budget control and governance problems converged until the council no longer had the financial capacity to absorb them.` },
    { type: 'paragraph', text: `Croydon is often described as having gone bankrupt three times.` },
    { type: 'paragraph', text: `That is not technically what happened.` },
    { type: 'paragraph', text: `English local authorities do not enter bankruptcy proceedings. A Section 114 notice is issued when the chief finance officer concludes that the council cannot balance its budget without corrective action.` },
    { type: 'paragraph', text: `Croydon issued its first notice in November 2020. Another followed in December, but that second notice continued the restrictions imposed by the first rather than representing an entirely separate financial collapse. A further Section 114 notice was issued in November 2022.` },
    { type: 'paragraph', text: `The underlying financial position was severe enough without turning those notices into three bankruptcies.` },
    { type: 'paragraph', text: `By 2023 Croydon reported £1.6 billion of debt, including about £1.3 billion attributable to the General Fund. Around £47 million a year was being spent servicing that debt before money could be used for current services.` },
    { type: 'paragraph', text: `The council had invested heavily in property and in its housing company Brick by Brick. Two reports in the public interest subsequently identified serious governance and financial-management failures.` },
    { type: 'paragraph', text: `Government intervention began in 2021 and became statutory in 2022.` },
    { type: 'paragraph', text: `Croydon's position also remains financially exceptional. For 2026/27 the government agreed £119 million of Exceptional Financial Support in principle, after revising its 2025/26 support to £110.3 million.` },
    { type: 'paragraph', text: `Croydon is no longer in the uncontrolled deterioration that produced its first Section 114 notice. It is still carrying the debt created during that period.` },
    { type: 'paragraph', text: `Thurrock's collapse came from an investment strategy that exposed a relatively small council to financial risks on an extraordinary scale.` },
    { type: 'paragraph', text: `By November 2022 the council expected £275.4 million of investment losses. It was setting aside a further £129.2 million to deal with investment debt, contributing to an in-year funding gap of £469.6 million before mitigation. The following year's projected gap was £184.4 million.` },
    { type: 'paragraph', text: `The subsequent Best Value Inspection found systemic weaknesses in finance, governance and leadership. Government intervention had already begun in September 2022 and was expanded after inspectors and commissioners uncovered the scale of the problems.` },
    { type: 'paragraph', text: `Not every pound invested disappeared.` },
    { type: 'paragraph', text: `A portfolio of 53 solar farms was sold in 2024 and produced just over £510 million for debt reduction. That matters because describing the whole investment portfolio as money simply "lost" would be wrong.` },
    { type: 'paragraph', text: `The failure was the way the council accumulated and governed the risk.` },
    { type: 'paragraph', text: `Commissioners were still overseeing Thurrock in 2026. Their January report recorded continued progress but also continuing risks to recovery. The government has agreed £68.91 million of Exceptional Financial Support in principle for 2026/27.` },
    { type: 'paragraph', text: `Slough's collapse exposed a different problem: the council's own financial records had ceased to provide a reliable picture of its position.` },
    { type: 'paragraph', text: `Its July 2021 Section 114 notice did not reveal a single £96 million current-year deficit, as the original version of this article stated.` },
    { type: 'paragraph', text: `The council estimated that it had ended 2020/21 with a negative General Fund balance of approximately £56 million, with a further £40 million pressure during 2021/22. Without action, the negative position was projected to reach £159 million by March 2025.` },
    { type: 'paragraph', text: `Investigations then uncovered errors in the treatment of its Minimum Revenue Provision, asset lives, capital receipts and other accounting decisions. Some problems extended back several years.` },
    { type: 'paragraph', text: `The initial external assurance review described a breakdown in scrutiny and accountability as well as serious financial mismanagement.` },
    { type: 'paragraph', text: `Five years later, Slough has still not completed its recovery.` },
    { type: 'paragraph', text: `Commissioners reported in March 2026 that earlier progress had not been sustained. Continued budget pressures and falling reserves were restricting the council's ability to carry out its transformation plans, and the government commissioned another external review of the intervention.` },
    { type: 'paragraph', text: `Slough has also been granted £42.899 million of Exceptional Financial Support in principle for 2026/27.` },
    { type: 'paragraph', text: `The troubling fact is no longer merely that Slough lost control of its finances in 2021. It is that government intervention has continued for years without yet producing a stable exit.` },
    { type: 'paragraph', text: `Warrington was missing from the original ranking. By June 2026 that omission is difficult to defend.` },
    { type: 'paragraph', text: `Its debt stood at almost £1.8 billion in January 2025, equivalent to 4.8 times its total service expenditure and, according to the government's intervention documents, the highest debt of any unitary authority in England at that point.` },
    { type: 'paragraph', text: `CIPFA's capital review raised concerns about the scale of Warrington's commercial activity, debt, decision-making and governance.` },
    { type: 'paragraph', text: `A subsequent Best Value Inspection found failings across continuous improvement, leadership, governance, culture and use of resources. Ministers imposed a statutory intervention in July 2025 running until July 2030.` },
    { type: 'paragraph', text: `The first report from the government's envoys, published in March 2026, found early signs of change but emphasised the seriousness of the financial position, failures in the commercial investment approach and weaknesses in governance.` },
    { type: 'paragraph', text: `Warrington has since asked for Exceptional Financial Support. Government agreed £87.029 million in principle for 2025/26 and £92.047 million for 2026/27.` },
    { type: 'paragraph', text: `A council with almost £1.8 billion of debt, a statutory intervention scheduled to last until 2030 and nearly £180 million of in-principle Exceptional Financial Support across two years belongs on any serious list of England's most troubled local authorities.` },
    { type: 'paragraph', text: `Nottingham's problems cannot be reduced to Robin Hood Energy.` },
    { type: 'paragraph', text: `The council-owned energy company was established in 2015 with the stated aim of tackling fuel poverty and providing cheaper energy. It collapsed in 2020 after losing tens of millions of pounds. A government-commissioned rapid review found serious weaknesses in governance and risk management.` },
    { type: 'paragraph', text: `But Nottingham's December 2021 Section 114 action was about a different failure.` },
    { type: 'paragraph', text: `The council had improperly used money from its ring-fenced Housing Revenue Account to finance General Fund spending over a period stretching from 2011 to 2021. The council subsequently transferred £14.366 million back into the Housing Revenue Account from reserves. An independent assessment described the transfers as irregular and unlawful.` },
    { type: 'paragraph', text: `Nottingham issued another Section 114 notice in November 2023 because it could not balance that year's budget.` },
    { type: 'paragraph', text: `Commissioners were appointed in February 2024. By December 2025 they reported significant improvement, but said Nottingham remained at an early stage of recovery and still faced important challenges.` },
    { type: 'paragraph', text: `The commissioner-led phase ended in February 2026. It was not the end of government involvement.` },
    { type: 'paragraph', text: `In March the government replaced commissioners with ministerial envoys and statutory directions running until September 2027.` },
    { type: 'paragraph', text: `Nottingham therefore presents a less tidy story than the original version suggested. Robin Hood Energy was a major failure, but it was one part of a wider and longer breakdown in financial governance.` },
    { type: 'paragraph', text: `Northamptonshire's place on the list survives scrutiny, but the reason needs tightening.` },
    { type: 'paragraph', text: `The council issued two Section 114 notices in 2018. A Best Value Inspection found poor financial management, inadequate budgetary control and a culture that discouraged challenge.` },
    { type: 'paragraph', text: `The inspectors were unusually explicit about one point: they did not attribute Northamptonshire's failure simply to insufficient funding.` },
    { type: 'paragraph', text: `Commissioners were sent in to take control of key governance and financial functions.` },
    { type: 'paragraph', text: `The original draft went too far in saying commissioners concluded that no intervention short of dissolving the council could work. What inspectors actually recommended was local government reorganisation, with a two-unitary structure as their preferred option.` },
    { type: 'paragraph', text: `That recommendation ultimately became reality.` },
    { type: 'paragraph', text: `Northamptonshire County Council and the seven district and borough councils in the county were abolished in April 2021 and replaced by North Northamptonshire Council and West Northamptonshire Council.` },
    { type: 'paragraph', text: `That makes Northamptonshire unusual among the authorities here. The failed institution no longer exists.` },
    { type: 'paragraph', text: `Liverpool's problem was governance rather than a Section 114 financial collapse.` },
    { type: 'paragraph', text: `Max Caller's 2021 inspection identified serious failures involving highways, planning, property management, regeneration, contracts and corporate governance. Ministers subsequently appointed commissioners with powers over parts of the authority.` },
    { type: 'paragraph', text: `The intervention lasted three years.` },
    { type: 'paragraph', text: `The original version of this article said commissioners were still involved in 2025. They were not.` },
    { type: 'paragraph', text: `The statutory directions and commissioner appointments expired on 9 June 2024. Liverpool then established a non-statutory Improvement and Assurance Board, which ran until March 2025, before moving continuing oversight into an internal Improvement Committee.` },
    { type: 'paragraph', text: `That does not erase the failures that triggered intervention. It does materially change how Liverpool should be described today.` },
    { type: 'paragraph', text: `The final commissioners' report recorded extensive improvement, while the government had been considering a further stage of intervention before the 2024 general election interrupted that process.` },
    { type: 'paragraph', text: `Liverpool belongs on a list of serious recent governance failures. It should not be presented as a council still under commissioners when it is not.` },
    { type: 'paragraph', text: `Tower Hamlets belongs on the list for a reason missing entirely from the original draft: it is now under its second major government intervention in little more than a decade.` },
    { type: 'paragraph', text: `A Best Value Inspection in 2014 found failures involving grant making, property disposals and publicity spending. Commissioners were appointed and the intervention eventually ended in September 2018 after the government concluded that sufficient progress had been made.` },
    { type: 'paragraph', text: `Concerns returned.` },
    { type: 'paragraph', text: `A new inspection published in November 2024 found serious problems in leadership, culture, governance and partnership working, although inspectors also recorded progress in areas including use of resources, service delivery and continuous improvement.` },
    { type: 'paragraph', text: `Ministerial envoys were appointed in January 2025.` },
    { type: 'paragraph', text: `By January 2026 the government said financial management and governance were deteriorating and concluded that Tower Hamlets was also failing its Best Value Duty in its use of resources.` },
    { type: 'paragraph', text: `The intervention was strengthened in March 2026 and is now scheduled to run until March 2028. Envoys said progress had been made but that the overall pace of change and leadership grip remained insufficient.` },
    { type: 'paragraph', text: `The precedent matters. Tower Hamlets had already been through inspection, commissioners, improvement plans and eventual release from intervention. Less than six years after that intervention ended, ministers ordered another Best Value Inspection.` },
    { type: 'paragraph', text: `There is no single explanation for these failures.` },
    { type: 'paragraph', text: `Woking, Thurrock and Warrington accumulated extraordinary financial exposure through borrowing and commercial activity. Croydon combined heavy borrowing with failures in governance and financial management. Birmingham accumulated equal pay liabilities alongside a failed financial-system implementation and severe budget pressures. Slough lost control of basic financial information. Nottingham suffered repeated governance and accounting failures. Northamptonshire's inspectors found poor management and inadequate challenge. Liverpool and Tower Hamlets were primarily governance interventions rather than Section 114 collapses.` },
    { type: 'paragraph', text: `England also has a wider council-finance problem that cannot simply be blamed on reckless investments.` },
    { type: 'paragraph', text: `For 2026/27, the government granted 35 local authorities in-principle Exceptional Financial Support, worth just over £1.5 billion in total. They include Croydon, Slough, Somerset, Thurrock, Warrington and Woking. The government itself says councils seek this help for different reasons, ranging from one-off pressures to the continuing consequences of historical financial mismanagement and governance failures.` },
    { type: 'paragraph', text: `Exceptional Financial Support is also easily misunderstood. It is generally capitalisation support rather than an ordinary cash grant. It allows approved revenue costs to be financed through borrowing or capital receipts. Somerset, for example, describes its 2026/27 £30 million package as allowing day-to-day spending to be financed over several years through additional borrowing or asset sales.` },
    { type: 'paragraph', text: `The official list for 2026/27 therefore contains councils suffering from very different problems.` },
    { type: 'paragraph', text: `Woking is on it after years of borrowing and commercial failures left it with debt measured in billions. Somerset is on it while dealing with severe continuing spending pressures and service demand. Warrington is on it while dismantling parts of a debt-backed commercial strategy. Croydon remains on it while servicing debt inherited from its earlier collapse.` },
    { type: 'paragraph', text: `The same government support mechanism is now being used for all of them.` },
  ],
  evidence: {
    recordsReviewed: [
      `Woking Borough Council, Section 114 report and 2022/23 accounts: establish the £1.2 billion estimated General Fund deficit, £16 million core funding figure, Minimum Revenue Provision problem and scale of historic borrowing`,
      `Woking Borough Council external assurance review and Grant Thornton Public Interest Report: examine the council's investment strategy, governance, debt and causes of the financial failure`,
      `Woking Commissioners' sixth report, 24 March 2026: records the progress made and the financial and organisational challenges still facing the council`,
      `Birmingham City Council Section 114 material and government intervention documents: establish the £87 million in-year gap, estimated £650 million to £760 million equal pay liability and estimated £100 million cost of resolving Oracle`,
      `Birmingham Commissioners and statutory intervention material, 2025-26: records the state of the recovery and the conditions expected before intervention can end`,
      `Croydon Council financial recovery material and government Exceptional Financial Support data: establish the £1.6 billion debt burden, annual debt-servicing cost and continuing financial support`,
      `Thurrock Council financial reports and Best Value Inspection: establish the investment losses, funding gap and systemic weaknesses that led to intervention`,
      `Slough Borough Council intervention documents and Commissioners' seventh report: record the original accounting and financial failures and the incomplete recovery as of March 2026`,
      `Warrington Borough Council Best Value intervention and Ministerial Envoys' first report: establish the nearly £1.8 billion debt position, Best Value failures and continuing statutory intervention`,
      `Nottingham City Council Housing Revenue Account investigation and 2026 intervention documents: establish the unlawful HRA transfers and the transition from commissioners to continuing ministerial oversight`,
      `Northamptonshire County Council Best Value Inspection and statutory intervention records: establish the causes of the 2018 failure and the subsequent reorganisation into two unitary councils`,
      `Liverpool City Council and government intervention records: establish the end of statutory intervention on 9 June 2024 and the subsequent non-statutory improvement arrangements`,
      `Tower Hamlets Best Value Inspection and statutory intervention records: establish the previous 2014-18 intervention, the findings of the 2024 inspection and the strengthened intervention announced in March 2026`,
      `Ministry of Housing, Communities and Local Government, Exceptional Financial Support for 2026/27: lists the councils receiving in-principle capitalisation support and the amounts agreed`,
    ],
    lastChecked: '5 October 2026',
  },
};

export default piece;
