import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'the-revolving-door',
  kicker: 'Political Ethics',
  headline: `Former Ministers Can Lobby Government Again After Two Years. The Rules Are Now Under Review`,
  standfirst: `Former ministers are normally banned from lobbying the government for two years after leaving office. After two years, those restrictions expire. That limit mattered when David Cameron lobbied ministers and officials for Greensill Capital. The Commons Treasury Committee found he had not broken the rules — and directed its criticism at the rules themselves. Five years later, the government is reviewing them again.`,
  publishedAt: '2026-06-11',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `Former ministers are normally banned from lobbying the government for two years after leaving office. They must also seek approval before taking outside work during that period.` },
    { type: 'paragraph', text: `After two years, those restrictions expire.` },
    { type: 'paragraph', text: `That limit mattered when David Cameron lobbied ministers and officials for Greensill Capital. Cameron had left Downing Street in July 2016 and became an adviser to Greensill after the period covered by the Business Appointment Rules had ended.` },
    { type: 'paragraph', text: `The Commons Treasury Committee later found that Cameron or his office made 56 separate contacts with government on Greensill's behalf.` },
    { type: 'paragraph', text: `It concluded that he had not broken the lobbying rules for former ministers. The committee's criticism was instead directed at the rules themselves, saying the case demonstrated their insufficient strength.` },
    { type: 'paragraph', text: `Five years later, the government is reviewing them again.` },
    { type: 'paragraph', text: `On 10 June 2026, Cabinet Office minister Nick Thomas-Symonds confirmed in a parliamentary answer that the new Ethics and Integrity Commission is examining whether the Business Appointment Rules are sufficient to deal with potentially improper access to and influence within government. The review covers ministers and special advisers as well as the wider system governing lobbying, disclosure and access.` },
    { type: 'paragraph', text: `The rules already recognise exactly why the revolving door can create a problem.` },
    { type: 'paragraph', text: `Government guidance says they are intended to prevent suspicions that a minister might make decisions while in office in expectation of a future job, that a new employer could benefit from confidential government information or that a former minister could exploit contacts acquired while in public office.` },
    { type: 'paragraph', text: `Under the current Ministerial Code, former ministers must seek advice from the Independent Adviser on Ministerial Standards before taking any paid or unpaid outside appointment during the two years after leaving government.` },
    { type: 'paragraph', text: `They are generally prohibited during those two years from lobbying ministers, special advisers or officials to influence government decisions, policies, contracts or funding. They must also avoid advising on bids for government contracts or funding.` },
    { type: 'paragraph', text: `Former Cabinet ministers are normally expected to wait at least three months before starting a new appointment. Restrictions can also be placed on dealings with a former department or involvement in particular parts of an employer's business.` },
    { type: 'paragraph', text: `The system was changed substantially in October 2025.` },
    { type: 'paragraph', text: `The Advisory Committee on Business Appointments, known as ACOBA, was abolished and responsibility for former ministers transferred to the Independent Adviser on Ministerial Standards. Responsibility for senior civil servants moved elsewhere, including to the Civil Service Commission.` },
    { type: 'paragraph', text: `The Ministerial Code was also strengthened. A former minister found by the Prime Minister to have seriously breached the Business Appointment Rules is now expected to repay their full ministerial severance payment.` },
    { type: 'paragraph', text: `The new system is not dormant. Sir Laurie Magnus, the Independent Adviser, reported in May that his office had decided 61 applications from former ministers after taking over responsibility for the rules in October. Advice is published when an appointment is announced or taken up.` },
    { type: 'paragraph', text: `The reforms address one longstanding weakness in the old regime: the absence of any meaningful consequence for breaking its rules.` },
    { type: 'paragraph', text: `As recently as December 2024, ACOBA reported former minister Mark Jenkinson to the government after he took up work without first seeking the required advice. Its chair stated plainly that there were no sanctions or consequences available under the system at that time and left any response to ministers.` },
    { type: 'paragraph', text: `That was not a newly discovered weakness.` },
    { type: 'paragraph', text: `A Commons committee said in 2012 that the Business Appointment Rules had no statutory basis and contained no sanctions for non-compliance. Another parliamentary inquiry made the same criticism in 2017.` },
    { type: 'paragraph', text: `After Greensill, Parliament returned to it again.` },
    { type: 'paragraph', text: `The Public Administration and Constitutional Affairs Committee recommended in 2022 that breaches should be capable of legal enforcement. It also supported tighter restrictions where former ministers or senior officials moved into sectors for which they had held significant and direct responsibility.` },
    { type: 'paragraph', text: `The committee specifically highlighted Cameron's case. He had complied with the rules because his involvement with Greensill began after the two-year restriction had expired. MPs argued that this demonstrated a weakness in the scope of the regime rather than misconduct by Cameron under the rules then in force.` },
    { type: 'paragraph', text: `The present rules still use two years as their normal boundary.` },
    { type: 'paragraph', text: `During that period, the Independent Adviser can recommend conditions, waiting periods and restrictions. Former ministers must seek advice and are expected to follow it. A serious breach can now cost a former minister their severance payment.` },
    { type: 'paragraph', text: `But the Business Appointment Rules do not permanently prevent somebody from working in a sector they previously regulated. Nor do they impose a permanent prohibition on contacting government for a subsequent employer.` },
    { type: 'paragraph', text: `Cameron's Greensill lobbying took place outside the restricted period and was therefore permitted by the rules. The Treasury Committee counted 56 contacts and still concluded that he had not broken them.` },
    { type: 'paragraph', text: `That distinction is important because much of the argument about Westminster's revolving door gets reduced to whether an individual politician "broke the rules".` },
    { type: 'paragraph', text: `In some of the most controversial cases, that is the wrong question.` },
    { type: 'paragraph', text: `The rules themselves were designed to manage the risk that knowledge, contacts and influence acquired in public office could later benefit a private employer. Parliament has repeatedly questioned whether those protections are strong enough, and the government has already replaced the body that administered them and introduced a financial consequence for serious breaches.` },
    { type: 'paragraph', text: `As of 11 June 2026, it is now reviewing the substance of the rules as well.` },
    { type: 'paragraph', text: `The unresolved question is not whether former ministers should ever be allowed to work in business. The government's own rules explicitly accept that they should.` },
    { type: 'paragraph', text: `It is whether two years is long enough to prevent the contacts and influence accumulated at the centre of government from becoming a commercial advantage afterwards.` },
  ],
  evidence: {
    recordsReviewed: [
      `Cabinet Office, Business Appointment Rules for Ministers, updated 13 October 2025: sets out the two-year application period, the purpose of the rules and the restrictions that may be imposed on former ministers`,
      `Ministerial Code, current edition: requires former ministers to seek and follow advice for two years after leaving office, provides the general two-year lobbying prohibition, establishes the three-month expected waiting period for former Cabinet ministers and provides for repayment of severance following a serious breach`,
      `Independent Adviser on Ministerial Standards, Annual Report 2025-26, 28 May 2026: records the abolition of ACOBA in October 2025, transfer of responsibility for former ministers to the Independent Adviser and 61 applications decided following the transfer`,
      `Cabinet Office, Written Question 4212, answered 10 June 2026: Nick Thomas-Symonds confirms that the Ethics and Integrity Commission's review covers whether the Business Appointment Rules are sufficient to manage potentially improper access to and influence within government`,
      `Cabinet Office, Ethics and Integrity Commission review, 11 March 2026: records the Prime Minister's commissioning of the wider review into lobbying, disclosure and access to government`,
      `House of Commons Treasury Committee, Lessons from Greensill Capital, 2021: records Cameron's lobbying for Greensill, including 56 contacts with government, and concludes that he did not breach the rules then governing former ministers while finding a strong case for strengthening them`,
      `Public Administration and Constitutional Affairs Committee, Propriety of Governance in Light of Greensill, 2022: examines the revolving-door regime, identifies the expiry of Cameron's two-year restriction and recommends stronger and enforceable Business Appointment Rules`,
      `ACOBA correspondence concerning Mark Jenkinson, 18 December 2024: records a failure to seek advice before taking an appointment and ACOBA's statement that the system then contained no sanctions or consequences for breaches`,
      `House of Commons Public Administration Committee, Business Appointment Rules, 2012, and PACAC, Managing Ministers' and officials' conflicts of interest, 2017: document Parliament's longstanding criticism that the rules lacked statutory enforcement and effective sanctions`,
    ],
    lastChecked: '5 October 2026',
  },
};

export default piece;
