import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'the-invisible-cost-of-keeping-parliament-running',
  kicker: 'Comment',
  headline: 'The Invisible Cost of Keeping Parliament Running',
  standfirst:
    'Parliament publishes everything it spends. That is not the same as making it understandable, and Westminster keeps mistaking publication for transparency.',
  publishedAt: '2026-06-11',
  authorByline: "The People's Chamber",
  body: [
    { type: 'paragraph', text: 'Most people know MPs cost money.' },
    { type: 'paragraph', text: 'What most people do not know is how much.' },
    { type: 'paragraph', text: 'Every Member of Parliament receives a staffing budget of around £177,000 a year. They can claim office expenses. Many claim accommodation costs. Travel between Westminster and their constituency is funded by the taxpayer, with no formal spending cap.' },
    { type: 'paragraph', text: 'None of this is secret.' },
    { type: 'paragraph', text: 'That is the strange part.' },
    { type: 'paragraph', text: 'The information exists. It is published. The rules are available online. Receipts are recorded. Audits take place.' },
    { type: 'paragraph', text: 'Yet ask the average voter how much their MP spends each year and the answer is usually silence.' },
    { type: 'paragraph', text: 'That tells us something important.' },
    { type: 'pullQuote', text: 'Transparency is not simply about making information available. Transparency is about making information understandable.' },
    { type: 'paragraph', text: 'The parliamentary expenses system was rebuilt after the 2009 expenses scandal shattered public trust. MPs were exposed claiming for everything from housing costs to furnishings and personal items. Careers ended. Reputations collapsed. The public reaction was furious because voters felt Parliament had been operating according to rules that ordinary people never knew existed.' },
    { type: 'paragraph', text: 'The system that replaced it is undoubtedly stricter.' },
    { type: 'paragraph', text: 'The question is whether it is genuinely transparent.' },
    { type: 'paragraph', text: 'Take staffing budgets.' },
    { type: 'paragraph', text: 'A typical MP employs several staff members to handle casework, correspondence, research and constituency issues. The work is real. Constituents expect help with benefits, housing, immigration cases, local services and government departments. Most MPs could not perform the role without staff.' },
    { type: 'paragraph', text: 'But how many people know how many staff their MP employs?' },
    { type: 'paragraph', text: 'How much those staff cost?' },
    { type: 'paragraph', text: 'How those costs compare with other MPs?' },
    { type: 'paragraph', text: 'Very few.' },
    { type: 'paragraph', text: 'The same pattern appears elsewhere.' },
    { type: 'paragraph', text: 'Travel is funded.' },
    { type: 'paragraph', text: 'Accommodation is funded.' },
    { type: 'paragraph', text: 'Office costs are funded.' },
    { type: 'paragraph', text: 'Additional support can be provided under exceptional circumstances.' },
    { type: 'paragraph', text: 'Every category has rules. Every category has oversight. Yet the overall picture remains surprisingly difficult for ordinary voters to understand.' },
    { type: 'paragraph', text: 'Parliament often points out that all this information is publicly available.' },
    { type: 'paragraph', text: 'Technically, that is true.' },
    { type: 'paragraph', text: 'So are thousands of pages of government procurement records, local authority accounts and departmental spending reports.' },
    { type: 'pullQuote', text: 'Availability is not the same thing as accessibility.' },
    { type: 'paragraph', text: 'If information can only be understood by journalists, researchers, campaign groups and the small number of citizens willing to spend hours navigating official databases, then transparency exists largely in theory.' },
    { type: 'paragraph', text: 'Most voters have a simple question.' },
    { type: 'paragraph', text: 'How much does my MP cost?' },
    { type: 'paragraph', text: 'The answer should be available in seconds.' },
    { type: 'paragraph', text: 'Instead, understanding the full picture often requires navigating multiple websites, downloading spreadsheets and interpreting categories that mean little to anyone outside Westminster.' },
    { type: 'paragraph', text: 'That is not openness.' },
    { type: 'paragraph', text: 'It is bureaucracy.' },
    { type: 'paragraph', text: 'The deeper issue is trust.' },
    { type: 'paragraph', text: 'The public funds Parliament. Parliament operates on behalf of the public. Yet there remains a significant information gap between those paying the bills and those spending the money. Not because the information is hidden, but because it is buried.' },
    { type: 'paragraph', text: 'This is not a story about corruption.' },
    { type: 'paragraph', text: 'It is a story about visibility.' },
    { type: 'paragraph', text: 'The expenses scandal of 2009 taught Parliament that secrecy destroys trust. The lesson that appears not to have been learned is that complexity can produce much the same result.' },
    { type: 'paragraph', text: 'A transparent system is one that ordinary people can understand without specialist knowledge.' },
    { type: 'paragraph', text: 'Until voters can easily see what their MP spends, how those costs compare and why the money is necessary, Westminster will continue to mistake publication for transparency.' },
    { type: 'paragraph', text: 'They are not the same thing.' },
    { type: 'signature', src: 'https://nwnsvnbudmfkhhwcjwwr.supabase.co/storage/v1/object/public/photos/editorial/signatures/jas.webp', alt: 'Jas' },
  ],
};

export default piece;
