import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'tk4n9mxw7r',
  kicker: 'Trade',
  headline: `Government Steel Tariffs Are Hitting Products Britain Does Not Make`,
  standfirst: `From 1 July, the government cut the tariff-free quota on steel imports by 51 per cent, with out-of-quota imports facing a 50 per cent tariff across 20 product categories. Officials confirmed to the Public Accounts Committee that the classification system used to enforce the measure can group steel products made in Britain with versions that are not, meaning British manufacturers face the tariff on inputs they cannot source domestically. The department told MPs the tariffs would not be reviewed for 12 months despite evidence of unintended impacts.`,
  publishedAt: '2026-09-18',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `The government says its new steel tariffs are designed to protect products that can be made in Britain.` },
    { type: 'paragraph', text: `Its own officials have admitted that is not always what the system does.` },
    { type: 'paragraph', text: `Since 1 July, the tariff-free quota on steel imports covered by the measure has been cut by 51 per cent compared with the previous safeguard arrangement, and imports above quota can face a 50 per cent tariff. The measure covers 20 product categories of steel that can be manufactured domestically. Ministers say it is intended to protect domestic steel production and reduce the pressure from cheap imports.` },
    { type: 'paragraph', text: `But evidence given to the Public Accounts Committee shows that some British manufacturers are being charged the tariff on steel products that are not actually made in the UK.` },
    { type: 'paragraph', text: `The problem is not the principle of protecting domestic steel. It is the machinery used to decide which imports are covered.` },
    { type: 'paragraph', text: `HMRC relies on customs commodity codes. Those codes can group together products with different dimensions and specifications under the same heading.` },
    { type: 'paragraph', text: `That means one code can cover a steel product that Britain does make and another version of the same broad product that it does not.` },
    { type: 'paragraph', text: `Steel pipe is the example the department itself gave the committee. Officials acknowledged that "all diameters and lengths are given the same standard industrial classification code, and that code is the only data that HM Revenue & Customs have to enforce the trade measure. But only some diameters and lengths are made in the UK."` },
    { type: 'paragraph', text: `For a British manufacturer needing one of the versions not made here, the tariff does not protect a domestic supplier.` },
    { type: 'paragraph', text: `There is no domestic supplier to protect.` },
    { type: 'paragraph', text: `It simply makes the imported input more expensive.` },
    { type: 'paragraph', text: `That is the contradiction at the centre of the policy.` },
    { type: 'paragraph', text: `The government's steel strategy itself acknowledges the tension, noting that "downstream users... favoured less intervention and highlighted their business need to secure their supply chains," and that the trade measure "will take into account the impact on supply for downstream sectors."` },
    { type: 'paragraph', text: `In practice, the tariff system can leave those downstream manufacturers paying more for materials they cannot source in Britain.` },
    { type: 'paragraph', text: `The Public Accounts Committee warned that this could push up costs, damage competitiveness and, in some cases, encourage firms to move toward importing finished products rather than manufacturing in the UK, the opposite of the strategy's stated goal.` },
    { type: 'paragraph', text: `It also warned that smaller manufacturers could be hit particularly hard, and that the regime "might put smaller companies out of business."` },
    { type: 'paragraph', text: `Under questioning, officials accepted the risk directly.` },
    { type: 'paragraph', text: `When MPs asked whether the policy could put some smaller firms out of business, the department replied: "I'm afraid that may well be the case."` },
    { type: 'paragraph', text: `That is difficult to square with a policy sold as support for British industry.` },
    { type: 'paragraph', text: `The government does have a defensible reason for acting.` },
    { type: 'paragraph', text: `Global steel markets are distorted by chronic overcapacity: the OECD projects the gap between global steel capacity and demand will reach 721 million tonnes by 2027, 13 per cent more than the current production capacity of every OECD country combined. UK producers have faced high energy costs, with nearly half of businesses surveyed for the steel strategy saying high electricity prices hurt their competitiveness or deterred investment, and intense import competition, while domestic crude steel production has fallen by more than 50 per cent over the past decade, with the domestic share of UK steel demand slipping from a typical 40 to 50 per cent between 2010 and 2020 to just 30 per cent by 2024.` },
    { type: 'paragraph', text: `A tariff regime can be justified if it protects production Britain wants to retain.` },
    { type: 'paragraph', text: `The problem comes when the same tariff catches products Britain does not make.` },
    { type: 'paragraph', text: `At that point, the measure stops protecting domestic production and starts taxing domestic manufacturers.` },
    { type: 'paragraph', text: `The government also knows the classification system is imperfect.` },
    { type: 'paragraph', text: `On 1 October, two non-alloy steel wire commodity codes (72173049 and 72173090) were removed from the measure, taking their tariff rate from 50 per cent to zero.` },
    { type: 'paragraph', text: `That change shows the scope can be adjusted when the categories prove too broad.` },
    { type: 'paragraph', text: `But it was narrow in a telling way: even as the tariff on those two codes was zeroed out, the underlying quota volumes for the wider product category they sit within were left unchanged. The government fixed the rate for two codes without touching the structure that produced the problem in the first place.` },
    { type: 'paragraph', text: `The wider system has not yet been redesigned.` },
    { type: 'paragraph', text: `Officials told the committee that it would not review the tariffs for 12 months, despite industry concerns and what the committee called credible evidence of unintended impacts on UK manufacturers.` },
    { type: 'paragraph', text: `For businesses already paying more, that is a long time to wait.` },
    { type: 'paragraph', text: `The committee has called for a quicker response.` },
    { type: 'paragraph', text: `It wants the government to create a formal route for businesses to raise concerns about the tariff regime, and to develop a more detailed product classification system within six months, setting out how it will monitor and mitigate unintended impacts on UK manufacturers.` },
    { type: 'paragraph', text: `That would deal with the most obvious flaw.` },
    { type: 'paragraph', text: `If a tariff is supposed to protect British production, the government should be able to show that the protected product is actually produced in Britain.` },
    { type: 'paragraph', text: `If it cannot, the policy risks punishing the very manufacturers it says it wants to help, one commodity code at a time, rather than through the systemic fix the committee says is needed.` },
  ],
  evidence: {
    recordsReviewed: [
      'House of Commons Public Accounts Committee, report on British Steel and steel policy — HMRC commodity-code/steel-pipe problem (quoted in full), committee warnings on cost and competitiveness, smaller-firms warning ("might put smaller companies out of business"), full "I\'m afraid that may well be the case" quote, 12-month no-review timeline, two recommendations (formal challenge route; detailed classification system within six months)',
      'GOV.UK, "UK\'s steel trade measure from 1 July 2026" — 51 per cent quota cut, 50 per cent out-of-quota tariff, 20 product categories covered, pre-14 March 2026 contract transitional relief, 1 October removal of commodity codes 72173049 and 72173090 (tariff to 0 per cent, Category 28 quota volumes unchanged)',
      'UK Steel Strategy — downstream-users-versus-producers tension, OECD 721-million-tonne 2027 overcapacity projection, electricity-cost survey findings (approx. 48 per cent/46 per cent of businesses), production decline (more than 50 per cent over a decade; domestic share falling from 40 to 50 per cent in 2010 to 2020 to 30 per cent in 2024)',
    ],
    lastChecked: '18 September 2026',
  },
};

export default piece;
