import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'tn4k7mxw9r',
  kicker: 'Critical Minerals',
  headline: `Government's Cornwall lithium claim raises questions over battery numbers and environmental impact`,
  standfirst: `Ministers say a government-backed expansion in Cornwall will produce enough lithium for more than 180,000 electric-car batteries a year. Earlier government and company figures point to a very different number.`,
  publishedAt: '2026-09-29',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `The government has announced nearly £10 million of support for a Cornwall lithium project it says could supply enough material for more than 180,000 electric-car batteries every year.` },
    { type: 'paragraph', text: `But that claim is difficult to reconcile with figures previously published by the government and by companies involved in the same project.` },
    { type: 'paragraph', text: `Geothermal Engineering Limited, known as GEL, plans to expand lithium production at its United Downs geothermal site near Redruth.` },
    { type: 'paragraph', text: `The government said on 27 September that GEL would invest around £43 million in the facility, supported by an offer in principle of nearly £10 million from its DRIVE35 Automotive Transformation Fund.` },
    { type: 'paragraph', text: `It said the plant would produce around 1,500 tonnes of technical-grade lithium carbonate a year from 2029.` },
    { type: 'paragraph', text: `According to the announcement, that would be enough to supply "more than 180,000 typical EV car batteries".` },
    { type: 'paragraph', text: `The arithmetic means each vehicle would require no more than about 8.3kg of lithium carbonate.` },
    { type: 'paragraph', text: `Previous figures for the same project are markedly different.` },
    { type: 'paragraph', text: `In February, renewable energy investor Thrive Renewables said GEL intended eventually to produce more than 18,000 tonnes of lithium carbonate a year, which it said would be enough for around 250,000 electric-vehicle batteries.` },
    { type: 'paragraph', text: `That calculation allows about 72kg of lithium carbonate for each vehicle.` },
    { type: 'paragraph', text: `The government's own UK Battery Strategy also points to a much higher amount of lithium carbonate per vehicle.` },
    { type: 'paragraph', text: `It described plans by the separate Imerys-British Lithium project in Cornwall to produce 20,800 tonnes of lithium carbonate a year, enough for 500,000 electric vehicles.` },
    { type: 'paragraph', text: `That equates to about 41.6kg per vehicle.` },
    { type: 'paragraph', text: `Using that government's own earlier ratio, 1,500 tonnes would provide enough lithium carbonate for about 36,000 vehicles rather than 180,000.` },
    { type: 'paragraph', text: `The figures are not necessarily directly comparable. Battery chemistry, capacity and assumptions about lithium use can differ between vehicles.` },
    { type: 'paragraph', text: `But the latest government announcement does not explain what battery size or chemistry was used to produce its 180,000 figure.` },
    { type: 'heading', level: 2, text: `Not quite a new mine` },
    { type: 'paragraph', text: `The announcement is headed "New lithium mine in Cornwall".` },
    { type: 'paragraph', text: `United Downs, however, is not a conventional new mine and lithium production at the site has already begun.` },
    { type: 'paragraph', text: `The operation uses a geothermal well more than five kilometres deep. Hot mineral-rich water is brought to the surface, used to generate electricity and processed to recover lithium before the fluid is reinjected underground.` },
    { type: 'paragraph', text: `Thrive Renewables announced in February that United Downs was generating geothermal electricity and had started commercial-scale production of lithium carbonate. It said the production well was more than 5km deep, with water above 190°C containing more than 340 parts per million of lithium.` },
    { type: 'paragraph', text: `The Advanced Propulsion Centre said in August that the plant had capacity to produce around 100 tonnes of technical-grade lithium carbonate a year and that tests showed purity above 99.3 per cent.` },
    { type: 'paragraph', text: `The latest announcement therefore concerns a large expansion of an operating geothermal and lithium facility rather than the opening of a conventional greenfield mine.` },
    { type: 'paragraph', text: `Production is expected to rise from around 100 tonnes to 1,500 tonnes a year.` },
    { type: 'heading', level: 2, text: `Public money already involved` },
    { type: 'paragraph', text: `The latest funding is also not the first public money connected with United Downs.` },
    { type: 'paragraph', text: `A report examining the impact of EU funding in Cornwall described the original geothermal development as industrial-scale research intended to prove whether deep geothermal power could work commercially, backed by £10.6 million from the European Regional Development Fund, £2.4 million from Cornwall Council and £5 million from private investors.` },
    { type: 'paragraph', text: `Those grants funded the geothermal development rather than the present lithium expansion, but the wells and geothermal infrastructure are what now make lithium recovery possible.` },
    { type: 'paragraph', text: `GEL later received another £1.8 million through the Automotive Transformation Fund to help develop its lithium process. The Advanced Propulsion Centre said in August that the grant had supported the project in reaching technical-grade production.` },
    { type: 'paragraph', text: `The latest offer of nearly £10 million remains an offer in principle rather than completed funding.` },
    { type: 'paragraph', text: `Taken together, the history shows that United Downs has been built with a substantial mixture of private and public money over several years.` },
    { type: 'heading', level: 2, text: `The environmental advantage` },
    { type: 'paragraph', text: `There are good reasons to believe lithium recovered from geothermal water could have environmental advantages over conventional mining.` },
    { type: 'paragraph', text: `United Downs does not require a vast open pit.` },
    { type: 'paragraph', text: `Nor does it use the enormous evaporation ponds associated with some conventional brine operations.` },
    { type: 'paragraph', text: `Instead, lithium dissolved in geothermal fluid is recovered after that water has already been brought to the surface as part of the geothermal operation.` },
    { type: 'paragraph', text: `GEL describes the resource as a sustainable domestic supply of lithium. The Advanced Propulsion Centre said in August that recent benchmarking studies had ranked GEL's proprietary production method among the most sustainable in the world because it is coupled with geothermal electricity.` },
    { type: 'paragraph', text: `What is less clear from the public announcements is the environmental cost of expanding production fifteenfold.` },
    { type: 'paragraph', text: `The government's announcement gives figures for investment, jobs, production and batteries.` },
    { type: 'paragraph', text: `It does not state how much freshwater the expanded lithium plant will consume, how much energy the lithium-processing stage will require, what quantities of chemical reagents will be used or how much solid and liquid waste will be produced.` },
    { type: 'paragraph', text: `Nor does the announcement provide a lifecycle carbon figure for each tonne of lithium carbonate produced.` },
    { type: 'paragraph', text: `Those figures matter because lithium extraction and purification involve processing as well as simply bringing geothermal water to the surface.` },
    { type: 'paragraph', text: `The environmental case therefore depends on more than the absence of an open pit.` },
    { type: 'heading', level: 2, text: `Water and underground operations, and a gap in the public record` },
    { type: 'paragraph', text: `United Downs is already subject to environmental regulation connected with its geothermal operations, though the paper trail is not as clean as it might appear.` },
    { type: 'paragraph', text: `An Environment Agency permit application published in October 2025 covered cooling-water and thermal discharge to groundwater of up to 3,456 cubic metres per day at the site. That figure should not be confused with the amount of freshwater consumed by lithium extraction. The application concerned cooling-water and thermal discharge from the geothermal facility, not lithium processing.` },
    { type: 'paragraph', text: `That application was withdrawn on 7 November 2025, before any decision was published, and no successor application covering the water demands of the fifteenfold lithium expansion appears on the public register. Given that even the smaller current operation involved fluid management at a scale of 3,456 cubic metres a day, this leaves an open question as lithium output rises: what will the complete water balance of the expanded operation look like, and under what permit will it run?` },
    { type: 'paragraph', text: `There is also a history of induced seismic activity associated with testing the geothermal wells.` },
    { type: 'paragraph', text: `GEL chief executive Dr Ryan Law told a parliamentary committee that injection testing at United Downs had caused "probably over 1,000 induced seismic events".` },
    { type: 'paragraph', text: `He said he believed one had been felt at the surface and that the project operated a tightly controlled monitoring network.` },
    { type: 'paragraph', text: `That evidence did not suggest the events had caused damage, and Law told MPs that the risk could be managed through monitoring and changes to water flows.` },
    { type: 'paragraph', text: `But any substantial expansion makes continued monitoring relevant to the environmental picture.` },
    { type: 'heading', level: 2, text: `A promising project, but unanswered questions` },
    { type: 'paragraph', text: `Britain has a clear strategic interest in developing domestic lithium production.` },
    { type: 'paragraph', text: `Lithium is an important raw material for battery manufacturing, and successful commercial production in Cornwall could give the UK a larger domestic supply.` },
    { type: 'paragraph', text: `United Downs may also prove substantially less environmentally damaging than many conventional lithium sources.` },
    { type: 'paragraph', text: `None of that removes the need for scrutiny when public money is involved.` },
    { type: 'paragraph', text: `The most immediate question is basic.` },
    { type: 'paragraph', text: `How can 1,500 tonnes of lithium carbonate supply more than 180,000 electric vehicles when previous figures for the same company, and the government's own Battery Strategy, imply several times more lithium carbonate is required per vehicle?` },
    { type: 'paragraph', text: `There are environmental questions too.` },
    { type: 'paragraph', text: `Before production rises from around 100 tonnes to 1,500 tonnes a year, GEL and the government should be able to publish the water, chemical, energy, waste and lifecycle-carbon figures that underpin claims that the process is sustainable, and clarify which permit, if any, will govern the expanded plant's discharge, given the last public application on record was withdrawn.` },
    { type: 'paragraph', text: `The technology may prove to be exactly the sort of domestic industry Britain wants.` },
    { type: 'paragraph', text: `But £43 million investments and government grants should be judged on measurable numbers, not simply the promises attached to them.` },
  ],
  evidence: {
    recordsReviewed: [
      'Department for Business, Innovation, Science and Trade, 27 September 2026: "New lithium mine in Cornwall to unlock Britain\'s industrial potential and support skilled jobs"',
      'Thrive Renewables, 26 February 2026: "UK generates first ever geothermal electricity at United Downs"',
      'Department for Business and Trade, UK Battery Strategy, December 2023',
      'Advanced Propulsion Centre case study, August 2026: "GEL Geothermal: Europe\'s first \'technical grade\' lithium carbonate on a commercial scale"',
      'Cornwall and Isles of Scilly Growth Programme: "United Downs Geothermal Project"',
      'Law, R. et al., Stanford Geothermal Workshop, 2019: "The United Downs Deep Geothermal Power Project"',
      'Environment Agency permit application EPR/YP3724LV/A001, published 6 October 2025, withdrawn 7 November 2025',
      'House of Commons Environmental Audit Committee, oral evidence from GEL chief executive Dr Ryan Law',
    ],
    lastChecked: '29 September 2026',
  },
};

export default piece;
