import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'vb8k4mxn9r',
  kicker: 'Energy & Infrastructure',
  headline: `Britain Is Spending Billions on the Grid. Now the Government Wants the State to Take a Share`,
  standfirst: `The government has created Great British Grid to invest public money in electricity transmission networks alongside private companies. Its parent, Great British Energy, spent £14.2 million establishing itself and holds £5.8 million in direct investments. Before further billions are committed under the GBE brand, the accounts and the political announcements are measuring different things.`,
  publishedAt: '2026-09-30',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `The government has created another publicly owned energy body.` },
    { type: 'paragraph', text: `Great British Grid will sit inside Great British Energy and invest public money directly in the electricity networks that carry power around Britain.` },
    { type: 'paragraph', text: `Ministers say it will speed up connections, increase competition and eventually help cut bills.` },
    { type: 'paragraph', text: `But the announcement leaves some of the most important questions unanswered.` },
    { type: 'paragraph', text: `The government has not published a long-term budget for Great British Grid, identified its first investment or calculated how much its intervention will save households.` },
    { type: 'paragraph', text: `And the organisation that will house it, Great British Energy, is itself still at a remarkably early stage.` },
    { type: 'paragraph', text: `Its first audited accounts show operating expenses of £14.2 million and just £5.8 million of financial investments at 31 March 2026.` },
    { type: 'paragraph', text: `Yet Great British Energy and its separate nuclear counterpart have been allocated more than £8.3 billion over the current Spending Review period, running to 2029-30.` },
    { type: 'paragraph', text: `GB Grid now adds another responsibility to an organisation that is still trying to turn that political promise into actual assets.` },
    { type: 'heading', level: 2, text: `A state competitor enters the grid` },
    { type: 'paragraph', text: `Britain's electricity transmission network is largely operated through regulated private businesses.` },
    { type: 'paragraph', text: `National Grid Electricity Transmission controls the high-voltage network in England and Wales, while ScottishPower Transmission and Scottish and Southern Electricity Networks Transmission operate the networks in Scotland.` },
    { type: 'paragraph', text: `Great British Grid will not nationalise those companies.` },
    { type: 'paragraph', text: `Nor will it replace the National Energy System Operator, which plans and operates the wider electricity system.` },
    { type: 'paragraph', text: `Instead, the government intends GB Grid to invest alongside private companies and compete for future network projects.` },
    { type: 'paragraph', text: `The government says this will increase public ownership of electricity infrastructure while introducing greater competition into a market historically dominated by regional monopolies.` },
    { type: 'paragraph', text: `That could become significant.` },
    { type: 'paragraph', text: `Ofgem is developing a regime, known as competitively appointed transmission ownership, under which some new transmission projects can be tendered rather than automatically delivered by the existing network owner.` },
    { type: 'paragraph', text: `GB Grid could eventually find itself bidding against private companies to finance, build and operate electricity infrastructure.` },
    { type: 'paragraph', text: `That would create something Britain has not previously had on any meaningful scale: a publicly owned competitor inside the regulated transmission market.` },
    { type: 'heading', level: 2, text: `The £70 billion build-out` },
    { type: 'paragraph', text: `The scale of what is coming dwarfs Great British Grid itself.` },
    { type: 'paragraph', text: `Britain needs to expand the electricity network rapidly as power generation becomes more dispersed and electricity demand increases.` },
    { type: 'paragraph', text: `Ofgem estimates that up to £70 billion of transmission investment may be required between 1 April 2025 and 31 March 2031, in 2023-24 prices — roughly a quadrupling of the current rate of spending, from about £2.5 billion a year now to more than £11 billion a year between 2027-28 and 2030-31.` },
    { type: 'paragraph', text: `That money will ultimately pay for new lines, substations and other infrastructure required to connect renewable generation, businesses, homes and new sources of demand.` },
    { type: 'paragraph', text: `GB Grid will therefore enter a market in which tens of billions of pounds are likely to be invested.` },
    { type: 'paragraph', text: `But the government has not yet said what proportion of that investment it expects the public company to undertake.` },
    { type: 'paragraph', text: `The 29 September announcement says its initial costs will be met from existing Great British Energy budgets.` },
    { type: 'paragraph', text: `Its longer-term funding will be decided at a future Spending Review.` },
    { type: 'paragraph', text: `That means the government has established the institution before determining how much capital it will ultimately control.` },
    { type: 'heading', level: 2, text: `The promise to cut bills needs qualification` },
    { type: 'paragraph', text: `The government headline says Great British Grid will "speed up connections and cut bills".` },
    { type: 'paragraph', text: `There is a reasonable economic argument behind that claim.` },
    { type: 'paragraph', text: `Britain already incurs substantial costs when electricity is generated in places where the transmission network cannot carry enough of it to consumers.` },
    { type: 'paragraph', text: `Generators can be paid to reduce output in one part of the country while other generators are paid to produce more elsewhere.` },
    { type: 'paragraph', text: `Expanding the network can reduce those constraint costs.` },
    { type: 'paragraph', text: `But building the network is not free.` },
    { type: 'paragraph', text: `Consumers also pay for transmission investment through network charges included in energy bills.` },
    { type: 'paragraph', text: `The question is therefore not simply whether building more grid infrastructure costs money.` },
    { type: 'paragraph', text: `It plainly does.` },
    { type: 'paragraph', text: `The relevant question is whether the cost of expanding the network is lower than the combination of constraint payments, delayed projects, imported energy exposure and economic activity lost because connections cannot be obtained.` },
    { type: 'paragraph', text: `The government has not published a specific estimate showing how much Great British Grid itself will reduce a household's bill.` },
    { type: 'heading', level: 2, text: `More than 300GW removed from the queue` },
    { type: 'paragraph', text: `Another striking number in the announcement is the government's claim that it is removing more than 300GW of speculative capacity from Britain's grid connection queue.` },
    { type: 'paragraph', text: `That figure requires context.` },
    { type: 'paragraph', text: `The old connections system allowed projects to enter the queue long before some had realistic prospects of being built.` },
    { type: 'paragraph', text: `The queue eventually exceeded the amount of generating capacity Britain was likely to need several times over.` },
    { type: 'paragraph', text: `More mature developments could therefore find themselves sitting behind speculative schemes.` },
    { type: 'paragraph', text: `Removing hundreds of gigawatts of speculative applications may improve the system.` },
    { type: 'paragraph', text: `But it does not mean 300GW of new network capacity has been created.` },
    { type: 'paragraph', text: `Nor was Great British Grid responsible for most of that work.` },
    { type: 'paragraph', text: `The connections reforms were already under way before GB Grid was announced.` },
    { type: 'heading', level: 2, text: `Businesses may be allowed to build their own connections` },
    { type: 'paragraph', text: `A less politically dramatic part of the announcement could have a more immediate effect.` },
    { type: 'paragraph', text: `The government wants to expand the circumstances in which businesses and developers can build their own connection infrastructure rather than waiting for network companies to do it.` },
    { type: 'paragraph', text: `For a factory, data centre, battery project or renewable generator facing years in a connection queue, that could matter considerably more than the ownership structure of the transmission system.` },
    { type: 'paragraph', text: `The government says similar reforms in Ireland have cut connection times by up to 11 months.` },
    { type: 'paragraph', text: `The policy therefore contains two separate ideas which should not be confused.` },
    { type: 'paragraph', text: `One is the creation of a publicly owned grid investor.` },
    { type: 'paragraph', text: `The other is loosening the existing network companies' control over the construction of connections.` },
    { type: 'heading', level: 2, text: `Great British Energy was supposed to be the public energy champion` },
    { type: 'paragraph', text: `GB Grid will be housed inside Great British Energy, the publicly owned company incorporated on 10 October 2024 and given statutory footing when the Great British Energy Act received Royal Assent on 15 May 2025.` },
    { type: 'paragraph', text: `Its ambitions are substantial.` },
    { type: 'paragraph', text: `Its strategic plan says that by 2030 it intends to hold a portfolio of at least 15GW of generation and storage capacity, mobilise £15 billion of private finance, support more than 1,000 local and community energy projects and directly support at least 10,000 jobs.` },
    { type: 'paragraph', text: `It also intends eventually to generate income from the energy assets owned by the public: the plan says GBE will "own and operate assets while using investments to catalyse growth," with returns "reinvested back into more capacity, more jobs, and more opportunity."` },
    { type: 'paragraph', text: `The company says it will operate commercially and reinvest returns into further energy projects, and expects its portfolio to be generating income by 2030, on a path to company-wide profitability.` },
    { type: 'paragraph', text: `But its first set of accounts shows how far it still has to travel.` },
    { type: 'heading', level: 2, text: `£14 million spent running Great British Energy` },
    { type: 'paragraph', text: `Great British Energy's first annual report covers the period from its incorporation on 10 October 2024 to 31 March 2026.` },
    { type: 'paragraph', text: `During that period it recorded £7.9 million of staff costs and £6.3 million of other operating expenses — of which £3.8 million was professional services: legal, advisory and other specialist support.` },
    { type: 'paragraph', text: `Total operating expenditure was £14.2 million.` },
    { type: 'paragraph', text: `Income was just £62,000, producing an accounting loss of £14.1 million.` },
    { type: 'paragraph', text: `That does not mean Great British Energy has lost £14 million on failed energy projects.` },
    { type: 'paragraph', text: `Most of the period covered its establishment.` },
    { type: 'paragraph', text: `The organisation was recruiting staff, creating investment systems and setting itself up as a functioning public company — it had no directly employed staff of its own during this period, relying instead on a workforce of 121 made up of DESNZ employees, loaned civil servants, secondees and contractors.` },
    { type: 'paragraph', text: `But it provides a useful benchmark against which future delivery can be measured.` },
    { type: 'paragraph', text: `The company's published accounts show that at 31 March its direct financial investment portfolio stood at only around £5.8 million.` },
    { type: 'paragraph', text: `Great British Energy had therefore spent considerably more establishing and operating itself during its first reporting period than it held in direct financial investments at the year end.` },
    { type: 'paragraph', text: `There is another complication.` },
    { type: 'paragraph', text: `The accounts do not contain every cost associated with creating GBE.` },
    { type: 'paragraph', text: `Costs incurred between the company's incorporation on 10 October 2024 and the Great British Energy Act receiving Royal Assent on 15 May 2025 were retained by the Department for Energy Security and Net Zero rather than appearing in GBE's own accounts.` },
    { type: 'paragraph', text: `The £14.2 million figure therefore should not automatically be treated as the complete taxpayer cost of establishing Great British Energy.` },
    { type: 'heading', level: 2, text: `The £8.3 billion headline is not £8.3 billion already spent` },
    { type: 'paragraph', text: `The 2025 Spending Review allocated more than £8.3 billion in capital funding across Great British Energy and Great British Energy-Nuclear over the spending review period to 2029-30.` },
    { type: 'paragraph', text: `That number is regularly associated with Great British Energy.` },
    { type: 'paragraph', text: `But it does not represent £8.3 billion already transferred into energy projects.` },
    { type: 'paragraph', text: `Nor does all of it belong to the main Great British Energy company.` },
    { type: 'paragraph', text: `Great British Energy-Nuclear is a separate publicly owned company responsible for nuclear programmes.` },
    { type: 'paragraph', text: `The remainder includes future investment programmes, grants and commitments extending over several years.` },
    { type: 'paragraph', text: `GBE's own strategic plan acknowledges that these are programmes it intends to build out towards 2030 rather than an existing £8.3 billion portfolio of publicly owned energy assets.` },
    { type: 'heading', level: 2, text: `£255 million of solar, but not £255 million on GBE's balance sheet` },
    { type: 'paragraph', text: `Great British Energy has nevertheless delivered tangible projects.` },
    { type: 'paragraph', text: `Government says £255 million has been invested in rooftop solar covering 250 schools and 260 NHS and military sites.` },
    { type: 'paragraph', text: `Those schemes matter because they can reduce the amount public bodies spend buying electricity from the grid.` },
    { type: 'paragraph', text: `But the accounting is important.` },
    { type: 'paragraph', text: `Much of that £255 million programme was delivered through DESNZ rather than appearing as £255 million of assets owned directly by Great British Energy.` },
    { type: 'paragraph', text: `The distinction gets blurred in political announcements.` },
    { type: 'paragraph', text: `Money can be described as a "Great British Energy investment" while actually representing a government grant programme delivered under the GBE banner.` },
    { type: 'paragraph', text: `That is different from Great British Energy buying an asset from which taxpayers receive a commercial return.` },
    { type: 'paragraph', text: `Both can be legitimate uses of public money.` },
    { type: 'paragraph', text: `They should not be counted as though they were the same thing.` },
    { type: 'heading', level: 2, text: `The direct portfolio is beginning to grow` },
    { type: 'paragraph', text: `GBE's ambitions are increasingly commercial.` },
    { type: 'paragraph', text: `Its strategic plan says it intends to become an energy developer that owns and operates assets, rather than simply distributing government funding.` },
    { type: 'paragraph', text: `It wants public investment to attract private finance and says returns from publicly owned assets will be reinvested.` },
    { type: 'paragraph', text: `Its target is to mobilise £15 billion of private finance from commitments made before 2030 and build a portfolio producing income by then.` },
    { type: 'paragraph', text: `The company has begun making direct investments in individual businesses and projects — its first, in Highland Wind Limited, is the £5.8 million holding recorded in its accounts.` },
    { type: 'paragraph', text: `That means future accounts should make it possible to measure whether GBE is genuinely building a valuable public energy portfolio rather than functioning mainly as another channel for government grants.` },
    { type: 'paragraph', text: `The distinction will become even more important as GB Grid begins investing in transmission infrastructure.` },
    { type: 'heading', level: 2, text: `What exactly will the taxpayer own?` },
    { type: 'paragraph', text: `That is the central unanswered question behind Great British Grid.` },
    { type: 'paragraph', text: `When GB Grid invests in a transmission project, will it own the resulting asset?` },
    { type: 'paragraph', text: `If so, what proportion?` },
    { type: 'paragraph', text: `Will it receive regulated revenues from electricity consumers in the same way private transmission owners do?` },
    { type: 'paragraph', text: `What return will the government require on its capital?` },
    { type: 'paragraph', text: `Will profits be retained by Great British Energy?` },
    { type: 'paragraph', text: `Will the company borrow independently?` },
    { type: 'paragraph', text: `Will Treasury guarantees support that borrowing?` },
    { type: 'paragraph', text: `And if a project overruns its budget, who carries the risk?` },
    { type: 'paragraph', text: `None of those questions is answered in detail by the launch announcement.` },
    { type: 'paragraph', text: `They matter because public ownership does not automatically make an infrastructure project cheaper.` },
    { type: 'paragraph', text: `Its financial advantage depends partly on the price at which the state can raise capital, the return it demands, the efficiency with which projects are delivered and where financial risk ultimately sits.` },
    { type: 'heading', level: 2, text: `An experiment in public versus private capital` },
    { type: 'paragraph', text: `That may eventually become GB Grid's most interesting feature.` },
    { type: 'paragraph', text: `Private electricity networks receive regulated returns because investors must be persuaded to provide billions of pounds of capital.` },
    { type: 'paragraph', text: `A publicly owned competitor may have a different cost of capital and does not have private shareholders requiring dividends.` },
    { type: 'paragraph', text: `If GB Grid can finance and deliver comparable infrastructure more cheaply while retaining returns for the public, it would provide evidence for expanding public investment.` },
    { type: 'paragraph', text: `If its costs are similar or higher, the argument becomes weaker.` },
    { type: 'paragraph', text: `For the first time, the two models could potentially operate alongside each other on comparable projects.` },
    { type: 'paragraph', text: `That is considerably more informative than political arguments about public and private ownership in the abstract.` },
    { type: 'heading', level: 2, text: `Great British Energy now has another job` },
    { type: 'paragraph', text: `This is where the timing deserves scrutiny.` },
    { type: 'paragraph', text: `Great British Energy was created to invest in renewable generation, energy storage, local energy schemes, supply chains and new technology.` },
    { type: 'paragraph', text: `Its first audited accounts show a company still establishing itself.` },
    { type: 'paragraph', text: `At 31 March 2026 it had incurred £14.2 million of operating expenses and held £5.8 million of direct financial investments.` },
    { type: 'paragraph', text: `Its much larger £8.3 billion headline funding commitment is shared with the separate nuclear company and stretches across the spending review period to 2029-30.` },
    { type: 'paragraph', text: `Its £255 million public-sector solar programme represents genuine delivery, but much of that spending has been channelled through DESNZ rather than appearing as commercially owned GBE assets.` },
    { type: 'paragraph', text: `Its own strategic plan does not expect the investment portfolio to be generating income until 2030.` },
    { type: 'paragraph', text: `Now Great British Grid is being placed inside it and potentially given a role in one of Britain's largest infrastructure programmes.` },
    { type: 'paragraph', text: `That raises a simple accountability question.` },
    { type: 'paragraph', text: `Before further billions are committed under the Great British Energy name, it should be possible to establish clearly how much public money has actually been spent, what assets taxpayers now own, what income those assets have generated and how much private investment has genuinely been attracted alongside them.` },
    { type: 'heading', level: 2, text: `The numbers need separating` },
    { type: 'paragraph', text: `The problem is not necessarily that Great British Energy has spent too much or achieved too little.` },
    { type: 'paragraph', text: `It is that several different types of money are routinely presented beneath the same brand.` },
    { type: 'paragraph', text: `There is money used to operate Great British Energy itself.` },
    { type: 'paragraph', text: `There are government grants delivered under its banner.` },
    { type: 'paragraph', text: `There are direct commercial investments owned by GBE.` },
    { type: 'paragraph', text: `There are co-investments with private companies.` },
    { type: 'paragraph', text: `There are future funding envelopes that have been announced but not yet spent.` },
    { type: 'paragraph', text: `And there is the separate Great British Energy-Nuclear company.` },
    { type: 'paragraph', text: `Adding those numbers together can create the impression of a vast existing public energy portfolio.` },
    { type: 'paragraph', text: `The accounts show something more embryonic.` },
    { type: 'paragraph', text: `That does not mean Great British Energy will fail.` },
    { type: 'paragraph', text: `It means its success still has to be demonstrated.` },
    { type: 'paragraph', text: `Great British Grid now provides another test.` },
    { type: 'paragraph', text: `Britain needs enormous amounts of electricity infrastructure regardless of who owns it.` },
    { type: 'paragraph', text: `Consumers will ultimately pay for much of it.` },
    { type: 'paragraph', text: `If the government believes public investment can deliver that infrastructure more cheaply, Great British Grid could establish that through actual projects and actual returns.` },
    { type: 'paragraph', text: `But ministers have so far announced the company without publishing its long-term budget, its first project, its expected rate of return or the savings it expects to deliver.` },
    { type: 'paragraph', text: `Great British Energy was created on the promise that the public should own a greater share of the infrastructure it pays for.` },
    { type: 'paragraph', text: `As billions begin to move, the simplest measure of that promise may also be the most important:` },
    { type: 'paragraph', text: `what did the public spend, what does the public now own, and what is it worth?` },
  ],
  evidence: {
    recordsReviewed: [
      'GOV.UK, 14 September 2026: "Great British Energy annual report and accounts 2025 to 2026" — source for incorporation date, Royal Assent date, pre-Royal Assent costs retained by DESNZ, operating expenditure (£14.2m), staff costs (£7.9m), other opex (£6.3m incl. £3.8m professional services), income (£62,000), accounting loss (£14.1m), £5.8m Highland Wind Limited investment, 121-person workforce',
      'Great British Energy Strategic Plan 2025 — 2030 targets: 15GW capacity, £15bn private finance, 1,000+ community projects, 10,000+ jobs; commitment to own/operate assets and reinvest returns',
      'DESNZ Annual Report and Accounts 2025-26 — source for £8.3bn combined GBE/GBE-Nuclear capital allocation to 2029-30 and £255m rooftop solar programme (250 schools, 260 NHS/military sites)',
      'GOV.UK, 29 September 2026: "Great British Grid to speed up connections and cut bills" — GB Grid announcement, initial costs from existing GBE budgets, 300GW queue removal, Ireland self-build comparison',
      'National Audit Office, September 2026: "Upgrading the electricity transmission network" — Ofgem £70bn transmission investment estimate (2025-31, 2023-24 prices) and ramp-up from ~£2.5bn/year to £11bn/year',
    ],
    lastChecked: '30 September 2026',
  },
};

export default piece;
