import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'vk4n9mxw7r',
  kicker: 'Industry',
  headline: `British Steel Is Costing Taxpayers £1.3m a Day. Government Still Has No Costed Plan to Make It Viable`,
  standfirst: `British Steel is costing the government about £1.3 million a day to keep operating. The National Audit Office describes the intervention as having "no set budget, repayment schedule, or end date." By the end of June 2026 the government had spent £555 million in working capital on the company, with the NAO warning costs could exceed £1.5 billion by 2028 before any major transformation or exit from public ownership.`,
  publishedAt: '2026-09-18',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `British Steel is costing the government about £1.3 million a day to keep operating, in an intervention the National Audit Office itself describes as having "no set budget, repayment schedule, or end date."` },
    { type: 'paragraph', text: `The intervention prevented an immediate collapse at Scunthorpe and preserved the UK's remaining primary steelmaking capacity. That was the immediate justification, and the Public Accounts Committee accepts it.` },
    { type: 'paragraph', text: `The harder question is what happens after the emergency.` },
    { type: 'paragraph', text: `Spending has climbed steadily since the intervention began. In its first nine months, from 12 April 2025 to 31 January 2026, the Department for Business and Trade spent £377 million: £15 million on advisers and £359 million directly on British Steel's operating costs. By June, that had risen to £555 million in working capital, with projected spending reaching £642 million by the end of that month, including advisers. The Public Accounts Committee says the department still could not provide even an indicative estimate of the eventual bill.` },
    { type: 'paragraph', text: `The National Audit Office has warned that, if support continues at roughly the same rate, the cost could exceed £1.5 billion by 2028.` },
    { type: 'paragraph', text: `That is before any major transformation of the plant, compensation to the previous owner or the eventual cost of exiting public ownership.` },
    { type: 'paragraph', text: `This is not yet a costed industrial strategy.` },
    { type: 'paragraph', text: `It is an open-ended rescue, and the government's own auditor describes it in those terms: no budget ceiling has been set, no repayment schedule exists, and no end date has been fixed.` },
    { type: 'paragraph', text: `The government had a defensible reason to intervene. Closing the blast furnaces abruptly would have threatened thousands of jobs, domestic steelmaking capacity and supply chains linked to infrastructure, rail and defence.` },
    { type: 'paragraph', text: `But preserving the company for long enough to decide what to do with it is not the same as making it sustainable.` },
    { type: 'paragraph', text: `The department told MPs that British Steel remains structurally unprofitable in its current form.` },
    { type: 'paragraph', text: `It has not settled the future production model.` },
    { type: 'paragraph', text: `It has not agreed the decarbonisation route.` },
    { type: 'paragraph', text: `And it has not set out how the business will become commercially viable.` },
    { type: 'paragraph', text: `Production has also been weaker than planned.` },
    { type: 'paragraph', text: `The committee says actual production at Scunthorpe has been considerably lower than capacity throughout the intervention, driven by outages and by health and safety concerns arising because the previous owner had not maintained the plant properly.` },
    { type: 'paragraph', text: `That matters because the public money currently going into the company is not simply paying for a defined modernisation programme.` },
    { type: 'paragraph', text: `A substantial part is keeping day-to-day operations going while the government decides what the modernisation programme should be.` },
    { type: 'paragraph', text: `The support is technically classed as debt to the Crown.` },
    { type: 'paragraph', text: `But there is no formal loan agreement, and the committee says it is not clear whether the money will ever be recovered.` },
    { type: 'paragraph', text: `That makes the label less reassuring than it sounds.` },
    { type: 'paragraph', text: `If the business cannot repay the support, taxpayers carry the loss.` },
    { type: 'paragraph', text: `The cost is also beginning to affect other departmental priorities.` },
    { type: 'paragraph', text: `The Department for Business and Trade used £95 million of underspending from other projects to help finance British Steel.` },
    { type: 'paragraph', text: `The National Audit Office had already warned that no dedicated budget for the rescue had been agreed at the Spending Review, meaning money might have to be found from elsewhere in the department.` },
    { type: 'paragraph', text: `That creates a second public-interest problem.` },
    { type: 'paragraph', text: `The government has said up to £2.5 billion is available to support and modernise the wider UK steel sector.` },
    { type: 'paragraph', text: `But when questioned by MPs, the department could not give a precise figure for how much of that remains once British Steel is taken into account, saying only that "much of this would be spent on the Scunthorpe site."` },
    { type: 'paragraph', text: `One company could therefore absorb a large share of a fund presented as support for the whole industry.` },
    { type: 'paragraph', text: `The wider steel strategy has a similar gap between ambition and measurement.` },
    { type: 'paragraph', text: `Government wants domestic producers to supply 40 to 50 per cent of UK steel demand, up from around 30 per cent in 2024.` },
    { type: 'paragraph', text: `That is framed in the strategy itself as a return to "recently sustained levels": domestic production ran at 40 to 50 per cent of UK demand as recently as 2010 to 2020, before falling away to 30 per cent by 2024, alongside a crude steel production decline of more than 50 per cent over the past decade. It is a recovery target, not an untested reach, which strengthens the underlying case for the policy even as it leaves the execution gap unresolved.` },
    { type: 'paragraph', text: `But the Public Accounts Committee found no deadline for reaching that target and no tonnage figure showing what success actually means.` },
    { type: 'paragraph', text: `That is important because demand itself will change.` },
    { type: 'paragraph', text: `A percentage target without a date or a tonnage target can move considerably depending on how much steel Britain consumes.` },
    { type: 'paragraph', text: `The rationale behind the policy is stronger than the detail.` },
    { type: 'paragraph', text: `Government argues that domestic capacity matters for national security, defence and critical infrastructure, including rail, telecommunications and energy, and for resilience against global steel overcapacity, which the OECD projects could reach 721 million tonnes by 2027.` },
    { type: 'paragraph', text: `That case is not difficult to understand.` },
    { type: 'paragraph', text: `The problem is that ministers have not yet shown how much taxpayers must spend to preserve that capacity, or what they will own at the end of it.` },
    { type: 'paragraph', text: `There is still no agreed route from £1.3 million a day of public support, running without a budget ceiling or an end date, to a business that can stand on its own.` },
    { type: 'paragraph', text: `The Public Accounts Committee says the department took this action without being able to conclude on value for money, and still cannot demonstrate how it will achieve it.` },
    { type: 'paragraph', text: `That is the test that now matters.` },
    { type: 'paragraph', text: `Not whether intervention bought time.` },
    { type: 'paragraph', text: `It did.` },
    { type: 'paragraph', text: `The test is what government does with that time.` },
    { type: 'paragraph', text: `If British Steel is modernised, becomes commercially sustainable and protects strategically important production, the cost may prove defensible, and the strategy's own framing, as a return to a level of domestic production Britain sustained for a decade before 2020, gives that case more grounding than a blank-sheet target would.` },
    { type: 'paragraph', text: `If public money keeps flowing while the end-state remains undefined, the rescue becomes something else.` },
    { type: 'paragraph', text: `An industrial policy without a destination.` },
  ],
  evidence: {
    recordsReviewed: [
      'House of Commons Public Accounts Committee, report on British Steel, 18 September 2026 — £555m working capital and £642m projected spend by 30 June 2026, department\'s inability to give indicative eventual cost, production shortfall and its causes, debt classification with no formal loan agreement and unclear repayment prospects, £95m underspend redirection, inability to say how much of the £2.5bn wider fund remains, 40 to 50 per cent / 30 per cent target with no deadline or tonnage figure, "bought time rather than providing a solution" / no value-for-money conclusion',
      'National Audit Office, "Government spends £377 million in 9 months to keep British Steel\'s Scunthorpe site operating" — £377m spent between 12 April 2025 and 31 January 2026 (£15m advisers, £359m operating costs), £615m further projection to June 2026, £1.5bn-by-2028 warning, £1.3 million daily operating cost, "no set budget, repayment schedule, or end date" characterisation',
      'UK Steel Strategy — more-than-50-per-cent-in-a-decade crude steel production decline, framing of the 40 to 50 per cent target as a return to levels sustained 2010 to 2020, OECD projected 721 million tonnes of global steel overcapacity by 2027',
    ],
    lastChecked: '18 September 2026',
  },
};

export default piece;
