import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'vq8k3mxw7n',
  kicker: 'Public Money',
  headline: `Government Says British Steel Is Worth Nothing. Taxpayer Support Has Already Reached £555m`,
  standfirst: `British Steel passed into public ownership on 16 July. In the same statement announcing the nationalisation, the government said its view was that the company's current commercial value was nil. By 18 June, the government had provided British Steel with about £555 million of working capital. The government has now committed itself to further spending without publishing an estimate of the eventual bill.`,
  publishedAt: '2026-07-16',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `British Steel passed into public ownership on 16 July.` },
    { type: 'paragraph', text: `In the same statement announcing the nationalisation, the government said its view was that the company's current commercial value was nil because of its history of losses and poor financial position. An independent valuer will now decide whether its former owner, Jingye, is nevertheless entitled to compensation.` },
    { type: 'paragraph', text: `The price of keeping the business running is a separate matter.` },
    { type: 'paragraph', text: `By 18 June, the government had provided British Steel with about £555 million of working capital, paying for costs including raw materials and wages. The Department for Business and Trade had also spent £15 million on advisers by the end of January. No final figure covering the period up to nationalisation has yet been published.` },
    { type: 'paragraph', text: `The government has now committed itself to further spending without publishing an estimate of the eventual bill.` },
    { type: 'paragraph', text: `That does not make nationalisation irrational. British Steel employs more than 4,000 permanent staff across its operations and runs the last working blast furnaces in Britain. Scunthorpe is the country's remaining source of primary steel made from iron ore and coke. British Steel is also the UK's only rail producer and supplies about 80 per cent of Network Rail's rail requirements under a five-year contract worth £500 million.` },
    { type: 'paragraph', text: `Ministers concluded that allowing the company to fail could disrupt the rail network, major infrastructure projects and other industrial supply chains. Their assessment was that nationalisation had become the only viable route for retaining that capability.` },
    { type: 'paragraph', text: `The jobs argument is also substantial, although the numbers need care.` },
    { type: 'paragraph', text: `The government's intervention in April 2025 led British Steel to withdraw a redundancy consultation that had put 2,700 jobs at immediate risk. That does not mean nationalisation has permanently secured 2,700 jobs. The company had 4,052 permanent employees at the end of January 2026, and its future workforce will depend on whatever restructuring follows.` },
    { type: 'paragraph', text: `A government unit previously modelled a "reasonable worst case" in which closure could result in as many as 10,000 job losses, including about 3,000 at Scunthorpe and further losses in the supply chain, with up to £802 million of economic output lost over five years. Those were modelled consequences of closure, not observed losses that can now be counted as jobs saved.` },
    { type: 'paragraph', text: `The financial problem was apparent before ministers intervened.` },
    { type: 'paragraph', text: `Jingye told the government in July 2024 that British Steel's position was unsustainable. On 24 March 2025, the Department for Business and Trade offered £500 million towards continued production and conversion of Scunthorpe to electric arc furnaces. Jingye rejected the offer the next day, saying the conditions were too onerous and the amount was lower than it had expected. It said British Steel was losing about £700,000 a day and intended to close the blast furnaces as early as June.` },
    { type: 'paragraph', text: `Officials initially advised ministers not to stop it.` },
    { type: 'paragraph', text: `Advice given on 28 March said there was "no affordable solution to maintain steel-making at Scunthorpe" and cited substantial delivery and value-for-money risks. On the information available then, officials recommended concentrating on mitigating the consequences of closure and supporting steelmaking elsewhere.` },
    { type: 'paragraph', text: `Within days, the situation changed. Raw-material orders were being cancelled or diverted, leaving the blast furnaces at risk of running out of essential supplies. Officials concluded that an uncontrolled shutdown was imminent and could be extremely difficult and expensive to reverse.` },
    { type: 'paragraph', text: `Parliament was recalled on 12 April 2025 and passed emergency legislation allowing ministers to direct British Steel's operations.` },
    { type: 'paragraph', text: `The decision was made so quickly that the department's Accounting Officer did not have time to complete assessments of either value for money or feasibility. Business Secretary Jonathan Reynolds issued a ministerial direction allowing the intervention to proceed because ministers considered keeping the furnaces running to be in the public interest.` },
    { type: 'paragraph', text: `What began as an emergency measure then became an expensive holding operation.` },
    { type: 'paragraph', text: `The National Audit Office found that £377 million had been spent by 31 January 2026. At the spending rate then expected, the total intervention cost was projected to reach about £615 million by 30 June, including adviser and departmental costs.` },
    { type: 'paragraph', text: `That £615 million was a forecast, not a confirmed amount actually spent. The latest published actual government funding figure before nationalisation was the £555 million of working capital reported on 18 June.` },
    { type: 'paragraph', text: `The NAO found that the intervention had not stabilised British Steel's finances. The department had no clear exit strategy, no specific limit on how much cash could be provided and no repayment schedule for the support already advanced. The NAO said it was not apparent that British Steel would be able to repay it.` },
    { type: 'paragraph', text: `It also calculated that, if support continued at the rates then being paid, spending could exceed £1.5 billion in 2028.` },
    { type: 'paragraph', text: `That figure is not a forecast of the final cost of nationalisation. It was a projection based on continuing the previous intervention at roughly the same rate. More importantly, the NAO said it excluded the costs of transforming British Steel, any compensation for Jingye and eventual exit costs.` },
    { type: 'paragraph', text: `Nationalisation is supposed to provide a route out of that holding pattern.` },
    { type: 'paragraph', text: `The new government-owned company has the Business Secretary as its sole shareholder. Its board has been instructed to develop a plan to make British Steel commercially and environmentally sustainable and to consider future private investment.` },
    { type: 'paragraph', text: `No cost has been attached to that transformation.` },
    { type: 'paragraph', text: `Scunthorpe's ageing blast furnaces have suffered unplanned outages, and the NAO found that production was below planned levels in almost every week it examined. Moving eventually to electric arc furnaces, direct-reduced iron or another lower-carbon production model would require further capital spending.` },
    { type: 'paragraph', text: `The government had already offered Jingye £500 million towards an electric arc furnace conversion before the emergency intervention. That proposal was never implemented. Nationalisation does not remove the need to decide what replaces the existing furnaces or how much taxpayers will contribute to it.` },
    { type: 'paragraph', text: `Compensation is also unresolved.` },
    { type: 'paragraph', text: `Ministers say British Steel's commercial value today is nil, but that is the government's assessment rather than the final compensation decision. Regulations due in the autumn will appoint an independent valuer to determine whether compensation is payable and, if so, how much. The determination will be published and can be appealed to the Upper Tribunal.` },
    { type: 'paragraph', text: `The government has promised quarterly statements for at least the next year setting out financial assistance provided to British Steel.` },
    { type: 'paragraph', text: `On the day it nationalised the company, however, it could say how much working capital had already been provided, why it believed the plant needed to remain open and why it considered public ownership necessary.` },
    { type: 'paragraph', text: `It could not say what making British Steel financially sustainable will ultimately cost.` },
  ],
  evidence: {
    recordsReviewed: [
      `Department for Business and Trade, British Steel, written ministerial statement, 16 July 2026: confirms nationalisation, the government's assessment that British Steel's current commercial value is nil, the independent compensation process, the new ownership structure and quarterly financial reporting commitment`,
      `Department for Business and Trade, Government brings British Steel into public ownership to protect UK steelmaking, 16 July 2026: confirms the date of nationalisation, the stated public-interest rationale and the government's plan for a commercially sustainable business`,
      `National Audit Office, Investigation into the government's intervention in British Steel's Scunthorpe site, March 2026: the £377 million actual spend to 31 January, the £615 million June projection, the lack of a clear exit strategy, the potential £1.5 billion scenario, production problems, employment figures, the £500 million offer to Jingye and the chronology leading to the April 2025 intervention`,
      `National Audit Office, evidence on the March and April 2025 decisions: the finding that officials initially advised there was no affordable solution to maintain steelmaking at Scunthorpe and that the emergency intervention proceeded without completed value-for-money and feasibility assessments because of the urgency`,
      `Department for Business and Trade, written ministerial statement, 18 June 2026: the latest published actual figure before nationalisation of approximately £555 million supplied to British Steel for working capital`,
      `Department for Business and Trade, The UK Steel Strategy, March 2026: confirms that Scunthorpe operates Britain's last blast furnaces, that British Steel is the UK's only rail and heavy-sections producer and that it supplies about 80 per cent of Network Rail's rail requirements`,
      `House of Commons written answer, 2 July 2026: confirms that the April 2025 intervention resulted in British Steel cancelling a redundancy consultation affecting 2,700 jobs`,
    ],
    lastChecked: '4 October 2026',
  },
};

export default piece;
