import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'when-did-politicians-stop-taking-responsibility',
  kicker: 'Constitutional Affairs',
  headline: `Ministers Still Have to Answer for Departmental Failure. They Do Not Have to Resign for It`,
  standfirst: `When Agriculture Minister Sir Thomas Dugdale resigned over the Crichel Down affair in 1954, he told the Commons that a minister had to accept responsibility for the mistakes and inefficiency of officials in his department. The episode is still regularly treated as evidence of an older political culture in which ministers resigned when the machinery beneath them failed. The history is less straightforward.`,
  publishedAt: '2026-06-11',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `When Agriculture Minister Sir Thomas Dugdale resigned over the Crichel Down affair in 1954, he told the Commons that a minister had to accept responsibility for the mistakes and inefficiency of officials in his department.` },
    { type: 'paragraph', text: `The episode is still regularly treated as evidence of an older political culture in which ministers resigned when the machinery beneath them failed.` },
    { type: 'paragraph', text: `The history is less straightforward.` },
    { type: 'paragraph', text: `Dugdale did resign, but the principles set out during the Crichel Down debate did not say that every departmental mistake required a minister to leave office. They distinguished between different levels of failure. For ordinary mistakes or delays, the minister was expected to acknowledge the error, accept responsibility and explain what would be done to correct it. Even where an official had behaved improperly without the minister's knowledge, the minister remained responsible for explaining to Parliament what had happened.` },
    { type: 'paragraph', text: `Nor was Dugdale's case as clean an example of resignation for somebody else's mistake as it is sometimes remembered. A later House of Lords Constitution Committee report noted that Dugdale had been personally involved in the land transactions and had come under pressure from Conservative backbenchers, while officials themselves were named and criticised by the inquiry.` },
    { type: 'paragraph', text: `Lord Carrington's resignation as foreign secretary after Argentina invaded the Falkland Islands in 1982 came closer to the popular idea of ministerial responsibility.` },
    { type: 'paragraph', text: `Carrington left even though Margaret Thatcher wanted him to remain in office. Thatcher later told the Commons that she had tried to persuade him not to resign. A former Foreign Office minister subsequently said the ministerial team considered resignation the "honourable course" after the failure to prevent the invasion.` },
    { type: 'paragraph', text: `That was a powerful precedent. It was not an automatic constitutional rule.` },
    { type: 'paragraph', text: `By 1996 the Conservative government was stating the distinction openly. Ministers remained accountable to Parliament for their departments and executive agencies, it said, but could not reasonably be considered personally blameworthy for every incompetent act carried out by somebody working beneath them when they had no personal involvement in it.` },
    { type: 'paragraph', text: `Government had also become harder to fit into the old departmental model.` },
    { type: 'paragraph', text: `From 1988, the Next Steps programme transferred day-to-day management of large parts of the civil service to executive agencies. Ministers formally remained accountable, but agency chief executives acquired direct responsibility for operations and increasingly answered detailed parliamentary questions themselves.` },
    { type: 'paragraph', text: `A House of Lords committee examining the change in the late 1990s found that ministers were increasingly referring operational questions to agency chiefs. It said this appeared "very different" from the previous understanding that ministers answered for everything happening within their departments. The committee nevertheless rejected the idea that ministers could simply transfer constitutional accountability away and recommended that they remain accountable for their agencies.` },
    { type: 'paragraph', text: `Parliament then put the principle into writing.` },
    { type: 'paragraph', text: `In March 1997 the Commons formally resolved that ministers had a duty to "account, and be held to account" for the policies, decisions and actions of their departments and executive agencies.` },
    { type: 'paragraph', text: `But the resolution did not say ministers must resign whenever those departments failed.` },
    { type: 'paragraph', text: `It identified one specific circumstance in which resignation was expected: a minister who knowingly misled Parliament should offer their resignation to the prime minister.` },
    { type: 'paragraph', text: `That distinction still exists.` },
    { type: 'paragraph', text: `The Ministerial Code requires ministers to account for the policies, decisions and actions of their departments and agencies, while the longstanding parliamentary rule on knowingly misleading Parliament remains. A Commons committee reviewing ministerial accountability in January 2026 said those parliamentary expectations continued to exist independently of the code itself.` },
    { type: 'paragraph', text: `There have been later resignations that resemble the older idea of accepting responsibility for performance.` },
    { type: 'paragraph', text: `Education Secretary Estelle Morris resigned in 2002 after a series of problems in education, including the A-level marking crisis. Her departure was unusual precisely because it was not principally a personal scandal or a disagreement with government policy. Morris also concluded that she was not performing the job as well as she believed a cabinet minister should. A Commons Library examination of ministerial responsibility described her resignation as an unusual case.` },
    { type: 'paragraph', text: `Amber Rudd's departure as home secretary during the Windrush scandal in 2018 provides a more complicated example.` },
    { type: 'paragraph', text: `Rudd had incorrectly told the Home Affairs Committee that the Home Office did not have removal targets. She subsequently acknowledged that targets had been used and resigned after discovering information had been provided to her office which referred to them. An official review later examined the quality of support and advice she had received from Home Office officials.` },
    { type: 'paragraph', text: `Rudd later said she believed the failures of the Home Office required the resignation of the home secretary regardless of her own mistakes before the select committee. That was her interpretation of political responsibility, rather than a rule compelling her to leave.` },
    { type: 'paragraph', text: `Resignation itself has not disappeared from Westminster.` },
    { type: 'paragraph', text: `The Institute for Government counted 11 ministerial resignations outside reshuffles under Keir Starmer between the 2024 general election and 13 January 2026, the second-highest total for a recent prime minister at the same stage of a premiership.` },
    { type: 'paragraph', text: `But the reasons are revealing.` },
    { type: 'paragraph', text: `Five involved retirement, health or personal circumstances. Two were resignations over disagreement with government policy. The Institute classified the remaining four as connected to ethical standards. None of the 11 was classified as a resignation for poor departmental performance.` },
    { type: 'paragraph', text: `The constitutional problem is therefore not quite that Britain once had a firm rule requiring ministers to resign for failure and politicians subsequently abolished it.` },
    { type: 'paragraph', text: `The rule was always more qualified.` },
    { type: 'paragraph', text: `Ministers were expected to answer for their departments, provide information to Parliament, correct mistakes and take corrective action. Resignation depended on the seriousness of the failure, the minister's own involvement, political pressure and ultimately whether the prime minister continued to support them.` },
    { type: 'paragraph', text: `That ambiguity was already visible decades ago. In 1997, when John Major was asked what departmental failures would require a minister to resign, he said it would depend on the circumstances, including the nature of the failure and the minister's personal responsibility for it.` },
    { type: 'paragraph', text: `The machinery of government has since added more agencies, regulators, contractors and delegated responsibilities, making the line between political decisions and operational failures harder to draw. The House of Lords Constitution Committee recognised that problem in 2012 but concluded that ministers remaining constitutionally responsible for their departments was still essential because otherwise Parliament could be left without anybody required to give an account.` },
    { type: 'paragraph', text: `The consequence is a system in which responsibility and resignation are two different things.` },
    { type: 'paragraph', text: `A minister can be responsible for answering for a departmental failure without being judged personally responsible for causing it. Parliament can demand explanations, summon ministers, question them, criticise them and require corrections. Except in specific circumstances such as knowingly misleading Parliament, there is no rule that converts a serious failure into an automatic resignation.` },
    { type: 'paragraph', text: `Whether a minister ultimately loses their job remains largely a political decision, with the prime minister the final judge of whether they remain in office.` },
  ],
  evidence: {
    recordsReviewed: [
      `House of Lords Constitution Committee, The accountability of civil servants, 2012: sets out the Crichel Down principles, the limits of the historical precedent and the committee's conclusion that ministers remain constitutionally responsible for their departments`,
      `Hansard, Ministerial Responsibility debate, 12 February 1996: records the government's distinction between ministerial accountability for a department and personal blame for every operational mistake within it`,
      `House of Lords Public Service Committee report, 1998: examines the effect of executive agencies on operational responsibility and parliamentary accountability`,
      `House of Commons resolution on Ministerial Accountability, 19 March 1997: establishes the duty of ministers to account for departments and the specific expectation of resignation where Parliament is knowingly misled`,
      `Public Administration and Constitutional Affairs Committee, Ministerial Statements and the Ministerial Code, 9 January 2026: confirms the continuing status of Parliament's ministerial-accountability principles and examines the limits of sanctions under the Ministerial Code`,
      `Hansard and parliamentary records on the Falklands, 1982-83: record Lord Carrington's resignation and Margaret Thatcher's statement that she had tried to persuade him to remain Foreign Secretary`,
      `House of Commons Library, Individual ministerial responsibility: issues and examples, 2004: examines Estelle Morris's 2002 resignation and its unusual relationship to departmental and personal responsibility`,
      `Home Office and Hansard records on Amber Rudd and removal targets, 2018: record Rudd's statements to Parliament and the subsequent official review of the advice supplied to her`,
      `Institute for Government, Whitehall Monitor 2026: counts ministerial resignations outside reshuffles under the Starmer government to 13 January 2026 and categorises the reasons for them`,
      `Hansard, Ministerial Accountability, 5 March 1997, HC Deb vol. 291, c623W: records John Major's written answer to Lindsay Hoyle that whether departmental failure should require a minister's resignation depended on the nature of the failure and the extent of the minister's personal responsibility`,
    ],
    lastChecked: '5 October 2026',
  },
};

export default piece;
