import type { EditorialEntry } from './types';

// Assessment of the Labour government's record against its 2024 manifesto
// promises, two years on. Every figure independently fact-checked against
// non-partisan sources (ONS, OBR, IFS, Full Fact, Channel 4 FactCheck,
// Ofgem, Home Office, House of Commons and Lords Library, Hansard).

const piece: EditorialEntry = {
  slug: 'whr8acs2gf',
  kicker: 'Reading the Record',
  headline: "Labour's Broken Promise Problem",
  standfirst:
    'Keir Starmer was not elected on ideological excitement. He was elected on trust. Two years on, the promises Labour broke are the ones that mattered most to voters.',
  publishedAt: '2026-06-23',
  authorByline: "The People's Chamber",
  body: [
    { type: 'paragraph', text: `When Labour won the 2024 general election, it did so on one argument above all others: trust. Britain had endured years of chaos, instability and broken promises under the Conservatives. Labour promised competence, seriousness and honesty. Keir Starmer's pitch was not ideological. It was contractual. Vote for us and you can believe what we tell you.` },
    { type: 'paragraph', text: `Two years later, the contract is in trouble. And the damage was largely self inflicted in the first hundred days.` },
    { type: 'paragraph', text: `The manifesto said Labour would not increase National Insurance, the basic, higher or additional rates of Income Tax, or VAT. Not employee National Insurance. Not some categories of National Insurance. National Insurance. In October 2024, Rachel Reeves increased employer contributions from 13.8 percent to 15 percent and cut the threshold at which they become payable. The change was forecast to raise £23.8 billion in 2025/26, rising to £25.7 billion by 2029/30. Paul Johnson, then director of the Institute for Fiscal Studies, called it a straightforward breach. The official forecast expected around three quarters of the cost to land on workers through lower wages, reduced hiring or higher prices. The government said the pledge applied only to employee National Insurance. The manifesto does not say that.` },
    { type: 'paragraph', text: `Then came November 2025 and a second Budget raising another £26 billion. Income tax thresholds were frozen to 2030/31, having been promised to rise with inflation from 2028. Across the two Budgets, tax rises reached around £66 billion. The tax burden is heading for 38.3 percent of GDP by the end of the decade, the highest on record. Labour inherited a burden the Conservatives had already pushed to a 70 year high and raised it further still. Sixty six billion pounds. From a party that won office by promising not to raise taxes on working people.` },
    { type: 'paragraph', text: `The winter fuel cut was politically even more destructive, because it arrived first and hit hardest. Within weeks of taking office, Reeves removed between £200 and £300 a year from around 10 million pensioners. The Treasury cited a £22 billion black hole in the public finances. Mel Stride said the special contract Labour sought to have with the British people, based on integrity and decency, had been smashed into a million pieces. He was not entirely wrong. Labour had spent years attacking Conservative cuts to pensioner support. Its first major spending decision was to cut pensioner support. After months of damage, the government restored the payment to most recipients and clawed it back only from those on higher incomes. By then the impression had set: Labour entered office promising competence and spent its opening months defending a decision it could not sustain.` },
    { type: 'paragraph', text: `Those two episodes, the National Insurance increase and the winter fuel cut, changed the government's relationship with voters. Everything that followed landed on ground that was already fractured.` },
    { type: 'paragraph', text: `Labour promised to smash the criminal boat gangs. In its first six months, 23,242 people arrived by small boat, a 29 percent increase on the same period in 2023. The Border Security, Asylum and Immigration Bill introduced new powers. Whether they have worked is contested. The 29 percent increase is not.` },
    { type: 'paragraph', text: `Labour told farmers it would protect Agricultural Property Relief. Steve Reed said so at the Country Land and Business Association conference in November 2023. In October 2024, the Budget imposed inheritance tax on farmland above £1 million. Thousands of farmers protested. Fourteen months later the threshold was raised to £2.5 million, with couples able to pass on £5 million. The original promise was broken. The revision was an admission of the damage.` },
    { type: 'paragraph', text: `Labour promised to cut energy bills by up to £300 by 2030. By October 2024 the price cap had risen by around £149. Ministers would not confirm the £300 commitment. The promise has not been kept.` },
    { type: 'paragraph', text: `Seven Labour MPs had the whip suspended for voting to scrap the two child benefit cap that Labour figures had spent years opposing. Eighteen months later, Labour scrapped it anyway. Mandatory Digital ID was announced in September 2025 and abandoned in January 2026 after a petition approaching three million signatures. A consultation on closing post office branches was reversed after 180,000 signatures. In April 2026, the government announced it would scrap Carbon Price Support, a policy it had previously defended. The Chagos sovereignty deal was signed and then stalled when American support evaporated. A grooming gangs inquiry was resisted for six months before being announced. Each U turn was individually explicable. Collectively they read as a government that announces before it thinks and retreats when the reaction arrives.` },
    { type: 'paragraph', text: `Independent trackers tell a more complete story. One, monitoring 92 manifesto commitments, records 24 achieved and 15 on track, against 6 not kept. Another rated 22 of 36 pledges as delivered or on track around Labour's first anniversary. Breakfast clubs have expanded. Rail nationalisation is underway. The NHS hit 40,000 extra appointments a week ahead of schedule. The Employment Rights Act and the Planning and Infrastructure Act both reached the statute book. These are real achievements, and pretending otherwise would be dishonest in the opposite direction.` },
    { type: 'paragraph', text: `But voters do not average out promises. They remember the ones that hurt. Sixty six billion in tax rises when you promised not to raise taxes. Winter fuel cut when you campaigned on protecting pensioners. A 29 percent rise in boat crossings when you promised to smash the gangs. Unemployment rising from 4.2 to 5.1 percent, the highest since the pandemic. Inflation inherited at 2.0 percent and hitting 3.4 by December 2025, above the Bank of England's target every month that year. The government inherited a difficult hand. Every government does. The difference is that this one asked to be judged on trust, and trust is binary. It exists or it does not.` },
    { type: 'paragraph', text: `Starmer's Labour was not elected on excitement. It was elected on reliability. And once enough voters suspect that every promise contains an asterisk, reliability is the one thing a government cannot get back.` },
  ],
};

export default piece;
