import type { EditorialEntry } from './types';

// Assessment of the Labour government's record against its 2024 manifesto
// promises, two years on. Every figure independently fact-checked against
// non-partisan sources (ONS, OBR, IFS, Full Fact, Channel 4 FactCheck,
// Ofgem, Home Office, House of Commons and Lords Library, Hansard).

const piece: EditorialEntry = {
  slug: 'whr8acs2gf',
  kicker: 'Reading the Record',
  headline: "Labour's Broken Promise Problem",
  standfirst:
    'Keir Starmer was not elected on ideological excitement. He was elected on trust. Two years on, the promises Labour broke are the ones that mattered most to voters.',
  publishedAt: '2026-06-23',
  authorByline: "The People's Chamber",
  body: [
    { type: 'paragraph', text: `When Labour won the 2024 general election, it did so on one argument above all others: trust. Britain had endured years of chaos, instability and broken promises under the Conservatives. Labour promised competence, seriousness and honesty. Keir Starmer's pitch was not ideological. It was contractual. Vote for us and you can believe what we tell you.` },
    { type: 'paragraph', text: `Two years later, the contract is in trouble.` },
    { type: 'paragraph', text: `The manifesto said Labour would not increase taxes on working people, which was why it would not increase National Insurance, the basic, higher, or additional rates of Income Tax, or VAT. The wording on National Insurance appeared unambiguous. In October 2024, Rachel Reeves increased employer National Insurance contributions from 13.8 percent to 15 percent and cut the threshold at which they become payable. The change was forecast to raise £23.8 billion in 2025/26, rising to £25.7 billion by 2029/30. Paul Johnson, then director of the Institute for Fiscal Studies, called it a straightforward breach of a manifesto commitment. The government argued the pledge applied only to employee National Insurance. The manifesto does not say that. The official forecast expected most of the cost, around three quarters, to be passed on to workers through lower wages, reduced hiring or higher prices.` },
    { type: 'paragraph', text: `In November 2025, Reeves delivered a second Budget raising a further £26 billion in taxes. She extended the freeze on income tax thresholds to 2030/31, having promised the year before to let them rise with inflation from 2028. Across the two Budgets, tax rises reached around £66 billion, and the tax burden is set to climb to 38.3 percent of GDP by the end of the decade, the highest on record. Labour inherited a tax burden the Conservatives had already pushed to a 70 year high. Labour raised it further.` },
    { type: 'paragraph', text: `Within weeks of taking office, Reeves cut the universal winter fuel allowance, removing between £200 and £300 a year from around 10 million pensioners. The Treasury cited a £22 billion black hole in the public finances. The Conservatives pointed out that Labour had made no mention of the cut during the election campaign. Mel Stride said the special contract Labour sought to have with the British people, based on integrity and decency, had been smashed into a million pieces. After months of political damage, the government restored the payment to the large majority of pensioners and clawed it back only from those on higher incomes.` },
    { type: 'paragraph', text: `Labour's manifesto promised to smash the criminal boat gangs. Between 5 July and 31 December 2024, 23,242 people arrived by small boat, a 29 percent increase on the same period in 2023. The Border Security, Asylum and Immigration Bill introduced new powers and enforcement cooperation with France. Whether those measures reduced crossings in 2025 and 2026 is contested. The 29 percent increase in Labour's first six months is not.` },
    { type: 'paragraph', text: `Before the election, Labour figures including Keir Starmer and Steve Reed repeatedly told farmers the party respected them and would protect their livelihoods. At the Country Land and Business Association conference in November 2023, Reed said Labour had no intention of changing Agricultural Property Relief. In the October 2024 Budget, Labour imposed inheritance tax on agricultural land worth more than £1 million. The backlash was severe. Thousands of farmers protested. After 14 months of campaigning, the government raised the threshold to £2.5 million per estate and made it transferable between spouses, allowing couples to pass on up to £5 million in qualifying assets. The original promise was broken. The revised policy was an admission of the damage.` },
    { type: 'paragraph', text: `The two child benefit cap had been a target for Labour criticism for years. Multiple Labour figures called for its abolition before the election. Once in government, Labour initially retained it, and seven of its own MPs had the whip suspended for voting to scrap it. At the November 2025 Budget, the cap was abolished. The final policy may have been right. The route to it, from opposition to retention to abolition within 18 months, was not a display of conviction.` },
    { type: 'paragraph', text: `Labour promised to cut household energy bills by up to £300 by 2030 through clean energy investment and reform. By October 2024 the energy price cap had instead risen by around £149, the first of several increases under the new government. Ministers would not confirm the £300 commitment. Bills remain heavily influenced by global markets. The promise has not been kept.` },
    { type: 'paragraph', text: `The economy has not cooperated with the narrative either. Unemployment rose from 4.2 percent at the election to 5.1 percent by late 2025, the highest since the pandemic, though the official figures from this period carry their own reliability warnings. Inflation was inherited at the Bank of England's 2.0 percent target. By December 2025 it had risen to 3.4 percent, and it exceeded the target in every month of 2025.` },
    { type: 'paragraph', text: `The U turns accumulated. In September 2025 Labour announced mandatory Digital ID. After a petition approaching three million signatures, it retreated in January 2026, dropping the demand that digital identity be the only accepted proof of the right to work. Labour resisted calls for a national grooming gangs inquiry for six months before announcing one in June 2025. A consultation was launched on the future of the post office network. After 180,000 petition signatures, the government committed to maintaining at least 11,500 branches. In April 2026, having previously defended the policy, the government announced it would scrap Carbon Price Support. The Chagos Islands sovereignty deal was negotiated and signed, then stalled when the United States withheld the support needed to bring it into force.` },
    { type: 'paragraph', text: `Independent pledge trackers tell a more balanced story. One, monitoring 92 manifesto commitments, records 24 as achieved, 15 on track and 24 in progress, against 5 off track, 6 not kept and a handful still unclear or too early to call. Another, examining 36 pledges around Labour's first anniversary, rated 22 as delivered or on track and 10 as inconclusive. The government can point to genuine delivery. Breakfast clubs have been expanded across England. Rail nationalisation is underway, with South Western Railway brought into public ownership. The NHS hit its target of 40,000 extra appointments a week ahead of schedule. The Employment Rights Act reached the statute book. The Planning and Infrastructure Act received Royal Assent.` },
    { type: 'paragraph', text: `The problem is not that every promise has been broken. Many have not. The problem is that the promises that were broken are the ones that mattered most to voters: taxes, energy bills, immigration and the cost of living. The government would argue it inherited weaker finances than expected and a hostile international environment. There is truth in that defence. But voters do not measure governments against the circumstances they inherit. They measure them against the promises they made.` },
    { type: 'paragraph', text: `Starmer's Labour was not elected on ideological excitement. It was elected on reliability. That raises the stakes for every U turn, every reinterpretation and every gap between commitment and delivery. A government elected on trust that breaks trust does not just lose an argument. It loses the one thing that made voters choose it over the alternative.` },
    { type: 'pullQuote', text: `A government elected on trust that breaks trust does not just lose an argument. It loses the one thing that made voters choose it over the alternative.` },
    { type: 'paragraph', text: `The real danger is not that Labour has broken every promise. It has not. The danger is that enough voters begin to suspect every promise contains an asterisk. And once that suspicion takes hold, trust becomes far harder to rebuild than it was to lose. Around £66 billion in tax rises, a record tax burden, a 29 percent increase in small boat arrivals, unemployment at its highest since the pandemic, inflation above target every month, and a run of U turns that would embarrass a fairground carousel. That is the record. The question is whether voters judge Labour by the promises it kept or the ones it did not. The answer will determine whether this government survives long enough to deliver the things it says it still intends to do.` },
  ],
};

export default piece;
