import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'whr8acs2gf',
  kicker: 'Labour Government',
  headline: `Labour Promised Not to Raise National Insurance. The OBR Says Workers Bear Most of the Rise`,
  standfirst: `Labour's 2024 manifesto said it would not increase National Insurance. Four months after the election, Rachel Reeves increased employer National Insurance. The OBR estimates that by 2026/27, 76 per cent of the long-run cost will ultimately be reflected in lower real wages. Labour's defence — that the promise referred to taxes paid directly by working people — was not what the manifesto said.`,
  publishedAt: '2026-06-23',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `Labour's 2024 manifesto contained a sentence that left little room for interpretation.` },
    { type: 'paragraph', text: `"Labour will not increase taxes on working people, which is why we will not increase National Insurance, the basic, higher, or additional rates of Income Tax, or VAT."` },
    { type: 'paragraph', text: `Four months after the election, Rachel Reeves increased employer National Insurance.` },
    { type: 'paragraph', text: `The rate rose from 13.8 per cent to 15 per cent from April 2025 and the earnings threshold at which employers start paying it fell from £9,100 to £5,000. The OBR initially estimated the changes would raise £23.8 billion in 2025/26, rising to £25.7 billion in 2029/30, before indirect economic effects and compensation for public-sector employers.` },
    { type: 'paragraph', text: `Labour's defence was that its manifesto promise referred to taxes paid directly by working people rather than National Insurance paid by employers.` },
    { type: 'paragraph', text: `The manifesto did not say that.` },
    { type: 'paragraph', text: `During the election campaign Labour described the commitment as a "tax lock for working people". Its manifesto referred simply to "National Insurance". Before the Budget, then Institute for Fiscal Studies director Paul Johnson said an employer increase would be a "straightforward breach" of the promise. Full Fact now rates the National Insurance pledge as not kept.` },
    { type: 'paragraph', text: `Employer National Insurance is legally paid by employers. Economically, the distinction is less clean.` },
    { type: 'paragraph', text: `The OBR assumed that in the first year firms would pass 60 per cent of the additional cost to workers and consumers through lower wages and higher prices. From 2026/27 onwards, it assumes 76 per cent of the total cost will ultimately be reflected in lower real wages, with the remaining 24 per cent absorbed through lower profits.` },
    { type: 'paragraph', text: `Of the long-run effect on workers, the OBR expects four-fifths to come through lower nominal wages and one-fifth through higher prices. It also estimated that the measure would reduce labour supply by a little over 50,000 on an average-hours-equivalent basis by 2029/30, split roughly equally between fewer people in work and lower hours among those who remained employed.` },
    { type: 'paragraph', text: `That does not mean every worker has had 76 per cent of an individual employer's tax bill deducted from their pay. It is an economy-wide forecast of where the cost will eventually fall.` },
    { type: 'paragraph', text: `It does mean the government's argument that employer National Insurance is separate from taxes on working people has never been as simple as the name on the tax return.` },
    { type: 'paragraph', text: `The first Budget contained tax measures which the OBR estimated would raise £41.5 billion a year by 2029/30. The November 2025 Budget then introduced another set of tax measures worth £26.1 billion in 2029/30 on the OBR's contemporaneous costing. Those figures should not simply be added together and described as one current £67.6 billion tax bill, because policies, baselines and forecasts change between fiscal events. They do show the scale of the tax decisions taken during Labour's first 18 months.` },
    { type: 'paragraph', text: `The second Budget also reversed another explicit commitment Reeves had made after entering office.` },
    { type: 'paragraph', text: `In October 2024, the Chancellor considered extending the Conservative freeze on personal Income Tax and National Insurance thresholds beyond 2027/28.` },
    { type: 'paragraph', text: `She rejected it.` },
    { type: 'paragraph', text: `"Extending the threshold freeze would hurt working people," Reeves told Parliament. "It would take more money out of their payslips."` },
    { type: 'paragraph', text: `She said personal tax thresholds would rise with inflation from 2028/29. The published Budget repeated the commitment.` },
    { type: 'paragraph', text: `Thirteen months later, the 2025 Budget froze those thresholds for another three years, through 2030/31.` },
    { type: 'paragraph', text: `The OBR estimates that decision will raise about £8 billion in 2029/30. It expects roughly 780,000 more people to be paying basic-rate Income Tax and 920,000 more to be paying the higher rate by then than under its previous forecast.` },
    { type: 'paragraph', text: `This was not a broken 2024 manifesto promise in the same way as the National Insurance dispute. The promise to start uprating thresholds in 2028 was made by Reeves in government at the October 2024 Budget.` },
    { type: 'paragraph', text: `It was still a clear commitment, followed by a clear reversal.` },
    { type: 'paragraph', text: `The tax burden is now forecast to reach 38.3 per cent of GDP in 2030/31, the highest level in the OBR's historical series. The OBR says that rise reflects policies taken over several governments, including the long-running freeze in personal tax thresholds inherited from the Conservatives as well as Labour's employer National Insurance increase and later tax measures. It cannot fairly be attributed to Labour alone.` },
    { type: 'paragraph', text: `The government's explanation for changing course has been consistent.` },
    { type: 'paragraph', text: `Ministers say they inherited public finances in substantially worse condition than they had understood before taking office and had to raise revenue to protect public services and meet their fiscal rules. Those rules are currently judged by Full Fact to be on track.` },
    { type: 'paragraph', text: `The same explanation was used when Labour changed its position on inheritance tax relief for farms.` },
    { type: 'paragraph', text: `In November 2023, while shadow environment secretary, Steve Reed was asked whether Labour intended to change Agricultural Property Relief.` },
    { type: 'paragraph', text: `He said no.` },
    { type: 'paragraph', text: `After Reeves announced reforms the following October, Reed returned to the Country Land and Business Association conference and addressed his previous answer directly.` },
    { type: 'paragraph', text: `"You asked me last year if Labour would raise APR. I said no. That was our position at the time. You deserve an explanation."` },
    { type: 'paragraph', text: `He said Labour had changed its position because it had not known the full scale of the fiscal problems it would inherit.` },
    { type: 'paragraph', text: `The original reform allowed 100 per cent Agricultural and Business Property Relief on the first £1 million of qualifying assets and 50 per cent relief above that, creating an effective inheritance tax rate of 20 per cent on qualifying assets above the allowance.` },
    { type: 'paragraph', text: `The government later changed the policy again. In December 2025 it increased the 100 per cent relief allowance from £1 million to £2.5 million, transferable between spouses and civil partners, allowing a couple potentially to pass on £5 million of qualifying agricultural or business assets before the reduced relief begins. The government estimates 85 per cent of estates claiming Agricultural Property Relief in 2026/27 will pay no additional inheritance tax because of the reform.` },
    { type: 'paragraph', text: `That later change does not erase Reed's earlier promise. Nor does it prove the original reform was indefensible. Ministers argued that unlimited relief was being used disproportionately by larger estates and non-farming investors and that some tax revenue was justified.` },
    { type: 'paragraph', text: `The sequence is simpler than either side sometimes makes it: Labour said it had no intention of changing APR, changed it after entering government, then softened the change before it came into force.` },
    { type: 'paragraph', text: `Winter Fuel Payment followed a different pattern.` },
    { type: 'paragraph', text: `Labour's manifesto did not promise to preserve the universal payment.` },
    { type: 'paragraph', text: `On 29 July 2024, however, Reeves announced that it would be restricted in England and Wales to pensioners receiving specified means-tested benefits. Official statistics later showed recipients falling from 10.6 million in winter 2023/24 to 1.3 million in 2024/25.` },
    { type: 'paragraph', text: `The government estimated the restriction would save £1.3 billion in its first year and about £1.5 billion in subsequent years.` },
    { type: 'paragraph', text: `In June 2025, it reversed most of the change.` },
    { type: 'paragraph', text: `From winter 2025/26, the payment returned to almost all pensioners, with those whose taxable income exceeded £35,000 having the money recovered through the tax system unless they opted out. The Treasury initially estimated about nine million pensioners would receive it.` },
    { type: 'paragraph', text: `That was a major policy reversal. Calling it a broken manifesto promise would be inaccurate because the manifesto contained no commitment to maintain the old Winter Fuel Payment system.` },
    { type: 'paragraph', text: `Not every unpopular decision is a broken promise, and not every missed political objective can be classified as one either.` },
    { type: 'paragraph', text: `Labour's promise to cut household energy bills by up to £300 has a 2030 deadline. In November 2025 the government said it remained its intention to deliver it. Energy bills rising before then may make the promise harder to achieve, but they do not prove in June 2026 that a 2030 pledge has already been broken.` },
    { type: 'paragraph', text: `Small-boat arrivals present a similar problem. Labour promised to create a Border Security Command and "smash the gangs" organising crossings. Arrivals rose to 36,816 during 2024, 25 per cent higher than in 2023, but the manifesto did not attach a numerical reduction or a date to the phrase "smash the gangs". A rise in crossings is evidence about performance. It is not enough on its own to identify the precise point at which that manifesto promise becomes formally broken.` },
    { type: 'paragraph', text: `There are commitments the government has delivered or remains on course to deliver.` },
    { type: 'paragraph', text: `Full Fact rates Labour's fiscal rules as on track and records the introduction of its Neighbourhood Policing Guarantee. The two-child limit in Universal Credit, which Labour initially declined to abolish immediately after taking office, was removed from April 2026 after being funded in the 2025 Budget. That was another policy change, but in this case the government moved towards a position many Labour MPs had wanted from the start.` },
    { type: 'paragraph', text: `The record therefore does not support the claim that Labour has simply abandoned everything it promised in 2024.` },
    { type: 'paragraph', text: `It does support a narrower and harder criticism.` },
    { type: 'paragraph', text: `Those three commitments were specific enough to check against what subsequently happened, which is why they can be rated rather than argued about.` },
    { type: 'paragraph', text: `The National Insurance sentence is still on page 21 of Labour's manifesto.` },
  ],
  evidence: {
    recordsReviewed: [
      `Labour Party, Change: Labour Party Manifesto 2024: contains the commitment that Labour would not increase National Insurance or the basic, higher or additional rates of Income Tax or VAT`,
      `Labour Party, manifesto launch page, 13 June 2024: confirms Labour's own campaign description of the commitment as "a tax lock for working people"`,
      `HM Treasury, Autumn Budget 2024: confirms the employer National Insurance increase from 13.8 per cent to 15 per cent, reduction of the secondary threshold from £9,100 to £5,000 and the original commitment to begin uprating personal tax thresholds from April 2028`,
      `HM Treasury, Rachel Reeves, Autumn Budget speech transcript, 30 October 2024: records the Chancellor's exact words on the threshold freeze, her decision not to extend it beyond the previous government's plans, and her commitment to inflation-linked uprating from 2028/29`,
      `Office for Budget Responsibility, Economic and fiscal outlook, October 2024: supports the £23.8 billion initial employer National Insurance yield, £25.7 billion 2029/30 figure, £41.5 billion total tax-policy figure, the OBR's assumptions about how the employer National Insurance cost would pass through to wages, prices and profits, and the average-hours-equivalent labour supply estimate`,
      `Office for Budget Responsibility, Economic and fiscal outlook, November 2025: supports the further three-year tax-threshold freeze, its estimated £8 billion 2029/30 revenue, the 780,000/920,000 additional-taxpayer estimates, the £26.1 billion of tax measures and the forecast 38.3 per cent tax-to-GDP ratio`,
      `Full Fact, Government Tracker, National Insurance pledge, updated 9 June 2026: rates Labour's National Insurance commitment as "not kept" and sets out the dispute over the meaning of the manifesto wording`,
      `Steve Reed, speech to the Country Land and Business Association conference, 21 November 2024: records Reed acknowledging that he had told the CLA the previous year that Labour would not raise Agricultural Property Relief and explaining why the government had changed its position`,
      `HM Treasury and Defra, Agricultural and Business Property Relief changes, 23 December 2025: confirms the subsequent increase in the 100 per cent relief allowance from £1 million to £2.5 million and the transferable £5 million figure for spouses or civil partners`,
      `Department for Work and Pensions, Winter Fuel Payment statistics for winter 2024/25: confirms recipients in England and Wales fell from 10.6 million to 1.3 million after the 2024 eligibility restriction`,
      `HM Treasury and Department for Work and Pensions, Winter Fuel Payment policy from winter 2025/26: confirms the subsequent restoration of payments to most pensioners and the £35,000 income threshold for recovery through the tax system`,
      `Full Fact, Government Tracker: supports the assessment that Labour's fiscal-rule commitment remained on track in June 2026 and records progress on the Neighbourhood Policing Guarantee`,
    ],
    lastChecked: '5 October 2026',
  },
};

export default piece;
