import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'wk4n9mxw7r',
  kicker: 'Planning',
  headline: `Norfolk Developers Could Pay £2,675 a Home Instead of Arranging Their Own Nutrient Mitigation`,
  standfirst: `Developers in parts of Norfolk could pay a flat £2,675 levy per home instead of arranging project-by-project nutrient pollution mitigation, under the first Environmental Delivery Plan proposed through the government's Nature Restoration Fund. Natural England says it could provide capacity for up to 15,780 homes. The consultation closes 27 October. Environmental groups have questioned whether the proposed charge is high enough.`,
  publishedAt: '2026-09-18',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `Developers in parts of Norfolk could pay a flat £2,675 levy for each new home instead of arranging their own project-by-project mitigation for nutrient pollution under the first Environmental Delivery Plan proposed through the government's Nature Restoration Fund.` },
    { type: 'paragraph', text: `The draft plan covers parts of the River Wensum, Bure Broads and Marshes and Yare Broads and Marshes catchments. Natural England says it could provide capacity for up to 15,780 homes. The consultation runs until 27 October and the plan is not yet in force.` },
    { type: 'paragraph', text: `At the proposed rate, using all 15,780 places would produce about £42.2 million in base levy payments before indexation.` },
    { type: 'paragraph', text: `The money would be pooled by Natural England and used for measures including wetland creation and restoration, conversion of intensively managed agricultural land, river restoration and management of fens and reedbeds.` },
    { type: 'paragraph', text: `For developers, the change is substantial.` },
    { type: 'paragraph', text: `Under the existing nutrient-neutrality system, affected developments can have to calculate their expected nitrogen or phosphorus load and secure mitigation before planning permission can safely be granted.` },
    { type: 'paragraph', text: `Under an Environmental Delivery Plan, a qualifying developer can instead request to use the nature restoration levy. If Natural England accepts the request and issues a commitment certificate, the environmental impact covered by the plan can be disregarded for specified environmental obligations when the planning application is considered. Other environmental effects and planning requirements still have to be assessed normally.` },
    { type: 'paragraph', text: `Natural England then becomes responsible for delivering the conservation programme funded by the levy.` },
    { type: 'paragraph', text: `The legal test is stronger than simply replacing pollution tonne for tonne. Before the plan can take effect, the Secretary of State must be satisfied that its conservation measures will materially outweigh the negative effects of the development on the conservation status of each environmental feature covered by the plan.` },
    { type: 'paragraph', text: `That judgment is based on improvements expected over the life of the Environmental Delivery Plan. Developers can therefore receive the planning benefit of entering the scheme before every conservation measure has been completed.` },
    { type: 'paragraph', text: `The government argues that this allows environmental work to be organised across whole catchments instead of relying on dozens of separate mitigation schemes attached to individual housing sites. Ministers say the present system has stalled development because suitable site-by-site mitigation can be difficult to secure.` },
    { type: 'paragraph', text: `That was also the argument when the Planning and Infrastructure Bill went through Parliament.` },
    { type: 'paragraph', text: `On 9 June 2025, Dan Tomlinson, then a backbench MP for Chipping Barnet rather than a minister, told MPs that around 160,000 homes nationally had been held up by nutrient-neutrality requirements and said on-site mitigation was often "virtually impossible" to deliver development by development. Labour MP Chris Hinchliff argued for stronger protection tying conservation improvements to the particular environmental feature being harmed.` },
    { type: 'paragraph', text: `Norfolk is now the first place where that argument will be tested through an Environmental Delivery Plan.` },
    { type: 'paragraph', text: `The £2,675 rate is flat rather than being calculated separately according to the nutrient burden of each qualifying development. The plan is also expected to be voluntary for most eligible developers, who can continue using another lawful mitigation route instead.` },
    { type: 'paragraph', text: `Environmental groups have already questioned whether the proposed charge is high enough. The Guardian reported on 24 September that an earlier draft of the Norfolk proposals, which it said it had seen, contained potential per-home contributions ranging from about £5,400 to £60,500, depending on the expected nutrient impact of a development. The current consultation proposes £2,675 per dwelling. That earlier draft is not among the public material Open Govt has been able to verify independently, so the figures should be treated as attributed reporting rather than a published government dataset.` },
    { type: 'paragraph', text: `The comparison needs care. A strategic catchment-wide programme can cost differently from requiring each development to purchase bespoke mitigation, and the £2,675 charge is intended to finance a different model rather than reproduce the old calculation house by house.` },
    { type: 'paragraph', text: `The test is whether Natural England can deliver enough conservation work at that price to satisfy the statutory requirement that the environmental gains materially outweigh the harm.` },
    { type: 'paragraph', text: `There is already a Norfolk precedent for using public intervention to create nutrient-mitigation capacity.` },
    { type: 'paragraph', text: `In November 2024, government announced £8.85 million of additional Local Nutrient Mitigation Fund money for the Norfolk Broads and River Wensum, saying it was intended to help unlock more than 5,000 homes. Norfolk had already received £9.6 million in an earlier funding round.` },
    { type: 'paragraph', text: `The wider Norfolk Nutrient Mitigation Fund now lists £18.45 million of capital funding.` },
    { type: 'paragraph', text: `There has been delivery from that earlier programme.` },
    { type: 'paragraph', text: `An independent Local Government Association review says Norfolk's approach has resulted in more than 3,000 homes being released through Norfolk Environmental Credits, with mitigation capacity for at least another 3,000 in the pipeline. It also says the capital funding has been fully committed and, because loans are recycled, commitments have already exceeded the original £18.4 million allocation.` },
    { type: 'paragraph', text: `That is stronger evidence than was available when the £8.85 million was announced.` },
    { type: 'paragraph', text: `It is not the same as 3,000 completed homes.` },
    { type: 'paragraph', text: `The LGA review describes homes being "released," meaning mitigation capacity has allowed development to progress through the planning constraint. It does not provide a figure for how many of those homes have subsequently started construction or been completed.` },
    { type: 'paragraph', text: `The same distinction applies to the new 15,780-home figure.` },
    { type: 'paragraph', text: `It is the maximum development capacity Natural England proposes to accommodate through the Environmental Delivery Plan. It is not a forecast that 15,780 homes will be built. Developers will still need planning permission, financing, infrastructure and a decision to proceed with construction.` },
    { type: 'paragraph', text: `The proposed Norfolk plan would also change who carries responsibility for the covered environmental obligation. Once an eligible developer uses the levy route, Natural England is responsible for delivering the strategic conservation measures on which the plan depends.` },
    { type: 'paragraph', text: `The Secretary of State cannot approve the final plan unless satisfied that those measures will materially outweigh the development's environmental effects. The draft is still open to consultation, and the £2,675 rate can therefore still change before the plan is made.` },
    { type: 'paragraph', text: `The government's new headline of up to 15,780 homes should be read on the same basis as the earlier Norfolk figures: planning capacity that may be released, not houses already delivered.` },
  ],
  evidence: {
    recordsReviewed: [
      `Defra and Natural England, "Government unveils plans to unlock over 15,000 new homes", 17 September 2026: 15,780-home maximum, geographic scope, strategic conservation approach and government rationale for the Environmental Delivery Plan`,
      `Natural England and Defra, Norfolk Environmental Delivery Plan consultation, 17 September 2026: status of the plan as a draft under consultation and the consultation timetable, including the 27 October closing date`,
      `Defra, MHCLG and Natural England, "Understanding the Nature Restoration Fund" and "Using the nature restoration levy": developer process, commitment certificates, voluntary nature of most EDPs, disapplication of specified environmental obligations and continuing requirement to assess impacts outside the plan`,
      `Government Environmental Delivery Plans guidance and Nature Restoration Fund implementation plan: overall improvement test and the requirement for conservation measures to materially outweigh the negative effects of development before the Secretary of State may approve an EDP`,
      `House of Commons Hansard, Planning and Infrastructure Bill, 9 June 2025: Dan Tomlinson's estimate of around 160,000 stalled homes, his comments on project-level mitigation, his status as a backbench MP rather than a minister at that date, and Chris Hinchliff's proposed environmental safeguard`,
      `MHCLG, Local Nutrient Mitigation Fund Round 2, October/November 2024: £8.85 million Norfolk allocation and the government's statement that it was intended to unlock more than 5,000 homes`,
      `Local Government Association, "Learning from the Local Nutrient Mitigation Fund", 2026: more than 3,000 homes reportedly released through Norfolk Environmental Credits, at least 3,000 further homes of mitigation capacity in the pipeline, and the status of the fund's capital commitments`,
      `The Guardian, reporting on the Norfolk EDP consultation, 24 September 2026: reported earlier modelling range of roughly £5,400 to £60,500 per dwelling and environmental criticism of the proposed £2,675 levy — not available in GOV.UK material retrieved for this review`,
    ],
    lastChecked: '3 October 2026',
  },
};

export default piece;
