import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'wk4n9mxw7r',
  kicker: 'Planning',
  headline: `Developers Could Pay £2,675 a Home to Clear Norfolk Nutrient Rules Under New Planning Model`,
  standfirst: `Developers in affected Norfolk areas could pay a flat charge of £2,675 for each new home to discharge nutrient-mitigation obligations under a new Environmental Delivery Plan. Government consultation modelling considered a range of £5,400 to £60,500 per house before settling on the lower figure. Environmental groups say the levy is too low; the government says pooled conservation investment will outweigh development impact under a legal "overall improvement test."`,
  publishedAt: '2026-09-17',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `Developers in Norfolk could pay a flat charge of £2,675 for each new home instead of arranging their own project-by-project nutrient mitigation under a new government planning model.` },
    { type: 'paragraph', text: `The first Environmental Delivery Plan under the Nature Restoration Fund is intended to unlock up to 15,780 homes around the Norfolk Broads and River Wensum.` },
    { type: 'paragraph', text: `At full capacity, the levy would raise about £42.2 million before VAT and indexation, or roughly £50.6 million once the 20 per cent VAT the government's own consultation documents apply to the charge is added.` },
    { type: 'paragraph', text: `In return, one of the most difficult environmental obstacles facing some developments would become a fixed cost. Natural England would then take responsibility for delivering enough environmental improvement across the wider catchment to outweigh the damage caused by the new housing.` },
    { type: 'paragraph', text: `That is a major change in how environmental obligations are handled.` },
    { type: 'paragraph', text: `Under the existing nutrient-neutrality system, developers can be required to calculate the likely nutrient pollution from a scheme and arrange mitigation linked to that development.` },
    { type: 'paragraph', text: `The new model allows qualifying developers to make a payment instead.` },
    { type: 'paragraph', text: `Where the Environmental Delivery Plan covers the relevant impact, the local planning authority no longer has to carry out its own appropriate assessment of that impact through the usual project-level route, though it must still consider any environmental effects the plan does not cover, and comply with other relevant legislation.` },
    { type: 'paragraph', text: `Natural England would instead pool the money and spend it on larger conservation projects.` },
    { type: 'paragraph', text: `The government says that could produce better environmental results than dozens of small schemes attached to individual housing developments.` },
    { type: 'paragraph', text: `It also gives housebuilders something they value highly: certainty.` },
    { type: 'paragraph', text: `A developer knows the charge in advance. It no longer has to spend months designing, negotiating and securing its own mitigation package for the covered nutrient issue.` },
    { type: 'heading', level: 2, text: `A levy that has already been cut by more than half` },
    { type: 'paragraph', text: `The proposed Norfolk charge is £2,675 for every eligible house or flat, plus VAT and indexation.` },
    { type: 'paragraph', text: `Applied across all 15,780 homes cited by the government, that produces a base contribution of roughly £42.2 million.` },
    { type: 'paragraph', text: `Natural England says the money would fund work including wetland creation, river restoration, changes to intensive agricultural land, management of reedbeds and fens, and other measures intended to reduce nutrient pollution and restore habitat.` },
    { type: 'paragraph', text: `That figure is already contested, and not just on principle. Government modelling ahead of the consultation had set out a much wider potential range, from around £5,400 to £60,500 per house, depending on how much pollution a given development was calculated to produce. The published rate of £2,675 sits at the very bottom of that range, and in some cases well below it.` },
    { type: 'paragraph', text: `Sally Hayns, chief executive of the Chartered Institute of Ecology and Environmental Management, has called the published levy "very conservative," with what she describes as minimal contingency built in and no separate provision for pollution-avoidance measures at source. Dr Justin Neal of the campaign group WildFish has gone further, describing the plan as "full of holes" and, along with other critics, characterising the model as effectively "pay to pollute."` },
    { type: 'paragraph', text: `Those critics point to a specific gap: even with the conservation programme fully funded and delivered, campaigners' figures suggest the plan does not eliminate the nutrient load from the new housing itself. They cite roughly 7,695kg of additional nitrogen a year, around 83 per cent of the development's calculated pollution burden, and up to 435kg of phosphorus a year that would still enter the protected waterways, to be offset by restoration work elsewhere rather than prevented at the point of development.` },
    { type: 'paragraph', text: `The legal test is not simply that the damage is matched.` },
    { type: 'paragraph', text: `The Planning and Infrastructure Act 2025 requires the plan to pass what the Act calls the "overall improvement test": Natural England prepares the plan, but the Secretary of State may only formally approve it if satisfied that, by the plan's end date, the conservation measures will materially outweigh the negative effect of the development on the conservation status of each affected environmental feature.` },
    { type: 'paragraph', text: `That gives the government a stronger defence than simple offsetting, at least on paper.` },
    { type: 'paragraph', text: `But it still relies on future delivery.` },
    { type: 'paragraph', text: `Homes can be approved on the basis that Natural England's planned conservation measures are expected to outweigh their environmental impact.` },
    { type: 'paragraph', text: `The environmental benefit may arrive later.` },
    { type: 'paragraph', text: `The housing permission arrives first.` },
    { type: 'heading', level: 2, text: `The risk shifts away from the developer` },
    { type: 'paragraph', text: `That is one of the biggest changes.` },
    { type: 'paragraph', text: `Under the older system, a developer remains directly responsible for making sure its mitigation is adequate.` },
    { type: 'paragraph', text: `Under the new levy model, once the developer has met the required payment and conditions, responsibility for delivering the wider environmental programme moves to Natural England.` },
    { type: 'paragraph', text: `If the conservation work later costs more than expected, proves less effective than modelled or takes longer to deliver, the developer has already discharged the covered obligation.` },
    { type: 'paragraph', text: `That moves a significant part of the long-term risk into the public system.` },
    { type: 'paragraph', text: `The model could still work well.` },
    { type: 'paragraph', text: `Large-scale wetlands and catchment restoration may produce better ecological results than fragmented mitigation attached to individual housing sites.` },
    { type: 'paragraph', text: `But it means the quality of Natural England's costings and environmental forecasts becomes critical. The gap identified by critics between the £2,675 rate and the government's own earlier £5,400 to £60,500 modelling range is exactly the kind of discrepancy that test is meant to catch.` },
    { type: 'paragraph', text: `If the levy is too low, Natural England could be left trying to deliver an environmental promise without enough money, while a share of the pollution goes unaddressed regardless.` },
    { type: 'paragraph', text: `If it is too high, it may make development unviable.` },
    { type: 'heading', level: 2, text: `Local harm no longer has to be repaired locally` },
    { type: 'paragraph', text: `There is another change that is easy to miss.` },
    { type: 'paragraph', text: `Under a pooled system, the environmental damage caused by one development does not necessarily have to be fixed at or next to that development.` },
    { type: 'paragraph', text: `The conservation work can happen elsewhere within the wider Environmental Delivery Plan area.` },
    { type: 'paragraph', text: `That may make ecological sense.` },
    { type: 'paragraph', text: `Restoring one substantial wetland can be more effective than requiring several developers to create small, disconnected schemes.` },
    { type: 'paragraph', text: `But it also breaks the direct link between the site causing the impact and the site receiving the mitigation.` },
    { type: 'paragraph', text: `That was one of the central concerns raised when the legislation passed through Parliament. During the Commons debate on the Planning and Infrastructure Bill in June 2025, Labour MP Chris Hinchliff argued for an amendment requiring that "conservation must result in improvements to the specific feature harmed," warning that habitats and species should not be put at risk on the promise of replacement measures delivered "somewhere, later." Housing minister Dan Tomlinson countered that on-site, project-by-project mitigation had left roughly 160,000 homes stalled nationally because it was "often virtually impossible" to deliver at that scale, and that Environmental Delivery Plans offered a more workable strategic alternative.` },
    { type: 'paragraph', text: `Norfolk will now provide the first practical test of which argument holds up.` },
    { type: 'heading', level: 2, text: `£2,675 may be cheaper than the existing route` },
    { type: 'paragraph', text: `One reason the new model is attractive to developers is that it converts an uncertain liability into a predictable charge.` },
    { type: 'paragraph', text: `Under the existing system, nutrient mitigation costs can vary significantly depending on the location, nutrient burden and mitigation available.` },
    { type: 'paragraph', text: `For some developments, a flat £2,675 charge may be considerably cheaper than arranging mitigation independently, and per the consultation modelling could be a small fraction of what the government's own earlier calculations suggested some sites might otherwise require.` },
    { type: 'paragraph', text: `That is not an accidental side effect.` },
    { type: 'paragraph', text: `The government wants environmental compliance to become simpler and more predictable so homes do not remain trapped in planning because a developer cannot find an acceptable mitigation scheme.` },
    { type: 'paragraph', text: `But it also means the levy needs to be scrutinised closely.` },
    { type: 'paragraph', text: `If developers obtain a much cheaper route through an environmental constraint, the public needs confidence that the lower private cost has not simply shifted the real cost elsewhere, which is precisely what the CIEEM and WildFish critiques argue is happening.` },
    { type: 'heading', level: 2, text: `Natural England will wear several hats` },
    { type: 'paragraph', text: `Natural England will be central to the system.` },
    { type: 'paragraph', text: `It prepares the Environmental Delivery Plan.` },
    { type: 'paragraph', text: `It identifies the conservation work required.` },
    { type: 'paragraph', text: `It helps calculate the levy.` },
    { type: 'paragraph', text: `It receives the payments.` },
    { type: 'paragraph', text: `And it is responsible for arranging delivery of the environmental programme.` },
    { type: 'paragraph', text: `The Secretary of State has to formally approve the plan against the overall improvement test, so Natural England does not have the final legal say over its own proposal.` },
    { type: 'paragraph', text: `Even so, a great deal of responsibility is concentrated in one public body.` },
    { type: 'paragraph', text: `Its modelling will determine how much developers pay and how much conservation work the public system later has to deliver.` },
    { type: 'paragraph', text: `That makes transparency around the calculations important.` },
    { type: 'paragraph', text: `The public should be able to see how the £2,675 figure was reached, what assumptions sit behind it, why it landed at the low end of the government's own earlier £5,400 to £60,500 range, and what happens if costs rise.` },
    { type: 'heading', level: 2, text: `"Unlocked" does not mean built` },
    { type: 'paragraph', text: `The government's language also needs care.` },
    { type: 'paragraph', text: `The announcement says the scheme could unlock more than 15,000 homes.` },
    { type: 'paragraph', text: `That does not mean 15,780 homes will be built.` },
    { type: 'paragraph', text: `It means one major planning obstacle could be removed for developments affected by nutrient rules.` },
    { type: 'paragraph', text: `The homes would still need planning permission, finance, infrastructure and developers willing to build them.` },
    { type: 'paragraph', text: `This distinction matters because "homes unlocked" has become a recurring government metric.` },
    { type: 'paragraph', text: `It is an easier number to announce than completions.` },
    { type: 'paragraph', text: `Norfolk has already received previous nutrient-mitigation funding. In November 2024, the government announced £47 million nationally to unlock 28,000 nutrient-neutrality-stalled homes across seven affected areas, with the single largest allocation, £8.8 million, going to the Norfolk Broads and River Wensum catchment specifically, aimed at unlocking more than 5,000 homes there.` },
    { type: 'paragraph', text: `Before treating the new 15,780 figure as delivery, it would be worth establishing how many of those earlier 5,000 Norfolk homes were actually started or completed and what happened to the £8.8 million.` },
    { type: 'paragraph', text: `That is a cleaner measure of whether these interventions turn announcements into houses.` },
    { type: 'heading', level: 2, text: `Norfolk is only the first test` },
    { type: 'paragraph', text: `This is not a one-off local scheme.` },
    { type: 'paragraph', text: `Natural England is preparing further Environmental Delivery Plans elsewhere, covering nutrient pollution and other protected environmental features.` },
    { type: 'paragraph', text: `The Norfolk plan is effectively the prototype.` },
    { type: 'paragraph', text: `If it works, the government will have created a route by which developers across England can increasingly pay a standard levy rather than resolving some environmental impacts development by development.` },
    { type: 'paragraph', text: `That could speed up planning substantially.` },
    { type: 'paragraph', text: `It could also shift more environmental responsibility from developers to Natural England.` },
    { type: 'paragraph', text: `The success of the model will depend on something much less glamorous than the announcement.` },
    { type: 'paragraph', text: `Whether the levy is priced correctly. The gap between £2,675 and the government's own earlier modelling suggests that question is already live, not hypothetical.` },
    { type: 'paragraph', text: `Whether the conservation work happens.` },
    { type: 'paragraph', text: `Whether the promised ecological improvement materialises.` },
    { type: 'paragraph', text: `And whether the homes described as "unlocked" are actually built.` },
    { type: 'paragraph', text: `The government has made the planning problem easier to price.` },
    { type: 'paragraph', text: `It has not yet proved that it has made the environmental problem easier to solve.` },
  ],
  evidence: {
    recordsReviewed: [
      'GOV.UK, 17 September 2026: "Government unveils plans to unlock over 15,000 new homes" — 15,780-home figure, geographic scope (River Wensum, Bure Broads and Marshes, Yare Broads and Marshes catchments), Natural England\'s role administering the fund',
      'GOV.UK, "Understanding the Nature Restoration Fund" guidance — how the levy commitment process works; confirmation that local planning authorities are relieved of appropriate assessment for impacts the EDP covers, while other effects and legislation still apply',
      'GOV.UK, Environmental Delivery Plans collection page — "overall improvement test" description; further EDPs in preparation beyond Norfolk',
      'Planning and Infrastructure Act 2025, Part 3 (Section 65) — Natural England prepares and submits the EDP; only the Secretary of State may make it; approval requires satisfaction that conservation measures will "materially outweigh" the development\'s negative effect on each identified environmental feature by the plan\'s end date',
      'Hansard, Planning and Infrastructure Bill debate, House of Commons, 9 June 2025 — Hinchliff amendment requiring conservation improvements to address the specific harmed feature; Tomlinson response citing ~160,000 homes stalled nationally and on-site mitigation described as "often virtually impossible"',
      'GOV.UK, "£47 million to unlock 28,000 nutrient neutrality stalled homes," 7 November 2024 — previous Norfolk Broads/River Wensum allocation: £8.8 million to unlock more than 5,000 homes, part of £47 million national package across seven areas',
      'planninggeek.co.uk and PA/AOL reporting on the published Norfolk levy consultation — £5,400 to £60,500 per-house modelling range considered before the £2,675 rate was set; CIEEM (Sally Hayns: "very conservative," minimal contingency, no source-avoidance provision) and WildFish (Dr Justin Neal: "full of holes," "pay to pollute") criticism; 7,695kg nitrogen/435kg phosphorus per-year figures cited by campaigners',
    ],
    lastChecked: '30 September 2026',
  },
};

export default piece;
