import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'wq7m4kx2np',
  kicker: 'Commentary',
  headline: `Digital ID Will Be Voluntary. Parliament Has Already Warned About Function Creep`,
  standfirst: `The government's digital ID will be voluntary. That is not merely ministerial reassurance — the consultation document says so explicitly. But voluntary in law is not the same as voluntary in practice. Parliament's Home Affairs Committee has already warned about function creep and recommended that future expansions require statutory scrutiny. The government has not yet said which protections will end up in legislation.`,
  publishedAt: '2026-07-17',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `The government's digital ID will be voluntary.` },
    { type: 'paragraph', text: `That is not merely ministerial reassurance. The consultation document published in March says there will be "no legal obligation for people to have or present the digital ID."` },
    { type: 'paragraph', text: `That is a significant change from where the policy started.` },
    { type: 'paragraph', text: `When Keir Starmer announced digital ID in September 2025, the government said it would become mandatory for right-to-work checks by the end of the Parliament. The Prime Minister said people would not be able to work legally in Britain without it.` },
    { type: 'paragraph', text: `Ministers retreated in January.` },
    { type: 'paragraph', text: `The government-issued ID itself would no longer be compulsory. Instead, the government said employers would eventually have to carry out right-to-work checks digitally, while workers could prove their entitlement through other approved digital routes.` },
    { type: 'paragraph', text: `The distinction is real.` },
    { type: 'paragraph', text: `It is also why the word "voluntary" deserves closer attention.` },
    { type: 'paragraph', text: `A voluntary identity system does not have to become compulsory in law to become difficult to avoid in practice.` },
    { type: 'paragraph', text: `That concern is not confined to campaigners opposed to digital ID. Parliament's Home Affairs Committee raised essentially the same problem in May.` },
    { type: 'paragraph', text: `Its report warned about "function creep", where a system introduced for one purpose gradually acquires others. More than 3,000 submissions from members of the public raised concerns about the issue. The committee recommended that significant future expansions of digital ID should require parliamentary scrutiny and, at minimum, the affirmative statutory instrument procedure.` },
    { type: 'paragraph', text: `The government itself envisages the ID being used much more widely than employment checks.` },
    { type: 'paragraph', text: `Its consultation says the system should sit at the heart of future digital public services and be usable across the wider economy. Examples include dealing with government departments, proving identity to landlords, accessing benefits and potentially making transactions with private companies easier.` },
    { type: 'paragraph', text: `The proposed ID would normally sit on a compatible phone or tablet.` },
    { type: 'paragraph', text: `The government's current design envisages it containing a person's name, date of birth, photograph and nationality. It would be capable of revealing limited attributes rather than the whole record. A business checking someone's age might receive confirmation only that they are over 18. An employer could receive confirmation that somebody has the right to work without being shown their full nationality or date of birth.` },
    { type: 'paragraph', text: `That is considerably better than requiring people to hand over a full passport every time somebody wants to know one fact about them.` },
    { type: 'paragraph', text: `It also illustrates why the system could become attractive very quickly.` },
    { type: 'paragraph', text: `If a government digital credential allows somebody to prove their age in seconds, prove their right to work without finding documents and establish their identity to a landlord through the same app, businesses and public bodies will have every incentive to use it.` },
    { type: 'paragraph', text: `Nothing improper has to happen.` },
    { type: 'paragraph', text: `Nobody has to announce that the ID is compulsory.` },
    { type: 'paragraph', text: `The digital route merely has to become cheaper, faster and easier for the organisation asking for proof.` },
    { type: 'paragraph', text: `The danger comes if the alternative remains legal but becomes progressively worse.` },
    { type: 'paragraph', text: `The government's consultation recognises this problem, although it has not yet settled the answer.` },
    { type: 'paragraph', text: `Its standard route requires a compatible device and connectivity. Ministers are considering alternatives for people who cannot use one, but the consultation says even those routes would have to involve a digitised check. A physical card that could only be inspected visually would not qualify as the alternative being considered.` },
    { type: 'paragraph', text: `That deserves more attention than it has received.` },
    { type: 'paragraph', text: `There is an important difference between saying nobody must have the government app and guaranteeing that somebody without a suitable phone, reliable internet connection or confidence using digital services can obtain the same service just as easily.` },
    { type: 'paragraph', text: `The Home Affairs Committee found that the government had not yet explained in detail how support would work for people affected by digital exclusion. It identified people with poor connectivity, limited digital skills and other barriers as groups at risk.` },
    { type: 'paragraph', text: `The government says inclusion will be designed into the scheme.` },
    { type: 'paragraph', text: `That should be judged when the alternative routes actually exist.` },
    { type: 'paragraph', text: `There is a second issue: what the ID eventually becomes useful for.` },
    { type: 'paragraph', text: `The government has good answers to some of the more alarming claims circulating about the scheme.` },
    { type: 'paragraph', text: `It says it does not intend to create one giant central database containing everybody's information. The current proposal is for a federated model in which information continues to be held by the relevant departments and is linked when necessary. Ministers say only the minimum data should be collected and shared.` },
    { type: 'paragraph', text: `The consultation also says police will receive no new power to demand a person's digital ID during an ordinary stop and search. Britain will retain its general rule that people do not have to carry identification.` },
    { type: 'paragraph', text: `Those are meaningful protections.` },
    { type: 'paragraph', text: `They are also still being designed.` },
    { type: 'paragraph', text: `The public consultation closed on 5 May. A second stage, a People's Panel examining the proposals in greater detail, concluded on 21 June, which the Cabinet Office described as the end of the formal consultation process. As of 17 July, the government had not published its final response setting out which proposals it intended to legislate for.` },
    { type: 'paragraph', text: `The important question is therefore not whether the present consultation contains safeguards.` },
    { type: 'paragraph', text: `It does.` },
    { type: 'paragraph', text: `The question is which of them end up in legislation and how difficult they are for a future government to weaken.` },
    { type: 'paragraph', text: `The Home Affairs Committee reached much the same conclusion.` },
    { type: 'paragraph', text: `It welcomed the government's recognition that expansion should be subject to parliamentary control, but recommended writing those protections into the forthcoming legislation so future uses could not simply be added without proper scrutiny.` },
    { type: 'paragraph', text: `That is where the real argument over "voluntary" sits.` },
    { type: 'paragraph', text: `A promise from one minister lasts until another minister changes it.` },
    { type: 'paragraph', text: `A statutory restriction has to be changed in Parliament.` },
    { type: 'paragraph', text: `The debate becomes more complicated when children enter the picture.` },
    { type: 'paragraph', text: `The government announced in June that major social-media services would be barred from providing their services to under-16s from spring 2027.` },
    { type: 'paragraph', text: `That inevitably requires some form of age assurance. A platform cannot reliably exclude 15-year-olds while admitting 16-year-olds merely by asking everyone to type in a birthday.` },
    { type: 'paragraph', text: `There are already several ways to perform stronger checks.` },
    { type: 'paragraph', text: `Ofcom regards methods including facial age estimation, photo-ID matching, mobile-network checks, credit cards, open banking and digital identity services as potentially capable of providing highly effective age assurance. No single method is compulsory.` },
    { type: 'paragraph', text: `The government's national digital ID could technically perform the same job. Its own proposed design allows it to reveal that somebody meets an age threshold without revealing their full date of birth.` },
    { type: 'paragraph', text: `But the evidence does not support saying teenagers are being pushed towards the government ID.` },
    { type: 'paragraph', text: `A parliamentary answer published three days ago addressed that exact question.` },
    { type: 'paragraph', text: `Asked whether the new digital ID would be used for age verification under the under-16 social-media restrictions, science minister Kanishka Narayan said Ofcom was still assessing the available methods and that the government was considering a range of options.` },
    { type: 'paragraph', text: `He added: "Any use of digital identity services would remain voluntary."` },
    { type: 'paragraph', text: `That should be included because it cuts against the strongest version of the argument.` },
    { type: 'paragraph', text: `The government's ID might eventually become one convenient method of proving age online. It is not currently the only method, the government has not announced that platforms must use it, and Ofcom already recognises several alternatives.` },
    { type: 'paragraph', text: `The legitimate question is what happens if one method becomes dominant because it is easier for platforms, users and regulators.` },
    { type: 'paragraph', text: `That is not inevitable. It is a risk worth designing against.` },
    { type: 'paragraph', text: `There is a similar temptation to overstate the security argument.` },
    { type: 'paragraph', text: `Any national identity system presents an attractive target for criminals and hostile states. The Home Affairs Committee heard substantial concern about government data security and cited earlier government data breaches and past concerns about GOV.UK One Login.` },
    { type: 'paragraph', text: `But the proposed system is not simply a central database containing everyone's identity waiting to be stolen.` },
    { type: 'paragraph', text: `The government's design instead proposes credentials held primarily on people's devices, minimum disclosure of information and records continuing to be maintained by the departments responsible for them.` },
    { type: 'paragraph', text: `That reduces some risks. It does not remove them.` },
    { type: 'paragraph', text: `Deleting the ID from a phone, for example, would not delete the underlying records held by government departments. The consultation explicitly says those would remain subject to the departments' normal retention policies.` },
    { type: 'paragraph', text: `Government also acknowledges that law-enforcement and intelligence agencies can already obtain access to some personal data where existing legislation permits it. The digital ID would sit within those existing legal frameworks rather than behind an absolute wall preventing state access.` },
    { type: 'paragraph', text: `None of that makes digital ID inherently sinister.` },
    { type: 'paragraph', text: `There are obvious advantages.` },
    { type: 'paragraph', text: `People who currently struggle to prove who they are may benefit from a free identity credential. Selective disclosure is preferable to repeatedly handing businesses copies of passports and utility bills. Digital right-to-work checks may reduce forged-document fraud. A system that stops people spending hours proving the same facts to different government departments could genuinely improve public services.` },
    { type: 'paragraph', text: `The Home Affairs Committee recognised those possible benefits even while criticising the way the policy was originally announced.` },
    { type: 'paragraph', text: `Its conclusion was unusually blunt. The first announcement had been rushed and poorly thought through. The government had improved the proposal by dropping mandatory national ID, engaging more widely and consulting the public.` },
    { type: 'paragraph', text: `That history is exactly why the remaining protections matter.` },
    { type: 'paragraph', text: `The original version was compulsory for employment.` },
    { type: 'paragraph', text: `Four months later, it was not.` },
    { type: 'paragraph', text: `A policy capable of changing that substantially in one direction can change substantially in the other.` },
    { type: 'paragraph', text: `"Voluntary" should therefore mean more than the absence of a legal requirement to download an app.` },
    { type: 'paragraph', text: `It should mean that somebody who chooses not to use it can still work, rent a home, deal with government and prove their age through realistic alternatives without paying a penalty in time, cost or access.` },
    { type: 'paragraph', text: `Future governments should not be able to add major new uses quietly.` },
    { type: 'paragraph', text: `The government says it agrees with the principle of parliamentary oversight. Parliament's Home Affairs Committee has recommended putting that safeguard into legislation.` },
    { type: 'paragraph', text: `That is where the promise should end up.` },
    { type: 'paragraph', text: `Not in a minister's press release.` },
    { type: 'paragraph', text: `In law.` },
  ],
  evidence: {
    recordsReviewed: [
      `Cabinet Office, Making public services work for you with your digital identity, March 2026: sets out the proposed national digital ID, its voluntary status, information it could contain, selective disclosure, alternative access routes, privacy and security proposals and possible use across public services and the wider economy; records the public consultation's 5 May 2026 close and the subsequent People's Panel concluding 21 June 2026, described by the Cabinet Office as the end of the formal consultation process`,
      `Prime Minister's Office, New digital ID scheme to be rolled out across UK, 26 September 2025: records the original commitment that digital ID would be mandatory for right-to-work checks`,
      `House of Commons Home Affairs Committee, Mandatory to manageable: the government's plans for digital ID, 20 May 2026: records the January reversal of mandatory government digital ID, examines data security and digital exclusion, identifies concerns about function creep and recommends parliamentary approval for significant future expansion`,
      `Department for Science, Innovation and Technology, Written Question 16720, answered 14 July 2026: Kanishka Narayan states that Ofcom is assessing age-assurance methods for the under-16 social-media restrictions and that any use of digital identity services would remain voluntary`,
      `Department for Science, Innovation and Technology, Social media to be banned for under-16s, 15 June 2026: establishes the proposed under-16 restriction and expected spring 2027 implementation`,
      `Ofcom, age-assurance guidance: identifies methods potentially capable of highly effective age assurance, including facial age estimation, photo-ID matching, open banking, mobile-network checks and digital identity services`,
    ],
    lastChecked: '5 October 2026',
  },
};

export default piece;
