import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'x7m3k9wq2n',
  kicker: 'Social Policy',
  headline: `The State Now Accepts Responsibility for Forced Adoption. Its £4m Package Includes No Compensation`,
  standfirst: `Keir Starmer apologised on behalf of the state on 2 July to mothers, adopted people and families harmed by historical forced adoption practices in England. The apology came with £4 million of support over three years. It did not include individual financial compensation.`,
  publishedAt: '2026-07-06',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `Keir Starmer apologised on behalf of the state on 2 July to mothers, adopted people and families harmed by historical forced adoption practices in England.` },
    { type: 'paragraph', text: `The apology came with £4 million of support over three years for adoption records, family-reconnection services, peer support, health care and research.` },
    { type: 'paragraph', text: `It did not include individual financial compensation.` },
    { type: 'paragraph', text: `The more striking change is what the government now says the state was responsible for.` },
    { type: 'paragraph', text: `When the Joint Committee on Human Rights called for a formal apology in 2022, the Conservative government refused. Its response, published in March 2023, said an official government apology would not be appropriate because "the state did not actively support these practices."` },
    { type: 'paragraph', text: `It apologised instead "on behalf of society".` },
    { type: 'paragraph', text: `Three years later, Starmer used almost the opposite formulation.` },
    { type: 'paragraph', text: `He told the Commons that governments had funded, enabled and relied on systems that were not consistently or effectively overseen. He said:` },
    { type: 'paragraph', text: `"The State bears responsibility for the systems it funded and legitimised."` },
    { type: 'paragraph', text: `He apologised for what he called a systemic failure to protect mothers, children and families.` },
    { type: 'paragraph', text: `That change is supported by the parliamentary evidence gathered since the previous government rejected responsibility.` },
    { type: 'paragraph', text: `The Education Committee concluded in March that government policy, funding arrangements and legislation helped create an environment in which unmarried mothers were routinely denied meaningful choice about whether they could keep their children. Religious organisations, charities, hospitals, doctors, adoption agencies, councils and families also played roles. The committee did not suggest there was one institution responsible for every adoption.` },
    { type: 'paragraph', text: `The numbers require the same caution.` },
    { type: 'paragraph', text: `The Education Committee used an estimate of around 185,000 children adopted between 1949 and 1976 to indicate the scale of the issue, while explicitly warning that not all those adoptions took place in the circumstances described by survivors. Some children were orphaned and experiences differed considerably.` },
    { type: 'paragraph', text: `The earlier Joint Committee on Human Rights was more precise about the uncertainty. It found that roughly half a million adoptions of all types took place in England and Wales during the period and said it was difficult to establish how many babies of unmarried mothers were adopted by new families. The 185,000 figure was the closest estimate it could establish from the available records, rather than a verified count of forced adoptions.` },
    { type: 'paragraph', text: `Nor did coercive practices fit neatly within those dates.` },
    { type: 'paragraph', text: `The Education Committee heard evidence that they occurred before 1949 and continued after the Adoption Act 1976. It said the government's apology should recognise people whose experiences fell outside the conventional period. The government has done so, saying it recognises that some cases extended beyond 1949 to 1976.` },
    { type: 'paragraph', text: `The practical package announced with the apology deals with several problems survivors have repeatedly raised.` },
    { type: 'paragraph', text: `The government will fund a national online resource to help people locate adoption records. It will consult on requiring existing historical adoption records to be retained for at least 100 years. The Education Secretary has written to councils, regional adoption agencies and voluntary agencies telling them that requests should be handled promptly and consistently.` },
    { type: 'paragraph', text: `Funding will also expand intermediary services used to reconnect families, establish national peer-led support groups and improve NHS understanding of the effects of forced adoption. NHS England will consider how people who want to do so could have their experience recorded appropriately in their health records. A testimonial project will document survivors' experiences.` },
    { type: 'paragraph', text: `Those measures respond directly to evidence Parliament has heard.` },
    { type: 'paragraph', text: `The 2022 inquiry recorded adoptees spending years trying to obtain information about their own births and adoptions. The Education Committee heard similar evidence this year, including accounts of files being inaccessible, extensively redacted or taking years to retrieve.` },
    { type: 'paragraph', text: `The £4 million should therefore not be dismissed as an accompaniment to the apology with no practical purpose.` },
    { type: 'paragraph', text: `It is also not compensation.` },
    { type: 'paragraph', text: `The Education Committee did not recommend a specific UK compensation scheme in March. It went further than simply asking for counselling and records, however.` },
    { type: 'paragraph', text: `It told the government to examine the responses adopted elsewhere, with particular attention to redress mechanisms in Australia, Northern Ireland and the Republic of Ireland, and said that work should produce a comprehensive and fully resourced response rather than symbolic or incomplete action.` },
    { type: 'paragraph', text: `Ireland has legislated for a Mother and Baby Institutions Payment Scheme providing financial redress and health support to eligible survivors. Northern Ireland's Truth Recovery Design Panel recommended an immediate redress payment scheme alongside an inquiry, records access and specialist support. The Education Committee cited both when considering what England should learn from other jurisdictions.` },
    { type: 'paragraph', text: `The government has not announced an equivalent individual payment scheme for England.` },
    { type: 'paragraph', text: `That does not mean it promised one and then failed to deliver it. Parliament's committee called for meaningful redress and examination of international models, not a specified compensation tariff.` },
    { type: 'paragraph', text: `It does mean that the government's present answer to the harm it has now accepted responsibility for consists of an apology and £4 million of collective support rather than financial payments to individuals.` },
    { type: 'paragraph', text: `The Church of England is in a different position.` },
    { type: 'paragraph', text: `On 18 June, Archbishop of Canterbury Sarah Mullally apologised for the Church's role in historical adoption practices. Research published with the apology concluded that the Church had been involved with potentially more than 200 mother and baby homes over time and estimated that tens of thousands of mothers and babies may have been connected to Church-affiliated homes. The Church cautioned that incomplete records prevent a precise total.` },
    { type: 'paragraph', text: `The Church is separately establishing a redress scheme for survivors of Church-related abuse. Its proposed financial framework ranges from £5,000 to £660,000 in rare and exceptional cases. That scheme was developed for Church-related abuse generally, not as an automatic compensation programme for everybody affected by historical adoption. Eligibility depends on whether an applicant meets the scheme's criteria.` },
    { type: 'paragraph', text: `Scotland and Wales had already apologised before Westminster.` },
    { type: 'paragraph', text: `Nicola Sturgeon issued Scotland's formal apology in March 2023. The Welsh Government followed with an apology on its behalf in April that year. Both recognised the continuing effects of historical adoption practices.` },
    { type: 'paragraph', text: `England took another three years.` },
    { type: 'paragraph', text: `Helen Hayes, chair of the Education Committee, called Starmer's apology an important milestone but said it was "only a first step" and promised further scrutiny of the support provided to survivors.` },
    { type: 'paragraph', text: `For years, the dispute was partly about whether the state should accept responsibility at all.` },
    { type: 'paragraph', text: `In 2023, the government's position was that it had not actively supported the practices and that an apology should instead be offered on behalf of society.` },
    { type: 'paragraph', text: `In 2026, the Prime Minister accepted that governments funded and legitimised systems in which the harm occurred.` },
    { type: 'paragraph', text: `The state has changed the official record.` },
    { type: 'paragraph', text: `Its current financial commitment is £4 million for records, services, health support and research.` },
    { type: 'paragraph', text: `No individual compensation scheme has been announced.` },
  ],
  evidence: {
    recordsReviewed: [
      `Prime Minister's Office, Prime Minister's statement in the House on historic forced adoption, 2 July 2026: records the formal apology, the acknowledgement that the state funded and legitimised the systems in which harm occurred, and the measures on records, intermediary services, peer support and health care`,
      `Department for Education, Government apologises for historic forced adoption practices, 2 July 2026: confirms the £4 million package over three years and sets out how the funding will be used`,
      `Joint Committee on Human Rights, The Violation of Family Life: Adoption of Children of Unmarried Women 1949–1976, 15 July 2022: documents coercion, institutional involvement, problems accessing records and the committee's original recommendation for a formal government apology; also explains the uncertainty surrounding the commonly cited 185,000 figure`,
      `UK Government response to the Joint Committee on Human Rights, 3 March 2023: records the previous government's refusal to issue a formal apology on the grounds that "the state did not actively support these practices", while apologising on behalf of society`,
      `House of Commons Education Committee, Historical Forced Adoption, 27 March 2026: finds systemic coercion and removal of parental choice, identifies the state's role through policy, funding and legislation, warns against treating every adoption within the period as forced, and recommends examination of international redress mechanisms`,
      `Education Committee, statement by Chair Helen Hayes MP, 2 July 2026: welcomes the apology while describing it as only a first step and commits the committee to scrutinising subsequent support`,
      `Church of England, historical adoption apology and research, 18 June 2026: records the Church's apology, its involvement with potentially more than 200 mother and baby homes over time and its estimate that tens of thousands of mothers and babies were connected to Church-affiliated homes`,
      `Church of England, National Redress Scheme: proposed financial award framework, 25 April 2024: sets out the separate proposed financial framework for eligible survivors of Church-related abuse, ranging from £5,000 to £660,000 in rare and exceptional cases`,
      `Welsh Government and Scottish Government material on historical forced adoption, 2023: records the formal apologies issued in Wales and Scotland before the UK Government's apology for practices in England`,
    ],
    lastChecked: '5 October 2026',
  },
};

export default piece;
