import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'xf4k9mxw7r',
  kicker: 'Environment',
  headline: `Ten Years After Salmon Recovery Plan Launched, 95% of England's Principal Rivers Are Still at Risk`,
  standfirst: `Ten years after the Environment Agency launched a national programme to restore England's salmon stocks, 40 of the country's 42 principal salmon rivers are now classified as at risk or probably at risk of failing to sustain their populations. That is 95 per cent, up from 88 per cent in the previous assessment and the worst position recorded. The Environment Agency has set out another long-term programme running to 2032.`,
  publishedAt: '2026-09-16',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `Ten years after the Environment Agency launched a national programme to restore England's salmon stocks, 40 of the country's 42 principal salmon rivers are now classified as at risk or probably at risk of failing to sustain their populations.` },
    { type: 'paragraph', text: `That is 95 per cent, up from 88 per cent in the previous assessment and the worst position recorded.` },
    { type: 'paragraph', text: `The decline cannot be attributed to English river management alone.` },
    { type: 'paragraph', text: `Atlantic salmon populations are falling across much of the North Atlantic. The Environment Agency says marine survival has deteriorated sharply: where 15 to 20 young salmon out of every 100 going to sea might once have returned as adults, the figure can now be as low as one or two. Climate change, changing ocean conditions, aquaculture, bycatch and other marine pressures affect salmon beyond the reach of any single government.` },
    { type: 'paragraph', text: `But salmon also spend important parts of their lives in English rivers, where the Environment Agency has direct regulatory responsibilities. Its latest assessment again identifies pollution, insufficient flows and barriers to migration among the main freshwater pressures.` },
    { type: 'paragraph', text: `Those problems were already at the centre of the Salmon Five Point Approach, launched in May 2016 by the Environment Agency, Defra, Cefas and conservation and fisheries groups.` },
    { type: 'paragraph', text: `The programme committed them to improving marine survival, reducing exploitation by fishing, removing migration barriers and restoring habitat, safeguarding river flows and improving water quality for spawning. Its stated aim was to restore the abundance, diversity and resilience of salmon stocks across England.` },
    { type: 'paragraph', text: `The stock data continued to deteriorate during and after that programme.` },
    { type: 'paragraph', text: `In 2006, 40 per cent of England's principal salmon rivers were classed as either not at risk or probably not at risk. By 2015 that figure was 19 per cent. In 2020 it was 12 per cent.` },
    { type: 'paragraph', text: `The five-point programme formally ended in 2021. Government stock-assessment documents published afterwards said a successor was still being developed. Related work continued through Environment Agency programmes and the UK's commitments to the North Atlantic Salmon Conservation Organisation.` },
    { type: 'paragraph', text: `The Environment Agency can point to substantial work completed during that period.` },
    { type: 'paragraph', text: `By the time the five-point approach was launched, 82 barriers had already been removed or altered since 2009, opening 5,767km of river catchment, and 77 unsustainable abstraction licences on salmon rivers had been removed or reduced since 2008. Early work under the programme added habitat, water-quality and fish-passage projects.` },
    { type: 'paragraph', text: `Later schemes included new fish passes, water-company improvement projects and tighter restrictions on salmon fishing. In 2021 alone, the Environment Agency said 53 water-industry schemes had been completed that would benefit salmon, while new fish-passage projects were restoring access to substantial stretches of river.` },
    { type: 'paragraph', text: `There are also places where intervention has produced visible improvements.` },
    { type: 'paragraph', text: `The Environment Agency points to the Trent and Ouse, where better water quality and fish passage have helped salmon return. On the River Don, restoration and removal of migration barriers have reopened habitat that salmon had not reached for generations. More recent projects on the Kent, Ribble and Lemon have restored habitat, planted riverside trees and removed obstacles to migration.` },
    { type: 'paragraph', text: `Those local results sit beside a worsening national assessment.` },
    { type: 'paragraph', text: `The latest data classifies 95 per cent of principal English salmon rivers in the two risk categories. The previous year's figure was 88 per cent.` },
    { type: 'paragraph', text: `The Environment Agency has now set out another long-term programme, running from 2026 to 2032.` },
    { type: 'paragraph', text: `It says it will restore 2,282 hectares of peatland, fund more than 800 projects to reduce wastewater pollution, remove or improve 105 migration barriers, restore habitat at 252 sites and plant trees along 648 hectares of riverbank. The programme also includes work on river flows, farm inspections, wastewater treatment and abstraction.` },
    { type: 'paragraph', text: `Much of that programme addresses the same freshwater pressures identified in 2016.` },
    { type: 'paragraph', text: `The Environment Agency itself says salmon recovery takes years because juveniles may spend up to three years in rivers and another one or two at sea before returning to spawn. Improvements made today therefore cannot be expected to appear immediately in adult salmon numbers.` },
    { type: 'paragraph', text: `That lag makes project counts a poor substitute for measuring the eventual population outcome.` },
    { type: 'paragraph', text: `The previous decade produced barriers removed, kilometres of river reopened, abstraction licences changed, pollution schemes completed and fishing restrictions tightened. The national stock assessment nevertheless continued to worsen.` },
    { type: 'paragraph', text: `The statistical publication behind those assessments is also undergoing scrutiny.` },
    { type: 'paragraph', text: `In May, the Office for Statistics Regulation found that the salmon-stock reports were not currently published as official statistics. It said parts of the Code of Practice relating to orderly release and accessibility were not being met and recommended that the Environment Agency, Cefas and Natural Resources Wales formally evaluate whether the assessments should receive official-statistics status.` },
    { type: 'paragraph', text: `The regulator did not say the stock figures were wrong. It said the producers should improve governance, transparency, accessibility and communication around planned changes to the methodology.` },
    { type: 'paragraph', text: `The 2025 assessment itself was first published on 15 September and replaced the following day because the original attachment contained errors. Further amendments were made on 29 September to a figure and accompanying text concerning fishing licences.` },
    { type: 'paragraph', text: `The new recovery programme gives the Environment Agency measurable outputs through to 2032: hectares restored, barriers altered, pollution projects completed and riverbanks planted.` },
    { type: 'paragraph', text: `The older programme produced many of those outputs too.` },
    { type: 'paragraph', text: `The national result now being reported is that 40 of England's 42 principal salmon rivers remain at risk or probably at risk of failing to sustain their salmon populations.` },
  ],
  evidence: {
    recordsReviewed: [
      `Environment Agency, Cefas and Natural Resources Wales, "Salmon numbers in England hit lowest level on record", 16 September 2026: the 95 per cent figure, comparison with 88 per cent the previous year, marine survival estimates, domestic freshwater pressures and the 2026 to 2032 recovery commitments`,
      `Environment Agency, "England's salmon stocks: what the latest data tells us", 17 September 2026: the 40-of-42 river figure, freshwater and marine pressures, salmon lifecycle, local recovery examples and detailed 2032 programme commitments`,
      `Environment Agency, "Restoring salmon stocks: our journey to a new approach", 6 May 2016: launch and five elements of the Salmon Five Point Approach and earlier barrier-removal and abstraction work`,
      `Assessment of Salmon Stocks and Fisheries in England and Wales, background reports: confirmation that the Salmon Five Point Approach ended in 2021 and that a successor remained in development in subsequent reporting`,
      `Environment Agency, Salmonid and freshwater fisheries statistics: historical risk classifications showing 40 per cent of English rivers in the two healthier categories in 2006, 19 per cent in 2015 and 12 per cent in 2020`,
      `Office for Statistics Regulation, Review of Assessment of Salmon Stocks and Fisheries Statistics, 18 May 2026: status of the publication outside official statistics and recommendations on governance, release practices, accessibility and methodology transparency`,
      `Cefas, Environment Agency and Natural Resources Wales, "Assessment of salmon stocks in England and Wales in 2025": publication and correction history of the latest assessment`,
    ],
    lastChecked: '3 October 2026',
  },
};

export default piece;
