import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'xf4k9mxw7r',
  kicker: 'Environment',
  headline: `After a Decade of Recovery Plans, 95% of England's Salmon Rivers Are Still Below Sustainable Levels`,
  standfirst: `Ninety-five per cent of England's principal salmon rivers are below sustainable stock levels, up from 88 per cent the year before. The Environment Agency launched a five-point national salmon recovery strategy a decade ago. The same domestic pressures it identified then remain at the centre of the new plan running to 2032.`,
  publishedAt: '2026-09-16',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `Ninety-five per cent of England's principal salmon rivers are now below sustainable stock levels, despite a decade of national recovery plans targeting pollution, low flows, migration barriers and damaged habitat.` },
    { type: 'paragraph', text: `That figure has deteriorated sharply even in the space of a year: the Environment Agency's own assessment put the proportion at 88 per cent just twelve months earlier.` },
    { type: 'paragraph', text: `The government points to worsening survival at sea, climate change and wider North Atlantic pressures.` },
    { type: 'paragraph', text: `Those are real factors.` },
    { type: 'paragraph', text: `But they do not remove the domestic accountability question.` },
    { type: 'paragraph', text: `The Environment Agency launched a national five-point salmon recovery strategy in 2016.` },
    { type: 'paragraph', text: `Ten years later, the national position has deteriorated.` },
    { type: 'heading', level: 2, text: `The same problems were identified a decade ago` },
    { type: 'paragraph', text: `The Environment Agency's 2016 Salmon Five Point Approach focused on five areas: reducing exploitation; improving marine survival; removing barriers; protecting river flows; and improving spawning habitat and water quality.` },
    { type: 'paragraph', text: `Those are broadly the same pressures the agency identifies today.` },
    { type: 'paragraph', text: `Its latest assessment points again to pollution, insufficient river flows, physical barriers and damaged habitat as major freshwater problems.` },
    { type: 'paragraph', text: `That makes the latest announcement more than a wildlife story.` },
    { type: 'paragraph', text: `It is also a test of whether a decade of policy has worked.` },
    { type: 'heading', level: 2, text: `The decline has been long and steady` },
    { type: 'paragraph', text: `The national trend is stark.` },
    { type: 'paragraph', text: `In 2006, 40 per cent of England's principal salmon rivers were in the two healthier categories, either "not at risk" or "probably not at risk".` },
    { type: 'paragraph', text: `By 2015, that had fallen to 19 per cent.` },
    { type: 'paragraph', text: `By 2020, it was 12 per cent.` },
    { type: 'paragraph', text: `The latest assessment puts 95 per cent of principal rivers below the level needed for long-term sustainability, up from 88 per cent in the previous year's assessment alone.` },
    { type: 'paragraph', text: `This is not one bad season.` },
    { type: 'paragraph', text: `It is a long-term deterioration that has recently accelerated.` },
    { type: 'heading', level: 2, text: `The sea is a major part of the problem` },
    { type: 'paragraph', text: `The government is right to stress that salmon decline is not confined to England.` },
    { type: 'paragraph', text: `Historically, roughly 15 to 20 salmon out of every 100 juveniles going to sea could be expected to return as adults.` },
    { type: 'paragraph', text: `The Environment Agency says that figure can now be as low as one or two.` },
    { type: 'paragraph', text: `Climate change, changing ocean conditions, bycatch and other marine pressures have reduced survival across the North Atlantic.` },
    { type: 'paragraph', text: `That means it would be wrong to claim that sewage, abstraction or river management alone caused the collapse.` },
    { type: 'paragraph', text: `But salmon still depend on rivers for spawning and juvenile development.` },
    { type: 'paragraph', text: `Those are areas government and regulators can influence directly.` },
    { type: 'heading', level: 2, text: `Domestic pressures remain unresolved` },
    { type: 'paragraph', text: `The Environment Agency identifies three recurring freshwater problems: pollution; low river flows; and barriers that block migration.` },
    { type: 'paragraph', text: `Salmon require cool, well-oxygenated water.` },
    { type: 'paragraph', text: `Low flows can prevent them reaching spawning areas.` },
    { type: 'paragraph', text: `Weirs and other structures can obstruct migration.` },
    { type: 'paragraph', text: `Pollution from agriculture and wastewater can damage habitat and reduce water quality.` },
    { type: 'paragraph', text: `None of those issues is new.` },
    { type: 'paragraph', text: `They were central to the strategy launched in 2016.` },
    { type: 'heading', level: 2, text: `Recovery work has been real, but not enough` },
    { type: 'paragraph', text: `The Environment Agency has carried out substantial work.` },
    { type: 'paragraph', text: `When the five-point programme was launched, the agency said 82 barriers had already been removed or altered since 2009, opening up 5,767km of river catchment.` },
    { type: 'paragraph', text: `It also said 77 unsustainable abstraction licences on salmon rivers had been removed or reduced since 2008.` },
    { type: 'paragraph', text: `Further schemes followed.` },
    { type: 'paragraph', text: `Barrier removal, habitat restoration and water-quality projects have continued for years.` },
    { type: 'paragraph', text: `Those measures cannot simply be dismissed as failure.` },
    { type: 'paragraph', text: `Without them, salmon numbers may have fallen even further.` },
    { type: 'paragraph', text: `But they have not reversed the national decline.` },
    { type: 'paragraph', text: `That is the point that matters.` },
    { type: 'heading', level: 2, text: `The new plan looks familiar` },
    { type: 'paragraph', text: `The Environment Agency is now launching another long-term recovery programme running to 2032.` },
    { type: 'paragraph', text: `It says this will include 2,282 hectares of peatland restoration; more than 800 wastewater-pollution projects; 105 migration barriers removed or improved; 252 habitat restoration sites; and 648 hectares of riverside tree planting.` },
    { type: 'paragraph', text: `Those are substantial commitments.` },
    { type: 'paragraph', text: `But the core prescription is strikingly familiar.` },
    { type: 'paragraph', text: `Improve water quality. Fix flows. Remove barriers. Restore habitat.` },
    { type: 'paragraph', text: `The same problems identified a decade ago remain at the centre of the new strategy.` },
    { type: 'paragraph', text: `That raises an obvious question.` },
    { type: 'paragraph', text: `If the Environment Agency already knew these were the main domestic pressures in 2016, why are 95 per cent of principal salmon rivers still below sustainable levels — and why did that figure worsen by seven percentage points in the space of a single year?` },
    { type: 'heading', level: 2, text: `Some projects have worked` },
    { type: 'paragraph', text: `There are local examples of recovery.` },
    { type: 'paragraph', text: `The Environment Agency points to improvements on rivers including the Trent, Ouse and Don, where better water quality and restored migration routes have helped salmon return.` },
    { type: 'paragraph', text: `That makes the wider failure harder to dismiss as inevitable.` },
    { type: 'paragraph', text: `If targeted intervention can work locally, the issue becomes one of scale, consistency and whether improvements are strong enough to overcome wider environmental pressures.` },
    { type: 'paragraph', text: `The national picture suggests they have not been.` },
    { type: 'heading', level: 2, text: `Fishing restrictions were never going to be enough` },
    { type: 'paragraph', text: `Over the past decade, the Environment Agency has also tightened restrictions on salmon fishing.` },
    { type: 'paragraph', text: `That reduced one source of pressure.` },
    { type: 'paragraph', text: `But the latest figures show that restricting anglers alone has not stabilised stocks.` },
    { type: 'paragraph', text: `That supports the agency's own argument that the larger problems lie elsewhere.` },
    { type: 'paragraph', text: `Protecting more fish from capture helps little if the river they return to is too warm, too polluted, too low or physically blocked.` },
    { type: 'heading', level: 2, text: `The statistical system could also be stronger` },
    { type: 'paragraph', text: `Earlier this year, the Office for Statistics Regulation reviewed the salmon-stock publication and recommended that officials "undertake and publish a clear evaluation of whether the Assessment of Salmon Stocks and Fisheries in England and Wales should be produced and published as official statistics" — a designation it does not currently carry.` },
    { type: 'paragraph', text: `The regulator recommended stronger publication practices, including a 12-month forward publication schedule, preannounced release dates, and clearer transparency around methods.` },
    { type: 'paragraph', text: `That does not mean the figures are wrong.` },
    { type: 'paragraph', text: `But it does mean a dataset now being used to describe a national ecological decline has room for stronger statistical governance.` },
    { type: 'paragraph', text: `The 2025 stock assessment was also updated the day after publication, on 16 September, because the original attachment contained errors.` },
    { type: 'paragraph', text: `Again, that is not evidence the central finding is unreliable.` },
    { type: 'paragraph', text: `It is a reminder that the publication process matters when the numbers are this serious.` },
    { type: 'heading', level: 2, text: `The next plan needs an outcome, not another list of projects` },
    { type: 'paragraph', text: `The new programme runs to 2032.` },
    { type: 'paragraph', text: `By then, the government and Environment Agency should be able to answer simple questions.` },
    { type: 'paragraph', text: `How many barriers were actually removed? How much peatland was restored? How many wastewater projects were completed? Did river flows improve? Did pollution incidents fall?` },
    { type: 'paragraph', text: `Most importantly: did more salmon return?` },
    { type: 'paragraph', text: `The current announcement is strong on outputs.` },
    { type: 'paragraph', text: `It lists projects, hectares, barriers and schemes.` },
    { type: 'paragraph', text: `The national outcome is still moving in the wrong direction, and moving there faster than the decade-long trend alone would suggest.` },
    { type: 'paragraph', text: `That is the measure that matters.` },
    { type: 'paragraph', text: `The Environment Agency identified the key domestic problems a decade ago.` },
    { type: 'paragraph', text: `It has spent ten years trying to address them.` },
    { type: 'paragraph', text: `Yet 95 per cent of England's principal salmon rivers are still below sustainable stock levels, up from 88 per cent only a year earlier.` },
    { type: 'paragraph', text: `The latest plan may succeed where the previous strategy did not.` },
    { type: 'paragraph', text: `But this time, the test should not be how much work was announced.` },
    { type: 'paragraph', text: `It should be whether the fish come back.` },
  ],
  evidence: {
    recordsReviewed: [
      'Environment Agency / GOV.UK, 16 September 2026: "Salmon numbers in England hit lowest level on record" — 95% figure (up from 88% previous year), historical vs current marine survival rates (15–20 per 100 down to 1–2), Trent/Ouse/Don recovery examples, 2032 programme commitments',
      'Environment Agency blog, "Restoring salmon stocks: our journey to a new approach", 6 May 2016 — five points of the original strategy; 82 barriers removed/altered since 2009 (5,767km opened); 77 abstraction licences removed/reduced since 2008',
      'Environment Agency blog, "England\'s salmon stocks: what the latest data tells us", 17 September 2026 — three recurring domestic freshwater pressures (pollution, low flows, barriers); detailed 2026–2032 programme figures (2,282ha peatland, 800+ wastewater projects, 105 barriers, 252 habitat sites, 648ha tree planting)',
      'GOV.UK, "Salmonid and freshwater fisheries statistics for England and Wales 2020" — 2006 (40%), 2015 (19%) and 2020 (12%) proportions classified as "not at risk" or "probably not at risk"',
      'Office for Statistics Regulation, review of the Assessment of Salmon Stocks and Fisheries publication, 18 May 2026 — recommendation to evaluate official-statistics designation; publication-practice recommendations (forward schedule, preannounced release dates, methods transparency)',
      'GOV.UK, "Assessment of salmon stocks in England and Wales in 2025" — correction history: published 15 September 2026, attachment replaced 16 September 2026 due to errors',
    ],
    lastChecked: '30 September 2026',
  },
};

export default piece;
