import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'xm7co0hssx',
  kicker: 'Child Protection',
  headline: `Police Are Reopening Grooming Cases They Previously Closed`,
  standfirst: `On 15 June, the National Crime Agency said police forces had been ordered to reopen previously closed child sexual exploitation cases in eight force areas because reviewers had found possible lines of inquiry that had not been exhausted. The cases form part of Operation Beaconport, the national police review created after Baroness Louise Casey's 2025 audit of group-based child sexual exploitation.`,
  publishedAt: '2026-06-24',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `On 15 June, the National Crime Agency said police forces had been ordered to reopen previously closed child sexual exploitation cases in eight force areas because reviewers had found possible lines of inquiry that had not been exhausted.` },
    { type: 'paragraph', text: `The cases form part of Operation Beaconport, the national police review created after Baroness Louise Casey's 2025 audit of group-based child sexual exploitation.` },
    { type: 'paragraph', text: `Police forces were ordered to search 15 years of records for cases involving two or more suspects where police or prosecutors had previously decided to take no further action.` },
    { type: 'paragraph', text: `By November, 1,273 cases had been referred to the operation. Of those, 236 involved allegations of rape.` },
    { type: 'paragraph', text: `The NCA is not saying that all those investigations were wrongly closed.` },
    { type: 'paragraph', text: `Each case is being examined to establish whether the original decision was justified and whether anything can still be investigated. Reopening a case does not establish that an offence occurred or that a suspect is guilty.` },
    { type: 'paragraph', text: `But the first results have already identified cases in eight police force areas with possible viable lines of inquiry. Separate analysis of force data has also identified new suspected offending in four areas, which is now being investigated locally.` },
    { type: 'paragraph', text: `That review is taking place because the country still cannot say reliably how many children have been subjected to group-based sexual exploitation.` },
    { type: 'paragraph', text: `Casey's national audit reached that conclusion in June 2025 after examining police, local authority, health and criminal justice data.` },
    { type: 'paragraph', text: `There is no national dataset that cleanly records what the public generally means by grooming gangs. Definitions have changed, police systems do not consistently talk to each other and ethnicity is missing for most recorded suspects.` },
    { type: 'paragraph', text: `Casey said it was a failure of public policy that, after years of inquiries and scandals, the true scale remained unknown.` },
    { type: 'paragraph', text: `Rotherham shows what can happen when information exists locally but institutions fail to act on it.` },
    { type: 'paragraph', text: `Alexis Jay's 2014 inquiry conservatively estimated that at least 1,400 children were sexually exploited between 1997 and 2013.` },
    { type: 'paragraph', text: `The report found that warnings had reached the council and South Yorkshire Police over many years. Children known to services were being sexually exploited, information about suspected offenders was being supplied and professionals working directly with victims were raising concerns.` },
    { type: 'paragraph', text: `The response was repeatedly inadequate.` },
    { type: 'paragraph', text: `A government inspection led by Louise Casey the following year found widespread governance failures at Rotherham Council and what it described as denial about the scale of the problem. The council's political leadership resigned and central government appointed commissioners who took control of its executive functions and licensing powers.` },
    { type: 'paragraph', text: `The elected council itself was not abolished, as is sometimes claimed. Its executive powers were transferred to government-appointed commissioners and were later returned as the authority improved.` },
    { type: 'paragraph', text: `The National Crime Agency subsequently took responsibility for the major historic criminal investigation.` },
    { type: 'paragraph', text: `Operation Stovewood identified more than 1,100 victims and, by March 2025, had secured 42 convictions.` },
    { type: 'paragraph', text: `Rotherham was not an isolated example of an investigation being allowed to fail.` },
    { type: 'paragraph', text: `Operation Augusta was established in Manchester in 2004 after concerns that vulnerable girls, many living in local authority care, were being sexually exploited.` },
    { type: 'paragraph', text: `It identified 26 potential victims.` },
    { type: 'paragraph', text: `The operation was closed in July 2005.` },
    { type: 'paragraph', text: `An independent review published years later found that its closure had been driven by the withdrawal of police resources rather than by investigators establishing that every reasonable line of inquiry had been completed. Reviewers said they could give no assurance that appropriate action had been taken to protect 16 of the children they examined.` },
    { type: 'paragraph', text: `The Independent Office for Police Conduct later investigated how Augusta had been closed.` },
    { type: 'paragraph', text: `It could not establish who ultimately made the decision or why because important records could not be found. It found no evidence justifying misconduct proceedings against the three former senior officers referred to it, but identified problems with record keeping, resourcing and the review of investigations.` },
    { type: 'paragraph', text: `The recurring problem was not simply that nobody had investigated child sexual exploitation.` },
    { type: 'paragraph', text: `Britain has produced inquiries, reviews, strategies and guidance on it for years.` },
    { type: 'paragraph', text: `Casey's 2025 audit examined that history and found the same issues repeatedly appearing: information not shared properly, inconsistent training, poor understanding of vulnerability, inadequate data and weak recording of perpetrators.` },
    { type: 'paragraph', text: `Her description was of a cycle in which scandal produced a burst of institutional attention without sustained improvement.` },
    { type: 'paragraph', text: `The Independent Inquiry into Child Sexual Abuse was one of the largest attempts to break that cycle.` },
    { type: 'paragraph', text: `It ran for seven years and published its final report in 2022 with 20 recommendations.` },
    { type: 'paragraph', text: `In January 2025, the Home Office told Parliament that none of those 20 final recommendations had been implemented by the previous government.` },
    { type: 'paragraph', text: `That is no longer the full position.` },
    { type: 'paragraph', text: `The Crime and Policing Act 2026 contains measures implementing parts of the IICSA programme, including a statutory duty for specified professionals to report suspected child sexual offences and a new aggravating factor where child sexual offences involve grooming.` },
    { type: 'paragraph', text: `As of 24 June, the reporting duty had been legislated for but had not yet been brought into force. The grooming aggravating factor was due to commence on 29 June.` },
    { type: 'paragraph', text: `The ethnicity of offenders has become the most contested part of the national argument.` },
    { type: 'paragraph', text: `The available evidence supports neither pretending the question does not exist nor claiming that national data proves one ethnic group dominates this form of offending.` },
    { type: 'paragraph', text: `Casey's audit found that ethnicity was not recorded for around two-thirds of perpetrators in the national data it examined. It concluded that the information was too incomplete to draw a reliable national conclusion.` },
    { type: 'paragraph', text: `The local evidence was different.` },
    { type: 'paragraph', text: `Casey found disproportionate numbers of men from Asian ethnic backgrounds among suspects in group-based child sexual exploitation data from Greater Manchester, South Yorkshire and West Yorkshire.` },
    { type: 'paragraph', text: `Operation Stovewood provided one of the clearest examples. Of 323 designated suspects in its Rotherham investigations, nearly two-thirds were recorded as being from a Pakistani ethnic background. Nearly two-thirds of the 42 people then convicted through the operation were also recorded as Pakistani.` },
    { type: 'paragraph', text: `Those figures describe Rotherham. They cannot properly be converted into a national percentage.` },
    { type: 'paragraph', text: `A 2020 Home Office paper had said the limited available research suggested that most group-based CSE offenders were White, while also acknowledging poor data, missing ethnicity records and studies showing over-representation of Asian and Black offenders.` },
    { type: 'paragraph', text: `The same paper said it was not possible to determine whether particular ethnic groups were over-represented.` },
    { type: 'paragraph', text: `Casey later criticised the way its conclusion about White offenders had been repeated as though the underlying evidence were definitive.` },
    { type: 'paragraph', text: `Her 2025 audit was unusually direct on the institutional handling of the subject. It said ethnicity had been "shied away from" and that incomplete evidence had been used to dismiss concerns about Asian grooming gangs instead of establishing what was actually happening.` },
    { type: 'paragraph', text: `Casey separately said in an interview after publication that, while examining archived material in Rotherham, she found the word "Pakistani" had been covered with correction fluid in a child's file.` },
    { type: 'paragraph', text: `The audit was equally clear about the limits of that evidence. National ethnicity data remained too poor for a national finding, and Casey warned against allowing an argument about ethnicity to eclipse the children being abused.` },
    { type: 'paragraph', text: `The government's response to her audit has gone beyond another review.` },
    { type: 'paragraph', text: `Operation Beaconport is now examining old police and CPS decisions. A separate statutory Independent Inquiry into Grooming Gangs has been established under Baroness Anne Longfield.` },
    { type: 'paragraph', text: `Its final terms of reference were published on 31 March.` },
    { type: 'paragraph', text: `The inquiry has powers to compel witnesses and documents, will examine failures and possible obstruction by statutory bodies and has been specifically instructed to consider the relevance of ethnicity, religion and culture to offending and institutional responses.` },
    { type: 'paragraph', text: `It has a maximum budget of £65 million and is supposed to finish within three years.` },
    { type: 'paragraph', text: `The inquiry exists in part because Casey concluded that local institutions had too often been reluctant to investigate themselves.` },
    { type: 'paragraph', text: `Her audit said police forces and councils had sometimes resisted independent scrutiny for years, with reviews finally happening only after campaigning by victims, journalists and others.` },
    { type: 'paragraph', text: `That history makes Operation Beaconport's current work more significant than another promise to learn lessons.` },
    { type: 'paragraph', text: `Its task is not simply to write another report about why investigations failed.` },
    { type: 'paragraph', text: `Police are going back into cases where a decision was made not to proceed and asking whether that decision can still be defended.` },
    { type: 'paragraph', text: `By 15 June, cases from eight police force areas had already been sent back to forces because reviewers believed viable lines of inquiry might remain.` },
    { type: 'paragraph', text: `The national inquiry will try to establish why institutions repeatedly failed.` },
    { type: 'paragraph', text: `The police review is testing whether some of the cases they closed can still be prosecuted.` },
  ],
  evidence: {
    recordsReviewed: [
      `National Crime Agency, Operation Beaconport: Update on the national investigation into group-based child sexual abuse, 15 June 2026: confirms that cases from eight force areas had been identified as potentially containing viable lines of inquiry and directed back to forces for reopening, and that new suspected offending had been identified in four force areas`,
      `National Crime Agency, Operation Beaconport: Hundreds of child abuse cases under review, 5 November 2025: supports the 1,273 referred cases, including 236 involving allegations of rape, and sets out the criteria for the national review of cases previously closed with no further action`,
      `Baroness Louise Casey, National Audit on Group-based Child Sexual Exploitation and Abuse, June 2025: supports the findings on inadequate national data, ethnicity recording, the repeated cycle of institutional failure, local evidence of disproportionate Asian offending in three force areas and the Operation Stovewood ethnicity figures`,
      `Professor Alexis Jay, Independent Inquiry into Child Sexual Exploitation in Rotherham 1997-2013, August 2014: supports the conservative estimate that at least 1,400 children were sexually exploited in Rotherham and the findings on failures by the council, police and other agencies`,
      `Department for Communities and Local Government, Rotherham intervention documents, 2015: supports Louise Casey's findings and the appointment of five commissioners to exercise the council's executive and licensing functions; the elected authority itself was not abolished`,
      `National Crime Agency, Operation Stovewood, March 2025: confirms more than 1,100 identified victims and 42 convictions secured through the Rotherham investigation by that date`,
      `Greater Manchester Combined Authority, Independent Assurance Review of Operation Augusta: supports the finding that Augusta was prematurely closed after police resources were withdrawn and that reviewers could not be assured that 16 children in their sample had been adequately protected`,
      `Independent Office for Police Conduct, Operation Augusta investigation: confirms that investigators could not establish who ultimately decided to close the operation or the rationale, found insufficient evidence of misconduct by the three former senior officers referred, and identified organisational lessons on records, resourcing and investigative review`,
      `Home Office written parliamentary answer, 14 January 2025: confirms the government's statement that none of the 20 recommendations in IICSA's 2022 final report had been implemented by the previous government at that point`,
      `Crime and Policing Act 2026: supports the new grooming aggravating factor and the legislated mandatory reporting duty; the reporting provisions had not yet been commenced by 24 June 2026`,
      `Home Office, Group-based Child Sexual Exploitation: Characteristics of Offending, 2020: supports the earlier government's findings on the poor quality of ethnicity data, evidence pointing in different directions and its conclusion that firm national comparisons could not be made`,
      `Home Office, Independent Inquiry into Grooming Gangs: final terms of reference, 31 March 2026: supports the inquiry's statutory remit, examination of ethnicity, religion and culture, three-year limit and £65 million budget`,
    ],
    lastChecked: '5 October 2026',
  },
};

export default piece;
