import type { EditorialEntry } from './types';

// Long-form account of the grooming gangs scandal and the institutional and
// political failures around it. Every specific figure, quote and date
// independently fact-checked against non-partisan sources (the Jay Report,
// Baroness Casey's 2025 national audit, the NCA, GMP, House of Commons
// Library, GOV.UK, Hansard and contemporaneous reporting).

const piece: EditorialEntry = {
  slug: 'xm7co0hssx',
  kicker: 'Investigation',
  headline: 'The Grooming Gangs Scandal: When the State Looked the Other Way',
  standfirst:
    'Britain identified the problem again and again, and failed to stop it again and again. The institutions paid to protect children failed. The individuals they tried to silence did not.',
  publishedAt: '2026-06-24',
  authorByline: "opengovt",
  body: [
    { type: 'paragraph', text: `The most disturbing fact about the grooming gangs scandal is not that organised child sexual exploitation existed. Every society contains predators. The disturbing fact is that Britain repeatedly identified the problem and repeatedly failed to stop it. Victims spoke to police officers. Youth workers filed reports. Teachers raised concerns. Social workers documented patterns of abuse. Researchers were hired specifically to investigate and warned local authorities what was happening. The abuse continued for years.` },
    { type: 'paragraph', text: `In Rotherham, between 1997 and 2013, at least 1,400 children were sexually exploited. Girls as young as 11 were groomed, plied with alcohol and drugs, raped, trafficked between towns and threatened with violence. The Jay Report, published in August 2014, found that the abuse had been known about at multiple levels of the council and police for over a decade. Researcher Angie Heal, a strategic drugs analyst hired by South Yorkshire Police, warned local authorities about child exploitation between 2002 and 2007. She later described it as "the biggest child protection scandal in UK history." The Jay Report found that both the council and South Yorkshire Police failed to act on what they knew, and that the police gave the abuse no priority and treated many of the victims with contempt. The Jay Report documented cases where known suspects, including family perpetrator groups, were not charged despite the police having prior information.` },
    { type: 'paragraph', text: `In January 2015, Louise Casey inspected Rotherham Council on behalf of the government. She concluded it was "not fit for purpose" and described a culture of bullying, sexism, covering up information and silencing whistleblowers. The council had been under continuous Labour control since 1974. In February 2015, the government disbanded the elected council and replaced it with five government appointed commissioners. In her 2025 national audit, Casey reported finding a case file where the word "Pakistani" had been tippexed out.` },
    { type: 'paragraph', text: `Operation Stovewood, the National Crime Agency's investigation into Rotherham, identified 323 child sexual abuse suspects and secured 42 convictions. Baroness Casey's 2025 audit found that nearly two thirds of those suspects and convicted individuals were of Pakistani heritage. In July 2025, five survivors told investigators they had been raped by police officers when they were as young as 12. Three former officers were arrested. Criminal proceedings are ongoing and expected to continue until 2027. The people meant to protect the children are alleged to have been among those abusing them.` },
    { type: 'paragraph', text: `Rotherham was not unique. In Rochdale, nine men were convicted in 2012. Seven more were convicted in June 2025 for crimes committed between 2001 and 2006. It took 20 years to bring them to justice. In Telford, an independent inquiry estimated over 1,000 victims. In Greater Manchester, Operation Augusta, which was investigating child sexual exploitation, was prematurely shut down. In Oxford, Oldham, Newcastle, Huddersfield, Halifax, Peterborough, Derby, Banbury, Bristol and Aylesbury, similar patterns emerged. Different towns. Different agencies. Different leadership teams. The same outcome. Children were abused while institutions delayed, deflected responsibility, protected reputations and failed to act.` },
    { type: 'paragraph', text: `The breakthroughs came not from institutions but from individuals the institutions tried to silence. Sara Rowbotham ran Rochdale's NHS crisis intervention team and between 2005 and 2011 made 181 referrals to police and social services about patterns of child sexual exploitation. She was told the witnesses were not reliable. Maggie Oliver, a GMP detective investigating Rochdale, pushed for action and was dismissed by her bosses as "an emotional woman." She resigned from the force and set up the Maggie Oliver Foundation to support victims. Andrew Norfolk, a journalist at The Times, had been investigating grooming networks across northern England since 2003. His January 2011 investigation, headlined "Revealed: conspiracy of silence on UK sex gangs," was the first national exposure. Rotherham Council tried to get a High Court injunction to stop him publishing an unredacted serious case review. Michael Gove intervened and the council withdrew its legal action. Norfolk's September 2012 report, based on 200 documents leaked by Jayne Senior, a youth worker who had spent 14 years documenting evidence of organised grooming in Rotherham, exposed the full scale of the scandal. Senior had passed names of perpetrators to police and council repeatedly and been told to stop. A police officer told her they had been instructed to "take this down the honour killing route" and could not mention child sexual exploitation. Her colleague Adele Weir told the Home Affairs Committee that someone broke into the Risky Business office and removed all the data. When Weir raised concerns about Asian men, she was sent on a two day ethnicity and diversity course. Senior was later awarded an MBE.` },
    { type: 'paragraph', text: `Nazir Afzal changed the course of the scandal. Born in Birmingham to Pakistani parents, he became Chief Crown Prosecutor for North West England in 2011. One of his first decisions was to overturn the CPS's earlier refusal to prosecute the Rochdale grooming gang. The CPS had declined to charge two men in 2009, ruling the main victim was not a credible witness. Afzal reviewed six hours of her video testimony and took what he called "an immediate decision" to prosecute. He said: "I believed her. I figured, well, if I believe her, why can't a jury believe her." All nine men charged were convicted. Afzal received death threats. He was targeted by the English Defence League and doorstepped by Nick Griffin. Members of his own community also attacked him. He responded: "If you are getting it from both sides, you are probably getting something right." He went on to lead nationally on child sexual abuse and violence against women. He is now Chancellor of the University of Manchester.` },
    { type: 'paragraph', text: `Alexis Jay, former chief social work adviser to the Scottish Government, was commissioned by Rotherham Council in 2013 to conduct the independent inquiry that would define the scandal. Her report, published in August 2014, estimated at least 1,400 children had been sexually exploited in Rotherham between 1997 and 2013. It found that the abuse had been known about at multiple levels of the council and police for over a decade. Jay later chaired the Independent Inquiry into Child Sexual Abuse, which took seven years and published 20 recommendations in 2022. By January 2025, not one of those recommendations had been implemented. The woman who documented the scale of the failure then spent seven years documenting the national failure, and the system ignored both reports.` },
    { type: 'paragraph', text: `Sammy Woodhouse became the first Rotherham survivor to waive her anonymity and campaign publicly. Her abuser, Arshid Hussain, was sentenced to 35 years. Ann Cryer, Labour MP for Keighley, was one of the first politicians to speak out publicly, warning that Asian men were targeting teenage girls outside schools. She was accused of racism for doing so.` },
    { type: 'paragraph', text: `The people who broke this scandal were not ministers, chief constables or council leaders. They were a crisis worker who made 181 referrals and was ignored, a detective who was called emotional for caring, a journalist who was taken to court for reporting the truth, a youth worker who documented abuse for 14 years and was told to stop, a prosecutor who believed a victim the system had dismissed, an academic who produced two reports the system failed to act on, and the survivors who refused to be silent. The institutions that were paid to protect children failed. The individuals who were not paid to do so did not.` },
    { type: 'pullQuote', text: `The institutions that were paid to protect children failed. The individuals who were not paid to do so did not.` },
    { type: 'paragraph', text: `The ethnicity question has been the most politically explosive element of the debate and the one most systematically avoided by the institutions responsible for addressing it. In two thirds of cases nationally, the ethnicity of perpetrators was not recorded. Baroness Casey's 2025 national audit found that the data was "not sufficient to allow any conclusions to be drawn at the national level" but that local data from three police forces, Greater Manchester, South Yorkshire and West Yorkshire, showed "disproportionate numbers of Asian men" were involved in group based child sexual exploitation. Casey wrote that the ethnicity of perpetrators had been "shied away from" and that "flawed data is used repeatedly to dismiss claims about Asian grooming gangs as sensationalised, biased or untrue." A 2020 government report under the Conservatives had concluded that offenders were "most commonly white" in line with national demographics. Priti Patel said it had been "difficult to draw conclusions." Casey called the data behind that claim insufficient and the framing misleading: "In a population with over 80 percent of people of White ethnicity, it should always be a significant issue when people from a White background are not in the majority of victims or perpetrators of crime."` },
    { type: 'paragraph', text: `The political failure to confront the scandal compounded the institutional failure to prevent it. The Independent Inquiry into Child Sexual Abuse, established in 2014, took seven years and published its final report with 20 recommendations in 2022. By January 2025, none of those recommendations had been implemented. Not one. In seven years of evidence gathering, testimony and analysis, the state produced a report and then ignored it. The government resisted calls for a specific national inquiry into grooming gangs for six months, driven in part by social media pressure from Elon Musk in January 2025. On 14 June 2025, Keir Starmer announced a full national statutory inquiry. In December 2025, Home Secretary Shabana Mahmood published draft terms of reference and appointed Baroness Anne Longfield as chair. The final terms of reference were published in March 2026 and the inquiry formally began in April 2026, with a budget of £65 million, a three year limit and a mandate to examine the ethnicity, religion and culture of both perpetrators and victims.` },
    { type: 'paragraph', text: `After police forces were asked to review cases involving grooming and child sexual exploitation that had been closed without further action, more than 1,200 cases had been identified for formal review, including over 200 high priority cases involving allegations of rape.` },
    { type: 'paragraph', text: `Casey herself changed her mind about the need for a national inquiry. She had previously rejected the idea. She reversed her position after finding that many local councils had failed to set up their own inquiries and that some organisations had refused to cooperate with her investigators. She wrote: "If Rotherham were to happen again today it would start online."` },
    { type: 'paragraph', text: `A mandatory duty to report child sexual abuse has been introduced through the Crime and Policing Act 2026. A new statutory aggravating factor for grooming has been created so that sentences match the severity of the crimes. These are overdue measures. They arrive more than a decade after the Jay Report and more than two decades after the first warnings were raised.` },
    { type: 'paragraph', text: `The gangs committed the crimes. The institutions failed to stop them. Police treated victims as troublemakers. Councils prioritised reputation over safeguarding. Data on ethnicity was suppressed, tippexed out or simply not collected. A seven year national inquiry produced 20 recommendations and none were implemented. Researchers who warned what was happening were ignored. Whistleblowers were silenced. Children who reported abuse were not believed. And when the political system was finally forced to act, it took six months of public pressure, social media intervention from the world's richest man and the publication of a national audit before a government that had been in office for a year agreed to hold the inquiry that campaigners had been demanding for over a decade.` },
    { type: 'paragraph', text: `At least 1,400 children were exploited in Rotherham alone. Similar patterns have been identified in towns across England. The true national scale remains unknown because the data was never properly collected. Until Britain builds a system that rewards intervention rather than avoidance, accountability rather than apology, and action rather than review, there is no guarantee the next generation of vulnerable children will be better protected than the last.` },
  ],
};

export default piece;
