import type { EditorialEntry } from './types';

const piece: EditorialEntry = {
  slug: 'zt7m4kq9xw',
  kicker: 'Commentary',
  headline: `They Call Farage's Clacton Vote a Stunt. So Why Are They Handing Him the Stage?`,
  standfirst: `Nigel Farage resigned as MP for Clacton while under parliamentary standards investigation and announced he would fight the resulting by-election. Labour, the Conservatives, Liberal Democrats, Greens and Restore Britain have all declined to stand against him. They say the election is a stunt. By refusing to fight it, they have given him the stage almost to himself.`,
  publishedAt: '2026-07-16',
  authorByline: 'opengovt',
  body: [
    { type: 'paragraph', text: `Nigel Farage resigned as MP for Clacton on 8 July while the Parliamentary Commissioner for Standards was investigating whether he should have registered a £5 million gift from cryptocurrency investor Christopher Harborne.` },
    { type: 'paragraph', text: `Farage denies breaking parliamentary rules.` },
    { type: 'paragraph', text: `Rather than wait for the investigation to reach a conclusion, he resigned his seat and announced that he would fight the resulting by-election.` },
    { type: 'paragraph', text: `His argument is simple. The people who elected him should judge his conduct.` },
    { type: 'paragraph', text: `Labour will not stand against him. Neither will the Conservatives, Liberal Democrats, Greens or Restore Britain.` },
    { type: 'paragraph', text: `They have different ways of describing what Farage has done. Kemi Badenoch called it a "fake by-election", accusing Farage of causing it to distract attention from the parliamentary scrutiny and saying the Conservatives would fight any later "real by-election". Keir Starmer separately called Farage's decision "a desperate stunt". The Greens called it a political circus. Ed Davey described it as a vanity project. Restore Britain said it would not participate in a Reform-sponsored media circus.` },
    { type: 'paragraph', text: `They may be right.` },
    { type: 'paragraph', text: `Farage has taken a parliamentary standards dispute and moved the action somewhere much more favourable to him.` },
    { type: 'paragraph', text: `He gets a campaign. He gets rallies, cameras and interviews. He gets to replace a question about the registration rules of the House of Commons with the political story he has spent much of his career telling: Nigel Farage against the establishment.` },
    { type: 'paragraph', text: `But the decision by the major parties to stay away makes that strategy easier.` },
    { type: 'paragraph', text: `The standards investigation has not disappeared because Farage resigned.` },
    { type: 'paragraph', text: `The House of Commons procedural rules say that when an MP leaves Parliament while an investigation is under way, the Commissioner suspends the case. If the MP is re-elected, the investigation resumes.` },
    { type: 'paragraph', text: `So the August by-election cannot clear Farage of anything.` },
    { type: 'paragraph', text: `Only the parliamentary process can decide whether he breached the MPs' Code.` },
    { type: 'paragraph', text: `If Farage wins Clacton, however, he will have something politically valuable that no standards report can provide: another electoral mandate.` },
    { type: 'paragraph', text: `He has already framed the contest as "the people versus the establishment".` },
    { type: 'paragraph', text: `His opponents appear to think the best way to deny him that spectacle is not to participate.` },
    { type: 'paragraph', text: `That is understandable as campaign strategy.` },
    { type: 'paragraph', text: `It is harder to defend as democratic strategy.` },
    { type: 'paragraph', text: `Clacton voted for Farage in 2024, but almost 54 per cent of those who voted chose somebody else. The Conservatives received 12,820 votes, Labour 7,448, the Liberal Democrats 2,016 and the Greens 1,935. Farage won 21,225 votes and a majority of 8,405.` },
    { type: 'paragraph', text: `Those voters have not stopped existing because the major parties think the by-election is ridiculous.` },
    { type: 'paragraph', text: `Labour supporters should be able to vote Labour.` },
    { type: 'paragraph', text: `Conservatives should be able to decide whether they want the party that represented Clacton before Farage.` },
    { type: 'paragraph', text: `Liberal Democrats and Greens should be prepared to make their case even where they expect to lose.` },
    { type: 'paragraph', text: `Political parties spend general elections telling people that every constituency matters. Apparently the principle becomes more negotiable when a seat looks unwinnable and the opponent is likely to turn the campaign into television.` },
    { type: 'paragraph', text: `Farage did not have the power to order Labour or the Conservatives off the ballot paper.` },
    { type: 'paragraph', text: `They chose to leave.` },
    { type: 'paragraph', text: `The Liberal Democrats went further. Ed Davey called on all parties to stand aside, arguing that contesting the by-election would give oxygen to Farage's "vanity project".` },
    { type: 'paragraph', text: `The Greens said participating would help legitimise a contest designed around Farage rather than local residents.` },
    { type: 'paragraph', text: `The Conservatives have said they would stand in a later by-election if the standards process ultimately resulted in Farage losing his seat.` },
    { type: 'paragraph', text: `Badenoch said her party would contest the "real by-election" if the investigation found a breach and Parliament decided Farage's seat should be vacated.` },
    { type: 'paragraph', text: `Restore Britain has taken essentially the same position. Rupert Lowe said it would contest a second Clacton by-election if one followed the investigation, but not the present contest.` },
    { type: 'paragraph', text: `There is a problem with that logic.` },
    { type: 'paragraph', text: `There may never be a second election.` },
    { type: 'paragraph', text: `The Commissioner could conclude that Farage did not breach the rules. A breach could be found but dealt with without a sanction capable of triggering recall. Parliament might never reach the point at which another election is required.` },
    { type: 'paragraph', text: `The only Clacton election definitely happening is the one on 13 August.` },
    { type: 'paragraph', text: `And the main parties have decided not to contest it.` },
    { type: 'paragraph', text: `Farage's original resignation was not triggered by a parliamentary finding against him.` },
    { type: 'paragraph', text: `The confirmed investigation concerns whether the £5 million Harborne gift should have appeared in the Register of Members' Financial Interests. Farage says the money was provided for his personal security and did not fall within the registration rules.` },
    { type: 'paragraph', text: `Separate questions have been raised about financial and other support associated with his longtime associate George Cottrell. Complaints were submitted to the Commissioner, but that should not be presented as a second confirmed formal investigation without an official announcement from the Commissioner's office.` },
    { type: 'paragraph', text: `The confirmed Harborne inquiry is serious enough without upgrading allegations into findings.` },
    { type: 'paragraph', text: `The electorate cannot resolve it.` },
    { type: 'paragraph', text: `Clacton voters do not have the Commissioner's evidence. They cannot determine whether a particular interest met the technical registration requirements. An election is not a substitute standards tribunal.` },
    { type: 'paragraph', text: `Farage knows that.` },
    { type: 'paragraph', text: `His opponents know it too.` },
    { type: 'paragraph', text: `The real argument for contesting the by-election is therefore not that Clacton should decide whether Farage broke parliamentary rules.` },
    { type: 'paragraph', text: `It is that when an MP voluntarily asks his constituents for another mandate, the parties that aspire to govern Britain should be willing to challenge him for it.` },
    { type: 'paragraph', text: `There is precedent for doing the opposite.` },
    { type: 'paragraph', text: `In 2008, Conservative shadow home secretary David Davis resigned his Haltemprice and Howden seat to force a by-election over the Labour government's proposal to allow terrorist suspects to be detained for up to 42 days without charge.` },
    { type: 'paragraph', text: `Labour called the election a stunt and refused to stand. The Liberal Democrats also stayed away because they agreed with Davis on the underlying civil-liberties issue.` },
    { type: 'paragraph', text: `Davis then faced 25 opponents, none from Labour or the Liberal Democrats.` },
    { type: 'paragraph', text: `He won 17,113 votes and 72 per cent of the poll. Turnout collapsed from 70.2 per cent at the previous general election to 34.5 per cent.` },
    { type: 'paragraph', text: `Davis called the result a stunning victory.` },
    { type: 'paragraph', text: `It proved that he could comfortably win a Conservative seat in an election from which his two principal opponents had removed themselves.` },
    { type: 'paragraph', text: `Eight years later Zac Goldsmith tried something similar and received a much more meaningful test.` },
    { type: 'paragraph', text: `Goldsmith resigned as Conservative MP for Richmond Park after the government backed expansion at Heathrow. He stood again as an independent. The Conservatives did not field a candidate against him.` },
    { type: 'paragraph', text: `The Liberal Democrats did.` },
    { type: 'paragraph', text: `Sarah Olney won 20,510 votes to Goldsmith's 18,638, overturning his previous majority and removing him from Parliament.` },
    { type: 'paragraph', text: `Goldsmith asked his constituents for another mandate and somebody capable of beating him turned up to challenge him.` },
    { type: 'paragraph', text: `That is what is missing in Clacton.` },
    { type: 'paragraph', text: `Count Binface has declared his candidacy and will ensure the contest receives exactly the sort of coverage the other parties say they want to deny Farage. Laurence Fox and candidates from smaller parties and independents have also entered or announced plans to enter the race.` },
    { type: 'paragraph', text: `Nominations do not close until 17 July, so the final ballot paper is not yet known.` },
    { type: 'paragraph', text: `But the central political decision already is.` },
    { type: 'paragraph', text: `Labour, Conservatives, Liberal Democrats, Greens and Restore Britain have all announced that their names will not be on it.` },
    { type: 'paragraph', text: `Staying away may deny Farage a conventional party contest.` },
    { type: 'paragraph', text: `It also denies voters a conventional party choice.` },
    { type: 'paragraph', text: `And it allows Farage to make an argument his opponents should have seen coming.` },
    { type: 'paragraph', text: `He says the political establishment attacks him but is frightened to face him.` },
    { type: 'paragraph', text: `Now Labour and the Conservatives will spend the campaign explaining why refusing to stand against him proves the opposite.` },
    { type: 'paragraph', text: `There was another option.` },
    { type: 'paragraph', text: `They could have called the election a stunt and fought it anyway.` },
    { type: 'paragraph', text: `They could have asked Farage what happened to the £5 million, challenged his record as Clacton's MP and attacked his decision to create an election while the standards inquiry was unfinished.` },
    { type: 'paragraph', text: `They could have forced him to defend himself against candidates capable of taking thousands of votes from him rather than leaving that work to independents and smaller parties.` },
    { type: 'paragraph', text: `If he won that contest convincingly, his opponents would at least know what Clacton had chosen when presented with the alternatives.` },
    { type: 'paragraph', text: `If he lost, the voters would have delivered the political verdict he asked them for.` },
    { type: 'paragraph', text: `Instead, the largest parties have chosen not to find out.` },
    { type: 'paragraph', text: `Farage cannot use an election victory to erase a parliamentary standards investigation. If he returns to the Commons, that investigation resumes.` },
    { type: 'paragraph', text: `But politics does not operate only through procedural findings.` },
    { type: 'paragraph', text: `If he wins after Labour, the Conservatives and Liberal Democrats have declined to put candidates in front of him, Farage will be able to say that his opponents condemned his conduct everywhere except the one place where Clacton voters could choose between them.` },
    { type: 'paragraph', text: `They call the election a stunt.` },
    { type: 'paragraph', text: `By refusing to fight it, they have given Farage the stage almost to himself.` },
  ],
  evidence: {
    recordsReviewed: [
      `HM Treasury, appointment to the Manor of Northstead, 8 July 2026: confirms Farage's formal resignation from the House of Commons`,
      `House of Commons, Procedural Protocol in respect of the Code of Conduct: states that an investigation is suspended when an MP ceases to be a Member and resumes if that Member is re-elected`,
      `UK Parliament, Parliamentary Commissioner for Standards: records the formal Rule 5 investigation into Nigel Farage concerning an alleged failure to register an interest, opened on 13 May 2026`,
      `ITV News, Clacton by-election, 8 and 10 July 2026: records Farage's decision to seek re-election, the 13 August polling date, the boycott by major parties and the suspension of the standards investigation following his resignation`,
      `Conservative Party/LBC, Kemi Badenoch response to Farage's resignation: records Badenoch describing the contest as a "fake by-election", contrasting it with any subsequent "real by-election", and accusing Farage of running away from scrutiny`,
      `Keir Starmer, remarks at the NATO summit in Ankara, July 2026: records the Prime Minister describing Farage's resignation and by-election as "a desperate stunt"`,
      `Liberal Democrats, Ed Davey statements, 7 July 2026: records the party's call for other parties to stand aside and its description of the contest as a vanity project`,
      `Green Party of England and Wales, 7 July 2026: records the party's decision not to stand and its reasons for refusing to participate`,
      `Restore Britain statement, reported 7 July 2026: records its decision to stay out of the present election while saying it would fight a subsequent Clacton contest following the parliamentary process`,
      `UK Parliament and contemporary reporting, Haltemprice and Howden by-election 2008: records David Davis's resignation over 42-day detention, the absence of Labour and Liberal Democrat candidates and his subsequent victory`,
      `UK Parliament, Richmond Park by-election, 1 December 2016: records Sarah Olney defeating Zac Goldsmith by 20,510 votes to 18,638 after Goldsmith resigned and stood as an independent`,
    ],
    lastChecked: '5 October 2026',
  },
};

export default piece;
