export const govukSlugs: Record<string, string> = {
  'treasury': 'hm-treasury',
  'home-office': 'home-office',
  'health': 'department-of-health-and-social-care',
  'energy': 'department-for-energy-security-and-net-zero',
  'education': 'department-for-education',
  'work-pensions': 'department-for-work-pensions',
  'transport': 'department-for-transport',
  'environment': 'department-for-environment-food-rural-affairs',
  'business-trade': 'department-for-business-innovation-science-and-trade',
  'housing': 'ministry-of-housing-communities-local-government',
  'justice': 'ministry-of-justice',
  'defence': 'ministry-of-defence',
  'culture': 'department-for-digital-culture-media-and-sport',
  'cabinet-office': 'cabinet-office',
  'foreign-office': 'foreign-commonwealth-development-office',
  'attorney-general': 'attorney-generals-office',
  'scotland-office': 'scotland-office',
  'wales-office': 'wales-office',
  'northern-ireland-office': 'northern-ireland-office',
  'commons-leader': 'the-office-of-the-leader-of-the-house-of-commons',
  'lords-leader': 'office-of-the-leader-of-the-house-of-lords',
  'advocate-general': 'office-of-the-advocate-general-for-scotland',
  'ukef': 'uk-export-finance',
};
